#undef mk_sl_cui_inl_def_name
#undef mk_sl_cui_inl_def_base_type
#undef mk_sl_cui_inl_def_base_name
#undef mk_sl_cui_inl_def_base_bits
#undef mk_sl_cui_inl_def_count
#undef mk_sl_cui_inl_def_endian

#undef mk_sl_cui_inl_def_idx

#undef mk_sl_cui_inl_def_base_set_zero
#undef mk_sl_cui_inl_def_base_set_max
#undef mk_sl_cui_inl_def_base_set_one
#undef mk_sl_cui_inl_def_base_set_bit
#undef mk_sl_cui_inl_def_base_set_mask
#undef mk_sl_cui_inl_def_base_is_zero
#undef mk_sl_cui_inl_def_base_is_max
#undef mk_sl_cui_inl_def_base_eq
#undef mk_sl_cui_inl_def_base_ne
#undef mk_sl_cui_inl_def_base_lt
#undef mk_sl_cui_inl_def_base_le
#undef mk_sl_cui_inl_def_base_gt
#undef mk_sl_cui_inl_def_base_ge
#undef mk_sl_cui_inl_def_base_inc2
#undef mk_sl_cui_inl_def_base_dec2
#undef mk_sl_cui_inl_def_base_inc1
#undef mk_sl_cui_inl_def_base_dec1
#undef mk_sl_cui_inl_def_base_not2
#undef mk_sl_cui_inl_def_base_or3
#undef mk_sl_cui_inl_def_base_and3
#undef mk_sl_cui_inl_def_base_xor3
#undef mk_sl_cui_inl_def_base_not1
#undef mk_sl_cui_inl_def_base_or2
#undef mk_sl_cui_inl_def_base_and2
#undef mk_sl_cui_inl_def_base_xor2
#undef mk_sl_cui_inl_def_base_shl3
#undef mk_sl_cui_inl_def_base_shr3
#undef mk_sl_cui_inl_def_base_rotl3
#undef mk_sl_cui_inl_def_base_rotr3
#undef mk_sl_cui_inl_def_base_shl2
#undef mk_sl_cui_inl_def_base_shr2
#undef mk_sl_cui_inl_def_base_rotl2
#undef mk_sl_cui_inl_def_base_rotr2
#undef mk_sl_cui_inl_def_base_add3_wrap_cid_cod
#undef mk_sl_cui_inl_def_base_add3_wrap_cid_coe
#undef mk_sl_cui_inl_def_base_add3_wrap_cie_cod
#undef mk_sl_cui_inl_def_base_add3_wrap_cie_coe
#undef mk_sl_cui_inl_def_base_add2_wrap_cid_cod
#undef mk_sl_cui_inl_def_base_add2_wrap_cid_coe
#undef mk_sl_cui_inl_def_base_add2_wrap_cie_cod
#undef mk_sl_cui_inl_def_base_add2_wrap_cie_coe
#undef mk_sl_cui_inl_def_base_sub3_wrap_cid_cod
#undef mk_sl_cui_inl_def_base_sub3_wrap_cid_coe
#undef mk_sl_cui_inl_def_base_sub3_wrap_cie_cod
#undef mk_sl_cui_inl_def_base_sub3_wrap_cie_coe
#undef mk_sl_cui_inl_def_base_sub2_wrap_cid_cod
#undef mk_sl_cui_inl_def_base_sub2_wrap_cid_coe
#undef mk_sl_cui_inl_def_base_sub2_wrap_cie_cod
#undef mk_sl_cui_inl_def_base_sub2_wrap_cie_coe
#undef mk_sl_cui_inl_def_base_mul3_wrap_lo
#undef mk_sl_cui_inl_def_base_mul3_wrap_hi
#undef mk_sl_cui_inl_def_base_mul4_wrap_wi
#undef mk_sl_cui_inl_def_base_mul2_wrap_lo
#undef mk_sl_cui_inl_def_base_mul2_wrap_hi
#undef mk_sl_cui_inl_def_base_mul2_wrap_wi

#undef mk_sl_cui_inl_def_s
#undef mk_sl_cui_inl_def_t

#undef mk_sl_cui_inl_def_set_zero
#undef mk_sl_cui_inl_def_set_max
#undef mk_sl_cui_inl_def_set_one
#undef mk_sl_cui_inl_def_set_bit
#undef mk_sl_cui_inl_def_set_mask

#undef mk_sl_cui_inl_def_is_zero
#undef mk_sl_cui_inl_def_is_max
#undef mk_sl_cui_inl_def_eq
#undef mk_sl_cui_inl_def_ne
#undef mk_sl_cui_inl_def_lt
#undef mk_sl_cui_inl_def_le
#undef mk_sl_cui_inl_def_gt
#undef mk_sl_cui_inl_def_ge

#undef mk_sl_cui_inl_def_inc2
#undef mk_sl_cui_inl_def_dec2
#undef mk_sl_cui_inl_def_inc1
#undef mk_sl_cui_inl_def_dec1

#undef mk_sl_cui_inl_def_not2
#undef mk_sl_cui_inl_def_or3
#undef mk_sl_cui_inl_def_and3
#undef mk_sl_cui_inl_def_xor3
#undef mk_sl_cui_inl_def_not1
#undef mk_sl_cui_inl_def_or2
#undef mk_sl_cui_inl_def_and2
#undef mk_sl_cui_inl_def_xor2

#undef mk_sl_cui_inl_def_shl3
#undef mk_sl_cui_inl_def_shr3
#undef mk_sl_cui_inl_def_rotl3
#undef mk_sl_cui_inl_def_rotr3
#undef mk_sl_cui_inl_def_shl2
#undef mk_sl_cui_inl_def_shr2
#undef mk_sl_cui_inl_def_rotl2
#undef mk_sl_cui_inl_def_rotr2

#undef mk_sl_cui_inl_def_add3_wrap_cid_cod
#undef mk_sl_cui_inl_def_add3_wrap_cid_coe
#undef mk_sl_cui_inl_def_add3_wrap_cie_cod
#undef mk_sl_cui_inl_def_add3_wrap_cie_coe
#undef mk_sl_cui_inl_def_add2_wrap_cid_cod
#undef mk_sl_cui_inl_def_add2_wrap_cid_coe
#undef mk_sl_cui_inl_def_add2_wrap_cie_cod
#undef mk_sl_cui_inl_def_add2_wrap_cie_coe

#undef mk_sl_cui_inl_def_sub3_wrap_cid_cod
#undef mk_sl_cui_inl_def_sub3_wrap_cid_coe
#undef mk_sl_cui_inl_def_sub3_wrap_cie_cod
#undef mk_sl_cui_inl_def_sub3_wrap_cie_coe
#undef mk_sl_cui_inl_def_sub2_wrap_cid_cod
#undef mk_sl_cui_inl_def_sub2_wrap_cid_coe
#undef mk_sl_cui_inl_def_sub2_wrap_cie_cod
#undef mk_sl_cui_inl_def_sub2_wrap_cie_coe

#undef mk_sl_cui_inl_def_mul3_wrap_lo_restrict
#undef mk_sl_cui_inl_def_mul3_wrap_lo_alias
#undef mk_sl_cui_inl_def_mul3_wrap_hi_restrict
#undef mk_sl_cui_inl_def_mul3_wrap_hi_alias
#undef mk_sl_cui_inl_def_mul4_wrap_wi_restrict
#undef mk_sl_cui_inl_def_mul4_wrap_wi_alias

#undef mk_sl_cui_inl_def_mul3_wrap_lo
#undef mk_sl_cui_inl_def_mul3_wrap_hi
#undef mk_sl_cui_inl_def_mul4_wrap_wi
#undef mk_sl_cui_inl_def_mul2_wrap_lo
#undef mk_sl_cui_inl_def_mul2_wrap_hi
#undef mk_sl_cui_inl_def_mul2_wrap_wi
