#ifndef mk_include_guard_mk_iip_cp_sessioncmd_message_impl_h
#define mk_include_guard_mk_iip_cp_sessioncmd_message_impl_h


#include "mk_iip_cp_message.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_struct.h"
#include "mk_lang_types.h"


mk_lang_struct_forward(mk_iip_cp_message);
mk_lang_struct_forward(mk_iip_cp_sessioncmd_message_intr);
mk_lang_struct_forward(mk_iip_cp_type_sessionid);


struct mk_iip_cp_sessioncmd_message_impl_s
{
	mk_iip_cp_sessioncmd_message_intr_pt m_sessioncmd_message_intr;
	mk_iip_cp_type_sessionid_pct m_session_id;
	mk_lang_types_bool_t m_did_something;
	mk_lang_types_bool_t m_want_receive;
	mk_iip_cp_type_messageid_t m_message_id;
	mk_iip_cp_type_buffer_t m_message_content;
};
typedef struct mk_iip_cp_sessioncmd_message_impl_s mk_iip_cp_sessioncmd_message_impl_t;
mk_lang_struct_typedef(mk_iip_cp_sessioncmd_message_impl);


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_message_impl_rw_allocate(mk_iip_cp_sessioncmd_message_impl_ppt const sessioncmd_message_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_message_impl_rw_deallocate(mk_iip_cp_sessioncmd_message_impl_pt const sessioncmd_message_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_message_impl_rw_construct(mk_iip_cp_sessioncmd_message_impl_pt const sessioncmd_message_impl, mk_iip_cp_sessioncmd_message_intr_pt const sessioncmd_message_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_message_impl_rw_destruct(mk_iip_cp_sessioncmd_message_impl_pt const sessioncmd_message_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_message_impl_rw_allocate_and_construct(mk_iip_cp_sessioncmd_message_impl_ppt const sessioncmd_message_impl, mk_iip_cp_sessioncmd_message_intr_pt const sessioncmd_message_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_message_impl_rw_destruct_and_deallocate(mk_iip_cp_sessioncmd_message_impl_pt const sessioncmd_message_impl) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_message_impl_rw_set_session_id(mk_iip_cp_sessioncmd_message_impl_pt const sessioncmd_message_impl, mk_iip_cp_type_sessionid_pct const session_id) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_iip_cp_type_sessionid_pct mk_iip_cp_sessioncmd_message_impl_rw_get_session_id(mk_iip_cp_sessioncmd_message_impl_pt const sessioncmd_message_impl) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_bool_t mk_iip_cp_sessioncmd_message_impl_rw_did_something(mk_iip_cp_sessioncmd_message_impl_pt const sessioncmd_message_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_message_impl_rw_on_msg(mk_iip_cp_sessioncmd_message_impl_pt const sessioncmd_message_impl, mk_iip_cp_message_pct const message) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_message_impl_rw_make_msg(mk_iip_cp_sessioncmd_message_impl_pt const sessioncmd_message_impl, mk_iip_cp_message_pt const message) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_message_impl_rw_tick_single(mk_iip_cp_sessioncmd_message_impl_pt const sessioncmd_message_impl) mk_lang_noexcept;


#if mk_lang_jumbo_have == 1
#include "mk_iip_cp_sessioncmd_message_impl.c"
#endif
#endif
