#ifndef mk_include_guard_mk_iip_cp_connection_impl_cmd_connect_fileh_h
#define mk_include_guard_mk_iip_cp_connection_impl_cmd_connect_fileh_h
#include "mk_iip_cp_connection_impl.h"


enum mk_iip_cp_connection_impl_cmd_connect_stage_e
{
	mk_iip_cp_connection_impl_cmd_connect_stage_e_connect_request,
	mk_iip_cp_connection_impl_cmd_connect_stage_e_connect_wait,
	mk_iip_cp_connection_impl_cmd_connect_stage_e_protocol_byte_send,
	mk_iip_cp_connection_impl_cmd_connect_stage_e_protocol_byte_wait,
	mk_iip_cp_connection_impl_cmd_connect_stage_e_get_date_send,
	mk_iip_cp_connection_impl_cmd_connect_stage_e_get_date_wait,
	mk_iip_cp_connection_impl_cmd_connect_stage_e_set_date_recv,
	mk_iip_cp_connection_impl_cmd_connect_stage_e_set_date_wait,
	mk_iip_cp_connection_impl_cmd_connect_stage_e_finish,
	mk_iip_cp_connection_impl_cmd_connect_stage_e_dummy_end
};
typedef enum mk_iip_cp_connection_impl_cmd_connect_stage_e mk_iip_cp_connection_impl_cmd_connect_stage_t;
mk_lang_struct_typedef(mk_iip_cp_connection_impl_cmd_connect_stage);

struct mk_iip_cp_connection_impl_cmd_connect_s
{
	mk_iip_cp_connection_impl_cmd_connect_stage_t m_stage;
	mk_iip_cp_client_data_request_connect_pct m_request;
	mk_iip_cp_client_data_response_connect_pt m_response;
};
typedef struct mk_iip_cp_connection_impl_cmd_connect_s mk_iip_cp_connection_impl_cmd_connect_t;
mk_lang_struct_typedef(mk_iip_cp_connection_impl_cmd_connect);


#endif
