#ifndef mk_include_guard_mk_iip_cp_connection_intr_h
#define mk_include_guard_mk_iip_cp_connection_intr_h


#include "mk_iip_cp_mallocator_global.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_struct.h"
#include "mk_lang_types.h"


mk_lang_struct_forward(mk_iip_cp_client_data_request_connect);
mk_lang_struct_forward(mk_iip_cp_client_data_request_create_session);
mk_lang_struct_forward(mk_iip_cp_client_data_request_get_bandwidth_limits);
mk_lang_struct_forward(mk_iip_cp_client_data_request_host_lookup);
mk_lang_struct_forward(mk_iip_cp_client_data_request_accept);
mk_lang_struct_forward(mk_iip_cp_client_data_request_read_data);
mk_lang_struct_forward(mk_iip_cp_client_data_response_connect);
mk_lang_struct_forward(mk_iip_cp_client_data_response_create_session);
mk_lang_struct_forward(mk_iip_cp_client_data_response_get_bandwidth_limits);
mk_lang_struct_forward(mk_iip_cp_client_data_response_host_lookup);
mk_lang_struct_forward(mk_iip_cp_client_data_response_accept);
mk_lang_struct_forward(mk_iip_cp_client_data_response_read_data);
mk_lang_struct_forward(mk_iip_cp_connection_impl);
mk_lang_struct_forward(mk_sl_io_async_iocp_windows);
mk_lang_struct_forward(mk_sl_net_windows_iorp_xxx);


struct mk_iip_cp_connection_intr_s
{
	mk_iip_cp_connection_impl_pt m_connection_impl;
};
typedef struct mk_iip_cp_connection_intr_s mk_iip_cp_connection_intr_t;
mk_lang_struct_typedef(mk_iip_cp_connection_intr);


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_allocate(mk_iip_cp_connection_intr_ppt const connection_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_deallocate(mk_iip_cp_connection_intr_pt const connection_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_construct(mk_iip_cp_connection_intr_pt const connection_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_destruct(mk_iip_cp_connection_intr_pt const connection_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_allocate_and_construct(mk_iip_cp_connection_intr_ppt const connection_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_destruct_and_deallocate(mk_iip_cp_connection_intr_pt const connection_intr) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_set_iocp(mk_iip_cp_connection_intr_pt const connection_intr, mk_sl_io_async_iocp_windows_pt const iocp) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_bool_t mk_iip_cp_connection_intr_rw_did_something(mk_iip_cp_connection_intr_pt const connection_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_bool_t mk_iip_cp_connection_intr_rw_has_outstanding_iorp(mk_iip_cp_connection_intr_pt const connection_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_on_iorp(mk_iip_cp_connection_intr_pt const connection_intr, mk_sl_net_windows_iorp_xxx_pt const iorp) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_tick_single(mk_iip_cp_connection_intr_pt const connection_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_tick_force(mk_iip_cp_connection_intr_pt const connection_intr) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_connect_to_i2cp(mk_iip_cp_connection_intr_pt const connection_intr, mk_iip_cp_client_data_request_connect_pct const request, mk_iip_cp_client_data_response_connect_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_create_session(mk_iip_cp_connection_intr_pt const connection_intr, mk_iip_cp_client_data_request_create_session_pct const request, mk_iip_cp_client_data_response_create_session_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_get_bandwidth_limits(mk_iip_cp_connection_intr_pt const connection_intr, mk_iip_cp_client_data_request_get_bandwidth_limits_pct const request, mk_iip_cp_client_data_response_get_bandwidth_limits_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_host_lookup(mk_iip_cp_connection_intr_pt const connection_intr, mk_iip_cp_client_data_request_host_lookup_pct const request, mk_iip_cp_client_data_response_host_lookup_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_accept(mk_iip_cp_connection_intr_pt const connection_intr, mk_iip_cp_client_data_request_accept_pct const request, mk_iip_cp_client_data_response_accept_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_read_data(mk_iip_cp_connection_intr_pt const connection_intr, mk_iip_cp_client_data_request_read_data_pct const request, mk_iip_cp_client_data_response_read_data_pt const response) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intr_rw_get_bandwidth_limits_internal(mk_iip_cp_connection_intr_pt const connection_intr) mk_lang_noexcept;


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intrs_pr_element_construct_void(mk_iip_cp_connection_intr_pt const connection_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_intrs_pr_element_destruct(mk_iip_cp_connection_intr_pt const connection_intr) mk_lang_noexcept;


#define mk_sl_vector_t_name mk_iip_cp_connection_intrs
#define mk_sl_vector_t_element mk_iip_cp_connection_intr_t
#define mk_sl_vector_t_element_construct_void mk_iip_cp_connection_intrs_pr_element_construct_void
#define mk_sl_vector_t_element_destruct mk_iip_cp_connection_intrs_pr_element_destruct
#define mk_sl_vector_t_mallocatorg mk_iip_cp_mallocator_global
#include "mk_sl_vector_inl_fileh.h"
#include "mk_sl_vector_inl_fileu.h"


#if mk_lang_jumbo_have == 1
#include "mk_iip_cp_connection_intr.c"
#endif
#endif
