#ifndef mk_include_guard_mk_iip_cp_helper_h
#define mk_include_guard_mk_iip_cp_helper_h


#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_struct.h"
#include "mk_lang_types.h"
#include "mk_lib_crypto_hash_block_sha2_256.h"
#include "mk_sl_uint8.h"

#define mk_lang_memcpy_t_name mk_iip_cp_helper_memcpy_u8
#define mk_lang_memcpy_t_type mk_sl_cui_uint8_t
#include "mk_lang_memcpy_inl_fileh.h"
#define mk_iip_cp_helper_bui_sizebits_d (mk_lang_sizeof_bi_uint_t * mk_lang_charbit)
#undef mk_lang_memcpy_t_name
#undef mk_lang_memcpy_t_type

#define mk_lang_bui_t_name mk_iip_cp_helper_bui
#define mk_lang_bui_t_base uint
#define mk_lang_bui_t_inline 1
#include "mk_lang_bui_inl_fileh.h"
#undef mk_lang_bui_t_name
#undef mk_lang_bui_t_base
#undef mk_lang_bui_t_inline


struct mk_iip_cp_helper_time_components_s
{
	mk_lang_types_sint_t m_year;
	mk_lang_types_sint_t m_month;
	mk_lang_types_sint_t m_day;
	mk_lang_types_sint_t m_hour;
	mk_lang_types_sint_t m_minute;
	mk_lang_types_sint_t m_second;
	mk_lang_types_sint_t m_milli_second;
};
typedef struct mk_iip_cp_helper_time_components_s mk_iip_cp_helper_time_components_t;
mk_lang_struct_typedef(mk_iip_cp_helper_time_components);


mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_u8s_to_uchars(mk_sl_cui_uint8_pct const u8s, mk_lang_types_uchar_pt const ucs, mk_lang_types_sint_t const len) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_u8s_to_pchars(mk_sl_cui_uint8_pct const u8s, mk_lang_types_pchar_pt const pcs, mk_lang_types_sint_t const len) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_u8s_to_hex(mk_sl_cui_uint8_pct const u8s, mk_lang_types_pchar_pt const pcs, mk_lang_types_sint_t const len) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_uchars_to_u8s(mk_lang_types_uchar_pct const ucs, mk_sl_cui_uint8_pt const u8s, mk_lang_types_sint_t const len) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_sha256_to_pchars(mk_lib_crypto_hash_block_sha2_256_digest_pct const digest, mk_lang_types_pchar_pt const strbuf) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_base64_u8s_to_pchars(mk_sl_cui_uint8_pct const databuf, mk_lang_types_sint_t const datalen, mk_lang_types_pchar_pt const strbuf, mk_lang_types_sint_pt const outlen) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_base64_pchars_to_u8s(mk_lang_types_pchar_pct const strbuf, mk_lang_types_sint_t const strlen, mk_sl_cui_uint8_pt const databuf, mk_lang_types_sint_pt const outlen) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_base32_u8s_to_pchars(mk_sl_cui_uint8_pct const databuf, mk_lang_types_sint_t const datalen, mk_lang_types_pchar_pt const strbuf, mk_lang_types_sint_pt const outlen) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_time_to_components(mk_sl_cui_uint64_pct const time, mk_iip_cp_helper_time_components_pt const components) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_time_to_text(mk_sl_cui_uint64_pct const time, mk_lang_types_pchar_pt const strbuf, mk_lang_types_sint_t const strlen, mk_lang_types_sint_pt const outlen) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_generate_random_u32(mk_sl_cui_uint32_pt const u32) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_generate_random_u32_non_zero(mk_sl_cui_uint32_pt const u32) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_generate_random_u8s(mk_sl_cui_uint8_pt const u8s, mk_lang_types_sint_t const len) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_generate_random_uchars(mk_lang_types_uchar_pt const ucs, mk_lang_types_sint_t const len) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_get_time_now(mk_sl_cui_uint64_pt const time) mk_lang_noexcept;


#define mk_sl_cui_t_name mk_iip_cp_helper_cui_elgamal_single
#define mk_sl_cui_t_base mk_iip_cp_helper_bui
#define mk_sl_cui_t_count ((256 * mk_lang_charbit) / mk_iip_cp_helper_bui_sizebits_d)
#define mk_sl_cui_t_inline 0
#include "mk_sl_cui_inl_fileh.h"
#undef mk_sl_cui_t_name
#undef mk_sl_cui_t_base
#undef mk_sl_cui_t_count
#undef mk_sl_cui_t_endian
#undef mk_sl_cui_t_disable_big_div
#undef mk_sl_cui_t_base_sizebits_d
#undef mk_sl_cui_t_inline

#define mk_sl_cui_t_name mk_iip_cp_helper_cui_elgamal_double
#define mk_sl_cui_t_base mk_iip_cp_helper_bui
#define mk_sl_cui_t_count (((256 * mk_lang_charbit) / mk_iip_cp_helper_bui_sizebits_d) * 2)
#define mk_sl_cui_t_inline 0
#include "mk_sl_cui_inl_fileh.h"
#undef mk_sl_cui_t_name
#undef mk_sl_cui_t_base
#undef mk_sl_cui_t_count
#undef mk_sl_cui_t_endian
#undef mk_sl_cui_t_disable_big_div
#undef mk_sl_cui_t_base_sizebits_d
#undef mk_sl_cui_t_inline

#define mk_sl_cui_t_name mk_iip_cp_helper_cui_dsa_pri_single
#define mk_sl_cui_t_base mk_iip_cp_helper_bui
#define mk_sl_cui_t_count ((20 * mk_lang_charbit) / mk_iip_cp_helper_bui_sizebits_d)
#define mk_sl_cui_t_inline 0
#include "mk_sl_cui_inl_fileh.h"
#undef mk_sl_cui_t_name
#undef mk_sl_cui_t_base
#undef mk_sl_cui_t_count
#undef mk_sl_cui_t_endian
#undef mk_sl_cui_t_disable_big_div
#undef mk_sl_cui_t_base_sizebits_d
#undef mk_sl_cui_t_inline

#define mk_sl_cui_t_name mk_iip_cp_helper_cui_dsa_pri_double
#define mk_sl_cui_t_base mk_iip_cp_helper_bui
#define mk_sl_cui_t_count (((20 * mk_lang_charbit) / mk_iip_cp_helper_bui_sizebits_d) * 2)
#define mk_sl_cui_t_inline 0
#include "mk_sl_cui_inl_fileh.h"
#undef mk_sl_cui_t_name
#undef mk_sl_cui_t_base
#undef mk_sl_cui_t_count
#undef mk_sl_cui_t_endian
#undef mk_sl_cui_t_disable_big_div
#undef mk_sl_cui_t_base_sizebits_d
#undef mk_sl_cui_t_inline

#define mk_sl_cui_t_name mk_iip_cp_helper_cui_dsa_pub_single
#define mk_sl_cui_t_base mk_iip_cp_helper_bui
#define mk_sl_cui_t_count ((128 * mk_lang_charbit) / mk_iip_cp_helper_bui_sizebits_d)
#define mk_sl_cui_t_inline 0
#include "mk_sl_cui_inl_fileh.h"
#undef mk_sl_cui_t_name
#undef mk_sl_cui_t_base
#undef mk_sl_cui_t_count
#undef mk_sl_cui_t_endian
#undef mk_sl_cui_t_disable_big_div
#undef mk_sl_cui_t_base_sizebits_d
#undef mk_sl_cui_t_inline

#define mk_sl_cui_t_name mk_iip_cp_helper_cui_dsa_pub_double
#define mk_sl_cui_t_base mk_iip_cp_helper_bui
#define mk_sl_cui_t_count (((128 * mk_lang_charbit) / mk_iip_cp_helper_bui_sizebits_d) * 2)
#define mk_sl_cui_t_inline 0
#include "mk_sl_cui_inl_fileh.h"
#undef mk_sl_cui_t_name
#undef mk_sl_cui_t_base
#undef mk_sl_cui_t_count
#undef mk_sl_cui_t_endian
#undef mk_sl_cui_t_disable_big_div
#undef mk_sl_cui_t_base_sizebits_d
#undef mk_sl_cui_t_inline


mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_elgamal_single_load_p(mk_iip_cp_helper_cui_elgamal_single_pt const x) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_elgamal_single_to_double(mk_iip_cp_helper_cui_elgamal_single_pct const a, mk_iip_cp_helper_cui_elgamal_double_pt const b) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_elgamal_double_to_single(mk_iip_cp_helper_cui_elgamal_double_pct const a, mk_iip_cp_helper_cui_elgamal_single_pt const b) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_elgamal_single_mod_pow(mk_iip_cp_helper_cui_elgamal_single_prct const base, mk_iip_cp_helper_cui_elgamal_single_prct const exponent, mk_iip_cp_helper_cui_elgamal_single_prct const modulus, mk_iip_cp_helper_cui_elgamal_single_prt const result) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_elgamal_double_load_p(mk_iip_cp_helper_cui_elgamal_double_pt const x) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pri_single_load_q(mk_iip_cp_helper_cui_dsa_pri_single_pt const x) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pri_single_from_u8s_be(mk_iip_cp_helper_cui_dsa_pri_single_pt const x, mk_sl_cui_uint8_pct const u8s) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pri_single_to_double(mk_iip_cp_helper_cui_dsa_pri_single_pct const a, mk_iip_cp_helper_cui_dsa_pri_double_pt const b) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pri_single_to_pub_double(mk_iip_cp_helper_cui_dsa_pri_single_pct const a, mk_iip_cp_helper_cui_dsa_pub_double_pt const b) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pri_single_mod_mul3_wrap_lo(mk_iip_cp_helper_cui_dsa_pri_single_prct const m, mk_iip_cp_helper_cui_dsa_pri_single_prct const a, mk_iip_cp_helper_cui_dsa_pri_single_prct const b, mk_iip_cp_helper_cui_dsa_pri_single_prt const c) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pri_single_mod_add2_wrap_cid_cod(mk_iip_cp_helper_cui_dsa_pri_single_prct const m, mk_iip_cp_helper_cui_dsa_pri_single_prt const a, mk_iip_cp_helper_cui_dsa_pri_single_prct const b) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pri_single_mod_mul2_wrap_lo(mk_iip_cp_helper_cui_dsa_pri_single_prct const m, mk_iip_cp_helper_cui_dsa_pri_single_prt const a, mk_iip_cp_helper_cui_dsa_pri_single_prct const b) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pri_double_to_single(mk_iip_cp_helper_cui_dsa_pri_double_pct const a, mk_iip_cp_helper_cui_dsa_pri_single_pt const b) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pri_single_to_pub_single(mk_iip_cp_helper_cui_dsa_pri_single_pct const a, mk_iip_cp_helper_cui_dsa_pub_single_pt const b) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_bool_t mk_iip_cp_helper_cui_dsa_pri_single_is_negative(mk_iip_cp_helper_cui_dsa_pri_single_pct const x) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pri_single_flip_sign_1(mk_iip_cp_helper_cui_dsa_pri_single_pt const x) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pri_single_gcd(mk_iip_cp_helper_cui_dsa_pri_single_prct const a, mk_iip_cp_helper_cui_dsa_pri_single_prct const b, mk_iip_cp_helper_cui_dsa_pri_single_prt const c) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pri_single_mul3_signed(mk_iip_cp_helper_cui_dsa_pri_single_prct const a, mk_iip_cp_helper_cui_dsa_pri_single_prct const b, mk_iip_cp_helper_cui_dsa_pri_single_prt const c) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pri_single_mod_inv(mk_iip_cp_helper_cui_dsa_pri_single_pct const a, mk_iip_cp_helper_cui_dsa_pri_single_pct const modulus, mk_iip_cp_helper_cui_dsa_pri_single_pt const res_out) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pri_double_load_q(mk_iip_cp_helper_cui_dsa_pri_double_pt const x) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pub_single_load_g(mk_iip_cp_helper_cui_dsa_pub_single_pt const x) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pub_single_load_p(mk_iip_cp_helper_cui_dsa_pub_single_pt const x) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pub_single_to_double(mk_iip_cp_helper_cui_dsa_pub_single_pct const a, mk_iip_cp_helper_cui_dsa_pub_double_pt const b) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pub_single_to_pri_single(mk_iip_cp_helper_cui_dsa_pub_single_pct const a, mk_iip_cp_helper_cui_dsa_pri_single_pt const b) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pub_double_to_single(mk_iip_cp_helper_cui_dsa_pub_double_pct const a, mk_iip_cp_helper_cui_dsa_pub_single_pt const b) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pub_double_to_pri_single(mk_iip_cp_helper_cui_dsa_pub_double_pct const a, mk_iip_cp_helper_cui_dsa_pri_single_pt const b) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pub_single_mod_pow_a(mk_iip_cp_helper_cui_dsa_pub_single_prct const base, mk_iip_cp_helper_cui_dsa_pub_single_prct const exponent, mk_iip_cp_helper_cui_dsa_pub_single_prct const modulus, mk_iip_cp_helper_cui_dsa_pub_single_prt const result) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pub_single_mod_pow_b(mk_iip_cp_helper_cui_dsa_pub_single_prct const base, mk_iip_cp_helper_cui_dsa_pri_single_prct const exponent, mk_iip_cp_helper_cui_dsa_pub_single_prct const modulus_a, mk_iip_cp_helper_cui_dsa_pri_single_prct const modulus_b, mk_iip_cp_helper_cui_dsa_pri_single_prt const result) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pub_double_load_g(mk_iip_cp_helper_cui_dsa_pub_double_pt const x) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_iip_cp_helper_cui_dsa_pub_double_load_p(mk_iip_cp_helper_cui_dsa_pub_double_pt const x) mk_lang_noexcept;


#if mk_lang_jumbo_have == 1
#include "mk_iip_cp_helper.c"
#endif
#endif
