#ifndef mk_include_guard_mk_iip_cp_connection_impl_h
#define mk_include_guard_mk_iip_cp_connection_impl_h


#include "mk_iip_cp_client_data.h"
#include "mk_iip_cp_client_data_impl.h"
#include "mk_iip_cp_mallocator_global.h"
#include "mk_iip_cp_message_parse.h"
#include "mk_iip_cp_message_serialize.h"
#include "mk_iip_cp_session_intr.h"
#include "mk_lang_struct.h"
#include "mk_sl_net_windows.h"


#define mk_sl_ring_dynamic_t_name mk_iip_cp_connection_impl_buffer
#define mk_sl_ring_dynamic_t_element mk_sl_cui_uint8_t
#define mk_sl_ring_dynamic_t_mallocatorg mk_iip_cp_mallocator_global
#include "mk_sl_ring_dynamic_inl_fileh.h"
#include "mk_sl_ring_dynamic_inl_fileu.h"


#include "mk_iip_cp_connection_impl_cmd_connect_fileh.h"
#include "mk_iip_cp_connection_impl_cmd_create_session_fileh.h"
#include "mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_fileh.h"
#include "mk_iip_cp_connection_impl_cmd_host_lookup_fileh.h"
#include "mk_iip_cp_connection_impl_cmd_accept_fileh.h"

enum mk_iip_cp_connection_impl_cmd_type_e
{
	mk_iip_cp_connection_impl_cmd_type_e_connect,
	mk_iip_cp_connection_impl_cmd_type_e_create_session,
	mk_iip_cp_connection_impl_cmd_type_e_get_bandwidth_limits,
	mk_iip_cp_connection_impl_cmd_type_e_host_lookup,
	mk_iip_cp_connection_impl_cmd_type_e_accept,
	mk_iip_cp_connection_impl_cmd_type_e_dummy_end
};
typedef enum mk_iip_cp_connection_impl_cmd_type_e mk_iip_cp_connection_impl_cmd_type_t;
mk_lang_struct_typedef(mk_iip_cp_connection_impl_cmd_type);

union mk_iip_cp_connection_impl_cmd_mix_data_u
{
	mk_iip_cp_connection_impl_cmd_connect_t m_connect;
	mk_iip_cp_connection_impl_cmd_create_session_t m_create_session;
	mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_t m_get_bandwidth_limits;
	mk_iip_cp_connection_impl_cmd_host_lookup_t m_host_lookup;
	mk_iip_cp_connection_impl_cmd_accept_t m_accept;
};
typedef union mk_iip_cp_connection_impl_cmd_mix_data_u mk_iip_cp_connection_impl_cmd_mix_data_t;
mk_lang_struct_typedef(mk_iip_cp_connection_impl_cmd_mix_data);

struct mk_iip_cp_connection_impl_cmd_mix_s
{
	mk_iip_cp_connection_impl_cmd_mix_data_t m_data;
};
typedef struct mk_iip_cp_connection_impl_cmd_mix_s mk_iip_cp_connection_impl_cmd_mix_t;
mk_lang_struct_typedef(mk_iip_cp_connection_impl_cmd_mix);

struct mk_iip_cp_connection_impl_cmd_s
{
	mk_iip_cp_connection_impl_cmd_type_t m_type;
	mk_iip_cp_connection_impl_cmd_mix_t m_mix;
};
typedef struct mk_iip_cp_connection_impl_cmd_s mk_iip_cp_connection_impl_cmd_t;
mk_lang_struct_typedef(mk_iip_cp_connection_impl_cmd);

#define mk_sl_vector_t_name mk_iip_cp_connection_impl_cmds
#define mk_sl_vector_t_element mk_iip_cp_connection_impl_cmd_t
#define mk_sl_vector_t_mallocatorg mk_iip_cp_mallocator_global
#include "mk_sl_vector_inl_fileh.h"
#include "mk_sl_vector_inl_fileu.h"


struct mk_iip_cp_connection_impl_s
{
	mk_iip_cp_connection_intr_pt m_connection_intr;
	mk_iip_cp_type_date_t m_server_date_val;
	mk_iip_cp_type_date_t m_server_date_now;
	mk_iip_cp_type_string_t m_server_version;
	mk_iip_cp_session_intrs_t m_sessions;
	mk_lang_types_bool_t m_did_something;
	mk_iip_cp_connection_impl_cmds_t m_cmds;
	mk_lang_types_uint_t m_sub_item_idx;
	mk_lang_types_bool_t m_force;
	mk_sl_net_windows_destination_t m_ip_destination;
	mk_lang_types_bool_t m_has_read_iorp;
	mk_lang_types_bool_t m_has_write_iorp;
	mk_sl_net_windows_ctx_connect_t m_connect_ctx;
	mk_sl_net_windows_socket_t m_socket;
	mk_sl_io_async_iocp_windows_pt m_iocp;
	mk_iip_cp_message_parse_errcode_t m_errcodep;
	mk_iip_cp_message_serialize_errcode_t m_errcodes;
	mk_lang_types_sint_t m_consumed;
	mk_iip_cp_message_t m_message;
	mk_iip_cp_client_data_request_get_bandwidth_limits_t m_request_get_bandwidth_limits_internal;
	mk_iip_cp_client_data_response_get_bandwidth_limits_t m_response_get_bandwidth_limits_internal;
	mk_iip_cp_type_bandwidth_limits_t m_bandwidth_limits;
	mk_sl_net_windows_iorp_xxx_t m_iorpr;
	mk_sl_net_windows_iorp_xxx_t m_iorpw;
	mk_iip_cp_connection_impl_buffer_t m_snd_buf;
	mk_iip_cp_connection_impl_buffer_t m_rcv_buf;
};
typedef struct mk_iip_cp_connection_impl_s mk_iip_cp_connection_impl_t;
mk_lang_struct_typedef(mk_iip_cp_connection_impl);


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_allocate(mk_iip_cp_connection_impl_ppt const connection_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_deallocate(mk_iip_cp_connection_impl_pt const connection_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_construct(mk_iip_cp_connection_impl_pt const connection_impl, mk_iip_cp_connection_intr_pt const connection_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_destruct(mk_iip_cp_connection_impl_pt const connection_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_allocate_and_construct(mk_iip_cp_connection_impl_ppt const connection_impl, mk_iip_cp_connection_intr_pt const connection_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_destruct_and_deallocate(mk_iip_cp_connection_impl_pt const connection_impl) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_set_iocp(mk_iip_cp_connection_impl_pt const connection_impl, mk_sl_io_async_iocp_windows_pt const iocp) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_bool_t mk_iip_cp_connection_impl_rw_did_something(mk_iip_cp_connection_impl_pt const connection_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_bool_t mk_iip_cp_connection_impl_rw_has_outstanding_iorp(mk_iip_cp_connection_impl_pt const connection_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_on_iorp(mk_iip_cp_connection_impl_pt const connection_impl, mk_sl_net_windows_iorp_xxx_pt const iorp) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_tick_single(mk_iip_cp_connection_impl_pt const connection_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_tick_force(mk_iip_cp_connection_impl_pt const connection_impl) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_connect_to_i2cp(mk_iip_cp_connection_impl_pt const connection_impl, mk_iip_cp_client_data_request_connect_pct const request, mk_iip_cp_client_data_response_connect_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_create_session(mk_iip_cp_connection_impl_pt const connection_impl, mk_iip_cp_client_data_request_create_session_pct const request, mk_iip_cp_client_data_response_create_session_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_get_bandwidth_limits(mk_iip_cp_connection_impl_pt const connection_impl, mk_iip_cp_client_data_request_get_bandwidth_limits_pct const request, mk_iip_cp_client_data_response_get_bandwidth_limits_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_host_lookup(mk_iip_cp_connection_impl_pt const connection_impl, mk_iip_cp_client_data_request_host_lookup_pct const request, mk_iip_cp_client_data_response_host_lookup_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_accept(mk_iip_cp_connection_impl_pt const connection_impl, mk_iip_cp_client_data_request_accept_pct const request, mk_iip_cp_client_data_response_accept_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_read_data(mk_iip_cp_connection_impl_pt const connection_impl, mk_iip_cp_client_data_request_read_data_pct const request, mk_iip_cp_client_data_response_read_data_pt const response) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_connection_impl_rw_get_bandwidth_limits_internal(mk_iip_cp_connection_impl_pt const connection_impl) mk_lang_noexcept;


#if mk_lang_jumbo_have == 1
#include "mk_iip_cp_connection_impl.c"
#endif
#endif
