#ifndef mk_include_guard_mk_iip_cp_sessioncmd_leaseset_intr_h
#define mk_include_guard_mk_iip_cp_sessioncmd_leaseset_intr_h


#include "mk_iip_cp_mallocator_global.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_struct.h"
#include "mk_lang_types.h"


mk_lang_struct_forward(mk_iip_cp_message);
mk_lang_struct_forward(mk_iip_cp_sessioncmd_leaseset_impl);
mk_lang_struct_forward(mk_iip_cp_type_destination_elgamal_dsa);
mk_lang_struct_forward(mk_iip_cp_type_sessionid);


struct mk_iip_cp_sessioncmd_leaseset_intr_s
{
	mk_iip_cp_sessioncmd_leaseset_impl_pt m_sessioncmd_leaseset_impl;
};
typedef struct mk_iip_cp_sessioncmd_leaseset_intr_s mk_iip_cp_sessioncmd_leaseset_intr_t;
mk_lang_struct_typedef(mk_iip_cp_sessioncmd_leaseset_intr);


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_leaseset_intr_rw_allocate(mk_iip_cp_sessioncmd_leaseset_intr_ppt const sessioncmd_leaseset_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_leaseset_intr_rw_deallocate(mk_iip_cp_sessioncmd_leaseset_intr_pt const sessioncmd_leaseset_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_leaseset_intr_rw_construct(mk_iip_cp_sessioncmd_leaseset_intr_pt const sessioncmd_leaseset_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_leaseset_intr_rw_destruct(mk_iip_cp_sessioncmd_leaseset_intr_pt const sessioncmd_leaseset_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_leaseset_intr_rw_allocate_and_construct(mk_iip_cp_sessioncmd_leaseset_intr_ppt const sessioncmd_leaseset_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_leaseset_intr_rw_destruct_and_deallocate(mk_iip_cp_sessioncmd_leaseset_intr_pt const sessioncmd_leaseset_intr) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_leaseset_intr_rw_set_session_id(mk_iip_cp_sessioncmd_leaseset_intr_pt const sessioncmd_leaseset_intr, mk_iip_cp_type_sessionid_pct const session_id) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_leaseset_intr_rw_set_destination(mk_iip_cp_sessioncmd_leaseset_intr_pt const sessioncmd_leaseset_intr, mk_iip_cp_type_destination_elgamal_dsa_pct const destination) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_iip_cp_type_sessionid_pct mk_iip_cp_sessioncmd_leaseset_intr_rw_get_session_id(mk_iip_cp_sessioncmd_leaseset_intr_pt const sessioncmd_leaseset_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_iip_cp_type_destination_elgamal_dsa_pct mk_iip_cp_sessioncmd_leaseset_intr_rw_get_destination(mk_iip_cp_sessioncmd_leaseset_intr_pt const sessioncmd_leaseset_intr) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_bool_t mk_iip_cp_sessioncmd_leaseset_intr_rw_did_something(mk_iip_cp_sessioncmd_leaseset_intr_pt const sessioncmd_leaseset_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_leaseset_intr_rw_on_msg(mk_iip_cp_sessioncmd_leaseset_intr_pt const sessioncmd_leaseset_intr, mk_iip_cp_message_pct const message) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_leaseset_intr_rw_make_msg(mk_iip_cp_sessioncmd_leaseset_intr_pt const sessioncmd_leaseset_intr, mk_iip_cp_message_pt const message) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_leaseset_intr_rw_tick_single(mk_iip_cp_sessioncmd_leaseset_intr_pt const sessioncmd_leaseset_intr) mk_lang_noexcept;


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_leaseset_intrs_pr_element_construct_void(mk_iip_cp_sessioncmd_leaseset_intr_pt const sessioncmd_leaseset_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_sessioncmd_leaseset_intrs_pr_element_destruct(mk_iip_cp_sessioncmd_leaseset_intr_pt const sessioncmd_leaseset_intr) mk_lang_noexcept;

#define mk_sl_vector_t_name mk_iip_cp_sessioncmd_leaseset_intrs
#define mk_sl_vector_t_element mk_iip_cp_sessioncmd_leaseset_intr_t
#define mk_sl_vector_t_element_construct_void mk_iip_cp_sessioncmd_leaseset_intrs_pr_element_construct_void
#define mk_sl_vector_t_element_destruct mk_iip_cp_sessioncmd_leaseset_intrs_pr_element_destruct
#define mk_sl_vector_t_mallocatorg mk_iip_cp_mallocator_global
#include "mk_sl_vector_inl_fileh.h"
#include "mk_sl_vector_inl_fileu.h"


#if mk_lang_jumbo_have == 1
#include "mk_iip_cp_sessioncmd_leaseset_intr.c"
#endif
#endif
