#ifndef mk_include_guard_mk_iip_cp_client_impl_h
#define mk_include_guard_mk_iip_cp_client_impl_h


#include "mk_iip_cp_client_data.h"
#include "mk_iip_cp_client_data_impl.h"
#include "mk_iip_cp_connection_intr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_struct.h"
#include "mk_lang_types.h"
#include "mk_sl_io_async_iocp.h"


struct mk_iip_cp_client_impl_s
{
	mk_iip_cp_connection_intrs_t m_connections;
	mk_iip_cp_client_data_impl_rrs_t m_rrs;
	mk_lang_types_bool_t m_did_something;
	mk_lang_types_usize_t m_idx;
	mk_sl_io_async_iocp_t m_iocp;
};
typedef struct mk_iip_cp_client_impl_s mk_iip_cp_client_impl_t;
mk_lang_struct_typedef(mk_iip_cp_client_impl);


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_allocate(mk_iip_cp_client_impl_ppt const client_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_deallocate(mk_iip_cp_client_impl_pt const client_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_construct(mk_iip_cp_client_impl_pt const client_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_destruct(mk_iip_cp_client_impl_pt const client_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_allocate_and_construct(mk_iip_cp_client_impl_ppt const client_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_destruct_and_deallocate(mk_iip_cp_client_impl_pt const client_impl) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_bool_t mk_iip_cp_client_impl_rw_did_something(mk_iip_cp_client_impl_pt const client_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_tick_single(mk_iip_cp_client_impl_pt const client_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_tick_single2(mk_iip_cp_client_impl_pt const client_impl, mk_lang_types_sint_t const ms) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_tick_until_idle(mk_iip_cp_client_impl_pt const client_impl) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_generate_destination(mk_iip_cp_client_impl_pt const client_impl, mk_iip_cp_client_data_request_generate_destination_pct const request, mk_iip_cp_client_data_response_generate_destination_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_connect_to_i2cp(mk_iip_cp_client_impl_pt const client_impl, mk_iip_cp_client_data_request_connect_pct const request, mk_iip_cp_client_data_response_connect_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_create_session(mk_iip_cp_client_impl_pt const client_impl, mk_iip_cp_client_data_request_create_session_pct const request, mk_iip_cp_client_data_response_create_session_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_get_bandwidth_limits(mk_iip_cp_client_impl_pt const client_impl, mk_iip_cp_client_data_request_get_bandwidth_limits_pct const request, mk_iip_cp_client_data_response_get_bandwidth_limits_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_host_lookup(mk_iip_cp_client_impl_pt const client_impl, mk_iip_cp_client_data_request_host_lookup_pct const request, mk_iip_cp_client_data_response_host_lookup_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_accept(mk_iip_cp_client_impl_pt const client_impl, mk_iip_cp_client_data_request_accept_pct const request, mk_iip_cp_client_data_response_accept_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_read_data(mk_iip_cp_client_impl_pt const client_impl, mk_iip_cp_client_data_request_read_data_pct const request, mk_iip_cp_client_data_response_read_data_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_client_impl_rw_send_data(mk_iip_cp_client_impl_pt const client_impl, mk_iip_cp_client_data_request_send_data_pct const request, mk_iip_cp_client_data_response_send_data_pt const response) mk_lang_noexcept;


#if mk_lang_jumbo_have == 1
#include "mk_iip_cp_client_impl.c"
#endif
#endif
