#ifndef mk_include_guard_mk_iip_cp_session_impl_h
#define mk_include_guard_mk_iip_cp_session_impl_h


#include "mk_iip_cp_client_data.h"
#include "mk_iip_cp_mallocator_global.h"
#include "mk_iip_cp_message.h"
#include "mk_iip_cp_sessioncmd_leaseset_intr.h"
#include "mk_iip_cp_sessioncmd_message_intr.h"
#include "mk_iip_cp_sm_tcp_intr.h"
#include "mk_iip_cp_type.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_types.h"


mk_lang_struct_forward(mk_iip_cp_connection_intr);
mk_lang_struct_forward(mk_iip_cp_session_intr);


struct mk_iip_cp_session_impl_s
{
	mk_iip_cp_session_intr_pt m_session_intr;
	mk_iip_cp_connection_intr_pt m_connection;
	mk_iip_cp_type_sessionid_t m_session_id;
	mk_iip_cp_type_destination_elgamal_dsa_t m_destination;
	mk_lang_types_bool_t m_did_something;
	mk_iip_cp_sessioncmd_leaseset_intr_t m_cmd_leaseset;
	mk_iip_cp_sm_tcp_intrs_t m_sms_tcp;
	mk_iip_cp_sessioncmd_message_intr_t m_cmd_message;
};
typedef struct mk_iip_cp_session_impl_s mk_iip_cp_session_impl_t;
mk_lang_struct_typedef(mk_iip_cp_session_impl);


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_session_impl_rw_allocate(mk_iip_cp_session_impl_ppt const session_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_session_impl_rw_deallocate(mk_iip_cp_session_impl_pt const session_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_session_impl_rw_construct(mk_iip_cp_session_impl_pt const session_impl, mk_iip_cp_session_intr_pt const session_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_session_impl_rw_destruct(mk_iip_cp_session_impl_pt const session_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_session_impl_rw_allocate_and_construct(mk_iip_cp_session_impl_ppt const session_impl, mk_iip_cp_session_intr_pt const session_intr) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_session_impl_rw_destruct_and_deallocate(mk_iip_cp_session_impl_pt const session_impl) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_session_impl_rw_set_connection(mk_iip_cp_session_impl_pt const session_impl, mk_iip_cp_connection_intr_pcpt const connection) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_session_impl_rw_set_session_id(mk_iip_cp_session_impl_pt const session_impl, mk_iip_cp_type_sessionid_pct const session_id) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_session_impl_rw_set_destination(mk_iip_cp_session_impl_pt const session_impl, mk_iip_cp_type_destination_elgamal_dsa_pct const destination) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_iip_cp_connection_intr_pcpt mk_iip_cp_session_impl_rw_get_connection(mk_iip_cp_session_impl_pt const session_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_iip_cp_type_sessionid_pct mk_iip_cp_session_impl_rw_get_session_id(mk_iip_cp_session_impl_pt const session_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_iip_cp_type_destination_elgamal_dsa_pct mk_iip_cp_session_impl_rw_get_destination(mk_iip_cp_session_impl_pt const session_impl) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_bool_t mk_iip_cp_session_impl_rw_did_something(mk_iip_cp_session_impl_pt const session_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_session_impl_rw_tick_single(mk_iip_cp_session_impl_pt const session_impl) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_session_impl_rw_on_msg(mk_iip_cp_session_impl_pt const session_impl, mk_iip_cp_message_pct const message) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_session_impl_rw_make_msg(mk_iip_cp_session_impl_pt const session_impl, mk_iip_cp_message_pt const message) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_session_impl_rw_accept(mk_iip_cp_session_impl_pt const session_impl, mk_iip_cp_client_data_request_accept_pct const request, mk_iip_cp_client_data_response_accept_pt const response) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_session_impl_rw_read_data(mk_iip_cp_session_impl_pt const session_impl, mk_iip_cp_client_data_request_read_data_pct const request, mk_iip_cp_client_data_response_read_data_pt const response) mk_lang_noexcept;


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_session_impls_pr_element_construct_void(mk_iip_cp_session_impl_ppt const session_impl) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_iip_cp_session_impls_pr_element_destruct(mk_iip_cp_session_impl_ppt const session_impl) mk_lang_noexcept;

#define mk_sl_vector_t_name mk_iip_cp_session_impls
#define mk_sl_vector_t_element mk_iip_cp_session_impl_pt
#define mk_sl_vector_t_element_construct_void mk_iip_cp_session_impls_pr_element_construct_void
#define mk_sl_vector_t_element_destruct mk_iip_cp_session_impls_pr_element_destruct
#define mk_sl_vector_t_mallocatorg mk_iip_cp_mallocator_global
#include "mk_sl_vector_inl_fileh.h"
#include "mk_sl_vector_inl_fileu.h"


#if mk_lang_jumbo_have == 1
#include "mk_iip_cp_session_impl.c"
#endif
#endif
