#ifndef mk_include_guard_mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_fileh_h
#define mk_include_guard_mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_fileh_h
#include "mk_iip_cp_connection_impl.h"


enum mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_stage_e
{
	mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_stage_e_get_bandwidth_limits_send,
	mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_stage_e_get_bandwidth_limits_wait,
	mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_stage_e_bandwidth_limits_recv,
	mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_stage_e_bandwidth_limits_wait,
	mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_stage_e_finish,
	mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_stage_e_dummy_end
};
typedef enum mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_stage_e mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_stage_t;
mk_lang_struct_typedef(mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_stage);

struct mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_s
{
	mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_stage_t m_stage;
	mk_iip_cp_client_data_request_get_bandwidth_limits_pct m_request;
	mk_iip_cp_client_data_response_get_bandwidth_limits_pt m_response;
	mk_sl_cui_uint32_t m_request_id;
};
typedef struct mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_s mk_iip_cp_connection_impl_cmd_get_bandwidth_limits_t;
mk_lang_struct_typedef(mk_iip_cp_connection_impl_cmd_get_bandwidth_limits);


#endif
