#ifndef mk_include_guard_mk_iip_cp_connection_impl_cmd_create_session_fileh_h
#define mk_include_guard_mk_iip_cp_connection_impl_cmd_create_session_fileh_h
#include "mk_iip_cp_connection_impl.h"


enum mk_iip_cp_connection_impl_cmd_create_session_stage_e
{
	mk_iip_cp_connection_impl_cmd_create_session_stage_e_create_session_send,
	mk_iip_cp_connection_impl_cmd_create_session_stage_e_create_session_wait,
	mk_iip_cp_connection_impl_cmd_create_session_stage_e_session_status_recv,
	mk_iip_cp_connection_impl_cmd_create_session_stage_e_session_status_wait,
	mk_iip_cp_connection_impl_cmd_create_session_stage_e_request_lease_set_recv,
	mk_iip_cp_connection_impl_cmd_create_session_stage_e_request_lease_set_wait,
	mk_iip_cp_connection_impl_cmd_create_session_stage_e_create_lease_set_send,
	mk_iip_cp_connection_impl_cmd_create_session_stage_e_create_lease_set_wait,
	mk_iip_cp_connection_impl_cmd_create_session_stage_e_finish,
	mk_iip_cp_connection_impl_cmd_create_session_stage_e_dummy_end
};
typedef enum mk_iip_cp_connection_impl_cmd_create_session_stage_e mk_iip_cp_connection_impl_cmd_create_session_stage_t;
mk_lang_struct_typedef(mk_iip_cp_connection_impl_cmd_create_session_stage);

struct mk_iip_cp_connection_impl_cmd_create_session_s
{
	mk_iip_cp_connection_impl_cmd_create_session_stage_t m_stage;
	mk_iip_cp_client_data_request_create_session_pct m_request;
	mk_iip_cp_client_data_response_create_session_pt m_response;
	mk_lang_types_bool_t m_at_least_one;
};
typedef struct mk_iip_cp_connection_impl_cmd_create_session_s mk_iip_cp_connection_impl_cmd_create_session_t;
mk_lang_struct_typedef(mk_iip_cp_connection_impl_cmd_create_session);


#endif
