define(`mk_lib_iip_cp_message_strings_mm_list', `dnl
`accepted', `accepted', dnl
`api_version', `api_version', dnl
`authentication', `authentication', dnl
`available', `available', dnl
`bad_destination', `bad_destination', dnl
`bad_leaseset', `bad_leaseset', dnl
`bad_local_leaseset', `bad_local_leaseset', dnl
`bad_message', `bad_message', dnl
`bad_options', `bad_options', dnl
`bad_session', `bad_session', dnl
`bandwidth_limits', `bandwidth_limits', dnl
`best_effort_failure', `best_effort_failure', dnl
`best_effort_success', `best_effort_success', dnl
`blinding_info', `blinding_info', dnl
`body', `body', dnl
`client_inbound_limit_kbps', `client_inbound_limit_kbps', dnl
`client_outbound_limit_kbps', `client_outbound_limit_kbps', dnl
`create_lease_set', `create_lease_set', dnl
`create_lease_set2', `create_lease_set2', dnl
`create_session', `create_session', dnl
`created', `created', dnl
`creation_date', `creation_date', dnl
`date', `date', dnl
`dest_lookup', `dest_lookup', dnl
`dest_reply', `dest_reply', dnl
`destination', `destination', dnl
`destroy_session', `destroy_session', dnl
`destroyed', `destroyed', dnl
`disconnect', `disconnect', dnl
`end_date', `end_date', dnl
`expired_leaseset', `expired_leaseset', dnl
`failure', `failure', dnl
`future_use_1', `future_use_1', dnl
`future_use_2', `future_use_2', dnl
`future_use_3', `future_use_3', dnl
`future_use_4', `future_use_4', dnl
`future_use_5', `future_use_5', dnl
`future_use_6', `future_use_6', dnl
`future_use_7', `future_use_7', dnl
`future_use_8', `future_use_8', dnl
`future_use_9', `future_use_9', dnl
`get_bandwidth_limits', `get_bandwidth_limits', dnl
`get_date', `get_date', dnl
`guaranteed_failure', `guaranteed_failure', dnl
`guaranteed_success', `guaranteed_success', dnl
`hash', `hash', dnl
`header', `header', dnl
`host_lookup', `host_lookup', dnl
`host_reply', `host_reply', dnl
`hostname', `hostname', dnl
`invalid', `invalid', dnl
`key_enc_pri', `key_enc_pri', dnl
`key_enc_pub', `key_enc_pub', dnl
`key_sgn_pri', `key_sgn_pri', dnl
`key_sgn_pub', `key_sgn_pub', dnl
`leases', `leases', dnl
`leaseset', `leaseset', dnl
`leaseset_decryption_failure', `leaseset_decryption_failure', dnl
`len', `len', dnl
`local_failure', `local_failure', dnl
`local_success', `local_success', dnl
`lookup_password_and_private_key_required', `lookup_password_and_private_key_required', dnl
`lookup_password_required', `lookup_password_required', dnl
`loopback_denied', `loopback_denied', dnl
`message', `message', dnl
`message_expired', `message_expired', dnl
`message_id', `message_id', dnl
`message_payload', `message_payload', dnl
`message_status', `message_status', dnl
`meta_leaseset', `meta_leaseset', dnl
`name', `name', dnl
`network_failure', `network_failure', dnl
`no_leaseset', `no_leaseset', dnl
`no_local_tunnels', `no_local_tunnels', dnl
`nonce', `nonce', dnl
`opptions', `opptions', dnl
`overflow_failure', `overflow_failure', dnl
`payload', `payload', dnl
`private_key_required', `private_key_required', dnl
`reason', `reason', dnl
`receive_message_begin', `receive_message_begin', dnl
`receive_message_end', `receive_message_end', dnl
`reconfigure_session', `reconfigure_session', dnl
`refused', `refused', dnl
`report_abuse', `report_abuse', dnl
`request_id', `request_id', dnl
`request_lease_set', `request_lease_set', dnl
`request_type', `request_type', dnl
`request_variable_lease_set', `request_variable_lease_set', dnl
`result_code', `result_code', dnl
`router_burst_time_seconds', `router_burst_time_seconds', dnl
`router_failure', `router_failure', dnl
`router_hash', `router_hash', dnl
`router_inbound_burst_limit_kbps', `router_inbound_burst_limit_kbps', dnl
`router_inbound_limit_kbps', `router_inbound_limit_kbps', dnl
`router_outbound_burst_limit_kbps', `router_outbound_burst_limit_kbps', dnl
`router_outbound_limit_kbps', `router_outbound_limit_kbps', dnl
`send_message', `send_message', dnl
`send_message_expires', `send_message_expires', dnl
`server_date', `server_date', dnl
`session_config', `session_config', dnl
`session_id', `session_id', dnl
`session_status', `session_status', dnl
`set_date', `set_date', dnl
`size', `size', dnl
`status', `status', dnl
`success', `success', dnl
`timeout_ms', `timeout_ms', dnl
`tunnel_id', `tunnel_id', dnl
`tunnels', `tunnels', dnl
`type', `type', dnl
`unsupported_encryption', `unsupported_encryption', dnl
`updated', `updated', dnl
`version', `version', dnl
`'')dnl
