include(`mk_lang_typedef.m')dnl
#include "mk_lang_concat.h"


#if(!( \
	(defined mk_lib_crypto_alg_stream_t_name) && \
	(defined mk_lib_crypto_alg_stream_t_base_name) && \
1))
#error xxxxxxxxxx
#endif

#define mk_lib_crypto_alg_stream_inl_defd_name mk_lib_crypto_alg_stream_t_name
#define mk_lib_crypto_alg_stream_inl_defd_base_name mk_lib_crypto_alg_stream_t_base_name


#define mk_lib_crypto_alg_stream_inl_defd_base_key_s mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_base_name, _key_s)
#define mk_lib_crypto_alg_stream_inl_defd_base_key_t mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_base_name, _key_t)
#define mk_lib_crypto_alg_stream_inl_defd_base_key_len_v mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_base_name, _key_len_v)

#define mk_lib_crypto_alg_stream_inl_defd_base_msg_s mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_base_name, _msg_s)
#define mk_lib_crypto_alg_stream_inl_defd_base_msg_t mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_base_name, _msg_t)
mm_per_typedef(`#define mk_lib_crypto_alg_stream_inl_defd_base_msg_$1 mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_base_name, _msg_$1)')dnl
#define mk_lib_crypto_alg_stream_inl_defd_base_msg_len_v mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_base_name, _msg_len_v)

#define mk_lib_crypto_alg_stream_inl_defd_base_schedule_s mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_base_name, _schedule_s)
#define mk_lib_crypto_alg_stream_inl_defd_base_schedule_t mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_base_name, _schedule_t)
#define mk_lib_crypto_alg_stream_inl_defd_base_schedule_len_v mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_base_name, _schedule_len_v)

#define mk_lib_crypto_alg_stream_inl_defd_base_schedule_encrypt mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_base_name, _schedule_encrypt)
#define mk_lib_crypto_alg_stream_inl_defd_base_schedule_decrypt mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_base_name, _schedule_decrypt)
#define mk_lib_crypto_alg_stream_inl_defd_base_expand_enc mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_base_name, _expand_enc)
#define mk_lib_crypto_alg_stream_inl_defd_base_expand_dec mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_base_name, _expand_dec)


#define mk_lib_crypto_alg_stream_inl_defd_key_len_e mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _key_len_e)
#define mk_lib_crypto_alg_stream_inl_defd_key_len_t mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _key_len_t)
#define mk_lib_crypto_alg_stream_inl_defd_key_len_v mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _key_len_v)
#define mk_lib_crypto_alg_stream_inl_defd_key_data_u mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _key_data_u)
#define mk_lib_crypto_alg_stream_inl_defd_key_data_t mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _key_data_t)
#define mk_lib_crypto_alg_stream_inl_defd_key mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _key)
#define mk_lib_crypto_alg_stream_inl_defd_key_s mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _key_s)
#define mk_lib_crypto_alg_stream_inl_defd_key_t mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _key_t)
mm_per_typedef(`#define mk_lib_crypto_alg_stream_inl_defd_key_$1 mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _key_$1)')dnl

#define mk_lib_crypto_alg_stream_inl_defd_msg_len_e mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _msg_len_e)
#define mk_lib_crypto_alg_stream_inl_defd_msg_len_t mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _msg_len_t)
#define mk_lib_crypto_alg_stream_inl_defd_msg_len_v mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _msg_len_v)
#define mk_lib_crypto_alg_stream_inl_defd_msg_data_u mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _msg_data_u)
#define mk_lib_crypto_alg_stream_inl_defd_msg_data_t mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _msg_data_t)
#define mk_lib_crypto_alg_stream_inl_defd_msg mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _msg)
#define mk_lib_crypto_alg_stream_inl_defd_msg_s mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _msg_s)
#define mk_lib_crypto_alg_stream_inl_defd_msg_t mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _msg_t)
mm_per_typedef(`#define mk_lib_crypto_alg_stream_inl_defd_msg_$1 mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _msg_$1)')dnl

#define mk_lib_crypto_alg_stream_inl_defd_schedule_len_e mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _schedule_len_e)
#define mk_lib_crypto_alg_stream_inl_defd_schedule_len_t mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _schedule_len_t)
#define mk_lib_crypto_alg_stream_inl_defd_schedule_len_v mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _schedule_len_v)
#define mk_lib_crypto_alg_stream_inl_defd_schedule_data_u mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _schedule_data_u)
#define mk_lib_crypto_alg_stream_inl_defd_schedule_data_t mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _schedule_data_t)
#define mk_lib_crypto_alg_stream_inl_defd_schedule mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _schedule)
#define mk_lib_crypto_alg_stream_inl_defd_schedule_s mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _schedule_s)
#define mk_lib_crypto_alg_stream_inl_defd_schedule_t mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _schedule_t)
mm_per_typedef(`#define mk_lib_crypto_alg_stream_inl_defd_schedule_$1 mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _schedule_$1)')dnl


#define mk_lib_crypto_alg_stream_inl_defd mk_lib_crypto_alg_stream_inl_defd_name
#define mk_lib_crypto_alg_stream_inl_defd_s mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _s)
#define mk_lib_crypto_alg_stream_inl_defd_t mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _t)
mm_per_typedef(`#define mk_lib_crypto_alg_stream_inl_defd_$1 mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _$1)')dnl

#define mk_lib_crypto_alg_stream_inl_defd_rw_construct_encrypt mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _rw_construct_encrypt)
#define mk_lib_crypto_alg_stream_inl_defd_rw_construct_decrypt mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _rw_construct_decrypt)
#define mk_lib_crypto_alg_stream_inl_defd_rw_encrypt mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _rw_encrypt)
#define mk_lib_crypto_alg_stream_inl_defd_rw_decrypt mk_lang_concat(mk_lib_crypto_alg_stream_inl_defd_name, _rw_decrypt)
