include(`mk_lang_typedef.m')dnl
#include "mk_lang_concat.h"


#if(!( \
	(defined mk_lib_crypto_mode_stream_t_name) && \
	(defined mk_lib_crypto_mode_stream_t_base_name) && \
1))
#error xxxxxxxxxx
#endif

#define mk_lib_crypto_mode_stream_inl_defd_name mk_lib_crypto_mode_stream_t_name
#define mk_lib_crypto_mode_stream_inl_defd_base_name mk_lib_crypto_mode_stream_t_base_name


#define mk_lib_crypto_mode_stream_inl_defd_base_iv_s mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _iv_s)
#define mk_lib_crypto_mode_stream_inl_defd_base_iv_t mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _iv_t)
#define mk_lib_crypto_mode_stream_inl_defd_base_iv_len_v mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _iv_len_v)
#define mk_lib_crypto_mode_stream_inl_defd_base_iv_len_d mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _iv_len_d)

#define mk_lib_crypto_mode_stream_inl_defd_base_key_s mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _key_s)
#define mk_lib_crypto_mode_stream_inl_defd_base_key_t mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _key_t)
#define mk_lib_crypto_mode_stream_inl_defd_base_key_len_v mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _key_len_v)

#define mk_lib_crypto_mode_stream_inl_defd_base_msg_s mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _msg_s)
#define mk_lib_crypto_mode_stream_inl_defd_base_msg_t mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _msg_t)
mm_per_typedef(`#define mk_lib_crypto_mode_stream_inl_defd_base_msg_$1 mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _msg_$1)')dnl
#define mk_lib_crypto_mode_stream_inl_defd_base_msg_len_v mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _msg_len_v)

#define mk_lib_crypto_mode_stream_inl_defd_base_alg_s mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _alg_s)
#define mk_lib_crypto_mode_stream_inl_defd_base_alg_t mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _alg_t)
mm_per_typedef(`#define mk_lib_crypto_mode_stream_inl_defd_base_alg_$1 mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _alg_$1)')dnl
#define mk_lib_crypto_mode_stream_inl_defd_base_alg_len_v mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _alg_len_v)

#define mk_lib_crypto_mode_stream_inl_defd_base_rw_set_iv mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _rw_set_iv)
#define mk_lib_crypto_mode_stream_inl_defd_base_rw_set_key_enc mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _rw_set_key_enc)
#define mk_lib_crypto_mode_stream_inl_defd_base_rw_set_key_dec mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _rw_set_key_dec)
#define mk_lib_crypto_mode_stream_inl_defd_base_rw_encrypt mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _rw_encrypt)
#define mk_lib_crypto_mode_stream_inl_defd_base_rw_decrypt mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_base_name, _rw_decrypt)


#define mk_lib_crypto_mode_stream_inl_defd_iv_len_d (mk_lib_crypto_mode_stream_inl_defd_base_iv_len_d)
#define mk_lib_crypto_mode_stream_inl_defd_iv_len_e mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _iv_len_e)
#define mk_lib_crypto_mode_stream_inl_defd_iv_len_t mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _iv_len_t)
#define mk_lib_crypto_mode_stream_inl_defd_iv_len_v mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _iv_len_v)
#define mk_lib_crypto_mode_stream_inl_defd_iv_data_u mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _iv_data_u)
#define mk_lib_crypto_mode_stream_inl_defd_iv_data_t mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _iv_data_t)
#define mk_lib_crypto_mode_stream_inl_defd_iv mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _iv)
#define mk_lib_crypto_mode_stream_inl_defd_iv_s mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _iv_s)
#define mk_lib_crypto_mode_stream_inl_defd_iv_t mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _iv_t)
mm_per_typedef(`#define mk_lib_crypto_mode_stream_inl_defd_iv_$1 mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _iv_$1)')dnl

#define mk_lib_crypto_mode_stream_inl_defd_key_len_e mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _key_len_e)
#define mk_lib_crypto_mode_stream_inl_defd_key_len_t mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _key_len_t)
#define mk_lib_crypto_mode_stream_inl_defd_key_len_v mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _key_len_v)
#define mk_lib_crypto_mode_stream_inl_defd_key_data_u mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _key_data_u)
#define mk_lib_crypto_mode_stream_inl_defd_key_data_t mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _key_data_t)
#define mk_lib_crypto_mode_stream_inl_defd_key mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _key)
#define mk_lib_crypto_mode_stream_inl_defd_key_s mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _key_s)
#define mk_lib_crypto_mode_stream_inl_defd_key_t mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _key_t)
mm_per_typedef(`#define mk_lib_crypto_mode_stream_inl_defd_key_$1 mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _key_$1)')dnl

#define mk_lib_crypto_mode_stream_inl_defd_msg_len_e mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _msg_len_e)
#define mk_lib_crypto_mode_stream_inl_defd_msg_len_t mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _msg_len_t)
#define mk_lib_crypto_mode_stream_inl_defd_msg_len_v mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _msg_len_v)
#define mk_lib_crypto_mode_stream_inl_defd_msg_data_u mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _msg_data_u)
#define mk_lib_crypto_mode_stream_inl_defd_msg_data_t mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _msg_data_t)
#define mk_lib_crypto_mode_stream_inl_defd_msg mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _msg)
#define mk_lib_crypto_mode_stream_inl_defd_msg_s mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _msg_s)
#define mk_lib_crypto_mode_stream_inl_defd_msg_t mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _msg_t)
mm_per_typedef(`#define mk_lib_crypto_mode_stream_inl_defd_msg_$1 mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _msg_$1)')dnl


#define mk_lib_crypto_mode_stream_inl_defd mk_lib_crypto_mode_stream_inl_defd_name
#define mk_lib_crypto_mode_stream_inl_defd_s mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _s)
#define mk_lib_crypto_mode_stream_inl_defd_t mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _t)
mm_per_typedef(`#define mk_lib_crypto_mode_stream_inl_defd_$1 mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _$1)')dnl

#define mk_lib_crypto_mode_stream_inl_defd_rw_set_iv mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _rw_set_iv)
#define mk_lib_crypto_mode_stream_inl_defd_rw_set_key_enc mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _rw_set_key_enc)
#define mk_lib_crypto_mode_stream_inl_defd_rw_set_key_dec mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _rw_set_key_dec)
#define mk_lib_crypto_mode_stream_inl_defd_rw_encrypt mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _rw_encrypt)
#define mk_lib_crypto_mode_stream_inl_defd_rw_decrypt mk_lang_concat(mk_lib_crypto_mode_stream_inl_defd_name, _rw_decrypt)
