#ifndef mk_include_guard_mk_lib_crypto_hash_block_blake2b_512_h
#define mk_include_guard_mk_lib_crypto_hash_block_blake2b_512_h

/* RFC 7693 */

#include "mk_lang_alignas.h"
#include "mk_lang_constexpr.h"
#include "mk_lang_countof.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_stringify.h"
#include "mk_lang_types.h"
#include "mk_lib_crypto_hash_block_blake2b_base.h"
#include "mk_sl_cui_uint8.h"


#define mk_lib_crypto_hash_block_blake2b_512_block_len_d 128
#define mk_lib_crypto_hash_block_blake2b_512_digest_len_d 64
#define mk_lib_crypto_hash_block_blake2b_512_name_def BLAKE2b-512
enum mk_lib_crypto_hash_block_blake2b_512_block_len_e{ mk_lib_crypto_hash_block_blake2b_512_block_len_v = mk_lib_crypto_hash_block_blake2b_512_block_len_d }; typedef enum mk_lib_crypto_hash_block_blake2b_512_block_len_e mk_lib_crypto_hash_block_blake2b_512_block_len_t;
enum mk_lib_crypto_hash_block_blake2b_512_digest_len_e{ mk_lib_crypto_hash_block_blake2b_512_digest_len_v = mk_lib_crypto_hash_block_blake2b_512_digest_len_d }; typedef enum mk_lib_crypto_hash_block_blake2b_512_digest_len_e mk_lib_crypto_hash_block_blake2b_512_digest_len_t;
mk_lang_constexpr_static_inline mk_lang_types_pchar_t const mk_lib_crypto_hash_block_blake2b_512_name_str_buf[] = mk_lang_stringify(mk_lib_crypto_hash_block_blake2b_512_name_def);
mk_lang_constexpr_static_inline mk_lang_types_sint_t const mk_lib_crypto_hash_block_blake2b_512_name_str_len = mk_lang_countstr(mk_lib_crypto_hash_block_blake2b_512_name_str_buf);


union mk_lib_crypto_hash_block_blake2b_512_block_data_u
{
	mk_lang_alignas(mk_lib_crypto_hash_block_blake2b_512_block_len_v) mk_sl_cui_uint8_t m_uint8s[mk_lib_crypto_hash_block_blake2b_512_block_len_v];
	mk_lang_types_ulllong_t m_align;
};
typedef union mk_lib_crypto_hash_block_blake2b_512_block_data_u mk_lib_crypto_hash_block_blake2b_512_block_data_t;
struct mk_lib_crypto_hash_block_blake2b_512_block_s
{
	mk_lib_crypto_hash_block_blake2b_512_block_data_t m_data;
};
typedef struct mk_lib_crypto_hash_block_blake2b_512_block_s mk_lib_crypto_hash_block_blake2b_512_block_t;
typedef mk_lib_crypto_hash_block_blake2b_512_block_t const mk_lib_crypto_hash_block_blake2b_512_block_ct;
typedef mk_lib_crypto_hash_block_blake2b_512_block_t* mk_lib_crypto_hash_block_blake2b_512_block_pt;
typedef mk_lib_crypto_hash_block_blake2b_512_block_t const* mk_lib_crypto_hash_block_blake2b_512_block_pct;

union mk_lib_crypto_hash_block_blake2b_512_digest_data_u
{
	mk_lang_alignas(mk_lib_crypto_hash_block_blake2b_512_digest_len_v) mk_sl_cui_uint8_t m_uint8s[mk_lib_crypto_hash_block_blake2b_512_digest_len_v];
	mk_lang_types_ulllong_t m_align;
};
typedef union mk_lib_crypto_hash_block_blake2b_512_digest_data_u mk_lib_crypto_hash_block_blake2b_512_digest_data_t;
struct mk_lib_crypto_hash_block_blake2b_512_digest_s
{
	mk_lib_crypto_hash_block_blake2b_512_digest_data_t m_data;
};
typedef struct mk_lib_crypto_hash_block_blake2b_512_digest_s mk_lib_crypto_hash_block_blake2b_512_digest_t;
typedef mk_lib_crypto_hash_block_blake2b_512_digest_t const mk_lib_crypto_hash_block_blake2b_512_digest_ct;
typedef mk_lib_crypto_hash_block_blake2b_512_digest_t* mk_lib_crypto_hash_block_blake2b_512_digest_pt;
typedef mk_lib_crypto_hash_block_blake2b_512_digest_t const* mk_lib_crypto_hash_block_blake2b_512_digest_pct;


struct mk_lib_crypto_hash_block_blake2b_512_s
{
	mk_lib_crypto_hash_block_blake2b_base_t m_blake2b_base;
};
typedef struct mk_lib_crypto_hash_block_blake2b_512_s mk_lib_crypto_hash_block_blake2b_512_t;
typedef mk_lib_crypto_hash_block_blake2b_512_t const mk_lib_crypto_hash_block_blake2b_512_ct;
typedef mk_lib_crypto_hash_block_blake2b_512_t* mk_lib_crypto_hash_block_blake2b_512_pt;
typedef mk_lib_crypto_hash_block_blake2b_512_t const* mk_lib_crypto_hash_block_blake2b_512_pct;


mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_hash_block_blake2b_512_init(mk_lib_crypto_hash_block_blake2b_512_pt const blake2b_512) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_hash_block_blake2b_512_append_blocks(mk_lib_crypto_hash_block_blake2b_512_pt const blake2b_512, mk_lib_crypto_hash_block_blake2b_512_block_pct const pblocks, mk_lang_types_usize_t const nblocks) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_hash_block_blake2b_512_finish(mk_lib_crypto_hash_block_blake2b_512_pt const blake2b_512, mk_lib_crypto_hash_block_blake2b_512_block_pt const block, mk_lang_types_sint_t const idx, mk_lib_crypto_hash_block_blake2b_512_digest_pt const digest) mk_lang_noexcept;


#if mk_lang_jumbo_have
#include "mk_lib_crypto_hash_block_blake2b_512.c"
#endif
#endif
