define(`mk_lib_iip_cp_message_create_session_strings_mm_list', `dnl
`client_message_timeout', `clientMessageTimeout', dnl
`crypto_low_tag_threshold', `crypto.lowTagThreshold', dnl
`crypto_ratchet_inbound_tags', `crypto.ratchet.inboundTags', dnl
`crypto_ratchet_outbound_tags', `crypto.ratchet.outboundTags', dnl
`crypto_tags_to_send', `crypto.tagsToSend', dnl
`explicit_peers', `explicitPeers', dnl
`i2cp_dont_publish_lease_set', `i2cp.dontPublishLeaseSet', dnl
`i2cp_fast_receive', `i2cp.fastReceive', dnl
`i2cp_lease_set_auth_type', `i2cp.leaseSetAuthType', dnl
`i2cp_lease_set_enc_type', `i2cp.leaseSetEncType', dnl
`i2cp_lease_set_offline_expiration', `i2cp.leaseSetOfflineExpiration', dnl
`i2cp_lease_set_offline_signature', `i2cp.leaseSetOfflineSignature', dnl
`i2cp_lease_set_priv_key', `i2cp.leaseSetPrivKey', dnl
`i2cp_lease_set_secret', `i2cp.leaseSetSecret', dnl
`i2cp_lease_set_transient_public_key', `i2cp.leaseSetTransientPublicKey', dnl
`i2cp_lease_set_type', `i2cp.leaseSetType', dnl
`i2cp_message_reliability', `i2cp.messageReliability', dnl
`i2cp_password', `i2cp.password', dnl
`i2cp_username', `i2cp.username', dnl
`inbound_allow_zero_hop', `inbound.allowZeroHop', dnl
`inbound_backup_quantity', `inbound.backupQuantity', dnl
`inbound_ip_restriction', `inbound.IPRestriction', dnl
`inbound_length', `inbound.length', dnl
`inbound_length_variance', `inbound.lengthVariance', dnl
`inbound_nickname', `inbound.nickname', dnl
`inbound_quantity', `inbound.quantity', dnl
`inbound_random_key', `inbound.randomKey', dnl
`outbound_allow_zero_hop', `outbound.allowZeroHop', dnl
`outbound_backup_quantity', `outbound.backupQuantity', dnl
`outbound_ip_restriction', `outbound.IPRestriction', dnl
`outbound_length', `outbound.length', dnl
`outbound_length_variance', `outbound.lengthVariance', dnl
`outbound_nickname', `outbound.nickname', dnl
`outbound_priority', `outbound.priority', dnl
`outbound_quantity', `outbound.quantity', dnl
`outbound_random_key', `outbound.randomKey', dnl
`should_bundle_reply_info', `shouldBundleReplyInfo', dnl
dnl
`false', `false', dnl
`true', `true', dnl
`best_effort', `BestEffort', dnl
`none', `None', dnl
`'')dnl
