#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"
#include "mk_sl_cui_uint8.h"


#include "mk_lib_crypto_mode_cbc_inl_defd.h"


enum mk_lib_crypto_mode_cbc_inl_defd_iv_len_e{ mk_lib_crypto_mode_cbc_inl_defd_iv_len_v = mk_lib_crypto_mode_cbc_inl_defd_iv_len_d }; typedef enum mk_lib_crypto_mode_cbc_inl_defd_iv_len_e mk_lib_crypto_mode_cbc_inl_defd_iv_len_t;
enum mk_lib_crypto_mode_cbc_inl_defd_msg_len_e{ mk_lib_crypto_mode_cbc_inl_defd_msg_len_v = mk_lib_crypto_mode_cbc_inl_defd_msg_len_d }; typedef enum mk_lib_crypto_mode_cbc_inl_defd_msg_len_e mk_lib_crypto_mode_cbc_inl_defd_msg_len_t;
enum mk_lib_crypto_mode_cbc_inl_defd_key_len_e{ mk_lib_crypto_mode_cbc_inl_defd_key_len_v = mk_lib_crypto_mode_cbc_inl_defd_key_len_d }; typedef enum mk_lib_crypto_mode_cbc_inl_defd_key_len_e mk_lib_crypto_mode_cbc_inl_defd_key_len_t;
enum mk_lib_crypto_mode_cbc_inl_defd_schedule_len_e{ mk_lib_crypto_mode_cbc_inl_defd_schedule_len_v = mk_lib_crypto_mode_cbc_inl_defd_schedule_len_d }; typedef enum mk_lib_crypto_mode_cbc_inl_defd_schedule_len_e mk_lib_crypto_mode_cbc_inl_defd_schedule_len_t;


union mk_lib_crypto_mode_cbc_inl_defd_iv_data_u
{
	mk_lib_crypto_mode_cbc_inl_defd_base_msg_t m_base;
	mk_sl_cui_uint8_t m_uint8s[mk_lib_crypto_mode_cbc_inl_defd_iv_len_v];
	mk_lang_types_ulllong_t m_align;
};
typedef union mk_lib_crypto_mode_cbc_inl_defd_iv_data_u mk_lib_crypto_mode_cbc_inl_defd_iv_data_t;
struct mk_lib_crypto_mode_cbc_inl_defd_iv_s
{
	mk_lib_crypto_mode_cbc_inl_defd_iv_data_t m_data;
};
typedef struct mk_lib_crypto_mode_cbc_inl_defd_iv_s mk_lib_crypto_mode_cbc_inl_defd_iv_t;
mk_lang_typedef(mk_lib_crypto_mode_cbc_inl_defd_iv);

union mk_lib_crypto_mode_cbc_inl_defd_msg_data_u
{
	mk_lib_crypto_mode_cbc_inl_defd_base_msg_t m_base;
	mk_sl_cui_uint8_t m_uint8s[mk_lib_crypto_mode_cbc_inl_defd_msg_len_v];
	mk_lang_types_ulllong_t m_align;
};
typedef union mk_lib_crypto_mode_cbc_inl_defd_msg_data_u mk_lib_crypto_mode_cbc_inl_defd_msg_data_t;
struct mk_lib_crypto_mode_cbc_inl_defd_msg_s
{
	mk_lib_crypto_mode_cbc_inl_defd_msg_data_t m_data;
};
typedef struct mk_lib_crypto_mode_cbc_inl_defd_msg_s mk_lib_crypto_mode_cbc_inl_defd_msg_t;
mk_lang_typedef(mk_lib_crypto_mode_cbc_inl_defd_msg);

union mk_lib_crypto_mode_cbc_inl_defd_key_data_u
{
	mk_lib_crypto_mode_cbc_inl_defd_base_key_t m_base;
	mk_sl_cui_uint8_t m_uint8s[mk_lib_crypto_mode_cbc_inl_defd_key_len_v];
	mk_lang_types_ulllong_t m_align;
};
typedef union mk_lib_crypto_mode_cbc_inl_defd_key_data_u mk_lib_crypto_mode_cbc_inl_defd_key_data_t;
struct mk_lib_crypto_mode_cbc_inl_defd_key_s
{
	mk_lib_crypto_mode_cbc_inl_defd_key_data_t m_data;
};
typedef struct mk_lib_crypto_mode_cbc_inl_defd_key_s mk_lib_crypto_mode_cbc_inl_defd_key_t;
mk_lang_typedef(mk_lib_crypto_mode_cbc_inl_defd_key);

union mk_lib_crypto_mode_cbc_inl_defd_schedule_data_u
{
	mk_lib_crypto_mode_cbc_inl_defd_base_schedule_t m_base;
	mk_sl_cui_uint8_t m_uint8s[mk_lib_crypto_mode_cbc_inl_defd_schedule_len_v];
	mk_lang_types_ulllong_t m_align;
};
typedef union mk_lib_crypto_mode_cbc_inl_defd_schedule_data_u mk_lib_crypto_mode_cbc_inl_defd_schedule_data_t;
struct mk_lib_crypto_mode_cbc_inl_defd_schedule_s
{
	mk_lib_crypto_mode_cbc_inl_defd_schedule_data_t m_data;
};
typedef struct mk_lib_crypto_mode_cbc_inl_defd_schedule_s mk_lib_crypto_mode_cbc_inl_defd_schedule_t;
mk_lang_typedef(mk_lib_crypto_mode_cbc_inl_defd_schedule);

struct mk_lib_crypto_mode_cbc_inl_defd_alg_s
{
	mk_lib_crypto_mode_cbc_inl_defd_schedule_t m_schedule;
	mk_lib_crypto_mode_cbc_inl_defd_iv_t m_iv;
};
typedef struct mk_lib_crypto_mode_cbc_inl_defd_alg_s mk_lib_crypto_mode_cbc_inl_defd_alg_t;
mk_lang_typedef(mk_lib_crypto_mode_cbc_inl_defd_alg);


mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_mode_cbc_inl_defd_rw_set_iv(mk_lib_crypto_mode_cbc_inl_defd_alg_pt const alg, mk_lib_crypto_mode_cbc_inl_defd_iv_pct const iv) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_mode_cbc_inl_defd_rw_set_key_enc(mk_lib_crypto_mode_cbc_inl_defd_alg_pt const alg, mk_lib_crypto_mode_cbc_inl_defd_key_pct const key) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_mode_cbc_inl_defd_rw_set_key_dec(mk_lib_crypto_mode_cbc_inl_defd_alg_pt const alg, mk_lib_crypto_mode_cbc_inl_defd_key_pct const key) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_mode_cbc_inl_defd_rw_encrypt(mk_lib_crypto_mode_cbc_inl_defd_alg_pt const alg, mk_lib_crypto_mode_cbc_inl_defd_msg_pct const inputs, mk_lib_crypto_mode_cbc_inl_defd_msg_pt const outputs, mk_lang_types_usize_t const count) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_mode_cbc_inl_defd_rw_decrypt(mk_lib_crypto_mode_cbc_inl_defd_alg_pt const alg, mk_lib_crypto_mode_cbc_inl_defd_msg_pct const inputs, mk_lib_crypto_mode_cbc_inl_defd_msg_pt const outputs, mk_lang_types_usize_t const count) mk_lang_noexcept;


#include "mk_lib_crypto_mode_cbc_inl_defu.h"
