#include "mk_lang_concat.h"


#if(!( \
	(defined mk_lib_crypto_hash_stream_t_name) && \
	((defined mk_lib_crypto_hash_stream_t_padding && ((mk_lib_crypto_hash_stream_t_padding) == 0 || (mk_lib_crypto_hash_stream_t_padding) == 1)) || !defined mk_lib_crypto_hash_stream_t_padding) && \
1))
#error xxxxxxxxxx
#endif


#define mk_lib_crypto_hash_stream_inl_defd_name mk_lib_crypto_hash_stream_t_name
#if defined mk_lib_crypto_hash_stream_t_padding
#define mk_lib_crypto_hash_stream_inl_defd_padding (mk_lib_crypto_hash_stream_t_padding)
#else
#define mk_lib_crypto_hash_stream_inl_defd_padding 1
#endif


#define mk_lib_crypto_hash_stream_inl_defd_base_prefix mk_lang_concat(mk_lib_crypto_hash_block_, mk_lib_crypto_hash_stream_inl_defd_name)

#define mk_lib_crypto_hash_stream_inl_defd_base_block_len_e mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _block_len_e)
#define mk_lib_crypto_hash_stream_inl_defd_base_block_len_t mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _block_len_t)
#define mk_lib_crypto_hash_stream_inl_defd_base_block_len_v mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _block_len_v)

#define mk_lib_crypto_hash_stream_inl_defd_base_digest_len_e mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _digest_len_e)
#define mk_lib_crypto_hash_stream_inl_defd_base_digest_len_t mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _digest_len_t)
#define mk_lib_crypto_hash_stream_inl_defd_base_digest_len_v mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _digest_len_v)

#define mk_lib_crypto_hash_stream_inl_defd_base_block_t mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _block_t)
#define mk_lib_crypto_hash_stream_inl_defd_base_block_ct mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _block_ct)
#define mk_lib_crypto_hash_stream_inl_defd_base_block_pt mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _block_pt)
#define mk_lib_crypto_hash_stream_inl_defd_base_block_pct mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _block_pct)

#define mk_lib_crypto_hash_stream_inl_defd_base_digest_t mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _digest_t)
#define mk_lib_crypto_hash_stream_inl_defd_base_digest_ct mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _digest_ct)
#define mk_lib_crypto_hash_stream_inl_defd_base_digest_pt mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _digest_pt)
#define mk_lib_crypto_hash_stream_inl_defd_base_digest_pct mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _digest_pct)

#define mk_lib_crypto_hash_stream_inl_defd_base_t mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _t)
#define mk_lib_crypto_hash_stream_inl_defd_base_ct mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _ct)
#define mk_lib_crypto_hash_stream_inl_defd_base_pt mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _pt)
#define mk_lib_crypto_hash_stream_inl_defd_base_pct mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _pct)

#define mk_lib_crypto_hash_stream_inl_defd_base_init mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _init)
#define mk_lib_crypto_hash_stream_inl_defd_base_append_blocks mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _append_blocks)
#define mk_lib_crypto_hash_stream_inl_defd_base_finish mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_base_prefix, _finish)


#define mk_lib_crypto_hash_stream_inl_defd_prefix mk_lang_concat(mk_lib_crypto_hash_stream_, mk_lib_crypto_hash_stream_inl_defd_name)

#define mk_lib_crypto_hash_stream_inl_defd_digest_len_e mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _digest_len_e)
#define mk_lib_crypto_hash_stream_inl_defd_digest_len_t mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _digest_len_t)
#define mk_lib_crypto_hash_stream_inl_defd_digest_len_v mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _digest_len_v)

#define mk_lib_crypto_hash_stream_inl_defd_block_t mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _block_t)
#define mk_lib_crypto_hash_stream_inl_defd_block_ct mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _block_ct)
#define mk_lib_crypto_hash_stream_inl_defd_block_pt mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _block_pt)
#define mk_lib_crypto_hash_stream_inl_defd_block_pct mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _block_pct)

#define mk_lib_crypto_hash_stream_inl_defd_digest_t mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _digest_t)
#define mk_lib_crypto_hash_stream_inl_defd_digest_ct mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _digest_ct)
#define mk_lib_crypto_hash_stream_inl_defd_digest_pt mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _digest_pt)
#define mk_lib_crypto_hash_stream_inl_defd_digest_pct mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _digest_pct)

#define mk_lib_crypto_hash_stream_inl_defd_s mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _s)
#define mk_lib_crypto_hash_stream_inl_defd_t mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _t)
#define mk_lib_crypto_hash_stream_inl_defd_ct mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _ct)
#define mk_lib_crypto_hash_stream_inl_defd_pt mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _pt)
#define mk_lib_crypto_hash_stream_inl_defd_pct mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _pct)

#define mk_lib_crypto_hash_stream_inl_defd_init mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _init)
#define mk_lib_crypto_hash_stream_inl_defd_append_u8s mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _append_u8s)
#define mk_lib_crypto_hash_stream_inl_defd_finish mk_lang_concat(mk_lib_crypto_hash_stream_inl_defd_prefix, _finish)
