#ifndef mk_include_guard_mk_lib_crypto_hash_block_sha3_224_h
#define mk_include_guard_mk_lib_crypto_hash_block_sha3_224_h

/* NIST FIPS PUB 202 */

#include "mk_lang_alignas.h"
#include "mk_lang_constexpr.h"
#include "mk_lang_countof.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_pow2.h"
#include "mk_lang_stringify.h"
#include "mk_lang_types.h"
#include "mk_lib_crypto_hash_block_sha3_base.h"
#include "mk_sl_cui_uint64.h"
#include "mk_sl_cui_uint8.h"


#define mk_lib_crypto_hash_block_sha3_224_block_len_d 144
#define mk_lib_crypto_hash_block_sha3_224_digest_len_d 28
#define mk_lib_crypto_hash_block_sha3_224_name_def SHA3-224
enum mk_lib_crypto_hash_block_sha3_224_block_len_e{ mk_lib_crypto_hash_block_sha3_224_block_len_v = mk_lib_crypto_hash_block_sha3_224_block_len_d }; typedef enum mk_lib_crypto_hash_block_sha3_224_block_len_e mk_lib_crypto_hash_block_sha3_224_block_len_t;
enum mk_lib_crypto_hash_block_sha3_224_digest_len_e{ mk_lib_crypto_hash_block_sha3_224_digest_len_v = mk_lib_crypto_hash_block_sha3_224_digest_len_d }; typedef enum mk_lib_crypto_hash_block_sha3_224_digest_len_e mk_lib_crypto_hash_block_sha3_224_digest_len_t;
mk_lang_constexpr_static_inline mk_lang_types_pchar_t const mk_lib_crypto_hash_block_sha3_224_name_str_buf[] = mk_lang_stringify(mk_lib_crypto_hash_block_sha3_224_name_def);
mk_lang_constexpr_static_inline mk_lang_types_sint_t const mk_lib_crypto_hash_block_sha3_224_name_str_len = mk_lang_countstr(mk_lib_crypto_hash_block_sha3_224_name_str_buf);


union mk_lib_crypto_hash_block_sha3_224_block_data_u
{
	mk_lang_alignas(16) mk_sl_cui_uint8_t m_uint8s[mk_lib_crypto_hash_block_sha3_224_block_len_v];
	mk_sl_cui_uint64_t m_align;
};
typedef union mk_lib_crypto_hash_block_sha3_224_block_data_u mk_lib_crypto_hash_block_sha3_224_block_data_t;
struct mk_lib_crypto_hash_block_sha3_224_block_s
{
	mk_lib_crypto_hash_block_sha3_224_block_data_t m_data;
};
typedef struct mk_lib_crypto_hash_block_sha3_224_block_s mk_lib_crypto_hash_block_sha3_224_block_t;
typedef mk_lib_crypto_hash_block_sha3_224_block_t const mk_lib_crypto_hash_block_sha3_224_block_ct;
typedef mk_lib_crypto_hash_block_sha3_224_block_t* mk_lib_crypto_hash_block_sha3_224_block_pt;
typedef mk_lib_crypto_hash_block_sha3_224_block_t const* mk_lib_crypto_hash_block_sha3_224_block_pct;

union mk_lib_crypto_hash_block_sha3_224_digest_data_u
{
	mk_lang_alignas(mk_lang_pow2_roundup(mk_lib_crypto_hash_block_sha3_224_digest_len_v)) mk_sl_cui_uint8_t m_uint8s[mk_lib_crypto_hash_block_sha3_224_digest_len_v];
	mk_lang_types_ulllong_t m_align;
};
typedef union mk_lib_crypto_hash_block_sha3_224_digest_data_u mk_lib_crypto_hash_block_sha3_224_digest_data_t;
struct mk_lib_crypto_hash_block_sha3_224_digest_s
{
	mk_lib_crypto_hash_block_sha3_224_digest_data_t m_data;
};
typedef struct mk_lib_crypto_hash_block_sha3_224_digest_s mk_lib_crypto_hash_block_sha3_224_digest_t;
typedef mk_lib_crypto_hash_block_sha3_224_digest_t const mk_lib_crypto_hash_block_sha3_224_digest_ct;
typedef mk_lib_crypto_hash_block_sha3_224_digest_t* mk_lib_crypto_hash_block_sha3_224_digest_pt;
typedef mk_lib_crypto_hash_block_sha3_224_digest_t const* mk_lib_crypto_hash_block_sha3_224_digest_pct;


struct mk_lib_crypto_hash_block_sha3_224_s
{
	mk_lib_crypto_hash_block_sha3_base_t m_sha3_base;
};
typedef struct mk_lib_crypto_hash_block_sha3_224_s mk_lib_crypto_hash_block_sha3_224_t;
typedef mk_lib_crypto_hash_block_sha3_224_t const mk_lib_crypto_hash_block_sha3_224_ct;
typedef mk_lib_crypto_hash_block_sha3_224_t* mk_lib_crypto_hash_block_sha3_224_pt;
typedef mk_lib_crypto_hash_block_sha3_224_t const* mk_lib_crypto_hash_block_sha3_224_pct;


mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_hash_block_sha3_224_init(mk_lib_crypto_hash_block_sha3_224_pt const sha3_224) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_hash_block_sha3_224_append_blocks(mk_lib_crypto_hash_block_sha3_224_pt const sha3_224, mk_lib_crypto_hash_block_sha3_224_block_pct const pblocks, mk_lang_types_usize_t const nblocks) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_hash_block_sha3_224_finish(mk_lib_crypto_hash_block_sha3_224_pt const sha3_224, mk_lib_crypto_hash_block_sha3_224_block_pt const block, mk_lang_types_sint_t const idx, mk_lib_crypto_hash_block_sha3_224_digest_pt const digest) mk_lang_noexcept;


#if mk_lang_jumbo_have == 1
#include "mk_lib_crypto_hash_block_sha3_224.c"
#endif
#endif
