



























#undef mk_lang_num_longdivmod_t_endian


#undef mk_lang_num_longdivmod_t_alg


#undef mk_lang_num_longdivmod_inl_defd_tn1_sizebits_d


#undef mk_lang_num_longdivmod_inl_defd_tn2_sizebits_d


#undef mk_lang_num_longdivmod_inl_defd_tn3_sizebits_d



#undef mk_lang_num_longdivmod_inl_defd_name
#undef mk_lang_num_longdivmod_inl_defd_tn1
#undef mk_lang_num_longdivmod_inl_defd_tn2
#undef mk_lang_num_longdivmod_inl_defd_tn3
#undef mk_lang_num_longdivmod_inl_defd_lena
#undef mk_lang_num_longdivmod_inl_defd_lenb
#undef mk_lang_num_longdivmod_inl_defd_endian
#undef mk_lang_num_longdivmod_inl_defd_alg
#undef mk_lang_num_longdivmod_inl_defd_tn1s_to_tn2
#undef mk_lang_num_longdivmod_inl_defd_tn1d_to_tn2
#undef mk_lang_num_longdivmod_inl_defd_tn1d_to_tn3
#undef mk_lang_num_longdivmod_inl_defd_tn1t_to_tn3
#undef mk_lang_num_longdivmod_inl_defd_tn2_get_lo
#undef mk_lang_num_longdivmod_inl_defd_tn2_get_hi
#undef mk_lang_num_longdivmod_inl_defd_tn3_get_tn2



#undef mk_lang_num_longdivmod_inl_defd_idxa
#undef mk_lang_num_longdivmod_inl_defd_idxb
#undef mk_lang_num_longdivmod_inl_defd_idxc
#undef mk_lang_num_longdivmod_inl_defd_idxd

#undef mk_lang_num_longdivmod_inl_defd_idxa
#undef mk_lang_num_longdivmod_inl_defd_idxb
#undef mk_lang_num_longdivmod_inl_defd_idxc
#undef mk_lang_num_longdivmod_inl_defd_idxd




#undef mk_lang_num_longdivmod_inl_defd_lenc
#undef mk_lang_num_longdivmod_inl_defd_lend
#undef mk_lang_num_longdivmod_inl_defd_get_lena
#undef mk_lang_num_longdivmod_inl_defd_get_lenb
#undef mk_lang_num_longdivmod_inl_defd_divmod4_1_1
#undef mk_lang_num_longdivmod_inl_defd_divmod4_0_n
#undef mk_lang_num_longdivmod_inl_defd_divmod4_b_g
#undef mk_lang_num_longdivmod_inl_defd_divmod4_x_1
#undef mk_lang_num_longdivmod_inl_defd_divmod4_n_1
#undef mk_lang_num_longdivmod_inl_defd_divmod4_x_x
#undef mk_lang_num_longdivmod_inl_defd_divmod4_n_n

#undef mk_lang_num_longdivmod_inl_defd_divmod4


#undef mk_lang_num_longdivmod_inl_defd_tn1_t
#undef mk_lang_num_longdivmod_inl_defd_tn1_ct
#undef mk_lang_num_longdivmod_inl_defd_tn1_pt
#undef mk_lang_num_longdivmod_inl_defd_tn1_pct
#undef mk_lang_num_longdivmod_inl_defd_tn1_prt
#undef mk_lang_num_longdivmod_inl_defd_tn1_prct

#undef mk_lang_num_longdivmod_inl_defd_tn1_sizebits_d
#undef mk_lang_num_longdivmod_inl_defd_tn1_sizebits_e
#undef mk_lang_num_longdivmod_inl_defd_tn1_sizebits_v
#undef mk_lang_num_longdivmod_inl_defd_tn1_sizebits_t

#undef mk_lang_num_longdivmod_inl_defd_tn1_from_base
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_bool
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_pchar
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_uchar
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_schar
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_ushort
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_sshort
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_uint
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_sint
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_ulong
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_slong
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_ullong
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_sllong
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_ulllong
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_slllong
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_uintptr
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_sintptr
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_uintmax
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_sintmax
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_usize
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_bi_ssize
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_base
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_bool
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_pchar
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_uchar
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_schar
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_ushort
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_sshort
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_uint
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_sint
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_ulong
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_slong
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_ullong
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_sllong
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_ulllong
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_slllong
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_uintptr
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_sintptr
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_uintmax
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_sintmax
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_usize
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_bi_ssize
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_uchar_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_ushort_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_uint_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_ulong_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_ullong_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_ulllong_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_uintptr_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_uintmax_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_usize_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_uchar_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_ushort_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_uint_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_ulong_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_ullong_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_ulllong_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_uintptr_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_uintmax_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_usize_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_uchar_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_ushort_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_uint_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_ulong_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_ullong_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_ulllong_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_uintptr_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_uintmax_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_from_buis_usize_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_uchar_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_ushort_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_uint_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_ulong_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_ullong_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_ulllong_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_uintptr_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_uintmax_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_to_buis_usize_be
#undef mk_lang_num_longdivmod_inl_defd_tn1_set_zero
#undef mk_lang_num_longdivmod_inl_defd_tn1_set_max
#undef mk_lang_num_longdivmod_inl_defd_tn1_set_one
#undef mk_lang_num_longdivmod_inl_defd_tn1_set_bit
#undef mk_lang_num_longdivmod_inl_defd_tn1_set_mask
#undef mk_lang_num_longdivmod_inl_defd_tn1_count_leading_zeros
#undef mk_lang_num_longdivmod_inl_defd_tn1_count_leading_ones
#undef mk_lang_num_longdivmod_inl_defd_tn1_count_trailing_zeros
#undef mk_lang_num_longdivmod_inl_defd_tn1_count_trailing_ones
#undef mk_lang_num_longdivmod_inl_defd_tn1_count_zeros
#undef mk_lang_num_longdivmod_inl_defd_tn1_count_ones
#undef mk_lang_num_longdivmod_inl_defd_tn1_has_lsb
#undef mk_lang_num_longdivmod_inl_defd_tn1_is_zero
#undef mk_lang_num_longdivmod_inl_defd_tn1_is_one
#undef mk_lang_num_longdivmod_inl_defd_tn1_is_max
#undef mk_lang_num_longdivmod_inl_defd_tn1_eq
#undef mk_lang_num_longdivmod_inl_defd_tn1_ne
#undef mk_lang_num_longdivmod_inl_defd_tn1_lt
#undef mk_lang_num_longdivmod_inl_defd_tn1_le
#undef mk_lang_num_longdivmod_inl_defd_tn1_gt
#undef mk_lang_num_longdivmod_inl_defd_tn1_ge
#undef mk_lang_num_longdivmod_inl_defd_tn1_inc2
#undef mk_lang_num_longdivmod_inl_defd_tn1_dec2
#undef mk_lang_num_longdivmod_inl_defd_tn1_inc1
#undef mk_lang_num_longdivmod_inl_defd_tn1_dec1
#undef mk_lang_num_longdivmod_inl_defd_tn1_not2
#undef mk_lang_num_longdivmod_inl_defd_tn1_or3
#undef mk_lang_num_longdivmod_inl_defd_tn1_and3
#undef mk_lang_num_longdivmod_inl_defd_tn1_xor3
#undef mk_lang_num_longdivmod_inl_defd_tn1_not1
#undef mk_lang_num_longdivmod_inl_defd_tn1_or2
#undef mk_lang_num_longdivmod_inl_defd_tn1_and2
#undef mk_lang_num_longdivmod_inl_defd_tn1_xor2
#undef mk_lang_num_longdivmod_inl_defd_tn1_shl3
#undef mk_lang_num_longdivmod_inl_defd_tn1_shr3
#undef mk_lang_num_longdivmod_inl_defd_tn1_rotl3
#undef mk_lang_num_longdivmod_inl_defd_tn1_rotr3
#undef mk_lang_num_longdivmod_inl_defd_tn1_shl2
#undef mk_lang_num_longdivmod_inl_defd_tn1_shr2
#undef mk_lang_num_longdivmod_inl_defd_tn1_rotl2
#undef mk_lang_num_longdivmod_inl_defd_tn1_rotr2
#undef mk_lang_num_longdivmod_inl_defd_tn1_would_overflow_add_cc
#undef mk_lang_num_longdivmod_inl_defd_tn1_would_overflow_add_cs
#undef mk_lang_num_longdivmod_inl_defd_tn1_would_overflow_add
#undef mk_lang_num_longdivmod_inl_defd_tn1_would_overflow_sub_cc
#undef mk_lang_num_longdivmod_inl_defd_tn1_would_overflow_sub_cs
#undef mk_lang_num_longdivmod_inl_defd_tn1_would_overflow_sub
#undef mk_lang_num_longdivmod_inl_defd_tn1_would_overflow_mul
#undef mk_lang_num_longdivmod_inl_defd_tn1_add3_wrap_cid_cod
#undef mk_lang_num_longdivmod_inl_defd_tn1_add3_wrap_cid_coe
#undef mk_lang_num_longdivmod_inl_defd_tn1_add3_wrap_cie_cod
#undef mk_lang_num_longdivmod_inl_defd_tn1_add3_wrap_cie_coe
#undef mk_lang_num_longdivmod_inl_defd_tn1_add2_wrap_cid_cod
#undef mk_lang_num_longdivmod_inl_defd_tn1_add2_wrap_cid_coe
#undef mk_lang_num_longdivmod_inl_defd_tn1_add2_wrap_cie_cod
#undef mk_lang_num_longdivmod_inl_defd_tn1_add2_wrap_cie_coe
#undef mk_lang_num_longdivmod_inl_defd_tn1_sub3_wrap_cid_cod
#undef mk_lang_num_longdivmod_inl_defd_tn1_sub3_wrap_cid_coe
#undef mk_lang_num_longdivmod_inl_defd_tn1_sub3_wrap_cie_cod
#undef mk_lang_num_longdivmod_inl_defd_tn1_sub3_wrap_cie_coe
#undef mk_lang_num_longdivmod_inl_defd_tn1_sub2_wrap_cid_cod
#undef mk_lang_num_longdivmod_inl_defd_tn1_sub2_wrap_cid_coe
#undef mk_lang_num_longdivmod_inl_defd_tn1_sub2_wrap_cie_cod
#undef mk_lang_num_longdivmod_inl_defd_tn1_sub2_wrap_cie_coe
#undef mk_lang_num_longdivmod_inl_defd_tn1_mul3_wrap_lo
#undef mk_lang_num_longdivmod_inl_defd_tn1_mul3_wrap_hi
#undef mk_lang_num_longdivmod_inl_defd_tn1_mul4_wrap_wi
#undef mk_lang_num_longdivmod_inl_defd_tn1_mul2_wrap_lo
#undef mk_lang_num_longdivmod_inl_defd_tn1_mul2_wrap_hi
#undef mk_lang_num_longdivmod_inl_defd_tn1_mul2_wrap_wi
#undef mk_lang_num_longdivmod_inl_defd_tn1_div3_wrap
#undef mk_lang_num_longdivmod_inl_defd_tn1_mod3_wrap
#undef mk_lang_num_longdivmod_inl_defd_tn1_divmod4_wrap
#undef mk_lang_num_longdivmod_inl_defd_tn1_div2_wrap
#undef mk_lang_num_longdivmod_inl_defd_tn1_mod2_wrap
#undef mk_lang_num_longdivmod_inl_defd_tn1_divmod2_wrap


#undef mk_lang_num_longdivmod_inl_defd_tn2_t
#undef mk_lang_num_longdivmod_inl_defd_tn2_ct
#undef mk_lang_num_longdivmod_inl_defd_tn2_pt
#undef mk_lang_num_longdivmod_inl_defd_tn2_pct
#undef mk_lang_num_longdivmod_inl_defd_tn2_prt
#undef mk_lang_num_longdivmod_inl_defd_tn2_prct

#undef mk_lang_num_longdivmod_inl_defd_tn2_sizebits_d
#undef mk_lang_num_longdivmod_inl_defd_tn2_sizebits_e
#undef mk_lang_num_longdivmod_inl_defd_tn2_sizebits_v
#undef mk_lang_num_longdivmod_inl_defd_tn2_sizebits_t

#undef mk_lang_num_longdivmod_inl_defd_tn2_from_base
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_bool
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_pchar
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_uchar
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_schar
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_ushort
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_sshort
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_uint
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_sint
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_ulong
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_slong
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_ullong
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_sllong
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_ulllong
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_slllong
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_uintptr
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_sintptr
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_uintmax
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_sintmax
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_usize
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_bi_ssize
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_base
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_bool
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_pchar
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_uchar
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_schar
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_ushort
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_sshort
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_uint
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_sint
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_ulong
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_slong
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_ullong
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_sllong
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_ulllong
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_slllong
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_uintptr
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_sintptr
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_uintmax
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_sintmax
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_usize
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_bi_ssize
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_uchar_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_ushort_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_uint_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_ulong_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_ullong_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_ulllong_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_uintptr_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_uintmax_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_usize_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_uchar_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_ushort_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_uint_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_ulong_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_ullong_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_ulllong_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_uintptr_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_uintmax_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_usize_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_uchar_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_ushort_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_uint_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_ulong_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_ullong_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_ulllong_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_uintptr_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_uintmax_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_from_buis_usize_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_uchar_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_ushort_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_uint_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_ulong_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_ullong_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_ulllong_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_uintptr_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_uintmax_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_to_buis_usize_be
#undef mk_lang_num_longdivmod_inl_defd_tn2_set_zero
#undef mk_lang_num_longdivmod_inl_defd_tn2_set_max
#undef mk_lang_num_longdivmod_inl_defd_tn2_set_one
#undef mk_lang_num_longdivmod_inl_defd_tn2_set_bit
#undef mk_lang_num_longdivmod_inl_defd_tn2_set_mask
#undef mk_lang_num_longdivmod_inl_defd_tn2_count_leading_zeros
#undef mk_lang_num_longdivmod_inl_defd_tn2_count_leading_ones
#undef mk_lang_num_longdivmod_inl_defd_tn2_count_trailing_zeros
#undef mk_lang_num_longdivmod_inl_defd_tn2_count_trailing_ones
#undef mk_lang_num_longdivmod_inl_defd_tn2_count_zeros
#undef mk_lang_num_longdivmod_inl_defd_tn2_count_ones
#undef mk_lang_num_longdivmod_inl_defd_tn2_has_lsb
#undef mk_lang_num_longdivmod_inl_defd_tn2_is_zero
#undef mk_lang_num_longdivmod_inl_defd_tn2_is_one
#undef mk_lang_num_longdivmod_inl_defd_tn2_is_max
#undef mk_lang_num_longdivmod_inl_defd_tn2_eq
#undef mk_lang_num_longdivmod_inl_defd_tn2_ne
#undef mk_lang_num_longdivmod_inl_defd_tn2_lt
#undef mk_lang_num_longdivmod_inl_defd_tn2_le
#undef mk_lang_num_longdivmod_inl_defd_tn2_gt
#undef mk_lang_num_longdivmod_inl_defd_tn2_ge
#undef mk_lang_num_longdivmod_inl_defd_tn2_inc2
#undef mk_lang_num_longdivmod_inl_defd_tn2_dec2
#undef mk_lang_num_longdivmod_inl_defd_tn2_inc1
#undef mk_lang_num_longdivmod_inl_defd_tn2_dec1
#undef mk_lang_num_longdivmod_inl_defd_tn2_not2
#undef mk_lang_num_longdivmod_inl_defd_tn2_or3
#undef mk_lang_num_longdivmod_inl_defd_tn2_and3
#undef mk_lang_num_longdivmod_inl_defd_tn2_xor3
#undef mk_lang_num_longdivmod_inl_defd_tn2_not1
#undef mk_lang_num_longdivmod_inl_defd_tn2_or2
#undef mk_lang_num_longdivmod_inl_defd_tn2_and2
#undef mk_lang_num_longdivmod_inl_defd_tn2_xor2
#undef mk_lang_num_longdivmod_inl_defd_tn2_shl3
#undef mk_lang_num_longdivmod_inl_defd_tn2_shr3
#undef mk_lang_num_longdivmod_inl_defd_tn2_rotl3
#undef mk_lang_num_longdivmod_inl_defd_tn2_rotr3
#undef mk_lang_num_longdivmod_inl_defd_tn2_shl2
#undef mk_lang_num_longdivmod_inl_defd_tn2_shr2
#undef mk_lang_num_longdivmod_inl_defd_tn2_rotl2
#undef mk_lang_num_longdivmod_inl_defd_tn2_rotr2
#undef mk_lang_num_longdivmod_inl_defd_tn2_would_overflow_add_cc
#undef mk_lang_num_longdivmod_inl_defd_tn2_would_overflow_add_cs
#undef mk_lang_num_longdivmod_inl_defd_tn2_would_overflow_add
#undef mk_lang_num_longdivmod_inl_defd_tn2_would_overflow_sub_cc
#undef mk_lang_num_longdivmod_inl_defd_tn2_would_overflow_sub_cs
#undef mk_lang_num_longdivmod_inl_defd_tn2_would_overflow_sub
#undef mk_lang_num_longdivmod_inl_defd_tn2_would_overflow_mul
#undef mk_lang_num_longdivmod_inl_defd_tn2_add3_wrap_cid_cod
#undef mk_lang_num_longdivmod_inl_defd_tn2_add3_wrap_cid_coe
#undef mk_lang_num_longdivmod_inl_defd_tn2_add3_wrap_cie_cod
#undef mk_lang_num_longdivmod_inl_defd_tn2_add3_wrap_cie_coe
#undef mk_lang_num_longdivmod_inl_defd_tn2_add2_wrap_cid_cod
#undef mk_lang_num_longdivmod_inl_defd_tn2_add2_wrap_cid_coe
#undef mk_lang_num_longdivmod_inl_defd_tn2_add2_wrap_cie_cod
#undef mk_lang_num_longdivmod_inl_defd_tn2_add2_wrap_cie_coe
#undef mk_lang_num_longdivmod_inl_defd_tn2_sub3_wrap_cid_cod
#undef mk_lang_num_longdivmod_inl_defd_tn2_sub3_wrap_cid_coe
#undef mk_lang_num_longdivmod_inl_defd_tn2_sub3_wrap_cie_cod
#undef mk_lang_num_longdivmod_inl_defd_tn2_sub3_wrap_cie_coe
#undef mk_lang_num_longdivmod_inl_defd_tn2_sub2_wrap_cid_cod
#undef mk_lang_num_longdivmod_inl_defd_tn2_sub2_wrap_cid_coe
#undef mk_lang_num_longdivmod_inl_defd_tn2_sub2_wrap_cie_cod
#undef mk_lang_num_longdivmod_inl_defd_tn2_sub2_wrap_cie_coe
#undef mk_lang_num_longdivmod_inl_defd_tn2_mul3_wrap_lo
#undef mk_lang_num_longdivmod_inl_defd_tn2_mul3_wrap_hi
#undef mk_lang_num_longdivmod_inl_defd_tn2_mul4_wrap_wi
#undef mk_lang_num_longdivmod_inl_defd_tn2_mul2_wrap_lo
#undef mk_lang_num_longdivmod_inl_defd_tn2_mul2_wrap_hi
#undef mk_lang_num_longdivmod_inl_defd_tn2_mul2_wrap_wi
#undef mk_lang_num_longdivmod_inl_defd_tn2_div3_wrap
#undef mk_lang_num_longdivmod_inl_defd_tn2_mod3_wrap
#undef mk_lang_num_longdivmod_inl_defd_tn2_divmod4_wrap
#undef mk_lang_num_longdivmod_inl_defd_tn2_div2_wrap
#undef mk_lang_num_longdivmod_inl_defd_tn2_mod2_wrap
#undef mk_lang_num_longdivmod_inl_defd_tn2_divmod2_wrap


#undef mk_lang_num_longdivmod_inl_defd_tn3_t
#undef mk_lang_num_longdivmod_inl_defd_tn3_ct
#undef mk_lang_num_longdivmod_inl_defd_tn3_pt
#undef mk_lang_num_longdivmod_inl_defd_tn3_pct
#undef mk_lang_num_longdivmod_inl_defd_tn3_prt
#undef mk_lang_num_longdivmod_inl_defd_tn3_prct

#undef mk_lang_num_longdivmod_inl_defd_tn3_sizebits_d
#undef mk_lang_num_longdivmod_inl_defd_tn3_sizebits_e
#undef mk_lang_num_longdivmod_inl_defd_tn3_sizebits_v
#undef mk_lang_num_longdivmod_inl_defd_tn3_sizebits_t

#undef mk_lang_num_longdivmod_inl_defd_tn3_from_base
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_bool
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_pchar
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_uchar
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_schar
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_ushort
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_sshort
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_uint
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_sint
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_ulong
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_slong
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_ullong
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_sllong
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_ulllong
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_slllong
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_uintptr
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_sintptr
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_uintmax
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_sintmax
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_usize
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_bi_ssize
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_base
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_bool
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_pchar
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_uchar
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_schar
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_ushort
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_sshort
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_uint
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_sint
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_ulong
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_slong
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_ullong
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_sllong
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_ulllong
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_slllong
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_uintptr
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_sintptr
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_uintmax
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_sintmax
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_usize
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_bi_ssize
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_uchar_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_ushort_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_uint_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_ulong_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_ullong_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_ulllong_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_uintptr_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_uintmax_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_usize_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_uchar_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_ushort_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_uint_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_ulong_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_ullong_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_ulllong_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_uintptr_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_uintmax_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_usize_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_uchar_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_ushort_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_uint_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_ulong_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_ullong_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_ulllong_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_uintptr_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_uintmax_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_from_buis_usize_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_uchar_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_ushort_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_uint_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_ulong_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_ullong_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_ulllong_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_uintptr_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_uintmax_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_to_buis_usize_be
#undef mk_lang_num_longdivmod_inl_defd_tn3_set_zero
#undef mk_lang_num_longdivmod_inl_defd_tn3_set_max
#undef mk_lang_num_longdivmod_inl_defd_tn3_set_one
#undef mk_lang_num_longdivmod_inl_defd_tn3_set_bit
#undef mk_lang_num_longdivmod_inl_defd_tn3_set_mask
#undef mk_lang_num_longdivmod_inl_defd_tn3_count_leading_zeros
#undef mk_lang_num_longdivmod_inl_defd_tn3_count_leading_ones
#undef mk_lang_num_longdivmod_inl_defd_tn3_count_trailing_zeros
#undef mk_lang_num_longdivmod_inl_defd_tn3_count_trailing_ones
#undef mk_lang_num_longdivmod_inl_defd_tn3_count_zeros
#undef mk_lang_num_longdivmod_inl_defd_tn3_count_ones
#undef mk_lang_num_longdivmod_inl_defd_tn3_has_lsb
#undef mk_lang_num_longdivmod_inl_defd_tn3_is_zero
#undef mk_lang_num_longdivmod_inl_defd_tn3_is_one
#undef mk_lang_num_longdivmod_inl_defd_tn3_is_max
#undef mk_lang_num_longdivmod_inl_defd_tn3_eq
#undef mk_lang_num_longdivmod_inl_defd_tn3_ne
#undef mk_lang_num_longdivmod_inl_defd_tn3_lt
#undef mk_lang_num_longdivmod_inl_defd_tn3_le
#undef mk_lang_num_longdivmod_inl_defd_tn3_gt
#undef mk_lang_num_longdivmod_inl_defd_tn3_ge
#undef mk_lang_num_longdivmod_inl_defd_tn3_inc2
#undef mk_lang_num_longdivmod_inl_defd_tn3_dec2
#undef mk_lang_num_longdivmod_inl_defd_tn3_inc1
#undef mk_lang_num_longdivmod_inl_defd_tn3_dec1
#undef mk_lang_num_longdivmod_inl_defd_tn3_not2
#undef mk_lang_num_longdivmod_inl_defd_tn3_or3
#undef mk_lang_num_longdivmod_inl_defd_tn3_and3
#undef mk_lang_num_longdivmod_inl_defd_tn3_xor3
#undef mk_lang_num_longdivmod_inl_defd_tn3_not1
#undef mk_lang_num_longdivmod_inl_defd_tn3_or2
#undef mk_lang_num_longdivmod_inl_defd_tn3_and2
#undef mk_lang_num_longdivmod_inl_defd_tn3_xor2
#undef mk_lang_num_longdivmod_inl_defd_tn3_shl3
#undef mk_lang_num_longdivmod_inl_defd_tn3_shr3
#undef mk_lang_num_longdivmod_inl_defd_tn3_rotl3
#undef mk_lang_num_longdivmod_inl_defd_tn3_rotr3
#undef mk_lang_num_longdivmod_inl_defd_tn3_shl2
#undef mk_lang_num_longdivmod_inl_defd_tn3_shr2
#undef mk_lang_num_longdivmod_inl_defd_tn3_rotl2
#undef mk_lang_num_longdivmod_inl_defd_tn3_rotr2
#undef mk_lang_num_longdivmod_inl_defd_tn3_would_overflow_add_cc
#undef mk_lang_num_longdivmod_inl_defd_tn3_would_overflow_add_cs
#undef mk_lang_num_longdivmod_inl_defd_tn3_would_overflow_add
#undef mk_lang_num_longdivmod_inl_defd_tn3_would_overflow_sub_cc
#undef mk_lang_num_longdivmod_inl_defd_tn3_would_overflow_sub_cs
#undef mk_lang_num_longdivmod_inl_defd_tn3_would_overflow_sub
#undef mk_lang_num_longdivmod_inl_defd_tn3_would_overflow_mul
#undef mk_lang_num_longdivmod_inl_defd_tn3_add3_wrap_cid_cod
#undef mk_lang_num_longdivmod_inl_defd_tn3_add3_wrap_cid_coe
#undef mk_lang_num_longdivmod_inl_defd_tn3_add3_wrap_cie_cod
#undef mk_lang_num_longdivmod_inl_defd_tn3_add3_wrap_cie_coe
#undef mk_lang_num_longdivmod_inl_defd_tn3_add2_wrap_cid_cod
#undef mk_lang_num_longdivmod_inl_defd_tn3_add2_wrap_cid_coe
#undef mk_lang_num_longdivmod_inl_defd_tn3_add2_wrap_cie_cod
#undef mk_lang_num_longdivmod_inl_defd_tn3_add2_wrap_cie_coe
#undef mk_lang_num_longdivmod_inl_defd_tn3_sub3_wrap_cid_cod
#undef mk_lang_num_longdivmod_inl_defd_tn3_sub3_wrap_cid_coe
#undef mk_lang_num_longdivmod_inl_defd_tn3_sub3_wrap_cie_cod
#undef mk_lang_num_longdivmod_inl_defd_tn3_sub3_wrap_cie_coe
#undef mk_lang_num_longdivmod_inl_defd_tn3_sub2_wrap_cid_cod
#undef mk_lang_num_longdivmod_inl_defd_tn3_sub2_wrap_cid_coe
#undef mk_lang_num_longdivmod_inl_defd_tn3_sub2_wrap_cie_cod
#undef mk_lang_num_longdivmod_inl_defd_tn3_sub2_wrap_cie_coe
#undef mk_lang_num_longdivmod_inl_defd_tn3_mul3_wrap_lo
#undef mk_lang_num_longdivmod_inl_defd_tn3_mul3_wrap_hi
#undef mk_lang_num_longdivmod_inl_defd_tn3_mul4_wrap_wi
#undef mk_lang_num_longdivmod_inl_defd_tn3_mul2_wrap_lo
#undef mk_lang_num_longdivmod_inl_defd_tn3_mul2_wrap_hi
#undef mk_lang_num_longdivmod_inl_defd_tn3_mul2_wrap_wi
#undef mk_lang_num_longdivmod_inl_defd_tn3_div3_wrap
#undef mk_lang_num_longdivmod_inl_defd_tn3_mod3_wrap
#undef mk_lang_num_longdivmod_inl_defd_tn3_divmod4_wrap
#undef mk_lang_num_longdivmod_inl_defd_tn3_div2_wrap
#undef mk_lang_num_longdivmod_inl_defd_tn3_mod2_wrap
#undef mk_lang_num_longdivmod_inl_defd_tn3_divmod2_wrap
