#include "mk_lang_concat.h"


#define mk_lib_crypto_hash_stream_lazy_inl_defd_s mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_stream_, mk_lib_crypto_hash_stream_lazy_t_name), _s)
#define mk_lib_crypto_hash_stream_lazy_inl_defd_t mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_stream_, mk_lib_crypto_hash_stream_lazy_t_name), _t)
#define mk_lib_crypto_hash_stream_lazy_inl_defd_ct mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_stream_, mk_lib_crypto_hash_stream_lazy_t_name), _ct)
#define mk_lib_crypto_hash_stream_lazy_inl_defd_pt mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_stream_, mk_lib_crypto_hash_stream_lazy_t_name), _pt)
#define mk_lib_crypto_hash_stream_lazy_inl_defd_pct mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_stream_, mk_lib_crypto_hash_stream_lazy_t_name), _pct)

#define mk_lib_crypto_hash_stream_lazy_inl_defd_init mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_stream_, mk_lib_crypto_hash_stream_lazy_t_name), _init)
#define mk_lib_crypto_hash_stream_lazy_inl_defd_append_u8 mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_stream_, mk_lib_crypto_hash_stream_lazy_t_name), _append_u8)
#define mk_lib_crypto_hash_stream_lazy_inl_defd_append mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_stream_, mk_lib_crypto_hash_stream_lazy_t_name), _append)
#define mk_lib_crypto_hash_stream_lazy_inl_defd_finish mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_stream_, mk_lib_crypto_hash_stream_lazy_t_name), _finish)

#define mk_lib_crypto_hash_stream_lazy_inl_defd_base_block_len mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_block_, mk_lib_crypto_hash_stream_lazy_t_name), _block_len)
#define mk_lib_crypto_hash_stream_lazy_inl_defd_base_t mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_block_, mk_lib_crypto_hash_stream_lazy_t_name), _t)
#define mk_lib_crypto_hash_stream_lazy_inl_defd_base_block_t mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_block_, mk_lib_crypto_hash_stream_lazy_t_name), _block_t)
#define mk_lib_crypto_hash_stream_lazy_inl_defd_base_block_pct mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_block_, mk_lib_crypto_hash_stream_lazy_t_name), _block_pct)
#define mk_lib_crypto_hash_stream_lazy_inl_defd_base_digest_pt mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_block_, mk_lib_crypto_hash_stream_lazy_t_name), _digest_pt)

#define mk_lib_crypto_hash_stream_lazy_inl_defd_base_init mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_block_, mk_lib_crypto_hash_stream_lazy_t_name), _init)
#define mk_lib_crypto_hash_stream_lazy_inl_defd_base_append_blocks mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_block_, mk_lib_crypto_hash_stream_lazy_t_name), _append_blocks)
#define mk_lib_crypto_hash_stream_lazy_inl_defd_base_pad_block mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_block_, mk_lib_crypto_hash_stream_lazy_t_name), _pad_block)
#define mk_lib_crypto_hash_stream_lazy_inl_defd_base_finish mk_lang_concat(mk_lang_concat(mk_lib_crypto_hash_block_, mk_lib_crypto_hash_stream_lazy_t_name), _finish)
