include(`mk_lang_typedef.m')dnl
#include "mk_lang_charbit.h"
#include "mk_lang_concat.h"


#if \
(!( \
	(defined mk_lib_crypto_mode_cfb_t_name) && \
	(defined mk_lib_crypto_mode_cfb_t_base_name) && \
	((defined mk_lib_crypto_mode_cfb_t_bits && (mk_lib_crypto_mode_cfb_t_bits) == 8) || !defined mk_lib_crypto_mode_cfb_t_bits) && \
1))
#error xxxxxxxxxx
#endif


#define mk_lib_crypto_mode_cfb_inl_defd_name mk_lib_crypto_mode_cfb_t_name
#define mk_lib_crypto_mode_cfb_inl_defd_base_name mk_lib_crypto_mode_cfb_t_base_name
#if defined mk_lib_crypto_mode_cfb_t_bits
#define mk_lib_crypto_mode_cfb_inl_defd_bits (mk_lib_crypto_mode_cfb_t_bits)
#else
#define mk_lib_crypto_mode_cfb_inl_defd_bits ((mk_lib_crypto_mode_cfb_inl_defd_base_msg_len_d) * (mk_lang_charbit))
#endif





#define mk_lib_crypto_mode_cfb_inl_defd_base_msg_len_d (mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_base_name, _msg_len_d))
#define mk_lib_crypto_mode_cfb_inl_defd_base_key_len_d (mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_base_name, _key_len_d))
#define mk_lib_crypto_mode_cfb_inl_defd_base_schedule_len_d (mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_base_name, _schedule_len_d))

#define mk_lib_crypto_mode_cfb_inl_defd_base_msg_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_base_name, _msg_t)
#define mk_lib_crypto_mode_cfb_inl_defd_base_key_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_base_name, _key_t)
#define mk_lib_crypto_mode_cfb_inl_defd_base_schedule_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_base_name, _schedule_t)

#define mk_lib_crypto_mode_cfb_inl_defd_base_expand_enc mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_base_name, _expand_enc)
#define mk_lib_crypto_mode_cfb_inl_defd_base_expand_dec mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_base_name, _expand_dec)
#define mk_lib_crypto_mode_cfb_inl_defd_base_schedule_encrypt mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_base_name, _schedule_encrypt)
#define mk_lib_crypto_mode_cfb_inl_defd_base_schedule_decrypt mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_base_name, _schedule_decrypt)





#define mk_lib_crypto_mode_cfb_inl_defd_iv_len_d mk_lib_crypto_mode_cfb_inl_defd_base_msg_len_d
#define mk_lib_crypto_mode_cfb_inl_defd_iv_len_e mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _iv_len_e)
#define mk_lib_crypto_mode_cfb_inl_defd_iv_len_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _iv_len_t)
#define mk_lib_crypto_mode_cfb_inl_defd_iv_len_v mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _iv_len_v)
#define mk_lib_crypto_mode_cfb_inl_defd_iv_data_u mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _iv_data_u)
#define mk_lib_crypto_mode_cfb_inl_defd_iv_data_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _iv_data_t)
#define mk_lib_crypto_mode_cfb_inl_defd_iv mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _iv)
#define mk_lib_crypto_mode_cfb_inl_defd_iv_s mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_iv, _s)
#define mk_lib_crypto_mode_cfb_inl_defd_iv_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_iv, _t)
mm_per_typedef2(`mk_lib_crypto_mode_cfb_inl_defd_iv')dnl

#define mk_lib_crypto_mode_cfb_inl_defd_tmp_msg_data_u mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _tmp_msg_data_u)
#define mk_lib_crypto_mode_cfb_inl_defd_tmp_msg_data_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _tmp_msg_data_t)
#define mk_lib_crypto_mode_cfb_inl_defd_tmp_msg_s mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _tmp_msg_s)
#define mk_lib_crypto_mode_cfb_inl_defd_tmp_msg_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _tmp_msg_t)

#define mk_lib_crypto_mode_cfb_inl_defd_msg_len_d (mk_lib_crypto_mode_cfb_inl_defd_bits / mk_lang_charbit)
#define mk_lib_crypto_mode_cfb_inl_defd_msg_len_e mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _msg_len_e)
#define mk_lib_crypto_mode_cfb_inl_defd_msg_len_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _msg_len_t)
#define mk_lib_crypto_mode_cfb_inl_defd_msg_len_v mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _msg_len_v)
#define mk_lib_crypto_mode_cfb_inl_defd_msg_data_u mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _msg_data_u)
#define mk_lib_crypto_mode_cfb_inl_defd_msg_data_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _msg_data_t)
#define mk_lib_crypto_mode_cfb_inl_defd_msg mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _msg)
#define mk_lib_crypto_mode_cfb_inl_defd_msg_s mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_msg, _s)
#define mk_lib_crypto_mode_cfb_inl_defd_msg_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_msg, _t)
mm_per_typedef2(`mk_lib_crypto_mode_cfb_inl_defd_msg')dnl

#define mk_lib_crypto_mode_cfb_inl_defd_key_len_d mk_lib_crypto_mode_cfb_inl_defd_base_key_len_d
#define mk_lib_crypto_mode_cfb_inl_defd_key_len_e mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _key_len_e)
#define mk_lib_crypto_mode_cfb_inl_defd_key_len_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _key_len_t)
#define mk_lib_crypto_mode_cfb_inl_defd_key_len_v mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _key_len_v)
#define mk_lib_crypto_mode_cfb_inl_defd_key_data_u mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _key_data_u)
#define mk_lib_crypto_mode_cfb_inl_defd_key_data_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _key_data_t)
#define mk_lib_crypto_mode_cfb_inl_defd_key mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _key)
#define mk_lib_crypto_mode_cfb_inl_defd_key_s mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_key, _s)
#define mk_lib_crypto_mode_cfb_inl_defd_key_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_key, _t)
mm_per_typedef2(`mk_lib_crypto_mode_cfb_inl_defd_key')dnl

#define mk_lib_crypto_mode_cfb_inl_defd_schedule_len_d mk_lib_crypto_mode_cfb_inl_defd_base_schedule_len_d
#define mk_lib_crypto_mode_cfb_inl_defd_schedule_len_e mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _schedule_len_e)
#define mk_lib_crypto_mode_cfb_inl_defd_schedule_len_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _schedule_len_t)
#define mk_lib_crypto_mode_cfb_inl_defd_schedule_len_v mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _schedule_len_v)
#define mk_lib_crypto_mode_cfb_inl_defd_schedule_data_u mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _schedule_data_u)
#define mk_lib_crypto_mode_cfb_inl_defd_schedule_data_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _schedule_data_t)
#define mk_lib_crypto_mode_cfb_inl_defd_schedule mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _schedule)
#define mk_lib_crypto_mode_cfb_inl_defd_schedule_s mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_schedule, _s)
#define mk_lib_crypto_mode_cfb_inl_defd_schedule_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_schedule, _t)
mm_per_typedef2(`mk_lib_crypto_mode_cfb_inl_defd_schedule')dnl

#define mk_lib_crypto_mode_cfb_inl_defd_alg mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _alg)
#define mk_lib_crypto_mode_cfb_inl_defd_alg_s mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_alg, _s)
#define mk_lib_crypto_mode_cfb_inl_defd_alg_t mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_alg, _t)
mm_per_typedef2(`mk_lib_crypto_mode_cfb_inl_defd_alg')dnl

#define mk_lib_crypto_mode_cfb_inl_defd_rw_set_iv mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _rw_set_iv)
#define mk_lib_crypto_mode_cfb_inl_defd_prrw_set_key mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _prrw_set_key)
#define mk_lib_crypto_mode_cfb_inl_defd_rw_set_key_enc mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _rw_set_key_enc)
#define mk_lib_crypto_mode_cfb_inl_defd_rw_set_key_dec mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _rw_set_key_dec)
#define mk_lib_crypto_mode_cfb_inl_defd_rw_encrypt mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _rw_encrypt)
#define mk_lib_crypto_mode_cfb_inl_defd_rw_decrypt mk_lang_concat(mk_lib_crypto_mode_cfb_inl_defd_name, _rw_decrypt)





#if mk_lib_crypto_mode_cfb_inl_defd_msg_len_d == 1
#define mk_lib_crypto_mode_cfb_inl_defd_xor_2 mk_sl_cui_uint_more_1_xor2
#define mk_lib_crypto_mode_cfb_inl_defd_xor_3 mk_sl_cui_uint_more_1_xor3
#define mk_lib_crypto_mode_cfb_inl_defd_memcpy mk_sl_cui_uint_more_1_memcpy
#define mk_lib_crypto_mode_cfb_inl_defd_memmov mk_sl_cui_uint_more_15_memmov
#elif mk_lib_crypto_mode_cfb_inl_defd_msg_len_d == 16
#define mk_lib_crypto_mode_cfb_inl_defd_xor_2 mk_sl_cui_uint_more_16_xor2
#define mk_lib_crypto_mode_cfb_inl_defd_xor_3 mk_sl_cui_uint_more_16_xor3
#else
#error xxxxxxxxxx
#endif
