#ifndef mk_include_guard_mk_lib_iip_key_sgn_dsa_sha1_pri_h
#define mk_include_guard_mk_lib_iip_key_sgn_dsa_sha1_pri_h


#include "mk_lang_bui.h"
#include "mk_lang_charbit.h"
#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_static_param.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"


mk_lang_forward(mk_lib_iip_key_sgn_dsa_sha1_pub);
mk_lang_forward(mk_lib_iip_key_sgn_dsa_sha1_pub_integer_single);
mk_lang_forward(mk_sl_cui_uint8);


#define mk_sl_cui_t_name mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single
#define mk_sl_cui_t_base_type_name mk_lang_bui_uint
#define mk_sl_cui_t_count (1 * ((20 * mk_lang_charbit) / mk_lang_bui_uint_size_bits_d))
#define mk_sl_cui_t_inline 0
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"

#define mk_sl_cui_t_name mk_lib_iip_key_sgn_dsa_sha1_pri_integer_double
#define mk_sl_cui_t_base_type_name mk_lang_bui_uint
#define mk_sl_cui_t_count (2 * ((20 * mk_lang_charbit) / mk_lang_bui_uint_size_bits_d))
#define mk_sl_cui_t_inline 0
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"


mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_to_pri_double(mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_pct const a, mk_lib_iip_key_sgn_dsa_sha1_pri_integer_double_pt const b) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_key_sgn_dsa_sha1_pri_integer_double_to_pri_single(mk_lib_iip_key_sgn_dsa_sha1_pri_integer_double_pct const a, mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_pt const b) mk_lang_noexcept;

mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_to_pub_single(mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_pct const a, mk_lib_iip_key_sgn_dsa_sha1_pub_integer_single_pt const b) mk_lang_noexcept;

mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_load_q(mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_pt const x) mk_lang_noexcept;

mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_from_u8s_be(mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_pt const a, mk_lang_static_param(mk_sl_cui_uint8_ct, b, mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_size_bytes_v)) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_bool_t mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_is_negative(mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_pct const x) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_flip_sign_1(mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_pt const x) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_mod_add2_wrap_cid_cod(mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_prct const m, mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_prt const a, mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_prct const b) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_mod_mul3_wrap_lo(mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_prct const m, mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_prct const a, mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_prct const b, mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_prt const c) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_mod_mul2_wrap_lo(mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_prct const m, mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_prt const a, mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_prct const b) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_gcd(mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_prct const a, mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_prct const b, mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_prt const c) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_mul3_signed(mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_prct const a, mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_prct const b, mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_prt const c) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_mod_inv(mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_pct const a, mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_pct const modulus, mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_pt const res_out) mk_lang_noexcept;


struct mk_lib_iip_key_sgn_dsa_sha1_pri_signature_s
{
	mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_t m_r;
	mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_t m_s;
};
typedef struct mk_lib_iip_key_sgn_dsa_sha1_pri_signature_s mk_lib_iip_key_sgn_dsa_sha1_pri_signature_t;
mk_lang_typedef(mk_lib_iip_key_sgn_dsa_sha1_pri_signature);
enum mk_lib_iip_key_sgn_dsa_sha1_pri_signature_len_e{ mk_lib_iip_key_sgn_dsa_sha1_pri_signature_len_v = 2 * mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_size_bytes_v }; typedef enum mk_lib_iip_key_sgn_dsa_sha1_pri_signature_len_e mk_lib_iip_key_sgn_dsa_sha1_pri_signature_len_t;


union mk_lib_iip_key_sgn_dsa_sha1_pri_data_u
{
	mk_lib_iip_key_sgn_dsa_sha1_pri_integer_single_t m_integer;
	mk_lang_types_ulllong_t m_align;
};
typedef union mk_lib_iip_key_sgn_dsa_sha1_pri_data_u mk_lib_iip_key_sgn_dsa_sha1_pri_data_t;
struct mk_lib_iip_key_sgn_dsa_sha1_pri_s
{
	mk_lib_iip_key_sgn_dsa_sha1_pri_data_t m_data;
};
typedef struct mk_lib_iip_key_sgn_dsa_sha1_pri_s mk_lib_iip_key_sgn_dsa_sha1_pri_t;
mk_lang_typedef(mk_lib_iip_key_sgn_dsa_sha1_pri);


mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_bool_t mk_lib_iip_key_sgn_dsa_sha1_pri_is_valid(mk_lib_iip_key_sgn_dsa_sha1_pri_pct const pri) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_pri_generate_random(mk_lib_iip_key_sgn_dsa_sha1_pri_pt const pri) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_key_sgn_dsa_sha1_pri_compute_public(mk_lib_iip_key_sgn_dsa_sha1_pri_pct const pri, mk_lib_iip_key_sgn_dsa_sha1_pub_pt const pub) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_pri_sign_data(mk_lib_iip_key_sgn_dsa_sha1_pri_pct const pri, mk_sl_cui_uint8_pct const data_buf, mk_lang_types_sint_t const data_len, mk_lib_iip_key_sgn_dsa_sha1_pri_signature_pt const signature) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_key_sgn_dsa_sha1_pri_signature_to_u8s(mk_lib_iip_key_sgn_dsa_sha1_pri_signature_pct const signature, mk_lang_static_param(mk_sl_cui_uint8_t, u8s, mk_lib_iip_key_sgn_dsa_sha1_pri_signature_len_v)) mk_lang_noexcept;


#if mk_lang_jumbo_have
#include "mk_lib_iip_key_sgn_dsa_sha1_pri.c"
#endif
#endif
