#ifndef mk_include_guard_mk_lib_crypto_hash_block_streebog_base_h
#define mk_include_guard_mk_lib_crypto_hash_block_streebog_base_h

/* http://tc26.ru/research/polozhenie/GOST_R_34_11-2012_eng.pdf */

#include "mk_lang_alignas.h"
#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_types.h"
#include "mk_sl_cui_uint64.h"
#include "mk_sl_cui_uint8.h"


#define mk_lib_crypto_hash_block_streebog_base_block_len_d 64
enum mk_lib_crypto_hash_block_streebog_base_block_len_e{ mk_lib_crypto_hash_block_streebog_base_block_len_v = mk_lib_crypto_hash_block_streebog_base_block_len_d }; typedef enum mk_lib_crypto_hash_block_streebog_base_block_len_e mk_lib_crypto_hash_block_streebog_base_block_len_t;


union mk_lib_crypto_hash_block_streebog_base_block_data_u
{
	mk_lang_alignas(mk_lib_crypto_hash_block_streebog_base_block_len_v) mk_sl_cui_uint8_t m_uint8s[mk_lib_crypto_hash_block_streebog_base_block_len_v];
	mk_lang_types_ulllong_t m_align;
};
typedef union mk_lib_crypto_hash_block_streebog_base_block_data_u mk_lib_crypto_hash_block_streebog_base_block_data_t;
struct mk_lib_crypto_hash_block_streebog_base_block_s
{
	mk_lib_crypto_hash_block_streebog_base_block_data_t m_data;
};
typedef struct mk_lib_crypto_hash_block_streebog_base_block_s mk_lib_crypto_hash_block_streebog_base_block_t;
typedef mk_lib_crypto_hash_block_streebog_base_block_t const mk_lib_crypto_hash_block_streebog_base_block_ct;
typedef mk_lib_crypto_hash_block_streebog_base_block_t* mk_lib_crypto_hash_block_streebog_base_block_pt;
typedef mk_lib_crypto_hash_block_streebog_base_block_t const* mk_lib_crypto_hash_block_streebog_base_block_pct;


union mk_lib_crypto_hash_block_streebog_base_block2_data_u
{
	mk_sl_cui_uint64_t m_uint64s[8];
	mk_lib_crypto_hash_block_streebog_base_block_t m_align;
};
typedef union mk_lib_crypto_hash_block_streebog_base_block2_data_u mk_lib_crypto_hash_block_streebog_base_block2_data_t;
struct mk_lib_crypto_hash_block_streebog_base_block2_s
{
	mk_lang_alignas(sizeof(mk_lib_crypto_hash_block_streebog_base_block2_data_t)) mk_lib_crypto_hash_block_streebog_base_block2_data_t m_data;
};
typedef struct mk_lib_crypto_hash_block_streebog_base_block2_s mk_lib_crypto_hash_block_streebog_base_block2_t;
typedef mk_lib_crypto_hash_block_streebog_base_block2_t const mk_lib_crypto_hash_block_streebog_base_block2_ct;
typedef mk_lib_crypto_hash_block_streebog_base_block2_t* mk_lib_crypto_hash_block_streebog_base_block2_pt;
typedef mk_lib_crypto_hash_block_streebog_base_block2_t const* mk_lib_crypto_hash_block_streebog_base_block2_pct;

struct mk_lib_crypto_hash_block_streebog_base_state_data_s
{
	mk_lib_crypto_hash_block_streebog_base_block2_t m_h;
	mk_lib_crypto_hash_block_streebog_base_block2_t m_n;
	mk_lib_crypto_hash_block_streebog_base_block2_t m_s;
};
typedef struct mk_lib_crypto_hash_block_streebog_base_state_data_s mk_lib_crypto_hash_block_streebog_base_state_data_t;
struct mk_lib_crypto_hash_block_streebog_base_state_s
{
	mk_lang_alignas(sizeof(mk_lib_crypto_hash_block_streebog_base_block2_t)) mk_lib_crypto_hash_block_streebog_base_state_data_t m_data;
};
typedef struct mk_lib_crypto_hash_block_streebog_base_state_s mk_lib_crypto_hash_block_streebog_base_state_t;


struct mk_lib_crypto_hash_block_streebog_base_s
{
	mk_lib_crypto_hash_block_streebog_base_state_t m_state;
};
typedef struct mk_lib_crypto_hash_block_streebog_base_s mk_lib_crypto_hash_block_streebog_base_t;
typedef mk_lib_crypto_hash_block_streebog_base_t const mk_lib_crypto_hash_block_streebog_base_ct;
typedef mk_lib_crypto_hash_block_streebog_base_t* mk_lib_crypto_hash_block_streebog_base_pt;
typedef mk_lib_crypto_hash_block_streebog_base_t const* mk_lib_crypto_hash_block_streebog_base_pct;


mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_hash_block_streebog_base_erase_block(mk_lib_crypto_hash_block_streebog_base_block2_pt const block) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_hash_block_streebog_base_append_blocks(mk_lib_crypto_hash_block_streebog_base_pt const streebog_base, mk_lib_crypto_hash_block_streebog_base_block_pct const pblocks, mk_lang_types_usize_t const nblocks) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_hash_block_streebog_base_stage_3(mk_lib_crypto_hash_block_streebog_base_pt const streebog_base, mk_lib_crypto_hash_block_streebog_base_block_pt const block, mk_lang_types_sint_t const idx) mk_lang_noexcept;


#if mk_lang_jumbo_have == 1
#include "mk_lib_crypto_hash_block_streebog_base.c"
#endif
#endif
