include(`mk_mm_nl.m')dnl
include(`mk_lib_app_cryptor_mode_stream.m')dnl
#ifndef mk_include_guard_mk_lib_app_cryptor_mode_stream_any1_h
#define mk_include_guard_mk_lib_app_cryptor_mode_stream_any1_h

#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"


mk_lang_forward(mk_sl_cui_uint8);


mk_lib_app_cryptor_mode_stream_mm_for_all(`dnl
mk_lang_forward(mk_lib_app_cryptor_mode_stream_$1_$3);
')dnl

mk_lib_app_cryptor_mode_stream_mm_for_all(`dnl
mk_lang_forward(mk_lib_app_cryptor_mode_stream_$1_$3_iv);
')dnl

mk_lib_app_cryptor_mode_stream_mm_for_all(`dnl
mk_lang_forward(mk_lib_app_cryptor_mode_stream_$1_$3_key);
')dnl


enum mk_lib_app_cryptor_mode_stream_any1_id_e
{
mk_lib_app_cryptor_mode_stream_mm_for_all(`dnl
	mk_lib_app_cryptor_mode_stream_any1_id_e_$1_$3,
')dnl
	mk_lib_app_cryptor_mode_stream_any1_id_e_dummy_end
};
typedef enum mk_lib_app_cryptor_mode_stream_any1_id_e mk_lib_app_cryptor_mode_stream_any1_id_t;

union mk_lib_app_cryptor_mode_stream_any1_bigid_data_u
{
	mk_lib_app_cryptor_mode_stream_any1_id_t m_id;
	mk_lang_types_void_pt m_align;
};
typedef union mk_lib_app_cryptor_mode_stream_any1_bigid_data_u mk_lib_app_cryptor_mode_stream_any1_bigid_data_t;
struct mk_lib_app_cryptor_mode_stream_any1_bigid_s
{
	mk_lib_app_cryptor_mode_stream_any1_bigid_data_t m_data;
};
typedef struct mk_lib_app_cryptor_mode_stream_any1_bigid_s mk_lib_app_cryptor_mode_stream_any1_bigid_t;


union mk_lib_app_cryptor_mode_stream_civ_any1_ptr_data_u
{
	mk_lang_types_void_pct m_void;
mk_lib_app_cryptor_mode_stream_mm_for_all(`dnl
	mk_lib_app_cryptor_mode_stream_$1_$3_iv_pct m_$1_$3;
')dnl
};
typedef union mk_lib_app_cryptor_mode_stream_civ_any1_ptr_data_u mk_lib_app_cryptor_mode_stream_civ_any1_ptr_data_t;
struct mk_lib_app_cryptor_mode_stream_civ_any1_ptr_s
{
	mk_lib_app_cryptor_mode_stream_civ_any1_ptr_data_t m_data;
};
typedef struct mk_lib_app_cryptor_mode_stream_civ_any1_ptr_s mk_lib_app_cryptor_mode_stream_civ_any1_ptr_t;
mk_lang_typedef(mk_lib_app_cryptor_mode_stream_civ_any1_ptr);

union mk_lib_app_cryptor_mode_stream_ckey_any1_ptr_data_u
{
	mk_lang_types_void_pct m_void;
mk_lib_app_cryptor_mode_stream_mm_for_all(`dnl
	mk_lib_app_cryptor_mode_stream_$1_$3_key_pct m_$1_$3;
')dnl
};
typedef union mk_lib_app_cryptor_mode_stream_ckey_any1_ptr_data_u mk_lib_app_cryptor_mode_stream_ckey_any1_ptr_data_t;
struct mk_lib_app_cryptor_mode_stream_ckey_any1_ptr_s
{
	mk_lib_app_cryptor_mode_stream_ckey_any1_ptr_data_t m_data;
};
typedef struct mk_lib_app_cryptor_mode_stream_ckey_any1_ptr_s mk_lib_app_cryptor_mode_stream_ckey_any1_ptr_t;
mk_lang_typedef(mk_lib_app_cryptor_mode_stream_ckey_any1_ptr);

union mk_lib_app_cryptor_mode_stream_any1_ptr_data_u
{
	mk_lang_types_void_pt m_void;
mk_lib_app_cryptor_mode_stream_mm_for_all(`dnl
	mk_lib_app_cryptor_mode_stream_$1_$3_pt m_$1_$3;
')dnl
};
typedef union mk_lib_app_cryptor_mode_stream_any1_ptr_data_u mk_lib_app_cryptor_mode_stream_any1_ptr_data_t;
struct mk_lib_app_cryptor_mode_stream_any1_ptr_s
{
	mk_lib_app_cryptor_mode_stream_any1_ptr_data_t m_data;
};
typedef struct mk_lib_app_cryptor_mode_stream_any1_ptr_s mk_lib_app_cryptor_mode_stream_any1_ptr_t;
mk_lang_typedef(mk_lib_app_cryptor_mode_stream_any1_ptr);


struct mk_lib_app_cryptor_mode_stream_any1_ptrid_s
{
	mk_lib_app_cryptor_mode_stream_any1_bigid_t m_id;
	mk_lib_app_cryptor_mode_stream_any1_ptr_t m_ptr;
};
typedef struct mk_lib_app_cryptor_mode_stream_any1_ptrid_s mk_lib_app_cryptor_mode_stream_any1_ptrid_t;
mk_lang_typedef(mk_lib_app_cryptor_mode_stream_any1_ptrid);


mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_lib_app_cryptor_mode_stream_any1_st_iv_len_v(mk_lib_app_cryptor_mode_stream_any1_id_t const id) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_lib_app_cryptor_mode_stream_any1_st_key_len_v(mk_lib_app_cryptor_mode_stream_any1_id_t const id) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_lib_app_cryptor_mode_stream_any1_st_msg_len_v(mk_lib_app_cryptor_mode_stream_any1_id_t const id) mk_lang_noexcept;

mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_app_cryptor_mode_stream_any1_ptr_rw_set_iv(mk_lib_app_cryptor_mode_stream_any1_ptr_pt const ptr, mk_lib_app_cryptor_mode_stream_any1_id_t const id, mk_lib_app_cryptor_mode_stream_civ_any1_ptr_pct const iv) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_app_cryptor_mode_stream_any1_ptr_rw_set_key_enc(mk_lib_app_cryptor_mode_stream_any1_ptr_pt const ptr, mk_lib_app_cryptor_mode_stream_any1_id_t const id, mk_lib_app_cryptor_mode_stream_ckey_any1_ptr_pct const key) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_app_cryptor_mode_stream_any1_ptr_rw_set_key_dec(mk_lib_app_cryptor_mode_stream_any1_ptr_pt const ptr, mk_lib_app_cryptor_mode_stream_any1_id_t const id, mk_lib_app_cryptor_mode_stream_ckey_any1_ptr_pct const key) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_app_cryptor_mode_stream_any1_ptr_rw_encrypt(mk_lib_app_cryptor_mode_stream_any1_ptr_pt const ptr, mk_lib_app_cryptor_mode_stream_any1_id_t const id, mk_sl_cui_uint8_pct const input_buf, mk_lang_types_usize_t const input_len, mk_sl_cui_uint8_pt const output_buf, mk_lang_types_usize_t const output_len, mk_lang_types_usize_pt const output_used) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_app_cryptor_mode_stream_any1_ptr_rw_decrypt(mk_lib_app_cryptor_mode_stream_any1_ptr_pt const ptr, mk_lib_app_cryptor_mode_stream_any1_id_t const id, mk_sl_cui_uint8_pct const input_buf, mk_lang_types_usize_t const input_len, mk_sl_cui_uint8_pt const output_buf, mk_lang_types_usize_t const output_len, mk_lang_types_usize_pt const output_used) mk_lang_noexcept;

mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_app_cryptor_mode_stream_any1_ptrid_rw_construct(mk_lib_app_cryptor_mode_stream_any1_ptrid_pt const any1, mk_lib_app_cryptor_mode_stream_any1_id_t const id) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_app_cryptor_mode_stream_any1_ptrid_rw_set_iv(mk_lib_app_cryptor_mode_stream_any1_ptrid_pt const any1, mk_lib_app_cryptor_mode_stream_civ_any1_ptr_pct const iv) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_app_cryptor_mode_stream_any1_ptrid_rw_set_key_enc(mk_lib_app_cryptor_mode_stream_any1_ptrid_pt const any1, mk_lib_app_cryptor_mode_stream_ckey_any1_ptr_pct const key) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_app_cryptor_mode_stream_any1_ptrid_rw_set_key_dec(mk_lib_app_cryptor_mode_stream_any1_ptrid_pt const any1, mk_lib_app_cryptor_mode_stream_ckey_any1_ptr_pct const key) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_app_cryptor_mode_stream_any1_ptrid_rw_encrypt(mk_lib_app_cryptor_mode_stream_any1_ptrid_pt const any1, mk_sl_cui_uint8_pct const input_buf, mk_lang_types_usize_t const input_len, mk_sl_cui_uint8_pt const output_buf, mk_lang_types_usize_t const output_len, mk_lang_types_usize_pt const output_used) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_app_cryptor_mode_stream_any1_ptrid_rw_decrypt(mk_lib_app_cryptor_mode_stream_any1_ptrid_pt const any1, mk_sl_cui_uint8_pct const input_buf, mk_lang_types_usize_t const input_len, mk_sl_cui_uint8_pt const output_buf, mk_lang_types_usize_t const output_len, mk_lang_types_usize_pt const output_used) mk_lang_noexcept;


#if mk_lang_jumbo_have
#include "mk_lib_app_cryptor_mode_stream_any1.c"
#endif
#endif
