/* NIST FIPS PUB 197 */


#include "mk_lang_alignas.h"
#include "mk_lang_charbit.h"
#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_pow2.h"
#include "mk_lang_types.h"
#include "mk_sl_uint8.h"


#include "mk_lib_crypto_alg_aes_x86_inl_defd.h"


#include mk_lib_crypto_alg_aes_x86_inl_defd_base_file


enum mk_lib_crypto_alg_aes_x86_inl_defd_key_len_e { mk_lib_crypto_alg_aes_x86_inl_defd_key_len_v = mk_lib_crypto_alg_aes_x86_inl_defd_key_bytes };
enum mk_lib_crypto_alg_aes_x86_inl_defd_msg_len_e { mk_lib_crypto_alg_aes_x86_inl_defd_msg_len_v = mk_lib_crypto_alg_aes_x86_inl_defd_msg_bytes };
enum mk_lib_crypto_alg_aes_x86_inl_defd_schedule_len_e { mk_lib_crypto_alg_aes_x86_inl_defd_schedule_len_v = mk_lib_crypto_alg_aes_x86_inl_defd_schedule_bytes };


typedef mk_lib_crypto_alg_aes_x86_inl_defd_base_key_t mk_lib_crypto_alg_aes_x86_inl_defd_key_t;
typedef mk_lib_crypto_alg_aes_x86_inl_defd_key_t const mk_lib_crypto_alg_aes_x86_inl_defd_key_ct;
typedef mk_lib_crypto_alg_aes_x86_inl_defd_key_t* mk_lib_crypto_alg_aes_x86_inl_defd_key_pt;
typedef mk_lib_crypto_alg_aes_x86_inl_defd_key_t const* mk_lib_crypto_alg_aes_x86_inl_defd_key_pct;

typedef mk_lib_crypto_alg_aes_x86_inl_defd_base_msg_t mk_lib_crypto_alg_aes_x86_inl_defd_msg_t;
typedef mk_lib_crypto_alg_aes_x86_inl_defd_msg_t const mk_lib_crypto_alg_aes_x86_inl_defd_msg_ct;
typedef mk_lib_crypto_alg_aes_x86_inl_defd_msg_t* mk_lib_crypto_alg_aes_x86_inl_defd_msg_pt;
typedef mk_lib_crypto_alg_aes_x86_inl_defd_msg_t const* mk_lib_crypto_alg_aes_x86_inl_defd_msg_pct;

typedef mk_lib_crypto_alg_aes_x86_inl_defd_base_schedule_t mk_lib_crypto_alg_aes_x86_inl_defd_schedule_t;
typedef mk_lib_crypto_alg_aes_x86_inl_defd_schedule_t const mk_lib_crypto_alg_aes_x86_inl_defd_schedule_ct;
typedef mk_lib_crypto_alg_aes_x86_inl_defd_schedule_t* mk_lib_crypto_alg_aes_x86_inl_defd_schedule_pt;
typedef mk_lib_crypto_alg_aes_x86_inl_defd_schedule_t const* mk_lib_crypto_alg_aes_x86_inl_defd_schedule_pct;


mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_alg_aes_x86_inl_defd_schedule_encrypt(mk_lib_crypto_alg_aes_x86_inl_defd_schedule_pct const schedule, mk_lib_crypto_alg_aes_x86_inl_defd_msg_pct const input, mk_lib_crypto_alg_aes_x86_inl_defd_msg_pt const output, mk_lang_types_usize_t const nblocks) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_alg_aes_x86_inl_defd_schedule_decrypt(mk_lib_crypto_alg_aes_x86_inl_defd_schedule_pct const schedule, mk_lib_crypto_alg_aes_x86_inl_defd_msg_pct const input, mk_lib_crypto_alg_aes_x86_inl_defd_msg_pt const output, mk_lang_types_usize_t const nblocks) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_alg_aes_x86_inl_defd_expand_enc(mk_lib_crypto_alg_aes_x86_inl_defd_key_pct const key, mk_lib_crypto_alg_aes_x86_inl_defd_schedule_pt const schedule) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_alg_aes_x86_inl_defd_expand_dec(mk_lib_crypto_alg_aes_x86_inl_defd_key_pct const key, mk_lib_crypto_alg_aes_x86_inl_defd_schedule_pt const schedule) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_alg_aes_x86_inl_defd_encrypt(mk_lib_crypto_alg_aes_x86_inl_defd_key_pct const key, mk_lib_crypto_alg_aes_x86_inl_defd_msg_pct const input, mk_lib_crypto_alg_aes_x86_inl_defd_msg_pt const output) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_alg_aes_x86_inl_defd_decrypt(mk_lib_crypto_alg_aes_x86_inl_defd_key_pct const key, mk_lib_crypto_alg_aes_x86_inl_defd_msg_pct const input, mk_lib_crypto_alg_aes_x86_inl_defd_msg_pt const output) mk_lang_noexcept;


#include "mk_lib_crypto_alg_aes_x86_inl_defu.h"
