#ifndef mk_include_guard_mk_lib_iip_cp_client_types_h
#define mk_include_guard_mk_lib_iip_cp_client_types_h


#include "mk_lang_bui.h"
#include "mk_lang_charbit.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lib_iip_buffer.h"
#include "mk_lib_iip_cp_local_destination.h"
#include "mk_lib_iip_cp_remote_destination.h"
#include "mk_lib_iip_cp_types.h"
#include "mk_lib_net.h"
#include "mk_sl_cui_uint16.h"


#define mk_sl_cui_t_name mk_lib_iip_cp_client_types_handle_wrapper
#define mk_sl_cui_t_base_type_name mk_lang_bui_uintptr
#define mk_sl_cui_t_count 1
#define mk_sl_cui_t_disable_big_div 1
#define mk_sl_cui_t_base_type_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_sl_cui_t_inline 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"
#define mk_lib_iip_cp_client_types_handle_wrapper_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_lib_iip_cp_client_types_handle_wrapper_size_bytes_d (mk_lang_bui_uintptr_size_bits_d / mk_lang_charbit)

#define mk_sl_cui_t_name mk_lib_iip_cp_client_types_handle_local
#define mk_sl_cui_t_base_type_name mk_lang_bui_uintptr
#define mk_sl_cui_t_count 1
#define mk_sl_cui_t_disable_big_div 1
#define mk_sl_cui_t_base_type_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_sl_cui_t_inline 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"
#define mk_lib_iip_cp_client_types_handle_local_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_lib_iip_cp_client_types_handle_local_size_bytes_d (mk_lang_bui_uintptr_size_bits_d / mk_lang_charbit)

#define mk_sl_cui_t_name mk_lib_iip_cp_client_types_handle_connection
#define mk_sl_cui_t_base_type_name mk_lang_bui_uintptr
#define mk_sl_cui_t_count 1
#define mk_sl_cui_t_disable_big_div 1
#define mk_sl_cui_t_base_type_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_sl_cui_t_inline 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"
#define mk_lib_iip_cp_client_types_handle_connection_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_lib_iip_cp_client_types_handle_connection_size_bytes_d (mk_lang_bui_uintptr_size_bits_d / mk_lang_charbit)

#define mk_sl_cui_t_name mk_lib_iip_cp_client_types_handle_session
#define mk_sl_cui_t_base_type_name mk_lang_bui_uintptr
#define mk_sl_cui_t_count 1
#define mk_sl_cui_t_disable_big_div 1
#define mk_sl_cui_t_base_type_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_sl_cui_t_inline 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"
#define mk_lib_iip_cp_client_types_handle_session_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_lib_iip_cp_client_types_handle_session_size_bytes_d (mk_lang_bui_uintptr_size_bits_d / mk_lang_charbit)

#define mk_sl_cui_t_name mk_lib_iip_cp_client_types_handle_socket_listener
#define mk_sl_cui_t_base_type_name mk_lang_bui_uintptr
#define mk_sl_cui_t_count 1
#define mk_sl_cui_t_disable_big_div 1
#define mk_sl_cui_t_base_type_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_sl_cui_t_inline 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"
#define mk_lib_iip_cp_client_types_handle_socket_listener_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_lib_iip_cp_client_types_handle_socket_listener_size_bytes_d (mk_lang_bui_uintptr_size_bits_d / mk_lang_charbit)

#define mk_sl_cui_t_name mk_lib_iip_cp_client_types_handle_socket_connect
#define mk_sl_cui_t_base_type_name mk_lang_bui_uintptr
#define mk_sl_cui_t_count 1
#define mk_sl_cui_t_disable_big_div 1
#define mk_sl_cui_t_base_type_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_sl_cui_t_inline 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"
#define mk_lib_iip_cp_client_types_handle_socket_connect_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_lib_iip_cp_client_types_handle_socket_connect_size_bytes_d (mk_lang_bui_uintptr_size_bits_d / mk_lang_charbit)


struct mk_lib_iip_cp_client_types_iocp_settings_s
{
	int m_dummy;
};
typedef struct mk_lib_iip_cp_client_types_iocp_settings_s mk_lib_iip_cp_client_types_iocp_settings_t;
mk_lang_typedef(mk_lib_iip_cp_client_types_iocp_settings);


struct mk_lib_iip_cp_client_types_application_settings_s
{
	mk_lib_iip_cp_client_types_iocp_settings_t m_iocp_settings;
	int m_dummy;
};
typedef struct mk_lib_iip_cp_client_types_application_settings_s mk_lib_iip_cp_client_types_application_settings_t;
mk_lang_typedef(mk_lib_iip_cp_client_types_application_settings);


#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_types_local_settings_s
{
	mk_lib_net_destination_t m_destination;
};
typedef struct mk_lib_iip_cp_client_types_local_settings_s mk_lib_iip_cp_client_types_local_settings_t;
mk_lang_typedef(mk_lib_iip_cp_client_types_local_settings);
#include "mk_lang_warning_msvc_pop.h"


struct mk_lib_iip_cp_client_types_connection_authentication_s
{
	mk_lib_iip_cp_types_string_t m_username;
	mk_lib_iip_cp_types_string_t m_password;
};
typedef struct mk_lib_iip_cp_client_types_connection_authentication_s mk_lib_iip_cp_client_types_connection_authentication_t;
mk_lang_typedef(mk_lib_iip_cp_client_types_connection_authentication);

struct mk_lib_iip_cp_client_types_connection_settings_s
{
	mk_lib_net_destination_t m_destination;
	mk_lib_iip_cp_client_types_connection_authentication_t m_authentication;
};
typedef struct mk_lib_iip_cp_client_types_connection_settings_s mk_lib_iip_cp_client_types_connection_settings_t;
mk_lang_typedef(mk_lib_iip_cp_client_types_connection_settings);


#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_types_session_settings_s
{
	mk_lib_iip_cp_client_types_handle_connection_t m_connection;
	mk_lib_iip_cp_local_destination_t m_local_destination;
	mk_lib_iip_cp_client_types_handle_session_t m_master_session;
	mk_lib_iip_cp_types_strpairs_t m_options;
};
typedef struct mk_lib_iip_cp_client_types_session_settings_s mk_lib_iip_cp_client_types_session_settings_t;
mk_lang_typedef(mk_lib_iip_cp_client_types_session_settings);
#include "mk_lang_warning_msvc_pop.h"

enum mk_lib_iip_cp_client_types_session_settings_options_message_reliability_e
{
	mk_lib_iip_cp_client_types_session_settings_options_message_reliability_e_best_effort,
	mk_lib_iip_cp_client_types_session_settings_options_message_reliability_e_none,
	mk_lib_iip_cp_client_types_session_settings_options_message_reliability_e_dummy_end
};
typedef enum mk_lib_iip_cp_client_types_session_settings_options_message_reliability_e mk_lib_iip_cp_client_types_session_settings_options_message_reliability_t;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_construct(mk_lib_iip_cp_types_strpairs_pt const options) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_client_message_timeout(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_slong_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_crypto_low_tag_threshold(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_crypto_ratchet_inbound_tags(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_crypto_ratchet_outbound_tags(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_crypto_tags_to_send(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_explicit_peers(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_pchar_pct const val_buf, mk_lang_types_sint_t const val_len) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_i2cp_dont_publish_lease_set(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_bool_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_i2cp_fast_receive(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_bool_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_i2cp_lease_set_auth_type(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_i2cp_lease_set_enc_type(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_slong_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_i2cp_lease_set_offline_expiration(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_ulong_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_i2cp_lease_set_offline_signature(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_pchar_pct const val_buf, mk_lang_types_sint_t const val_len) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_i2cp_lease_set_priv_key(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_pchar_pct const val_buf, mk_lang_types_sint_t const val_len) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_i2cp_lease_set_secret(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_pchar_pct const val_buf, mk_lang_types_sint_t const val_len) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_i2cp_lease_set_transient_public_key(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_pchar_pct const val_buf, mk_lang_types_sint_t const val_len) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_i2cp_lease_set_type(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_i2cp_message_reliability(mk_lib_iip_cp_types_strpairs_pt const options, mk_lib_iip_cp_client_types_session_settings_options_message_reliability_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_i2cp_password(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_pchar_pct const val_buf, mk_lang_types_sint_t const val_len) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_i2cp_username(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_pchar_pct const val_buf, mk_lang_types_sint_t const val_len) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_inbound_allow_zero_hop(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_bool_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_inbound_backup_quantity(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_inbound_ip_restriction(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_inbound_length(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_inbound_length_variance(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_inbound_nickname(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_pchar_pct const val_buf, mk_lang_types_sint_t const val_len) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_inbound_quantity(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_inbound_random_key(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_pchar_pct const val_buf, mk_lang_types_sint_t const val_len) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_outbound_allow_zero_hop(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_bool_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_outbound_backup_quantity(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_outbound_ip_restriction(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_outbound_length(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_outbound_length_variance(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_outbound_nickname(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_pchar_pct const val_buf, mk_lang_types_sint_t const val_len) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_outbound_priority(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_outbound_quantity(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_sint_t const val) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_outbound_random_key(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_pchar_pct const val_buf, mk_lang_types_sint_t const val_len) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_types_session_settings_options_rw_set_should_bundle_reply_info(mk_lib_iip_cp_types_strpairs_pt const options, mk_lang_types_bool_t const val) mk_lang_noexcept;


#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_types_socket_listener_settings_s
{
	mk_lib_iip_cp_client_types_handle_session_t m_session;
	mk_sl_cui_uint16_t m_port;
};
typedef struct mk_lib_iip_cp_client_types_socket_listener_settings_s mk_lib_iip_cp_client_types_socket_listener_settings_t;
mk_lang_typedef(mk_lib_iip_cp_client_types_socket_listener_settings);
#include "mk_lang_warning_msvc_pop.h"


#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_types_socket_connect_settings_s
{
	mk_lib_iip_cp_client_types_handle_session_t m_session;
	mk_lib_iip_cp_remote_destination_t m_remote_destination;
	mk_sl_cui_uint16_t m_port;
};
typedef struct mk_lib_iip_cp_client_types_socket_connect_settings_s mk_lib_iip_cp_client_types_socket_connect_settings_t;
mk_lang_typedef(mk_lib_iip_cp_client_types_socket_connect_settings);
#include "mk_lang_warning_msvc_pop.h"


#define mk_sl_cui_t_name mk_lib_iip_cp_client_types_handle_lookup_host_name
#define mk_sl_cui_t_base_type_name mk_lang_bui_uintptr
#define mk_sl_cui_t_count 1
#define mk_sl_cui_t_disable_big_div 1
#define mk_sl_cui_t_base_type_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_sl_cui_t_inline 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"
#define mk_lib_iip_cp_client_types_handle_lookup_host_name_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_lib_iip_cp_client_types_handle_lookup_host_name_size_bytes_d (mk_lang_bui_uintptr_size_bits_d / mk_lang_charbit)

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_types_lookup_host_name_s
{
	mk_lib_iip_cp_client_types_handle_session_t m_session;
	mk_lang_types_pchar_pct m_host_name_buf;
	mk_lang_types_sint_t m_host_name_len;
	mk_lang_types_bool_t m_done;
	mk_lang_types_sint_t m_result_code;
	mk_lib_iip_buffer_t m_destination;
	mk_lib_iip_cp_client_types_handle_lookup_host_name_t m_internal;
};
typedef struct mk_lib_iip_cp_client_types_lookup_host_name_s mk_lib_iip_cp_client_types_lookup_host_name_t;
mk_lang_typedef(mk_lib_iip_cp_client_types_lookup_host_name);
#include "mk_lang_warning_msvc_pop.h"


#if mk_lang_jumbo_have
#include "mk_lib_iip_cp_client_types.c"
#endif
#endif
