#include "mk_lang_concat.h"


#if(!( \
	defined mk_lib_crypto_alg_twofish_base_t_name && \
	defined mk_lib_crypto_alg_twofish_base_t_keylen && \
	1 \
))
#error xxxxxxxxxx
#endif

#define mk_lib_crypto_alg_twofish_base_inl_defd_name mk_lib_crypto_alg_twofish_base_t_name
#define mk_lib_crypto_alg_twofish_base_inl_defd_keylen (mk_lib_crypto_alg_twofish_base_t_keylen)

#if(!( \
	mk_lib_crypto_alg_twofish_base_inl_defd_keylen == 128 || \
	mk_lib_crypto_alg_twofish_base_inl_defd_keylen == 192 || \
	mk_lib_crypto_alg_twofish_base_inl_defd_keylen == 256 || \
	0 \
))
#error xxxxxxxxxx
#endif


#define mk_lib_crypto_alg_twofish_base_inl_defd_nr mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _nr)

#define mk_lib_crypto_alg_twofish_base_inl_defd_key_len_m mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _key_len_m)
#define mk_lib_crypto_alg_twofish_base_inl_defd_key_len_e mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _key_len_e)
#define mk_lib_crypto_alg_twofish_base_inl_defd_key_len_v mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _key_len_v)

#define mk_lib_crypto_alg_twofish_base_inl_defd_msg_len_m mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _msg_len_m)
#define mk_lib_crypto_alg_twofish_base_inl_defd_msg_len_e mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _msg_len_e)
#define mk_lib_crypto_alg_twofish_base_inl_defd_msg_len_v mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _msg_len_v)

#define mk_lib_crypto_alg_twofish_base_inl_defd_schedule_len_m mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _schedule_len_m)
#define mk_lib_crypto_alg_twofish_base_inl_defd_schedule_len_e mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _schedule_len_e)
#define mk_lib_crypto_alg_twofish_base_inl_defd_schedule_len_v mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _schedule_len_v)

#define mk_lib_crypto_alg_twofish_base_inl_defd_key_data_u mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _key_data_u)
#define mk_lib_crypto_alg_twofish_base_inl_defd_key_data_t mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _key_data_t)
#define mk_lib_crypto_alg_twofish_base_inl_defd_key_s mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _key_s)
#define mk_lib_crypto_alg_twofish_base_inl_defd_key_t mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _key_t)
#define mk_lib_crypto_alg_twofish_base_inl_defd_key_ct mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _key_ct)
#define mk_lib_crypto_alg_twofish_base_inl_defd_key_pt mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _key_pt)
#define mk_lib_crypto_alg_twofish_base_inl_defd_key_pct mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _key_pct)

#define mk_lib_crypto_alg_twofish_base_inl_defd_msg_data_u mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _msg_data_u)
#define mk_lib_crypto_alg_twofish_base_inl_defd_msg_data_t mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _msg_data_t)
#define mk_lib_crypto_alg_twofish_base_inl_defd_msg_s mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _msg_s)
#define mk_lib_crypto_alg_twofish_base_inl_defd_msg_t mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _msg_t)
#define mk_lib_crypto_alg_twofish_base_inl_defd_msg_ct mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _msg_ct)
#define mk_lib_crypto_alg_twofish_base_inl_defd_msg_pt mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _msg_pt)
#define mk_lib_crypto_alg_twofish_base_inl_defd_msg_pct mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _msg_pct)

#define mk_lib_crypto_alg_twofish_base_inl_defd_schedule_data_u mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _schedule_data_u)
#define mk_lib_crypto_alg_twofish_base_inl_defd_schedule_data_t mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _schedule_data_t)
#define mk_lib_crypto_alg_twofish_base_inl_defd_schedule_s mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _schedule_s)
#define mk_lib_crypto_alg_twofish_base_inl_defd_schedule_t mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _schedule_t)
#define mk_lib_crypto_alg_twofish_base_inl_defd_schedule_ct mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _schedule_ct)
#define mk_lib_crypto_alg_twofish_base_inl_defd_schedule_pt mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _schedule_pt)
#define mk_lib_crypto_alg_twofish_base_inl_defd_schedule_pct mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _schedule_pct)

#define mk_lib_crypto_alg_twofish_base_inl_defd_schedule_encrypt mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _schedule_encrypt)
#define mk_lib_crypto_alg_twofish_base_inl_defd_schedule_decrypt mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _schedule_decrypt)
#define mk_lib_crypto_alg_twofish_base_inl_defd_expand_enc mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _expand_enc)
#define mk_lib_crypto_alg_twofish_base_inl_defd_expand_dec mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _expand_dec)
#define mk_lib_crypto_alg_twofish_base_inl_defd_encrypt mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _encrypt)
#define mk_lib_crypto_alg_twofish_base_inl_defd_decrypt mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _decrypt)


#define mk_lib_crypto_alg_twofish_base_inl_defd_uint328_data_u mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _uint328_data_u)
#define mk_lib_crypto_alg_twofish_base_inl_defd_uint328_data_t mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _uint328_data_t)
#define mk_lib_crypto_alg_twofish_base_inl_defd_uint328_s mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _uint328_s)
#define mk_lib_crypto_alg_twofish_base_inl_defd_uint328_t mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _uint328_t)

#define mk_lib_crypto_alg_twofish_base_inl_defd_table_data_u mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _table_data_u)
#define mk_lib_crypto_alg_twofish_base_inl_defd_table_data_t mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _table_data_t)
#define mk_lib_crypto_alg_twofish_base_inl_defd_table_s mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _table_s)
#define mk_lib_crypto_alg_twofish_base_inl_defd_table_t mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _table_t)

#define mk_lib_crypto_alg_twofish_base_inl_defd_tables_data_s mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _tables_data_s)
#define mk_lib_crypto_alg_twofish_base_inl_defd_tables_data_t mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _tables_data_t)
#define mk_lib_crypto_alg_twofish_base_inl_defd_tables_s mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _tables_s)
#define mk_lib_crypto_alg_twofish_base_inl_defd_tables_t mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _tables_t)

#define mk_lib_crypto_alg_twofish_base_inl_defd_tables mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _tables)

#define mk_lib_crypto_alg_twofish_base_inl_defd_lfsr1 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _lfsr1)
#define mk_lib_crypto_alg_twofish_base_inl_defd_lfsr2 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _lfsr2)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul1 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul1)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mulx mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mulx)
#define mk_lib_crypto_alg_twofish_base_inl_defd_muly mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _muly)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul00 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul00)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul01 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul01)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul02 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul02)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul03 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul03)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul10 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul10)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul11 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul11)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul12 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul12)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul13 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul13)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul20 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul20)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul21 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul21)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul22 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul22)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul23 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul23)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul30 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul30)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul31 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul31)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul32 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul32)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mul33 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mul33)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mulxy mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mulxy)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx00 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx00)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx01 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx01)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx02 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx02)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx03 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx03)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx04 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx04)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx10 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx10)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx11 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx11)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx12 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx12)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx13 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx13)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx14 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx14)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx20 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx20)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx21 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx21)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx22 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx22)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx23 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx23)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx24 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx24)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx30 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx30)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx31 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx31)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx32 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx32)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx33 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx33)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idx34 mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idx34)
#define mk_lib_crypto_alg_twofish_base_inl_defd_idxxy mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _idxxy)
#define mk_lib_crypto_alg_twofish_base_inl_defd_fx mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _fx)
#define mk_lib_crypto_alg_twofish_base_inl_defd_f mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _f)
#define mk_lib_crypto_alg_twofish_base_inl_defd_rsrem mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _rsrem)
#define mk_lib_crypto_alg_twofish_base_inl_defd_mds mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _mds)
#define mk_lib_crypto_alg_twofish_base_inl_defd_expand mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _expand)
#define mk_lib_crypto_alg_twofish_base_inl_defd_rnd_enc mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _rndenc)
#define mk_lib_crypto_alg_twofish_base_inl_defd_rnd_dec mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _rnddec)
#define mk_lib_crypto_alg_twofish_base_inl_defd_one_enc mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _oneenc)
#define mk_lib_crypto_alg_twofish_base_inl_defd_one_dec mk_lang_concat(mk_lib_crypto_alg_twofish_base_inl_defd_name, _onedec)
