#ifndef mk_include_guard_mk_lib_iip_key_sgn_dsa_sha1_windows_h
#define mk_include_guard_mk_lib_iip_key_sgn_dsa_sha1_windows_h


#include "mk_lang_jumbo.h"
#include "mk_lang_platform.h"
#if mk_lang_platform_is_windows_at_least_any


#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_static_param.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"
#include "mk_sl_cui_uint8.h"
#include "mk_win_dll_bcrypt.h"


#define mk_lib_iip_key_sgn_dsa_sha1_windows_pri_len_d 20
#define mk_lib_iip_key_sgn_dsa_sha1_windows_pub_len_d 128
#define mk_lib_iip_key_sgn_dsa_sha1_windows_digest_len_d 20
#define mk_lib_iip_key_sgn_dsa_sha1_windows_signature_len_d 40

enum mk_lib_iip_key_sgn_dsa_sha1_windows_pri_len_e{ mk_lib_iip_key_sgn_dsa_sha1_windows_pri_len_v = mk_lib_iip_key_sgn_dsa_sha1_windows_pri_len_d }; typedef enum mk_lib_iip_key_sgn_dsa_sha1_windows_pri_len_e mk_lib_iip_key_sgn_dsa_sha1_windows_pri_len_t;
enum mk_lib_iip_key_sgn_dsa_sha1_windows_pub_len_e{ mk_lib_iip_key_sgn_dsa_sha1_windows_pub_len_v = mk_lib_iip_key_sgn_dsa_sha1_windows_pub_len_d }; typedef enum mk_lib_iip_key_sgn_dsa_sha1_windows_pub_len_e mk_lib_iip_key_sgn_dsa_sha1_windows_pub_len_t;
enum mk_lib_iip_key_sgn_dsa_sha1_windows_digest_len_e{ mk_lib_iip_key_sgn_dsa_sha1_windows_digest_len_v = mk_lib_iip_key_sgn_dsa_sha1_windows_digest_len_d }; typedef enum mk_lib_iip_key_sgn_dsa_sha1_windows_digest_len_e mk_lib_iip_key_sgn_dsa_sha1_windows_digest_len_t;
enum mk_lib_iip_key_sgn_dsa_sha1_windows_signature_len_e{ mk_lib_iip_key_sgn_dsa_sha1_windows_signature_len_v = mk_lib_iip_key_sgn_dsa_sha1_windows_signature_len_d }; typedef enum mk_lib_iip_key_sgn_dsa_sha1_windows_signature_len_e mk_lib_iip_key_sgn_dsa_sha1_windows_signature_len_t;


union mk_lib_iip_key_sgn_dsa_sha1_windows_digest_data_u
{
	mk_sl_cui_uint8_t m_uint8s[mk_lib_iip_key_sgn_dsa_sha1_windows_digest_len_v];
	mk_lang_types_uint_t m_align;
};
typedef union mk_lib_iip_key_sgn_dsa_sha1_windows_digest_data_u mk_lib_iip_key_sgn_dsa_sha1_windows_digest_data_t;
struct mk_lib_iip_key_sgn_dsa_sha1_windows_digest_s
{
	mk_lib_iip_key_sgn_dsa_sha1_windows_digest_data_t m_data;
};
typedef struct mk_lib_iip_key_sgn_dsa_sha1_windows_digest_s mk_lib_iip_key_sgn_dsa_sha1_windows_digest_t;
mk_lang_typedef(mk_lib_iip_key_sgn_dsa_sha1_windows_digest);

union mk_lib_iip_key_sgn_dsa_sha1_windows_signature_data_u
{
	mk_sl_cui_uint8_t m_uint8s[mk_lib_iip_key_sgn_dsa_sha1_windows_signature_len_v];
	mk_lang_types_uint_t m_align;
};
typedef union mk_lib_iip_key_sgn_dsa_sha1_windows_signature_data_u mk_lib_iip_key_sgn_dsa_sha1_windows_signature_data_t;
struct mk_lib_iip_key_sgn_dsa_sha1_windows_signature_s
{
	mk_lib_iip_key_sgn_dsa_sha1_windows_signature_data_t m_data;
};
typedef struct mk_lib_iip_key_sgn_dsa_sha1_windows_signature_s mk_lib_iip_key_sgn_dsa_sha1_windows_signature_t;
mk_lang_typedef(mk_lib_iip_key_sgn_dsa_sha1_windows_signature);


struct mk_lib_iip_key_sgn_dsa_sha1_windows_pri_s
{
	mk_win_dll_bcrypt_key_t m_key_handle;
};
typedef struct mk_lib_iip_key_sgn_dsa_sha1_windows_pri_s mk_lib_iip_key_sgn_dsa_sha1_windows_pri_t;
mk_lang_typedef(mk_lib_iip_key_sgn_dsa_sha1_windows_pri);

struct mk_lib_iip_key_sgn_dsa_sha1_windows_pub_s
{
	mk_win_dll_bcrypt_key_t m_key_handle;
};
typedef struct mk_lib_iip_key_sgn_dsa_sha1_windows_pub_s mk_lib_iip_key_sgn_dsa_sha1_windows_pub_t;
mk_lang_typedef(mk_lib_iip_key_sgn_dsa_sha1_windows_pub);


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_windows_st_hash_data(mk_sl_cui_uint8_pct const data_buf, mk_lang_types_sint_t const data_len, mk_lib_iip_key_sgn_dsa_sha1_windows_digest_pt const digest) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_windows_pri_rw_is_valid(mk_lang_static_param(mk_sl_cui_uint8_ct, u8s, mk_lib_iip_key_sgn_dsa_sha1_windows_pri_len_v), mk_lang_types_bool_pt const is_valid) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_windows_pri_rw_generate_random(mk_lib_iip_key_sgn_dsa_sha1_windows_pri_pt const pri) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_windows_pri_rw_construct_from_u8s(mk_lib_iip_key_sgn_dsa_sha1_windows_pri_pt const pri, mk_lang_static_param(mk_sl_cui_uint8_ct, u8s, mk_lib_iip_key_sgn_dsa_sha1_windows_pri_len_v)) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_windows_pri_rw_destroy(mk_lib_iip_key_sgn_dsa_sha1_windows_pri_pt const pri) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_windows_pri_rw_export_pri_to_u8s(mk_lib_iip_key_sgn_dsa_sha1_windows_pri_pct const pri, mk_lang_static_param(mk_sl_cui_uint8_t, u8s, mk_lib_iip_key_sgn_dsa_sha1_windows_pri_len_v)) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_windows_pri_rw_export_pub_to_u8s(mk_lib_iip_key_sgn_dsa_sha1_windows_pri_pct const pri, mk_lang_static_param(mk_sl_cui_uint8_t, u8s, mk_lib_iip_key_sgn_dsa_sha1_windows_pub_len_v)) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_windows_pri_rw_get_public(mk_lib_iip_key_sgn_dsa_sha1_windows_pri_pct const pri, mk_lib_iip_key_sgn_dsa_sha1_windows_pub_pt const pub) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_windows_pri_rw_sign_digest(mk_lib_iip_key_sgn_dsa_sha1_windows_pri_pct const pri, mk_lib_iip_key_sgn_dsa_sha1_windows_digest_pct const digest, mk_lib_iip_key_sgn_dsa_sha1_windows_signature_pt const signature) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_windows_pri_rw_validate_signature(mk_lib_iip_key_sgn_dsa_sha1_windows_pri_pct const pri, mk_lib_iip_key_sgn_dsa_sha1_windows_digest_pct const digest, mk_lib_iip_key_sgn_dsa_sha1_windows_signature_pct const signature, mk_lang_types_bool_pt const is_valid) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_windows_pub_rw_construct_from_u8s(mk_lib_iip_key_sgn_dsa_sha1_windows_pub_pt const pub, mk_lang_static_param(mk_sl_cui_uint8_ct, u8s, mk_lib_iip_key_sgn_dsa_sha1_windows_pub_len_v)) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_windows_pub_rw_destroy(mk_lib_iip_key_sgn_dsa_sha1_windows_pub_pt const pub) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_windows_pub_rw_export_to_u8s(mk_lib_iip_key_sgn_dsa_sha1_windows_pub_pct const pub, mk_lang_static_param(mk_sl_cui_uint8_t, u8s, mk_lib_iip_key_sgn_dsa_sha1_windows_pub_len_v)) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_windows_pub_rw_validate_signature(mk_lib_iip_key_sgn_dsa_sha1_windows_pub_pct const pub, mk_lib_iip_key_sgn_dsa_sha1_windows_digest_pct const digest, mk_lib_iip_key_sgn_dsa_sha1_windows_signature_pct const signature, mk_lang_types_bool_pt const is_valid) mk_lang_noexcept;


#endif


#if mk_lang_jumbo_have
#include "mk_lib_iip_key_sgn_dsa_sha1_windows.c"
#endif
#endif
