#ifndef mk_include_guard_mk_lib_iip_cp_client_session_h
#define mk_include_guard_mk_lib_iip_cp_client_session_h


#include "mk_lang_bui.h"
#include "mk_lang_charbit.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"
#include "mk_lib_iip_cp_client_socket.h"
#include "mk_lib_iip_cp_local_destination.h"
#include "mk_lib_iip_cp_mallocator_global.h"
#include "mk_lib_iip_cp_message.h"
#include "mk_lib_iip_cp_types.h"


mk_lang_forward(mk_lib_iip_cp_client_shared);
mk_lang_forward(mk_lib_iip_cp_client_types_handle_socket_connect);
mk_lang_forward(mk_lib_iip_cp_client_types_handle_socket_listener);
mk_lang_forward(mk_lib_iip_cp_client_types_lookup_host_name);
mk_lang_forward(mk_lib_iip_cp_client_types_socket_connect_settings);
mk_lang_forward(mk_lib_iip_cp_client_types_socket_listener_settings);


#define mk_sl_cui_t_name mk_lib_iip_cp_client_session_handle
#define mk_sl_cui_t_base_type_name mk_lang_bui_uintptr
#define mk_sl_cui_t_count 1
#define mk_sl_cui_t_disable_big_div 1
#define mk_sl_cui_t_base_type_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_sl_cui_t_inline 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"
#define mk_lib_iip_cp_client_session_handle_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_lib_iip_cp_client_session_handle_size_bytes_d (mk_lang_bui_uintptr_size_bits_d / mk_lang_charbit)

mk_lang_forward(mk_lib_iip_cp_client_session_lookup_host_name);
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_lookup_host_name_ptr_rw_construct_void(mk_lib_iip_cp_client_session_lookup_host_name_ppt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_lookup_host_name_ptr_rw_destroy(mk_lib_iip_cp_client_session_lookup_host_name_ppt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_lookup_host_name_ptr_rw_construct_copy(mk_lib_iip_cp_client_session_lookup_host_name_ppt const dst, mk_lib_iip_cp_client_session_lookup_host_name_pcpt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_lookup_host_name_ptr_rw_construct_move(mk_lib_iip_cp_client_session_lookup_host_name_ppt const dst, mk_lib_iip_cp_client_session_lookup_host_name_ppt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_lookup_host_name_ptr_rw_assign_copy(mk_lib_iip_cp_client_session_lookup_host_name_ppt const dst, mk_lib_iip_cp_client_session_lookup_host_name_pcpt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_lookup_host_name_ptr_rw_assign_move(mk_lib_iip_cp_client_session_lookup_host_name_ppt const dst, mk_lib_iip_cp_client_session_lookup_host_name_ppt const src) mk_lang_noexcept;
#define mk_sl_vector_t_name mk_lib_iip_cp_client_session_lookups_host_name
#define mk_sl_vector_t_element_type mk_lib_iip_cp_client_session_lookup_host_name_pt
#define mk_sl_vector_t_mallocatorg mk_lib_iip_cp_mallocator_global
#define mk_sl_vector_t_element_construct_void mk_lib_iip_cp_client_session_lookup_host_name_ptr_rw_construct_void
#define mk_sl_vector_t_element_destruct mk_lib_iip_cp_client_session_lookup_host_name_ptr_rw_destroy
#define mk_sl_vector_t_element_copy_construct mk_lib_iip_cp_client_session_lookup_host_name_ptr_rw_construct_copy
#define mk_sl_vector_t_element_move_construct mk_lib_iip_cp_client_session_lookup_host_name_ptr_rw_construct_move
#define mk_sl_vector_t_element_copy_assign mk_lib_iip_cp_client_session_lookup_host_name_ptr_rw_assign_copy
#define mk_sl_vector_t_element_move_assign mk_lib_iip_cp_client_session_lookup_host_name_ptr_rw_assign_move
#include "mk_sl_vector_inl_fileh.h"
#include "mk_sl_vector_inl_fileu.h"

struct mk_lib_iip_cp_client_session_message_status_s
{
	mk_lib_iip_cp_types_messageid_t m_message_id;
	mk_lang_types_sint_t m_size;
	mk_lib_iip_cp_types_nonce_t m_nonce;
};
typedef struct mk_lib_iip_cp_client_session_message_status_s mk_lib_iip_cp_client_session_message_status_t;
mk_lang_typedef(mk_lib_iip_cp_client_session_message_status);
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_message_status_rw_construct_void(mk_lib_iip_cp_client_session_message_status_pt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_message_status_rw_destroy(mk_lib_iip_cp_client_session_message_status_pt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_message_status_rw_construct_copy(mk_lib_iip_cp_client_session_message_status_pt const dst, mk_lib_iip_cp_client_session_message_status_pct const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_message_status_rw_construct_move(mk_lib_iip_cp_client_session_message_status_pt const dst, mk_lib_iip_cp_client_session_message_status_pt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_message_status_rw_assign_copy(mk_lib_iip_cp_client_session_message_status_pt const dst, mk_lib_iip_cp_client_session_message_status_pct const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_message_status_rw_assign_move(mk_lib_iip_cp_client_session_message_status_pt const dst, mk_lib_iip_cp_client_session_message_status_pt const src, mk_lang_types_usize_t const count) mk_lang_noexcept;
#define mk_sl_dynamic_ring_t_name mk_lib_iip_cp_client_session_message_statuses
#define mk_sl_dynamic_ring_t_element_type mk_lib_iip_cp_client_session_message_status_t
#define mk_sl_dynamic_ring_t_mallocatorg mk_lib_iip_cp_mallocator_global
#define mk_sl_dynamic_ring_t_element_construct_void mk_lib_iip_cp_client_session_message_status_rw_construct_void
#define mk_sl_dynamic_ring_t_element_destruct mk_lib_iip_cp_client_session_message_status_rw_destroy
#define mk_sl_dynamic_ring_t_element_construct_copy mk_lib_iip_cp_client_session_message_status_rw_construct_copy
#define mk_sl_dynamic_ring_t_element_construct_move mk_lib_iip_cp_client_session_message_status_rw_construct_move
#define mk_sl_dynamic_ring_t_element_assign_copy mk_lib_iip_cp_client_session_message_status_rw_assign_copy
#define mk_sl_dynamic_ring_t_element_assign_move mk_lib_iip_cp_client_session_message_status_rw_assign_move
#include "mk_sl_dynamic_ring_inl_fileh.h"
#include "mk_sl_dynamic_ring_inl_fileu.h"

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_session_nonce_and_socket_s
{
	mk_lib_iip_cp_types_nonce_t m_nonce;
	mk_lib_iip_cp_client_socket_task_pt m_socket;
};
typedef struct mk_lib_iip_cp_client_session_nonce_and_socket_s mk_lib_iip_cp_client_session_nonce_and_socket_t;
mk_lang_typedef(mk_lib_iip_cp_client_session_nonce_and_socket);
#include "mk_lang_warning_msvc_pop.h"
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_nonce_and_socket_rw_cmp(mk_lib_iip_cp_client_session_nonce_and_socket_pct const a, mk_lib_iip_cp_client_session_nonce_and_socket_pct const b, mk_lang_types_sint_pt const cmp) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_nonce_and_socket_rw_construct_copy(mk_lib_iip_cp_client_session_nonce_and_socket_pt const dst, mk_lib_iip_cp_client_session_nonce_and_socket_pct const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_nonce_and_socket_rw_construct_move(mk_lib_iip_cp_client_session_nonce_and_socket_pt const dst, mk_lib_iip_cp_client_session_nonce_and_socket_pt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_nonce_and_socket_rw_destroy(mk_lib_iip_cp_client_session_nonce_and_socket_pt const x) mk_lang_noexcept;
#define mk_sl_tree_wavl_t_name mk_lib_iip_cp_client_session_nonces_and_sockets
#define mk_sl_tree_wavl_t_element_type mk_lib_iip_cp_client_session_nonce_and_socket_t
#define mk_sl_tree_wavl_t_elements_compare mk_lib_iip_cp_client_session_nonce_and_socket_rw_cmp
#define mk_sl_tree_wavl_t_mallocatorg_name mk_lib_iip_cp_mallocator_global
#define mk_sl_tree_wavl_t_validate_want 0
#define mk_sl_tree_wavl_t_element_copy_construct mk_lib_iip_cp_client_session_nonce_and_socket_rw_construct_copy
#define mk_sl_tree_wavl_t_element_move_construct mk_lib_iip_cp_client_session_nonce_and_socket_rw_construct_move
#define mk_sl_tree_wavl_t_element_destruct mk_lib_iip_cp_client_session_nonce_and_socket_rw_destroy
#include "mk_sl_tree_wavl_inl_fileh.h"
#include "mk_sl_tree_wavl_inl_fileu.h"

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_session_settings_s
{
	mk_lib_iip_cp_local_destination_t m_local_destination;
	mk_lib_iip_cp_client_session_handle_t m_master_session;
	mk_lib_iip_cp_types_strpairs_t m_options;
};
typedef struct mk_lib_iip_cp_client_session_settings_s mk_lib_iip_cp_client_session_settings_t;
mk_lang_typedef(mk_lib_iip_cp_client_session_settings);
#include "mk_lang_warning_msvc_pop.h"

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_session_state_s
{
	mk_lib_iip_cp_client_shared_pt m_shared;
	mk_lib_iip_cp_types_sessionid_t m_id;
	mk_lang_types_bool_t m_has_id;
	mk_lang_types_sint_t m_child_sessions;
	mk_lang_types_bool_t m_stop_requested;
	mk_lib_iip_cp_message_t m_msg;
	mk_lang_types_bool_t m_has_msg_pending;
	mk_lib_iip_cp_types_leasez_t m_leases;
	mk_lib_iip_cp_client_session_message_statuses_t m_msgs_available;
	mk_lang_types_bool_t m_msg_expecting;
	mk_lib_iip_cp_client_socket_tasks_t m_listening_sockets;
	mk_lib_iip_cp_client_socket_tasks_t m_connecting_sockets;
	mk_lang_types_usize_t m_idx_listening_sockets;
	mk_lang_types_usize_t m_idx_connecting_sockets;
	mk_lib_iip_cp_message_pt m_msg_from_socket;
	mk_lib_iip_cp_message_pt m_msg_to_be_accepted;
	mk_lib_iip_cp_client_session_lookups_host_name_t m_lookups_host_name_a;
	mk_lib_iip_cp_client_session_lookups_host_name_t m_lookups_host_name_b;
	mk_lib_iip_cp_client_session_nonces_and_sockets_t m_nonce_mapping;
};
typedef struct mk_lib_iip_cp_client_session_state_s mk_lib_iip_cp_client_session_state_t;
mk_lang_typedef(mk_lib_iip_cp_client_session_state);
#include "mk_lang_warning_msvc_pop.h"

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_session_s
{
	mk_lib_iip_cp_client_session_settings_t m_settings;
	mk_lib_iip_cp_client_session_state_t m_state;
};
typedef struct mk_lib_iip_cp_client_session_s mk_lib_iip_cp_client_session_t;
mk_lang_typedef(mk_lib_iip_cp_client_session);
#include "mk_lang_warning_msvc_pop.h"

enum mk_lib_iip_cp_client_session_task_result_e
{
	mk_lib_iip_cp_client_session_task_result_e_did_something,
	mk_lib_iip_cp_client_session_task_result_e_idling,
	mk_lib_iip_cp_client_session_task_result_e_want_send,
	mk_lib_iip_cp_client_session_task_result_e_want_recv,
	mk_lib_iip_cp_client_session_task_result_e_dummy_end
};
typedef enum mk_lib_iip_cp_client_session_task_result_e mk_lib_iip_cp_client_session_task_result_t;
mk_lang_typedef(mk_lib_iip_cp_client_session_task_result);

enum mk_lib_iip_cp_client_session_task_step_e
{
	mk_lib_iip_cp_client_session_task_step_e_make_msg_create_session,
	mk_lib_iip_cp_client_session_task_step_e_pickup_msg_create_session,
	mk_lib_iip_cp_client_session_task_step_e_wait_msg_session_status,
	mk_lib_iip_cp_client_session_task_step_e_wait_msg_request_leaseset,
	mk_lib_iip_cp_client_session_task_step_e_pickup_msg_create_lease_set,
	mk_lib_iip_cp_client_session_task_step_e_pickup_msg_receive_message_begin,
	mk_lib_iip_cp_client_session_task_step_e_pickup_msg_receive_message_end,
	mk_lib_iip_cp_client_session_task_step_e_pickup_msg_destroy_session,
	mk_lib_iip_cp_client_session_task_step_e_pickup_msg_from_socket,
	mk_lib_iip_cp_client_session_task_step_e_pickup_msg_lookup,
	mk_lib_iip_cp_client_session_task_step_e_idle,
	mk_lib_iip_cp_client_session_task_step_e_destroy_sent,
	mk_lib_iip_cp_client_session_task_step_e_destroyed_total,
	mk_lib_iip_cp_client_session_task_step_e_dummy_end
};
typedef enum mk_lib_iip_cp_client_session_task_step_e mk_lib_iip_cp_client_session_task_step_t;

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_session_task_s
{
	mk_lib_iip_cp_client_session_task_step_t m_step;
	mk_lib_iip_cp_client_session_t m_session;
};
typedef struct mk_lib_iip_cp_client_session_task_s mk_lib_iip_cp_client_session_task_t;
mk_lang_typedef(mk_lib_iip_cp_client_session_task);
#include "mk_lang_warning_msvc_pop.h"


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_construct(mk_lib_iip_cp_client_session_task_pt const task, mk_lib_iip_cp_client_shared_pt const shared, mk_lib_iip_cp_client_session_settings_pct const settings) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_destroy(mk_lib_iip_cp_client_session_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_on_child_session_spawned(mk_lib_iip_cp_client_session_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_on_child_session_died(mk_lib_iip_cp_client_session_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_new_socket_listener(mk_lib_iip_cp_client_session_task_pt const task, mk_lib_iip_cp_client_types_socket_listener_settings_pct const settings, mk_lib_iip_cp_client_types_handle_socket_listener_pt const socket_listener) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_gimme_msg(mk_lib_iip_cp_client_session_task_pt const task, mk_lib_iip_cp_message_ppt const msg) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_on_msg(mk_lib_iip_cp_client_session_task_pt const task, mk_lib_iip_cp_message_pt const msg) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_step(mk_lib_iip_cp_client_session_task_pt const task, mk_lib_iip_cp_client_session_task_result_pt const step_result) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_request_close(mk_lib_iip_cp_client_session_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_want_die(mk_lib_iip_cp_client_session_task_pt const task, mk_lang_types_bool_pt const want) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_lookup_host_name(mk_lib_iip_cp_client_session_task_pt const task, mk_lib_iip_cp_client_types_lookup_host_name_pt const request) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_connect_to(mk_lib_iip_cp_client_session_task_pt const task, mk_lib_iip_cp_client_types_socket_connect_settings_pct const settings, mk_lib_iip_cp_client_types_handle_socket_connect_pt const socket) mk_lang_noexcept;


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_ptr_rw_construct_void(mk_lib_iip_cp_client_session_task_ppt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_ptr_rw_destroy(mk_lib_iip_cp_client_session_task_ppt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_ptr_rw_construct_copy(mk_lib_iip_cp_client_session_task_ppt const dst, mk_lib_iip_cp_client_session_task_pcpt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_ptr_rw_construct_move(mk_lib_iip_cp_client_session_task_ppt const dst, mk_lib_iip_cp_client_session_task_ppt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_ptr_rw_assign_copy(mk_lib_iip_cp_client_session_task_ppt const dst, mk_lib_iip_cp_client_session_task_pcpt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_ptr_rw_assign_move(mk_lib_iip_cp_client_session_task_ppt const dst, mk_lib_iip_cp_client_session_task_ppt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_bool_t mk_lib_iip_cp_client_session_task_ptr_ro_eq(mk_lib_iip_cp_client_session_task_pcpt const a, mk_lib_iip_cp_client_session_task_pcpt const b) mk_lang_noexcept;

#define mk_sl_vector_t_name mk_lib_iip_cp_client_session_tasks
#define mk_sl_vector_t_element_type mk_lib_iip_cp_client_session_task_pt
#define mk_sl_vector_t_mallocatorg mk_lib_iip_cp_mallocator_global
#define mk_sl_vector_t_element_construct_void mk_lib_iip_cp_client_session_task_ptr_rw_construct_void
#define mk_sl_vector_t_element_destruct mk_lib_iip_cp_client_session_task_ptr_rw_destroy
#define mk_sl_vector_t_element_copy_construct mk_lib_iip_cp_client_session_task_ptr_rw_construct_copy
#define mk_sl_vector_t_element_move_construct mk_lib_iip_cp_client_session_task_ptr_rw_construct_move
#define mk_sl_vector_t_element_copy_assign mk_lib_iip_cp_client_session_task_ptr_rw_assign_copy
#define mk_sl_vector_t_element_move_assign mk_lib_iip_cp_client_session_task_ptr_rw_assign_move
#define mk_sl_vector_t_element_eq mk_lib_iip_cp_client_session_task_ptr_ro_eq
#include "mk_sl_vector_inl_fileh.h"
#include "mk_sl_vector_inl_fileu.h"


#if mk_lang_jumbo_have
#include "mk_lib_iip_cp_client_session.c"
#endif
#endif
