#include "mk_lang_concat.h"


#define mk_lib_crypto_mac_hmac_inl_defd_name mk_lib_crypto_mac_hmac_t_name


#define mk_lib_crypto_mac_hmac_inl_defd_prefix mk_lang_concat(mk_lib_crypto_mac_hmac_, mk_lib_crypto_mac_hmac_inl_defd_name)

#define mk_lib_crypto_mac_hmac_inl_defd_s mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_prefix, _s)
#define mk_lib_crypto_mac_hmac_inl_defd_t mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_prefix, _t)
#define mk_lib_crypto_mac_hmac_inl_defd_ct mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_prefix, _ct)
#define mk_lib_crypto_mac_hmac_inl_defd_pt mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_prefix, _pt)
#define mk_lib_crypto_mac_hmac_inl_defd_pct mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_prefix, _pct)

#define mk_lib_crypto_mac_hmac_inl_defd_init mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_prefix, _init)
#define mk_lib_crypto_mac_hmac_inl_defd_append mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_prefix, _append)
#define mk_lib_crypto_mac_hmac_inl_defd_finish mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_prefix, _finish)


#define mk_lib_crypto_mac_hmac_inl_defd_base_block_prefix mk_lang_concat(mk_lib_crypto_hash_block_, mk_lib_crypto_mac_hmac_inl_defd_name)
#define mk_lib_crypto_mac_hmac_inl_defd_base_stream_prefix mk_lang_concat(mk_lib_crypto_hash_stream_, mk_lib_crypto_mac_hmac_inl_defd_name)

#define mk_lib_crypto_mac_hmac_inl_defd_base_block_len mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_block_prefix, _block_len)
#define mk_lib_crypto_mac_hmac_inl_defd_base_digest_len mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_block_prefix, _digest_len)

#define mk_lib_crypto_mac_hmac_inl_defd_base_s mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_stream_prefix, _s)
#define mk_lib_crypto_mac_hmac_inl_defd_base_t mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_stream_prefix, _t)
#define mk_lib_crypto_mac_hmac_inl_defd_base_ct mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_stream_prefix, _ct)
#define mk_lib_crypto_mac_hmac_inl_defd_base_pt mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_stream_prefix, _pt)
#define mk_lib_crypto_mac_hmac_inl_defd_base_pct mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_stream_prefix, _pct)

#define mk_lib_crypto_mac_hmac_inl_defd_base_block_t mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_block_prefix, _block_t)
#define mk_lib_crypto_mac_hmac_inl_defd_base_block_ct mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_block_prefix, _block_ct)
#define mk_lib_crypto_mac_hmac_inl_defd_base_block_pt mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_block_prefix, _block_pt)
#define mk_lib_crypto_mac_hmac_inl_defd_base_block_pct mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_block_prefix, _block_pct)

#define mk_lib_crypto_mac_hmac_inl_defd_base_digest_t mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_block_prefix, _digest_t)
#define mk_lib_crypto_mac_hmac_inl_defd_base_digest_ct mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_block_prefix, _digest_ct)
#define mk_lib_crypto_mac_hmac_inl_defd_base_digest_pt mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_block_prefix, _digest_pt)
#define mk_lib_crypto_mac_hmac_inl_defd_base_digest_pct mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_block_prefix, _digest_pct)

#define mk_lib_crypto_mac_hmac_inl_defd_base_init mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_stream_prefix, _init)
#define mk_lib_crypto_mac_hmac_inl_defd_base_append mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_stream_prefix, _append_u8)
#define mk_lib_crypto_mac_hmac_inl_defd_base_finish mk_lang_concat(mk_lib_crypto_mac_hmac_inl_defd_base_stream_prefix, _finish)
