#ifndef mk_include_guard_mk_lib_mt_unique_lock_windows_wosa
#define mk_include_guard_mk_lib_mt_unique_lock_windows_wosa


#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_types.h"
#include "mk_lib_mt_mutex_windows_wosa.h"


struct mk_lib_mt_unique_lock_exclusive_windows_wosa_s
{
	mk_lib_mt_mutex_windows_wosa_pt m_mutex;
};
typedef struct mk_lib_mt_unique_lock_exclusive_windows_wosa_s mk_lib_mt_unique_lock_exclusive_windows_wosa_t;
typedef mk_lib_mt_unique_lock_exclusive_windows_wosa_t const mk_lib_mt_unique_lock_exclusive_windows_wosa_ct;
typedef mk_lib_mt_unique_lock_exclusive_windows_wosa_t* mk_lib_mt_unique_lock_exclusive_windows_wosa_pt;
typedef mk_lib_mt_unique_lock_exclusive_windows_wosa_t const* mk_lib_mt_unique_lock_exclusive_windows_wosa_pct;

struct mk_lib_mt_unique_lock_shared_windows_wosa_s
{
	mk_lib_mt_mutex_windows_wosa_pt m_mutex;
};
typedef struct mk_lib_mt_unique_lock_shared_windows_wosa_s mk_lib_mt_unique_lock_shared_windows_wosa_t;
typedef mk_lib_mt_unique_lock_shared_windows_wosa_t const mk_lib_mt_unique_lock_shared_windows_wosa_ct;
typedef mk_lib_mt_unique_lock_shared_windows_wosa_t* mk_lib_mt_unique_lock_shared_windows_wosa_pt;
typedef mk_lib_mt_unique_lock_shared_windows_wosa_t const* mk_lib_mt_unique_lock_shared_windows_wosa_pct;


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_mt_unique_lock_exclusive_windows_wosa_construct(mk_lib_mt_unique_lock_exclusive_windows_wosa_pt const unique_lock, mk_lib_mt_mutex_windows_wosa_pt const mutex) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_mt_unique_lock_exclusive_windows_wosa_destruct(mk_lib_mt_unique_lock_exclusive_windows_wosa_pt const unique_lock) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_mt_unique_lock_shared_windows_wosa_construct(mk_lib_mt_unique_lock_shared_windows_wosa_pt const unique_lock, mk_lib_mt_mutex_windows_wosa_pt const mutex) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_mt_unique_lock_shared_windows_wosa_destruct(mk_lib_mt_unique_lock_shared_windows_wosa_pt const unique_lock) mk_lang_noexcept;


#if mk_lang_jumbo_want == 1
#include "mk_lib_mt_unique_lock_windows_wosa.c"
#endif
#endif
