#ifndef mk_include_guard_mk_lib_crypto_hash_block_blake2s_base_h
#define mk_include_guard_mk_lib_crypto_hash_block_blake2s_base_h

#include "mk_lang_alignas.h"
#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_types.h"
#include "mk_sl_cui_uint32.h"
#include "mk_sl_cui_uint64.h"
#include "mk_sl_cui_uint8.h"


#define mk_lib_crypto_hash_block_blake2s_base_block_len_d 64
#define mk_lib_crypto_hash_block_blake2s_base_digest_len_d 32
enum mk_lib_crypto_hash_block_blake2s_base_block_len_e{ mk_lib_crypto_hash_block_blake2s_base_block_len_v = mk_lib_crypto_hash_block_blake2s_base_block_len_d }; typedef enum mk_lib_crypto_hash_block_blake2s_base_block_len_e mk_lib_crypto_hash_block_blake2s_base_block_len_t;
enum mk_lib_crypto_hash_block_blake2s_base_digest_len_e{ mk_lib_crypto_hash_block_blake2s_base_digest_len_v = mk_lib_crypto_hash_block_blake2s_base_digest_len_d }; typedef enum mk_lib_crypto_hash_block_blake2s_base_digest_len_e mk_lib_crypto_hash_block_blake2s_base_digest_len_t;


union mk_lib_crypto_hash_block_blake2s_base_block_data_u
{
	mk_lang_alignas(mk_lib_crypto_hash_block_blake2s_base_block_len_v) mk_sl_cui_uint8_t m_uint8s[mk_lib_crypto_hash_block_blake2s_base_block_len_v];
	mk_lang_types_ulllong_t m_align;
};
typedef union mk_lib_crypto_hash_block_blake2s_base_block_data_u mk_lib_crypto_hash_block_blake2s_base_block_data_t;
struct mk_lib_crypto_hash_block_blake2s_base_block_s
{
	mk_lib_crypto_hash_block_blake2s_base_block_data_t m_data;
};
typedef struct mk_lib_crypto_hash_block_blake2s_base_block_s mk_lib_crypto_hash_block_blake2s_base_block_t;
typedef mk_lib_crypto_hash_block_blake2s_base_block_t const mk_lib_crypto_hash_block_blake2s_base_block_ct;
typedef mk_lib_crypto_hash_block_blake2s_base_block_t* mk_lib_crypto_hash_block_blake2s_base_block_pt;
typedef mk_lib_crypto_hash_block_blake2s_base_block_t const* mk_lib_crypto_hash_block_blake2s_base_block_pct;

union mk_lib_crypto_hash_block_blake2s_base_digest_data_u
{
	mk_lang_alignas(mk_lib_crypto_hash_block_blake2s_base_digest_len_v) mk_sl_cui_uint8_t m_uint8s[mk_lib_crypto_hash_block_blake2s_base_digest_len_v];
	mk_lang_types_ulllong_t m_align;
};
typedef union mk_lib_crypto_hash_block_blake2s_base_digest_data_u mk_lib_crypto_hash_block_blake2s_base_digest_data_t;
struct mk_lib_crypto_hash_block_blake2s_base_digest_s
{
	mk_lib_crypto_hash_block_blake2s_base_digest_data_t m_data;
};
typedef struct mk_lib_crypto_hash_block_blake2s_base_digest_s mk_lib_crypto_hash_block_blake2s_base_digest_t;
typedef mk_lib_crypto_hash_block_blake2s_base_digest_t const mk_lib_crypto_hash_block_blake2s_base_digest_ct;
typedef mk_lib_crypto_hash_block_blake2s_base_digest_t* mk_lib_crypto_hash_block_blake2s_base_digest_pt;
typedef mk_lib_crypto_hash_block_blake2s_base_digest_t const* mk_lib_crypto_hash_block_blake2s_base_digest_pct;


struct mk_lib_crypto_hash_block_blake2s_base_s
{
	mk_sl_cui_uint32_t m_state[8];
	mk_sl_cui_uint64_t m_len;
};
typedef struct mk_lib_crypto_hash_block_blake2s_base_s mk_lib_crypto_hash_block_blake2s_base_t;
typedef mk_lib_crypto_hash_block_blake2s_base_t const mk_lib_crypto_hash_block_blake2s_base_ct;
typedef mk_lib_crypto_hash_block_blake2s_base_t* mk_lib_crypto_hash_block_blake2s_base_pt;
typedef mk_lib_crypto_hash_block_blake2s_base_t const* mk_lib_crypto_hash_block_blake2s_base_pct;


mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_hash_block_blake2s_base_init(mk_lib_crypto_hash_block_blake2s_base_pt const blake2s_base, mk_lang_types_sint_t const digest_len, mk_lang_types_sint_t const key_len, mk_lang_types_sint_t const fanout, mk_lang_types_sint_t const max_depth, mk_lang_types_ulong_t const leaf_len, mk_lang_types_ulong_t const node_offset, mk_lang_types_ulong_t const xof_len, mk_lang_types_sint_t const node_depth, mk_lang_types_sint_t const inner_len, mk_lang_types_uchar_pct const salt_buf, mk_lang_types_sint_t const salt_len, mk_lang_types_uchar_pct const personalization_buf, mk_lang_types_sint_t const personalization_len) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_hash_block_blake2s_base_append_blocks(mk_lib_crypto_hash_block_blake2s_base_pt const blake2s_base, mk_lib_crypto_hash_block_blake2s_base_block_pct const pblocks, mk_lang_types_usize_t const nblocks) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_hash_block_blake2s_base_finish(mk_lib_crypto_hash_block_blake2s_base_pt const blake2s_base, mk_lib_crypto_hash_block_blake2s_base_block_pt const block, mk_lang_types_sint_t const idx, mk_lib_crypto_hash_block_blake2s_base_digest_pt const digest) mk_lang_noexcept;


#if mk_lang_jumbo_have
#include "mk_lib_crypto_hash_block_blake2s_base.c"
#endif
#endif
