#undef mk_lib_crypto_hash_stream_blake2_inl_defd_s
#undef mk_lib_crypto_hash_stream_blake2_inl_defd_t
#undef mk_lib_crypto_hash_stream_blake2_inl_defd_ct
#undef mk_lib_crypto_hash_stream_blake2_inl_defd_pt
#undef mk_lib_crypto_hash_stream_blake2_inl_defd_pct

#undef mk_lib_crypto_hash_stream_blake2_inl_defd_init
#undef mk_lib_crypto_hash_stream_blake2_inl_defd_append_u8
#undef mk_lib_crypto_hash_stream_blake2_inl_defd_append
#undef mk_lib_crypto_hash_stream_blake2_inl_defd_finish

#undef mk_lib_crypto_hash_stream_blake2_inl_defd_base_block_len
#undef mk_lib_crypto_hash_stream_blake2_inl_defd_base_t
#undef mk_lib_crypto_hash_stream_blake2_inl_defd_base_block_t
#undef mk_lib_crypto_hash_stream_blake2_inl_defd_base_block_pct
#undef mk_lib_crypto_hash_stream_blake2_inl_defd_base_digest_pt

#undef mk_lib_crypto_hash_stream_blake2_inl_defd_base_init
#undef mk_lib_crypto_hash_stream_blake2_inl_defd_base_append_blocks
#undef mk_lib_crypto_hash_stream_blake2_inl_defd_base_pad_block
#undef mk_lib_crypto_hash_stream_blake2_inl_defd_base_finish
