include(`mk_lang_bui_inl.m')dnl



















`#'undef mk_lang_bui_inl_defd_name
`#'undef mk_lang_bui_inl_defd_base



`#'undef mk_lang_bui_inl_defd_str_style

`#'undef mk_lang_bui_inl_defd_str_style



`#'undef mk_lang_bui_inl_defd_inline

`#'undef mk_lang_bui_inl_defd_inline




`#'undef mk_lang_bui_inl_defd_flatten
`#'undef mk_lang_bui_inl_defd_forceinline

`#'undef mk_lang_bui_inl_defd_flatten
`#'undef mk_lang_bui_inl_defd_forceinline



`#'undef mk_lang_bui_inl_defd_base_name

`#'undef mk_lang_bui_inl_defd_base_t
`#'undef mk_lang_bui_inl_defd_base_ct
`#'undef mk_lang_bui_inl_defd_base_vt
`#'undef mk_lang_bui_inl_defd_base_cvt
`#'undef mk_lang_bui_inl_defd_base_pt
`#'undef mk_lang_bui_inl_defd_base_pct
`#'undef mk_lang_bui_inl_defd_base_pvt
`#'undef mk_lang_bui_inl_defd_base_pcvt
`#'undef mk_lang_bui_inl_defd_base_prt
`#'undef mk_lang_bui_inl_defd_base_prct
`#'undef mk_lang_bui_inl_defd_base_prvt
`#'undef mk_lang_bui_inl_defd_base_prcvt
`#'undef mk_lang_bui_inl_defd_base_lpt
`#'undef mk_lang_bui_inl_defd_base_lpct
`#'undef mk_lang_bui_inl_defd_base_lpvt
`#'undef mk_lang_bui_inl_defd_base_lpcvt
`#'undef mk_lang_bui_inl_defd_base_lprt
`#'undef mk_lang_bui_inl_defd_base_lprct
`#'undef mk_lang_bui_inl_defd_base_lprvt
`#'undef mk_lang_bui_inl_defd_base_lprcvt
`#'undef mk_lang_bui_inl_defd_base_npt
`#'undef mk_lang_bui_inl_defd_base_npct
`#'undef mk_lang_bui_inl_defd_base_npvt
`#'undef mk_lang_bui_inl_defd_base_npcvt
`#'undef mk_lang_bui_inl_defd_base_nprt
`#'undef mk_lang_bui_inl_defd_base_nprct
`#'undef mk_lang_bui_inl_defd_base_nprvt
`#'undef mk_lang_bui_inl_defd_base_nprcvt
`#'undef mk_lang_bui_inl_defd_base_cpt
`#'undef mk_lang_bui_inl_defd_base_vpt
`#'undef mk_lang_bui_inl_defd_base_cvpt
`#'undef mk_lang_bui_inl_defd_base_ppt
`#'undef mk_lang_bui_inl_defd_base_pcpt
`#'undef mk_lang_bui_inl_defd_base_pvpt
`#'undef mk_lang_bui_inl_defd_base_pcvpt
`#'undef mk_lang_bui_inl_defd_base_prpt
`#'undef mk_lang_bui_inl_defd_base_prcpt
`#'undef mk_lang_bui_inl_defd_base_prvpt
`#'undef mk_lang_bui_inl_defd_base_prcvpt
`#'undef mk_lang_bui_inl_defd_base_lppt
`#'undef mk_lang_bui_inl_defd_base_lpcpt
`#'undef mk_lang_bui_inl_defd_base_lpvpt
`#'undef mk_lang_bui_inl_defd_base_lpcvpt
`#'undef mk_lang_bui_inl_defd_base_lprpt
`#'undef mk_lang_bui_inl_defd_base_lprcpt
`#'undef mk_lang_bui_inl_defd_base_lprvpt
`#'undef mk_lang_bui_inl_defd_base_lprcvpt
`#'undef mk_lang_bui_inl_defd_base_nppt
`#'undef mk_lang_bui_inl_defd_base_npcpt
`#'undef mk_lang_bui_inl_defd_base_npvpt
`#'undef mk_lang_bui_inl_defd_base_npcvpt
`#'undef mk_lang_bui_inl_defd_base_nprpt
`#'undef mk_lang_bui_inl_defd_base_nprcpt
`#'undef mk_lang_bui_inl_defd_base_nprvpt
`#'undef mk_lang_bui_inl_defd_base_nprcvpt
`#'undef mk_lang_bui_inl_defd_base_cpct
`#'undef mk_lang_bui_inl_defd_base_vpct
`#'undef mk_lang_bui_inl_defd_base_cvpct
`#'undef mk_lang_bui_inl_defd_base_ppct
`#'undef mk_lang_bui_inl_defd_base_pcpct
`#'undef mk_lang_bui_inl_defd_base_pvpct
`#'undef mk_lang_bui_inl_defd_base_pcvpct
`#'undef mk_lang_bui_inl_defd_base_prpct
`#'undef mk_lang_bui_inl_defd_base_prcpct
`#'undef mk_lang_bui_inl_defd_base_prvpct
`#'undef mk_lang_bui_inl_defd_base_prcvpct
`#'undef mk_lang_bui_inl_defd_base_lppct
`#'undef mk_lang_bui_inl_defd_base_lpcpct
`#'undef mk_lang_bui_inl_defd_base_lpvpct
`#'undef mk_lang_bui_inl_defd_base_lpcvpct
`#'undef mk_lang_bui_inl_defd_base_lprpct
`#'undef mk_lang_bui_inl_defd_base_lprcpct
`#'undef mk_lang_bui_inl_defd_base_lprvpct
`#'undef mk_lang_bui_inl_defd_base_lprcvpct
`#'undef mk_lang_bui_inl_defd_base_nppct
`#'undef mk_lang_bui_inl_defd_base_npcpct
`#'undef mk_lang_bui_inl_defd_base_npvpct
`#'undef mk_lang_bui_inl_defd_base_npcvpct
`#'undef mk_lang_bui_inl_defd_base_nprpct
`#'undef mk_lang_bui_inl_defd_base_nprcpct
`#'undef mk_lang_bui_inl_defd_base_nprvpct
`#'undef mk_lang_bui_inl_defd_base_nprcvpct
`#'undef mk_lang_bui_inl_defd_base_cppt
`#'undef mk_lang_bui_inl_defd_base_vppt
`#'undef mk_lang_bui_inl_defd_base_cvppt
`#'undef mk_lang_bui_inl_defd_base_pppt
`#'undef mk_lang_bui_inl_defd_base_pcppt
`#'undef mk_lang_bui_inl_defd_base_pvppt
`#'undef mk_lang_bui_inl_defd_base_pcvppt
`#'undef mk_lang_bui_inl_defd_base_prppt
`#'undef mk_lang_bui_inl_defd_base_prcppt
`#'undef mk_lang_bui_inl_defd_base_prvppt
`#'undef mk_lang_bui_inl_defd_base_prcvppt
`#'undef mk_lang_bui_inl_defd_base_lpppt
`#'undef mk_lang_bui_inl_defd_base_lpcppt
`#'undef mk_lang_bui_inl_defd_base_lpvppt
`#'undef mk_lang_bui_inl_defd_base_lpcvppt
`#'undef mk_lang_bui_inl_defd_base_lprppt
`#'undef mk_lang_bui_inl_defd_base_lprcppt
`#'undef mk_lang_bui_inl_defd_base_lprvppt
`#'undef mk_lang_bui_inl_defd_base_lprcvppt
`#'undef mk_lang_bui_inl_defd_base_npppt
`#'undef mk_lang_bui_inl_defd_base_npcppt
`#'undef mk_lang_bui_inl_defd_base_npvppt
`#'undef mk_lang_bui_inl_defd_base_npcvppt
`#'undef mk_lang_bui_inl_defd_base_nprppt
`#'undef mk_lang_bui_inl_defd_base_nprcppt
`#'undef mk_lang_bui_inl_defd_base_nprvppt
`#'undef mk_lang_bui_inl_defd_base_nprcvppt


`#'undef mk_lang_bui_inl_defd_t
`#'undef mk_lang_bui_inl_defd_ct
`#'undef mk_lang_bui_inl_defd_vt
`#'undef mk_lang_bui_inl_defd_cvt
`#'undef mk_lang_bui_inl_defd_pt
`#'undef mk_lang_bui_inl_defd_pct
`#'undef mk_lang_bui_inl_defd_pvt
`#'undef mk_lang_bui_inl_defd_pcvt
`#'undef mk_lang_bui_inl_defd_prt
`#'undef mk_lang_bui_inl_defd_prct
`#'undef mk_lang_bui_inl_defd_prvt
`#'undef mk_lang_bui_inl_defd_prcvt
`#'undef mk_lang_bui_inl_defd_lpt
`#'undef mk_lang_bui_inl_defd_lpct
`#'undef mk_lang_bui_inl_defd_lpvt
`#'undef mk_lang_bui_inl_defd_lpcvt
`#'undef mk_lang_bui_inl_defd_lprt
`#'undef mk_lang_bui_inl_defd_lprct
`#'undef mk_lang_bui_inl_defd_lprvt
`#'undef mk_lang_bui_inl_defd_lprcvt
`#'undef mk_lang_bui_inl_defd_npt
`#'undef mk_lang_bui_inl_defd_npct
`#'undef mk_lang_bui_inl_defd_npvt
`#'undef mk_lang_bui_inl_defd_npcvt
`#'undef mk_lang_bui_inl_defd_nprt
`#'undef mk_lang_bui_inl_defd_nprct
`#'undef mk_lang_bui_inl_defd_nprvt
`#'undef mk_lang_bui_inl_defd_nprcvt
`#'undef mk_lang_bui_inl_defd_cpt
`#'undef mk_lang_bui_inl_defd_vpt
`#'undef mk_lang_bui_inl_defd_cvpt
`#'undef mk_lang_bui_inl_defd_ppt
`#'undef mk_lang_bui_inl_defd_pcpt
`#'undef mk_lang_bui_inl_defd_pvpt
`#'undef mk_lang_bui_inl_defd_pcvpt
`#'undef mk_lang_bui_inl_defd_prpt
`#'undef mk_lang_bui_inl_defd_prcpt
`#'undef mk_lang_bui_inl_defd_prvpt
`#'undef mk_lang_bui_inl_defd_prcvpt
`#'undef mk_lang_bui_inl_defd_lppt
`#'undef mk_lang_bui_inl_defd_lpcpt
`#'undef mk_lang_bui_inl_defd_lpvpt
`#'undef mk_lang_bui_inl_defd_lpcvpt
`#'undef mk_lang_bui_inl_defd_lprpt
`#'undef mk_lang_bui_inl_defd_lprcpt
`#'undef mk_lang_bui_inl_defd_lprvpt
`#'undef mk_lang_bui_inl_defd_lprcvpt
`#'undef mk_lang_bui_inl_defd_nppt
`#'undef mk_lang_bui_inl_defd_npcpt
`#'undef mk_lang_bui_inl_defd_npvpt
`#'undef mk_lang_bui_inl_defd_npcvpt
`#'undef mk_lang_bui_inl_defd_nprpt
`#'undef mk_lang_bui_inl_defd_nprcpt
`#'undef mk_lang_bui_inl_defd_nprvpt
`#'undef mk_lang_bui_inl_defd_nprcvpt
`#'undef mk_lang_bui_inl_defd_cpct
`#'undef mk_lang_bui_inl_defd_vpct
`#'undef mk_lang_bui_inl_defd_cvpct
`#'undef mk_lang_bui_inl_defd_ppct
`#'undef mk_lang_bui_inl_defd_pcpct
`#'undef mk_lang_bui_inl_defd_pvpct
`#'undef mk_lang_bui_inl_defd_pcvpct
`#'undef mk_lang_bui_inl_defd_prpct
`#'undef mk_lang_bui_inl_defd_prcpct
`#'undef mk_lang_bui_inl_defd_prvpct
`#'undef mk_lang_bui_inl_defd_prcvpct
`#'undef mk_lang_bui_inl_defd_lppct
`#'undef mk_lang_bui_inl_defd_lpcpct
`#'undef mk_lang_bui_inl_defd_lpvpct
`#'undef mk_lang_bui_inl_defd_lpcvpct
`#'undef mk_lang_bui_inl_defd_lprpct
`#'undef mk_lang_bui_inl_defd_lprcpct
`#'undef mk_lang_bui_inl_defd_lprvpct
`#'undef mk_lang_bui_inl_defd_lprcvpct
`#'undef mk_lang_bui_inl_defd_nppct
`#'undef mk_lang_bui_inl_defd_npcpct
`#'undef mk_lang_bui_inl_defd_npvpct
`#'undef mk_lang_bui_inl_defd_npcvpct
`#'undef mk_lang_bui_inl_defd_nprpct
`#'undef mk_lang_bui_inl_defd_nprcpct
`#'undef mk_lang_bui_inl_defd_nprvpct
`#'undef mk_lang_bui_inl_defd_nprcvpct
`#'undef mk_lang_bui_inl_defd_cppt
`#'undef mk_lang_bui_inl_defd_vppt
`#'undef mk_lang_bui_inl_defd_cvppt
`#'undef mk_lang_bui_inl_defd_pppt
`#'undef mk_lang_bui_inl_defd_pcppt
`#'undef mk_lang_bui_inl_defd_pvppt
`#'undef mk_lang_bui_inl_defd_pcvppt
`#'undef mk_lang_bui_inl_defd_prppt
`#'undef mk_lang_bui_inl_defd_prcppt
`#'undef mk_lang_bui_inl_defd_prvppt
`#'undef mk_lang_bui_inl_defd_prcvppt
`#'undef mk_lang_bui_inl_defd_lpppt
`#'undef mk_lang_bui_inl_defd_lpcppt
`#'undef mk_lang_bui_inl_defd_lpvppt
`#'undef mk_lang_bui_inl_defd_lpcvppt
`#'undef mk_lang_bui_inl_defd_lprppt
`#'undef mk_lang_bui_inl_defd_lprcppt
`#'undef mk_lang_bui_inl_defd_lprvppt
`#'undef mk_lang_bui_inl_defd_lprcvppt
`#'undef mk_lang_bui_inl_defd_npppt
`#'undef mk_lang_bui_inl_defd_npcppt
`#'undef mk_lang_bui_inl_defd_npvppt
`#'undef mk_lang_bui_inl_defd_npcvppt
`#'undef mk_lang_bui_inl_defd_nprppt
`#'undef mk_lang_bui_inl_defd_nprcppt
`#'undef mk_lang_bui_inl_defd_nprvppt
`#'undef mk_lang_bui_inl_defd_nprcvppt

`#'undef mk_lang_bui_inl_defd_size_bytes_d
`#'undef mk_lang_bui_inl_defd_size_bytes_e
`#'undef mk_lang_bui_inl_defd_size_bytes_t
`#'undef mk_lang_bui_inl_defd_size_bytes_v

`#'undef mk_lang_bui_inl_defd_size_bits_d
`#'undef mk_lang_bui_inl_defd_size_bits_e
`#'undef mk_lang_bui_inl_defd_size_bits_t
`#'undef mk_lang_bui_inl_defd_size_bits_v

`#'undef mk_lang_bui_inl_defd_strlen_dec_log

`#'undef mk_lang_bui_inl_defd_strlen_bin_d
`#'undef mk_lang_bui_inl_defd_strlen_bin_e
`#'undef mk_lang_bui_inl_defd_strlen_bin_t
`#'undef mk_lang_bui_inl_defd_strlen_bin_v

`#'undef mk_lang_bui_inl_defd_strlen_oct_d
`#'undef mk_lang_bui_inl_defd_strlen_oct_e
`#'undef mk_lang_bui_inl_defd_strlen_oct_t
`#'undef mk_lang_bui_inl_defd_strlen_oct_v

`#'undef mk_lang_bui_inl_defd_strlen_dec_d
`#'undef mk_lang_bui_inl_defd_strlen_dec_e
`#'undef mk_lang_bui_inl_defd_strlen_dec_t
`#'undef mk_lang_bui_inl_defd_strlen_dec_v

`#'undef mk_lang_bui_inl_defd_strlen_hex_d
`#'undef mk_lang_bui_inl_defd_strlen_hex_e
`#'undef mk_lang_bui_inl_defd_strlen_hex_t
`#'undef mk_lang_bui_inl_defd_strlen_hex_v

`#'undef mk_lang_bui_inl_defd_symbols_bin_a
`#'undef mk_lang_bui_inl_defd_symbols_bin_b
`#'undef mk_lang_bui_inl_defd_symbols_bin_c
`#'undef mk_lang_bui_inl_defd_symbols_bin_d
`#'undef mk_lang_bui_inl_defd_symbols_oct_a
`#'undef mk_lang_bui_inl_defd_symbols_oct_b
`#'undef mk_lang_bui_inl_defd_symbols_oct_c
`#'undef mk_lang_bui_inl_defd_symbols_oct_d
`#'undef mk_lang_bui_inl_defd_symbols_dec_a
`#'undef mk_lang_bui_inl_defd_symbols_dec_b
`#'undef mk_lang_bui_inl_defd_symbols_dec_c
`#'undef mk_lang_bui_inl_defd_symbols_dec_d
`#'undef mk_lang_bui_inl_defd_symbols_hex_a
`#'undef mk_lang_bui_inl_defd_symbols_hex_b
`#'undef mk_lang_bui_inl_defd_symbols_hex_c
`#'undef mk_lang_bui_inl_defd_symbols_hex_C
`#'undef mk_lang_bui_inl_defd_symbols_hex_d
`#'undef mk_lang_bui_inl_defd_symbols_hex_D
`#'undef mk_lang_bui_inl_defd_symbols_bin_e
`#'undef mk_lang_bui_inl_defd_symbols_bin_f
`#'undef mk_lang_bui_inl_defd_symbols_hex_e
`#'undef mk_lang_bui_inl_defd_symbols_hex_f

`#'undef mk_lang_bui_inl_defd_pr_from_str_dec_border_base_impl
`#'undef mk_lang_bui_inl_defd_pr_from_str_dec_border_value_impl
`#'undef mk_lang_bui_inl_defd_pr_from_str_dec_border_digit_impl
`#'undef mk_lang_bui_inl_defd_pr_from_str_dec_border_base_val
`#'undef mk_lang_bui_inl_defd_pr_from_str_dec_border_value_val
`#'undef mk_lang_bui_inl_defd_pr_from_str_dec_border_digit_val
`#'undef mk_lang_bui_inl_defd_pr_from_str_dec_border_base
`#'undef mk_lang_bui_inl_defd_pr_from_str_dec_border_value
`#'undef mk_lang_bui_inl_defd_pr_from_str_dec_border_digit

`#'undef mk_lang_bui_inl_defd_pr_from_base
mm_per_bi(`#undef mk_lang_bui_inl_defd_pr_from_bi_$1')
`#'undef mk_lang_bui_inl_defd_pr_to_base
mm_per_bi(`#undef mk_lang_bui_inl_defd_pr_to_bi_$1')
mm_per_bui(`#undef mk_lang_bui_inl_defd_pr_from_buis_$1_le')
mm_per_bui(`#undef mk_lang_bui_inl_defd_pr_to_buis_$1_le')
mm_per_bui(`#undef mk_lang_bui_inl_defd_pr_from_buis_$1_be')
mm_per_bui(`#undef mk_lang_bui_inl_defd_pr_to_buis_$1_be')
`#'undef mk_lang_bui_inl_defd_pr_assign
`#'undef mk_lang_bui_inl_defd_pr_set_zero
`#'undef mk_lang_bui_inl_defd_pr_set_max
`#'undef mk_lang_bui_inl_defd_pr_set_one
`#'undef mk_lang_bui_inl_defd_pr_set_two
`#'undef mk_lang_bui_inl_defd_pr_set_bit
`#'undef mk_lang_bui_inl_defd_pr_set_mask
`#'undef mk_lang_bui_inl_defd_pr_count_leading_zeros
`#'undef mk_lang_bui_inl_defd_pr_count_leading_ones
`#'undef mk_lang_bui_inl_defd_pr_count_trailing_zeros
`#'undef mk_lang_bui_inl_defd_pr_count_trailing_ones
`#'undef mk_lang_bui_inl_defd_pr_count_ones
`#'undef mk_lang_bui_inl_defd_pr_count_zeros
`#'undef mk_lang_bui_inl_defd_pr_has_lsb
`#'undef mk_lang_bui_inl_defd_pr_is_zero
`#'undef mk_lang_bui_inl_defd_pr_is_one
`#'undef mk_lang_bui_inl_defd_pr_is_two
`#'undef mk_lang_bui_inl_defd_pr_is_max
`#'undef mk_lang_bui_inl_defd_pr_is_bit
`#'undef mk_lang_bui_inl_defd_pr_eq
`#'undef mk_lang_bui_inl_defd_pr_ne
`#'undef mk_lang_bui_inl_defd_pr_lt
`#'undef mk_lang_bui_inl_defd_pr_le
`#'undef mk_lang_bui_inl_defd_pr_gt
`#'undef mk_lang_bui_inl_defd_pr_ge
`#'undef mk_lang_bui_inl_defd_pr_cmp
`#'undef mk_lang_bui_inl_defd_pr_inc2
`#'undef mk_lang_bui_inl_defd_pr_dec2
`#'undef mk_lang_bui_inl_defd_pr_inc1
`#'undef mk_lang_bui_inl_defd_pr_dec1
`#'undef mk_lang_bui_inl_defd_pr_not2
`#'undef mk_lang_bui_inl_defd_pr_or3
`#'undef mk_lang_bui_inl_defd_pr_and3
`#'undef mk_lang_bui_inl_defd_pr_xor3
`#'undef mk_lang_bui_inl_defd_pr_not1
`#'undef mk_lang_bui_inl_defd_pr_or2
`#'undef mk_lang_bui_inl_defd_pr_and2
`#'undef mk_lang_bui_inl_defd_pr_xor2
`#'undef mk_lang_bui_inl_defd_pr_shl3
`#'undef mk_lang_bui_inl_defd_pr_shr3
`#'undef mk_lang_bui_inl_defd_pr_rotl3
`#'undef mk_lang_bui_inl_defd_pr_rotr3
`#'undef mk_lang_bui_inl_defd_pr_shl2
`#'undef mk_lang_bui_inl_defd_pr_shr2
`#'undef mk_lang_bui_inl_defd_pr_rotl2
`#'undef mk_lang_bui_inl_defd_pr_rotr2
`#'undef mk_lang_bui_inl_defd_pr_would_overflow_add_cc
`#'undef mk_lang_bui_inl_defd_pr_would_overflow_add_cs
`#'undef mk_lang_bui_inl_defd_pr_would_overflow_add_cp
`#'undef mk_lang_bui_inl_defd_pr_would_overflow_sub_cc
`#'undef mk_lang_bui_inl_defd_pr_would_overflow_sub_cs
`#'undef mk_lang_bui_inl_defd_pr_would_overflow_sub_cp
`#'undef mk_lang_bui_inl_defd_pr_would_overflow_mul
`#'undef mk_lang_bui_inl_defd_pr_would_overflow_div
`#'undef mk_lang_bui_inl_defd_pr_would_overflow_mod
`#'undef mk_lang_bui_inl_defd_pr_add3_wrap_cid_cod
`#'undef mk_lang_bui_inl_defd_pr_add3_wrap_cid_coe
`#'undef mk_lang_bui_inl_defd_pr_add3_wrap_cie_cod
`#'undef mk_lang_bui_inl_defd_pr_add3_wrap_cie_coe
`#'undef mk_lang_bui_inl_defd_pr_add2_wrap_cid_cod
`#'undef mk_lang_bui_inl_defd_pr_add2_wrap_cid_coe
`#'undef mk_lang_bui_inl_defd_pr_add2_wrap_cie_cod
`#'undef mk_lang_bui_inl_defd_pr_add2_wrap_cie_coe
`#'undef mk_lang_bui_inl_defd_pr_sub3_wrap_cid_cod
`#'undef mk_lang_bui_inl_defd_pr_sub3_wrap_cid_coe
`#'undef mk_lang_bui_inl_defd_pr_sub3_wrap_cie_cod
`#'undef mk_lang_bui_inl_defd_pr_sub3_wrap_cie_coe
`#'undef mk_lang_bui_inl_defd_pr_sub2_wrap_cid_cod
`#'undef mk_lang_bui_inl_defd_pr_sub2_wrap_cid_coe
`#'undef mk_lang_bui_inl_defd_pr_sub2_wrap_cie_cod
`#'undef mk_lang_bui_inl_defd_pr_sub2_wrap_cie_coe
`#'undef mk_lang_bui_inl_defd_pr_mul3_wrap_lo
`#'undef mk_lang_bui_inl_defd_pr_mul3_wrap_hi
`#'undef mk_lang_bui_inl_defd_pr_mul4_wrap_wi
`#'undef mk_lang_bui_inl_defd_pr_mul2_wrap_lo
`#'undef mk_lang_bui_inl_defd_pr_mul2_wrap_hi
`#'undef mk_lang_bui_inl_defd_pr_mul2_wrap_wi
`#'undef mk_lang_bui_inl_defd_pr_div3_wrap
`#'undef mk_lang_bui_inl_defd_pr_mod3_wrap
`#'undef mk_lang_bui_inl_defd_pr_divmod4_wrap
`#'undef mk_lang_bui_inl_defd_pr_div2_wrap
`#'undef mk_lang_bui_inl_defd_pr_mod2_wrap
`#'undef mk_lang_bui_inl_defd_pr_divmod2_wrap
`#'undef mk_lang_bui_inl_defd_pr_to_str_bin_n
`#'undef mk_lang_bui_inl_defd_pr_to_str_bin_w
`#'undef mk_lang_bui_inl_defd_pr_from_str_bin_n
`#'undef mk_lang_bui_inl_defd_pr_from_str_bin_w
`#'undef mk_lang_bui_inl_defd_pr_to_str_oct_n
`#'undef mk_lang_bui_inl_defd_pr_to_str_oct_w
`#'undef mk_lang_bui_inl_defd_pr_from_str_oct_n
`#'undef mk_lang_bui_inl_defd_pr_from_str_oct_w
`#'undef mk_lang_bui_inl_defd_pr_to_str_dec_n
`#'undef mk_lang_bui_inl_defd_pr_to_str_dec_w
`#'undef mk_lang_bui_inl_defd_pr_from_str_dec_n
`#'undef mk_lang_bui_inl_defd_pr_from_str_dec_w
`#'undef mk_lang_bui_inl_defd_pr_to_str_hex_n
`#'undef mk_lang_bui_inl_defd_pr_to_str_hex_w
`#'undef mk_lang_bui_inl_defd_pr_from_str_hex_n
`#'undef mk_lang_bui_inl_defd_pr_from_str_hex_w
`#'undef mk_lang_bui_inl_defd_pr_from_str_hex_many_n
`#'undef mk_lang_bui_inl_defd_pr_from_str_hex_many_w
`#'undef mk_lang_bui_inl_defd_pr_to_str_binf_n
`#'undef mk_lang_bui_inl_defd_pr_to_str_binf_w
`#'undef mk_lang_bui_inl_defd_pr_to_str_hexf_n
`#'undef mk_lang_bui_inl_defd_pr_to_str_hexf_w
`#'undef mk_lang_bui_inl_defd_pr_to_str_hexf_many_n
`#'undef mk_lang_bui_inl_defd_pr_to_str_hexf_many_w

`#'undef mk_lang_bui_inl_defd_from_base
mm_per_bi(`#undef mk_lang_bui_inl_defd_from_bi_$1')
`#'undef mk_lang_bui_inl_defd_to_base
mm_per_bi(`#undef mk_lang_bui_inl_defd_to_bi_$1')
mm_per_bui(`#undef mk_lang_bui_inl_defd_from_buis_$1_le')
mm_per_bui(`#undef mk_lang_bui_inl_defd_to_buis_$1_le')
mm_per_bui(`#undef mk_lang_bui_inl_defd_from_buis_$1_be')
mm_per_bui(`#undef mk_lang_bui_inl_defd_to_buis_$1_be')
`#'undef mk_lang_bui_inl_defd_assign
`#'undef mk_lang_bui_inl_defd_set_zero
`#'undef mk_lang_bui_inl_defd_set_max
`#'undef mk_lang_bui_inl_defd_set_one
`#'undef mk_lang_bui_inl_defd_set_two
`#'undef mk_lang_bui_inl_defd_set_bit
`#'undef mk_lang_bui_inl_defd_set_mask
`#'undef mk_lang_bui_inl_defd_count_leading_zeros
`#'undef mk_lang_bui_inl_defd_count_leading_ones
`#'undef mk_lang_bui_inl_defd_count_trailing_zeros
`#'undef mk_lang_bui_inl_defd_count_trailing_ones
`#'undef mk_lang_bui_inl_defd_count_ones
`#'undef mk_lang_bui_inl_defd_count_zeros
`#'undef mk_lang_bui_inl_defd_has_lsb
`#'undef mk_lang_bui_inl_defd_is_zero
`#'undef mk_lang_bui_inl_defd_is_one
`#'undef mk_lang_bui_inl_defd_is_two
`#'undef mk_lang_bui_inl_defd_is_max
`#'undef mk_lang_bui_inl_defd_is_bit
`#'undef mk_lang_bui_inl_defd_eq
`#'undef mk_lang_bui_inl_defd_ne
`#'undef mk_lang_bui_inl_defd_lt
`#'undef mk_lang_bui_inl_defd_le
`#'undef mk_lang_bui_inl_defd_gt
`#'undef mk_lang_bui_inl_defd_ge
`#'undef mk_lang_bui_inl_defd_cmp
`#'undef mk_lang_bui_inl_defd_inc2
`#'undef mk_lang_bui_inl_defd_dec2
`#'undef mk_lang_bui_inl_defd_inc1
`#'undef mk_lang_bui_inl_defd_dec1
`#'undef mk_lang_bui_inl_defd_not2
`#'undef mk_lang_bui_inl_defd_or3
`#'undef mk_lang_bui_inl_defd_and3
`#'undef mk_lang_bui_inl_defd_xor3
`#'undef mk_lang_bui_inl_defd_not1
`#'undef mk_lang_bui_inl_defd_or2
`#'undef mk_lang_bui_inl_defd_and2
`#'undef mk_lang_bui_inl_defd_xor2
`#'undef mk_lang_bui_inl_defd_shl3
`#'undef mk_lang_bui_inl_defd_shr3
`#'undef mk_lang_bui_inl_defd_rotl3
`#'undef mk_lang_bui_inl_defd_rotr3
`#'undef mk_lang_bui_inl_defd_shl2
`#'undef mk_lang_bui_inl_defd_shr2
`#'undef mk_lang_bui_inl_defd_rotl2
`#'undef mk_lang_bui_inl_defd_rotr2
`#'undef mk_lang_bui_inl_defd_would_overflow_add_cc
`#'undef mk_lang_bui_inl_defd_would_overflow_add_cs
`#'undef mk_lang_bui_inl_defd_would_overflow_add_cp
`#'undef mk_lang_bui_inl_defd_would_overflow_sub_cc
`#'undef mk_lang_bui_inl_defd_would_overflow_sub_cs
`#'undef mk_lang_bui_inl_defd_would_overflow_sub_cp
`#'undef mk_lang_bui_inl_defd_would_overflow_mul
`#'undef mk_lang_bui_inl_defd_would_overflow_div
`#'undef mk_lang_bui_inl_defd_would_overflow_mod
`#'undef mk_lang_bui_inl_defd_add3_wrap_cid_cod
`#'undef mk_lang_bui_inl_defd_add3_wrap_cid_coe
`#'undef mk_lang_bui_inl_defd_add3_wrap_cie_cod
`#'undef mk_lang_bui_inl_defd_add3_wrap_cie_coe
`#'undef mk_lang_bui_inl_defd_add2_wrap_cid_cod
`#'undef mk_lang_bui_inl_defd_add2_wrap_cid_coe
`#'undef mk_lang_bui_inl_defd_add2_wrap_cie_cod
`#'undef mk_lang_bui_inl_defd_add2_wrap_cie_coe
`#'undef mk_lang_bui_inl_defd_sub3_wrap_cid_cod
`#'undef mk_lang_bui_inl_defd_sub3_wrap_cid_coe
`#'undef mk_lang_bui_inl_defd_sub3_wrap_cie_cod
`#'undef mk_lang_bui_inl_defd_sub3_wrap_cie_coe
`#'undef mk_lang_bui_inl_defd_sub2_wrap_cid_cod
`#'undef mk_lang_bui_inl_defd_sub2_wrap_cid_coe
`#'undef mk_lang_bui_inl_defd_sub2_wrap_cie_cod
`#'undef mk_lang_bui_inl_defd_sub2_wrap_cie_coe
`#'undef mk_lang_bui_inl_defd_mul3_wrap_lo
`#'undef mk_lang_bui_inl_defd_mul3_wrap_hi
`#'undef mk_lang_bui_inl_defd_mul4_wrap_wi
`#'undef mk_lang_bui_inl_defd_mul2_wrap_lo
`#'undef mk_lang_bui_inl_defd_mul2_wrap_hi
`#'undef mk_lang_bui_inl_defd_mul2_wrap_wi
`#'undef mk_lang_bui_inl_defd_div3_wrap
`#'undef mk_lang_bui_inl_defd_mod3_wrap
`#'undef mk_lang_bui_inl_defd_divmod4_wrap
`#'undef mk_lang_bui_inl_defd_div2_wrap
`#'undef mk_lang_bui_inl_defd_mod2_wrap
`#'undef mk_lang_bui_inl_defd_divmod2_wrap
`#'undef mk_lang_bui_inl_defd_to_str_bin_n
`#'undef mk_lang_bui_inl_defd_to_str_bin_w
`#'undef mk_lang_bui_inl_defd_from_str_bin_n
`#'undef mk_lang_bui_inl_defd_from_str_bin_w
`#'undef mk_lang_bui_inl_defd_to_str_oct_n
`#'undef mk_lang_bui_inl_defd_to_str_oct_w
`#'undef mk_lang_bui_inl_defd_from_str_oct_n
`#'undef mk_lang_bui_inl_defd_from_str_oct_w
`#'undef mk_lang_bui_inl_defd_to_str_dec_n
`#'undef mk_lang_bui_inl_defd_to_str_dec_w
`#'undef mk_lang_bui_inl_defd_from_str_dec_n
`#'undef mk_lang_bui_inl_defd_from_str_dec_w
`#'undef mk_lang_bui_inl_defd_to_str_hex_n
`#'undef mk_lang_bui_inl_defd_to_str_hex_w
`#'undef mk_lang_bui_inl_defd_from_str_hex_n
`#'undef mk_lang_bui_inl_defd_from_str_hex_w
`#'undef mk_lang_bui_inl_defd_from_str_hex_many_n
`#'undef mk_lang_bui_inl_defd_from_str_hex_many_w
`#'undef mk_lang_bui_inl_defd_to_str_binf_n
`#'undef mk_lang_bui_inl_defd_to_str_binf_w
`#'undef mk_lang_bui_inl_defd_to_str_hexf_n
`#'undef mk_lang_bui_inl_defd_to_str_hexf_w
`#'undef mk_lang_bui_inl_defd_to_str_hexf_many_n
`#'undef mk_lang_bui_inl_defd_to_str_hexf_many_w
