










#undef mk_lib_crypto_alg_twofish_base_inl_defd_name
#undef mk_lib_crypto_alg_twofish_base_inl_defd_keylen


#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_len_m
#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_len_e
#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_len_v

#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_len_m
#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_len_e
#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_len_v

#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_len_m
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_len_e
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_len_v

#undef mk_lib_crypto_alg_twofish_base_inl_defd_nr
#undef mk_lib_crypto_alg_twofish_base_inl_defd_rks_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_rks_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_sbox_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_sbox_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_sboxs_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_sboxs_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_rks_sboxs_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_rks_sboxs_t

#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_data_u
#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_data_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_ct
#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_pt
#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_pct

#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_data_u
#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_data_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_ct
#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_pt
#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_pct

#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_data_u
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_data_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_ct
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_pt
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_pct

#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_encrypt
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_decrypt
#undef mk_lib_crypto_alg_twofish_base_inl_defd_expand_enc
#undef mk_lib_crypto_alg_twofish_base_inl_defd_expand_dec
#undef mk_lib_crypto_alg_twofish_base_inl_defd_encrypt
#undef mk_lib_crypto_alg_twofish_base_inl_defd_decrypt

#undef mk_lib_crypto_alg_twofish_base_inl_defd_uint328_data_u
#undef mk_lib_crypto_alg_twofish_base_inl_defd_uint328_data_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_uint328_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_uint328_t

#undef mk_lib_crypto_alg_twofish_base_inl_defd_table_q_data_u
#undef mk_lib_crypto_alg_twofish_base_inl_defd_table_q_data_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_table_q_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_table_q_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_q_data_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_q_data_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_q_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_q_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_q

#undef mk_lib_crypto_alg_twofish_base_inl_defd_table_mdsq_data_u
#undef mk_lib_crypto_alg_twofish_base_inl_defd_table_mdsq_data_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_table_mdsq_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_table_mdsq_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_mdsq_data_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_mdsq_data_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_mdsq_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_mdsq_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_mdsq

#undef mk_lib_crypto_alg_twofish_base_inl_defd_table_rs_data_u
#undef mk_lib_crypto_alg_twofish_base_inl_defd_table_rs_data_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_table_rs_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_table_rs_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_rs_data_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_rs_data_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_rs_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_rs_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_rs

#undef mk_lib_crypto_alg_twofish_base_inl_defd_rnd_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_rnd_enc_a
#undef mk_lib_crypto_alg_twofish_base_inl_defd_rnd_enc_b
#undef mk_lib_crypto_alg_twofish_base_inl_defd_rnd_dec_a
#undef mk_lib_crypto_alg_twofish_base_inl_defd_rnd_dec_b
#undef mk_lib_crypto_alg_twofish_base_inl_defd_one_enc
#undef mk_lib_crypto_alg_twofish_base_inl_defd_one_dec
#undef mk_lib_crypto_alg_twofish_base_inl_defd_expand_128
#undef mk_lib_crypto_alg_twofish_base_inl_defd_expand_192
#undef mk_lib_crypto_alg_twofish_base_inl_defd_expand_256
#undef mk_lib_crypto_alg_twofish_base_inl_defd_expand
