









#undef mk_lib_crypto_mac_hmac_inl_defd_name


#undef mk_lib_crypto_mac_hmac_inl_defd_base_block_prefix

#undef mk_lib_crypto_mac_hmac_inl_defd_base_block_len_d
#undef mk_lib_crypto_mac_hmac_inl_defd_base_block_len_v

#undef mk_lib_crypto_mac_hmac_inl_defd_base_block_t
#undef mk_lib_crypto_mac_hmac_inl_defd_base_block_ct
#undef mk_lib_crypto_mac_hmac_inl_defd_base_block_pt
#undef mk_lib_crypto_mac_hmac_inl_defd_base_block_pct


#undef mk_lib_crypto_mac_hmac_inl_defd_base_stream_prefix

#undef mk_lib_crypto_mac_hmac_inl_defd_base_digest_len_v

#undef mk_lib_crypto_mac_hmac_inl_defd_base_digest_t
#undef mk_lib_crypto_mac_hmac_inl_defd_base_digest_ct
#undef mk_lib_crypto_mac_hmac_inl_defd_base_digest_pt
#undef mk_lib_crypto_mac_hmac_inl_defd_base_digest_pct

#undef mk_lib_crypto_mac_hmac_inl_defd_base_t
#undef mk_lib_crypto_mac_hmac_inl_defd_base_ct
#undef mk_lib_crypto_mac_hmac_inl_defd_base_pt
#undef mk_lib_crypto_mac_hmac_inl_defd_base_pct

#undef mk_lib_crypto_mac_hmac_inl_defd_base_init
#undef mk_lib_crypto_mac_hmac_inl_defd_base_append_u8s
#undef mk_lib_crypto_mac_hmac_inl_defd_base_finish


#undef mk_lib_crypto_mac_hmac_inl_defd_prefix

#undef mk_lib_crypto_mac_hmac_inl_defd_digest

#undef mk_lib_crypto_mac_hmac_inl_defd_digest_len_e
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_len_t
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_len_v

#undef mk_lib_crypto_mac_hmac_inl_defd_digest_s
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_t
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_ct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_vt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_cvt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_pt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_pct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_pvt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_pcvt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_prt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_prct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_prvt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_prcvt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lpvt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lpcvt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lprt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lprct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lprvt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lprcvt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_npt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_npct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_npvt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_npcvt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_nprt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_nprct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_nprvt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_nprcvt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_cpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_vpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_cvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_ppt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_pcpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_pvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_pcvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_prpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_prcpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_prvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_prcvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lppt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lpcpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lpvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lpcvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lprpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lprcpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lprvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lprcvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_nppt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_npcpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_npvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_npcvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_nprpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_nprcpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_nprvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_nprcvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_cpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_vpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_cvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_ppct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_pcpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_pvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_pcvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_prpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_prcpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_prvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_prcvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lppct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lpcpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lpvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lpcvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lprpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lprcpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lprvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_lprcvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_nppct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_npcpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_npvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_npcvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_nprpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_nprcpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_nprvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_digest_nprcvpct

#undef mk_lib_crypto_mac_hmac_inl_defd
#undef mk_lib_crypto_mac_hmac_inl_defd_s
#undef mk_lib_crypto_mac_hmac_inl_defd_t
#undef mk_lib_crypto_mac_hmac_inl_defd_ct
#undef mk_lib_crypto_mac_hmac_inl_defd_vt
#undef mk_lib_crypto_mac_hmac_inl_defd_cvt
#undef mk_lib_crypto_mac_hmac_inl_defd_pt
#undef mk_lib_crypto_mac_hmac_inl_defd_pct
#undef mk_lib_crypto_mac_hmac_inl_defd_pvt
#undef mk_lib_crypto_mac_hmac_inl_defd_pcvt
#undef mk_lib_crypto_mac_hmac_inl_defd_prt
#undef mk_lib_crypto_mac_hmac_inl_defd_prct
#undef mk_lib_crypto_mac_hmac_inl_defd_prvt
#undef mk_lib_crypto_mac_hmac_inl_defd_prcvt
#undef mk_lib_crypto_mac_hmac_inl_defd_lpt
#undef mk_lib_crypto_mac_hmac_inl_defd_lpct
#undef mk_lib_crypto_mac_hmac_inl_defd_lpvt
#undef mk_lib_crypto_mac_hmac_inl_defd_lpcvt
#undef mk_lib_crypto_mac_hmac_inl_defd_lprt
#undef mk_lib_crypto_mac_hmac_inl_defd_lprct
#undef mk_lib_crypto_mac_hmac_inl_defd_lprvt
#undef mk_lib_crypto_mac_hmac_inl_defd_lprcvt
#undef mk_lib_crypto_mac_hmac_inl_defd_npt
#undef mk_lib_crypto_mac_hmac_inl_defd_npct
#undef mk_lib_crypto_mac_hmac_inl_defd_npvt
#undef mk_lib_crypto_mac_hmac_inl_defd_npcvt
#undef mk_lib_crypto_mac_hmac_inl_defd_nprt
#undef mk_lib_crypto_mac_hmac_inl_defd_nprct
#undef mk_lib_crypto_mac_hmac_inl_defd_nprvt
#undef mk_lib_crypto_mac_hmac_inl_defd_nprcvt
#undef mk_lib_crypto_mac_hmac_inl_defd_cpt
#undef mk_lib_crypto_mac_hmac_inl_defd_vpt
#undef mk_lib_crypto_mac_hmac_inl_defd_cvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_ppt
#undef mk_lib_crypto_mac_hmac_inl_defd_pcpt
#undef mk_lib_crypto_mac_hmac_inl_defd_pvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_pcvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_prpt
#undef mk_lib_crypto_mac_hmac_inl_defd_prcpt
#undef mk_lib_crypto_mac_hmac_inl_defd_prvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_prcvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_lppt
#undef mk_lib_crypto_mac_hmac_inl_defd_lpcpt
#undef mk_lib_crypto_mac_hmac_inl_defd_lpvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_lpcvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_lprpt
#undef mk_lib_crypto_mac_hmac_inl_defd_lprcpt
#undef mk_lib_crypto_mac_hmac_inl_defd_lprvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_lprcvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_nppt
#undef mk_lib_crypto_mac_hmac_inl_defd_npcpt
#undef mk_lib_crypto_mac_hmac_inl_defd_npvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_npcvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_nprpt
#undef mk_lib_crypto_mac_hmac_inl_defd_nprcpt
#undef mk_lib_crypto_mac_hmac_inl_defd_nprvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_nprcvpt
#undef mk_lib_crypto_mac_hmac_inl_defd_cpct
#undef mk_lib_crypto_mac_hmac_inl_defd_vpct
#undef mk_lib_crypto_mac_hmac_inl_defd_cvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_ppct
#undef mk_lib_crypto_mac_hmac_inl_defd_pcpct
#undef mk_lib_crypto_mac_hmac_inl_defd_pvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_pcvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_prpct
#undef mk_lib_crypto_mac_hmac_inl_defd_prcpct
#undef mk_lib_crypto_mac_hmac_inl_defd_prvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_prcvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_lppct
#undef mk_lib_crypto_mac_hmac_inl_defd_lpcpct
#undef mk_lib_crypto_mac_hmac_inl_defd_lpvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_lpcvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_lprpct
#undef mk_lib_crypto_mac_hmac_inl_defd_lprcpct
#undef mk_lib_crypto_mac_hmac_inl_defd_lprvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_lprcvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_nppct
#undef mk_lib_crypto_mac_hmac_inl_defd_npcpct
#undef mk_lib_crypto_mac_hmac_inl_defd_npvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_npcvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_nprpct
#undef mk_lib_crypto_mac_hmac_inl_defd_nprcpct
#undef mk_lib_crypto_mac_hmac_inl_defd_nprvpct
#undef mk_lib_crypto_mac_hmac_inl_defd_nprcvpct

#undef mk_lib_crypto_mac_hmac_inl_defd_init
#undef mk_lib_crypto_mac_hmac_inl_defd_append
#undef mk_lib_crypto_mac_hmac_inl_defd_finish
