include(`mk_lang_typedef.m')dnl










#undef mk_lib_crypto_mode_stream_inl_defd_name
#undef mk_lib_crypto_mode_stream_inl_defd_base_name


#undef mk_lib_crypto_mode_stream_inl_defd_base_iv_s
#undef mk_lib_crypto_mode_stream_inl_defd_base_iv_t
#undef mk_lib_crypto_mode_stream_inl_defd_base_iv_len_v

#undef mk_lib_crypto_mode_stream_inl_defd_base_key_s
#undef mk_lib_crypto_mode_stream_inl_defd_base_key_t
#undef mk_lib_crypto_mode_stream_inl_defd_base_key_len_v

#undef mk_lib_crypto_mode_stream_inl_defd_base_msg_s
#undef mk_lib_crypto_mode_stream_inl_defd_base_msg_t
mm_per_typedef(`#undef mk_lib_crypto_mode_stream_inl_defd_base_msg_$1')dnl
#undef mk_lib_crypto_mode_stream_inl_defd_base_msg_len_v

#undef mk_lib_crypto_mode_stream_inl_defd_base_alg_s
#undef mk_lib_crypto_mode_stream_inl_defd_base_alg_t
mm_per_typedef(`#undef mk_lib_crypto_mode_stream_inl_defd_base_alg_$1')dnl
#undef mk_lib_crypto_mode_stream_inl_defd_base_alg_len_v

#undef mk_lib_crypto_mode_stream_inl_defd_base_rw_set_iv
#undef mk_lib_crypto_mode_stream_inl_defd_base_rw_set_key_enc
#undef mk_lib_crypto_mode_stream_inl_defd_base_rw_set_key_dec
#undef mk_lib_crypto_mode_stream_inl_defd_base_rw_encrypt
#undef mk_lib_crypto_mode_stream_inl_defd_base_rw_decrypt


#undef mk_lib_crypto_mode_stream_inl_defd_iv_len_e
#undef mk_lib_crypto_mode_stream_inl_defd_iv_len_t
#undef mk_lib_crypto_mode_stream_inl_defd_iv_len_v
#undef mk_lib_crypto_mode_stream_inl_defd_iv_data_u
#undef mk_lib_crypto_mode_stream_inl_defd_iv_data_t
#undef mk_lib_crypto_mode_stream_inl_defd_iv
#undef mk_lib_crypto_mode_stream_inl_defd_iv_s
#undef mk_lib_crypto_mode_stream_inl_defd_iv_t
mm_per_typedef(`#undef mk_lib_crypto_mode_stream_inl_defd_iv_$1')dnl

#undef mk_lib_crypto_mode_stream_inl_defd_key_len_e
#undef mk_lib_crypto_mode_stream_inl_defd_key_len_t
#undef mk_lib_crypto_mode_stream_inl_defd_key_len_v
#undef mk_lib_crypto_mode_stream_inl_defd_key_data_u
#undef mk_lib_crypto_mode_stream_inl_defd_key_data_t
#undef mk_lib_crypto_mode_stream_inl_defd_key
#undef mk_lib_crypto_mode_stream_inl_defd_key_s
#undef mk_lib_crypto_mode_stream_inl_defd_key_t
mm_per_typedef(`#undef mk_lib_crypto_mode_stream_inl_defd_key_$1')dnl

#undef mk_lib_crypto_mode_stream_inl_defd_msg_len_e
#undef mk_lib_crypto_mode_stream_inl_defd_msg_len_t
#undef mk_lib_crypto_mode_stream_inl_defd_msg_len_v
#undef mk_lib_crypto_mode_stream_inl_defd_msg_data_u
#undef mk_lib_crypto_mode_stream_inl_defd_msg_data_t
#undef mk_lib_crypto_mode_stream_inl_defd_msg
#undef mk_lib_crypto_mode_stream_inl_defd_msg_s
#undef mk_lib_crypto_mode_stream_inl_defd_msg_t
mm_per_typedef(`#undef mk_lib_crypto_mode_stream_inl_defd_msg_$1')dnl


#undef mk_lib_crypto_mode_stream_inl_defd
#undef mk_lib_crypto_mode_stream_inl_defd_s
#undef mk_lib_crypto_mode_stream_inl_defd_t
mm_per_typedef(`#undef mk_lib_crypto_mode_stream_inl_defd_$1')dnl

#undef mk_lib_crypto_mode_stream_inl_defd_rw_set_iv
#undef mk_lib_crypto_mode_stream_inl_defd_rw_set_key_enc
#undef mk_lib_crypto_mode_stream_inl_defd_rw_set_key_dec
#undef mk_lib_crypto_mode_stream_inl_defd_rw_encrypt
#undef mk_lib_crypto_mode_stream_inl_defd_rw_decrypt
