#ifndef mk_include_guard_mk_lib_iip_cp_client_connection_h
#define mk_include_guard_mk_lib_iip_cp_client_connection_h


#include "mk_lang_bui.h"
#include "mk_lang_charbit.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"
#include "mk_lib_iip_any_data_connection.h"
#include "mk_lib_iip_cp_client_session.h"
#include "mk_lib_iip_cp_mallocator_global.h"
#include "mk_lib_iip_cp_message.h"
#include "mk_lib_iip_cp_types.h"
#include "mk_lib_net.h"
#include "mk_sl_time.h"


mk_lang_forward(mk_sl_cui_uint8);
mk_lang_forward(mk_lib_iip_cp_client_shared);


#define mk_sl_cui_t_name mk_lib_iip_cp_client_connection_handle
#define mk_sl_cui_t_base_type_name mk_lang_bui_uintptr
#define mk_sl_cui_t_count 1
#define mk_sl_cui_t_disable_big_div 1
#define mk_sl_cui_t_base_type_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_sl_cui_t_inline 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"
#define mk_lib_iip_cp_client_connection_handle_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_lib_iip_cp_client_connection_handle_size_bytes_d (mk_lang_bui_uintptr_size_bits_d / mk_lang_charbit)

struct mk_lib_iip_cp_client_connection_authentication_s
{
	mk_lib_iip_cp_types_string_t m_user_name;
	mk_lib_iip_cp_types_string_t m_password;
};
typedef struct mk_lib_iip_cp_client_connection_authentication_s mk_lib_iip_cp_client_connection_authentication_t;
mk_lang_typedef(mk_lib_iip_cp_client_connection_authentication);

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_connection_buffer_s
{
	mk_sl_cui_uint8_pt m_data;
	mk_lang_types_void_pt m_mallocation;
	mk_lang_types_sint_t m_used;
};
typedef struct mk_lib_iip_cp_client_connection_buffer_s mk_lib_iip_cp_client_connection_buffer_t;
mk_lang_typedef(mk_lib_iip_cp_client_connection_buffer);
#include "mk_lang_warning_msvc_pop.h"

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_connection_task_settings_s
{
	mk_lib_iip_any_data_connection_t m_type;
	mk_lib_iip_cp_client_shared_pt m_shared;
	mk_lib_net_destination_t m_destination;
	mk_lib_iip_cp_client_connection_authentication_t m_authentication;
};
typedef struct mk_lib_iip_cp_client_connection_task_settings_s mk_lib_iip_cp_client_connection_task_settings_t;
mk_lang_typedef(mk_lib_iip_cp_client_connection_task_settings);
#include "mk_lang_warning_msvc_pop.h"

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_connection_state_s
{
	mk_lib_net_socket_t m_socket;
	mk_lib_net_async_connect_t m_async_connect;
	mk_lib_net_write_request_t m_write_request;
	mk_lib_net_read_request_t m_read_request;
	mk_lang_types_bool_t m_stop_requested;
	mk_lang_types_bool_t m_stop_acknowledged;
	mk_lang_types_bool_t m_disconnected;
	mk_lib_iip_cp_client_session_tasks_t m_sessions;
	mk_lang_types_usize_t m_session_idx;
	mk_lang_types_bool_t m_pending_send;
	mk_lang_types_bool_t m_pending_recv;
	mk_sl_time_timestamp_t m_time_req_send;
	mk_sl_time_timestamp_t m_time_req_recv;
	mk_lib_iip_cp_message_t m_msg;
	mk_lib_iip_cp_client_session_task_pt m_pending_session_to_create;
	mk_lib_iip_cp_client_connection_buffer_t m_buf_rcv;
	mk_lib_iip_cp_client_connection_buffer_t m_buf_snd;
};
typedef struct mk_lib_iip_cp_client_connection_state_s mk_lib_iip_cp_client_connection_state_t;
mk_lang_typedef(mk_lib_iip_cp_client_connection_state);
#include "mk_lang_warning_msvc_pop.h"

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_connection_s
{
	mk_lib_iip_cp_client_connection_task_settings_t m_settings;
	mk_lib_iip_cp_client_connection_state_t m_state;
};
typedef struct mk_lib_iip_cp_client_connection_s mk_lib_iip_cp_client_connection_t;
mk_lang_typedef(mk_lib_iip_cp_client_connection);
#include "mk_lang_warning_msvc_pop.h"

enum mk_lib_iip_cp_client_connection_task_result_e
{
	mk_lib_iip_cp_client_connection_task_result_e_did_something,
	mk_lib_iip_cp_client_connection_task_result_e_would_block,
	mk_lib_iip_cp_client_connection_task_result_e_timed_out,
	mk_lib_iip_cp_client_connection_task_result_e_did_nothing,
	mk_lib_iip_cp_client_connection_task_result_e_dummy_end
};
typedef enum mk_lib_iip_cp_client_connection_task_result_e mk_lib_iip_cp_client_connection_task_result_t;
mk_lang_typedef(mk_lib_iip_cp_client_connection_task_result);

enum mk_lib_iip_cp_client_connection_task_step_e
{
	mk_lib_iip_cp_client_connection_task_step_e_create_socket,
	mk_lib_iip_cp_client_connection_task_step_e_want_associate_socket,
	mk_lib_iip_cp_client_connection_task_step_e_connect_begin,
	mk_lib_iip_cp_client_connection_task_step_e_connect_finish,
	mk_lib_iip_cp_client_connection_task_step_e_send_get_date_request,
	mk_lib_iip_cp_client_connection_task_step_e_send_get_date_finish,
	mk_lib_iip_cp_client_connection_task_step_e_recv_set_date_request,
	mk_lib_iip_cp_client_connection_task_step_e_recv_set_date_finish,
	mk_lib_iip_cp_client_connection_task_step_e_send_bandwidth_request,
	mk_lib_iip_cp_client_connection_task_step_e_send_bandwidth_finish,
	mk_lib_iip_cp_client_connection_task_step_e_recv_bandwidth_request,
	mk_lib_iip_cp_client_connection_task_step_e_recv_bandwidth_finish,
	mk_lib_iip_cp_client_connection_task_step_e_ready,
	mk_lib_iip_cp_client_connection_task_step_e_parse_incoming_msg,
	mk_lib_iip_cp_client_connection_task_step_e_dispatch_msg,
	mk_lib_iip_cp_client_connection_task_step_e_want_die,
	mk_lib_iip_cp_client_connection_task_step_e_dummy_end
};
typedef enum mk_lib_iip_cp_client_connection_task_step_e mk_lib_iip_cp_client_connection_task_step_t;

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_connection_task_s
{
	mk_lib_iip_cp_client_connection_task_step_t m_step;
	mk_lib_iip_cp_client_connection_t m_connection;
};
typedef struct mk_lib_iip_cp_client_connection_task_s mk_lib_iip_cp_client_connection_task_t;
mk_lang_typedef(mk_lib_iip_cp_client_connection_task);
#include "mk_lang_warning_msvc_pop.h"


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_rw_construct(mk_lib_iip_cp_client_connection_task_pt const task, mk_lib_iip_cp_client_connection_task_settings_pct const settings) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_rw_destroy(mk_lib_iip_cp_client_connection_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_rw_request_close(mk_lib_iip_cp_client_connection_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_rw_want_associate_socket(mk_lib_iip_cp_client_connection_task_pt const task, mk_lang_types_bool_pt const want) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_rw_gimme_socket(mk_lib_iip_cp_client_connection_task_pt const task, mk_lib_net_socket_ppt const socket, mk_lib_iip_any_data_connection_ppt const associatee) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_rw_on_iorp_done(mk_lib_iip_cp_client_connection_task_pt const task, mk_lang_types_bool_t const successful_io_operation, mk_lang_types_sint_t const bytes_transferred, mk_lang_types_void_pt const overlapped) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_rw_step(mk_lib_iip_cp_client_connection_task_pt const task, mk_lang_types_bool_t const allow_to_block, mk_lang_types_sint_t const tm, mk_lib_iip_cp_client_connection_task_result_pt const step_result) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_rw_want_die(mk_lib_iip_cp_client_connection_task_pt const task, mk_lang_types_bool_pt const want) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_rw_new_session(mk_lib_iip_cp_client_connection_task_pt const task, mk_lib_iip_cp_client_session_settings_pct const settings, mk_lib_iip_cp_client_session_task_ppt const session) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_any_rw_allocate(mk_lib_iip_any_data_connection_ppt const connection) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_any_rw_deallocate(mk_lib_iip_any_data_connection_pt const connection) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_any_rw_construct(mk_lib_iip_any_data_connection_pt const connection, mk_lang_types_void_pt const settings) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_any_rw_destroy(mk_lib_iip_any_data_connection_pt const connection) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_any_rw_request_close(mk_lib_iip_any_data_connection_pt const connection) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_any_rw_want_associate_socket(mk_lib_iip_any_data_connection_pt const connection, mk_lang_types_bool_pt const want) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_any_rw_gimme_socket(mk_lib_iip_any_data_connection_pt const connection, mk_lib_net_socket_ppt const socket, mk_lib_iip_any_data_connection_ppt const associatee) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_any_rw_on_iorp_done(mk_lib_iip_any_data_connection_pt const connection, mk_lang_types_bool_t const successful_io_operation, mk_lang_types_sint_t const bytes_transferred, mk_lang_types_void_pt const overlapped) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_any_rw_step(mk_lib_iip_any_data_connection_pt const connection, mk_lang_types_bool_t const allow_to_block, mk_lang_types_sint_t const tm, mk_lib_iip_any_data_connection_result_pt const step_result) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_any_rw_want_die(mk_lib_iip_any_data_connection_pt const connection, mk_lang_types_bool_pt const want) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_any_rw_new_session(mk_lib_iip_any_data_connection_pt const connection, mk_lib_iip_cp_client_session_settings_pct const settings, mk_lib_iip_cp_client_session_task_ppt const session) mk_lang_noexcept;


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_ptr_rw_construct_void(mk_lib_iip_cp_client_connection_task_ppt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_ptr_rw_destroy(mk_lib_iip_cp_client_connection_task_ppt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_ptr_rw_construct_copy(mk_lib_iip_cp_client_connection_task_ppt const dst, mk_lib_iip_cp_client_connection_task_pcpt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_ptr_rw_construct_move(mk_lib_iip_cp_client_connection_task_ppt const dst, mk_lib_iip_cp_client_connection_task_ppt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_ptr_rw_assign_copy(mk_lib_iip_cp_client_connection_task_ppt const dst, mk_lib_iip_cp_client_connection_task_pcpt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_connection_task_ptr_rw_assign_move(mk_lib_iip_cp_client_connection_task_ppt const dst, mk_lib_iip_cp_client_connection_task_ppt const src) mk_lang_noexcept;

#define mk_sl_vector_t_name mk_lib_iip_cp_client_connection_tasks
#define mk_sl_vector_t_element_type mk_lib_iip_cp_client_connection_task_pt
#define mk_sl_vector_t_mallocatorg mk_lib_iip_cp_mallocator_global
#define mk_sl_vector_t_element_construct_void mk_lib_iip_cp_client_connection_task_ptr_rw_construct_void
#define mk_sl_vector_t_element_destruct mk_lib_iip_cp_client_connection_task_ptr_rw_destroy
#define mk_sl_vector_t_element_copy_construct mk_lib_iip_cp_client_connection_task_ptr_rw_construct_copy
#define mk_sl_vector_t_element_move_construct mk_lib_iip_cp_client_connection_task_ptr_rw_construct_move
#define mk_sl_vector_t_element_copy_assign mk_lib_iip_cp_client_connection_task_ptr_rw_assign_copy
#define mk_sl_vector_t_element_move_assign mk_lib_iip_cp_client_connection_task_ptr_rw_assign_move
#include "mk_sl_vector_inl_fileh.h"
#include "mk_sl_vector_inl_fileu.h"


#if mk_lang_jumbo_have
#include "mk_lib_iip_cp_client_connection_task.c"
#endif
#endif
