include(`mk_lang_typedef.m')dnl



































#undef mk_lib_float_analyzer_inl_defd_name
#undef mk_lib_float_analyzer_inl_defd_bits_all
#undef mk_lib_float_analyzer_inl_defd_bits_exponent
#undef mk_lib_float_analyzer_inl_defd_bits_mantissa

#undef mk_lib_float_analyzer_inl_defd_prefix

#undef mk_lib_float_analyzer_inl_defd
#undef mk_lib_float_analyzer_inl_defd_s
#undef mk_lib_float_analyzer_inl_defd_t
mm_per_typedef(`#undef mk_lib_float_analyzer_inl_defd_$1')`'



#undef mk_lib_float_analyzer_inl_defd_base_cui_all
#undef mk_lib_float_analyzer_inl_defd_base_cui_all_size_bits_d


#undef mk_lib_float_analyzer_inl_defd_base_cui_all
#undef mk_lib_float_analyzer_inl_defd_base_cui_all_size_bits_d


#undef mk_lib_float_analyzer_inl_defd_base_cui_all
#undef mk_lib_float_analyzer_inl_defd_base_cui_all_size_bits_d


#undef mk_lib_float_analyzer_inl_defd_base_cui_all
#undef mk_lib_float_analyzer_inl_defd_base_cui_all_size_bits_d



#undef mk_lib_float_analyzer_inl_defd_base_cui_all_t
#undef mk_lib_float_analyzer_inl_defd_cui_all
#undef mk_lib_float_analyzer_inl_defd_cui_all_t
mm_per_typedef(`#undef mk_lib_float_analyzer_inl_defd_cui_all_$1')`'
#undef mk_lib_float_analyzer_inl_defd_cui_all_size_bits_v
#undef mk_lib_float_analyzer_inl_defd_cui_all_size_bytes_v
#undef mk_lib_float_analyzer_inl_defd_cui_all_strlen_bin_v
#undef mk_lib_float_analyzer_inl_defd_cui_all_strlen_dec_v
#undef mk_lib_float_analyzer_inl_defd_cui_all_strlen_hex_v
#undef mk_lib_float_analyzer_inl_defd_cui_all_from_buis_uchar_le
#undef mk_lib_float_analyzer_inl_defd_cui_all_to_str_binf_n
#undef mk_lib_float_analyzer_inl_defd_cui_all_to_str_hexf_n
#undef mk_lib_float_analyzer_inl_defd_cui_all_to_str_dec_n
#undef mk_lib_float_analyzer_inl_defd_cui_all_has_msb
#undef mk_lib_float_analyzer_inl_defd_cui_all_not1
#undef mk_lib_float_analyzer_inl_defd_cui_all_inc1
#undef mk_lib_float_analyzer_inl_defd_cui_all_shl3
#undef mk_lib_float_analyzer_inl_defd_cui_all_shl2
#undef mk_lib_float_analyzer_inl_defd_cui_all_shr2
#undef mk_lib_float_analyzer_inl_defd_cui_all_to_buis_uchar_le



#undef mk_lib_float_analyzer_inl_defd_base_cui_exponent
#undef mk_lib_float_analyzer_inl_defd_base_cui_exponent_size_bits_d


#undef mk_lib_float_analyzer_inl_defd_base_cui_exponent
#undef mk_lib_float_analyzer_inl_defd_base_cui_exponent_size_bits_d


#undef mk_lib_float_analyzer_inl_defd_base_cui_exponent
#undef mk_lib_float_analyzer_inl_defd_base_cui_exponent_size_bits_d


#undef mk_lib_float_analyzer_inl_defd_base_cui_exponent
#undef mk_lib_float_analyzer_inl_defd_base_cui_exponent_size_bits_d


#undef mk_lib_float_analyzer_inl_defd_base_cui_exponent
#undef mk_lib_float_analyzer_inl_defd_base_cui_exponent_size_bits_d



#undef mk_lib_float_analyzer_inl_defd_cui_exponent
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_t
mm_per_typedef(`#undef mk_lib_float_analyzer_inl_defd_cui_exponent_$1')`'
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_strlen_bin_v
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_strlen_dec_v
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_strlen_hex_v
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_from_buis_uchar_le
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_to_str_binf_n
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_to_str_hexf_n
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_to_str_dec_n
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_set_max
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_set_bit
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_dec1
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_shr2
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_sub2_wrap_cid_cod
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_is_zero
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_is_max
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_count_trailing_ones
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_has_msb
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_not1
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_inc1
#undef mk_lib_float_analyzer_inl_defd_cui_exponent_to_bi_sint



#undef mk_lib_float_analyzer_inl_defd_base_cui_mantissa
#undef mk_lib_float_analyzer_inl_defd_base_cui_mantissa_size_bits_d


#undef mk_lib_float_analyzer_inl_defd_base_cui_mantissa
#undef mk_lib_float_analyzer_inl_defd_base_cui_mantissa_size_bits_d


#undef mk_lib_float_analyzer_inl_defd_base_cui_mantissa
#undef mk_lib_float_analyzer_inl_defd_base_cui_mantissa_size_bits_d


#undef mk_lib_float_analyzer_inl_defd_base_cui_mantissa
#undef mk_lib_float_analyzer_inl_defd_base_cui_mantissa_size_bits_d


#undef mk_lib_float_analyzer_inl_defd_base_cui_mantissa
#undef mk_lib_float_analyzer_inl_defd_base_cui_mantissa_size_bits_d



#undef mk_lib_float_analyzer_inl_defd_cui_mantissa
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_t
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_pt
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_strlen_bin_v
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_strlen_dec_v
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_strlen_hex_v
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_from_buis_uchar_le
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_is_zero
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_to_str_binf_n
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_to_str_hexf_n
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_to_str_dec_n
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_from_bi_sint
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_shl3
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_mul4_wrap_wi_smol
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_to_bi_sint
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_fraction_max_len_d

#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_base_t
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_base_from_bi_sint
#undef mk_lib_float_analyzer_inl_defd_cui_mantissa_base_to_bi_sint

#undef mk_lib_float_analyzer_inl_defd_cui_big_bits_needed_d
#undef mk_lib_float_analyzer_inl_defd_cui_big
#undef mk_lib_float_analyzer_inl_defd_cui_big_t
mm_per_typedef(`#undef mk_lib_float_analyzer_inl_defd_cui_big_$1')`'
#undef mk_lib_float_analyzer_inl_defd_cui_big_to_str_dec_inverse_n
#undef mk_lib_float_analyzer_inl_defd_cui_big_from_bi_sint
#undef mk_lib_float_analyzer_inl_defd_cui_big_mul4_wrap_wi
#undef mk_lib_float_analyzer_inl_defd_cui_big_mul4_wrap_wi_smol
#undef mk_lib_float_analyzer_inl_defd_cui_big_to_bi_sint
#undef mk_lib_float_analyzer_inl_defd_cui_big_is_zero
#undef mk_lib_float_analyzer_inl_defd_cui_big_set_one
#undef mk_lib_float_analyzer_inl_defd_cui_big_set_zero
#undef mk_lib_float_analyzer_inl_defd_cui_big_shl2
#undef mk_lib_float_analyzer_inl_defd_cui_big_from_bi_uchar
#undef mk_lib_float_analyzer_inl_defd_cui_big_or2
#undef mk_lib_float_analyzer_inl_defd_cui_big_shr3
#undef mk_lib_float_analyzer_inl_defd_cui_big_shl3
#undef mk_lib_float_analyzer_inl_defd_cui_big_to_str_dec_n

#undef mk_lib_float_analyzer_inl_defd_cui_value_log10
#undef mk_lib_float_analyzer_inl_defd_cui_value_max_len_before_point_d
#undef mk_lib_float_analyzer_inl_defd_cui_value_max_len_after_point_d
#undef mk_lib_float_analyzer_inl_defd_cui_value_max_len_d

#undef mk_lib_float_analyzer_inl_defd_text_sign_positive
#undef mk_lib_float_analyzer_inl_defd_text_sign_negative
#undef mk_lib_float_analyzer_inl_defd_text_exponent_na
#undef mk_lib_float_analyzer_inl_defd_text_exponent_type_denormal
#undef mk_lib_float_analyzer_inl_defd_text_exponent_type_infinity
#undef mk_lib_float_analyzer_inl_defd_text_exponent_type_nan
#undef mk_lib_float_analyzer_inl_defd_text_exponent_type_normal
#undef mk_lib_float_analyzer_inl_defd_text_exponent_type_zero
#undef mk_lib_float_analyzer_inl_defd_text_exponent_implied_one_na
#undef mk_lib_float_analyzer_inl_defd_text_exponent_implied_one_no
#undef mk_lib_float_analyzer_inl_defd_text_exponent_implied_one_yes
#undef mk_lib_float_analyzer_inl_defd_text_mantissa_na

#undef mk_lib_float_analyzer_inl_defd_kind_e
#undef mk_lib_float_analyzer_inl_defd_kind_t
#undef mk_lib_float_analyzer_inl_defd_kind_e_normal
#undef mk_lib_float_analyzer_inl_defd_kind_e_zero
#undef mk_lib_float_analyzer_inl_defd_kind_e_denormal
#undef mk_lib_float_analyzer_inl_defd_kind_e_infinity
#undef mk_lib_float_analyzer_inl_defd_kind_e_nan
#undef mk_lib_float_analyzer_inl_defd_kind_e_dummy_end

#undef mk_lib_float_analyzer_inl_defd_k_alphabet

#undef mk_lib_float_analyzer_inl_defd_pr_analyze_get_kind
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_get_all
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_get_exponent
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_get_mantissa
#undef mk_lib_float_analyzer_inl_defd_pr_decode_exponent

#undef mk_lib_float_analyzer_inl_defd_pr_analyze_all_bin
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_all_hex
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_all_dec
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_all_sgn
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_sign
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_exponent_bin
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_exponent_hex
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_exponent_dec
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_exponent_dcd
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_exponent_typ
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_exponent_one
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_mantissa_bin
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_mantissa_hex
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_mantissa_dec
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_mantissa_dcd
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_value

#undef mk_lib_float_analyzer_inl_defd_pr_analyze_mantissa_dcd_y
#undef mk_lib_float_analyzer_inl_defd_pr_analyze_mantissa_dcd_n

#undef mk_lib_float_analyzer_inl_defd_analyze
