#ifndef mk_include_guard_mk_lib_iip_key_sgn_dsa_sha1_h
#define mk_include_guard_mk_lib_iip_key_sgn_dsa_sha1_h


#include "mk_lang_concat.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_platform.h"
#include "mk_lang_static_param.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"


mk_lang_forward(mk_sl_cui_uint8);


#if mk_lang_platform_is_windows_at_least_any
#include "mk_lib_iip_key_sgn_dsa_sha1_windows.h"
#define mk_lib_iip_key_sgn_dsa_sha1_base mk_lib_iip_key_sgn_dsa_sha1_windows
#else
#include "mk_lib_iip_key_sgn_dsa_sha1_portable.h"
#define mk_lib_iip_key_sgn_dsa_sha1_base mk_lib_iip_key_sgn_dsa_sha1_portable
#endif
#define mk_lib_iip_key_sgn_dsa_sha1_impl_pri_len_d mk_lang_concat(mk_lib_iip_key_sgn_dsa_sha1_base, _pri_len_d)
#define mk_lib_iip_key_sgn_dsa_sha1_impl_pub_len_d mk_lang_concat(mk_lib_iip_key_sgn_dsa_sha1_base, _pub_len_d)
#define mk_lib_iip_key_sgn_dsa_sha1_impl_digest_len_d mk_lang_concat(mk_lib_iip_key_sgn_dsa_sha1_base, _digest_len_d)
#define mk_lib_iip_key_sgn_dsa_sha1_impl_signature_len_d mk_lang_concat(mk_lib_iip_key_sgn_dsa_sha1_base, _signature_len_d)
#define mk_lib_iip_key_sgn_dsa_sha1_impl_digest_t mk_lang_concat(mk_lib_iip_key_sgn_dsa_sha1_base, _digest_t)
#define mk_lib_iip_key_sgn_dsa_sha1_impl_signature_t mk_lang_concat(mk_lib_iip_key_sgn_dsa_sha1_base, _signature_t)
#define mk_lib_iip_key_sgn_dsa_sha1_impl_pri_t mk_lang_concat(mk_lib_iip_key_sgn_dsa_sha1_base, _pri_t)
#define mk_lib_iip_key_sgn_dsa_sha1_impl_pub_t mk_lang_concat(mk_lib_iip_key_sgn_dsa_sha1_base, _pub_t)


#define mk_lib_iip_key_sgn_dsa_sha1_pri_len_d mk_lib_iip_key_sgn_dsa_sha1_impl_pri_len_d
#define mk_lib_iip_key_sgn_dsa_sha1_pub_len_d mk_lib_iip_key_sgn_dsa_sha1_impl_pub_len_d
#define mk_lib_iip_key_sgn_dsa_sha1_digest_len_d mk_lib_iip_key_sgn_dsa_sha1_impl_digest_len_d
#define mk_lib_iip_key_sgn_dsa_sha1_signature_len_d mk_lib_iip_key_sgn_dsa_sha1_impl_signature_len_d

enum mk_lib_iip_key_sgn_dsa_sha1_pri_len_e{ mk_lib_iip_key_sgn_dsa_sha1_pri_len_v = mk_lib_iip_key_sgn_dsa_sha1_pri_len_d }; typedef enum mk_lib_iip_key_sgn_dsa_sha1_pri_len_e mk_lib_iip_key_sgn_dsa_sha1_pri_len_t;
enum mk_lib_iip_key_sgn_dsa_sha1_pub_len_e{ mk_lib_iip_key_sgn_dsa_sha1_pub_len_v = mk_lib_iip_key_sgn_dsa_sha1_pub_len_d }; typedef enum mk_lib_iip_key_sgn_dsa_sha1_pub_len_e mk_lib_iip_key_sgn_dsa_sha1_pub_len_t;
enum mk_lib_iip_key_sgn_dsa_sha1_digest_len_e{ mk_lib_iip_key_sgn_dsa_sha1_digest_len_v = mk_lib_iip_key_sgn_dsa_sha1_digest_len_d }; typedef enum mk_lib_iip_key_sgn_dsa_sha1_digest_len_e mk_lib_iip_key_sgn_dsa_sha1_digest_len_t;
enum mk_lib_iip_key_sgn_dsa_sha1_signature_len_e{ mk_lib_iip_key_sgn_dsa_sha1_signature_len_v = mk_lib_iip_key_sgn_dsa_sha1_signature_len_d }; typedef enum mk_lib_iip_key_sgn_dsa_sha1_signature_len_e mk_lib_iip_key_sgn_dsa_sha1_signature_len_t;


struct mk_lib_iip_key_sgn_dsa_sha1_digest_s
{
	mk_lib_iip_key_sgn_dsa_sha1_impl_digest_t m_base;
};
typedef struct mk_lib_iip_key_sgn_dsa_sha1_digest_s mk_lib_iip_key_sgn_dsa_sha1_digest_t;
mk_lang_typedef(mk_lib_iip_key_sgn_dsa_sha1_digest);

struct mk_lib_iip_key_sgn_dsa_sha1_signature_s
{
	mk_lib_iip_key_sgn_dsa_sha1_impl_signature_t m_base;
};
typedef struct mk_lib_iip_key_sgn_dsa_sha1_signature_s mk_lib_iip_key_sgn_dsa_sha1_signature_t;
mk_lang_typedef(mk_lib_iip_key_sgn_dsa_sha1_signature);


struct mk_lib_iip_key_sgn_dsa_sha1_pri_s
{
	mk_lib_iip_key_sgn_dsa_sha1_impl_pri_t m_base;
};
typedef struct mk_lib_iip_key_sgn_dsa_sha1_pri_s mk_lib_iip_key_sgn_dsa_sha1_pri_t;
mk_lang_typedef(mk_lib_iip_key_sgn_dsa_sha1_pri);

struct mk_lib_iip_key_sgn_dsa_sha1_pub_s
{
	mk_lib_iip_key_sgn_dsa_sha1_impl_pub_t m_base;
};
typedef struct mk_lib_iip_key_sgn_dsa_sha1_pub_s mk_lib_iip_key_sgn_dsa_sha1_pub_t;
mk_lang_typedef(mk_lib_iip_key_sgn_dsa_sha1_pub);


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_st_hash_data(mk_sl_cui_uint8_pct const data_buf, mk_lang_types_sint_t const data_len, mk_lib_iip_key_sgn_dsa_sha1_digest_pt const digest) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_pri_rw_is_valid(mk_lang_static_param(mk_sl_cui_uint8_ct, u8s, mk_lib_iip_key_sgn_dsa_sha1_pri_len_v), mk_lang_types_bool_pt const is_valid) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_pri_rw_generate_random(mk_lib_iip_key_sgn_dsa_sha1_pri_pt const pri) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_pri_rw_construct_from_u8s(mk_lib_iip_key_sgn_dsa_sha1_pri_pt const pri, mk_lang_static_param(mk_sl_cui_uint8_ct, u8s, mk_lib_iip_key_sgn_dsa_sha1_pri_len_v)) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_pri_rw_destroy(mk_lib_iip_key_sgn_dsa_sha1_pri_pt const pri) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_pri_rw_export_pri_to_u8s(mk_lib_iip_key_sgn_dsa_sha1_pri_pct const pri, mk_lang_static_param(mk_sl_cui_uint8_t, u8s, mk_lib_iip_key_sgn_dsa_sha1_pri_len_v)) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_pri_rw_export_pub_to_u8s(mk_lib_iip_key_sgn_dsa_sha1_pri_pct const pri, mk_lang_static_param(mk_sl_cui_uint8_t, u8s, mk_lib_iip_key_sgn_dsa_sha1_pub_len_v)) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_pri_rw_get_public(mk_lib_iip_key_sgn_dsa_sha1_pri_pct const pri, mk_lib_iip_key_sgn_dsa_sha1_pub_pt const pub) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_pri_rw_sign_digest(mk_lib_iip_key_sgn_dsa_sha1_pri_pct const pri, mk_lib_iip_key_sgn_dsa_sha1_digest_pct const digest, mk_lib_iip_key_sgn_dsa_sha1_signature_pt const signature) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_pri_rw_validate_signature(mk_lib_iip_key_sgn_dsa_sha1_pri_pct const pri, mk_lib_iip_key_sgn_dsa_sha1_digest_pct const digest, mk_lib_iip_key_sgn_dsa_sha1_signature_pct const signature, mk_lang_types_bool_pt const is_valid) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_pub_rw_construct_from_u8s(mk_lib_iip_key_sgn_dsa_sha1_pub_pt const pub, mk_lang_static_param(mk_sl_cui_uint8_ct, u8s, mk_lib_iip_key_sgn_dsa_sha1_pub_len_v)) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_pub_rw_destroy(mk_lib_iip_key_sgn_dsa_sha1_pub_pt const pub) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_pub_rw_export_to_u8s(mk_lib_iip_key_sgn_dsa_sha1_pub_pct const pub, mk_lang_static_param(mk_sl_cui_uint8_t, u8s, mk_lib_iip_key_sgn_dsa_sha1_pub_len_v)) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_key_sgn_dsa_sha1_pub_rw_validate_signature(mk_lib_iip_key_sgn_dsa_sha1_pub_pct const pub, mk_lib_iip_key_sgn_dsa_sha1_digest_pct const digest, mk_lib_iip_key_sgn_dsa_sha1_signature_pct const signature, mk_lang_types_bool_pt const is_valid) mk_lang_noexcept;


#if mk_lang_jumbo_have
#include "mk_lib_iip_key_sgn_dsa_sha1.c"
#endif
#endif
