










#undef mk_lib_crypto_hash_stream_inl_defd_name

#undef mk_lib_crypto_hash_stream_inl_defd_padding

#undef mk_lib_crypto_hash_stream_inl_defd_padding



#undef mk_lib_crypto_hash_stream_inl_defd_base_prefix

#undef mk_lib_crypto_hash_stream_inl_defd_base_block_len_e
#undef mk_lib_crypto_hash_stream_inl_defd_base_block_len_t
#undef mk_lib_crypto_hash_stream_inl_defd_base_block_len_v

#undef mk_lib_crypto_hash_stream_inl_defd_base_digest_len_e
#undef mk_lib_crypto_hash_stream_inl_defd_base_digest_len_t
#undef mk_lib_crypto_hash_stream_inl_defd_base_digest_len_v

#undef mk_lib_crypto_hash_stream_inl_defd_base_block_t
#undef mk_lib_crypto_hash_stream_inl_defd_base_block_ct
#undef mk_lib_crypto_hash_stream_inl_defd_base_block_pt
#undef mk_lib_crypto_hash_stream_inl_defd_base_block_pct

#undef mk_lib_crypto_hash_stream_inl_defd_base_digest_t
#undef mk_lib_crypto_hash_stream_inl_defd_base_digest_ct
#undef mk_lib_crypto_hash_stream_inl_defd_base_digest_pt
#undef mk_lib_crypto_hash_stream_inl_defd_base_digest_pct

#undef mk_lib_crypto_hash_stream_inl_defd_base_t
#undef mk_lib_crypto_hash_stream_inl_defd_base_ct
#undef mk_lib_crypto_hash_stream_inl_defd_base_pt
#undef mk_lib_crypto_hash_stream_inl_defd_base_pct

#undef mk_lib_crypto_hash_stream_inl_defd_base_init
#undef mk_lib_crypto_hash_stream_inl_defd_base_append_blocks
#undef mk_lib_crypto_hash_stream_inl_defd_base_finish


#undef mk_lib_crypto_hash_stream_inl_defd_prefix

#undef mk_lib_crypto_hash_stream_inl_defd_digest_len_e
#undef mk_lib_crypto_hash_stream_inl_defd_digest_len_t
#undef mk_lib_crypto_hash_stream_inl_defd_digest_len_v

#undef mk_lib_crypto_hash_stream_inl_defd_block_t
#undef mk_lib_crypto_hash_stream_inl_defd_block_ct
#undef mk_lib_crypto_hash_stream_inl_defd_block_pt
#undef mk_lib_crypto_hash_stream_inl_defd_block_pct

#undef mk_lib_crypto_hash_stream_inl_defd_digest_t
#undef mk_lib_crypto_hash_stream_inl_defd_digest_ct
#undef mk_lib_crypto_hash_stream_inl_defd_digest_pt
#undef mk_lib_crypto_hash_stream_inl_defd_digest_pct

#undef mk_lib_crypto_hash_stream_inl_defd_s
#undef mk_lib_crypto_hash_stream_inl_defd_t
#undef mk_lib_crypto_hash_stream_inl_defd_ct
#undef mk_lib_crypto_hash_stream_inl_defd_pt
#undef mk_lib_crypto_hash_stream_inl_defd_pct

#undef mk_lib_crypto_hash_stream_inl_defd_init
#undef mk_lib_crypto_hash_stream_inl_defd_append_u8s
#undef mk_lib_crypto_hash_stream_inl_defd_finish
