#ifndef mk_include_guard_mk_lang_types
#define mk_include_guard_mk_lang_types


#include "mk_lang_bool.h"
#include "mk_lang_intmaxt.h"
#include "mk_lang_intptrt.h"
#include "mk_lang_lllong.h"
#include "mk_lang_llong.h"
#include "mk_lang_restrict.h"
#include "mk_lang_sizet.h"


typedef void mk_lang_types_void_t;
typedef mk_lang_bool_t mk_lang_types_bool_t;
typedef char mk_lang_types_pchar_t;
typedef unsigned char mk_lang_types_uchar_t;
typedef signed char mk_lang_types_schar_t;
typedef unsigned short int mk_lang_types_ushort_t;
typedef signed short int mk_lang_types_sshort_t;
typedef unsigned int mk_lang_types_uint_t;
typedef signed int mk_lang_types_sint_t;
typedef unsigned long int mk_lang_types_ulong_t;
typedef signed long int mk_lang_types_slong_t;
typedef mk_lang_ullong_t mk_lang_types_ullong_t;
typedef mk_lang_sllong_t mk_lang_types_sllong_t;
typedef mk_lang_ulllong_t mk_lang_types_ulllong_t;
typedef mk_lang_slllong_t mk_lang_types_slllong_t;
typedef mk_lang_uintptr_t mk_lang_types_uintptr_t;
typedef mk_lang_sintptr_t mk_lang_types_sintptr_t;
typedef mk_lang_uintmax_t mk_lang_types_uintmax_t;
typedef mk_lang_sintmax_t mk_lang_types_sintmax_t;
typedef mk_lang_usize_t mk_lang_types_usize_t;
typedef mk_lang_ssize_t mk_lang_types_ssize_t;
typedef float mk_lang_types_float_t;
typedef double mk_lang_types_double_t;
typedef long double mk_lang_types_ldouble_t;

typedef mk_lang_types_void_t const mk_lang_types_void_ct;
typedef mk_lang_types_bool_t const mk_lang_types_bool_ct;
typedef mk_lang_types_pchar_t const mk_lang_types_pchar_ct;
typedef mk_lang_types_uchar_t const mk_lang_types_uchar_ct;
typedef mk_lang_types_schar_t const mk_lang_types_schar_ct;
typedef mk_lang_types_ushort_t const mk_lang_types_ushort_ct;
typedef mk_lang_types_sshort_t const mk_lang_types_sshort_ct;
typedef mk_lang_types_uint_t const mk_lang_types_uint_ct;
typedef mk_lang_types_sint_t const mk_lang_types_sint_ct;
typedef mk_lang_types_ulong_t const mk_lang_types_ulong_ct;
typedef mk_lang_types_slong_t const mk_lang_types_slong_ct;
typedef mk_lang_types_ullong_t const mk_lang_types_ullong_ct;
typedef mk_lang_types_sllong_t const mk_lang_types_sllong_ct;
typedef mk_lang_types_ulllong_t const mk_lang_types_ulllong_ct;
typedef mk_lang_types_slllong_t const mk_lang_types_slllong_ct;
typedef mk_lang_types_uintptr_t const mk_lang_types_uintptr_ct;
typedef mk_lang_types_sintptr_t const mk_lang_types_sintptr_ct;
typedef mk_lang_types_uintmax_t const mk_lang_types_uintmax_ct;
typedef mk_lang_types_sintmax_t const mk_lang_types_sintmax_ct;
typedef mk_lang_types_usize_t const mk_lang_types_usize_ct;
typedef mk_lang_types_ssize_t const mk_lang_types_ssize_ct;
typedef mk_lang_types_float_t const mk_lang_types_float_ct;
typedef mk_lang_types_double_t const mk_lang_types_double_ct;
typedef mk_lang_types_ldouble_t const mk_lang_types_ldouble_ct;

typedef mk_lang_types_void_t* mk_lang_types_void_pt;
typedef mk_lang_types_bool_t* mk_lang_types_bool_pt;
typedef mk_lang_types_pchar_t* mk_lang_types_pchar_pt;
typedef mk_lang_types_uchar_t* mk_lang_types_uchar_pt;
typedef mk_lang_types_schar_t* mk_lang_types_schar_pt;
typedef mk_lang_types_ushort_t* mk_lang_types_ushort_pt;
typedef mk_lang_types_sshort_t* mk_lang_types_sshort_pt;
typedef mk_lang_types_uint_t* mk_lang_types_uint_pt;
typedef mk_lang_types_sint_t* mk_lang_types_sint_pt;
typedef mk_lang_types_ulong_t* mk_lang_types_ulong_pt;
typedef mk_lang_types_slong_t* mk_lang_types_slong_pt;
typedef mk_lang_types_ullong_t* mk_lang_types_ullong_pt;
typedef mk_lang_types_sllong_t* mk_lang_types_sllong_pt;
typedef mk_lang_types_ulllong_t* mk_lang_types_ulllong_pt;
typedef mk_lang_types_slllong_t* mk_lang_types_slllong_pt;
typedef mk_lang_types_uintptr_t* mk_lang_types_uintptr_pt;
typedef mk_lang_types_sintptr_t* mk_lang_types_sintptr_pt;
typedef mk_lang_types_uintmax_t* mk_lang_types_uintmax_pt;
typedef mk_lang_types_sintmax_t* mk_lang_types_sintmax_pt;
typedef mk_lang_types_usize_t* mk_lang_types_usize_pt;
typedef mk_lang_types_ssize_t* mk_lang_types_ssize_pt;
typedef mk_lang_types_float_t* mk_lang_types_float_pt;
typedef mk_lang_types_double_t* mk_lang_types_double_pt;
typedef mk_lang_types_ldouble_t* mk_lang_types_ldouble_pt;

typedef mk_lang_types_void_t const* mk_lang_types_void_pct;
typedef mk_lang_types_bool_t const* mk_lang_types_bool_pct;
typedef mk_lang_types_pchar_t const* mk_lang_types_pchar_pct;
typedef mk_lang_types_uchar_t const* mk_lang_types_uchar_pct;
typedef mk_lang_types_schar_t const* mk_lang_types_schar_pct;
typedef mk_lang_types_ushort_t const* mk_lang_types_ushort_pct;
typedef mk_lang_types_sshort_t const* mk_lang_types_sshort_pct;
typedef mk_lang_types_uint_t const* mk_lang_types_uint_pct;
typedef mk_lang_types_sint_t const* mk_lang_types_sint_pct;
typedef mk_lang_types_ulong_t const* mk_lang_types_ulong_pct;
typedef mk_lang_types_slong_t const* mk_lang_types_slong_pct;
typedef mk_lang_types_ullong_t const* mk_lang_types_ullong_pct;
typedef mk_lang_types_sllong_t const* mk_lang_types_sllong_pct;
typedef mk_lang_types_ulllong_t const* mk_lang_types_ulllong_pct;
typedef mk_lang_types_slllong_t const* mk_lang_types_slllong_pct;
typedef mk_lang_types_uintptr_t const* mk_lang_types_uintptr_pct;
typedef mk_lang_types_sintptr_t const* mk_lang_types_sintptr_pct;
typedef mk_lang_types_uintmax_t const* mk_lang_types_uintmax_pct;
typedef mk_lang_types_sintmax_t const* mk_lang_types_sintmax_pct;
typedef mk_lang_types_usize_t const* mk_lang_types_usize_pct;
typedef mk_lang_types_ssize_t const* mk_lang_types_ssize_pct;
typedef mk_lang_types_float_t const* mk_lang_types_float_pct;
typedef mk_lang_types_double_t const* mk_lang_types_double_pct;
typedef mk_lang_types_ldouble_t const* mk_lang_types_ldouble_pct;

typedef mk_lang_types_void_t* mk_lang_restrict mk_lang_types_void_prt;
typedef mk_lang_types_bool_t* mk_lang_restrict mk_lang_types_bool_prt;
typedef mk_lang_types_pchar_t* mk_lang_restrict mk_lang_types_pchar_prt;
typedef mk_lang_types_uchar_t* mk_lang_restrict mk_lang_types_uchar_prt;
typedef mk_lang_types_schar_t* mk_lang_restrict mk_lang_types_schar_prt;
typedef mk_lang_types_ushort_t* mk_lang_restrict mk_lang_types_ushort_prt;
typedef mk_lang_types_sshort_t* mk_lang_restrict mk_lang_types_sshort_prt;
typedef mk_lang_types_uint_t* mk_lang_restrict mk_lang_types_uint_prt;
typedef mk_lang_types_sint_t* mk_lang_restrict mk_lang_types_sint_prt;
typedef mk_lang_types_ulong_t* mk_lang_restrict mk_lang_types_ulong_prt;
typedef mk_lang_types_slong_t* mk_lang_restrict mk_lang_types_slong_prt;
typedef mk_lang_types_ullong_t* mk_lang_restrict mk_lang_types_ullong_prt;
typedef mk_lang_types_sllong_t* mk_lang_restrict mk_lang_types_sllong_prt;
typedef mk_lang_types_ulllong_t* mk_lang_restrict mk_lang_types_ulllong_prt;
typedef mk_lang_types_slllong_t* mk_lang_restrict mk_lang_types_slllong_prt;
typedef mk_lang_types_uintptr_t* mk_lang_restrict mk_lang_types_uintptr_prt;
typedef mk_lang_types_sintptr_t* mk_lang_restrict mk_lang_types_sintptr_prt;
typedef mk_lang_types_uintmax_t* mk_lang_restrict mk_lang_types_uintmax_prt;
typedef mk_lang_types_sintmax_t* mk_lang_restrict mk_lang_types_sintmax_prt;
typedef mk_lang_types_usize_t* mk_lang_restrict mk_lang_types_usize_prt;
typedef mk_lang_types_ssize_t* mk_lang_restrict mk_lang_types_ssize_prt;
typedef mk_lang_types_float_t* mk_lang_restrict mk_lang_types_float_prt;
typedef mk_lang_types_double_t* mk_lang_restrict mk_lang_types_double_prt;
typedef mk_lang_types_ldouble_t* mk_lang_restrict mk_lang_types_ldouble_prt;

typedef mk_lang_types_void_t const* mk_lang_restrict mk_lang_types_void_prct;
typedef mk_lang_types_bool_t const* mk_lang_restrict mk_lang_types_bool_prct;
typedef mk_lang_types_pchar_t const* mk_lang_restrict mk_lang_types_pchar_prct;
typedef mk_lang_types_uchar_t const* mk_lang_restrict mk_lang_types_uchar_prct;
typedef mk_lang_types_schar_t const* mk_lang_restrict mk_lang_types_schar_prct;
typedef mk_lang_types_ushort_t const* mk_lang_restrict mk_lang_types_ushort_prct;
typedef mk_lang_types_sshort_t const* mk_lang_restrict mk_lang_types_sshort_prct;
typedef mk_lang_types_uint_t const* mk_lang_restrict mk_lang_types_uint_prct;
typedef mk_lang_types_sint_t const* mk_lang_restrict mk_lang_types_sint_prct;
typedef mk_lang_types_ulong_t const* mk_lang_restrict mk_lang_types_ulong_prct;
typedef mk_lang_types_slong_t const* mk_lang_restrict mk_lang_types_slong_prct;
typedef mk_lang_types_ullong_t const* mk_lang_restrict mk_lang_types_ullong_prct;
typedef mk_lang_types_sllong_t const* mk_lang_restrict mk_lang_types_sllong_prct;
typedef mk_lang_types_ulllong_t const* mk_lang_restrict mk_lang_types_ulllong_prct;
typedef mk_lang_types_slllong_t const* mk_lang_restrict mk_lang_types_slllong_prct;
typedef mk_lang_types_uintptr_t const* mk_lang_restrict mk_lang_types_uintptr_prct;
typedef mk_lang_types_sintptr_t const* mk_lang_restrict mk_lang_types_sintptr_prct;
typedef mk_lang_types_uintmax_t const* mk_lang_restrict mk_lang_types_uintmax_prct;
typedef mk_lang_types_sintmax_t const* mk_lang_restrict mk_lang_types_sintmax_prct;
typedef mk_lang_types_usize_t const* mk_lang_restrict mk_lang_types_usize_prct;
typedef mk_lang_types_ssize_t const* mk_lang_restrict mk_lang_types_ssize_prct;
typedef mk_lang_types_float_t const* mk_lang_restrict mk_lang_types_float_prct;
typedef mk_lang_types_double_t const* mk_lang_restrict mk_lang_types_double_prct;
typedef mk_lang_types_ldouble_t const* mk_lang_restrict mk_lang_types_ldouble_prct;

typedef mk_lang_types_void_pt* mk_lang_types_void_ppt;
typedef mk_lang_types_bool_pt* mk_lang_types_bool_ppt;
typedef mk_lang_types_pchar_pt* mk_lang_types_pchar_ppt;
typedef mk_lang_types_uchar_pt* mk_lang_types_uchar_ppt;
typedef mk_lang_types_schar_pt* mk_lang_types_schar_ppt;
typedef mk_lang_types_ushort_pt* mk_lang_types_ushort_ppt;
typedef mk_lang_types_sshort_pt* mk_lang_types_sshort_ppt;
typedef mk_lang_types_uint_pt* mk_lang_types_uint_ppt;
typedef mk_lang_types_sint_pt* mk_lang_types_sint_ppt;
typedef mk_lang_types_ulong_pt* mk_lang_types_ulong_ppt;
typedef mk_lang_types_slong_pt* mk_lang_types_slong_ppt;
typedef mk_lang_types_ullong_pt* mk_lang_types_ullong_ppt;
typedef mk_lang_types_sllong_pt* mk_lang_types_sllong_ppt;
typedef mk_lang_types_ulllong_pt* mk_lang_types_ulllong_ppt;
typedef mk_lang_types_slllong_pt* mk_lang_types_slllong_ppt;
typedef mk_lang_types_uintptr_pt* mk_lang_types_uintptr_ppt;
typedef mk_lang_types_sintptr_pt* mk_lang_types_sintptr_ppt;
typedef mk_lang_types_uintmax_pt* mk_lang_types_uintmax_ppt;
typedef mk_lang_types_sintmax_pt* mk_lang_types_sintmax_ppt;
typedef mk_lang_types_usize_pt* mk_lang_types_usize_ppt;
typedef mk_lang_types_ssize_pt* mk_lang_types_ssize_ppt;
typedef mk_lang_types_float_pt* mk_lang_types_float_ppt;
typedef mk_lang_types_double_pt* mk_lang_types_double_ppt;
typedef mk_lang_types_ldouble_pt* mk_lang_types_ldouble_ppt;

typedef mk_lang_types_void_pct* mk_lang_types_void_ppct;
typedef mk_lang_types_bool_pct* mk_lang_types_bool_ppct;
typedef mk_lang_types_pchar_pct* mk_lang_types_pchar_ppct;
typedef mk_lang_types_uchar_pct* mk_lang_types_uchar_ppct;
typedef mk_lang_types_schar_pct* mk_lang_types_schar_ppct;
typedef mk_lang_types_ushort_pct* mk_lang_types_ushort_ppct;
typedef mk_lang_types_sshort_pct* mk_lang_types_sshort_ppct;
typedef mk_lang_types_uint_pct* mk_lang_types_uint_ppct;
typedef mk_lang_types_sint_pct* mk_lang_types_sint_ppct;
typedef mk_lang_types_ulong_pct* mk_lang_types_ulong_ppct;
typedef mk_lang_types_slong_pct* mk_lang_types_slong_ppct;
typedef mk_lang_types_ullong_pct* mk_lang_types_ullong_ppct;
typedef mk_lang_types_sllong_pct* mk_lang_types_sllong_ppct;
typedef mk_lang_types_ulllong_pct* mk_lang_types_ulllong_ppct;
typedef mk_lang_types_slllong_pct* mk_lang_types_slllong_ppct;
typedef mk_lang_types_uintptr_pct* mk_lang_types_uintptr_ppct;
typedef mk_lang_types_sintptr_pct* mk_lang_types_sintptr_ppct;
typedef mk_lang_types_uintmax_pct* mk_lang_types_uintmax_ppct;
typedef mk_lang_types_sintmax_pct* mk_lang_types_sintmax_ppct;
typedef mk_lang_types_usize_pct* mk_lang_types_usize_ppct;
typedef mk_lang_types_ssize_pct* mk_lang_types_ssize_ppct;
typedef mk_lang_types_float_pct* mk_lang_types_float_ppct;
typedef mk_lang_types_double_pct* mk_lang_types_double_ppct;
typedef mk_lang_types_ldouble_pct* mk_lang_types_ldouble_ppct;

typedef mk_lang_types_void_pt const* mk_lang_types_void_pcpt;
typedef mk_lang_types_bool_pt const* mk_lang_types_bool_pcpt;
typedef mk_lang_types_pchar_pt const* mk_lang_types_pchar_pcpt;
typedef mk_lang_types_uchar_pt const* mk_lang_types_uchar_pcpt;
typedef mk_lang_types_schar_pt const* mk_lang_types_schar_pcpt;
typedef mk_lang_types_ushort_pt const* mk_lang_types_ushort_pcpt;
typedef mk_lang_types_sshort_pt const* mk_lang_types_sshort_pcpt;
typedef mk_lang_types_uint_pt const* mk_lang_types_uint_pcpt;
typedef mk_lang_types_sint_pt const* mk_lang_types_sint_pcpt;
typedef mk_lang_types_ulong_pt const* mk_lang_types_ulong_pcpt;
typedef mk_lang_types_slong_pt const* mk_lang_types_slong_pcpt;
typedef mk_lang_types_ullong_pt const* mk_lang_types_ullong_pcpt;
typedef mk_lang_types_sllong_pt const* mk_lang_types_sllong_pcpt;
typedef mk_lang_types_ulllong_pt const* mk_lang_types_ulllong_pcpt;
typedef mk_lang_types_slllong_pt const* mk_lang_types_slllong_pcpt;
typedef mk_lang_types_uintptr_pt const* mk_lang_types_uintptr_pcpt;
typedef mk_lang_types_sintptr_pt const* mk_lang_types_sintptr_pcpt;
typedef mk_lang_types_uintmax_pt const* mk_lang_types_uintmax_pcpt;
typedef mk_lang_types_sintmax_pt const* mk_lang_types_sintmax_pcpt;
typedef mk_lang_types_usize_pt const* mk_lang_types_usize_pcpt;
typedef mk_lang_types_ssize_pt const* mk_lang_types_ssize_pcpt;
typedef mk_lang_types_float_pt const* mk_lang_types_float_pcpt;
typedef mk_lang_types_double_pt const* mk_lang_types_double_pcpt;
typedef mk_lang_types_ldouble_pt const* mk_lang_types_ldouble_pcpt;

typedef mk_lang_types_void_pct const* mk_lang_types_void_pcpct;
typedef mk_lang_types_bool_pct const* mk_lang_types_bool_pcpct;
typedef mk_lang_types_pchar_pct const* mk_lang_types_pchar_pcpct;
typedef mk_lang_types_uchar_pct const* mk_lang_types_uchar_pcpct;
typedef mk_lang_types_schar_pct const* mk_lang_types_schar_pcpct;
typedef mk_lang_types_ushort_pct const* mk_lang_types_ushort_pcpct;
typedef mk_lang_types_sshort_pct const* mk_lang_types_sshort_pcpct;
typedef mk_lang_types_uint_pct const* mk_lang_types_uint_pcpct;
typedef mk_lang_types_sint_pct const* mk_lang_types_sint_pcpct;
typedef mk_lang_types_ulong_pct const* mk_lang_types_ulong_pcpct;
typedef mk_lang_types_slong_pct const* mk_lang_types_slong_pcpct;
typedef mk_lang_types_ullong_pct const* mk_lang_types_ullong_pcpct;
typedef mk_lang_types_sllong_pct const* mk_lang_types_sllong_pcpct;
typedef mk_lang_types_ulllong_pct const* mk_lang_types_ulllong_pcpct;
typedef mk_lang_types_slllong_pct const* mk_lang_types_slllong_pcpct;
typedef mk_lang_types_uintptr_pct const* mk_lang_types_uintptr_pcpct;
typedef mk_lang_types_sintptr_pct const* mk_lang_types_sintptr_pcpct;
typedef mk_lang_types_uintmax_pct const* mk_lang_types_uintmax_pcpct;
typedef mk_lang_types_sintmax_pct const* mk_lang_types_sintmax_pcpct;
typedef mk_lang_types_usize_pct const* mk_lang_types_usize_pcpct;
typedef mk_lang_types_ssize_pct const* mk_lang_types_ssize_pcpct;
typedef mk_lang_types_float_pct const* mk_lang_types_float_pcpct;
typedef mk_lang_types_double_pct const* mk_lang_types_double_pcpct;
typedef mk_lang_types_ldouble_pct const* mk_lang_types_ldouble_pcpct;


#endif
