










#undef mk_lib_crypto_alg_twofish_base_inl_defd_name
#undef mk_lib_crypto_alg_twofish_base_inl_defd_keylen











#undef mk_lib_crypto_alg_twofish_base_inl_defd_nr

#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_len_m
#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_len_e
#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_len_v

#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_len_m
#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_len_e
#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_len_v

#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_len_m
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_len_e
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_len_v

#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_data_u
#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_data_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_ct
#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_pt
#undef mk_lib_crypto_alg_twofish_base_inl_defd_key_pct

#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_data_u
#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_data_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_ct
#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_pt
#undef mk_lib_crypto_alg_twofish_base_inl_defd_msg_pct

#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_data_u
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_data_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_ct
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_pt
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_pct

#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_encrypt
#undef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_decrypt
#undef mk_lib_crypto_alg_twofish_base_inl_defd_expand_enc
#undef mk_lib_crypto_alg_twofish_base_inl_defd_expand_dec
#undef mk_lib_crypto_alg_twofish_base_inl_defd_encrypt
#undef mk_lib_crypto_alg_twofish_base_inl_defd_decrypt


#undef mk_lib_crypto_alg_twofish_base_inl_defd_uint328_data_u
#undef mk_lib_crypto_alg_twofish_base_inl_defd_uint328_data_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_uint328_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_uint328_t

#undef mk_lib_crypto_alg_twofish_base_inl_defd_table_data_u
#undef mk_lib_crypto_alg_twofish_base_inl_defd_table_data_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_table_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_table_t

#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_data_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_data_t
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_s
#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables_t

#undef mk_lib_crypto_alg_twofish_base_inl_defd_tables

#undef mk_lib_crypto_alg_twofish_base_inl_defd_lfsr1
#undef mk_lib_crypto_alg_twofish_base_inl_defd_lfsr2
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul1
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mulx
#undef mk_lib_crypto_alg_twofish_base_inl_defd_muly
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul00
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul01
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul02
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul03
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul10
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul11
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul12
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul13
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul20
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul21
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul22
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul23
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul30
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul31
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul32
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mul33
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mulxy
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx00
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx01
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx02
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx03
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx04
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx10
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx11
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx12
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx13
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx14
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx20
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx21
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx22
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx23
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx24
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx30
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx31
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx32
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx33
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idx34
#undef mk_lib_crypto_alg_twofish_base_inl_defd_idxxy
#undef mk_lib_crypto_alg_twofish_base_inl_defd_fx
#undef mk_lib_crypto_alg_twofish_base_inl_defd_f
#undef mk_lib_crypto_alg_twofish_base_inl_defd_rsrem
#undef mk_lib_crypto_alg_twofish_base_inl_defd_mds
#undef mk_lib_crypto_alg_twofish_base_inl_defd_expand
#undef mk_lib_crypto_alg_twofish_base_inl_defd_rnd_enc
#undef mk_lib_crypto_alg_twofish_base_inl_defd_rnd_dec
#undef mk_lib_crypto_alg_twofish_base_inl_defd_one_enc
#undef mk_lib_crypto_alg_twofish_base_inl_defd_one_dec
