#ifndef mk_include_guard_mk_lib_iip_cp_mallocator_global_h
#define mk_include_guard_mk_lib_iip_cp_mallocator_global_h


#include "mk_lang_bui.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_static_param.h"
#include "mk_lang_types.h"


#define mk_sl_cui_t_name mk_lib_iip_cp_mallocator_global_blocks
#define mk_sl_cui_t_base mk_lang_bui_usize
#define mk_sl_cui_t_count 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"

#define mk_sl_cui_t_name mk_lib_iip_cp_mallocator_global_bytes
#define mk_sl_cui_t_base mk_lang_bui_usize
#define mk_sl_cui_t_count 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_mallocator_global_init(mk_lang_types_void_t) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_mallocator_global_deinit(mk_lang_types_void_t) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_mallocator_global_allocate(mk_lang_types_usize_t const size_bytes, mk_lang_types_void_ppt const mem) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_mallocator_global_deallocate(mk_lang_types_void_pct const mem, mk_lang_types_usize_t const size_bytes) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_mallocator_global_reallocate(mk_lang_types_void_pct const old_mem, mk_lang_types_usize_t const old_size_bytes, mk_lang_types_usize_t const new_size_bytes, mk_lang_types_void_ppt const new_mem) mk_lang_noexcept;

mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_cp_mallocator_global_statistics_get_blocks_allocated(mk_lib_iip_cp_mallocator_global_blocks_pt const blocks_allocated) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_cp_mallocator_global_statistics_get_blocks_dealocated(mk_lib_iip_cp_mallocator_global_blocks_pt const blocks_deallocated) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_cp_mallocator_global_statistics_get_blocks_peak(mk_lib_iip_cp_mallocator_global_blocks_pt const blocks_peak) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_cp_mallocator_global_statistics_get_blocks_live(mk_lib_iip_cp_mallocator_global_blocks_pt const blocks_live) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_cp_mallocator_global_statistics_get_bytes_allocated(mk_lib_iip_cp_mallocator_global_bytes_pt const bytes_allocated) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_cp_mallocator_global_statistics_get_bytes_dealocated(mk_lib_iip_cp_mallocator_global_bytes_pt const bytes_deallocated) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_cp_mallocator_global_statistics_get_bytes_peak(mk_lib_iip_cp_mallocator_global_bytes_pt const bytes_peak) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_cp_mallocator_global_statistics_get_bytes_live(mk_lib_iip_cp_mallocator_global_bytes_pt const bytes_live) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_iip_cp_mallocator_global_statistics_get_all(mk_lang_static_param(mk_lib_iip_cp_mallocator_global_blocks_t, blocks_all, 4), mk_lang_static_param(mk_lib_iip_cp_mallocator_global_bytes_t, bytes_all, 4)) mk_lang_noexcept;


#if mk_lang_jumbo_have
#include "mk_lib_iip_cp_mallocator_global.c"
#endif
#endif
