#ifndef mk_include_guard_mk_lib_iip_any_data_connections_h
#define mk_include_guard_mk_lib_iip_any_data_connections_h


#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_types.h"
#include "mk_lib_iip_any_data_connection.h"
#include "mk_lib_iip_cp_mallocator_global.h"


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_any_data_connections_elem_rw_construct_void(mk_lib_iip_any_data_connection_ppt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_any_data_connections_elem_rw_destroy(mk_lib_iip_any_data_connection_ppt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_any_data_connections_elem_rw_construct_copy(mk_lib_iip_any_data_connection_ppt const dst, mk_lib_iip_any_data_connection_pcpt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_any_data_connections_elem_rw_construct_move(mk_lib_iip_any_data_connection_ppt const dst, mk_lib_iip_any_data_connection_ppt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_any_data_connections_elem_rw_assign_copy(mk_lib_iip_any_data_connection_ppt const dst, mk_lib_iip_any_data_connection_pcpt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_any_data_connections_elem_rw_assign_move(mk_lib_iip_any_data_connection_ppt const dst, mk_lib_iip_any_data_connection_ppt const src) mk_lang_noexcept;


#define mk_sl_vector_t_name mk_lib_iip_any_data_connections
#define mk_sl_vector_t_element_type mk_lib_iip_any_data_connection_pt
#define mk_sl_vector_t_mallocatorg mk_lib_iip_cp_mallocator_global
#define mk_sl_vector_t_element_construct_void mk_lib_iip_any_data_connections_elem_rw_construct_void
#define mk_sl_vector_t_element_destruct mk_lib_iip_any_data_connections_elem_rw_destroy
#define mk_sl_vector_t_element_copy_construct mk_lib_iip_any_data_connections_elem_rw_construct_copy
#define mk_sl_vector_t_element_move_construct mk_lib_iip_any_data_connections_elem_rw_construct_move
#define mk_sl_vector_t_element_copy_assign mk_lib_iip_any_data_connections_elem_rw_assign_copy
#define mk_sl_vector_t_element_move_assign mk_lib_iip_any_data_connections_elem_rw_assign_move
#include "mk_sl_vector_inl_fileh.h"
#include "mk_sl_vector_inl_fileu.h"


#if mk_lang_jumbo_have
#include "mk_lib_iip_any_data_connections.c"
#endif
#endif
