include(`mk_lang_typedef.m')dnl
#include "mk_lang_concat.h"


#if \
(!( \
	(defined mk_lib_crypto_mode_ctr_t_name) && \
	(defined mk_lib_crypto_mode_ctr_t_base_name) && \
1))
#error xxxxxxxxxx
#endif


#define mk_lib_crypto_mode_ctr_inl_defd_name mk_lib_crypto_mode_ctr_t_name
#define mk_lib_crypto_mode_ctr_inl_defd_base_name mk_lib_crypto_mode_ctr_t_base_name





#define mk_lib_crypto_mode_ctr_inl_defd_base_msg_len_d (mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_base_name, _msg_len_d))
#define mk_lib_crypto_mode_ctr_inl_defd_base_key_len_d (mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_base_name, _key_len_d))
#define mk_lib_crypto_mode_ctr_inl_defd_base_schedule_len_d (mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_base_name, _schedule_len_d))

#define mk_lib_crypto_mode_ctr_inl_defd_base_msg_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_base_name, _msg_t)
#define mk_lib_crypto_mode_ctr_inl_defd_base_key_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_base_name, _key_t)
#define mk_lib_crypto_mode_ctr_inl_defd_base_schedule_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_base_name, _schedule_t)

#define mk_lib_crypto_mode_ctr_inl_defd_base_expand_enc mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_base_name, _expand_enc)
#define mk_lib_crypto_mode_ctr_inl_defd_base_expand_dec mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_base_name, _expand_dec)
#define mk_lib_crypto_mode_ctr_inl_defd_base_schedule_encrypt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_base_name, _schedule_encrypt)
#define mk_lib_crypto_mode_ctr_inl_defd_base_schedule_decrypt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_base_name, _schedule_decrypt)





#if mk_lib_crypto_mode_ctr_inl_defd_base_msg_len_d == 16
#define mk_lib_crypto_mode_ctr_inl_defd_xor_2 mk_sl_cui_uint_more_16_xor2
#define mk_lib_crypto_mode_ctr_inl_defd_xor_3 mk_sl_cui_uint_more_16_xor3
#else
#error xxxxxxxxxx
#endif





#define mk_lib_crypto_mode_ctr_inl_defd_iv_len_d mk_lib_crypto_mode_ctr_inl_defd_base_msg_len_d
#define mk_lib_crypto_mode_ctr_inl_defd_iv_len_e mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _iv_len_e)
#define mk_lib_crypto_mode_ctr_inl_defd_iv_len_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _iv_len_t)
#define mk_lib_crypto_mode_ctr_inl_defd_iv_len_v mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _iv_len_v)
#define mk_lib_crypto_mode_ctr_inl_defd_iv_data_u mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _iv_data_u)
#define mk_lib_crypto_mode_ctr_inl_defd_iv_data_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _iv_data_t)
#define mk_lib_crypto_mode_ctr_inl_defd_iv mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _iv)
#define mk_lib_crypto_mode_ctr_inl_defd_iv_s mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_iv, _s)
#define mk_lib_crypto_mode_ctr_inl_defd_iv_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_iv, _t)
mm_per_typedef2(`mk_lib_crypto_mode_ctr_inl_defd_iv')dnl

#define mk_lib_crypto_mode_ctr_inl_defd_msg_len_d mk_lib_crypto_mode_ctr_inl_defd_base_msg_len_d
#define mk_lib_crypto_mode_ctr_inl_defd_msg_len_e mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _msg_len_e)
#define mk_lib_crypto_mode_ctr_inl_defd_msg_len_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _msg_len_t)
#define mk_lib_crypto_mode_ctr_inl_defd_msg_len_v mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _msg_len_v)
#define mk_lib_crypto_mode_ctr_inl_defd_msg_data_u mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _msg_data_u)
#define mk_lib_crypto_mode_ctr_inl_defd_msg_data_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _msg_data_t)
#define mk_lib_crypto_mode_ctr_inl_defd_msg mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _msg)
#define mk_lib_crypto_mode_ctr_inl_defd_msg_s mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_msg, _s)
#define mk_lib_crypto_mode_ctr_inl_defd_msg_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_msg, _t)
mm_per_typedef2(`mk_lib_crypto_mode_ctr_inl_defd_msg')dnl

#define mk_lib_crypto_mode_ctr_inl_defd_key_len_d mk_lib_crypto_mode_ctr_inl_defd_base_key_len_d
#define mk_lib_crypto_mode_ctr_inl_defd_key_len_e mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _key_len_e)
#define mk_lib_crypto_mode_ctr_inl_defd_key_len_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _key_len_t)
#define mk_lib_crypto_mode_ctr_inl_defd_key_len_v mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _key_len_v)
#define mk_lib_crypto_mode_ctr_inl_defd_key_data_u mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _key_data_u)
#define mk_lib_crypto_mode_ctr_inl_defd_key_data_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _key_data_t)
#define mk_lib_crypto_mode_ctr_inl_defd_key mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _key)
#define mk_lib_crypto_mode_ctr_inl_defd_key_s mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_key, _s)
#define mk_lib_crypto_mode_ctr_inl_defd_key_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_key, _t)
mm_per_typedef2(`mk_lib_crypto_mode_ctr_inl_defd_key')dnl

#define mk_lib_crypto_mode_ctr_inl_defd_schedule_len_d mk_lib_crypto_mode_ctr_inl_defd_base_schedule_len_d
#define mk_lib_crypto_mode_ctr_inl_defd_schedule_len_e mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _schedule_len_e)
#define mk_lib_crypto_mode_ctr_inl_defd_schedule_len_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _schedule_len_t)
#define mk_lib_crypto_mode_ctr_inl_defd_schedule_len_v mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _schedule_len_v)
#define mk_lib_crypto_mode_ctr_inl_defd_schedule_data_u mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _schedule_data_u)
#define mk_lib_crypto_mode_ctr_inl_defd_schedule_data_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _schedule_data_t)
#define mk_lib_crypto_mode_ctr_inl_defd_schedule mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _schedule)
#define mk_lib_crypto_mode_ctr_inl_defd_schedule_s mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_schedule, _s)
#define mk_lib_crypto_mode_ctr_inl_defd_schedule_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_schedule, _t)
mm_per_typedef2(`mk_lib_crypto_mode_ctr_inl_defd_schedule')dnl

#define mk_lib_crypto_mode_ctr_inl_defd_alg mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _alg)
#define mk_lib_crypto_mode_ctr_inl_defd_alg_s mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_alg, _s)
#define mk_lib_crypto_mode_ctr_inl_defd_alg_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_alg, _t)
mm_per_typedef2(`mk_lib_crypto_mode_ctr_inl_defd_alg')dnl

#define mk_lib_crypto_mode_ctr_inl_defd_counter mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _counter)
#define mk_lib_crypto_mode_ctr_inl_defd_counter_s mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _counter_s)
#define mk_lib_crypto_mode_ctr_inl_defd_counter_t mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _counter_t)
mm_per_typedef2(`mk_lib_crypto_mode_ctr_inl_defd_counter')dnl
#define mk_lib_crypto_mode_ctr_inl_defd_counter_from_buis_uchar_be mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _counter_from_buis_uchar_be)
#define mk_lib_crypto_mode_ctr_inl_defd_counter_to_buis_uchar_be mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _counter_to_buis_uchar_be)
#define mk_lib_crypto_mode_ctr_inl_defd_counter_inc1 mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _counter_inc1)
#define mk_lib_crypto_mode_ctr_inl_defd_counter_from_uint8s_be mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _counter_from_uint8s_be)
#define mk_lib_crypto_mode_ctr_inl_defd_counter_to_uint8s_be mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _counter_to_uint8s_be)
#define mk_lib_crypto_mode_ctr_inl_defd_prrw_increment mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _prrw_increment)

#define mk_lib_crypto_mode_ctr_inl_defd_prrw_set_key mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _prrw_set_key)
#define mk_lib_crypto_mode_ctr_inl_defd_prrw_crypt_do_constexpr mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _prrw_crypt_do_constexpr)
#define mk_lib_crypto_mode_ctr_inl_defd_prrw_crypt_no_constexpr mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _prrw_crypt_no_constexpr)
#define mk_lib_crypto_mode_ctr_inl_defd_prrw_crypt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _prrw_crypt)

#define mk_lib_crypto_mode_ctr_inl_defd_n1_alg_pt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n1_alg_pt)
#define mk_lib_crypto_mode_ctr_inl_defd_n2_alg_pt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n2_alg_pt)
#define mk_lib_crypto_mode_ctr_inl_defd_n4_alg_pt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n4_alg_pt)
#define mk_lib_crypto_mode_ctr_inl_defd_n8_alg_pt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n8_alg_pt)
#define mk_lib_crypto_mode_ctr_inl_defd_n16_alg_pt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n16_alg_pt)
#define mk_lib_crypto_mode_ctr_inl_defd_n32_alg_pt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n32_alg_pt)
#define mk_lib_crypto_mode_ctr_inl_defd_n64_alg_pt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n64_alg_pt)

#define mk_lib_crypto_mode_ctr_inl_defd_n1_msg_pt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n1_msg_pt)
#define mk_lib_crypto_mode_ctr_inl_defd_n2_msg_pt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n2_msg_pt)
#define mk_lib_crypto_mode_ctr_inl_defd_n4_msg_pt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n4_msg_pt)
#define mk_lib_crypto_mode_ctr_inl_defd_n8_msg_pt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n8_msg_pt)
#define mk_lib_crypto_mode_ctr_inl_defd_n16_msg_pt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n16_msg_pt)
#define mk_lib_crypto_mode_ctr_inl_defd_n32_msg_pt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n32_msg_pt)
#define mk_lib_crypto_mode_ctr_inl_defd_n64_msg_pt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n64_msg_pt)

#define mk_lib_crypto_mode_ctr_inl_defd_n1_msg_pct mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n1_msg_pct)
#define mk_lib_crypto_mode_ctr_inl_defd_n2_msg_pct mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n2_msg_pct)
#define mk_lib_crypto_mode_ctr_inl_defd_n4_msg_pct mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n4_msg_pct)
#define mk_lib_crypto_mode_ctr_inl_defd_n8_msg_pct mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n8_msg_pct)
#define mk_lib_crypto_mode_ctr_inl_defd_n16_msg_pct mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n16_msg_pct)
#define mk_lib_crypto_mode_ctr_inl_defd_n32_msg_pct mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n32_msg_pct)
#define mk_lib_crypto_mode_ctr_inl_defd_n64_msg_pct mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n64_msg_pct)

#define mk_lib_crypto_mode_ctr_inl_defd_rw_crypt_n1 mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n1_rw_crypt)
#define mk_lib_crypto_mode_ctr_inl_defd_rw_crypt_n2 mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n2_rw_crypt)
#define mk_lib_crypto_mode_ctr_inl_defd_rw_crypt_n4 mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n4_rw_crypt)
#define mk_lib_crypto_mode_ctr_inl_defd_rw_crypt_n8 mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n8_rw_crypt)
#define mk_lib_crypto_mode_ctr_inl_defd_rw_crypt_n16 mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n16_rw_crypt)
#define mk_lib_crypto_mode_ctr_inl_defd_rw_crypt_n32 mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n32_rw_crypt)
#define mk_lib_crypto_mode_ctr_inl_defd_rw_crypt_n64 mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _n64_rw_crypt)

#define mk_lib_crypto_mode_ctr_inl_defd_rw_set_iv mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _rw_set_iv)
#define mk_lib_crypto_mode_ctr_inl_defd_rw_set_key_enc mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _rw_set_key_enc)
#define mk_lib_crypto_mode_ctr_inl_defd_rw_set_key_dec mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _rw_set_key_dec)
#define mk_lib_crypto_mode_ctr_inl_defd_rw_encrypt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _rw_encrypt)
#define mk_lib_crypto_mode_ctr_inl_defd_rw_decrypt mk_lang_concat(mk_lib_crypto_mode_ctr_inl_defd_name, _rw_decrypt)
