#include "mk_lang_concat.h"


#if(!( \
	(defined mk_lib_crypto_kdf_pbkdf2_t_name) && \
1))
#error xxxxxxxxxx
#endif


#define mk_lib_crypto_kdf_pbkdf2_inl_defd_name mk_lib_crypto_kdf_pbkdf2_t_name


#define mk_lib_crypto_kdf_pbkdf2_inl_defd_base_hmac_prefix mk_lang_concat(mk_lib_crypto_mac_hmac_, mk_lib_crypto_kdf_pbkdf2_inl_defd_name)

#define mk_lib_crypto_kdf_pbkdf2_inl_defd_base_digest_len_v mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_base_hmac_prefix, _digest_len_v)

#define mk_lib_crypto_kdf_pbkdf2_inl_defd_base_digest_t mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_base_hmac_prefix, _digest_t)
#define mk_lib_crypto_kdf_pbkdf2_inl_defd_base_digest_ct mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_base_hmac_prefix, _digest_ct)
#define mk_lib_crypto_kdf_pbkdf2_inl_defd_base_digest_pt mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_base_hmac_prefix, _digest_pt)
#define mk_lib_crypto_kdf_pbkdf2_inl_defd_base_digest_pct mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_base_hmac_prefix, _digest_pct)

#define mk_lib_crypto_kdf_pbkdf2_inl_defd_base_t mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_base_hmac_prefix, _t)
#define mk_lib_crypto_kdf_pbkdf2_inl_defd_base_ct mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_base_hmac_prefix, _ct)
#define mk_lib_crypto_kdf_pbkdf2_inl_defd_base_pt mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_base_hmac_prefix, _pt)
#define mk_lib_crypto_kdf_pbkdf2_inl_defd_base_pct mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_base_hmac_prefix, _pct)

#define mk_lib_crypto_kdf_pbkdf2_inl_defd_base_init mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_base_hmac_prefix, _init)
#define mk_lib_crypto_kdf_pbkdf2_inl_defd_base_append mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_base_hmac_prefix, _append)
#define mk_lib_crypto_kdf_pbkdf2_inl_defd_base_finish mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_base_hmac_prefix, _finish)


#define mk_lib_crypto_kdf_pbkdf2_inl_defd_prefix mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_, mk_lib_crypto_kdf_pbkdf2_inl_defd_name)

#define mk_lib_crypto_kdf_pbkdf2_inl_defd_convert_data_u mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_prefix, _convert_data_u)
#define mk_lib_crypto_kdf_pbkdf2_inl_defd_convert_data_t mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_prefix, _convert_data_t)
#define mk_lib_crypto_kdf_pbkdf2_inl_defd_convert_s mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_prefix, _convert_s)
#define mk_lib_crypto_kdf_pbkdf2_inl_defd_convert_t mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_prefix, _convert_t)

#define mk_lib_crypto_kdf_pbkdf2_inl_defd_fn mk_lang_concat(mk_lib_crypto_kdf_pbkdf2_inl_defd_prefix, _fn)
