#ifndef mk_include_guard_mk_lib_iip_cp_client_wrapper_h
#define mk_include_guard_mk_lib_iip_cp_client_wrapper_h


#include "mk_lang_bui.h"
#include "mk_lang_charbit.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"
#include "mk_lib_iip_cp_client_types.h"
#include "mk_lib_iip_cp_mallocator_global.h"


enum mk_lib_iip_cp_client_wrapper_task_result_e
{
	mk_lib_iip_cp_client_wrapper_task_result_e_did_something,
	mk_lib_iip_cp_client_wrapper_task_result_e_would_block,
	mk_lib_iip_cp_client_wrapper_task_result_e_did_nothing,
	mk_lib_iip_cp_client_wrapper_task_result_e_dummy_end
};
typedef enum mk_lib_iip_cp_client_wrapper_task_result_e mk_lib_iip_cp_client_wrapper_task_result_t;
mk_lang_typedef(mk_lib_iip_cp_client_wrapper_task_result);

struct mk_lib_iip_cp_client_wrapper_task_s
{
	mk_lib_iip_cp_client_types_handle_wrapper_t m_wrapper;
};
typedef struct mk_lib_iip_cp_client_wrapper_task_s mk_lib_iip_cp_client_wrapper_task_t;
mk_lang_typedef(mk_lib_iip_cp_client_wrapper_task);


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_rw_construct(mk_lib_iip_cp_client_wrapper_task_pt const task, mk_lib_iip_cp_client_types_application_settings_pct const settings) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_rw_destroy(mk_lib_iip_cp_client_wrapper_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_rw_new_connection(mk_lib_iip_cp_client_wrapper_task_pt const task, mk_lib_iip_cp_client_types_connection_settings_pct const settings, mk_lib_iip_cp_client_types_handle_connection_pt const connection) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_rw_new_session(mk_lib_iip_cp_client_wrapper_task_pt const task, mk_lib_iip_cp_client_types_session_settings_pct const settings, mk_lib_iip_cp_client_types_handle_session_pt const session) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_rw_step(mk_lib_iip_cp_client_wrapper_task_pt const task, mk_lang_types_bool_t const allow_to_block, mk_lib_iip_cp_client_wrapper_task_result_pt const step_result) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_rw_run_block(mk_lib_iip_cp_client_wrapper_task_pt const task) mk_lang_noexcept;


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_val_rw_construct_void(mk_lib_iip_cp_client_wrapper_task_pt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_val_rw_destroy(mk_lib_iip_cp_client_wrapper_task_pt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_val_rw_construct_copy(mk_lib_iip_cp_client_wrapper_task_pt const dst, mk_lib_iip_cp_client_wrapper_task_pct const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_val_rw_construct_move(mk_lib_iip_cp_client_wrapper_task_pt const dst, mk_lib_iip_cp_client_wrapper_task_pt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_val_rw_assign_copy(mk_lib_iip_cp_client_wrapper_task_pt const dst, mk_lib_iip_cp_client_wrapper_task_pct const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_val_rw_assign_move(mk_lib_iip_cp_client_wrapper_task_pt const dst, mk_lib_iip_cp_client_wrapper_task_pt const src) mk_lang_noexcept;

#define mk_sl_vector_t_name mk_lib_iip_cp_client_wrapper_tasks
#define mk_sl_vector_t_element_type mk_lib_iip_cp_client_wrapper_task_t
#define mk_sl_vector_t_mallocatorg mk_lib_iip_cp_mallocator_global
#define mk_sl_vector_t_element_construct_void mk_lib_iip_cp_client_wrapper_task_val_rw_construct_void
#define mk_sl_vector_t_element_destruct mk_lib_iip_cp_client_wrapper_task_val_rw_destroy
#define mk_sl_vector_t_element_copy_construct mk_lib_iip_cp_client_wrapper_task_val_rw_construct_copy
#define mk_sl_vector_t_element_move_construct mk_lib_iip_cp_client_wrapper_task_val_rw_construct_move
#define mk_sl_vector_t_element_copy_assign mk_lib_iip_cp_client_wrapper_task_val_rw_assign_copy
#define mk_sl_vector_t_element_move_assign mk_lib_iip_cp_client_wrapper_task_val_rw_assign_move
#include "mk_sl_vector_inl_fileh.h"
#include "mk_sl_vector_inl_fileu.h"


#if mk_lang_jumbo_have
#include "mk_lib_iip_cp_client_wrapper.c"
#endif
#endif
