include(`mk_lib_crypto_mode_stream.m')dnl
#ifndef mk_include_guard_mk_lib_crypto_mode_stream_any3_h
#define mk_include_guard_mk_lib_crypto_mode_stream_any3_h

#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"


mk_lang_forward(mk_sl_cui_uint8);


struct mk_lib_crypto_mode_stream_any1_bigid_s; typedef struct mk_lib_crypto_mode_stream_any1_bigid_s mk_lib_crypto_mode_stream_any1_bigid_t; typedef mk_lib_crypto_mode_stream_any1_bigid_t* mk_lib_crypto_mode_stream_any1_bigid_pt;
define(`mk_lib_crypto_mode_stream_any3_h_mm_unions', `dnl
struct mk_lib_crypto_mode_stream_any2_$1_$2_s; typedef struct mk_lib_crypto_mode_stream_any2_$1_$2_s mk_lib_crypto_mode_stream_any2_$1_$2_t; typedef mk_lib_crypto_mode_stream_any2_$1_$2_t* mk_lib_crypto_mode_stream_any2_$1_$2_pt;
')`'dnl
mk_lib_crypto_mode_stream_mm_recurse(`mk_lib_crypto_mode_stream_any3_h_mm_unions', mk_lib_crypto_mode_stream_mm_list())dnl


enum mk_lib_crypto_mode_stream_any3_id_e
{
define(`mk_lib_crypto_mode_stream_any3_h_mm_enum', `dnl
	mk_lib_crypto_mode_stream_any3_id_e_$1_$2,
')`'dnl
mk_lib_crypto_mode_stream_mm_recurse(`mk_lib_crypto_mode_stream_any3_h_mm_enum', mk_lib_crypto_mode_stream_mm_list())dnl
	mk_lib_crypto_mode_stream_any3_id_e_dummy_end
};
typedef enum mk_lib_crypto_mode_stream_any3_id_e mk_lib_crypto_mode_stream_any3_id_t;
mk_lang_typedef(mk_lib_crypto_mode_stream_any3_id);

#define mk_lib_crypto_mode_stream_any3_max_iv_len_guess_d 16
#define mk_lib_crypto_mode_stream_any3_max_key_len_guess_d 32
#define mk_lib_crypto_mode_stream_any3_max_msg_len_guess_d 16
enum mk_lib_crypto_mode_stream_any3_max_iv_len_guess_e{mk_lib_crypto_mode_stream_any3_max_iv_len_guess_v = mk_lib_crypto_mode_stream_any3_max_iv_len_guess_d}; typedef enum mk_lib_crypto_mode_stream_any3_max_iv_len_guess_e mk_lib_crypto_mode_stream_any3_max_iv_len_guess_t;
enum mk_lib_crypto_mode_stream_any3_max_key_len_guess_e{mk_lib_crypto_mode_stream_any3_max_key_len_guess_v = mk_lib_crypto_mode_stream_any3_max_key_len_guess_d}; typedef enum mk_lib_crypto_mode_stream_any3_max_key_len_guess_e mk_lib_crypto_mode_stream_any3_max_key_len_guess_t;
enum mk_lib_crypto_mode_stream_any3_max_msg_len_guess_e{mk_lib_crypto_mode_stream_any3_max_msg_len_guess_v = mk_lib_crypto_mode_stream_any3_max_msg_len_guess_d}; typedef enum mk_lib_crypto_mode_stream_any3_max_msg_len_guess_e mk_lib_crypto_mode_stream_any3_max_msg_len_guess_t;


union mk_lib_crypto_mode_stream_any3_data_u
{
	mk_lib_crypto_mode_stream_any1_bigid_pt m_id;
define(`mk_lib_crypto_mode_stream_any3_h_mm_pointers', `dnl
	mk_lib_crypto_mode_stream_any2_$1_$2_pt m_$1_$2;
')`'dnl
mk_lib_crypto_mode_stream_mm_recurse(`mk_lib_crypto_mode_stream_any3_h_mm_pointers', mk_lib_crypto_mode_stream_mm_list())dnl
};
typedef union mk_lib_crypto_mode_stream_any3_data_u mk_lib_crypto_mode_stream_any3_data_t;
struct mk_lib_crypto_mode_stream_any3_s
{
	mk_lib_crypto_mode_stream_any3_data_t m_data;
};
typedef struct mk_lib_crypto_mode_stream_any3_s mk_lib_crypto_mode_stream_any3_t;
mk_lang_typedef(mk_lib_crypto_mode_stream_any3);


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_crypto_mode_stream_any3_st_get_max_iv_len(mk_lang_types_void_t) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_crypto_mode_stream_any3_st_get_max_key_len(mk_lang_types_void_t) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_crypto_mode_stream_any3_st_get_max_msg_len(mk_lang_types_void_t) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_crypto_mode_stream_any3_rw_construct_void(mk_lib_crypto_mode_stream_any3_pt const any3) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_crypto_mode_stream_any3_rw_construct_type(mk_lib_crypto_mode_stream_any3_pt const any3, mk_lib_crypto_mode_stream_any3_id_t const id) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_crypto_mode_stream_any3_rw_destroy(mk_lib_crypto_mode_stream_any3_pt const any3) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_crypto_mode_stream_any3_rw_reconstruct_void(mk_lib_crypto_mode_stream_any3_pt const any3) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_crypto_mode_stream_any3_rw_reconstruct_type(mk_lib_crypto_mode_stream_any3_pt const any3, mk_lib_crypto_mode_stream_any3_id_t const id) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_crypto_mode_stream_any3_ro_get_iv_len(mk_lib_crypto_mode_stream_any3_pct const any3) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_crypto_mode_stream_any3_ro_get_key_len(mk_lib_crypto_mode_stream_any3_pct const any3) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_crypto_mode_stream_any3_ro_get_msg_len(mk_lib_crypto_mode_stream_any3_pct const any3) mk_lang_noexcept;

mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_mode_stream_any3_rw_set_iv(mk_lib_crypto_mode_stream_any3_pt const any3, mk_sl_cui_uint8_pct const iv_buf, mk_lang_types_sint_t const iv_len) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_mode_stream_any3_rw_set_key_enc(mk_lib_crypto_mode_stream_any3_pt const any3, mk_sl_cui_uint8_pct const key_buf, mk_lang_types_sint_t const key_len) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_mode_stream_any3_rw_set_key_dec(mk_lib_crypto_mode_stream_any3_pt const any3, mk_sl_cui_uint8_pct const key_buf, mk_lang_types_sint_t const key_len) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_mode_stream_any3_rw_encrypt(mk_lib_crypto_mode_stream_any3_pt const any3, mk_sl_cui_uint8_pct const input_buf, mk_lang_types_usize_t const input_len, mk_sl_cui_uint8_pt const output_buf, mk_lang_types_usize_t const output_len, mk_lang_types_usize_pt const output_used) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_mode_stream_any3_rw_decrypt(mk_lib_crypto_mode_stream_any3_pt const any3, mk_sl_cui_uint8_pct const input_buf, mk_lang_types_usize_t const input_len, mk_sl_cui_uint8_pt const output_buf, mk_lang_types_usize_t const output_len, mk_lang_types_usize_pt const output_used) mk_lang_noexcept;


#if mk_lang_jumbo_have
#include "mk_lib_crypto_mode_stream_any3.c"
#endif
#endif
