#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_static_param.h"
#include "mk_lang_types.h"


#include "mk_lib_crypto_bitops_bulk_inl_defd.h"


typedef mk_lib_crypto_bitops_bulk_inl_defd_base_t mk_lib_crypto_bitops_bulk_inl_defd_t;
typedef mk_lib_crypto_bitops_bulk_inl_defd_t const mk_lib_crypto_bitops_bulk_inl_defd_ct;
typedef mk_lib_crypto_bitops_bulk_inl_defd_t* mk_lib_crypto_bitops_bulk_inl_defd_pt;
typedef mk_lib_crypto_bitops_bulk_inl_defd_t const* mk_lib_crypto_bitops_bulk_inl_defd_pct;


mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_bitops_bulk_inl_defd_memcpy(mk_lang_static_param(mk_lib_crypto_bitops_bulk_inl_defd_t, dst, mk_lib_crypto_bitops_bulk_inl_defd_count), mk_lang_static_param(mk_lib_crypto_bitops_bulk_inl_defd_ct, src, mk_lib_crypto_bitops_bulk_inl_defd_count)) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_bitops_bulk_inl_defd_memclr(mk_lang_static_param(mk_lib_crypto_bitops_bulk_inl_defd_t, x, mk_lib_crypto_bitops_bulk_inl_defd_count)) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_bitops_bulk_inl_defd_xor2(mk_lang_static_param(mk_lib_crypto_bitops_bulk_inl_defd_t, a, mk_lib_crypto_bitops_bulk_inl_defd_count), mk_lang_static_param(mk_lib_crypto_bitops_bulk_inl_defd_ct, b, mk_lib_crypto_bitops_bulk_inl_defd_count)) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_bitops_bulk_inl_defd_xor3(mk_lang_static_param(mk_lib_crypto_bitops_bulk_inl_defd_ct, a, mk_lib_crypto_bitops_bulk_inl_defd_count), mk_lang_static_param(mk_lib_crypto_bitops_bulk_inl_defd_ct, b, mk_lib_crypto_bitops_bulk_inl_defd_count), mk_lang_static_param(mk_lib_crypto_bitops_bulk_inl_defd_t, c, mk_lib_crypto_bitops_bulk_inl_defd_count)) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_bitops_bulk_inl_defd_add2_wrap_cid_cod(mk_lang_static_param(mk_lib_crypto_bitops_bulk_inl_defd_t, a, mk_lib_crypto_bitops_bulk_inl_defd_count), mk_lang_static_param(mk_lib_crypto_bitops_bulk_inl_defd_ct, b, mk_lib_crypto_bitops_bulk_inl_defd_count)) mk_lang_noexcept;


#include "mk_lib_crypto_bitops_bulk_inl_defu.h"
