include(`mk_lang_typedef.m')dnl













#undef mk_lib_crypto_mode_ctr_n_inl_defd_name
#undef mk_lib_crypto_mode_ctr_n_inl_defd_base_name
#undef mk_lib_crypto_mode_ctr_n_inl_defd_count





#undef mk_lib_crypto_mode_ctr_n_inl_defd_base_msg_len_d
#undef mk_lib_crypto_mode_ctr_n_inl_defd_base_key_len_d
#undef mk_lib_crypto_mode_ctr_n_inl_defd_base_schedule_len_d

#undef mk_lib_crypto_mode_ctr_n_inl_defd_base_msg_t
#undef mk_lib_crypto_mode_ctr_n_inl_defd_base_msg_pt
#undef mk_lib_crypto_mode_ctr_n_inl_defd_base_msg_pct
#undef mk_lib_crypto_mode_ctr_n_inl_defd_base_key_t
#undef mk_lib_crypto_mode_ctr_n_inl_defd_base_schedule_t

#undef mk_lib_crypto_mode_ctr_n_inl_defd_base_expand_enc
#undef mk_lib_crypto_mode_ctr_n_inl_defd_base_expand_dec
#undef mk_lib_crypto_mode_ctr_n_inl_defd_base_schedule_encrypt
#undef mk_lib_crypto_mode_ctr_n_inl_defd_base_schedule_decrypt






#undef mk_lib_crypto_mode_ctr_n_inl_defd_xor_2
#undef mk_lib_crypto_mode_ctr_n_inl_defd_xor_3








#undef mk_lib_crypto_mode_ctr_n_inl_defd_iv_len_d
#undef mk_lib_crypto_mode_ctr_n_inl_defd_iv_len_e
#undef mk_lib_crypto_mode_ctr_n_inl_defd_iv_len_t
#undef mk_lib_crypto_mode_ctr_n_inl_defd_iv_len_v
#undef mk_lib_crypto_mode_ctr_n_inl_defd_iv_data_u
#undef mk_lib_crypto_mode_ctr_n_inl_defd_iv_data_t
#undef mk_lib_crypto_mode_ctr_n_inl_defd_iv
#undef mk_lib_crypto_mode_ctr_n_inl_defd_iv_s
#undef mk_lib_crypto_mode_ctr_n_inl_defd_iv_t
mm_per_typedef_undef(`mk_lib_crypto_mode_ctr_n_inl_defd_iv')dnl

#undef mk_lib_crypto_mode_ctr_n_inl_defd_msg_len_d
#undef mk_lib_crypto_mode_ctr_n_inl_defd_msg_len_e
#undef mk_lib_crypto_mode_ctr_n_inl_defd_msg_len_t
#undef mk_lib_crypto_mode_ctr_n_inl_defd_msg_len_v
#undef mk_lib_crypto_mode_ctr_n_inl_defd_msg_data_u
#undef mk_lib_crypto_mode_ctr_n_inl_defd_msg_data_t
#undef mk_lib_crypto_mode_ctr_n_inl_defd_msg
#undef mk_lib_crypto_mode_ctr_n_inl_defd_msg_s
#undef mk_lib_crypto_mode_ctr_n_inl_defd_msg_t
mm_per_typedef_undef(`mk_lib_crypto_mode_ctr_n_inl_defd_msg')dnl

#undef mk_lib_crypto_mode_ctr_n_inl_defd_key_len_d
#undef mk_lib_crypto_mode_ctr_n_inl_defd_key_len_e
#undef mk_lib_crypto_mode_ctr_n_inl_defd_key_len_t
#undef mk_lib_crypto_mode_ctr_n_inl_defd_key_len_v
#undef mk_lib_crypto_mode_ctr_n_inl_defd_key_data_u
#undef mk_lib_crypto_mode_ctr_n_inl_defd_key_data_t
#undef mk_lib_crypto_mode_ctr_n_inl_defd_key
#undef mk_lib_crypto_mode_ctr_n_inl_defd_key_s
#undef mk_lib_crypto_mode_ctr_n_inl_defd_key_t
mm_per_typedef_undef(`mk_lib_crypto_mode_ctr_n_inl_defd_key')dnl

#undef mk_lib_crypto_mode_ctr_n_inl_defd_schedule_len_d
#undef mk_lib_crypto_mode_ctr_n_inl_defd_schedule_len_e
#undef mk_lib_crypto_mode_ctr_n_inl_defd_schedule_len_t
#undef mk_lib_crypto_mode_ctr_n_inl_defd_schedule_len_v
#undef mk_lib_crypto_mode_ctr_n_inl_defd_schedule_data_u
#undef mk_lib_crypto_mode_ctr_n_inl_defd_schedule_data_t
#undef mk_lib_crypto_mode_ctr_n_inl_defd_schedule
#undef mk_lib_crypto_mode_ctr_n_inl_defd_schedule_s
#undef mk_lib_crypto_mode_ctr_n_inl_defd_schedule_t
mm_per_typedef_undef(`mk_lib_crypto_mode_ctr_n_inl_defd_schedule')dnl

#undef mk_lib_crypto_mode_ctr_n_inl_defd_alg
#undef mk_lib_crypto_mode_ctr_n_inl_defd_alg_s
#undef mk_lib_crypto_mode_ctr_n_inl_defd_alg_t
mm_per_typedef_undef(`mk_lib_crypto_mode_ctr_n_inl_defd_alg')dnl

#undef mk_lib_crypto_mode_ctr_n_inl_defd_counter
#undef mk_lib_crypto_mode_ctr_n_inl_defd_counter_s
#undef mk_lib_crypto_mode_ctr_n_inl_defd_counter_t
mm_per_typedef_undef(`mk_lib_crypto_mode_ctr_n_inl_defd_counter')dnl
#undef mk_lib_crypto_mode_ctr_n_inl_defd_counter_from_buis_uchar_be
#undef mk_lib_crypto_mode_ctr_n_inl_defd_counter_to_buis_uchar_be
#undef mk_lib_crypto_mode_ctr_n_inl_defd_counter_inc1
#undef mk_lib_crypto_mode_ctr_n_inl_defd_counter_from_uint8s_be
#undef mk_lib_crypto_mode_ctr_n_inl_defd_counter_to_uint8s_be
#undef mk_lib_crypto_mode_ctr_n_inl_defd_prrw_increment_single
#undef mk_lib_crypto_mode_ctr_n_inl_defd_prrw_increment_all

#undef mk_lib_crypto_mode_ctr_n_inl_defd_prrw_set_key
#undef mk_lib_crypto_mode_ctr_n_inl_defd_prrw_crypt

#undef mk_lib_crypto_mode_ctr_n_inl_defd_rw_set_iv
#undef mk_lib_crypto_mode_ctr_n_inl_defd_rw_set_key_enc
#undef mk_lib_crypto_mode_ctr_n_inl_defd_rw_set_key_dec
#undef mk_lib_crypto_mode_ctr_n_inl_defd_rw_crypt
#undef mk_lib_crypto_mode_ctr_n_inl_defd_rw_encrypt
#undef mk_lib_crypto_mode_ctr_n_inl_defd_rw_decrypt
