#ifndef mk_include_guard_mk_lib_iip_cp_client_wrapper_h
#define mk_include_guard_mk_lib_iip_cp_client_wrapper_h


#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"
#include "mk_lib_iip_cp_client_types.h"


enum mk_lib_iip_cp_client_wrapper_task_result_e
{
	mk_lib_iip_cp_client_wrapper_task_result_e_did_something,
	mk_lib_iip_cp_client_wrapper_task_result_e_would_block,
	mk_lib_iip_cp_client_wrapper_task_result_e_timed_out,
	mk_lib_iip_cp_client_wrapper_task_result_e_did_nothing,
	mk_lib_iip_cp_client_wrapper_task_result_e_dummy_end
};
typedef enum mk_lib_iip_cp_client_wrapper_task_result_e mk_lib_iip_cp_client_wrapper_task_result_t;
mk_lang_typedef(mk_lib_iip_cp_client_wrapper_task_result);

struct mk_lib_iip_cp_client_wrapper_task_s
{
	mk_lib_iip_cp_client_types_handle_wrapper_t m_wrapper;
};
typedef struct mk_lib_iip_cp_client_wrapper_task_s mk_lib_iip_cp_client_wrapper_task_t;
mk_lang_typedef(mk_lib_iip_cp_client_wrapper_task);


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_rw_construct(mk_lib_iip_cp_client_wrapper_task_pt const task, mk_lib_iip_cp_client_types_application_settings_pct const settings) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_rw_destroy(mk_lib_iip_cp_client_wrapper_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_rw_new_connection(mk_lib_iip_cp_client_wrapper_task_pt const task, mk_lib_iip_cp_client_types_connection_settings_pct const settings, mk_lib_iip_cp_client_types_handle_connection_pt const connection) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_rw_new_session(mk_lib_iip_cp_client_wrapper_task_pt const task, mk_lib_iip_cp_client_types_session_settings_pct const settings, mk_lib_iip_cp_client_types_handle_session_pt const session) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_rw_step(mk_lib_iip_cp_client_wrapper_task_pt const task, mk_lang_types_bool_t const allow_to_block, mk_lang_types_sint_t const tm, mk_lib_iip_cp_client_wrapper_task_result_pt const step_result) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_rw_run_no_block(mk_lib_iip_cp_client_wrapper_task_pt const task, mk_lib_iip_cp_client_wrapper_task_result_pt const result) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_rw_run_do_block(mk_lib_iip_cp_client_wrapper_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_rw_run_block_tm(mk_lib_iip_cp_client_wrapper_task_pt const task, mk_lang_types_sint_t const tm, mk_lib_iip_cp_client_wrapper_task_result_pt const result) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_wrapper_task_rw_request_close(mk_lib_iip_cp_client_wrapper_task_pt const task) mk_lang_noexcept;


#if mk_lang_jumbo_have
#include "mk_lib_iip_cp_client_wrapper.c"
#endif
#endif
