#ifndef mk_include_guard_mk_lib_iip_cp_client_socket_h
#define mk_include_guard_mk_lib_iip_cp_client_socket_h


#include "mk_lang_bui.h"
#include "mk_lang_charbit.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"
#include "mk_lib_iip_buffer.h"
#include "mk_lib_iip_cp_dynamic_ring.h"
#include "mk_lib_iip_cp_mallocator_global.h"
#include "mk_lib_iip_cp_message.h"
#include "mk_lib_iip_cp_types.h"
#include "mk_lib_iip_net_streaming_packet.h"
#include "mk_sl_cui_uint16.h"


mk_lang_forward(mk_lib_iip_cp_client_session_task);
mk_lang_forward(mk_lib_iip_cp_client_shared);
mk_lang_forward(mk_lib_iip_cp_message);


#define mk_sl_cui_t_name mk_lib_iip_cp_client_socket_handle
#define mk_sl_cui_t_base_type_name mk_lang_bui_uintptr
#define mk_sl_cui_t_count 1
#define mk_sl_cui_t_disable_big_div 1
#define mk_sl_cui_t_base_type_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_sl_cui_t_inline 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"
#define mk_lib_iip_cp_client_socket_handle_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_lib_iip_cp_client_socket_handle_size_bytes_d (mk_lang_bui_uintptr_size_bits_d / mk_lang_charbit)

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_socket_packet_with_payload_s
{
	mk_lib_iip_net_streaming_packet_t m_packet;
	mk_lib_iip_buffer_t m_payload;
};
typedef struct mk_lib_iip_cp_client_socket_packet_with_payload_s mk_lib_iip_cp_client_socket_packet_with_payload_t;
mk_lang_typedef(mk_lib_iip_cp_client_socket_packet_with_payload);
#include "mk_lang_warning_msvc_pop.h"
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_packet_with_payload_rw_destroy(mk_lib_iip_cp_client_socket_packet_with_payload_pt const x) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_packet_with_payload_ptr_rw_construct_void(mk_lib_iip_cp_client_socket_packet_with_payload_ppt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_packet_with_payload_ptr_rw_destroy(mk_lib_iip_cp_client_socket_packet_with_payload_ppt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_packet_with_payload_ptr_rw_construct_copy(mk_lib_iip_cp_client_socket_packet_with_payload_ppt const dst, mk_lib_iip_cp_client_socket_packet_with_payload_pcpt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_packet_with_payload_ptr_rw_construct_move(mk_lib_iip_cp_client_socket_packet_with_payload_ppt const dst, mk_lib_iip_cp_client_socket_packet_with_payload_ppt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_packet_with_payload_ptr_rw_assign_copy(mk_lib_iip_cp_client_socket_packet_with_payload_ppt const dst, mk_lib_iip_cp_client_socket_packet_with_payload_pcpt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_packet_with_payload_ptr_rw_assign_move(mk_lib_iip_cp_client_socket_packet_with_payload_ppt const dst, mk_lib_iip_cp_client_socket_packet_with_payload_ppt const src, mk_lang_types_usize_t const count) mk_lang_noexcept;
#define mk_sl_dynamic_ring_t_name mk_lib_iip_cp_client_socket_packets_with_payload
#define mk_sl_dynamic_ring_t_element_type mk_lib_iip_cp_client_socket_packet_with_payload_pt
#define mk_sl_dynamic_ring_t_mallocatorg mk_lib_iip_cp_mallocator_global
#define mk_sl_dynamic_ring_t_element_construct_void mk_lib_iip_cp_client_socket_packet_with_payload_ptr_rw_construct_void
#define mk_sl_dynamic_ring_t_element_destruct mk_lib_iip_cp_client_socket_packet_with_payload_ptr_rw_destroy
#define mk_sl_dynamic_ring_t_element_construct_copy mk_lib_iip_cp_client_socket_packet_with_payload_ptr_rw_construct_copy
#define mk_sl_dynamic_ring_t_element_construct_move mk_lib_iip_cp_client_socket_packet_with_payload_ptr_rw_construct_move
#define mk_sl_dynamic_ring_t_element_assign_copy mk_lib_iip_cp_client_socket_packet_with_payload_ptr_rw_assign_copy
#define mk_sl_dynamic_ring_t_element_assign_move mk_lib_iip_cp_client_socket_packet_with_payload_ptr_rw_assign_move
#include "mk_sl_dynamic_ring_inl_fileh.h"
#include "mk_sl_dynamic_ring_inl_fileu.h"

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_socket_settings_s
{
	mk_lib_iip_cp_client_shared_pt m_shared;
	mk_lib_iip_cp_types_sessionid_pt m_session_id;
	mk_lang_types_bool_t m_is_listener;
	mk_lib_iip_cp_types_destination2_pt m_local_destination;
	mk_sl_cui_uint16_t m_local_port;
	mk_lib_iip_cp_types_remote_destination_t m_remote_destination;
	mk_sl_cui_uint16_t m_remote_port;
};
typedef struct mk_lib_iip_cp_client_socket_settings_s mk_lib_iip_cp_client_socket_settings_t;
mk_lang_typedef(mk_lib_iip_cp_client_socket_settings);
#include "mk_lang_warning_msvc_pop.h"

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_socket_state_s
{
	mk_lang_types_bool_t m_stop_requested;
	mk_lang_types_bool_t m_stop_acknowledged;
	mk_lib_iip_cp_client_socket_packets_with_payload_t m_incoming_packets_a;
	mk_lib_iip_cp_client_socket_packets_with_payload_t m_incoming_packets_b;
	mk_lang_types_bool_t m_waiting_for_syn;
	mk_lang_types_bool_t m_our_syn_sent;
	mk_sl_cui_uint16_t m_local_port;
	mk_sl_cui_uint16_t m_remote_port;
	mk_sl_cui_uint32_t m_local_stream_id;
	mk_sl_cui_uint32_t m_remote_stream_id;
	mk_sl_cui_uint32_t m_local_sequence_number;
	mk_sl_cui_uint32_t m_remote_sequence_number;
	mk_lib_iip_cp_types_remote_destination_t m_remote_destination;
	mk_lang_types_pchar_t m_remote_b32[mk_lang_roundup_div(mk_lib_crypto_hash_block_sha2_256_digest_len_v * 8, 5)];
	mk_lib_iip_cp_dynamic_ring_u8_t m_data_to_sent;
	mk_lib_iip_cp_dynamic_ring_u8_t m_data_received;
	mk_lib_iip_cp_message_t m_msg;
};
typedef struct mk_lib_iip_cp_client_socket_state_s mk_lib_iip_cp_client_socket_state_t;
mk_lang_typedef(mk_lib_iip_cp_client_socket_state);
#include "mk_lang_warning_msvc_pop.h"

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_socket_s
{
	mk_lib_iip_cp_client_socket_settings_t m_settings;
	mk_lib_iip_cp_client_socket_state_t m_state;
};
typedef struct mk_lib_iip_cp_client_socket_s mk_lib_iip_cp_client_socket_t;
mk_lang_typedef(mk_lib_iip_cp_client_socket);
#include "mk_lang_warning_msvc_pop.h"

enum mk_lib_iip_cp_client_socket_task_result_e
{
	mk_lib_iip_cp_client_socket_task_result_e_did_something,
	mk_lib_iip_cp_client_socket_task_result_e_idling,
	mk_lib_iip_cp_client_socket_task_result_e_want_send,
	//mk_lib_iip_cp_client_socket_task_result_e_want_recv,
	mk_lib_iip_cp_client_socket_task_result_e_dummy_end
};
typedef enum mk_lib_iip_cp_client_socket_task_result_e mk_lib_iip_cp_client_socket_task_result_t;
mk_lang_typedef(mk_lib_iip_cp_client_socket_task_result);

enum mk_lib_iip_cp_client_socket_task_step_e
{
	mk_lib_iip_cp_client_socket_task_step_e_idle,
	/*mk_lib_iip_cp_client_socket_task_step_e_make_msg_create_session,
	mk_lib_iip_cp_client_socket_task_step_e_pickup_msg_create_session,
	mk_lib_iip_cp_client_socket_task_step_e_wait_msg_session_status,
	mk_lib_iip_cp_client_socket_task_step_e_wait_msg_request_leaseset,
	mk_lib_iip_cp_client_socket_task_step_e_pickup_msg_create_lease_set,
	mk_lib_iip_cp_client_socket_task_step_e_pickup_msg_receive_message_begin,
	mk_lib_iip_cp_client_socket_task_step_e_pickup_msg_destroy_session,
	mk_lib_iip_cp_client_socket_task_step_e_destroy_sent,
	mk_lib_iip_cp_client_socket_task_step_e_destroyed_total,*/
	mk_lib_iip_cp_client_socket_task_step_e_dummy_end
};
typedef enum mk_lib_iip_cp_client_socket_task_step_e mk_lib_iip_cp_client_socket_task_step_t;

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_socket_task_s
{
	mk_lib_iip_cp_client_socket_task_step_t m_step;
	mk_lib_iip_cp_client_socket_t m_socket;
};
typedef struct mk_lib_iip_cp_client_socket_task_s mk_lib_iip_cp_client_socket_task_t;
mk_lang_typedef(mk_lib_iip_cp_client_socket_task);
#include "mk_lang_warning_msvc_pop.h"


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_rw_construct(mk_lib_iip_cp_client_socket_task_pt const task, mk_lib_iip_cp_client_socket_settings_pct const settings) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_rw_destroy(mk_lib_iip_cp_client_socket_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_rw_request_close(mk_lib_iip_cp_client_socket_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_rw_want_die(mk_lib_iip_cp_client_socket_task_pt const task, mk_lang_types_bool_pt const want) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_rw_on_packet(mk_lib_iip_cp_client_socket_task_pt const task, mk_sl_cui_uint16_pct const src_port, mk_sl_cui_uint16_pct const dst_port, mk_lib_iip_net_streaming_packet_pct const packet, mk_lang_types_bool_pt const consumed) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_rw_recv(mk_lib_iip_cp_client_socket_task_pt const task, mk_sl_cui_uint8_pt const data_buf, mk_lang_types_sint_t const data_len, mk_lang_types_sint_pt const recvd) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_rw_send(mk_lib_iip_cp_client_socket_task_pt const task, mk_sl_cui_uint8_pct const data_buf, mk_lang_types_sint_t const data_len, mk_lang_types_sint_pt const sent) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_rw_gimme_msg(mk_lib_iip_cp_client_socket_task_pt const task, mk_lib_iip_cp_message_ppt const msg) mk_lang_noexcept;
/*mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_rw_on_child_session_spawned(mk_lib_iip_cp_client_socket_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_rw_on_child_session_died(mk_lib_iip_cp_client_socket_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_rw_on_msg(mk_lib_iip_cp_client_socket_task_pt const task, mk_lib_iip_cp_message_pt const msg) mk_lang_noexcept;*/
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_rw_step(mk_lib_iip_cp_client_socket_task_pt const task, mk_lib_iip_cp_client_socket_task_result_pt const step_result) mk_lang_noexcept;


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_ptr_rw_construct_void(mk_lib_iip_cp_client_socket_task_ppt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_ptr_rw_destroy(mk_lib_iip_cp_client_socket_task_ppt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_ptr_rw_construct_copy(mk_lib_iip_cp_client_socket_task_ppt const dst, mk_lib_iip_cp_client_socket_task_pcpt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_ptr_rw_construct_move(mk_lib_iip_cp_client_socket_task_ppt const dst, mk_lib_iip_cp_client_socket_task_ppt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_ptr_rw_assign_copy(mk_lib_iip_cp_client_socket_task_ppt const dst, mk_lib_iip_cp_client_socket_task_pcpt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_socket_task_ptr_rw_assign_move(mk_lib_iip_cp_client_socket_task_ppt const dst, mk_lib_iip_cp_client_socket_task_ppt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_bool_t mk_lib_iip_cp_client_socket_task_ptr_ro_eq(mk_lib_iip_cp_client_socket_task_pcpt const a, mk_lib_iip_cp_client_socket_task_pcpt const b) mk_lang_noexcept;

#define mk_sl_vector_t_name mk_lib_iip_cp_client_socket_tasks
#define mk_sl_vector_t_element_type mk_lib_iip_cp_client_socket_task_pt
#define mk_sl_vector_t_mallocatorg mk_lib_iip_cp_mallocator_global
#define mk_sl_vector_t_element_construct_void mk_lib_iip_cp_client_socket_task_ptr_rw_construct_void
#define mk_sl_vector_t_element_destruct mk_lib_iip_cp_client_socket_task_ptr_rw_destroy
#define mk_sl_vector_t_element_copy_construct mk_lib_iip_cp_client_socket_task_ptr_rw_construct_copy
#define mk_sl_vector_t_element_move_construct mk_lib_iip_cp_client_socket_task_ptr_rw_construct_move
#define mk_sl_vector_t_element_copy_assign mk_lib_iip_cp_client_socket_task_ptr_rw_assign_copy
#define mk_sl_vector_t_element_move_assign mk_lib_iip_cp_client_socket_task_ptr_rw_assign_move
#define mk_sl_vector_t_element_eq mk_lib_iip_cp_client_socket_task_ptr_ro_eq
#include "mk_sl_vector_inl_fileh.h"
#include "mk_sl_vector_inl_fileu.h"


#if mk_lang_jumbo_have
#include "mk_lib_iip_cp_client_socket.c"
#endif
#endif
