#ifndef mk_include_guard_mk_lib_iip_cp_destination_h
#define mk_include_guard_mk_lib_iip_cp_destination_h


#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_static_param.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"
#include "mk_lib_iip_cp_bytes.h"
#include "mk_sl_cui_uint8.h"


struct mk_lib_iip_cp_destination_basic_buffer_s
{
	mk_lib_iip_cp_bytes_256_t m_enc_pub_key;
	mk_lib_iip_cp_bytes_128_t m_sgn_pub_key;
};
typedef struct mk_lib_iip_cp_destination_basic_buffer_s mk_lib_iip_cp_destination_basic_buffer_t;
mk_lang_typedef(mk_lib_iip_cp_destination_basic_buffer);

enum mk_lib_iip_cp_destination_certificate_key_sgn_type_e
{
	mk_lib_iip_cp_destination_certificate_key_sgn_type_e_dsa_sha1,
	mk_lib_iip_cp_destination_certificate_key_sgn_type_e_ecdsa_sha256_p256,
	mk_lib_iip_cp_destination_certificate_key_sgn_type_e_ecdsa_sha384_p384,
	mk_lib_iip_cp_destination_certificate_key_sgn_type_e_ecdsa_sha512_p521,
	mk_lib_iip_cp_destination_certificate_key_sgn_type_e_rsa_sha256_2048,
	mk_lib_iip_cp_destination_certificate_key_sgn_type_e_rsa_sha384_3072,
	mk_lib_iip_cp_destination_certificate_key_sgn_type_e_rsa_sha512_4096,
	mk_lib_iip_cp_destination_certificate_key_sgn_type_e_eddsa_sha512_ed25519,
	mk_lib_iip_cp_destination_certificate_key_sgn_type_e_eddsa_sha512_ed25519ph,
	mk_lib_iip_cp_destination_certificate_key_sgn_type_e_gost_a,
	mk_lib_iip_cp_destination_certificate_key_sgn_type_e_gost_b,
	mk_lib_iip_cp_destination_certificate_key_sgn_type_e_reddsa_sha512_ed25519,
	mk_lib_iip_cp_destination_certificate_key_sgn_type_e_dummy_end
};
typedef enum mk_lib_iip_cp_destination_certificate_key_sgn_type_e mk_lib_iip_cp_destination_certificate_key_sgn_type_t;
mk_lang_typedef(mk_lib_iip_cp_destination_certificate_key_sgn_type);

enum mk_lib_iip_cp_destination_certificate_key_enc_type_e
{
	mk_lib_iip_cp_destination_certificate_key_enc_type_e_elgamal,
	mk_lib_iip_cp_destination_certificate_key_enc_type_e_p256,
	mk_lib_iip_cp_destination_certificate_key_enc_type_e_p384,
	mk_lib_iip_cp_destination_certificate_key_enc_type_e_p521,
	mk_lib_iip_cp_destination_certificate_key_enc_type_e_x25519,
	mk_lib_iip_cp_destination_certificate_key_enc_type_e_dummy_end
};
typedef enum mk_lib_iip_cp_destination_certificate_key_enc_type_e mk_lib_iip_cp_destination_certificate_key_enc_type_t;
mk_lang_typedef(mk_lib_iip_cp_destination_certificate_key_enc_type);

struct mk_lib_iip_cp_destination_cert_signeda_s
{
	mk_sl_cui_uint8_t m_dsa_signature[40];
};
typedef struct mk_lib_iip_cp_destination_cert_signeda_s mk_lib_iip_cp_destination_cert_signeda_t;
mk_lang_typedef(mk_lib_iip_cp_destination_cert_signeda);

struct mk_lib_iip_cp_destination_cert_signedb_s
{
	mk_lib_iip_cp_destination_cert_signeda_t m_signeda;
	mk_sl_cui_uint8_t m_signing_destination_hash[32];
};
typedef struct mk_lib_iip_cp_destination_cert_signedb_s mk_lib_iip_cp_destination_cert_signedb_t;
mk_lang_typedef(mk_lib_iip_cp_destination_cert_signedb);

struct mk_lib_iip_cp_destination_cert_key_s
{
	mk_lib_iip_cp_destination_certificate_key_sgn_type_t m_sgn_type;
	mk_lib_iip_cp_destination_certificate_key_enc_type_t m_enc_type;
	mk_sl_cui_uint8_t m_sgn_pub_key[384];
	/*mk_sl_cui_uint8_t m_enc_pub_key[0];*/
};
typedef struct mk_lib_iip_cp_destination_cert_key_s mk_lib_iip_cp_destination_cert_key_t;
mk_lang_typedef(mk_lib_iip_cp_destination_cert_key);

enum mk_lib_iip_cp_destination_cert_type_e
{
	mk_lib_iip_cp_destination_cert_type_e_null,
	mk_lib_iip_cp_destination_cert_type_e_hidden,
	mk_lib_iip_cp_destination_cert_type_e_signeda,
	mk_lib_iip_cp_destination_cert_type_e_signedb,
	mk_lib_iip_cp_destination_cert_type_e_key,
	mk_lib_iip_cp_destination_cert_type_e_dummy_end
};
typedef enum mk_lib_iip_cp_destination_cert_type_e mk_lib_iip_cp_destination_cert_type_t;
mk_lang_typedef(mk_lib_iip_cp_destination_cert_type);

union mk_lib_iip_cp_destination_cert_data_u
{
	mk_lib_iip_cp_destination_cert_signeda_t m_signeda;
	mk_lib_iip_cp_destination_cert_signedb_t m_signedb;
	mk_lib_iip_cp_destination_cert_key_t m_key;
};
typedef union mk_lib_iip_cp_destination_cert_data_u mk_lib_iip_cp_destination_cert_data_t;
struct mk_lib_iip_cp_destination_cert_s
{
	mk_lib_iip_cp_destination_cert_data_t m_data;
};
typedef struct mk_lib_iip_cp_destination_cert_s mk_lib_iip_cp_destination_cert_t;
mk_lang_typedef(mk_lib_iip_cp_destination_cert);

struct mk_lib_iip_cp_destination_certificate_s
{
	mk_lib_iip_cp_destination_cert_type_t m_cert_type;
	mk_lib_iip_cp_destination_cert_t m_cert_data;
};
typedef struct mk_lib_iip_cp_destination_certificate_s mk_lib_iip_cp_destination_certificate_t;
mk_lang_typedef(mk_lib_iip_cp_destination_certificate);

struct mk_lib_iip_cp_destination_remote_s
{
	mk_lib_iip_cp_destination_basic_buffer_t m_basic_buffer;
	mk_lib_iip_cp_destination_certificate_t m_certificate;
};
typedef struct mk_lib_iip_cp_destination_remote_s mk_lib_iip_cp_destination_remote_t;
mk_lang_typedef(mk_lib_iip_cp_destination_remote);

struct mk_lib_iip_cp_destination_local_basic_buffer_s
{
	mk_lib_iip_cp_bytes_256_t m_enc_pri_key;
	mk_lib_iip_cp_bytes_20_t m_sgn_pri_key;
};
typedef struct mk_lib_iip_cp_destination_local_basic_buffer_s mk_lib_iip_cp_destination_local_basic_buffer_t;
mk_lang_typedef(mk_lib_iip_cp_destination_local_basic_buffer);

struct mk_lib_iip_cp_destination_local_s
{
	mk_lib_iip_cp_destination_remote_t m_remote_destination;
	mk_lib_iip_cp_destination_local_basic_buffer_t m_basic_buffer;
};
typedef struct mk_lib_iip_cp_destination_local_s mk_lib_iip_cp_destination_local_t;
mk_lang_typedef(mk_lib_iip_cp_destination_local);

enum mk_lib_iip_cp_destination_max_len_bytes_e{ mk_lib_iip_cp_destination_max_len_bytes_v = 775 }; typedef enum mk_lib_iip_cp_destination_max_len_bytes_e mk_lib_iip_cp_destination_max_len_bytes_t; mk_lang_typedef(mk_lib_iip_cp_destination_max_len_bytes);


mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_destination_get_signature_len(mk_lib_iip_cp_destination_certificate_key_sgn_type_t const sgn_type) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_destination_remote_rw_from_bytes(mk_lib_iip_cp_destination_remote_pt const remote_destination, mk_sl_cui_uint8_pct const data_buf, mk_lang_types_sint_t const data_len, mk_lang_types_bool_pt const succeeded, mk_lang_types_sint_pt const consumed) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_destination_remote_ro_to_bytes(mk_lib_iip_cp_destination_remote_pct const remote_destination, mk_sl_cui_uint8_pt const data_buf, mk_lang_types_sint_t const data_len, mk_lang_types_bool_pt const succeeded, mk_lang_types_sint_pt const consumed) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_destination_remote_ro_enc_to_bytes(mk_lib_iip_cp_destination_remote_pct const remote_destination, mk_sl_cui_uint8_pt const data_buf, mk_lang_types_sint_t const data_len, mk_lang_types_bool_pt const succeeded, mk_lang_types_sint_pt const consumed) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_destination_remote_ro_sgn_to_bytes(mk_lib_iip_cp_destination_remote_pct const remote_destination, mk_sl_cui_uint8_pt const data_buf, mk_lang_types_sint_t const data_len, mk_lang_types_bool_pt const succeeded, mk_lang_types_sint_pt const consumed) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_destination_remote_ro_to_b32(mk_lib_iip_cp_destination_remote_pct const remote_destination, mk_lang_static_param(mk_lang_types_pchar_t, str_buf, 52), mk_lang_types_sint_t const str_len, mk_lang_types_sint_pt const consumed) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_destination_remote_ro_get_signature_len(mk_lib_iip_cp_destination_remote_pct const remote_destination) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_destination_local_rw_from_bytes(mk_lib_iip_cp_destination_local_pt const remote_destination, mk_sl_cui_uint8_pct const data_buf, mk_lang_types_sint_t const data_len, mk_lang_types_bool_pt const succeeded, mk_lang_types_sint_pt const consumed) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_destination_local_rw_to_bytes(mk_lib_iip_cp_destination_local_pct const remote_destination, mk_sl_cui_uint8_pt const data_buf, mk_lang_types_sint_t const data_len, mk_lang_types_bool_pt const succeeded, mk_lang_types_sint_pt const consumed) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_destination_local_ro_enc_to_bytes(mk_lib_iip_cp_destination_local_pct const local_destination, mk_sl_cui_uint8_pt const data_buf, mk_lang_types_sint_t const data_len, mk_lang_types_bool_pt const succeeded, mk_lang_types_sint_pt const consumed) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_destination_local_ro_sgn_to_bytes(mk_lib_iip_cp_destination_local_pct const local_destination, mk_sl_cui_uint8_pt const data_buf, mk_lang_types_sint_t const data_len, mk_lang_types_bool_pt const succeeded, mk_lang_types_sint_pt const consumed) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_bool_t mk_lib_iip_cp_destination_local_ro_eq_enc(mk_lib_iip_cp_destination_local_pct const a, mk_lib_iip_cp_destination_local_pct const b) mk_lang_noexcept;


#if mk_lang_jumbo_have
#include "mk_lib_iip_cp_destination.c"
#endif
#endif
