include(`mk_lang_typedef.m')dnl
#include "mk_lang_charbit.h"
#include "mk_lang_concat.h"
#include "mk_lang_max.h"
#include "mk_lang_pow.h"


#if \
(!( \
	(defined mk_lib_float_analyzer_t_name) && \
	(defined mk_lib_float_analyzer_t_bits_all && (mk_lib_float_analyzer_t_bits_all) >= 1 && (mk_lib_float_analyzer_t_bits_all) <= 1 * 1024 * 1024) && \
	(defined mk_lib_float_analyzer_t_bits_exponent && (mk_lib_float_analyzer_t_bits_exponent) >= 1 && (mk_lib_float_analyzer_t_bits_exponent) <= 1 * 1024 * 1024) && \
	(defined mk_lib_float_analyzer_t_bits_mantissa && (mk_lib_float_analyzer_t_bits_mantissa) >= 1 && (mk_lib_float_analyzer_t_bits_mantissa) <= 1 * 1024 * 1024) && \
(1)))
#error xxxxxxxxxx
#endif

#if(!((mk_lib_float_analyzer_t_bits_all) == 1 + (mk_lib_float_analyzer_t_bits_exponent) + (mk_lib_float_analyzer_t_bits_mantissa)))
#error xxxxxxxxxx
#endif

#if(!((mk_lib_float_analyzer_t_bits_all) % mk_lang_charbit == 0))
#error xxxxxxxxxx
#endif

#if \
(!( \
	((mk_lib_float_analyzer_t_bits_all) == 16) || \
	((mk_lib_float_analyzer_t_bits_all) == 32) || \
	((mk_lib_float_analyzer_t_bits_all) == 64) || \
	((mk_lib_float_analyzer_t_bits_all) == 128) || \
(0)))
#error todo
#endif


#define mk_lib_float_analyzer_inl_defd_name mk_lib_float_analyzer_t_name
#define mk_lib_float_analyzer_inl_defd_bits_all (mk_lib_float_analyzer_t_bits_all)
#define mk_lib_float_analyzer_inl_defd_bits_exponent (mk_lib_float_analyzer_t_bits_exponent)
#define mk_lib_float_analyzer_inl_defd_bits_mantissa (mk_lib_float_analyzer_t_bits_mantissa)

#define mk_lib_float_analyzer_inl_defd_prefix mk_lib_float_analyzer_inl_defd_name

#define mk_lib_float_analyzer_inl_defd mk_lib_float_analyzer_inl_defd_prefix
#define mk_lib_float_analyzer_inl_defd_s mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _s)
#define mk_lib_float_analyzer_inl_defd_t mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _t)
mm_per_typedef(`#define mk_lib_float_analyzer_inl_defd_$1 mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _$1)')`'

#if mk_lib_float_analyzer_inl_defd_bits_all == 16
#include "mk_sl_cui_uint16.h"
#define mk_lib_float_analyzer_inl_defd_base_cui_all mk_sl_cui_uint16
#define mk_lib_float_analyzer_inl_defd_base_cui_all_size_bits_d mk_sl_cui_uint16_size_bits_d
#elif mk_lib_float_analyzer_inl_defd_bits_all == 32
#include "mk_sl_cui_uint32.h"
#define mk_lib_float_analyzer_inl_defd_base_cui_all mk_sl_cui_uint32
#define mk_lib_float_analyzer_inl_defd_base_cui_all_size_bits_d mk_sl_cui_uint32_size_bits_d
#elif mk_lib_float_analyzer_inl_defd_bits_all == 64
#include "mk_sl_cui_uint64.h"
#define mk_lib_float_analyzer_inl_defd_base_cui_all mk_sl_cui_uint64
#define mk_lib_float_analyzer_inl_defd_base_cui_all_size_bits_d mk_sl_cui_uint64_size_bits_d
#elif mk_lib_float_analyzer_inl_defd_bits_all == 128
#include "mk_sl_cui_uint128.h"
#define mk_lib_float_analyzer_inl_defd_base_cui_all mk_sl_cui_uint128
#define mk_lib_float_analyzer_inl_defd_base_cui_all_size_bits_d mk_sl_cui_uint128_size_bits_d
#else
#error todo
#endif
#define mk_lib_float_analyzer_inl_defd_base_cui_all_t mk_lang_concat(mk_lib_float_analyzer_inl_defd_base_cui_all, _t)
#define mk_lib_float_analyzer_inl_defd_cui_all mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_all)
#define mk_lib_float_analyzer_inl_defd_cui_all_t mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _t)
mm_per_typedef(`#define mk_lib_float_analyzer_inl_defd_cui_all_$1 mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _$1)')`'
#define mk_lib_float_analyzer_inl_defd_cui_all_size_bits_v mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _size_bits_v)
#define mk_lib_float_analyzer_inl_defd_cui_all_size_bytes_v mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _size_bytes_v)
#define mk_lib_float_analyzer_inl_defd_cui_all_strlen_bin_v mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _strlen_bin_v)
#define mk_lib_float_analyzer_inl_defd_cui_all_strlen_dec_v mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _strlen_dec_v)
#define mk_lib_float_analyzer_inl_defd_cui_all_strlen_hex_v mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _strlen_hex_v)
#define mk_lib_float_analyzer_inl_defd_cui_all_from_buis_uchar_le mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _from_buis_uchar_le)
#define mk_lib_float_analyzer_inl_defd_cui_all_to_str_binf_n mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _to_str_binf_n)
#define mk_lib_float_analyzer_inl_defd_cui_all_to_str_hexf_n mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _to_str_hexf_n)
#define mk_lib_float_analyzer_inl_defd_cui_all_to_str_dec_n mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _to_str_dec_n)
#define mk_lib_float_analyzer_inl_defd_cui_all_has_msb mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _has_msb)
#define mk_lib_float_analyzer_inl_defd_cui_all_not1 mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _not1)
#define mk_lib_float_analyzer_inl_defd_cui_all_inc1 mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _inc1)
#define mk_lib_float_analyzer_inl_defd_cui_all_shl3 mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _shl3)
#define mk_lib_float_analyzer_inl_defd_cui_all_shl2 mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _shl2)
#define mk_lib_float_analyzer_inl_defd_cui_all_shr2 mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _shr2)
#define mk_lib_float_analyzer_inl_defd_cui_all_to_buis_uchar_le mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_all, _to_buis_uchar_le)

#if mk_lib_float_analyzer_inl_defd_bits_exponent <= 8
#include "mk_sl_cui_uint8.h"
#define mk_lib_float_analyzer_inl_defd_base_cui_exponent mk_sl_cui_uint8
#define mk_lib_float_analyzer_inl_defd_base_cui_exponent_size_bits_d mk_sl_cui_uint8_size_bits_d
#elif mk_lib_float_analyzer_inl_defd_bits_exponent <= 16
#include "mk_sl_cui_uint16.h"
#define mk_lib_float_analyzer_inl_defd_base_cui_exponent mk_sl_cui_uint16
#define mk_lib_float_analyzer_inl_defd_base_cui_exponent_size_bits_d mk_sl_cui_uint16_size_bits_d
#elif mk_lib_float_analyzer_inl_defd_bits_exponent <= 32
#include "mk_sl_cui_uint32.h"
#define mk_lib_float_analyzer_inl_defd_base_cui_exponent mk_sl_cui_uint32
#define mk_lib_float_analyzer_inl_defd_base_cui_exponent_size_bits_d mk_sl_cui_uint32_size_bits_d
#elif mk_lib_float_analyzer_inl_defd_bits_exponent <= 64
#include "mk_sl_cui_uint64.h"
#define mk_lib_float_analyzer_inl_defd_base_cui_exponent mk_sl_cui_uint64
#define mk_lib_float_analyzer_inl_defd_base_cui_exponent_size_bits_d mk_sl_cui_uint64_size_bits_d
#elif mk_lib_float_analyzer_inl_defd_bits_exponent <= 128
#include "mk_sl_cui_uint128.h"
#define mk_lib_float_analyzer_inl_defd_base_cui_exponent mk_sl_cui_uint128
#define mk_lib_float_analyzer_inl_defd_base_cui_exponent_size_bits_d mk_sl_cui_uint128_size_bits_d
#else
#error todo
#endif
#define mk_lib_float_analyzer_inl_defd_cui_exponent mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_exponent)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_t mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _t)
mm_per_typedef(`#define mk_lib_float_analyzer_inl_defd_cui_exponent_$1 mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _$1)')`'
#define mk_lib_float_analyzer_inl_defd_cui_exponent_strlen_bin_v mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _strlen_bin_v)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_strlen_dec_v mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _strlen_dec_v)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_strlen_hex_v mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _strlen_hex_v)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_from_buis_uchar_le mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _from_buis_uchar_le)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_to_str_binf_n mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _to_str_binf_n)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_to_str_hexf_n mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _to_str_hexf_n)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_to_str_dec_n mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _to_str_dec_n)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_set_max mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _set_max)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_set_bit mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _set_bit)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_dec1 mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _dec1)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_shr2 mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _shr2)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_sub2_wrap_cid_cod mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _sub2_wrap_cid_cod)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_is_zero mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _is_zero)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_is_max mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _is_max)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_count_trailing_ones mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _count_trailing_ones)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_has_msb mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _has_msb)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_not1 mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _not1)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_inc1 mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _inc1)
#define mk_lib_float_analyzer_inl_defd_cui_exponent_to_bi_sint mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_exponent, _to_bi_sint)

#if mk_lib_float_analyzer_inl_defd_bits_mantissa <= 8
#include "mk_sl_cui_uint8.h"
#define mk_lib_float_analyzer_inl_defd_base_cui_mantissa mk_sl_cui_uint8
#define mk_lib_float_analyzer_inl_defd_base_cui_mantissa_size_bits_d mk_sl_cui_uint8_size_bits_d
#elif mk_lib_float_analyzer_inl_defd_bits_mantissa <= 16
#include "mk_sl_cui_uint16.h"
#define mk_lib_float_analyzer_inl_defd_base_cui_mantissa mk_sl_cui_uint16
#define mk_lib_float_analyzer_inl_defd_base_cui_mantissa_size_bits_d mk_sl_cui_uint16_size_bits_d
#elif mk_lib_float_analyzer_inl_defd_bits_mantissa <= 32
#include "mk_sl_cui_uint32.h"
#define mk_lib_float_analyzer_inl_defd_base_cui_mantissa mk_sl_cui_uint32
#define mk_lib_float_analyzer_inl_defd_base_cui_mantissa_size_bits_d mk_sl_cui_uint32_size_bits_d
#elif mk_lib_float_analyzer_inl_defd_bits_mantissa <= 64
#include "mk_sl_cui_uint64.h"
#define mk_lib_float_analyzer_inl_defd_base_cui_mantissa mk_sl_cui_uint64
#define mk_lib_float_analyzer_inl_defd_base_cui_mantissa_size_bits_d mk_sl_cui_uint64_size_bits_d
#elif mk_lib_float_analyzer_inl_defd_bits_mantissa <= 128
#include "mk_sl_cui_uint128.h"
#define mk_lib_float_analyzer_inl_defd_base_cui_mantissa mk_sl_cui_uint128
#define mk_lib_float_analyzer_inl_defd_base_cui_mantissa_size_bits_d mk_sl_cui_uint128_size_bits_d
#else
#error todo
#endif
#define mk_lib_float_analyzer_inl_defd_cui_mantissa mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_mantissa)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_t mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_mantissa, _t)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_pt mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_mantissa, _pt)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_strlen_bin_v mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_mantissa, _strlen_bin_v)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_strlen_dec_v mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_mantissa, _strlen_dec_v)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_strlen_hex_v mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_mantissa, _strlen_hex_v)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_from_buis_uchar_le mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_mantissa, _from_buis_uchar_le)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_is_zero mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_mantissa, _is_zero)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_to_str_binf_n mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_mantissa, _to_str_binf_n)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_to_str_hexf_n mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_mantissa, _to_str_hexf_n)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_to_str_dec_n mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_mantissa, _to_str_dec_n)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_from_bi_sint mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_mantissa, _from_bi_sint)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_shl3 mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_mantissa, _shl3)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_mul4_wrap_wi_smol mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_mantissa, _mul4_wrap_wi_smol)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_to_bi_sint mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_mantissa, _to_bi_sint)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_fraction_max_len_d (2 + mk_lib_float_analyzer_inl_defd_bits_mantissa)

#define mk_lib_float_analyzer_inl_defd_cui_mantissa_base_t mk_lang_concat(mk_lib_float_analyzer_inl_defd_base_cui_mantissa, _t)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_base_from_bi_sint mk_lang_concat(mk_lib_float_analyzer_inl_defd_base_cui_mantissa, _from_bi_sint)
#define mk_lib_float_analyzer_inl_defd_cui_mantissa_base_to_bi_sint mk_lang_concat(mk_lib_float_analyzer_inl_defd_base_cui_mantissa, _to_bi_sint)

#define mk_lib_float_analyzer_inl_defd_cui_big_bits_needed_d (mk_lib_float_analyzer_inl_defd_bits_mantissa + mk_lang_pow(2, mk_lib_float_analyzer_inl_defd_bits_exponent - 1) - 2)
#define mk_lib_float_analyzer_inl_defd_cui_big mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_big)
#define mk_lib_float_analyzer_inl_defd_cui_big_t mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_big, _t)
mm_per_typedef(`#define mk_lib_float_analyzer_inl_defd_cui_big_$1 mk_lang_concat(mk_lib_float_analyzer_inl_defd_cui_big, _$1)')`'
#define mk_lib_float_analyzer_inl_defd_cui_big_to_str_dec_inverse_n mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_big_to_str_dec_inverse_n)
#define mk_lib_float_analyzer_inl_defd_cui_big_from_bi_sint mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_big_from_bi_sint)
#define mk_lib_float_analyzer_inl_defd_cui_big_mul4_wrap_wi mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_big_mul4_wrap_wi)
#define mk_lib_float_analyzer_inl_defd_cui_big_mul4_wrap_wi_smol mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_big_mul4_wrap_wi_smol)
#define mk_lib_float_analyzer_inl_defd_cui_big_to_bi_sint mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_big_to_bi_sint)
#define mk_lib_float_analyzer_inl_defd_cui_big_is_zero mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_big_is_zero)
#define mk_lib_float_analyzer_inl_defd_cui_big_set_one mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_big_set_one)
#define mk_lib_float_analyzer_inl_defd_cui_big_set_zero mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_big_set_zero)
#define mk_lib_float_analyzer_inl_defd_cui_big_shl2 mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_big_shl2)
#define mk_lib_float_analyzer_inl_defd_cui_big_from_bi_uchar mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_big_from_bi_uchar)
#define mk_lib_float_analyzer_inl_defd_cui_big_or2 mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_big_or2)
#define mk_lib_float_analyzer_inl_defd_cui_big_shr3 mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_big_shr3)
#define mk_lib_float_analyzer_inl_defd_cui_big_shl3 mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_big_shl3)
#define mk_lib_float_analyzer_inl_defd_cui_big_to_str_dec_n mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _cui_big_to_str_dec_n)

#define mk_lib_float_analyzer_inl_defd_cui_value_log10 19728 /* floor(log10(2) * (2^16)) */
#define mk_lib_float_analyzer_inl_defd_cui_value_max_len_before_point_d ((((mk_lang_pow(2, (mk_lib_float_analyzer_inl_defd_bits_exponent - 1)) - 1 + 1) * mk_lib_float_analyzer_inl_defd_cui_value_log10) >> 16) + 1)
#define mk_lib_float_analyzer_inl_defd_cui_value_max_len_after_point_d ((mk_lang_pow(2, (mk_lib_float_analyzer_inl_defd_bits_exponent - 1)) - 1) + mk_lib_float_analyzer_inl_defd_bits_mantissa)
#define mk_lib_float_analyzer_inl_defd_cui_value_max_len_d (1 + 2 + mk_lang_max(mk_lib_float_analyzer_inl_defd_cui_value_max_len_before_point_d, mk_lib_float_analyzer_inl_defd_cui_value_max_len_after_point_d))

#define mk_lib_float_analyzer_inl_defd_text_sign_positive "Positive"
#define mk_lib_float_analyzer_inl_defd_text_sign_negative "Negative"
#define mk_lib_float_analyzer_inl_defd_text_exponent_na "n/a"
#define mk_lib_float_analyzer_inl_defd_text_exponent_type_denormal "Denormal"
#define mk_lib_float_analyzer_inl_defd_text_exponent_type_infinity "Infinity"
#define mk_lib_float_analyzer_inl_defd_text_exponent_type_nan "NaN"
#define mk_lib_float_analyzer_inl_defd_text_exponent_type_normal "Normal"
#define mk_lib_float_analyzer_inl_defd_text_exponent_type_zero "Zero"
#define mk_lib_float_analyzer_inl_defd_text_exponent_implied_one_na "n/a"
#define mk_lib_float_analyzer_inl_defd_text_exponent_implied_one_no "No"
#define mk_lib_float_analyzer_inl_defd_text_exponent_implied_one_yes "Yes"
#define mk_lib_float_analyzer_inl_defd_text_mantissa_na "n/a"

#define mk_lib_float_analyzer_inl_defd_kind_e mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _kind_e)
#define mk_lib_float_analyzer_inl_defd_kind_t mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _kind_t)
#define mk_lib_float_analyzer_inl_defd_kind_e_normal mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _kind_e_normal)
#define mk_lib_float_analyzer_inl_defd_kind_e_zero mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _kind_e_zero)
#define mk_lib_float_analyzer_inl_defd_kind_e_denormal mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _kind_e_denormal)
#define mk_lib_float_analyzer_inl_defd_kind_e_infinity mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _kind_e_infinity)
#define mk_lib_float_analyzer_inl_defd_kind_e_nan mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _kind_e_nan)
#define mk_lib_float_analyzer_inl_defd_kind_e_dummy_end mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _kind_e_dummy_end)

#define mk_lib_float_analyzer_inl_defd_k_alphabet mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _k_alphabet)

#define mk_lib_float_analyzer_inl_defd_pr_analyze_get_kind mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_get_kind)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_get_all mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_get_all)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_get_exponent mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_get_exponent)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_get_mantissa mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_get_mantissa)
#define mk_lib_float_analyzer_inl_defd_pr_decode_exponent mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_decode_exponent)

#define mk_lib_float_analyzer_inl_defd_pr_analyze_all_bin mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_all_bin)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_all_hex mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_all_hex)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_all_dec mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_all_dec)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_all_sgn mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_all_sgn)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_sign mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_sign)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_exponent_bin mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_exponent_bin)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_exponent_hex mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_exponent_hex)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_exponent_dec mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_exponent_dec)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_exponent_dcd mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_exponent_dcd)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_exponent_typ mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_exponent_typ)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_exponent_one mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_exponent_one)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_mantissa_bin mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_mantissa_bin)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_mantissa_hex mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_mantissa_hex)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_mantissa_dec mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_mantissa_dec)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_mantissa_dcd mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_mantissa_dcd)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_value mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_value)

#define mk_lib_float_analyzer_inl_defd_pr_analyze_mantissa_dcd_y mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_mantissa_dcd_y)
#define mk_lib_float_analyzer_inl_defd_pr_analyze_mantissa_dcd_n mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _pr_analyze_mantissa_dcd_n)

#define mk_lib_float_analyzer_inl_defd_analyze mk_lang_concat(mk_lib_float_analyzer_inl_defd_prefix, _analyze)
