#include "mk_lang_alignas.h"
#include "mk_lang_charbit.h"
#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_types.h"
#include "mk_sl_uint32.h"
#include "mk_sl_uint8.h"


#include "mk_lib_crypto_alg_twofish_base_inl_defd.h"


enum mk_lib_crypto_alg_twofish_base_inl_defd_key_len_e { mk_lib_crypto_alg_twofish_base_inl_defd_key_len_v = mk_lib_crypto_alg_twofish_base_inl_defd_key_len_m };
enum mk_lib_crypto_alg_twofish_base_inl_defd_msg_len_e { mk_lib_crypto_alg_twofish_base_inl_defd_msg_len_v = mk_lib_crypto_alg_twofish_base_inl_defd_msg_len_m };
enum mk_lib_crypto_alg_twofish_base_inl_defd_schedule_len_e { mk_lib_crypto_alg_twofish_base_inl_defd_schedule_len_v = mk_lib_crypto_alg_twofish_base_inl_defd_schedule_len_m };


union mk_lib_crypto_alg_twofish_base_inl_defd_key_data_u
{
	mk_lang_alignas(mk_lib_crypto_alg_twofish_base_inl_defd_msg_len_v) mk_sl_cui_uint8_t m_uint8s[mk_lib_crypto_alg_twofish_base_inl_defd_key_len_v];
	mk_lang_types_ulllong_t m_ulllong;
};
typedef union mk_lib_crypto_alg_twofish_base_inl_defd_key_data_u mk_lib_crypto_alg_twofish_base_inl_defd_key_data_t;

struct mk_lib_crypto_alg_twofish_base_inl_defd_key_s
{
	mk_lib_crypto_alg_twofish_base_inl_defd_key_data_t m_data;
};
typedef struct mk_lib_crypto_alg_twofish_base_inl_defd_key_s mk_lib_crypto_alg_twofish_base_inl_defd_key_t;
typedef mk_lib_crypto_alg_twofish_base_inl_defd_key_t const mk_lib_crypto_alg_twofish_base_inl_defd_key_ct;
typedef mk_lib_crypto_alg_twofish_base_inl_defd_key_t* mk_lib_crypto_alg_twofish_base_inl_defd_key_pt;
typedef mk_lib_crypto_alg_twofish_base_inl_defd_key_t const* mk_lib_crypto_alg_twofish_base_inl_defd_key_pct;


union mk_lib_crypto_alg_twofish_base_inl_defd_msg_data_u
{
	mk_lang_alignas(mk_lib_crypto_alg_twofish_base_inl_defd_msg_len_v) mk_sl_cui_uint8_t m_uint8s[mk_lib_crypto_alg_twofish_base_inl_defd_msg_len_v];
	mk_lang_types_ulllong_t m_ulllong;
};
typedef union mk_lib_crypto_alg_twofish_base_inl_defd_msg_data_u mk_lib_crypto_alg_twofish_base_inl_defd_msg_data_t;

struct mk_lib_crypto_alg_twofish_base_inl_defd_msg_s
{
	mk_lib_crypto_alg_twofish_base_inl_defd_msg_data_t m_data;
};
typedef struct mk_lib_crypto_alg_twofish_base_inl_defd_msg_s mk_lib_crypto_alg_twofish_base_inl_defd_msg_t;
typedef mk_lib_crypto_alg_twofish_base_inl_defd_msg_t const mk_lib_crypto_alg_twofish_base_inl_defd_msg_ct;
typedef mk_lib_crypto_alg_twofish_base_inl_defd_msg_t* mk_lib_crypto_alg_twofish_base_inl_defd_msg_pt;
typedef mk_lib_crypto_alg_twofish_base_inl_defd_msg_t const* mk_lib_crypto_alg_twofish_base_inl_defd_msg_pct;


struct mk_lib_crypto_alg_twofish_base_inl_defd_rks_s
{
	mk_sl_cui_uint32_t m_uint32s[40];
};
typedef struct mk_lib_crypto_alg_twofish_base_inl_defd_rks_s mk_lib_crypto_alg_twofish_base_inl_defd_rks_t;

struct mk_lib_crypto_alg_twofish_base_inl_defd_sbox_s
{
	mk_sl_cui_uint32_t m_uint32s[0xff + 1];
};
typedef struct mk_lib_crypto_alg_twofish_base_inl_defd_sbox_s mk_lib_crypto_alg_twofish_base_inl_defd_sbox_t;

struct mk_lib_crypto_alg_twofish_base_inl_defd_sboxs_s
{
	mk_lib_crypto_alg_twofish_base_inl_defd_sbox_t m_sboxs[4];
};
typedef struct mk_lib_crypto_alg_twofish_base_inl_defd_sboxs_s mk_lib_crypto_alg_twofish_base_inl_defd_sboxs_t;

struct mk_lib_crypto_alg_twofish_base_inl_defd_rks_sboxs_s
{
	mk_lib_crypto_alg_twofish_base_inl_defd_rks_t m_rks;
	mk_lib_crypto_alg_twofish_base_inl_defd_sboxs_t m_sboxs;
};
typedef struct mk_lib_crypto_alg_twofish_base_inl_defd_rks_sboxs_s mk_lib_crypto_alg_twofish_base_inl_defd_rks_sboxs_t;

union mk_lib_crypto_alg_twofish_base_inl_defd_schedule_data_u
{
	mk_lang_alignas(mk_lib_crypto_alg_twofish_base_inl_defd_msg_len_v) mk_lib_crypto_alg_twofish_base_inl_defd_rks_sboxs_t m_rks_sboxs;
	mk_lang_types_ulllong_t m_ulllong;
};
typedef union mk_lib_crypto_alg_twofish_base_inl_defd_schedule_data_u mk_lib_crypto_alg_twofish_base_inl_defd_schedule_data_t;

struct mk_lib_crypto_alg_twofish_base_inl_defd_schedule_s
{
	mk_lib_crypto_alg_twofish_base_inl_defd_schedule_data_t m_data;
};
typedef struct mk_lib_crypto_alg_twofish_base_inl_defd_schedule_s mk_lib_crypto_alg_twofish_base_inl_defd_schedule_t;
typedef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_t const mk_lib_crypto_alg_twofish_base_inl_defd_schedule_ct;
typedef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_t* mk_lib_crypto_alg_twofish_base_inl_defd_schedule_pt;
typedef mk_lib_crypto_alg_twofish_base_inl_defd_schedule_t const* mk_lib_crypto_alg_twofish_base_inl_defd_schedule_pct;


mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_alg_twofish_base_inl_defd_schedule_encrypt(mk_lib_crypto_alg_twofish_base_inl_defd_schedule_pct const schedule, mk_lib_crypto_alg_twofish_base_inl_defd_msg_pct const input, mk_lib_crypto_alg_twofish_base_inl_defd_msg_pt const output, mk_lang_types_usize_t const nblocks) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_alg_twofish_base_inl_defd_schedule_decrypt(mk_lib_crypto_alg_twofish_base_inl_defd_schedule_pct const schedule, mk_lib_crypto_alg_twofish_base_inl_defd_msg_pct const input, mk_lib_crypto_alg_twofish_base_inl_defd_msg_pt const output, mk_lang_types_usize_t const nblocks) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_alg_twofish_base_inl_defd_expand_enc(mk_lib_crypto_alg_twofish_base_inl_defd_key_pct const key, mk_lib_crypto_alg_twofish_base_inl_defd_schedule_pt const schedule) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_alg_twofish_base_inl_defd_expand_dec(mk_lib_crypto_alg_twofish_base_inl_defd_key_pct const key, mk_lib_crypto_alg_twofish_base_inl_defd_schedule_pt const schedule) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_alg_twofish_base_inl_defd_encrypt(mk_lib_crypto_alg_twofish_base_inl_defd_key_pct const key, mk_lib_crypto_alg_twofish_base_inl_defd_msg_pct const input, mk_lib_crypto_alg_twofish_base_inl_defd_msg_pt const output) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_alg_twofish_base_inl_defd_decrypt(mk_lib_crypto_alg_twofish_base_inl_defd_key_pct const key, mk_lib_crypto_alg_twofish_base_inl_defd_msg_pct const input, mk_lib_crypto_alg_twofish_base_inl_defd_msg_pt const output) mk_lang_noexcept;


#include "mk_lib_crypto_alg_twofish_base_inl_defu.h"
