#ifndef mk_include_guard_mk_lib_iip_cp_client_local_h
#define mk_include_guard_mk_lib_iip_cp_client_local_h


#include "mk_lang_bui.h"
#include "mk_lang_charbit.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"
#include "mk_lib_iip_cp_client_local_client_task.h"
#include "mk_lib_iip_cp_mallocator_global.h"
#include "mk_lib_iip_cp_message.h"
#include "mk_lib_iip_cp_types.h"
#include "mk_lib_net.h"
#include "mk_sl_cui_uint8.h"


mk_lang_forward(mk_lib_iip_cp_client_shared);


#define mk_sl_cui_t_name mk_lib_iip_cp_client_local_handle
#define mk_sl_cui_t_base_type_name mk_lang_bui_uintptr
#define mk_sl_cui_t_count 1
#define mk_sl_cui_t_disable_big_div 1
#define mk_sl_cui_t_base_type_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_sl_cui_t_inline 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"
#define mk_lib_iip_cp_client_local_handle_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_lib_iip_cp_client_local_handle_size_bytes_d (mk_lang_bui_uintptr_size_bits_d / mk_lang_charbit)

struct mk_lib_iip_cp_client_local_task_settings_s
{
	mk_lib_iip_cp_client_shared_pt m_shared;
	mk_lib_net_destination_t m_destination;
};
typedef struct mk_lib_iip_cp_client_local_task_settings_s mk_lib_iip_cp_client_local_task_settings_t;
mk_lang_typedef(mk_lib_iip_cp_client_local_task_settings);

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_local_state_s
{
	mk_lib_net_socket_t m_listening_socket;
	mk_lib_iip_cp_client_local_client_task_pt m_new_client;
	mk_lib_net_ioctl_request_t m_ioctl_request;
	mk_lang_types_ulllong_t m_ioctl_request_input[128 / 8 / sizeof(mk_lang_types_ulllong_t)];
	mk_lang_types_sint_t(*m_fn_ptr_accept_ex)(mk_lang_types_sint_t);
	mk_lang_types_sint_t(*m_fn_ptr_get_accept_ex_sock_addrs)(mk_lang_types_sint_t);
	mk_lib_net_accept_request_t m_accept_request;
	mk_lib_net_destination_t m_client_address_local;
	mk_lib_net_destination_t m_client_address_remote;
	mk_lang_types_bool_t m_close_requested;
	mk_lib_iip_cp_client_local_client_tasks_t m_clients;
	mk_lang_types_usize_t m_client_idx;
};
typedef struct mk_lib_iip_cp_client_local_state_s mk_lib_iip_cp_client_local_state_t;
mk_lang_typedef(mk_lib_iip_cp_client_local_state);
#include "mk_lang_warning_msvc_pop.h"

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_local_s
{
	mk_lib_iip_cp_client_local_task_settings_t m_settings;
	mk_lib_iip_cp_client_local_state_t m_state;
};
typedef struct mk_lib_iip_cp_client_local_s mk_lib_iip_cp_client_local_t;
mk_lang_typedef(mk_lib_iip_cp_client_local);
#include "mk_lang_warning_msvc_pop.h"

enum mk_lib_iip_cp_client_local_task_result_e
{
	mk_lib_iip_cp_client_local_task_result_e_did_something,
	mk_lib_iip_cp_client_local_task_result_e_would_block,
	mk_lib_iip_cp_client_local_task_result_e_timed_out,
	mk_lib_iip_cp_client_local_task_result_e_did_nothing,
	mk_lib_iip_cp_client_local_task_result_e_dummy_end
};
typedef enum mk_lib_iip_cp_client_local_task_result_e mk_lib_iip_cp_client_local_task_result_t;
mk_lang_typedef(mk_lib_iip_cp_client_local_task_result);

enum mk_lib_iip_cp_client_local_task_step_e
{
	mk_lib_iip_cp_client_local_task_step_e_create_socket,
	mk_lib_iip_cp_client_local_task_step_e_want_associate_socket,
	mk_lib_iip_cp_client_local_task_step_e_bind_socket,
	mk_lib_iip_cp_client_local_task_step_e_listen_socket,
	mk_lib_iip_cp_client_local_task_step_e_rqst_accept_ex,
	mk_lib_iip_cp_client_local_task_step_e_wait_accept_ex,
	mk_lib_iip_cp_client_local_task_step_e_rqst_get_accept_ex_sock_addrs,
	mk_lib_iip_cp_client_local_task_step_e_wait_get_accept_ex_sock_addrs,
	mk_lib_iip_cp_client_local_task_step_e_create_client,
	mk_lib_iip_cp_client_local_task_step_e_want_associate_client,
	mk_lib_iip_cp_client_local_task_step_e_accept_client,
	mk_lib_iip_cp_client_local_task_step_e_idle,
	mk_lib_iip_cp_client_local_task_step_e_dummy_end
};
typedef enum mk_lib_iip_cp_client_local_task_step_e mk_lib_iip_cp_client_local_task_step_t;

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_local_task_s
{
	mk_lib_iip_cp_client_local_task_step_t m_step;
	mk_lib_iip_cp_client_local_t m_local;
};
typedef struct mk_lib_iip_cp_client_local_task_s mk_lib_iip_cp_client_local_task_t;
mk_lang_typedef(mk_lib_iip_cp_client_local_task);
#include "mk_lang_warning_msvc_pop.h"


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_local_task_rw_construct(mk_lib_iip_cp_client_local_task_pt const task, mk_lib_iip_cp_client_local_task_settings_pct const settings) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_local_task_rw_destroy(mk_lib_iip_cp_client_local_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_local_task_rw_request_close(mk_lib_iip_cp_client_local_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_bool_t mk_lib_iip_cp_client_local_task_rw_want_associate_socket(mk_lib_iip_cp_client_local_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lib_net_socket_pt mk_lib_iip_cp_client_local_task_rw_gimme_socket(mk_lib_iip_cp_client_local_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_local_task_rw_on_iorp_done(mk_lib_iip_cp_client_local_task_pt const task, mk_lang_types_sint_t const bytes_transferred, mk_lang_types_void_pt const overlapped) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_local_task_rw_step(mk_lib_iip_cp_client_local_task_pt const task, mk_lang_types_bool_t const allow_to_block, mk_lang_types_sint_t const tm, mk_lib_iip_cp_client_local_task_result_pt const step_result) mk_lang_noexcept;


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_local_task_ptr_rw_construct_void(mk_lib_iip_cp_client_local_task_ppt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_local_task_ptr_rw_destroy(mk_lib_iip_cp_client_local_task_ppt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_local_task_ptr_rw_construct_copy(mk_lib_iip_cp_client_local_task_ppt const dst, mk_lib_iip_cp_client_local_task_pcpt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_local_task_ptr_rw_construct_move(mk_lib_iip_cp_client_local_task_ppt const dst, mk_lib_iip_cp_client_local_task_ppt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_local_task_ptr_rw_assign_copy(mk_lib_iip_cp_client_local_task_ppt const dst, mk_lib_iip_cp_client_local_task_pcpt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_local_task_ptr_rw_assign_move(mk_lib_iip_cp_client_local_task_ppt const dst, mk_lib_iip_cp_client_local_task_ppt const src) mk_lang_noexcept;

#define mk_sl_vector_t_name mk_lib_iip_cp_client_local_tasks
#define mk_sl_vector_t_element_type mk_lib_iip_cp_client_local_task_pt
#define mk_sl_vector_t_mallocatorg mk_lib_iip_cp_mallocator_global
#define mk_sl_vector_t_element_construct_void mk_lib_iip_cp_client_local_task_ptr_rw_construct_void
#define mk_sl_vector_t_element_destruct mk_lib_iip_cp_client_local_task_ptr_rw_destroy
#define mk_sl_vector_t_element_copy_construct mk_lib_iip_cp_client_local_task_ptr_rw_construct_copy
#define mk_sl_vector_t_element_move_construct mk_lib_iip_cp_client_local_task_ptr_rw_construct_move
#define mk_sl_vector_t_element_copy_assign mk_lib_iip_cp_client_local_task_ptr_rw_assign_copy
#define mk_sl_vector_t_element_move_assign mk_lib_iip_cp_client_local_task_ptr_rw_assign_move
#include "mk_sl_vector_inl_fileh.h"
#include "mk_sl_vector_inl_fileu.h"


#if mk_lang_jumbo_have
#include "mk_lib_iip_cp_client_local_task.c"
#endif
#endif
