#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_types.h"
#include "mk_sl_cui_uint8.h"


#include "mk_lib_crypto_xof_stream_inl_defd.h"


enum mk_lib_crypto_xof_stream_inl_defd_block_len_e{ mk_lib_crypto_xof_stream_inl_defd_block_len_v = mk_lib_crypto_xof_stream_inl_defd_base_block_len_v }; typedef enum mk_lib_crypto_xof_stream_inl_defd_block_len_e mk_lib_crypto_xof_stream_inl_defd_block_len_t;
enum mk_lib_crypto_xof_stream_inl_defd_digest_len_e{ mk_lib_crypto_xof_stream_inl_defd_digest_len_v = mk_lib_crypto_xof_stream_inl_defd_base_digest_len_v }; typedef enum mk_lib_crypto_xof_stream_inl_defd_digest_len_e mk_lib_crypto_xof_stream_inl_defd_digest_len_t;

typedef mk_lib_crypto_xof_stream_inl_defd_base_block_t mk_lib_crypto_xof_stream_inl_defd_block_t;
typedef mk_lib_crypto_xof_stream_inl_defd_block_t const mk_lib_crypto_xof_stream_inl_defd_block_ct;
typedef mk_lib_crypto_xof_stream_inl_defd_block_t* mk_lib_crypto_xof_stream_inl_defd_block_pt;
typedef mk_lib_crypto_xof_stream_inl_defd_block_t const* mk_lib_crypto_xof_stream_inl_defd_block_pct;

typedef mk_lib_crypto_xof_stream_inl_defd_base_digest_t mk_lib_crypto_xof_stream_inl_defd_digest_t;
typedef mk_lib_crypto_xof_stream_inl_defd_digest_t const mk_lib_crypto_xof_stream_inl_defd_digest_ct;
typedef mk_lib_crypto_xof_stream_inl_defd_digest_t* mk_lib_crypto_xof_stream_inl_defd_digest_pt;
typedef mk_lib_crypto_xof_stream_inl_defd_digest_t const* mk_lib_crypto_xof_stream_inl_defd_digest_pct;


#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_crypto_xof_stream_inl_defd_s
{
	mk_lib_crypto_xof_stream_inl_defd_base_t m_base;
	mk_lang_types_sint_t m_idx;
	mk_lib_crypto_xof_stream_inl_defd_base_block_t m_block;
};
typedef struct mk_lib_crypto_xof_stream_inl_defd_s mk_lib_crypto_xof_stream_inl_defd_t;
typedef mk_lib_crypto_xof_stream_inl_defd_t const mk_lib_crypto_xof_stream_inl_defd_ct;
typedef mk_lib_crypto_xof_stream_inl_defd_t* mk_lib_crypto_xof_stream_inl_defd_pt;
typedef mk_lib_crypto_xof_stream_inl_defd_t const* mk_lib_crypto_xof_stream_inl_defd_pct;
#include "mk_lang_warning_msvc_pop.h"


mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_xof_stream_inl_defd_init(mk_lib_crypto_xof_stream_inl_defd_pt const xof_stream) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_xof_stream_inl_defd_append_u8s(mk_lib_crypto_xof_stream_inl_defd_pt const xof_stream, mk_sl_cui_uint8_pct const u8s, mk_lang_types_usize_t const count) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_xof_stream_inl_defd_finish(mk_lib_crypto_xof_stream_inl_defd_pt const xof_stream) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_lib_crypto_xof_stream_inl_defd_squeeze_u8s(mk_lib_crypto_xof_stream_inl_defd_pt const xof_stream, mk_sl_cui_uint8_pt const u8s, mk_lang_types_usize_t const count) mk_lang_noexcept;


#include "mk_lib_crypto_xof_stream_inl_defu.h"
