#ifndef mk_include_guard_mk_lib_iip_cp_client_session_h
#define mk_include_guard_mk_lib_iip_cp_client_session_h


#include "mk_lang_bui.h"
#include "mk_lang_charbit.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"
#include "mk_lib_iip_cp_mallocator_global.h"
#include "mk_lib_iip_cp_message.h"
#include "mk_lib_iip_cp_types.h"


mk_lang_forward(mk_lib_iip_cp_client_shared);


#define mk_sl_cui_t_name mk_lib_iip_cp_client_session_handle
#define mk_sl_cui_t_base_type_name mk_lang_bui_uintptr
#define mk_sl_cui_t_count 1
#define mk_sl_cui_t_disable_big_div 1
#define mk_sl_cui_t_base_type_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_sl_cui_t_inline 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"
#define mk_lib_iip_cp_client_session_handle_size_bits_d mk_lang_bui_uintptr_size_bits_d
#define mk_lib_iip_cp_client_session_handle_size_bytes_d (mk_lang_bui_uintptr_size_bits_d / mk_lang_charbit)

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_session_settings_s
{
	mk_lib_iip_cp_types_destination_elgamal_dsa_sha1_t m_destination;
	mk_lib_iip_cp_client_session_handle_t m_master_session;
};
typedef struct mk_lib_iip_cp_client_session_settings_s mk_lib_iip_cp_client_session_settings_t;
mk_lang_typedef(mk_lib_iip_cp_client_session_settings);
#include "mk_lang_warning_msvc_pop.h"

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_session_state_s
{
	mk_lib_iip_cp_types_sessionid_t m_id;
	mk_lang_types_bool_t m_has_id;
	mk_lib_iip_cp_message_t m_msg;
	mk_lang_types_bool_t m_has_msg_pending;
	mk_lib_iip_cp_types_leasez_t m_leases;
	mk_lang_types_bool_t m_expecting_msg_b;
	mk_lang_types_bool_t m_expecting_msg_end;
	mk_lib_iip_cp_types_messageid_t m_expecting_msg_id;
	mk_lang_types_sint_t m_expecting_msg_size;
};
typedef struct mk_lib_iip_cp_client_session_state_s mk_lib_iip_cp_client_session_state_t;
mk_lang_typedef(mk_lib_iip_cp_client_session_state);
#include "mk_lang_warning_msvc_pop.h"

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_session_s
{
	mk_lib_iip_cp_client_session_settings_t m_settings;
	mk_lib_iip_cp_client_session_state_t m_state;
};
typedef struct mk_lib_iip_cp_client_session_s mk_lib_iip_cp_client_session_t;
mk_lang_typedef(mk_lib_iip_cp_client_session);
#include "mk_lang_warning_msvc_pop.h"

enum mk_lib_iip_cp_client_session_task_result_e
{
	mk_lib_iip_cp_client_session_task_result_e_did_something,
	mk_lib_iip_cp_client_session_task_result_e_idling,
	mk_lib_iip_cp_client_session_task_result_e_want_send,
	mk_lib_iip_cp_client_session_task_result_e_want_recv,
	mk_lib_iip_cp_client_session_task_result_e_dummy_end
};
typedef enum mk_lib_iip_cp_client_session_task_result_e mk_lib_iip_cp_client_session_task_result_t;
mk_lang_typedef(mk_lib_iip_cp_client_session_task_result);

enum mk_lib_iip_cp_client_session_task_step_e
{
	mk_lib_iip_cp_client_session_task_step_e_make_msg_create_session,
	mk_lib_iip_cp_client_session_task_step_e_pickup_msg_create_session,
	mk_lib_iip_cp_client_session_task_step_e_wait_msg_session_status,
	mk_lib_iip_cp_client_session_task_step_e_wait_msg_request_leaseset,
	mk_lib_iip_cp_client_session_task_step_e_pickup_msg_create_lease_set,
	mk_lib_iip_cp_client_session_task_step_e_pickup_msg_receive_message_begin,
	mk_lib_iip_cp_client_session_task_step_e_idle,
	mk_lib_iip_cp_client_session_task_step_e_dummy_end
};
typedef enum mk_lib_iip_cp_client_session_task_step_e mk_lib_iip_cp_client_session_task_step_t;

#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_lib_iip_cp_client_session_task_s
{
	mk_lib_iip_cp_client_shared_pt m_shared;
	mk_lib_iip_cp_client_session_task_step_t m_step;
	mk_lib_iip_cp_client_session_t m_session;
};
typedef struct mk_lib_iip_cp_client_session_task_s mk_lib_iip_cp_client_session_task_t;
mk_lang_typedef(mk_lib_iip_cp_client_session_task);
#include "mk_lang_warning_msvc_pop.h"


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_construct(mk_lib_iip_cp_client_session_task_pt const task, mk_lib_iip_cp_client_shared_pt const shared, mk_lib_iip_cp_client_session_settings_pct const settings) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_destroy(mk_lib_iip_cp_client_session_task_pt const task) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_gimme_msg(mk_lib_iip_cp_client_session_task_pt const task, mk_lib_iip_cp_message_ppt const msg) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_on_msg(mk_lib_iip_cp_client_session_task_pt const task, mk_lib_iip_cp_message_pt const msg) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_rw_step(mk_lib_iip_cp_client_session_task_pt const task, mk_lib_iip_cp_client_session_task_result_pt const step_result) mk_lang_noexcept;


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_ptr_rw_construct_void(mk_lib_iip_cp_client_session_task_ppt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_ptr_rw_destroy(mk_lib_iip_cp_client_session_task_ppt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_ptr_rw_construct_copy(mk_lib_iip_cp_client_session_task_ppt const dst, mk_lib_iip_cp_client_session_task_pcpt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_ptr_rw_construct_move(mk_lib_iip_cp_client_session_task_ppt const dst, mk_lib_iip_cp_client_session_task_ppt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_ptr_rw_assign_copy(mk_lib_iip_cp_client_session_task_ppt const dst, mk_lib_iip_cp_client_session_task_pcpt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_lib_iip_cp_client_session_task_ptr_rw_assign_move(mk_lib_iip_cp_client_session_task_ppt const dst, mk_lib_iip_cp_client_session_task_ppt const src) mk_lang_noexcept;

#define mk_sl_vector_t_name mk_lib_iip_cp_client_session_tasks
#define mk_sl_vector_t_element_type mk_lib_iip_cp_client_session_task_pt
#define mk_sl_vector_t_mallocatorg mk_lib_iip_cp_mallocator_global
#define mk_sl_vector_t_element_construct_void mk_lib_iip_cp_client_session_task_ptr_rw_construct_void
#define mk_sl_vector_t_element_destruct mk_lib_iip_cp_client_session_task_ptr_rw_destroy
#define mk_sl_vector_t_element_copy_construct mk_lib_iip_cp_client_session_task_ptr_rw_construct_copy
#define mk_sl_vector_t_element_move_construct mk_lib_iip_cp_client_session_task_ptr_rw_construct_move
#define mk_sl_vector_t_element_copy_assign mk_lib_iip_cp_client_session_task_ptr_rw_assign_copy
#define mk_sl_vector_t_element_move_assign mk_lib_iip_cp_client_session_task_ptr_rw_assign_move
#include "mk_sl_vector_inl_fileh.h"
#include "mk_sl_vector_inl_fileu.h"


#if mk_lang_jumbo_have
#include "mk_lib_iip_cp_client_session.c"
#endif
#endif
