#undef mk_sl_cui_t_name
#undef mk_sl_cui_t_base
#undef mk_sl_cui_t_count
#undef mk_sl_cui_t_endian
#undef mk_sl_cui_t_str_style
#undef mk_sl_cui_t_disable_big_div
#undef mk_sl_cui_t_base_size_bits_d
#undef mk_sl_cui_t_inline
#undef mk_sl_cui_t_alignas
