#undef mk_sl_sort_merge_inl_defd_proxy_tt
#undef mk_sl_sort_merge_first_roundd

#undef mk_sl_sort_merge_inl_defd_data_t
#undef mk_sl_sort_merge_inl_defd_data_pt
#undef mk_sl_sort_merge_inl_defd_data_prt
#undef mk_sl_sort_merge_inl_defd_data_pct
#undef mk_sl_sort_merge_inl_defd_data_prct
#undef mk_sl_sort_merge_inl_defd_proxy_t
#undef mk_sl_sort_merge_inl_defd_proxy_pt
#undef mk_sl_sort_merge_inl_defd_proxy_prt
#undef mk_sl_sort_merge_inl_defd_proxy_pct
#undef mk_sl_sort_merge_inl_defd_proxy_prct
#undef mk_sl_sort_merge_inl_defd_count_t

#undef mk_sl_sort_merge_inl_defd_first_round

#undef mk_sl_sort_merge_inl_defd_count_count_leading_zeros

#undef mk_sl_sort_merge_inl_defd_fn_is_sorted_plain
#undef mk_sl_sort_merge_inl_defd_fn_is_sorted_proxy
#undef mk_sl_sort_merge_inl_defd_fn_first_round_plain_inplace
#undef mk_sl_sort_merge_inl_defd_fn_first_round_plain_copy
#undef mk_sl_sort_merge_inl_defd_fn_first_round_plain
#undef mk_sl_sort_merge_inl_defd_fn_first_round_proxy_inplace
#undef mk_sl_sort_merge_inl_defd_fn_first_round_proxy_copy
#undef mk_sl_sort_merge_inl_defd_fn_first_round_proxy
#undef mk_sl_sort_merge_inl_defd_fn_merge_plain
#undef mk_sl_sort_merge_inl_defd_fn_merge_proxy
#undef mk_sl_sort_merge_inl_defd_fn_plain
#undef mk_sl_sort_merge_inl_defd_fn_proxy
