#undef mk_sl_buffer_inl_defd_buffer_s
#undef mk_sl_buffer_inl_defd_buffer_t
#undef mk_sl_buffer_inl_defd_buffer_ct
#undef mk_sl_buffer_inl_defd_buffer_pt
#undef mk_sl_buffer_inl_defd_buffer_pct

#undef mk_sl_buffer_inl_defd_buffer_ro_destroy
#undef mk_sl_buffer_inl_defd_buffer_ro_get_data
#undef mk_sl_buffer_inl_defd_buffer_ro_get_size
#undef mk_sl_buffer_inl_defd_buffer_ro_is_empty
#undef mk_sl_buffer_inl_defd_buffer_ro_get_data_at

#undef mk_sl_buffer_inl_defd_buffer_rw_construct
#undef mk_sl_buffer_inl_defd_buffer_rw_destroy
#undef mk_sl_buffer_inl_defd_buffer_rw_get_data
#undef mk_sl_buffer_inl_defd_buffer_rw_get_size
#undef mk_sl_buffer_inl_defd_buffer_rw_is_empty
#undef mk_sl_buffer_inl_defd_buffer_rw_get_data_at
#undef mk_sl_buffer_inl_defd_buffer_rw_resize

#undef mk_sl_buffer_inl_defd_mallocator_allocate
#undef mk_sl_buffer_inl_defd_mallocator_deallocate
#undef mk_sl_buffer_inl_defd_mallocator_reallocate
