#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"
#include "mk_lang_version.h"


#include "mk_sl_dynamic_ring_inl_defd.h"


typedef mk_sl_dynamic_ring_inl_defd_element_type mk_sl_dynamic_ring_inl_defd_element_t;
mk_lang_typedef(mk_sl_dynamic_ring_inl_defd_element);


#if mk_lang_version_at_least_cpp_11 || mk_lang_version_at_least_msvc_cpp_11
enum class mk_sl_dynamic_ring_inl_defd_max_capacity_e : mk_lang_types_usize_t { mk_sl_dynamic_ring_inl_defd_max_capacity_v = mk_sl_dynamic_ring_inl_defd_max_capacity_d }; typedef enum mk_sl_dynamic_ring_inl_defd_max_capacity_e mk_sl_dynamic_ring_inl_defd_max_capacity_t;
#elif mk_lang_version_at_least_c_23
enum mk_sl_dynamic_ring_inl_defd_max_capacity_e : mk_lang_types_usize_t { mk_sl_dynamic_ring_inl_defd_max_capacity_v = mk_sl_dynamic_ring_inl_defd_max_capacity_d }; typedef enum mk_sl_dynamic_ring_inl_defd_max_capacity_e mk_sl_dynamic_ring_inl_defd_max_capacity_t;
#else
#include "mk_lang_warning_msvc_push_c4309.h"
enum mk_sl_dynamic_ring_inl_defd_max_capacity_e { mk_sl_dynamic_ring_inl_defd_max_capacity_v = mk_sl_dynamic_ring_inl_defd_max_capacity_d }; typedef enum mk_sl_dynamic_ring_inl_defd_max_capacity_e mk_sl_dynamic_ring_inl_defd_max_capacity_t;
#include "mk_lang_warning_msvc_pop.h"
#endif


struct mk_sl_dynamic_ring_inl_defd_s
{
	mk_sl_dynamic_ring_inl_defd_element_pt m_buffer;
	mk_lang_types_usize_t m_capacity;
	mk_lang_types_usize_t m_read;
	mk_lang_types_usize_t m_write;
	mk_sl_dynamic_ring_inl_defd_mallocator_member
};
typedef struct mk_sl_dynamic_ring_inl_defd_s mk_sl_dynamic_ring_inl_defd_t;
mk_lang_typedef(mk_sl_dynamic_ring_inl_defd);


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_usize_t mk_sl_dynamic_ring_inl_defd_ro_get_capacity(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_usize_t mk_sl_dynamic_ring_inl_defd_ro_get_size(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_ro_get_sise(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_usize_t mk_sl_dynamic_ring_inl_defd_ro_get_free_size(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_bool_t mk_sl_dynamic_ring_inl_defd_ro_is_empty(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_bool_t mk_sl_dynamic_ring_inl_defd_ro_is_full(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_sl_dynamic_ring_inl_defd_element_pct mk_sl_dynamic_ring_inl_defd_ro_get_front(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_sl_dynamic_ring_inl_defd_element_pct mk_sl_dynamic_ring_inl_defd_ro_get_back(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_usize_t mk_sl_dynamic_ring_inl_defd_ro_get_size_a(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_ro_get_sise_a(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_sl_dynamic_ring_inl_defd_element_pct mk_sl_dynamic_ring_inl_defd_ro_get_data_a(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_usize_t mk_sl_dynamic_ring_inl_defd_ro_get_size_b(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_ro_get_sise_b(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_sl_dynamic_ring_inl_defd_element_pct mk_sl_dynamic_ring_inl_defd_ro_get_data_b(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_usize_t mk_sl_dynamic_ring_inl_defd_ro_get_free_size_a(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_sl_dynamic_ring_inl_defd_element_pct mk_sl_dynamic_ring_inl_defd_ro_get_free_data_a(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_usize_t mk_sl_dynamic_ring_inl_defd_ro_get_free_size_b(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_sl_dynamic_ring_inl_defd_element_pct mk_sl_dynamic_ring_inl_defd_ro_get_free_data_b(mk_sl_dynamic_ring_inl_defd_pct const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_sl_dynamic_ring_inl_defd_element_pct mk_sl_dynamic_ring_inl_defd_ro_get_at(mk_sl_dynamic_ring_inl_defd_pct const ring, mk_lang_types_usize_t const idx) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_usize_t mk_sl_dynamic_ring_inl_defd_rw_get_capacity(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_usize_t mk_sl_dynamic_ring_inl_defd_rw_get_size(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_get_sise(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_usize_t mk_sl_dynamic_ring_inl_defd_rw_get_free_size(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_bool_t mk_sl_dynamic_ring_inl_defd_rw_is_empty(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_bool_t mk_sl_dynamic_ring_inl_defd_rw_is_full(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_sl_dynamic_ring_inl_defd_element_pt mk_sl_dynamic_ring_inl_defd_rw_get_front(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_sl_dynamic_ring_inl_defd_element_pt mk_sl_dynamic_ring_inl_defd_rw_get_back(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_usize_t mk_sl_dynamic_ring_inl_defd_rw_get_size_a(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_get_sise_a(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_sl_dynamic_ring_inl_defd_element_pt mk_sl_dynamic_ring_inl_defd_rw_get_data_a(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_usize_t mk_sl_dynamic_ring_inl_defd_rw_get_size_b(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_get_sise_b(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_sl_dynamic_ring_inl_defd_element_pt mk_sl_dynamic_ring_inl_defd_rw_get_data_b(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_usize_t mk_sl_dynamic_ring_inl_defd_rw_get_free_size_a(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_sl_dynamic_ring_inl_defd_element_pt mk_sl_dynamic_ring_inl_defd_rw_get_free_data_a(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_usize_t mk_sl_dynamic_ring_inl_defd_rw_get_free_size_b(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_sl_dynamic_ring_inl_defd_element_pt mk_sl_dynamic_ring_inl_defd_rw_get_free_data_b(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_sl_dynamic_ring_inl_defd_element_pt mk_sl_dynamic_ring_inl_defd_rw_get_at(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_lang_types_usize_t const idx) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_construct(mk_sl_dynamic_ring_inl_defd_pt const ring mk_sl_dynamic_ring_inl_defd_mallocator_param) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_construct_copy(mk_sl_dynamic_ring_inl_defd_pt const dst, mk_sl_dynamic_ring_inl_defd_pct const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_construct_move(mk_sl_dynamic_ring_inl_defd_pt const dst, mk_sl_dynamic_ring_inl_defd_pt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_destroy(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_assign_copy(mk_sl_dynamic_ring_inl_defd_pt const dst, mk_sl_dynamic_ring_inl_defd_pct const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_assign_move(mk_sl_dynamic_ring_inl_defd_pt const dst, mk_sl_dynamic_ring_inl_defd_pt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_reserve_at_least(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_lang_types_usize_t const count) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_reserve_additional(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_lang_types_usize_t const count) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_clear(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_consolidate(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_push_back_void(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_lang_types_usize_t const count) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_push_back_move_many(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_sl_dynamic_ring_inl_defd_element_pt const elements, mk_lang_types_usize_t const count) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_push_back_copy_many(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_sl_dynamic_ring_inl_defd_element_pct const elements, mk_lang_types_usize_t const count) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_push_back_move_single(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_sl_dynamic_ring_inl_defd_element_pt const element) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_push_back_copy_single(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_sl_dynamic_ring_inl_defd_element_pct const element) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_push_front_move_many(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_sl_dynamic_ring_inl_defd_element_pt const elements, mk_lang_types_usize_t const count) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_push_front_copy_many(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_sl_dynamic_ring_inl_defd_element_pct const elements, mk_lang_types_usize_t const count) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_push_front_move_single(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_sl_dynamic_ring_inl_defd_element_pt const element) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_push_front_copy_single(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_sl_dynamic_ring_inl_defd_element_pct const element) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_pop_back_many(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_lang_types_usize_t const count) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_pop_back_single(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_pop_front_many(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_lang_types_usize_t const count) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_pop_front_single(mk_sl_dynamic_ring_inl_defd_pt const ring) mk_lang_noexcept;
/*mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_erase_at(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_lang_types_usize_t const idx) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_erase_element(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_sl_dynamic_ring_inl_defd_element_pct const element) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_inl_defd_rw_erase_value(mk_sl_dynamic_ring_inl_defd_pt const ring, mk_sl_dynamic_ring_inl_defd_element_pct const element) mk_lang_noexcept;*/


#include "mk_sl_dynamic_ring_inl_defu.h"
