include(`mk_sl_cui_inl.m')dnl
#include "mk_lang_alignas.h"
#include "mk_lang_concat.h"
#include "mk_lang_endian.h"
#include "mk_lang_flatten.h"
#include "mk_lang_forceinline.h"
#include "mk_lang_roundup.h"
#include "mk_lang_str_style.h"


#if(!( \
	(defined mk_sl_cui_t_name) && \
	(defined mk_sl_cui_t_base_type_name) && \
	(defined mk_sl_cui_t_count && (mk_sl_cui_t_count) >= 1 && (mk_sl_cui_t_count) <= 16 * 1024) && \
	((defined mk_sl_cui_t_endian && ((mk_sl_cui_t_endian) == mk_lang_endian_little || (mk_sl_cui_t_endian) == mk_lang_endian_big)) || !defined mk_sl_cui_t_endian) && \
	((defined mk_sl_cui_t_str_style && ((mk_sl_cui_t_str_style) == mk_lang_str_style_table || (mk_sl_cui_t_str_style) == mk_lang_str_style_arithmetic || (mk_sl_cui_t_str_style) == mk_lang_str_style_arithmetic_if_possible)) || !defined mk_sl_cui_t_str_style) && \
	((defined mk_sl_cui_t_disable_big_div && ((mk_sl_cui_t_disable_big_div) == 0 || (mk_sl_cui_t_disable_big_div) == 1)) || !defined mk_sl_cui_t_disable_big_div) && \
	((defined mk_sl_cui_t_base_type_size_bits_d && (mk_sl_cui_t_base_type_size_bits_d) >= 1) || !defined mk_sl_cui_t_base_type_size_bits_d) && \
	((defined mk_sl_cui_t_inline && ((mk_sl_cui_t_inline) == 0 || (mk_sl_cui_t_inline) == 1)) || !defined mk_sl_cui_t_inline) && \
	((defined mk_sl_cui_t_alignas && (mk_sl_cui_t_alignas) >= 0 && (mk_sl_cui_t_alignas) <= 64 * 1024) || !defined mk_sl_cui_t_alignas) && \
1))
#error xxxxxxxxxx
#endif


#define mk_sl_cui_inl_defd_name mk_sl_cui_t_name
#define mk_sl_cui_inl_defd_base_type_name mk_sl_cui_t_base_type_name
#define mk_sl_cui_inl_defd_count (mk_sl_cui_t_count)


#if defined mk_sl_cui_t_endian
#define mk_sl_cui_inl_defd_endian (mk_sl_cui_t_endian)
#else
#define mk_sl_cui_inl_defd_endian mk_lang_endian_native
#endif

#if defined mk_sl_cui_t_str_style
#define mk_sl_cui_inl_defd_str_style (mk_sl_cui_t_str_style)
#else
#define mk_sl_cui_inl_defd_str_style mk_lang_str_style_arithmetic_if_possible
#endif

#if defined mk_sl_cui_t_disable_big_div
#define mk_sl_cui_inl_defd_disable_big_div (mk_sl_cui_t_disable_big_div)
#else
#define mk_sl_cui_inl_defd_disable_big_div 0
#endif

#if defined mk_sl_cui_t_base_type_size_bits_d
#define mk_sl_cui_inl_defd_base_size_bits_d (mk_sl_cui_t_base_type_size_bits_d)
#else
#define mk_sl_cui_inl_defd_base_size_bits_d mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _size_bits_d)
#endif

#if defined mk_sl_cui_t_inline
#define mk_sl_cui_inl_defd_inline (mk_sl_cui_t_inline)
#else
#define mk_sl_cui_inl_defd_inline 0
#endif

#if defined mk_sl_cui_t_alignas
#define mk_sl_cui_inl_defd_alignas (mk_sl_cui_t_alignas)
#else
#define mk_sl_cui_inl_defd_alignas 0
#endif


#if mk_sl_cui_inl_defd_inline
#define mk_sl_cui_inl_defd_flatten mk_lang_flatten
#define mk_sl_cui_inl_defd_forceinline mk_lang_forceinline
#else
#define mk_sl_cui_inl_defd_flatten
#define mk_sl_cui_inl_defd_forceinline
#endif

#if mk_sl_cui_inl_defd_alignas == 0
#define mk_sl_cui_inl_defd_alignme
#else
#define mk_sl_cui_inl_defd_alignme mk_lang_alignas(mk_sl_cui_inl_defd_alignas)
#endif


#define mk_sl_cui_inl_defd_base_type_t mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _t)

#define mk_sl_cui_inl_defd_base mk_lang_concat(mk_sl_cui_inl_defd_name, _base)

#define mk_sl_cui_inl_defd_base_t mk_lang_concat(mk_sl_cui_inl_defd_name, _base_t)
#define mk_sl_cui_inl_defd_base_ct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_ct)
#define mk_sl_cui_inl_defd_base_vt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_vt)
#define mk_sl_cui_inl_defd_base_cvt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_cvt)
#define mk_sl_cui_inl_defd_base_pt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_pt)
#define mk_sl_cui_inl_defd_base_pct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_pct)
#define mk_sl_cui_inl_defd_base_pvt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_pvt)
#define mk_sl_cui_inl_defd_base_pcvt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_pcvt)
#define mk_sl_cui_inl_defd_base_prt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_prt)
#define mk_sl_cui_inl_defd_base_prct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_prct)
#define mk_sl_cui_inl_defd_base_prvt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_prvt)
#define mk_sl_cui_inl_defd_base_prcvt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_prcvt)
#define mk_sl_cui_inl_defd_base_lpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lpt)
#define mk_sl_cui_inl_defd_base_lpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lpct)
#define mk_sl_cui_inl_defd_base_lpvt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lpvt)
#define mk_sl_cui_inl_defd_base_lpcvt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lpcvt)
#define mk_sl_cui_inl_defd_base_lprt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lprt)
#define mk_sl_cui_inl_defd_base_lprct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lprct)
#define mk_sl_cui_inl_defd_base_lprvt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lprvt)
#define mk_sl_cui_inl_defd_base_lprcvt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lprcvt)
#define mk_sl_cui_inl_defd_base_npt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_npt)
#define mk_sl_cui_inl_defd_base_npct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_npct)
#define mk_sl_cui_inl_defd_base_npvt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_npvt)
#define mk_sl_cui_inl_defd_base_npcvt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_npcvt)
#define mk_sl_cui_inl_defd_base_nprt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_nprt)
#define mk_sl_cui_inl_defd_base_nprct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_nprct)
#define mk_sl_cui_inl_defd_base_nprvt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_nprvt)
#define mk_sl_cui_inl_defd_base_nprcvt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_nprcvt)
#define mk_sl_cui_inl_defd_base_cpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_cpt)
#define mk_sl_cui_inl_defd_base_vpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_vpt)
#define mk_sl_cui_inl_defd_base_cvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_cvpt)
#define mk_sl_cui_inl_defd_base_ppt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_ppt)
#define mk_sl_cui_inl_defd_base_pcpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_pcpt)
#define mk_sl_cui_inl_defd_base_pvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_pvpt)
#define mk_sl_cui_inl_defd_base_pcvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_pcvpt)
#define mk_sl_cui_inl_defd_base_prpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_prpt)
#define mk_sl_cui_inl_defd_base_prcpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_prcpt)
#define mk_sl_cui_inl_defd_base_prvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_prvpt)
#define mk_sl_cui_inl_defd_base_prcvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_prcvpt)
#define mk_sl_cui_inl_defd_base_lppt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lppt)
#define mk_sl_cui_inl_defd_base_lpcpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lpcpt)
#define mk_sl_cui_inl_defd_base_lpvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lpvpt)
#define mk_sl_cui_inl_defd_base_lpcvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lpcvpt)
#define mk_sl_cui_inl_defd_base_lprpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lprpt)
#define mk_sl_cui_inl_defd_base_lprcpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lprcpt)
#define mk_sl_cui_inl_defd_base_lprvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lprvpt)
#define mk_sl_cui_inl_defd_base_lprcvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lprcvpt)
#define mk_sl_cui_inl_defd_base_nppt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_nppt)
#define mk_sl_cui_inl_defd_base_npcpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_npcpt)
#define mk_sl_cui_inl_defd_base_npvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_npvpt)
#define mk_sl_cui_inl_defd_base_npcvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_npcvpt)
#define mk_sl_cui_inl_defd_base_nprpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_nprpt)
#define mk_sl_cui_inl_defd_base_nprcpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_nprcpt)
#define mk_sl_cui_inl_defd_base_nprvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_nprvpt)
#define mk_sl_cui_inl_defd_base_nprcvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _base_nprcvpt)
#define mk_sl_cui_inl_defd_base_cpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_cpct)
#define mk_sl_cui_inl_defd_base_vpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_vpct)
#define mk_sl_cui_inl_defd_base_cvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_cvpct)
#define mk_sl_cui_inl_defd_base_ppct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_ppct)
#define mk_sl_cui_inl_defd_base_pcpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_pcpct)
#define mk_sl_cui_inl_defd_base_pvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_pvpct)
#define mk_sl_cui_inl_defd_base_pcvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_pcvpct)
#define mk_sl_cui_inl_defd_base_prpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_prpct)
#define mk_sl_cui_inl_defd_base_prcpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_prcpct)
#define mk_sl_cui_inl_defd_base_prvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_prvpct)
#define mk_sl_cui_inl_defd_base_prcvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_prcvpct)
#define mk_sl_cui_inl_defd_base_lppct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lppct)
#define mk_sl_cui_inl_defd_base_lpcpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lpcpct)
#define mk_sl_cui_inl_defd_base_lpvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lpvpct)
#define mk_sl_cui_inl_defd_base_lpcvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lpcvpct)
#define mk_sl_cui_inl_defd_base_lprpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lprpct)
#define mk_sl_cui_inl_defd_base_lprcpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lprcpct)
#define mk_sl_cui_inl_defd_base_lprvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lprvpct)
#define mk_sl_cui_inl_defd_base_lprcvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_lprcvpct)
#define mk_sl_cui_inl_defd_base_nppct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_nppct)
#define mk_sl_cui_inl_defd_base_npcpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_npcpct)
#define mk_sl_cui_inl_defd_base_npvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_npvpct)
#define mk_sl_cui_inl_defd_base_npcvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_npcvpct)
#define mk_sl_cui_inl_defd_base_nprpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_nprpct)
#define mk_sl_cui_inl_defd_base_nprcpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_nprcpct)
#define mk_sl_cui_inl_defd_base_nprvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_nprvpct)
#define mk_sl_cui_inl_defd_base_nprcvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _base_nprcvpct)

#define mk_sl_cui_inl_defd_base_from_base mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _from_base)
mm_per_bi(`#define mk_sl_cui_inl_defd_base_from_bi_$1 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _from_bi_$1)')
#define mk_sl_cui_inl_defd_base_to_base mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_base)
mm_per_bi(`#define mk_sl_cui_inl_defd_base_to_bi_$1 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_bi_$1)')
mm_per_bui(`#define mk_sl_cui_inl_defd_base_from_buis_$1_le mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _from_buis_$1_le)')
mm_per_bui(`#define mk_sl_cui_inl_defd_base_to_buis_$1_le mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_buis_$1_le)')
mm_per_bui(`#define mk_sl_cui_inl_defd_base_from_buis_$1_be mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _from_buis_$1_be)')
mm_per_bui(`#define mk_sl_cui_inl_defd_base_to_buis_$1_be mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_buis_$1_be)')
#define mk_sl_cui_inl_defd_base_assign mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _assign)
#define mk_sl_cui_inl_defd_base_set_zero mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _set_zero)
#define mk_sl_cui_inl_defd_base_set_max mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _set_max)
#define mk_sl_cui_inl_defd_base_set_one mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _set_one)
#define mk_sl_cui_inl_defd_base_set_two mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _set_two)
#define mk_sl_cui_inl_defd_base_set_bit mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _set_bit)
#define mk_sl_cui_inl_defd_base_set_mask mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _set_mask)
#define mk_sl_cui_inl_defd_base_count_leading_zeros mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _count_leading_zeros)
#define mk_sl_cui_inl_defd_base_count_leading_ones mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _count_leading_ones)
#define mk_sl_cui_inl_defd_base_count_trailing_zeros mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _count_trailing_zeros)
#define mk_sl_cui_inl_defd_base_count_trailing_ones mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _count_trailing_ones)
#define mk_sl_cui_inl_defd_base_count_ones mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _count_ones)
#define mk_sl_cui_inl_defd_base_count_zeros mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _count_zeros)
#define mk_sl_cui_inl_defd_base_has_msb mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _has_msb)
#define mk_sl_cui_inl_defd_base_has_lsb mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _has_lsb)
#define mk_sl_cui_inl_defd_base_is_zero mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _is_zero)
#define mk_sl_cui_inl_defd_base_is_one mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _is_one)
#define mk_sl_cui_inl_defd_base_is_two mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _is_two)
#define mk_sl_cui_inl_defd_base_is_max mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _is_max)
#define mk_sl_cui_inl_defd_base_is_bit mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _is_bit)
#define mk_sl_cui_inl_defd_base_eq mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _eq)
#define mk_sl_cui_inl_defd_base_ne mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _ne)
#define mk_sl_cui_inl_defd_base_lt mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _lt)
#define mk_sl_cui_inl_defd_base_le mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _le)
#define mk_sl_cui_inl_defd_base_gt mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _gt)
#define mk_sl_cui_inl_defd_base_ge mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _ge)
#define mk_sl_cui_inl_defd_base_cmp mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _cmp)
#define mk_sl_cui_inl_defd_base_inc2 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _inc2)
#define mk_sl_cui_inl_defd_base_dec2 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _dec2)
#define mk_sl_cui_inl_defd_base_inc1 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _inc1)
#define mk_sl_cui_inl_defd_base_dec1 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _dec1)
#define mk_sl_cui_inl_defd_base_not2 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _not2)
#define mk_sl_cui_inl_defd_base_or3 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _or3)
#define mk_sl_cui_inl_defd_base_and3 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _and3)
#define mk_sl_cui_inl_defd_base_xor3 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _xor3)
#define mk_sl_cui_inl_defd_base_not1 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _not1)
#define mk_sl_cui_inl_defd_base_or2 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _or2)
#define mk_sl_cui_inl_defd_base_and2 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _and2)
#define mk_sl_cui_inl_defd_base_xor2 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _xor2)
#define mk_sl_cui_inl_defd_base_shl3 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _shl3)
#define mk_sl_cui_inl_defd_base_shr3 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _shr3)
#define mk_sl_cui_inl_defd_base_rotl3 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _rotl3)
#define mk_sl_cui_inl_defd_base_rotr3 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _rotr3)
#define mk_sl_cui_inl_defd_base_shl2 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _shl2)
#define mk_sl_cui_inl_defd_base_shr2 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _shr2)
#define mk_sl_cui_inl_defd_base_rotl2 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _rotl2)
#define mk_sl_cui_inl_defd_base_rotr2 mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _rotr2)
#define mk_sl_cui_inl_defd_base_would_overflow_add_cc mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _would_overflow_add_cc)
#define mk_sl_cui_inl_defd_base_would_overflow_add_cs mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _would_overflow_add_cs)
#define mk_sl_cui_inl_defd_base_would_overflow_add_cp mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _would_overflow_add_cp)
#define mk_sl_cui_inl_defd_base_would_overflow_sub_cc mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _would_overflow_sub_cc)
#define mk_sl_cui_inl_defd_base_would_overflow_sub_cs mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _would_overflow_sub_cs)
#define mk_sl_cui_inl_defd_base_would_overflow_sub_cp mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _would_overflow_sub_cp)
#define mk_sl_cui_inl_defd_base_would_overflow_mul mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _would_overflow_mul)
#define mk_sl_cui_inl_defd_base_add3_wrap_cid_cod mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _add3_wrap_cid_cod)
#define mk_sl_cui_inl_defd_base_add3_wrap_cid_coe mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _add3_wrap_cid_coe)
#define mk_sl_cui_inl_defd_base_add3_wrap_cie_cod mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _add3_wrap_cie_cod)
#define mk_sl_cui_inl_defd_base_add3_wrap_cie_coe mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _add3_wrap_cie_coe)
#define mk_sl_cui_inl_defd_base_add2_wrap_cid_cod mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _add2_wrap_cid_cod)
#define mk_sl_cui_inl_defd_base_add2_wrap_cid_coe mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _add2_wrap_cid_coe)
#define mk_sl_cui_inl_defd_base_add2_wrap_cie_cod mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _add2_wrap_cie_cod)
#define mk_sl_cui_inl_defd_base_add2_wrap_cie_coe mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _add2_wrap_cie_coe)
#define mk_sl_cui_inl_defd_base_sub3_wrap_cid_cod mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _sub3_wrap_cid_cod)
#define mk_sl_cui_inl_defd_base_sub3_wrap_cid_coe mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _sub3_wrap_cid_coe)
#define mk_sl_cui_inl_defd_base_sub3_wrap_cie_cod mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _sub3_wrap_cie_cod)
#define mk_sl_cui_inl_defd_base_sub3_wrap_cie_coe mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _sub3_wrap_cie_coe)
#define mk_sl_cui_inl_defd_base_sub2_wrap_cid_cod mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _sub2_wrap_cid_cod)
#define mk_sl_cui_inl_defd_base_sub2_wrap_cid_coe mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _sub2_wrap_cid_coe)
#define mk_sl_cui_inl_defd_base_sub2_wrap_cie_cod mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _sub2_wrap_cie_cod)
#define mk_sl_cui_inl_defd_base_sub2_wrap_cie_coe mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _sub2_wrap_cie_coe)
#define mk_sl_cui_inl_defd_base_mul3_wrap_lo mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _mul3_wrap_lo)
#define mk_sl_cui_inl_defd_base_mul3_wrap_hi mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _mul3_wrap_hi)
#define mk_sl_cui_inl_defd_base_mul4_wrap_wi mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _mul4_wrap_wi)
#define mk_sl_cui_inl_defd_base_mul2_wrap_lo mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _mul2_wrap_lo)
#define mk_sl_cui_inl_defd_base_mul2_wrap_hi mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _mul2_wrap_hi)
#define mk_sl_cui_inl_defd_base_mul2_wrap_wi mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _mul2_wrap_wi)
#define mk_sl_cui_inl_defd_base_div3_wrap mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _div3_wrap)
#define mk_sl_cui_inl_defd_base_mod3_wrap mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _mod3_wrap)
#define mk_sl_cui_inl_defd_base_divmod4_wrap mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _divmod4_wrap)
#define mk_sl_cui_inl_defd_base_div2_wrap mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _div2_wrap)
#define mk_sl_cui_inl_defd_base_mod2_wrap mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _mod2_wrap)
#define mk_sl_cui_inl_defd_base_divmod2_wrap mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _divmod2_wrap)
#define mk_sl_cui_inl_defd_base_to_str_bin_n mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_str_bin_n)
#define mk_sl_cui_inl_defd_base_to_str_bin_w mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_str_bin_w)
#define mk_sl_cui_inl_defd_base_from_str_bin_n mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _from_str_bin_n)
#define mk_sl_cui_inl_defd_base_from_str_bin_w mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _from_str_bin_w)
#define mk_sl_cui_inl_defd_base_to_str_oct_n mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_str_oct_n)
#define mk_sl_cui_inl_defd_base_to_str_oct_w mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_str_oct_w)
#define mk_sl_cui_inl_defd_base_from_str_oct_n mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _from_str_oct_n)
#define mk_sl_cui_inl_defd_base_from_str_oct_w mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _from_str_oct_w)
#define mk_sl_cui_inl_defd_base_to_str_dec_n mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_str_dec_n)
#define mk_sl_cui_inl_defd_base_to_str_dec_w mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_str_dec_w)
#define mk_sl_cui_inl_defd_base_from_str_dec_n mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _from_str_dec_n)
#define mk_sl_cui_inl_defd_base_from_str_dec_w mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _from_str_dec_w)
#define mk_sl_cui_inl_defd_base_to_str_hex_n mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_str_hex_n)
#define mk_sl_cui_inl_defd_base_to_str_hex_w mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_str_hex_w)
#define mk_sl_cui_inl_defd_base_from_str_hex_n mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _from_str_hex_n)
#define mk_sl_cui_inl_defd_base_from_str_hex_w mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _from_str_hex_w)
#define mk_sl_cui_inl_defd_base_from_str_hex_many_n mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _from_str_hex_many_n)
#define mk_sl_cui_inl_defd_base_from_str_hex_many_w mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _from_str_hex_many_w)
#define mk_sl_cui_inl_defd_base_to_str_binf_n mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_str_binf_n)
#define mk_sl_cui_inl_defd_base_to_str_binf_w mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_str_binf_w)
#define mk_sl_cui_inl_defd_base_to_str_hexf_n mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_str_hexf_n)
#define mk_sl_cui_inl_defd_base_to_str_hexf_w mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_str_hexf_w)
#define mk_sl_cui_inl_defd_base_to_str_hexf_many_n mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_str_hexf_many_n)
#define mk_sl_cui_inl_defd_base_to_str_hexf_many_w mk_lang_concat(mk_sl_cui_inl_defd_base_type_name, _to_str_hexf_many_w)


#if mk_sl_cui_inl_defd_endian == mk_lang_endian_little
#define mk_sl_cui_inl_defd_idx(idx) ((idx))
#elif mk_sl_cui_inl_defd_endian == mk_lang_endian_big
#define mk_sl_cui_inl_defd_idx(idx) (((mk_sl_cui_inl_defd_count) - 1) - (idx))
#else
#error xxxxxxxxxx
#endif

#define mk_sl_cui_inl_defd_s mk_lang_concat(mk_sl_cui_inl_defd_name, _s)
#define mk_sl_cui_inl_defd_t mk_lang_concat(mk_sl_cui_inl_defd_name, _t)
#define mk_sl_cui_inl_defd_ct mk_lang_concat(mk_sl_cui_inl_defd_name, _ct)
#define mk_sl_cui_inl_defd_vt mk_lang_concat(mk_sl_cui_inl_defd_name, _vt)
#define mk_sl_cui_inl_defd_cvt mk_lang_concat(mk_sl_cui_inl_defd_name, _cvt)
#define mk_sl_cui_inl_defd_pt mk_lang_concat(mk_sl_cui_inl_defd_name, _pt)
#define mk_sl_cui_inl_defd_pct mk_lang_concat(mk_sl_cui_inl_defd_name, _pct)
#define mk_sl_cui_inl_defd_pvt mk_lang_concat(mk_sl_cui_inl_defd_name, _pvt)
#define mk_sl_cui_inl_defd_pcvt mk_lang_concat(mk_sl_cui_inl_defd_name, _pcvt)
#define mk_sl_cui_inl_defd_prt mk_lang_concat(mk_sl_cui_inl_defd_name, _prt)
#define mk_sl_cui_inl_defd_prct mk_lang_concat(mk_sl_cui_inl_defd_name, _prct)
#define mk_sl_cui_inl_defd_prvt mk_lang_concat(mk_sl_cui_inl_defd_name, _prvt)
#define mk_sl_cui_inl_defd_prcvt mk_lang_concat(mk_sl_cui_inl_defd_name, _prcvt)
#define mk_sl_cui_inl_defd_lpt mk_lang_concat(mk_sl_cui_inl_defd_name, _lpt)
#define mk_sl_cui_inl_defd_lpct mk_lang_concat(mk_sl_cui_inl_defd_name, _lpct)
#define mk_sl_cui_inl_defd_lpvt mk_lang_concat(mk_sl_cui_inl_defd_name, _lpvt)
#define mk_sl_cui_inl_defd_lpcvt mk_lang_concat(mk_sl_cui_inl_defd_name, _lpcvt)
#define mk_sl_cui_inl_defd_lprt mk_lang_concat(mk_sl_cui_inl_defd_name, _lprt)
#define mk_sl_cui_inl_defd_lprct mk_lang_concat(mk_sl_cui_inl_defd_name, _lprct)
#define mk_sl_cui_inl_defd_lprvt mk_lang_concat(mk_sl_cui_inl_defd_name, _lprvt)
#define mk_sl_cui_inl_defd_lprcvt mk_lang_concat(mk_sl_cui_inl_defd_name, _lprcvt)
#define mk_sl_cui_inl_defd_npt mk_lang_concat(mk_sl_cui_inl_defd_name, _npt)
#define mk_sl_cui_inl_defd_npct mk_lang_concat(mk_sl_cui_inl_defd_name, _npct)
#define mk_sl_cui_inl_defd_npvt mk_lang_concat(mk_sl_cui_inl_defd_name, _npvt)
#define mk_sl_cui_inl_defd_npcvt mk_lang_concat(mk_sl_cui_inl_defd_name, _npcvt)
#define mk_sl_cui_inl_defd_nprt mk_lang_concat(mk_sl_cui_inl_defd_name, _nprt)
#define mk_sl_cui_inl_defd_nprct mk_lang_concat(mk_sl_cui_inl_defd_name, _nprct)
#define mk_sl_cui_inl_defd_nprvt mk_lang_concat(mk_sl_cui_inl_defd_name, _nprvt)
#define mk_sl_cui_inl_defd_nprcvt mk_lang_concat(mk_sl_cui_inl_defd_name, _nprcvt)
#define mk_sl_cui_inl_defd_cpt mk_lang_concat(mk_sl_cui_inl_defd_name, _cpt)
#define mk_sl_cui_inl_defd_vpt mk_lang_concat(mk_sl_cui_inl_defd_name, _vpt)
#define mk_sl_cui_inl_defd_cvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _cvpt)
#define mk_sl_cui_inl_defd_ppt mk_lang_concat(mk_sl_cui_inl_defd_name, _ppt)
#define mk_sl_cui_inl_defd_pcpt mk_lang_concat(mk_sl_cui_inl_defd_name, _pcpt)
#define mk_sl_cui_inl_defd_pvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _pvpt)
#define mk_sl_cui_inl_defd_pcvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _pcvpt)
#define mk_sl_cui_inl_defd_prpt mk_lang_concat(mk_sl_cui_inl_defd_name, _prpt)
#define mk_sl_cui_inl_defd_prcpt mk_lang_concat(mk_sl_cui_inl_defd_name, _prcpt)
#define mk_sl_cui_inl_defd_prvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _prvpt)
#define mk_sl_cui_inl_defd_prcvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _prcvpt)
#define mk_sl_cui_inl_defd_lppt mk_lang_concat(mk_sl_cui_inl_defd_name, _lppt)
#define mk_sl_cui_inl_defd_lpcpt mk_lang_concat(mk_sl_cui_inl_defd_name, _lpcpt)
#define mk_sl_cui_inl_defd_lpvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _lpvpt)
#define mk_sl_cui_inl_defd_lpcvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _lpcvpt)
#define mk_sl_cui_inl_defd_lprpt mk_lang_concat(mk_sl_cui_inl_defd_name, _lprpt)
#define mk_sl_cui_inl_defd_lprcpt mk_lang_concat(mk_sl_cui_inl_defd_name, _lprcpt)
#define mk_sl_cui_inl_defd_lprvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _lprvpt)
#define mk_sl_cui_inl_defd_lprcvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _lprcvpt)
#define mk_sl_cui_inl_defd_nppt mk_lang_concat(mk_sl_cui_inl_defd_name, _nppt)
#define mk_sl_cui_inl_defd_npcpt mk_lang_concat(mk_sl_cui_inl_defd_name, _npcpt)
#define mk_sl_cui_inl_defd_npvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _npvpt)
#define mk_sl_cui_inl_defd_npcvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _npcvpt)
#define mk_sl_cui_inl_defd_nprpt mk_lang_concat(mk_sl_cui_inl_defd_name, _nprpt)
#define mk_sl_cui_inl_defd_nprcpt mk_lang_concat(mk_sl_cui_inl_defd_name, _nprcpt)
#define mk_sl_cui_inl_defd_nprvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _nprvpt)
#define mk_sl_cui_inl_defd_nprcvpt mk_lang_concat(mk_sl_cui_inl_defd_name, _nprcvpt)
#define mk_sl_cui_inl_defd_cpct mk_lang_concat(mk_sl_cui_inl_defd_name, _cpct)
#define mk_sl_cui_inl_defd_vpct mk_lang_concat(mk_sl_cui_inl_defd_name, _vpct)
#define mk_sl_cui_inl_defd_cvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _cvpct)
#define mk_sl_cui_inl_defd_ppct mk_lang_concat(mk_sl_cui_inl_defd_name, _ppct)
#define mk_sl_cui_inl_defd_pcpct mk_lang_concat(mk_sl_cui_inl_defd_name, _pcpct)
#define mk_sl_cui_inl_defd_pvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _pvpct)
#define mk_sl_cui_inl_defd_pcvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _pcvpct)
#define mk_sl_cui_inl_defd_prpct mk_lang_concat(mk_sl_cui_inl_defd_name, _prpct)
#define mk_sl_cui_inl_defd_prcpct mk_lang_concat(mk_sl_cui_inl_defd_name, _prcpct)
#define mk_sl_cui_inl_defd_prvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _prvpct)
#define mk_sl_cui_inl_defd_prcvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _prcvpct)
#define mk_sl_cui_inl_defd_lppct mk_lang_concat(mk_sl_cui_inl_defd_name, _lppct)
#define mk_sl_cui_inl_defd_lpcpct mk_lang_concat(mk_sl_cui_inl_defd_name, _lpcpct)
#define mk_sl_cui_inl_defd_lpvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _lpvpct)
#define mk_sl_cui_inl_defd_lpcvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _lpcvpct)
#define mk_sl_cui_inl_defd_lprpct mk_lang_concat(mk_sl_cui_inl_defd_name, _lprpct)
#define mk_sl_cui_inl_defd_lprcpct mk_lang_concat(mk_sl_cui_inl_defd_name, _lprcpct)
#define mk_sl_cui_inl_defd_lprvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _lprvpct)
#define mk_sl_cui_inl_defd_lprcvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _lprcvpct)
#define mk_sl_cui_inl_defd_nppct mk_lang_concat(mk_sl_cui_inl_defd_name, _nppct)
#define mk_sl_cui_inl_defd_npcpct mk_lang_concat(mk_sl_cui_inl_defd_name, _npcpct)
#define mk_sl_cui_inl_defd_npvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _npvpct)
#define mk_sl_cui_inl_defd_npcvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _npcvpct)
#define mk_sl_cui_inl_defd_nprpct mk_lang_concat(mk_sl_cui_inl_defd_name, _nprpct)
#define mk_sl_cui_inl_defd_nprcpct mk_lang_concat(mk_sl_cui_inl_defd_name, _nprcpct)
#define mk_sl_cui_inl_defd_nprvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _nprvpct)
#define mk_sl_cui_inl_defd_nprcvpct mk_lang_concat(mk_sl_cui_inl_defd_name, _nprcvpct)

#define mk_sl_cui_inl_defd_size_bits_d (mk_sl_cui_inl_defd_count * mk_sl_cui_inl_defd_base_size_bits_d)
#define mk_sl_cui_inl_defd_size_bits_e mk_lang_concat(mk_sl_cui_inl_defd_name, _size_bits_e)
#define mk_sl_cui_inl_defd_size_bits_t mk_lang_concat(mk_sl_cui_inl_defd_name, _size_bits_t)
#define mk_sl_cui_inl_defd_size_bits_v mk_lang_concat(mk_sl_cui_inl_defd_name, _size_bits_v)

#define mk_sl_cui_inl_defd_size_bytes_d (mk_lang_roundup_div((mk_sl_cui_inl_defd_size_bits_d), (mk_lang_charbit)))
#define mk_sl_cui_inl_defd_size_bytes_e mk_lang_concat(mk_sl_cui_inl_defd_name, _size_bytes_e)
#define mk_sl_cui_inl_defd_size_bytes_t mk_lang_concat(mk_sl_cui_inl_defd_name, _size_bytes_t)
#define mk_sl_cui_inl_defd_size_bytes_v mk_lang_concat(mk_sl_cui_inl_defd_name, _size_bytes_v)

#define mk_sl_cui_inl_defd_strlen_dec_log 19728ul /* floor(log10(2) * (2^16)) */

#define mk_sl_cui_inl_defd_strlen_bin_d mk_sl_cui_inl_defd_size_bits_d
#define mk_sl_cui_inl_defd_strlen_bin_e mk_lang_concat(mk_sl_cui_inl_defd_name, _strlen_bin_e)
#define mk_sl_cui_inl_defd_strlen_bin_t mk_lang_concat(mk_sl_cui_inl_defd_name, _strlen_bin_t)
#define mk_sl_cui_inl_defd_strlen_bin_v mk_lang_concat(mk_sl_cui_inl_defd_name, _strlen_bin_v)

#define mk_sl_cui_inl_defd_strlen_oct_d mk_lang_roundup_div(mk_sl_cui_inl_defd_size_bits_d, 3)
#define mk_sl_cui_inl_defd_strlen_oct_e mk_lang_concat(mk_sl_cui_inl_defd_name, _strlen_oct_e)
#define mk_sl_cui_inl_defd_strlen_oct_t mk_lang_concat(mk_sl_cui_inl_defd_name, _strlen_oct_t)
#define mk_sl_cui_inl_defd_strlen_oct_v mk_lang_concat(mk_sl_cui_inl_defd_name, _strlen_oct_v)

#define mk_sl_cui_inl_defd_strlen_dec_d (((mk_sl_cui_inl_defd_size_bits_d * mk_sl_cui_inl_defd_strlen_dec_log) >> 16) + 1)
#define mk_sl_cui_inl_defd_strlen_dec_e mk_lang_concat(mk_sl_cui_inl_defd_name, _strlen_dec_e)
#define mk_sl_cui_inl_defd_strlen_dec_t mk_lang_concat(mk_sl_cui_inl_defd_name, _strlen_dec_t)
#define mk_sl_cui_inl_defd_strlen_dec_v mk_lang_concat(mk_sl_cui_inl_defd_name, _strlen_dec_v)

#define mk_sl_cui_inl_defd_strlen_hex_d mk_lang_roundup_div(mk_sl_cui_inl_defd_size_bits_d, 4)
#define mk_sl_cui_inl_defd_strlen_hex_e mk_lang_concat(mk_sl_cui_inl_defd_name, _strlen_hex_e)
#define mk_sl_cui_inl_defd_strlen_hex_t mk_lang_concat(mk_sl_cui_inl_defd_name, _strlen_hex_t)
#define mk_sl_cui_inl_defd_strlen_hex_v mk_lang_concat(mk_sl_cui_inl_defd_name, _strlen_hex_v)

#define mk_sl_cui_inl_defd_symbols_bin_a mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_bin_a)
#define mk_sl_cui_inl_defd_symbols_bin_b mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_bin_b)
#define mk_sl_cui_inl_defd_symbols_bin_c mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_bin_c)
#define mk_sl_cui_inl_defd_symbols_bin_d mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_bin_d)
#define mk_sl_cui_inl_defd_symbols_oct_a mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_oct_a)
#define mk_sl_cui_inl_defd_symbols_oct_b mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_oct_b)
#define mk_sl_cui_inl_defd_symbols_oct_c mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_oct_c)
#define mk_sl_cui_inl_defd_symbols_oct_d mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_oct_d)
#define mk_sl_cui_inl_defd_symbols_dec_a mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_dec_a)
#define mk_sl_cui_inl_defd_symbols_dec_b mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_dec_b)
#define mk_sl_cui_inl_defd_symbols_dec_c mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_dec_c)
#define mk_sl_cui_inl_defd_symbols_dec_d mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_dec_d)
#define mk_sl_cui_inl_defd_symbols_hex_a mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_hex_a)
#define mk_sl_cui_inl_defd_symbols_hex_b mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_hex_b)
#define mk_sl_cui_inl_defd_symbols_hex_c mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_hex_c)
#define mk_sl_cui_inl_defd_symbols_hex_C mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_hex_C)
#define mk_sl_cui_inl_defd_symbols_hex_d mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_hex_d)
#define mk_sl_cui_inl_defd_symbols_hex_D mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_hex_D)
#define mk_sl_cui_inl_defd_symbols_bin_e mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_bin_e)
#define mk_sl_cui_inl_defd_symbols_bin_f mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_bin_f)
#define mk_sl_cui_inl_defd_symbols_hex_e mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_hex_e)
#define mk_sl_cui_inl_defd_symbols_hex_f mk_lang_concat(mk_sl_cui_inl_defd_name, _symbols_hex_f)

#define mk_sl_cui_inl_defd_pr_from_base mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_base)
mm_per_bi(`#define mk_sl_cui_inl_defd_pr_from_bi_$1 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_bi_$1)')
#define mk_sl_cui_inl_defd_pr_to_base mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_base)
mm_per_bi(`#define mk_sl_cui_inl_defd_pr_to_bi_$1 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_bi_$1)')
mm_per_bui(`#define mk_sl_cui_inl_defd_pr_from_buis_$1_le mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_buis_$1_le)')
mm_per_bui(`#define mk_sl_cui_inl_defd_pr_to_buis_$1_le mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_buis_$1_le)')
mm_per_bui(`#define mk_sl_cui_inl_defd_pr_from_buis_$1_be mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_buis_$1_be)')
mm_per_bui(`#define mk_sl_cui_inl_defd_pr_to_buis_$1_be mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_buis_$1_be)')
#define mk_sl_cui_inl_defd_pr_assign mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_assign)
#define mk_sl_cui_inl_defd_pr_set_zero mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_set_zero)
#define mk_sl_cui_inl_defd_pr_set_max mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_set_max)
#define mk_sl_cui_inl_defd_pr_set_one mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_set_one)
#define mk_sl_cui_inl_defd_pr_set_two mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_set_two)
#define mk_sl_cui_inl_defd_pr_set_bit mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_set_bit)
#define mk_sl_cui_inl_defd_pr_set_mask mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_set_mask)
#define mk_sl_cui_inl_defd_pr_count_leading_zeros mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_count_leading_zeros)
#define mk_sl_cui_inl_defd_pr_count_leading_ones mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_count_leading_ones)
#define mk_sl_cui_inl_defd_pr_count_trailing_zeros mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_count_trailing_zeros)
#define mk_sl_cui_inl_defd_pr_count_trailing_ones mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_count_trailing_ones)
#define mk_sl_cui_inl_defd_pr_count_ones mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_count_ones)
#define mk_sl_cui_inl_defd_pr_count_zeros mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_count_zeros)
#define mk_sl_cui_inl_defd_pr_has_msb mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_has_msb)
#define mk_sl_cui_inl_defd_pr_has_lsb mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_has_lsb)
#define mk_sl_cui_inl_defd_pr_is_zero mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_is_zero)
#define mk_sl_cui_inl_defd_pr_is_one mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_is_one)
#define mk_sl_cui_inl_defd_pr_is_two mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_is_two)
#define mk_sl_cui_inl_defd_pr_is_max mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_is_max)
#define mk_sl_cui_inl_defd_pr_is_bit mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_is_bit)
#define mk_sl_cui_inl_defd_pr_eq mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_eq)
#define mk_sl_cui_inl_defd_pr_ne mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_ne)
#define mk_sl_cui_inl_defd_pr_lt mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_lt)
#define mk_sl_cui_inl_defd_pr_le mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_le)
#define mk_sl_cui_inl_defd_pr_gt mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_gt)
#define mk_sl_cui_inl_defd_pr_ge mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_ge)
#define mk_sl_cui_inl_defd_pr_cmp mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_cmp)
#define mk_sl_cui_inl_defd_pr_inc2 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_inc2)
#define mk_sl_cui_inl_defd_pr_dec2 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_dec2)
#define mk_sl_cui_inl_defd_pr_inc1 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_inc1)
#define mk_sl_cui_inl_defd_pr_dec1 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_dec1)
#define mk_sl_cui_inl_defd_pr_not2 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_not2)
#define mk_sl_cui_inl_defd_pr_or3 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_or3)
#define mk_sl_cui_inl_defd_pr_and3 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_and3)
#define mk_sl_cui_inl_defd_pr_xor3 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_xor3)
#define mk_sl_cui_inl_defd_pr_not1 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_not1)
#define mk_sl_cui_inl_defd_pr_or2 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_or2)
#define mk_sl_cui_inl_defd_pr_and2 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_and2)
#define mk_sl_cui_inl_defd_pr_xor2 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_xor2)
#define mk_sl_cui_inl_defd_pr_shl3 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_shl3)
#define mk_sl_cui_inl_defd_pr_shr3 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_shr3)
#define mk_sl_cui_inl_defd_pr_rotl3 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_rotl3)
#define mk_sl_cui_inl_defd_pr_rotr3 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_rotr3)
#define mk_sl_cui_inl_defd_pr_shl2 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_shl2)
#define mk_sl_cui_inl_defd_pr_shr2 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_shr2)
#define mk_sl_cui_inl_defd_pr_rotl2 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_rotl2)
#define mk_sl_cui_inl_defd_pr_rotr2 mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_rotr2)
#define mk_sl_cui_inl_defd_pr_would_overflow_add_cc mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_would_overflow_add_cc)
#define mk_sl_cui_inl_defd_pr_would_overflow_add_cs mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_would_overflow_add_cs)
#define mk_sl_cui_inl_defd_pr_would_overflow_add_cp mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_would_overflow_add_cp)
#define mk_sl_cui_inl_defd_pr_would_overflow_sub_cc mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_would_overflow_sub_cc)
#define mk_sl_cui_inl_defd_pr_would_overflow_sub_cs mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_would_overflow_sub_cs)
#define mk_sl_cui_inl_defd_pr_would_overflow_sub_cp mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_would_overflow_sub_cp)
#define mk_sl_cui_inl_defd_pr_would_overflow_mul mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_would_overflow_mul)
#define mk_sl_cui_inl_defd_pr_would_overflow_div mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_would_overflow_div)
#define mk_sl_cui_inl_defd_pr_would_overflow_mod mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_would_overflow_mod)
#define mk_sl_cui_inl_defd_pr_add3_wrap_cid_cod mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_add3_wrap_cid_cod)
#define mk_sl_cui_inl_defd_pr_add3_wrap_cid_coe mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_add3_wrap_cid_coe)
#define mk_sl_cui_inl_defd_pr_add3_wrap_cie_cod mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_add3_wrap_cie_cod)
#define mk_sl_cui_inl_defd_pr_add3_wrap_cie_coe mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_add3_wrap_cie_coe)
#define mk_sl_cui_inl_defd_pr_add2_wrap_cid_cod mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_add2_wrap_cid_cod)
#define mk_sl_cui_inl_defd_pr_add2_wrap_cid_coe mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_add2_wrap_cid_coe)
#define mk_sl_cui_inl_defd_pr_add2_wrap_cie_cod mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_add2_wrap_cie_cod)
#define mk_sl_cui_inl_defd_pr_add2_wrap_cie_coe mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_add2_wrap_cie_coe)
#define mk_sl_cui_inl_defd_pr_sub3_wrap_cid_cod mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_sub3_wrap_cid_cod)
#define mk_sl_cui_inl_defd_pr_sub3_wrap_cid_coe mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_sub3_wrap_cid_coe)
#define mk_sl_cui_inl_defd_pr_sub3_wrap_cie_cod mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_sub3_wrap_cie_cod)
#define mk_sl_cui_inl_defd_pr_sub3_wrap_cie_coe mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_sub3_wrap_cie_coe)
#define mk_sl_cui_inl_defd_pr_sub2_wrap_cid_cod mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_sub2_wrap_cid_cod)
#define mk_sl_cui_inl_defd_pr_sub2_wrap_cid_coe mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_sub2_wrap_cid_coe)
#define mk_sl_cui_inl_defd_pr_sub2_wrap_cie_cod mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_sub2_wrap_cie_cod)
#define mk_sl_cui_inl_defd_pr_sub2_wrap_cie_coe mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_sub2_wrap_cie_coe)
#define mk_sl_cui_inl_defd_pr_mul3_wrap_lo mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mul3_wrap_lo)
#define mk_sl_cui_inl_defd_pr_mul3_wrap_hi mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mul3_wrap_hi)
#define mk_sl_cui_inl_defd_pr_mul4_wrap_wi mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mul4_wrap_wi)
#define mk_sl_cui_inl_defd_pr_mul2_wrap_lo mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mul2_wrap_lo)
#define mk_sl_cui_inl_defd_pr_mul2_wrap_hi mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mul2_wrap_hi)
#define mk_sl_cui_inl_defd_pr_mul2_wrap_wi mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mul2_wrap_wi)
#define mk_sl_cui_inl_defd_pr_div3_wrap mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_div3_wrap)
#define mk_sl_cui_inl_defd_pr_mod3_wrap mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mod3_wrap)
#define mk_sl_cui_inl_defd_pr_divmod4_wrap mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_divmod4_wrap)
#define mk_sl_cui_inl_defd_pr_div2_wrap mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_div2_wrap)
#define mk_sl_cui_inl_defd_pr_mod2_wrap mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mod2_wrap)
#define mk_sl_cui_inl_defd_pr_divmod2_wrap mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_divmod2_wrap)
#define mk_sl_cui_inl_defd_pr_to_str_bin_n mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_str_bin_n)
#define mk_sl_cui_inl_defd_pr_to_str_bin_w mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_str_bin_w)
#define mk_sl_cui_inl_defd_pr_from_str_bin_n mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_bin_n)
#define mk_sl_cui_inl_defd_pr_from_str_bin_w mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_bin_w)
#define mk_sl_cui_inl_defd_pr_to_str_oct_n mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_str_oct_n)
#define mk_sl_cui_inl_defd_pr_to_str_oct_w mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_str_oct_w)
#define mk_sl_cui_inl_defd_pr_from_str_oct_n mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_oct_n)
#define mk_sl_cui_inl_defd_pr_from_str_oct_w mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_oct_w)
#define mk_sl_cui_inl_defd_pr_to_str_dec_n mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_str_dec_n)
#define mk_sl_cui_inl_defd_pr_to_str_dec_w mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_str_dec_w)
#define mk_sl_cui_inl_defd_pr_from_str_dec_n mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_dec_n)
#define mk_sl_cui_inl_defd_pr_from_str_dec_w mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_dec_w)
#define mk_sl_cui_inl_defd_pr_to_str_hex_n mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_str_hex_n)
#define mk_sl_cui_inl_defd_pr_to_str_hex_w mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_str_hex_w)
#define mk_sl_cui_inl_defd_pr_from_str_hex_n mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_hex_n)
#define mk_sl_cui_inl_defd_pr_from_str_hex_w mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_hex_w)
#define mk_sl_cui_inl_defd_pr_from_str_hex_many_n mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_hex_many_n)
#define mk_sl_cui_inl_defd_pr_from_str_hex_many_w mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_hex_many_w)
#define mk_sl_cui_inl_defd_pr_to_str_binf_n mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_str_binf_n)
#define mk_sl_cui_inl_defd_pr_to_str_binf_w mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_str_binf_w)
#define mk_sl_cui_inl_defd_pr_to_str_hexf_n mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_str_hexf_n)
#define mk_sl_cui_inl_defd_pr_to_str_hexf_w mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_str_hexf_w)
#define mk_sl_cui_inl_defd_pr_to_str_hexf_many_n mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_str_hexf_many_n)
#define mk_sl_cui_inl_defd_pr_to_str_hexf_many_w mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_to_str_hexf_many_w)

#define mk_sl_cui_inl_defd_pr_mul3_wrap_lo_restrict mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mul3_wrap_lo_restrict)
#define mk_sl_cui_inl_defd_pr_mul3_wrap_lo_alias mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mul3_wrap_lo_alias)
#define mk_sl_cui_inl_defd_pr_mul3_wrap_hi_restrict mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mul3_wrap_hi_restrict)
#define mk_sl_cui_inl_defd_pr_mul3_wrap_hi_alias mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mul3_wrap_hi_alias)
#define mk_sl_cui_inl_defd_pr_mul3_wrap_wi_restrict mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mul3_wrap_wi_restrict)
#define mk_sl_cui_inl_defd_pr_mul3_wrap_wi_alias mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mul3_wrap_wi_alias)
#define mk_sl_cui_inl_defd_pr_mul4_wrap_wi_restrict mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mul4_wrap_wi_restrict)
#define mk_sl_cui_inl_defd_pr_mul4_wrap_wi_alias mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mul4_wrap_wi_alias)
#define mk_sl_cui_inl_defd_pr_add2_wrap_cid_cod_smol mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_add2_wrap_cid_cod_smol)
#define mk_sl_cui_inl_defd_pr_mul3_wrap_lo_smol mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mul3_wrap_lo_smol)
#define mk_sl_cui_inl_defd_pr_mul4_wrap_wi_smol mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_mul4_wrap_wi_smol)
#define mk_sl_cui_inl_defd_pr_divmod4_wrap_smol mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_divmod4_wrap_smol)
#define mk_sl_cui_inl_defd_pr_from_str_dec_border_base_impl mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_dec_border_base_impl)
#define mk_sl_cui_inl_defd_pr_from_str_dec_border_value_impl mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_dec_border_value_impl)
#define mk_sl_cui_inl_defd_pr_from_str_dec_border_digit_impl mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_dec_border_digit_impl)
#define mk_sl_cui_inl_defd_pr_from_str_dec_border_base mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_dec_border_base)
#define mk_sl_cui_inl_defd_pr_from_str_dec_border_value mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_dec_border_value)
#define mk_sl_cui_inl_defd_pr_from_str_dec_border_digit mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_dec_border_digit)
#define mk_sl_cui_inl_defd_pr_from_str_dec_border_base_val mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_dec_border_base_val)
#define mk_sl_cui_inl_defd_pr_from_str_dec_border_value_val mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_dec_border_value_val)
#define mk_sl_cui_inl_defd_pr_from_str_dec_border_digit_val mk_lang_concat(mk_sl_cui_inl_defd_name, _pr_from_str_dec_border_digit_val)


#define mk_sl_cui_inl_defd_from_base mk_lang_concat(mk_sl_cui_inl_defd_name, _from_base)
mm_per_bi(`#define mk_sl_cui_inl_defd_from_bi_$1 mk_lang_concat(mk_sl_cui_inl_defd_name, _from_bi_$1)')
#define mk_sl_cui_inl_defd_to_base mk_lang_concat(mk_sl_cui_inl_defd_name, _to_base)
mm_per_bi(`#define mk_sl_cui_inl_defd_to_bi_$1 mk_lang_concat(mk_sl_cui_inl_defd_name, _to_bi_$1)')
mm_per_bui(`#define mk_sl_cui_inl_defd_from_buis_$1_le mk_lang_concat(mk_sl_cui_inl_defd_name, _from_buis_$1_le)')
mm_per_bui(`#define mk_sl_cui_inl_defd_to_buis_$1_le mk_lang_concat(mk_sl_cui_inl_defd_name, _to_buis_$1_le)')
mm_per_bui(`#define mk_sl_cui_inl_defd_from_buis_$1_be mk_lang_concat(mk_sl_cui_inl_defd_name, _from_buis_$1_be)')
mm_per_bui(`#define mk_sl_cui_inl_defd_to_buis_$1_be mk_lang_concat(mk_sl_cui_inl_defd_name, _to_buis_$1_be)')
#define mk_sl_cui_inl_defd_assign mk_lang_concat(mk_sl_cui_inl_defd_name, _assign)
#define mk_sl_cui_inl_defd_set_zero mk_lang_concat(mk_sl_cui_inl_defd_name, _set_zero)
#define mk_sl_cui_inl_defd_set_max mk_lang_concat(mk_sl_cui_inl_defd_name, _set_max)
#define mk_sl_cui_inl_defd_set_one mk_lang_concat(mk_sl_cui_inl_defd_name, _set_one)
#define mk_sl_cui_inl_defd_set_two mk_lang_concat(mk_sl_cui_inl_defd_name, _set_two)
#define mk_sl_cui_inl_defd_set_bit mk_lang_concat(mk_sl_cui_inl_defd_name, _set_bit)
#define mk_sl_cui_inl_defd_set_mask mk_lang_concat(mk_sl_cui_inl_defd_name, _set_mask)
#define mk_sl_cui_inl_defd_count_leading_zeros mk_lang_concat(mk_sl_cui_inl_defd_name, _count_leading_zeros)
#define mk_sl_cui_inl_defd_count_leading_ones mk_lang_concat(mk_sl_cui_inl_defd_name, _count_leading_ones)
#define mk_sl_cui_inl_defd_count_trailing_zeros mk_lang_concat(mk_sl_cui_inl_defd_name, _count_trailing_zeros)
#define mk_sl_cui_inl_defd_count_trailing_ones mk_lang_concat(mk_sl_cui_inl_defd_name, _count_trailing_ones)
#define mk_sl_cui_inl_defd_count_ones mk_lang_concat(mk_sl_cui_inl_defd_name, _count_ones)
#define mk_sl_cui_inl_defd_count_zeros mk_lang_concat(mk_sl_cui_inl_defd_name, _count_zeros)
#define mk_sl_cui_inl_defd_has_msb mk_lang_concat(mk_sl_cui_inl_defd_name, _has_msb)
#define mk_sl_cui_inl_defd_has_lsb mk_lang_concat(mk_sl_cui_inl_defd_name, _has_lsb)
#define mk_sl_cui_inl_defd_is_zero mk_lang_concat(mk_sl_cui_inl_defd_name, _is_zero)
#define mk_sl_cui_inl_defd_is_one mk_lang_concat(mk_sl_cui_inl_defd_name, _is_one)
#define mk_sl_cui_inl_defd_is_two mk_lang_concat(mk_sl_cui_inl_defd_name, _is_two)
#define mk_sl_cui_inl_defd_is_max mk_lang_concat(mk_sl_cui_inl_defd_name, _is_max)
#define mk_sl_cui_inl_defd_is_bit mk_lang_concat(mk_sl_cui_inl_defd_name, _is_bit)
#define mk_sl_cui_inl_defd_eq mk_lang_concat(mk_sl_cui_inl_defd_name, _eq)
#define mk_sl_cui_inl_defd_ne mk_lang_concat(mk_sl_cui_inl_defd_name, _ne)
#define mk_sl_cui_inl_defd_lt mk_lang_concat(mk_sl_cui_inl_defd_name, _lt)
#define mk_sl_cui_inl_defd_le mk_lang_concat(mk_sl_cui_inl_defd_name, _le)
#define mk_sl_cui_inl_defd_gt mk_lang_concat(mk_sl_cui_inl_defd_name, _gt)
#define mk_sl_cui_inl_defd_ge mk_lang_concat(mk_sl_cui_inl_defd_name, _ge)
#define mk_sl_cui_inl_defd_cmp mk_lang_concat(mk_sl_cui_inl_defd_name, _cmp)
#define mk_sl_cui_inl_defd_inc2 mk_lang_concat(mk_sl_cui_inl_defd_name, _inc2)
#define mk_sl_cui_inl_defd_dec2 mk_lang_concat(mk_sl_cui_inl_defd_name, _dec2)
#define mk_sl_cui_inl_defd_inc1 mk_lang_concat(mk_sl_cui_inl_defd_name, _inc1)
#define mk_sl_cui_inl_defd_dec1 mk_lang_concat(mk_sl_cui_inl_defd_name, _dec1)
#define mk_sl_cui_inl_defd_not2 mk_lang_concat(mk_sl_cui_inl_defd_name, _not2)
#define mk_sl_cui_inl_defd_or3 mk_lang_concat(mk_sl_cui_inl_defd_name, _or3)
#define mk_sl_cui_inl_defd_and3 mk_lang_concat(mk_sl_cui_inl_defd_name, _and3)
#define mk_sl_cui_inl_defd_xor3 mk_lang_concat(mk_sl_cui_inl_defd_name, _xor3)
#define mk_sl_cui_inl_defd_not1 mk_lang_concat(mk_sl_cui_inl_defd_name, _not1)
#define mk_sl_cui_inl_defd_or2 mk_lang_concat(mk_sl_cui_inl_defd_name, _or2)
#define mk_sl_cui_inl_defd_and2 mk_lang_concat(mk_sl_cui_inl_defd_name, _and2)
#define mk_sl_cui_inl_defd_xor2 mk_lang_concat(mk_sl_cui_inl_defd_name, _xor2)
#define mk_sl_cui_inl_defd_shl3 mk_lang_concat(mk_sl_cui_inl_defd_name, _shl3)
#define mk_sl_cui_inl_defd_shr3 mk_lang_concat(mk_sl_cui_inl_defd_name, _shr3)
#define mk_sl_cui_inl_defd_rotl3 mk_lang_concat(mk_sl_cui_inl_defd_name, _rotl3)
#define mk_sl_cui_inl_defd_rotr3 mk_lang_concat(mk_sl_cui_inl_defd_name, _rotr3)
#define mk_sl_cui_inl_defd_shl2 mk_lang_concat(mk_sl_cui_inl_defd_name, _shl2)
#define mk_sl_cui_inl_defd_shr2 mk_lang_concat(mk_sl_cui_inl_defd_name, _shr2)
#define mk_sl_cui_inl_defd_rotl2 mk_lang_concat(mk_sl_cui_inl_defd_name, _rotl2)
#define mk_sl_cui_inl_defd_rotr2 mk_lang_concat(mk_sl_cui_inl_defd_name, _rotr2)
#define mk_sl_cui_inl_defd_would_overflow_add_cc mk_lang_concat(mk_sl_cui_inl_defd_name, _would_overflow_add_cc)
#define mk_sl_cui_inl_defd_would_overflow_add_cs mk_lang_concat(mk_sl_cui_inl_defd_name, _would_overflow_add_cs)
#define mk_sl_cui_inl_defd_would_overflow_add_cp mk_lang_concat(mk_sl_cui_inl_defd_name, _would_overflow_add_cp)
#define mk_sl_cui_inl_defd_would_overflow_sub_cc mk_lang_concat(mk_sl_cui_inl_defd_name, _would_overflow_sub_cc)
#define mk_sl_cui_inl_defd_would_overflow_sub_cs mk_lang_concat(mk_sl_cui_inl_defd_name, _would_overflow_sub_cs)
#define mk_sl_cui_inl_defd_would_overflow_sub_cp mk_lang_concat(mk_sl_cui_inl_defd_name, _would_overflow_sub_cp)
#define mk_sl_cui_inl_defd_would_overflow_mul mk_lang_concat(mk_sl_cui_inl_defd_name, _would_overflow_mul)
#define mk_sl_cui_inl_defd_would_overflow_div mk_lang_concat(mk_sl_cui_inl_defd_name, _would_overflow_div)
#define mk_sl_cui_inl_defd_would_overflow_mod mk_lang_concat(mk_sl_cui_inl_defd_name, _would_overflow_mod)
#define mk_sl_cui_inl_defd_add3_wrap_cid_cod mk_lang_concat(mk_sl_cui_inl_defd_name, _add3_wrap_cid_cod)
#define mk_sl_cui_inl_defd_add3_wrap_cid_coe mk_lang_concat(mk_sl_cui_inl_defd_name, _add3_wrap_cid_coe)
#define mk_sl_cui_inl_defd_add3_wrap_cie_cod mk_lang_concat(mk_sl_cui_inl_defd_name, _add3_wrap_cie_cod)
#define mk_sl_cui_inl_defd_add3_wrap_cie_coe mk_lang_concat(mk_sl_cui_inl_defd_name, _add3_wrap_cie_coe)
#define mk_sl_cui_inl_defd_add2_wrap_cid_cod mk_lang_concat(mk_sl_cui_inl_defd_name, _add2_wrap_cid_cod)
#define mk_sl_cui_inl_defd_add2_wrap_cid_coe mk_lang_concat(mk_sl_cui_inl_defd_name, _add2_wrap_cid_coe)
#define mk_sl_cui_inl_defd_add2_wrap_cie_cod mk_lang_concat(mk_sl_cui_inl_defd_name, _add2_wrap_cie_cod)
#define mk_sl_cui_inl_defd_add2_wrap_cie_coe mk_lang_concat(mk_sl_cui_inl_defd_name, _add2_wrap_cie_coe)
#define mk_sl_cui_inl_defd_sub3_wrap_cid_cod mk_lang_concat(mk_sl_cui_inl_defd_name, _sub3_wrap_cid_cod)
#define mk_sl_cui_inl_defd_sub3_wrap_cid_coe mk_lang_concat(mk_sl_cui_inl_defd_name, _sub3_wrap_cid_coe)
#define mk_sl_cui_inl_defd_sub3_wrap_cie_cod mk_lang_concat(mk_sl_cui_inl_defd_name, _sub3_wrap_cie_cod)
#define mk_sl_cui_inl_defd_sub3_wrap_cie_coe mk_lang_concat(mk_sl_cui_inl_defd_name, _sub3_wrap_cie_coe)
#define mk_sl_cui_inl_defd_sub2_wrap_cid_cod mk_lang_concat(mk_sl_cui_inl_defd_name, _sub2_wrap_cid_cod)
#define mk_sl_cui_inl_defd_sub2_wrap_cid_coe mk_lang_concat(mk_sl_cui_inl_defd_name, _sub2_wrap_cid_coe)
#define mk_sl_cui_inl_defd_sub2_wrap_cie_cod mk_lang_concat(mk_sl_cui_inl_defd_name, _sub2_wrap_cie_cod)
#define mk_sl_cui_inl_defd_sub2_wrap_cie_coe mk_lang_concat(mk_sl_cui_inl_defd_name, _sub2_wrap_cie_coe)
#define mk_sl_cui_inl_defd_mul3_wrap_lo mk_lang_concat(mk_sl_cui_inl_defd_name, _mul3_wrap_lo)
#define mk_sl_cui_inl_defd_mul3_wrap_hi mk_lang_concat(mk_sl_cui_inl_defd_name, _mul3_wrap_hi)
#define mk_sl_cui_inl_defd_mul4_wrap_wi mk_lang_concat(mk_sl_cui_inl_defd_name, _mul4_wrap_wi)
#define mk_sl_cui_inl_defd_mul4_wrap_wi_smol mk_lang_concat(mk_sl_cui_inl_defd_name, _mul4_wrap_wi_smol)
#define mk_sl_cui_inl_defd_mul2_wrap_lo mk_lang_concat(mk_sl_cui_inl_defd_name, _mul2_wrap_lo)
#define mk_sl_cui_inl_defd_mul2_wrap_hi mk_lang_concat(mk_sl_cui_inl_defd_name, _mul2_wrap_hi)
#define mk_sl_cui_inl_defd_mul2_wrap_wi mk_lang_concat(mk_sl_cui_inl_defd_name, _mul2_wrap_wi)
#define mk_sl_cui_inl_defd_div3_wrap mk_lang_concat(mk_sl_cui_inl_defd_name, _div3_wrap)
#define mk_sl_cui_inl_defd_mod3_wrap mk_lang_concat(mk_sl_cui_inl_defd_name, _mod3_wrap)
#define mk_sl_cui_inl_defd_divmod4_wrap mk_lang_concat(mk_sl_cui_inl_defd_name, _divmod4_wrap)
#define mk_sl_cui_inl_defd_div2_wrap mk_lang_concat(mk_sl_cui_inl_defd_name, _div2_wrap)
#define mk_sl_cui_inl_defd_mod2_wrap mk_lang_concat(mk_sl_cui_inl_defd_name, _mod2_wrap)
#define mk_sl_cui_inl_defd_divmod2_wrap mk_lang_concat(mk_sl_cui_inl_defd_name, _divmod2_wrap)
#define mk_sl_cui_inl_defd_to_str_bin_n mk_lang_concat(mk_sl_cui_inl_defd_name, _to_str_bin_n)
#define mk_sl_cui_inl_defd_to_str_bin_w mk_lang_concat(mk_sl_cui_inl_defd_name, _to_str_bin_w)
#define mk_sl_cui_inl_defd_from_str_bin_n mk_lang_concat(mk_sl_cui_inl_defd_name, _from_str_bin_n)
#define mk_sl_cui_inl_defd_from_str_bin_w mk_lang_concat(mk_sl_cui_inl_defd_name, _from_str_bin_w)
#define mk_sl_cui_inl_defd_to_str_oct_n mk_lang_concat(mk_sl_cui_inl_defd_name, _to_str_oct_n)
#define mk_sl_cui_inl_defd_to_str_oct_w mk_lang_concat(mk_sl_cui_inl_defd_name, _to_str_oct_w)
#define mk_sl_cui_inl_defd_from_str_oct_n mk_lang_concat(mk_sl_cui_inl_defd_name, _from_str_oct_n)
#define mk_sl_cui_inl_defd_from_str_oct_w mk_lang_concat(mk_sl_cui_inl_defd_name, _from_str_oct_w)
#define mk_sl_cui_inl_defd_to_str_dec_n mk_lang_concat(mk_sl_cui_inl_defd_name, _to_str_dec_n)
#define mk_sl_cui_inl_defd_to_str_dec_w mk_lang_concat(mk_sl_cui_inl_defd_name, _to_str_dec_w)
#define mk_sl_cui_inl_defd_from_str_dec_n mk_lang_concat(mk_sl_cui_inl_defd_name, _from_str_dec_n)
#define mk_sl_cui_inl_defd_from_str_dec_w mk_lang_concat(mk_sl_cui_inl_defd_name, _from_str_dec_w)
#define mk_sl_cui_inl_defd_to_str_hex_n mk_lang_concat(mk_sl_cui_inl_defd_name, _to_str_hex_n)
#define mk_sl_cui_inl_defd_to_str_hex_w mk_lang_concat(mk_sl_cui_inl_defd_name, _to_str_hex_w)
#define mk_sl_cui_inl_defd_from_str_hex_n mk_lang_concat(mk_sl_cui_inl_defd_name, _from_str_hex_n)
#define mk_sl_cui_inl_defd_from_str_hex_w mk_lang_concat(mk_sl_cui_inl_defd_name, _from_str_hex_w)
#define mk_sl_cui_inl_defd_from_str_hex_many_n mk_lang_concat(mk_sl_cui_inl_defd_name, _from_str_hex_many_n)
#define mk_sl_cui_inl_defd_from_str_hex_many_w mk_lang_concat(mk_sl_cui_inl_defd_name, _from_str_hex_many_w)
#define mk_sl_cui_inl_defd_to_str_binf_n mk_lang_concat(mk_sl_cui_inl_defd_name, _to_str_binf_n)
#define mk_sl_cui_inl_defd_to_str_binf_w mk_lang_concat(mk_sl_cui_inl_defd_name, _to_str_binf_w)
#define mk_sl_cui_inl_defd_to_str_hexf_n mk_lang_concat(mk_sl_cui_inl_defd_name, _to_str_hexf_n)
#define mk_sl_cui_inl_defd_to_str_hexf_w mk_lang_concat(mk_sl_cui_inl_defd_name, _to_str_hexf_w)
#define mk_sl_cui_inl_defd_to_str_hexf_many_n mk_lang_concat(mk_sl_cui_inl_defd_name, _to_str_hexf_many_n)
#define mk_sl_cui_inl_defd_to_str_hexf_many_w mk_lang_concat(mk_sl_cui_inl_defd_name, _to_str_hexf_many_w)
