#include "mk_lang_concat.h"
#include "mk_lang_limits.h"
#include "mk_sl_vector.h"


#if(!( \
	(defined mk_sl_vector_t_name) && \
	(defined mk_sl_vector_t_element_type) && \
	(defined mk_sl_vector_t_mallocatorg || defined mk_sl_vector_t_mallocatorl) && \
	((defined mk_sl_vector_t_copy && ((mk_sl_vector_t_copy) == mk_sl_vector_cpy_use_bitblasting || (mk_sl_vector_t_copy) == mk_sl_vector_cpy_use_type_suffix || (mk_sl_vector_t_copy) == mk_sl_vector_cpy_use_custom)) || !defined mk_sl_vector_t_copy) && \
	(defined mk_sl_vector_t_element_construct_void || !defined mk_sl_vector_t_element_construct_void) && \
	(defined mk_sl_vector_t_element_destruct || !defined mk_sl_vector_t_element_destruct) && \
	(defined mk_sl_vector_t_element_copy || !defined mk_sl_vector_t_element_copy) && \
	(defined mk_sl_vector_t_element_move || !defined mk_sl_vector_t_element_move) && \
1))
#error xxxxxxxxxx
#endif

#if( \
	defined mk_sl_vector_t_mallocatorg && \
	defined mk_sl_vector_t_mallocatorl && \
1)
#error xxxxxxxxxx
#endif

#if( \
	defined mk_sl_vector_t_element_construct_void || \
	defined mk_sl_vector_t_element_destruct || \
0)
#if(!( \
	defined mk_sl_vector_t_element_construct_void && \
	defined mk_sl_vector_t_element_destruct && \
1))
#error xxxxxxxxxx
#endif
#endif

#if( \
	defined mk_sl_vector_t_element_copy || \
	defined mk_sl_vector_t_element_move || \
0)
#if(!( \
	defined mk_sl_vector_t_element_copy && \
	defined mk_sl_vector_t_element_move && \
1))
#error xxxxxxxxxx
#endif
#endif


#define mk_sl_vector_inl_defd_name mk_sl_vector_t_name
#define mk_sl_vector_inl_defd_element_type mk_sl_vector_t_element_type

#if defined mk_sl_vector_t_mallocatorg
#define mk_sl_vector_inl_defd_mallocator mk_sl_vector_t_mallocatorg
#define mk_sl_vector_inl_defd_mallocator_is_global 1
#define mk_sl_vector_inl_defd_mallocator_is_lokal 0
#elif defined mk_sl_vector_t_mallocatorl
#define mk_sl_vector_inl_defd_mallocator mk_sl_vector_t_mallocatorl
#define mk_sl_vector_inl_defd_mallocator_is_global 0
#define mk_sl_vector_inl_defd_mallocator_is_lokal 1
#else
#error xxxxxxxxxx
#endif

#if defined mk_sl_vector_t_copy
#define mk_sl_vector_inl_defd_copy mk_sl_vector_t_copy
#else
#if defined mk_sl_vector_t_element_copy && defined mk_sl_vector_t_element_move
#define mk_sl_vector_inl_defd_copy mk_sl_vector_cpy_use_type_suffix
#else
#define mk_sl_vector_inl_defd_copy mk_sl_vector_cpy_use_bitblasting
#endif
#endif

#if defined mk_sl_vector_t_element_construct_void
#define mk_sl_vector_inl_defd_element_construct_void mk_sl_vector_t_element_construct_void
#define mk_sl_vector_inl_defd_element_destruct mk_sl_vector_t_element_destruct
#else
#define mk_sl_vector_inl_defd_element_construct_void mk_sl_vector_inl_defd_pr_nothing
#define mk_sl_vector_inl_defd_element_destruct mk_sl_vector_inl_defd_pr_nothing
#endif


#define mk_sl_vector_inl_defd_element_prefix mk_lang_concat(mk_sl_vector_inl_defd_name, _element)

#define mk_sl_vector_inl_defd_element_s mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _s)
#define mk_sl_vector_inl_defd_element_t mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _t)
#define mk_sl_vector_inl_defd_element_ct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _ct)
#define mk_sl_vector_inl_defd_element_vt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _vt)
#define mk_sl_vector_inl_defd_element_cvt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _cvt)
#define mk_sl_vector_inl_defd_element_pt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _pt)
#define mk_sl_vector_inl_defd_element_pct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _pct)
#define mk_sl_vector_inl_defd_element_pvt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _pvt)
#define mk_sl_vector_inl_defd_element_pcvt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _pcvt)
#define mk_sl_vector_inl_defd_element_prt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _prt)
#define mk_sl_vector_inl_defd_element_prct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _prct)
#define mk_sl_vector_inl_defd_element_prvt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _prvt)
#define mk_sl_vector_inl_defd_element_prcvt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _prcvt)
#define mk_sl_vector_inl_defd_element_lpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lpt)
#define mk_sl_vector_inl_defd_element_lpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lpct)
#define mk_sl_vector_inl_defd_element_lpvt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lpvt)
#define mk_sl_vector_inl_defd_element_lpcvt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lpcvt)
#define mk_sl_vector_inl_defd_element_lprt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lprt)
#define mk_sl_vector_inl_defd_element_lprct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lprct)
#define mk_sl_vector_inl_defd_element_lprvt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lprvt)
#define mk_sl_vector_inl_defd_element_lprcvt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lprcvt)
#define mk_sl_vector_inl_defd_element_npt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _npt)
#define mk_sl_vector_inl_defd_element_npct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _npct)
#define mk_sl_vector_inl_defd_element_npvt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _npvt)
#define mk_sl_vector_inl_defd_element_npcvt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _npcvt)
#define mk_sl_vector_inl_defd_element_nprt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _nprt)
#define mk_sl_vector_inl_defd_element_nprct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _nprct)
#define mk_sl_vector_inl_defd_element_nprvt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _nprvt)
#define mk_sl_vector_inl_defd_element_nprcvt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _nprcvt)
#define mk_sl_vector_inl_defd_element_cpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _cpt)
#define mk_sl_vector_inl_defd_element_vpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _vpt)
#define mk_sl_vector_inl_defd_element_cvpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _cvpt)
#define mk_sl_vector_inl_defd_element_ppt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _ppt)
#define mk_sl_vector_inl_defd_element_pcpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _pcpt)
#define mk_sl_vector_inl_defd_element_pvpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _pvpt)
#define mk_sl_vector_inl_defd_element_pcvpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _pcvpt)
#define mk_sl_vector_inl_defd_element_prpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _prpt)
#define mk_sl_vector_inl_defd_element_prcpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _prcpt)
#define mk_sl_vector_inl_defd_element_prvpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _prvpt)
#define mk_sl_vector_inl_defd_element_prcvpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _prcvpt)
#define mk_sl_vector_inl_defd_element_lppt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lppt)
#define mk_sl_vector_inl_defd_element_lpcpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lpcpt)
#define mk_sl_vector_inl_defd_element_lpvpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lpvpt)
#define mk_sl_vector_inl_defd_element_lpcvpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lpcvpt)
#define mk_sl_vector_inl_defd_element_lprpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lprpt)
#define mk_sl_vector_inl_defd_element_lprcpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lprcpt)
#define mk_sl_vector_inl_defd_element_lprvpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lprvpt)
#define mk_sl_vector_inl_defd_element_lprcvpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lprcvpt)
#define mk_sl_vector_inl_defd_element_nppt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _nppt)
#define mk_sl_vector_inl_defd_element_npcpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _npcpt)
#define mk_sl_vector_inl_defd_element_npvpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _npvpt)
#define mk_sl_vector_inl_defd_element_npcvpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _npcvpt)
#define mk_sl_vector_inl_defd_element_nprpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _nprpt)
#define mk_sl_vector_inl_defd_element_nprcpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _nprcpt)
#define mk_sl_vector_inl_defd_element_nprvpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _nprvpt)
#define mk_sl_vector_inl_defd_element_nprcvpt mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _nprcvpt)
#define mk_sl_vector_inl_defd_element_cpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _cpct)
#define mk_sl_vector_inl_defd_element_vpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _vpct)
#define mk_sl_vector_inl_defd_element_cvpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _cvpct)
#define mk_sl_vector_inl_defd_element_ppct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _ppct)
#define mk_sl_vector_inl_defd_element_pcpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _pcpct)
#define mk_sl_vector_inl_defd_element_pvpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _pvpct)
#define mk_sl_vector_inl_defd_element_pcvpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _pcvpct)
#define mk_sl_vector_inl_defd_element_prpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _prpct)
#define mk_sl_vector_inl_defd_element_prcpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _prcpct)
#define mk_sl_vector_inl_defd_element_prvpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _prvpct)
#define mk_sl_vector_inl_defd_element_prcvpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _prcvpct)
#define mk_sl_vector_inl_defd_element_lppct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lppct)
#define mk_sl_vector_inl_defd_element_lpcpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lpcpct)
#define mk_sl_vector_inl_defd_element_lpvpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lpvpct)
#define mk_sl_vector_inl_defd_element_lpcvpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lpcvpct)
#define mk_sl_vector_inl_defd_element_lprpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lprpct)
#define mk_sl_vector_inl_defd_element_lprcpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lprcpct)
#define mk_sl_vector_inl_defd_element_lprvpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lprvpct)
#define mk_sl_vector_inl_defd_element_lprcvpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _lprcvpct)
#define mk_sl_vector_inl_defd_element_nppct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _nppct)
#define mk_sl_vector_inl_defd_element_npcpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _npcpct)
#define mk_sl_vector_inl_defd_element_npvpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _npvpct)
#define mk_sl_vector_inl_defd_element_npcvpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _npcvpct)
#define mk_sl_vector_inl_defd_element_nprpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _nprpct)
#define mk_sl_vector_inl_defd_element_nprcpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _nprcpct)
#define mk_sl_vector_inl_defd_element_nprvpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _nprvpct)
#define mk_sl_vector_inl_defd_element_nprcvpct mk_lang_concat(mk_sl_vector_inl_defd_element_prefix, _nprcvpct)

#if mk_sl_vector_inl_defd_copy == mk_sl_vector_cpy_use_bitblasting
#elif mk_sl_vector_inl_defd_copy == mk_sl_vector_cpy_use_type_suffix
#define mk_sl_vector_inl_defd_element_move_construct
#elif mk_sl_vector_inl_defd_copy == mk_sl_vector_cpy_use_custom
#else
#error xxxxxxxxxx
#endif

#define mk_sl_vector_inl_defd_mallocator_pt mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _pt)
#if mk_sl_vector_inl_defd_mallocator_is_global
#define mk_sl_vector_inl_defd_mallocator_init mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _init)
#define mk_sl_vector_inl_defd_mallocator_deinit mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _deinit)
#define mk_sl_vector_inl_defd_mallocator_allocate mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _allocate)
#define mk_sl_vector_inl_defd_mallocator_deallocate mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _deallocate)
#define mk_sl_vector_inl_defd_mallocator_reallocate mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _reallocate)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_blocks_allocated mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_blocks_allocated)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_blocks_dealocated mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_blocks_dealocated)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_blocks_peak mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_blocks_peak)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_blocks_live mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_blocks_live)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_bytes_allocated mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_bytes_allocated)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_bytes_dealocated mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_bytes_dealocated)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_bytes_peak mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_bytes_peak)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_bytes_live mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_bytes_live)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_all mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_all)
#else
#define mk_sl_vector_inl_defd_mallocator_init mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _init)
#define mk_sl_vector_inl_defd_mallocator_deinit mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _deinit)
#define mk_sl_vector_inl_defd_mallocator_allocate(a, b) mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _allocate)(vector->m_mallocator, a, b)
#define mk_sl_vector_inl_defd_mallocator_deallocate(a, b) mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _deallocate)(vector->m_mallocator, a, b)
#define mk_sl_vector_inl_defd_mallocator_reallocate(a, b, c, d) mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _reallocate)(vector->m_mallocator, a, b, c, d)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_blocks_allocated mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_blocks_allocated)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_blocks_dealocated mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_blocks_dealocated)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_blocks_peak mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_blocks_peak)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_blocks_live mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_blocks_live)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_bytes_allocated mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_bytes_allocated)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_bytes_dealocated mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_bytes_dealocated)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_bytes_peak mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_bytes_peak)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_bytes_live mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_bytes_live)
#define mk_sl_vector_inl_defd_mallocator_statistics_get_all mk_lang_concat(mk_sl_vector_inl_defd_mallocator, _statistics_get_all)
#endif

#define mk_sl_vector_inl_defd_s mk_lang_concat(mk_sl_vector_inl_defd_name, _s)
#define mk_sl_vector_inl_defd_t mk_lang_concat(mk_sl_vector_inl_defd_name, _t)
#define mk_sl_vector_inl_defd_ct mk_lang_concat(mk_sl_vector_inl_defd_name, _ct)
#define mk_sl_vector_inl_defd_vt mk_lang_concat(mk_sl_vector_inl_defd_name, _vt)
#define mk_sl_vector_inl_defd_cvt mk_lang_concat(mk_sl_vector_inl_defd_name, _cvt)
#define mk_sl_vector_inl_defd_pt mk_lang_concat(mk_sl_vector_inl_defd_name, _pt)
#define mk_sl_vector_inl_defd_pct mk_lang_concat(mk_sl_vector_inl_defd_name, _pct)
#define mk_sl_vector_inl_defd_pvt mk_lang_concat(mk_sl_vector_inl_defd_name, _pvt)
#define mk_sl_vector_inl_defd_pcvt mk_lang_concat(mk_sl_vector_inl_defd_name, _pcvt)
#define mk_sl_vector_inl_defd_prt mk_lang_concat(mk_sl_vector_inl_defd_name, _prt)
#define mk_sl_vector_inl_defd_prct mk_lang_concat(mk_sl_vector_inl_defd_name, _prct)
#define mk_sl_vector_inl_defd_prvt mk_lang_concat(mk_sl_vector_inl_defd_name, _prvt)
#define mk_sl_vector_inl_defd_prcvt mk_lang_concat(mk_sl_vector_inl_defd_name, _prcvt)
#define mk_sl_vector_inl_defd_lpt mk_lang_concat(mk_sl_vector_inl_defd_name, _lpt)
#define mk_sl_vector_inl_defd_lpct mk_lang_concat(mk_sl_vector_inl_defd_name, _lpct)
#define mk_sl_vector_inl_defd_lpvt mk_lang_concat(mk_sl_vector_inl_defd_name, _lpvt)
#define mk_sl_vector_inl_defd_lpcvt mk_lang_concat(mk_sl_vector_inl_defd_name, _lpcvt)
#define mk_sl_vector_inl_defd_lprt mk_lang_concat(mk_sl_vector_inl_defd_name, _lprt)
#define mk_sl_vector_inl_defd_lprct mk_lang_concat(mk_sl_vector_inl_defd_name, _lprct)
#define mk_sl_vector_inl_defd_lprvt mk_lang_concat(mk_sl_vector_inl_defd_name, _lprvt)
#define mk_sl_vector_inl_defd_lprcvt mk_lang_concat(mk_sl_vector_inl_defd_name, _lprcvt)
#define mk_sl_vector_inl_defd_npt mk_lang_concat(mk_sl_vector_inl_defd_name, _npt)
#define mk_sl_vector_inl_defd_npct mk_lang_concat(mk_sl_vector_inl_defd_name, _npct)
#define mk_sl_vector_inl_defd_npvt mk_lang_concat(mk_sl_vector_inl_defd_name, _npvt)
#define mk_sl_vector_inl_defd_npcvt mk_lang_concat(mk_sl_vector_inl_defd_name, _npcvt)
#define mk_sl_vector_inl_defd_nprt mk_lang_concat(mk_sl_vector_inl_defd_name, _nprt)
#define mk_sl_vector_inl_defd_nprct mk_lang_concat(mk_sl_vector_inl_defd_name, _nprct)
#define mk_sl_vector_inl_defd_nprvt mk_lang_concat(mk_sl_vector_inl_defd_name, _nprvt)
#define mk_sl_vector_inl_defd_nprcvt mk_lang_concat(mk_sl_vector_inl_defd_name, _nprcvt)
#define mk_sl_vector_inl_defd_cpt mk_lang_concat(mk_sl_vector_inl_defd_name, _cpt)
#define mk_sl_vector_inl_defd_vpt mk_lang_concat(mk_sl_vector_inl_defd_name, _vpt)
#define mk_sl_vector_inl_defd_cvpt mk_lang_concat(mk_sl_vector_inl_defd_name, _cvpt)
#define mk_sl_vector_inl_defd_ppt mk_lang_concat(mk_sl_vector_inl_defd_name, _ppt)
#define mk_sl_vector_inl_defd_pcpt mk_lang_concat(mk_sl_vector_inl_defd_name, _pcpt)
#define mk_sl_vector_inl_defd_pvpt mk_lang_concat(mk_sl_vector_inl_defd_name, _pvpt)
#define mk_sl_vector_inl_defd_pcvpt mk_lang_concat(mk_sl_vector_inl_defd_name, _pcvpt)
#define mk_sl_vector_inl_defd_prpt mk_lang_concat(mk_sl_vector_inl_defd_name, _prpt)
#define mk_sl_vector_inl_defd_prcpt mk_lang_concat(mk_sl_vector_inl_defd_name, _prcpt)
#define mk_sl_vector_inl_defd_prvpt mk_lang_concat(mk_sl_vector_inl_defd_name, _prvpt)
#define mk_sl_vector_inl_defd_prcvpt mk_lang_concat(mk_sl_vector_inl_defd_name, _prcvpt)
#define mk_sl_vector_inl_defd_lppt mk_lang_concat(mk_sl_vector_inl_defd_name, _lppt)
#define mk_sl_vector_inl_defd_lpcpt mk_lang_concat(mk_sl_vector_inl_defd_name, _lpcpt)
#define mk_sl_vector_inl_defd_lpvpt mk_lang_concat(mk_sl_vector_inl_defd_name, _lpvpt)
#define mk_sl_vector_inl_defd_lpcvpt mk_lang_concat(mk_sl_vector_inl_defd_name, _lpcvpt)
#define mk_sl_vector_inl_defd_lprpt mk_lang_concat(mk_sl_vector_inl_defd_name, _lprpt)
#define mk_sl_vector_inl_defd_lprcpt mk_lang_concat(mk_sl_vector_inl_defd_name, _lprcpt)
#define mk_sl_vector_inl_defd_lprvpt mk_lang_concat(mk_sl_vector_inl_defd_name, _lprvpt)
#define mk_sl_vector_inl_defd_lprcvpt mk_lang_concat(mk_sl_vector_inl_defd_name, _lprcvpt)
#define mk_sl_vector_inl_defd_nppt mk_lang_concat(mk_sl_vector_inl_defd_name, _nppt)
#define mk_sl_vector_inl_defd_npcpt mk_lang_concat(mk_sl_vector_inl_defd_name, _npcpt)
#define mk_sl_vector_inl_defd_npvpt mk_lang_concat(mk_sl_vector_inl_defd_name, _npvpt)
#define mk_sl_vector_inl_defd_npcvpt mk_lang_concat(mk_sl_vector_inl_defd_name, _npcvpt)
#define mk_sl_vector_inl_defd_nprpt mk_lang_concat(mk_sl_vector_inl_defd_name, _nprpt)
#define mk_sl_vector_inl_defd_nprcpt mk_lang_concat(mk_sl_vector_inl_defd_name, _nprcpt)
#define mk_sl_vector_inl_defd_nprvpt mk_lang_concat(mk_sl_vector_inl_defd_name, _nprvpt)
#define mk_sl_vector_inl_defd_nprcvpt mk_lang_concat(mk_sl_vector_inl_defd_name, _nprcvpt)
#define mk_sl_vector_inl_defd_cpct mk_lang_concat(mk_sl_vector_inl_defd_name, _cpct)
#define mk_sl_vector_inl_defd_vpct mk_lang_concat(mk_sl_vector_inl_defd_name, _vpct)
#define mk_sl_vector_inl_defd_cvpct mk_lang_concat(mk_sl_vector_inl_defd_name, _cvpct)
#define mk_sl_vector_inl_defd_ppct mk_lang_concat(mk_sl_vector_inl_defd_name, _ppct)
#define mk_sl_vector_inl_defd_pcpct mk_lang_concat(mk_sl_vector_inl_defd_name, _pcpct)
#define mk_sl_vector_inl_defd_pvpct mk_lang_concat(mk_sl_vector_inl_defd_name, _pvpct)
#define mk_sl_vector_inl_defd_pcvpct mk_lang_concat(mk_sl_vector_inl_defd_name, _pcvpct)
#define mk_sl_vector_inl_defd_prpct mk_lang_concat(mk_sl_vector_inl_defd_name, _prpct)
#define mk_sl_vector_inl_defd_prcpct mk_lang_concat(mk_sl_vector_inl_defd_name, _prcpct)
#define mk_sl_vector_inl_defd_prvpct mk_lang_concat(mk_sl_vector_inl_defd_name, _prvpct)
#define mk_sl_vector_inl_defd_prcvpct mk_lang_concat(mk_sl_vector_inl_defd_name, _prcvpct)
#define mk_sl_vector_inl_defd_lppct mk_lang_concat(mk_sl_vector_inl_defd_name, _lppct)
#define mk_sl_vector_inl_defd_lpcpct mk_lang_concat(mk_sl_vector_inl_defd_name, _lpcpct)
#define mk_sl_vector_inl_defd_lpvpct mk_lang_concat(mk_sl_vector_inl_defd_name, _lpvpct)
#define mk_sl_vector_inl_defd_lpcvpct mk_lang_concat(mk_sl_vector_inl_defd_name, _lpcvpct)
#define mk_sl_vector_inl_defd_lprpct mk_lang_concat(mk_sl_vector_inl_defd_name, _lprpct)
#define mk_sl_vector_inl_defd_lprcpct mk_lang_concat(mk_sl_vector_inl_defd_name, _lprcpct)
#define mk_sl_vector_inl_defd_lprvpct mk_lang_concat(mk_sl_vector_inl_defd_name, _lprvpct)
#define mk_sl_vector_inl_defd_lprcvpct mk_lang_concat(mk_sl_vector_inl_defd_name, _lprcvpct)
#define mk_sl_vector_inl_defd_nppct mk_lang_concat(mk_sl_vector_inl_defd_name, _nppct)
#define mk_sl_vector_inl_defd_npcpct mk_lang_concat(mk_sl_vector_inl_defd_name, _npcpct)
#define mk_sl_vector_inl_defd_npvpct mk_lang_concat(mk_sl_vector_inl_defd_name, _npvpct)
#define mk_sl_vector_inl_defd_npcvpct mk_lang_concat(mk_sl_vector_inl_defd_name, _npcvpct)
#define mk_sl_vector_inl_defd_nprpct mk_lang_concat(mk_sl_vector_inl_defd_name, _nprpct)
#define mk_sl_vector_inl_defd_nprcpct mk_lang_concat(mk_sl_vector_inl_defd_name, _nprcpct)
#define mk_sl_vector_inl_defd_nprvpct mk_lang_concat(mk_sl_vector_inl_defd_name, _nprvpct)
#define mk_sl_vector_inl_defd_nprcvpct mk_lang_concat(mk_sl_vector_inl_defd_name, _nprcvpct)

#if mk_sl_vector_inl_defd_mallocator_is_global
#define mk_sl_vector_inl_defd_mallocator_member
#define mk_sl_vector_inl_defd_mallocator_param
#define mk_sl_vector_inl_defd_mallocator_assert() mk_lang_assert(mk_lang_true)
#define mk_sl_vector_inl_defd_mallocator_assign() mk_lang_assert(mk_lang_true)
#else
#define mk_sl_vector_inl_defd_mallocator_member mk_sl_vector_inl_defd_mallocator_pt m_mallocator;
#define mk_sl_vector_inl_defd_mallocator_param , mk_sl_vector_inl_defd_mallocator_pt const mallocator
#define mk_sl_vector_inl_defd_mallocator_assert() mk_lang_assert(mallocator)
#define mk_sl_vector_inl_defd_mallocator_assign() vector->m_mallocator = mallocator
#endif

#define mk_sl_vector_inl_defd_max_capacity_e mk_lang_concat(mk_sl_vector_inl_defd_name, _max_capacity_e)
#define mk_sl_vector_inl_defd_max_capacity_t mk_lang_concat(mk_sl_vector_inl_defd_name, _max_capacity_t)
#define mk_sl_vector_inl_defd_max_capacity_v mk_lang_concat(mk_sl_vector_inl_defd_name, _max_capacity_v)
#define mk_sl_vector_inl_defd_max_capacity_d (mk_lang_limits_usize_max / sizeof(mk_sl_vector_inl_defd_element_t))

#define mk_sl_vector_inl_defd_prro_verify_invariants mk_lang_concat(mk_sl_vector_inl_defd_name, _prro_verify_invariants)

#define mk_sl_vector_inl_defd_st_max_capacity mk_lang_concat(mk_sl_vector_inl_defd_name, _st_max_capacity)

#define mk_sl_vector_inl_defd_ro_max_capacity mk_lang_concat(mk_sl_vector_inl_defd_name, _ro_max_capacity)
#define mk_sl_vector_inl_defd_ro_capacity mk_lang_concat(mk_sl_vector_inl_defd_name, _ro_capacity)
#define mk_sl_vector_inl_defd_ro_size mk_lang_concat(mk_sl_vector_inl_defd_name, _ro_size)
#define mk_sl_vector_inl_defd_ro_free mk_lang_concat(mk_sl_vector_inl_defd_name, _ro_free)
#define mk_sl_vector_inl_defd_ro_is_empty mk_lang_concat(mk_sl_vector_inl_defd_name, _ro_is_empty)
#define mk_sl_vector_inl_defd_ro_is_full mk_lang_concat(mk_sl_vector_inl_defd_name, _ro_is_full)
#define mk_sl_vector_inl_defd_ro_at mk_lang_concat(mk_sl_vector_inl_defd_name, _ro_at)
#define mk_sl_vector_inl_defd_ro_data mk_lang_concat(mk_sl_vector_inl_defd_name, _ro_data)
#define mk_sl_vector_inl_defd_ro_front mk_lang_concat(mk_sl_vector_inl_defd_name, _ro_front)
#define mk_sl_vector_inl_defd_ro_back mk_lang_concat(mk_sl_vector_inl_defd_name, _ro_back)

#define mk_sl_vector_inl_defd_rw_max_capacity mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_max_capacity)
#define mk_sl_vector_inl_defd_rw_capacity mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_capacity)
#define mk_sl_vector_inl_defd_rw_size mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_size)
#define mk_sl_vector_inl_defd_rw_free mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_free)
#define mk_sl_vector_inl_defd_rw_is_empty mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_is_empty)
#define mk_sl_vector_inl_defd_rw_is_full mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_is_full)
#define mk_sl_vector_inl_defd_rw_at mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_at)
#define mk_sl_vector_inl_defd_rw_data mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_data)
#define mk_sl_vector_inl_defd_rw_front mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_front)
#define mk_sl_vector_inl_defd_rw_back mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_back)

#define mk_sl_vector_inl_defd_prrw_destruct_last_count mk_lang_concat(mk_sl_vector_inl_defd_name, _prrw_destruct_last_count)
#define mk_sl_vector_inl_defd_prrw_destruct_all mk_lang_concat(mk_sl_vector_inl_defd_name, _prrw_destruct_all)
#define mk_sl_vector_inl_defd_prrw_move_assign_single mk_lang_concat(mk_sl_vector_inl_defd_name, _prrw_move_assign_single)
#define mk_sl_vector_inl_defd_prrw_move_assign_many mk_lang_concat(mk_sl_vector_inl_defd_name, _prrw_move_assign_many)
#define mk_sl_vector_inl_defd_prrw_copy_assign_many mk_lang_concat(mk_sl_vector_inl_defd_name, _prrw_copy_assign_many)
#define mk_sl_vector_inl_defd_prrw_move_construct_single mk_lang_concat(mk_sl_vector_inl_defd_name, _prrw_move_construct_single)
#define mk_sl_vector_inl_defd_prrw_move_construct_many mk_lang_concat(mk_sl_vector_inl_defd_name, _prrw_move_construct_many)
#define mk_sl_vector_inl_defd_prrw_copy_construct_many mk_lang_concat(mk_sl_vector_inl_defd_name, _prrw_copy_construct_many)
#define mk_sl_vector_inl_defd_prrw_construct_last_count mk_lang_concat(mk_sl_vector_inl_defd_name, _prrw_construct_last_count)

#define mk_sl_vector_inl_defd_rw_construct mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_construct)
#define mk_sl_vector_inl_defd_rw_destroy mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_destroy)
#define mk_sl_vector_inl_defd_rw_reserve_at_least mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_reserve_at_least)
#define mk_sl_vector_inl_defd_rw_reserve_additional mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_reserve_additional)
#define mk_sl_vector_inl_defd_rw_shrink_by mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_shrink_by)
#define mk_sl_vector_inl_defd_rw_resize_to mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_resize_to)
#define mk_sl_vector_inl_defd_rw_clear mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_clear)
#define mk_sl_vector_inl_defd_rw_push_back_move_many mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_push_back_move_many)
#define mk_sl_vector_inl_defd_rw_push_back_copy_many mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_push_back_copy_many)
#define mk_sl_vector_inl_defd_rw_push_back_move_single mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_push_back_move_single)
#define mk_sl_vector_inl_defd_rw_push_back_copy_single mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_push_back_copy_single)
#define mk_sl_vector_inl_defd_rw_pop_back_many mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_pop_back_many)
#define mk_sl_vector_inl_defd_rw_pop_back_single mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_pop_back_single)
#define mk_sl_vector_inl_defd_rw_erase_at mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_erase_at)
#define mk_sl_vector_inl_defd_rw_erase_element mk_lang_concat(mk_sl_vector_inl_defd_name, _rw_erase_element)
