#include "mk_lang_concat.h"
#include "mk_lang_restrict.h"


#if defined mk_sl_sort_merge_proxy_t
#define mk_sl_sort_merge_inl_defd_proxy_tt mk_sl_sort_merge_proxy_t
#else
#define mk_sl_sort_merge_inl_defd_proxy_tt int
#endif

#if defined mk_sl_sort_merge_first_round
#define mk_sl_sort_merge_first_roundd mk_sl_sort_merge_first_round
#else
#define mk_sl_sort_merge_first_roundd 0
#endif

#define mk_sl_sort_merge_inl_defd_data_t mk_sl_sort_merge_data_t
#define mk_sl_sort_merge_inl_defd_data_pt mk_sl_sort_merge_inl_defd_data_t*
#define mk_sl_sort_merge_inl_defd_data_prt mk_sl_sort_merge_inl_defd_data_t* mk_lang_restrict
#define mk_sl_sort_merge_inl_defd_data_pct mk_sl_sort_merge_inl_defd_data_t const*
#define mk_sl_sort_merge_inl_defd_data_prct mk_sl_sort_merge_inl_defd_data_t const* mk_lang_restrict
#define mk_sl_sort_merge_inl_defd_proxy_t mk_sl_sort_merge_inl_defd_proxy_tt
#define mk_sl_sort_merge_inl_defd_proxy_pt mk_sl_sort_merge_inl_defd_proxy_t*
#define mk_sl_sort_merge_inl_defd_proxy_prt mk_sl_sort_merge_inl_defd_proxy_t* mk_lang_restrict
#define mk_sl_sort_merge_inl_defd_proxy_pct mk_sl_sort_merge_inl_defd_proxy_t const*
#define mk_sl_sort_merge_inl_defd_proxy_prct mk_sl_sort_merge_inl_defd_proxy_t const* mk_lang_restrict
#define mk_sl_sort_merge_inl_defd_count_t mk_sl_sort_merge_count_t

#define mk_sl_sort_merge_inl_defd_first_round mk_sl_sort_merge_first_roundd

#define mk_sl_sort_merge_inl_defd_count_count_leading_zeros mk_lang_concat(mk_sl_sort_merge_count_math_prefix, _count_leading_zeros)

#define mk_sl_sort_merge_inl_defd_fn_is_sorted_plain mk_sl_sort_merge_is_sorted
#define mk_sl_sort_merge_inl_defd_fn_is_sorted_proxy mk_sl_sort_merge_is_sorted
#define mk_sl_sort_merge_inl_defd_fn_first_round_plain_inplace mk_lang_concat(mk_lang_concat(mk_sl_sort_merge_, mk_sl_sort_merge_name), _first_round_plain_inplace)
#define mk_sl_sort_merge_inl_defd_fn_first_round_plain_copy mk_lang_concat(mk_lang_concat(mk_sl_sort_merge_, mk_sl_sort_merge_name), _first_round_plain_copy)
#define mk_sl_sort_merge_inl_defd_fn_first_round_plain mk_lang_concat(mk_lang_concat(mk_sl_sort_merge_, mk_sl_sort_merge_name), _first_round_plain)
#define mk_sl_sort_merge_inl_defd_fn_first_round_proxy_inplace mk_lang_concat(mk_lang_concat(mk_sl_sort_merge_, mk_sl_sort_merge_name), _first_round_proxy_inplace)
#define mk_sl_sort_merge_inl_defd_fn_first_round_proxy_copy mk_lang_concat(mk_lang_concat(mk_sl_sort_merge_, mk_sl_sort_merge_name), _first_round_proxy_copy)
#define mk_sl_sort_merge_inl_defd_fn_first_round_proxy mk_lang_concat(mk_lang_concat(mk_sl_sort_merge_, mk_sl_sort_merge_name), _first_round_proxy)
#define mk_sl_sort_merge_inl_defd_fn_merge_plain mk_lang_concat(mk_lang_concat(mk_sl_sort_merge_, mk_sl_sort_merge_name), _merge_plain)
#define mk_sl_sort_merge_inl_defd_fn_merge_proxy mk_lang_concat(mk_lang_concat(mk_sl_sort_merge_, mk_sl_sort_merge_name), _merge_proxy)
#define mk_sl_sort_merge_inl_defd_fn_plain mk_lang_concat(mk_lang_concat(mk_sl_sort_merge_, mk_sl_sort_merge_name), _plain)
#define mk_sl_sort_merge_inl_defd_fn_proxy mk_lang_concat(mk_lang_concat(mk_sl_sort_merge_, mk_sl_sort_merge_name), _proxy)
