#include "mk_lang_concat.h"


#define mk_sl_speed_counter_inl_defd_name mk_sl_speed_counter_t_name
#define mk_sl_speed_counter_inl_defd_item_prefix mk_sl_speed_counter_t_item_prefix
#define mk_sl_speed_counter_inl_defd_time_prefix mk_sl_speed_counter_t_time_prefix
#define mk_sl_speed_counter_inl_defd_time_denominator (mk_sl_speed_counter_t_time_denominator)
#define mk_sl_speed_counter_inl_defd_time_granule_size (mk_sl_speed_counter_t_time_granule_size)
#define mk_sl_speed_counter_inl_defd_time_granule_count (mk_sl_speed_counter_t_time_granule_count)

#define mk_sl_speed_counter_inl_defd_prefix mk_lang_concat(mk_sl_speed_counter_, mk_sl_speed_counter_inl_defd_name)

#define mk_sl_speed_counter_inl_defd_s mk_lang_concat(mk_sl_speed_counter_inl_defd_prefix, _s)
#define mk_sl_speed_counter_inl_defd_t mk_lang_concat(mk_sl_speed_counter_inl_defd_prefix, _t)
#define mk_sl_speed_counter_inl_defd_ct mk_lang_concat(mk_sl_speed_counter_inl_defd_prefix, _ct)
#define mk_sl_speed_counter_inl_defd_pt mk_lang_concat(mk_sl_speed_counter_inl_defd_prefix, _pt)
#define mk_sl_speed_counter_inl_defd_pct mk_lang_concat(mk_sl_speed_counter_inl_defd_prefix, _pct)

#define mk_sl_speed_counter_inl_defd_construct mk_lang_concat(mk_sl_speed_counter_inl_defd_prefix, _construct)
#define mk_sl_speed_counter_inl_defd_count mk_lang_concat(mk_sl_speed_counter_inl_defd_prefix, _count)
#define mk_sl_speed_counter_inl_defd_get_time_quantized mk_lang_concat(mk_sl_speed_counter_inl_defd_prefix, _get_time_quantized)
#define mk_sl_speed_counter_inl_defd_get_speed mk_lang_concat(mk_sl_speed_counter_inl_defd_prefix, _get_speed)

#define mk_sl_speed_counter_inl_defd_item_t mk_lang_concat(mk_sl_speed_counter_t_item_prefix, _t)
#define mk_sl_speed_counter_inl_defd_item_ct mk_lang_concat(mk_sl_speed_counter_t_item_prefix, _ct)
#define mk_sl_speed_counter_inl_defd_item_pt mk_lang_concat(mk_sl_speed_counter_t_item_prefix, _pt)
#define mk_sl_speed_counter_inl_defd_item_pct mk_lang_concat(mk_sl_speed_counter_t_item_prefix, _pct)
#define mk_sl_speed_counter_inl_defd_item_memmove mk_lang_concat(mk_lang_memmove_obj_, mk_lang_concat(mk_sl_speed_counter_inl_defd_prefix, _item))
#define mk_sl_speed_counter_inl_defd_item_set_zero mk_lang_concat(mk_sl_speed_counter_t_item_prefix, _set_zero)
#define mk_sl_speed_counter_inl_defd_item_to_bi_uint mk_lang_concat(mk_sl_speed_counter_t_item_prefix, _to_bi_uint)
#define mk_sl_speed_counter_inl_defd_item_from_bi_uint mk_lang_concat(mk_sl_speed_counter_t_item_prefix, _from_bi_uint)
#define mk_sl_speed_counter_inl_defd_item_is_max mk_lang_concat(mk_sl_speed_counter_t_item_prefix, _is_max)
#define mk_sl_speed_counter_inl_defd_item_shr3 mk_lang_concat(mk_sl_speed_counter_t_item_prefix, _shr3)
#define mk_sl_speed_counter_inl_defd_item_inc1 mk_lang_concat(mk_sl_speed_counter_t_item_prefix, _inc1)
#define mk_sl_speed_counter_inl_defd_item_would_overflow_add_cc mk_lang_concat(mk_sl_speed_counter_t_item_prefix, _would_overflow_add_cc)
#define mk_sl_speed_counter_inl_defd_item_add2_wrap_cid_cod mk_lang_concat(mk_sl_speed_counter_t_item_prefix, _add2_wrap_cid_cod)
#define mk_sl_speed_counter_inl_defd_item_add3_wrap_cid_cod mk_lang_concat(mk_sl_speed_counter_t_item_prefix, _add3_wrap_cid_cod)
#define mk_sl_speed_counter_inl_defd_item_mul3_wrap_lo mk_lang_concat(mk_sl_speed_counter_t_item_prefix, _mul3_wrap_lo)

#define mk_sl_speed_counter_inl_defd_time_t mk_lang_concat(mk_sl_speed_counter_t_time_prefix, _t)
#define mk_sl_speed_counter_inl_defd_time_ct mk_lang_concat(mk_sl_speed_counter_t_time_prefix, _ct)
#define mk_sl_speed_counter_inl_defd_time_pt mk_lang_concat(mk_sl_speed_counter_t_time_prefix, _pt)
#define mk_sl_speed_counter_inl_defd_time_pct mk_lang_concat(mk_sl_speed_counter_t_time_prefix, _pct)
#define mk_sl_speed_counter_inl_defd_time_set_zero mk_lang_concat(mk_sl_speed_counter_t_time_prefix, _set_zero)
#define mk_sl_speed_counter_inl_defd_time_to_bi_ulllong mk_lang_concat(mk_sl_speed_counter_t_time_prefix, _to_bi_ulllong)
#define mk_sl_speed_counter_inl_defd_time_from_bi_ulllong mk_lang_concat(mk_sl_speed_counter_t_time_prefix, _from_bi_ulllong)
#define mk_sl_speed_counter_inl_defd_time_sub3_wrap_cid_cod mk_lang_concat(mk_sl_speed_counter_t_time_prefix, _sub3_wrap_cid_cod)
#define mk_sl_speed_counter_inl_defd_time_div3_wrap mk_lang_concat(mk_sl_speed_counter_t_time_prefix, _div3_wrap)
