#undef mk_sl_vector_t_name
#undef mk_sl_vector_t_element_type
#undef mk_sl_vector_t_mallocatorg
#undef mk_sl_vector_t_mallocatorl
#undef mk_sl_vector_t_copy_style
#undef mk_sl_vector_t_element_construct_void
#undef mk_sl_vector_t_element_destruct
#undef mk_sl_vector_t_element_copy_construct
#undef mk_sl_vector_t_element_move_construct
#undef mk_sl_vector_t_element_copy_assign
#undef mk_sl_vector_t_element_move_assign
#undef mk_sl_vector_t_element_eq
