#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_types.h"


#include "mk_sl_fixed_tree_wavl_inl_defd.h"


typedef mk_sl_fixed_tree_wavl_inl_defd_element_type mk_sl_fixed_tree_wavl_inl_defd_element_t;
typedef mk_sl_fixed_tree_wavl_inl_defd_element_t const mk_sl_fixed_tree_wavl_inl_defd_element_ct;
typedef mk_sl_fixed_tree_wavl_inl_defd_element_t* mk_sl_fixed_tree_wavl_inl_defd_element_pt;
typedef mk_sl_fixed_tree_wavl_inl_defd_element_t const* mk_sl_fixed_tree_wavl_inl_defd_element_pct;
typedef mk_sl_fixed_tree_wavl_inl_defd_element_pt const mk_sl_fixed_tree_wavl_inl_defd_element_cpt;
typedef mk_sl_fixed_tree_wavl_inl_defd_element_pt* mk_sl_fixed_tree_wavl_inl_defd_element_ppt;
typedef mk_sl_fixed_tree_wavl_inl_defd_element_pt const* mk_sl_fixed_tree_wavl_inl_defd_element_pcpt;
typedef mk_sl_fixed_tree_wavl_inl_defd_element_pct const mk_sl_fixed_tree_wavl_inl_defd_element_cpct;
typedef mk_sl_fixed_tree_wavl_inl_defd_element_pct* mk_sl_fixed_tree_wavl_inl_defd_element_ppct;
typedef mk_sl_fixed_tree_wavl_inl_defd_element_pct const* mk_sl_fixed_tree_wavl_inl_defd_element_pcpct;


struct mk_sl_fixed_tree_wavl_inl_defd_node_s;
typedef struct mk_sl_fixed_tree_wavl_inl_defd_node_s mk_sl_fixed_tree_wavl_inl_defd_node_t;
typedef mk_sl_fixed_tree_wavl_inl_defd_node_t const mk_sl_fixed_tree_wavl_inl_defd_node_ct;
typedef mk_sl_fixed_tree_wavl_inl_defd_node_t* mk_sl_fixed_tree_wavl_inl_defd_node_pt;
typedef mk_sl_fixed_tree_wavl_inl_defd_node_t const* mk_sl_fixed_tree_wavl_inl_defd_node_pct;
typedef mk_sl_fixed_tree_wavl_inl_defd_node_pt const mk_sl_fixed_tree_wavl_inl_defd_node_cpt;
typedef mk_sl_fixed_tree_wavl_inl_defd_node_pt* mk_sl_fixed_tree_wavl_inl_defd_node_ppt;
typedef mk_sl_fixed_tree_wavl_inl_defd_node_pt const* mk_sl_fixed_tree_wavl_inl_defd_node_pcpt;
typedef mk_sl_fixed_tree_wavl_inl_defd_node_pct const mk_sl_fixed_tree_wavl_inl_defd_node_cpct;
typedef mk_sl_fixed_tree_wavl_inl_defd_node_pct* mk_sl_fixed_tree_wavl_inl_defd_node_ppct;
typedef mk_sl_fixed_tree_wavl_inl_defd_node_pct const* mk_sl_fixed_tree_wavl_inl_defd_node_pcpct;
struct mk_sl_fixed_tree_wavl_inl_defd_node_s
{
	mk_sl_fixed_tree_wavl_inl_defd_node_pt m_left;
	mk_sl_fixed_tree_wavl_inl_defd_node_pt m_right;
	mk_sl_fixed_tree_wavl_inl_defd_node_pt m_parent;
	mk_lang_types_sint_t m_ref_count_and_rank_diff;
	mk_sl_fixed_tree_wavl_inl_defd_element_t m_element;
};

#define mk_sl_fixed_vector_t_name mk_sl_fixed_tree_wavl_inl_defd_fv_name
#define mk_sl_fixed_vector_t_element mk_sl_fixed_tree_wavl_inl_defd_node_t
#define mk_sl_fixed_vector_t_count mk_sl_fixed_tree_wavl_inl_defd_capacity
#include "mk_sl_fixed_vector_inl_fileh.h"
#undef mk_sl_fixed_vector_t_name
#undef mk_sl_fixed_vector_t_element
#undef mk_sl_fixed_vector_t_count


struct mk_sl_fixed_tree_wavl_inl_defd_s
{
	mk_sl_fixed_tree_wavl_inl_defd_node_pt m_root;
	mk_sl_fixed_tree_wavl_inl_defd_fv_t m_fv;
};
typedef struct mk_sl_fixed_tree_wavl_inl_defd_s mk_sl_fixed_tree_wavl_inl_defd_t;
typedef mk_sl_fixed_tree_wavl_inl_defd_t const mk_sl_fixed_tree_wavl_inl_defd_ct;
typedef mk_sl_fixed_tree_wavl_inl_defd_t* mk_sl_fixed_tree_wavl_inl_defd_pt;
typedef mk_sl_fixed_tree_wavl_inl_defd_t const* mk_sl_fixed_tree_wavl_inl_defd_pct;
typedef mk_sl_fixed_tree_wavl_inl_defd_pt const mk_sl_fixed_tree_wavl_inl_defd_cpt;
typedef mk_sl_fixed_tree_wavl_inl_defd_pt* mk_sl_fixed_tree_wavl_inl_defd_ppt;
typedef mk_sl_fixed_tree_wavl_inl_defd_pt const* mk_sl_fixed_tree_wavl_inl_defd_pcpt;
typedef mk_sl_fixed_tree_wavl_inl_defd_pct const mk_sl_fixed_tree_wavl_inl_defd_cpct;
typedef mk_sl_fixed_tree_wavl_inl_defd_pct* mk_sl_fixed_tree_wavl_inl_defd_ppct;
typedef mk_sl_fixed_tree_wavl_inl_defd_pct const* mk_sl_fixed_tree_wavl_inl_defd_pcpct;


mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_fixed_tree_wavl_inl_defd_rw_construct(mk_sl_fixed_tree_wavl_inl_defd_pt const tree) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_fixed_tree_wavl_inl_defd_rw_destroy(mk_sl_fixed_tree_wavl_inl_defd_pt const tree) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_fixed_tree_wavl_inl_defd_rw_insert_element(mk_sl_fixed_tree_wavl_inl_defd_pt const tree, mk_sl_fixed_tree_wavl_inl_defd_element_pct const element, mk_sl_fixed_tree_wavl_inl_defd_node_ppct const node) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_fixed_tree_wavl_inl_defd_rw_insert_node(mk_sl_fixed_tree_wavl_inl_defd_pt const tree, mk_sl_fixed_tree_wavl_inl_defd_node_pt const node) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_fixed_tree_wavl_inl_defd_rw_find(mk_sl_fixed_tree_wavl_inl_defd_pt const tree, mk_sl_fixed_tree_wavl_inl_defd_element_pct const element, mk_sl_fixed_tree_wavl_inl_defd_node_ppct const node) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_fixed_tree_wavl_inl_defd_rw_decrement_node(mk_sl_fixed_tree_wavl_inl_defd_pt const tree, mk_sl_fixed_tree_wavl_inl_defd_node_pct const node) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_fixed_tree_wavl_inl_defd_rw_remove_node(mk_sl_fixed_tree_wavl_inl_defd_pt const tree, mk_sl_fixed_tree_wavl_inl_defd_node_pct const node) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_fixed_tree_wavl_inl_defd_ro_node_get_element(mk_sl_fixed_tree_wavl_inl_defd_node_pct const node, mk_sl_fixed_tree_wavl_inl_defd_element_ppct const element) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_fixed_tree_wavl_inl_defd_rw_node_get_element(mk_sl_fixed_tree_wavl_inl_defd_node_pt const node, mk_sl_fixed_tree_wavl_inl_defd_element_ppt const element) mk_lang_noexcept;


#include "mk_sl_fixed_tree_wavl_inl_defu.h"
