include(`mk_lang_typedef.m')dnl
#include "mk_lang_concat.h"
#include "mk_lang_limits.h"
#include "mk_lang_types.h"
#include "mk_sl_fixed_vector_copy.h"


#if(!( \
	(defined mk_sl_fixed_vector_t_name) && \
	(defined mk_sl_fixed_vector_t_element_type) && \
	(defined mk_sl_fixed_vector_t_capacity && (mk_sl_fixed_vector_t_capacity) >= 1 && (mk_sl_fixed_vector_t_capacity) <= 1 * 1024 * 1024 * 1024) && \
	((defined mk_sl_fixed_vector_t_copy_style && ((mk_sl_fixed_vector_t_copy_style) == mk_sl_fixed_vector_copy_use_bitblt || (mk_sl_fixed_vector_t_copy_style) == mk_sl_fixed_vector_copy_use_custom)) || !defined mk_sl_fixed_vector_t_copy_style) && \
	(defined mk_sl_fixed_vector_t_element_construct_void || !defined mk_sl_fixed_vector_t_element_construct_void) && \
	(defined mk_sl_fixed_vector_t_element_destroy || !defined mk_sl_fixed_vector_t_element_destroy) && \
	(defined mk_sl_fixed_vector_t_element_construct_copy || !defined mk_sl_fixed_vector_t_element_construct_copy) && \
	(defined mk_sl_fixed_vector_t_element_construct_move || !defined mk_sl_fixed_vector_t_element_construct_move) && \
	(defined mk_sl_fixed_vector_t_element_assign_copy || !defined mk_sl_fixed_vector_t_element_assign_copy) && \
	(defined mk_sl_fixed_vector_t_element_assign_move || !defined mk_sl_fixed_vector_t_element_assign_move) && \
	(defined mk_sl_fixed_vector_t_element_eq || !defined mk_sl_fixed_vector_t_element_eq) && \
1))
#error xxxxxxxxxx
#endif


#if( \
	defined mk_sl_fixed_vector_t_element_construct_void || \
	defined mk_sl_fixed_vector_t_element_destroy || \
0)
#if(!( \
	defined mk_sl_fixed_vector_t_element_construct_void && \
	defined mk_sl_fixed_vector_t_element_destroy && \
1))
#error xxxxxxxxxx
#endif
#endif

#if( \
	defined mk_sl_fixed_vector_t_element_construct_copy || \
	defined mk_sl_fixed_vector_t_element_assign_copy || \
0)
#if(!( \
	defined mk_sl_fixed_vector_t_element_construct_copy && \
	defined mk_sl_fixed_vector_t_element_assign_copy && \
1))
#error xxxxxxxxxx
#endif
#endif

#if( \
	defined mk_sl_fixed_vector_t_element_construct_move || \
	defined mk_sl_fixed_vector_t_element_assign_move || \
0)
#if(!( \
	defined mk_sl_fixed_vector_t_element_construct_move && \
	defined mk_sl_fixed_vector_t_element_assign_move && \
1))
#error xxxxxxxxxx
#endif
#endif


#define mk_sl_fixed_vector_inl_defd_name mk_sl_fixed_vector_t_name
#define mk_sl_fixed_vector_inl_defd_element_type mk_sl_fixed_vector_t_element_type
#define mk_sl_fixed_vector_inl_defd_capacity (mk_sl_fixed_vector_t_capacity)

#if defined mk_sl_fixed_vector_t_copy_style
#define mk_sl_fixed_vector_inl_defd_copy_style (mk_sl_fixed_vector_t_copy_style)
#else
#if defined mk_sl_fixed_vector_t_element_construct_copy && defined mk_sl_fixed_vector_t_element_assign_copy
#define mk_sl_fixed_vector_inl_defd_copy_style mk_sl_fixed_vector_copy_use_custom
#else
#if defined mk_sl_fixed_vector_t_element_construct_move && defined mk_sl_fixed_vector_t_element_assign_move
#define mk_sl_fixed_vector_inl_defd_copy_style mk_sl_fixed_vector_copy_use_custom
#else
#define mk_sl_fixed_vector_inl_defd_copy_style mk_sl_fixed_vector_copy_use_bitblt
#endif
#endif
#endif

#if defined mk_sl_fixed_vector_t_element_construct_void && defined mk_sl_fixed_vector_t_element_destroy
#define mk_sl_fixed_vector_inl_defd_element_construct_destroy_has 1
#define mk_sl_fixed_vector_inl_defd_element_construct_void mk_sl_fixed_vector_t_element_construct_void
#define mk_sl_fixed_vector_inl_defd_element_destroy mk_sl_fixed_vector_t_element_destroy
#else
#define mk_sl_fixed_vector_inl_defd_element_construct_destroy_has 0
#endif

#if defined mk_sl_fixed_vector_t_element_construct_copy && defined mk_sl_fixed_vector_t_element_assign_copy
#define mk_sl_fixed_vector_inl_defd_element_copy_has 1
#define mk_sl_fixed_vector_inl_defd_element_construct_copy(a, b) mk_sl_fixed_vector_t_element_construct_copy((a), (b))
#define mk_sl_fixed_vector_inl_defd_element_assign_copy(a, b) mk_sl_fixed_vector_t_element_assign_copy((a), (b))
#else
#define mk_sl_fixed_vector_inl_defd_element_copy_has 0
#endif

#if defined mk_sl_fixed_vector_t_element_construct_move && defined mk_sl_fixed_vector_t_element_assign_move
#define mk_sl_fixed_vector_inl_defd_element_move_has 1
#define mk_sl_fixed_vector_inl_defd_element_construct_move(a, b) mk_sl_fixed_vector_t_element_construct_move((a), (b))
#define mk_sl_fixed_vector_inl_defd_element_assign_move(a, b) mk_sl_fixed_vector_t_element_assign_move((a), (b))
#else
#define mk_sl_fixed_vector_inl_defd_element_move_has 0
#endif

#if defined mk_sl_fixed_vector_t_element_eq
#define mk_sl_fixed_vector_inl_defd_element_eq_has 1
#define mk_sl_fixed_vector_inl_defd_element_eq_fn mk_sl_fixed_vector_t_element_eq
#else
#define mk_sl_fixed_vector_inl_defd_element_eq_has 0
#endif





#define mk_sl_fixed_vector_inl_defd_element_prefix mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _element)
#define mk_sl_fixed_vector_inl_defd_element_s mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _s)
#define mk_sl_fixed_vector_inl_defd_element_t mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _t)
mm_per_typedef(`#define mk_sl_fixed_vector_inl_defd_element_$1 mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _$1)')

#define mk_sl_fixed_vector_inl_defd_s mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _s)
#define mk_sl_fixed_vector_inl_defd_t mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _t)
mm_per_typedef(`#define mk_sl_fixed_vector_inl_defd_$1 mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _$1)')





#define mk_sl_fixed_vector_inl_defd_prrw_element_bitblt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_element_assign_bitblt)
#define mk_sl_fixed_vector_inl_defd_prrw_element_construct_void mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_element_construct_void)
#define mk_sl_fixed_vector_inl_defd_prrw_element_destroy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_element_destroy)
#define mk_sl_fixed_vector_inl_defd_prrw_element_construct_copy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_element_construct_copy)
#define mk_sl_fixed_vector_inl_defd_prrw_element_construct_move mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_element_construct_move)
#define mk_sl_fixed_vector_inl_defd_prrw_element_assign_copy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_element_assign_copy)
#define mk_sl_fixed_vector_inl_defd_prrw_element_assign_move mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_element_assign_move)
#define mk_sl_fixed_vector_inl_defd_prrw_element_eq mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_element_eq)

#define mk_sl_fixed_vector_inl_defd_prro_verify_invariants mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_verify_invariants)

#define mk_sl_fixed_vector_inl_defd_prst_max_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prst_max_capacity)
#define mk_sl_fixed_vector_inl_defd_prro_max_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_max_capacity)
#define mk_sl_fixed_vector_inl_defd_prro_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_capacity)
#define mk_sl_fixed_vector_inl_defd_prro_size mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_size)
#define mk_sl_fixed_vector_inl_defd_prro_sise mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_sise)
#define mk_sl_fixed_vector_inl_defd_prro_free mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_free)
#define mk_sl_fixed_vector_inl_defd_prro_is_empty mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_is_empty)
#define mk_sl_fixed_vector_inl_defd_prro_is_full mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_is_full)
#define mk_sl_fixed_vector_inl_defd_prro_data mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_data)
#define mk_sl_fixed_vector_inl_defd_prro_at mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_at)
#define mk_sl_fixed_vector_inl_defd_prro_front mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_front)
#define mk_sl_fixed_vector_inl_defd_prro_back mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_back)
#define mk_sl_fixed_vector_inl_defd_prro_eq mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_eq)
#define mk_sl_fixed_vector_inl_defd_prro_ne mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_ne)

#define mk_sl_fixed_vector_inl_defd_prrw_max_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_max_capacity)
#define mk_sl_fixed_vector_inl_defd_prrw_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_capacity)
#define mk_sl_fixed_vector_inl_defd_prrw_size mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_size)
#define mk_sl_fixed_vector_inl_defd_prrw_sise mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_sise)
#define mk_sl_fixed_vector_inl_defd_prrw_free mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_free)
#define mk_sl_fixed_vector_inl_defd_prrw_is_empty mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_is_empty)
#define mk_sl_fixed_vector_inl_defd_prrw_is_full mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_is_full)
#define mk_sl_fixed_vector_inl_defd_prrw_data mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_data)
#define mk_sl_fixed_vector_inl_defd_prrw_at mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_at)
#define mk_sl_fixed_vector_inl_defd_prrw_front mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_front)
#define mk_sl_fixed_vector_inl_defd_prrw_back mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_back)
#define mk_sl_fixed_vector_inl_defd_prrw_eq mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_eq)
#define mk_sl_fixed_vector_inl_defd_prrw_ne mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_ne)

#define mk_sl_fixed_vector_inl_defd_prrw_elements_construct_void_from_to mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_construct_void_from_to)
#define mk_sl_fixed_vector_inl_defd_prrw_elements_destroy_from_to mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_destroy_from_to)
#define mk_sl_fixed_vector_inl_defd_prrw_elements_construct_void_last mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_construct_void_last)
#define mk_sl_fixed_vector_inl_defd_prrw_elements_destroy_last mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_destroy_last)
#define mk_sl_fixed_vector_inl_defd_prrw_elements_destroy_all mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_destroy_all)
#define mk_sl_fixed_vector_inl_defd_prrw_elements_construct_copy_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_construct_copy_many)
#define mk_sl_fixed_vector_inl_defd_prrw_elements_construct_move_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_construct_move_many)
#define mk_sl_fixed_vector_inl_defd_prrw_elements_assign_copy_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_assign_copy_many)
#define mk_sl_fixed_vector_inl_defd_prrw_elements_assign_move_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_assign_move_many)

#define mk_sl_fixed_vector_inl_defd_prrw_construct_void mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_construct_void)
#define mk_sl_fixed_vector_inl_defd_prrw_destroy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_destroy)
#define mk_sl_fixed_vector_inl_defd_prrw_construct_copy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_construct_copy)
#define mk_sl_fixed_vector_inl_defd_prrw_construct_move mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_construct_move)
#define mk_sl_fixed_vector_inl_defd_prrw_assign_copy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_assign_copy)
#define mk_sl_fixed_vector_inl_defd_prrw_assign_move mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_assign_move)
#define mk_sl_fixed_vector_inl_defd_prrw_reserve_at_least mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_reserve_at_least)
#define mk_sl_fixed_vector_inl_defd_prrw_reserve_additional mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_reserve_additional)
#define mk_sl_fixed_vector_inl_defd_prrw_shrink_by mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_shrink_by)
#define mk_sl_fixed_vector_inl_defd_prrw_resize_to mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_resize_to)
#define mk_sl_fixed_vector_inl_defd_prrw_grow_by mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_grow_by)
#define mk_sl_fixed_vector_inl_defd_prrw_clear mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_clear)
#define mk_sl_fixed_vector_inl_defd_prrw_push_back_copy_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_push_back_copy_many)
#define mk_sl_fixed_vector_inl_defd_prrw_push_back_move_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_push_back_move_many)
#define mk_sl_fixed_vector_inl_defd_prrw_push_back_copy_single mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_push_back_copy_single)
#define mk_sl_fixed_vector_inl_defd_prrw_push_back_move_single mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_push_back_move_single)
#define mk_sl_fixed_vector_inl_defd_prrw_pop_back_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_pop_back_many)
#define mk_sl_fixed_vector_inl_defd_prrw_pop_back_single mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_pop_back_single)
#define mk_sl_fixed_vector_inl_defd_prrw_erase_at mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_erase_at)
#define mk_sl_fixed_vector_inl_defd_prrw_erase_element mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_erase_element)





#define mk_sl_fixed_vector_inl_defd_capacity_e mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _capacity_e)
#define mk_sl_fixed_vector_inl_defd_capacity_t mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _capacity_t)
#define mk_sl_fixed_vector_inl_defd_capacity_v mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _capacity_v)
#define mk_sl_fixed_vector_inl_defd_capacity_d mk_sl_fixed_vector_inl_defd_capacity
#define mk_sl_fixed_vector_inl_defd_capacity_k mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _capacity_k)

#define mk_sl_fixed_vector_inl_defd_st_max_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _st_max_capacity)

#define mk_sl_fixed_vector_inl_defd_ro_max_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_max_capacity)
#define mk_sl_fixed_vector_inl_defd_ro_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_capacity)
#define mk_sl_fixed_vector_inl_defd_ro_size mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_size)
#define mk_sl_fixed_vector_inl_defd_ro_sise mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_sise)
#define mk_sl_fixed_vector_inl_defd_ro_free mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_free)
#define mk_sl_fixed_vector_inl_defd_ro_is_empty mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_is_empty)
#define mk_sl_fixed_vector_inl_defd_ro_is_full mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_is_full)
#define mk_sl_fixed_vector_inl_defd_ro_at mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_at)
#define mk_sl_fixed_vector_inl_defd_ro_data mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_data)
#define mk_sl_fixed_vector_inl_defd_ro_front mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_front)
#define mk_sl_fixed_vector_inl_defd_ro_back mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_back)
#define mk_sl_fixed_vector_inl_defd_ro_eq mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_eq)
#define mk_sl_fixed_vector_inl_defd_ro_ne mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_ne)

#define mk_sl_fixed_vector_inl_defd_rw_max_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_max_capacity)
#define mk_sl_fixed_vector_inl_defd_rw_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_capacity)
#define mk_sl_fixed_vector_inl_defd_rw_size mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_size)
#define mk_sl_fixed_vector_inl_defd_rw_sise mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_sise)
#define mk_sl_fixed_vector_inl_defd_rw_free mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_free)
#define mk_sl_fixed_vector_inl_defd_rw_is_empty mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_is_empty)
#define mk_sl_fixed_vector_inl_defd_rw_is_full mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_is_full)
#define mk_sl_fixed_vector_inl_defd_rw_at mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_at)
#define mk_sl_fixed_vector_inl_defd_rw_data mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_data)
#define mk_sl_fixed_vector_inl_defd_rw_front mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_front)
#define mk_sl_fixed_vector_inl_defd_rw_back mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_back)
#define mk_sl_fixed_vector_inl_defd_rw_eq mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_eq)
#define mk_sl_fixed_vector_inl_defd_rw_ne mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_ne)

#define mk_sl_fixed_vector_inl_defd_rw_construct_void mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_construct_void)
#define mk_sl_fixed_vector_inl_defd_rw_destroy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_destroy)
#define mk_sl_fixed_vector_inl_defd_rw_construct_copy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_construct_copy)
#define mk_sl_fixed_vector_inl_defd_rw_construct_move mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_construct_move)
#define mk_sl_fixed_vector_inl_defd_rw_assign_copy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_assign_copy)
#define mk_sl_fixed_vector_inl_defd_rw_assign_move mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_assign_move)
#define mk_sl_fixed_vector_inl_defd_rw_reserve_at_least mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_reserve_at_least)
#define mk_sl_fixed_vector_inl_defd_rw_reserve_additional mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_reserve_additional)
#define mk_sl_fixed_vector_inl_defd_rw_shrink_by mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_shrink_by)
#define mk_sl_fixed_vector_inl_defd_rw_resize_to mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_resize_to)
#define mk_sl_fixed_vector_inl_defd_rw_grow_by mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_grow_by)
#define mk_sl_fixed_vector_inl_defd_rw_clear mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_clear)
#define mk_sl_fixed_vector_inl_defd_rw_push_back_copy_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_push_back_copy_many)
#define mk_sl_fixed_vector_inl_defd_rw_push_back_move_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_push_back_move_many)
#define mk_sl_fixed_vector_inl_defd_rw_push_back_copy_single mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_push_back_copy_single)
#define mk_sl_fixed_vector_inl_defd_rw_push_back_move_single mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_push_back_move_single)
#define mk_sl_fixed_vector_inl_defd_rw_pop_back_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_pop_back_many)
#define mk_sl_fixed_vector_inl_defd_rw_pop_back_single mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_pop_back_single)
#define mk_sl_fixed_vector_inl_defd_rw_erase_at mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_erase_at)
#define mk_sl_fixed_vector_inl_defd_rw_erase_element mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_erase_element)
