#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_noalias.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_restrict.h"
#include "mk_lang_sizeof.h"
#include "mk_lang_tchar.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"


mk_lang_forward(mk_sl_cui_uint1024);
mk_lang_forward(mk_sl_cui_uint128);
mk_lang_forward(mk_sl_cui_uint16);
mk_lang_forward(mk_sl_cui_uint256);
mk_lang_forward(mk_sl_cui_uint32);
mk_lang_forward(mk_sl_cui_uint512);
mk_lang_forward(mk_sl_cui_uint64);
mk_lang_forward(mk_sl_cui_uint8);


#include "mk_sl_fxp_inl_defd.h"


typedef mk_sl_fxp_inl_defd_base_type_name_t mk_sl_fxp_inl_defd_base_t;
mk_lang_typedef(mk_sl_fxp_inl_defd_base);


enum mk_sl_fxp_inl_defd_bits_before_e{ mk_sl_fxp_inl_defd_bits_before_v = mk_sl_fxp_inl_defd_bits_before_d }; typedef enum mk_sl_fxp_inl_defd_bits_before_e mk_sl_fxp_inl_defd_bits_before_t;
enum mk_sl_fxp_inl_defd_bits_after_e { mk_sl_fxp_inl_defd_bits_after_v  = mk_sl_fxp_inl_defd_bits_after_d  }; typedef enum mk_sl_fxp_inl_defd_bits_after_e  mk_sl_fxp_inl_defd_bits_after_t ;


struct mk_sl_fxp_inl_defd_s
{
	mk_sl_fxp_inl_defd_alignme mk_sl_fxp_inl_defd_base_t m_base;
};
typedef struct mk_sl_fxp_inl_defd_s mk_sl_fxp_inl_defd_t;
mk_lang_typedef(mk_sl_fxp_inl_defd_name);


mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_base(mk_sl_fxp_inl_defd_pt const a, mk_sl_fxp_inl_defd_base_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_bool(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_bool_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_pchar(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_pchar_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_wchar(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_wchar_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_uchar(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_uchar_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_ushort(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_ushort_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_uint(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_uint_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_ulong(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_ulong_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_ullong(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_ullong_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_ulllong(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_ulllong_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_uintptr(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_uintptr_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_uintmax(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_uintmax_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_usize(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_usize_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_schar(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_schar_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_sshort(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_sshort_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_sint(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_sint_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_slong(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_slong_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_sllong(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_sllong_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_slllong(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_slllong_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_sintptr(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_sintptr_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_sintmax(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_sintmax_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_bi_ssize(mk_sl_fxp_inl_defd_pt const a, mk_lang_types_ssize_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_uint8(mk_sl_fxp_inl_defd_pt const a, mk_sl_cui_uint8_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_uint16(mk_sl_fxp_inl_defd_pt const a, mk_sl_cui_uint16_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_uint32(mk_sl_fxp_inl_defd_pt const a, mk_sl_cui_uint32_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_uint64(mk_sl_fxp_inl_defd_pt const a, mk_sl_cui_uint64_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_uint128(mk_sl_fxp_inl_defd_pt const a, mk_sl_cui_uint128_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_uint256(mk_sl_fxp_inl_defd_pt const a, mk_sl_cui_uint256_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_uint512(mk_sl_fxp_inl_defd_pt const a, mk_sl_cui_uint512_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_from_uint1024(mk_sl_fxp_inl_defd_pt const a, mk_sl_cui_uint1024_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_base(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_base_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_bool(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_bool_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_pchar(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_pchar_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_wchar(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_wchar_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_uchar(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_uchar_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_ushort(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_ushort_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_uint(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_uint_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_ulong(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_ulong_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_ullong(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_ullong_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_ulllong(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_ulllong_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_uintptr(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_uintptr_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_uintmax(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_uintmax_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_usize(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_usize_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_schar(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_schar_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_sshort(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_sshort_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_sint(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_sint_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_slong(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_slong_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_sllong(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_sllong_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_slllong(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_slllong_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_sintptr(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_sintptr_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_sintmax(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_sintmax_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_to_bi_ssize(mk_sl_fxp_inl_defd_pct const a, mk_lang_types_ssize_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_set_zero(mk_sl_fxp_inl_defd_pt const x) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_set_one(mk_sl_fxp_inl_defd_pt const x) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_set_two(mk_sl_fxp_inl_defd_pt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_bool_t mk_sl_fxp_inl_defd_is_zero(mk_sl_fxp_inl_defd_pct const x) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_bool_t mk_sl_fxp_inl_defd_is_one(mk_sl_fxp_inl_defd_pct const x) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_bool_t mk_sl_fxp_inl_defd_is_two(mk_sl_fxp_inl_defd_pct const x) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_bool_t mk_sl_fxp_inl_defd_eq(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_bool_t mk_sl_fxp_inl_defd_ne(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_bool_t mk_sl_fxp_inl_defd_lt(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_bool_t mk_sl_fxp_inl_defd_le(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_bool_t mk_sl_fxp_inl_defd_gt(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_bool_t mk_sl_fxp_inl_defd_ge(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_sint_t mk_sl_fxp_inl_defd_cmp(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_inc1(mk_sl_fxp_inl_defd_pt const x) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_dec1(mk_sl_fxp_inl_defd_pt const x) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_inc2(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_dec2(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_ulp_inc1(mk_sl_fxp_inl_defd_pt const x) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_ulp_dec1(mk_sl_fxp_inl_defd_pt const x) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_ulp_inc2(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_ulp_dec2(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pt const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_add3_wrap_cid_cod(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b, mk_sl_fxp_inl_defd_pt const c) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_add3_wrap_cid_coe(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b, mk_sl_fxp_inl_defd_pt const c, mk_lang_types_bool_pt const co) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_add3_wrap_cie_cod(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b, mk_lang_types_bool_t const ci, mk_sl_fxp_inl_defd_pt const c) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_add3_wrap_cie_coe(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b, mk_lang_types_bool_t const ci, mk_sl_fxp_inl_defd_pt const c, mk_lang_types_bool_pt const co) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_add2_wrap_cid_cod(mk_sl_fxp_inl_defd_pt const a, mk_sl_fxp_inl_defd_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_add2_wrap_cid_coe(mk_sl_fxp_inl_defd_pt const a, mk_sl_fxp_inl_defd_pct const b, mk_lang_types_bool_pt const co) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_add2_wrap_cie_cod(mk_sl_fxp_inl_defd_pt const a, mk_sl_fxp_inl_defd_pct const b, mk_lang_types_bool_t const ci) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_add2_wrap_cie_coe(mk_sl_fxp_inl_defd_pt const a, mk_sl_fxp_inl_defd_pct const b, mk_lang_types_bool_t const ci, mk_lang_types_bool_pt const co) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_sub3_wrap_cid_cod(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b, mk_sl_fxp_inl_defd_pt const c) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_sub3_wrap_cid_coe(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b, mk_sl_fxp_inl_defd_pt const c, mk_lang_types_bool_pt const co) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_sub3_wrap_cie_cod(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b, mk_lang_types_bool_t const ci, mk_sl_fxp_inl_defd_pt const c) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_sub3_wrap_cie_coe(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b, mk_lang_types_bool_t const ci, mk_sl_fxp_inl_defd_pt const c, mk_lang_types_bool_pt const co) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_sub2_wrap_cid_cod(mk_sl_fxp_inl_defd_pt const a, mk_sl_fxp_inl_defd_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_sub2_wrap_cid_coe(mk_sl_fxp_inl_defd_pt const a, mk_sl_fxp_inl_defd_pct const b, mk_lang_types_bool_pt const co) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_sub2_wrap_cie_cod(mk_sl_fxp_inl_defd_pt const a, mk_sl_fxp_inl_defd_pct const b, mk_lang_types_bool_t const ci) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_sub2_wrap_cie_coe(mk_sl_fxp_inl_defd_pt const a, mk_sl_fxp_inl_defd_pct const b, mk_lang_types_bool_t const ci, mk_lang_types_bool_pt const co) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_mul3_wrap_lo(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b, mk_sl_fxp_inl_defd_pt const c) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_mul2_wrap_lo(mk_sl_fxp_inl_defd_pt const a, mk_sl_fxp_inl_defd_pct const b) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_div3_wrap(mk_sl_fxp_inl_defd_pct const a, mk_sl_fxp_inl_defd_pct const b, mk_sl_fxp_inl_defd_pt const c) mk_lang_noexcept;
mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_void_t mk_sl_fxp_inl_defd_div2_wrap(mk_sl_fxp_inl_defd_pt const a, mk_sl_fxp_inl_defd_pct const b) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_sint_t mk_sl_fxp_inl_defd_to_string_n(mk_sl_fxp_inl_defd_pct const x, mk_lang_types_pchar_pt const str_buf, mk_lang_types_sint_t const str_len) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_sint_t mk_sl_fxp_inl_defd_to_string_w(mk_sl_fxp_inl_defd_pct const x, mk_lang_types_wchar_pt const str_buf, mk_lang_types_sint_t const str_len) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_fxp_inl_defd_forceinline mk_lang_constexpr mk_lang_noalias mk_lang_jumbo mk_lang_types_sint_t mk_sl_fxp_inl_defd_to_string_t(mk_sl_fxp_inl_defd_pct const x, mk_lang_tchar_pt const str_buf, mk_lang_types_sint_t const str_len) mk_lang_noexcept;


#include "mk_sl_fxp_inl_defu.h"
