include(`mk_lang_typedef.m')dnl
#include "mk_lang_concat.h"
#include "mk_lang_limits.h"
#include "mk_lang_types.h"
#include "mk_sl_dynamic_ring_copy.h"


#if(!( \
	(defined mk_sl_dynamic_ring_t_name) && \
	(defined mk_sl_dynamic_ring_t_element_type) && \
	(defined mk_sl_dynamic_ring_t_mallocatorg || defined mk_sl_dynamic_ring_t_mallocatorl) && \
	((defined mk_sl_dynamic_ring_t_copy_style && ((mk_sl_dynamic_ring_t_copy_style) == mk_sl_dynamic_ring_copy_use_bitblt || (mk_sl_dynamic_ring_t_copy_style) == mk_sl_dynamic_ring_copy_use_custom)) || !defined mk_sl_dynamic_ring_t_copy_style) && \
	(defined mk_sl_dynamic_ring_t_element_construct_void || !defined mk_sl_dynamic_ring_t_element_construct_void) && \
	(defined mk_sl_dynamic_ring_t_element_destruct || !defined mk_sl_dynamic_ring_t_element_destruct) && \
	(defined mk_sl_dynamic_ring_t_element_construct_copy || !defined mk_sl_dynamic_ring_t_element_construct_copy) && \
	(defined mk_sl_dynamic_ring_t_element_construct_move || !defined mk_sl_dynamic_ring_t_element_construct_move) && \
	(defined mk_sl_dynamic_ring_t_element_assign_copy || !defined mk_sl_dynamic_ring_t_element_assign_copy) && \
	(defined mk_sl_dynamic_ring_t_element_assign_move || !defined mk_sl_dynamic_ring_t_element_assign_move) && \
	(defined mk_sl_dynamic_ring_t_element_eq || !defined mk_sl_dynamic_ring_t_element_eq) && \
1))
#error xxxxxxxxxx
#endif


#if( \
	defined mk_sl_dynamic_ring_t_mallocatorg && \
	defined mk_sl_dynamic_ring_t_mallocatorl && \
1)
#error xxxxxxxxxx
#endif

#if( \
	defined mk_sl_dynamic_ring_t_element_construct_void || \
	defined mk_sl_dynamic_ring_t_element_destruct || \
0)
#if(!( \
	defined mk_sl_dynamic_ring_t_element_construct_void && \
	defined mk_sl_dynamic_ring_t_element_destruct && \
1))
#error xxxxxxxxxx
#endif
#endif

#if( \
	defined mk_sl_dynamic_ring_t_element_construct_copy || \
	defined mk_sl_dynamic_ring_t_element_assign_copy || \
0)
#if(!( \
	defined mk_sl_dynamic_ring_t_element_construct_copy && \
	defined mk_sl_dynamic_ring_t_element_assign_copy && \
1))
#error xxxxxxxxxx
#endif
#endif

#if( \
	defined mk_sl_dynamic_ring_t_element_construct_move || \
	defined mk_sl_dynamic_ring_t_element_assign_move || \
0)
#if(!( \
	defined mk_sl_dynamic_ring_t_element_construct_move && \
	defined mk_sl_dynamic_ring_t_element_assign_move && \
1))
#error xxxxxxxxxx
#endif
#endif


#define mk_sl_dynamic_ring_inl_defd_name mk_sl_dynamic_ring_t_name
#define mk_sl_dynamic_ring_inl_defd_element_type mk_sl_dynamic_ring_t_element_type

#if defined mk_sl_dynamic_ring_t_mallocatorg
#define mk_sl_dynamic_ring_inl_defd_mallocator mk_sl_dynamic_ring_t_mallocatorg
#define mk_sl_dynamic_ring_inl_defd_mallocator_is_global 1
#define mk_sl_dynamic_ring_inl_defd_mallocator_is_lokal 0
#elif defined mk_sl_dynamic_ring_t_mallocatorl
#define mk_sl_dynamic_ring_inl_defd_mallocator mk_sl_dynamic_ring_t_mallocatorl
#define mk_sl_dynamic_ring_inl_defd_mallocator_is_global 0
#define mk_sl_dynamic_ring_inl_defd_mallocator_is_lokal 1
#else
#error xxxxxxxxxx
#endif

#if defined mk_sl_dynamic_ring_t_copy_style
#define mk_sl_dynamic_ring_inl_defd_copy_style (mk_sl_dynamic_ring_t_copy_style)
#else
#if defined mk_sl_dynamic_ring_t_element_construct_copy && defined mk_sl_dynamic_ring_t_element_assign_copy
#define mk_sl_dynamic_ring_inl_defd_copy_style mk_sl_dynamic_ring_copy_use_custom
#else
#if defined mk_sl_dynamic_ring_t_element_construct_move && defined mk_sl_dynamic_ring_t_element_assign_move
#define mk_sl_dynamic_ring_inl_defd_copy_style mk_sl_dynamic_ring_copy_use_custom
#else
#define mk_sl_dynamic_ring_inl_defd_copy_style mk_sl_dynamic_ring_copy_use_bitblt
#endif
#endif
#endif

#if defined mk_sl_dynamic_ring_t_element_construct_void && defined mk_sl_dynamic_ring_t_element_destruct
#define mk_sl_dynamic_ring_inl_defd_element_construct_destruct_has 1
#define mk_sl_dynamic_ring_inl_defd_element_construct_void mk_sl_dynamic_ring_t_element_construct_void
#define mk_sl_dynamic_ring_inl_defd_element_destruct mk_sl_dynamic_ring_t_element_destruct
#else
#define mk_sl_dynamic_ring_inl_defd_element_construct_destruct_has 0
#endif

#if defined mk_sl_dynamic_ring_t_element_construct_copy && defined mk_sl_dynamic_ring_t_element_assign_copy
#define mk_sl_dynamic_ring_inl_defd_element_copy_has 1
#define mk_sl_dynamic_ring_inl_defd_element_copy_construct mk_sl_dynamic_ring_t_element_construct_copy
#define mk_sl_dynamic_ring_inl_defd_element_copy_assign mk_sl_dynamic_ring_t_element_assign_copy
#else
#define mk_sl_dynamic_ring_inl_defd_element_copy_has 0
#endif

#if defined mk_sl_dynamic_ring_t_element_construct_move && defined mk_sl_dynamic_ring_t_element_assign_move
#define mk_sl_dynamic_ring_inl_defd_element_move_has 1
#define mk_sl_dynamic_ring_inl_defd_element_move_construct mk_sl_dynamic_ring_t_element_construct_move
#define mk_sl_dynamic_ring_inl_defd_element_move_assign mk_sl_dynamic_ring_t_element_assign_move
#else
#define mk_sl_dynamic_ring_inl_defd_element_move_has 0
#endif

#if defined mk_sl_dynamic_ring_t_element_eq
#define mk_sl_dynamic_ring_inl_defd_element_eq_has 1
#define mk_sl_dynamic_ring_inl_defd_element_eq mk_sl_dynamic_ring_t_element_eq
#else
#define mk_sl_dynamic_ring_inl_defd_element_eq_has 0
#endif


#define mk_sl_dynamic_ring_inl_defd_element_prefix mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _element)
#define mk_sl_dynamic_ring_inl_defd_element_s mk_lang_concat(mk_sl_dynamic_ring_inl_defd_element_prefix, _s)
#define mk_sl_dynamic_ring_inl_defd_element_t mk_lang_concat(mk_sl_dynamic_ring_inl_defd_element_prefix, _t)
mm_per_typedef(`#define mk_sl_dynamic_ring_inl_defd_element_$1 mk_lang_concat(mk_sl_dynamic_ring_inl_defd_element_prefix, _$1)')`'dnl

#define mk_sl_dynamic_ring_inl_defd_mallocator_pt mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _pt)
#if mk_sl_dynamic_ring_inl_defd_mallocator_is_global
#define mk_sl_dynamic_ring_inl_defd_mallocator_init mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _init)
#define mk_sl_dynamic_ring_inl_defd_mallocator_deinit mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _deinit)
#define mk_sl_dynamic_ring_inl_defd_mallocator_allocate(a, b, c) mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _allocate)((b), (c)); ((mk_lang_types_void_t)((a)))
#define mk_sl_dynamic_ring_inl_defd_mallocator_deallocate(a, b, c) mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _deallocate)((b), (c)); ((mk_lang_types_void_t)((a)))
#define mk_sl_dynamic_ring_inl_defd_mallocator_reallocate(a, b, c, d, e) mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _reallocate)((b), (c), (d), (e)); ((mk_lang_types_void_t)((a)))
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_blocks_allocated mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_blocks_allocated)
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_blocks_dealocated mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_blocks_dealocated)
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_blocks_peak mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_blocks_peak)
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_blocks_live mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_blocks_live)
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_bytes_allocated mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_bytes_allocated)
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_bytes_dealocated mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_bytes_dealocated)
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_bytes_peak mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_bytes_peak)
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_bytes_live mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_bytes_live)
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_all mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_all)
#else
#define mk_sl_dynamic_ring_inl_defd_mallocator_init mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _init)
#define mk_sl_dynamic_ring_inl_defd_mallocator_deinit mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _deinit)
#define mk_sl_dynamic_ring_inl_defd_mallocator_allocate(a, b, c) mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _allocate)((a)->m_mallocator, (b), (c))
#define mk_sl_dynamic_ring_inl_defd_mallocator_deallocate(a, b, c) mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _deallocate)((a)->m_mallocator, (b), (c))
#define mk_sl_dynamic_ring_inl_defd_mallocator_reallocate(a, b, c, d, e) mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _reallocate)((a)->m_mallocator, (b), (c), (d), (e))
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_blocks_allocated mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_blocks_allocated)
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_blocks_dealocated mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_blocks_dealocated)
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_blocks_peak mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_blocks_peak)
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_blocks_live mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_blocks_live)
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_bytes_allocated mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_bytes_allocated)
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_bytes_dealocated mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_bytes_dealocated)
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_bytes_peak mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_bytes_peak)
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_bytes_live mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_bytes_live)
#define mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_all mk_lang_concat(mk_sl_dynamic_ring_inl_defd_mallocator, _statistics_get_all)
#endif

#define mk_sl_dynamic_ring_inl_defd_s mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _s)
#define mk_sl_dynamic_ring_inl_defd_t mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _t)
mm_per_typedef(`#define mk_sl_dynamic_ring_inl_defd_$1 mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _$1)')`'dnl

#if mk_sl_dynamic_ring_inl_defd_mallocator_is_global
#define mk_sl_dynamic_ring_inl_defd_mallocator_member
#define mk_sl_dynamic_ring_inl_defd_mallocator_param
	#define mk_sl_dynamic_ring_inl_defd_mallocator_get_param
#define mk_sl_dynamic_ring_inl_defd_mallocator_assert()
#define mk_sl_dynamic_ring_inl_defd_mallocator_assign(x)
#define mk_sl_dynamic_ring_inl_defd_mallocator_access(x)
#else
#define mk_sl_dynamic_ring_inl_defd_mallocator_member mk_sl_dynamic_ring_inl_defd_mallocator_pt m_mallocator;
#define mk_sl_dynamic_ring_inl_defd_mallocator_param , mk_sl_dynamic_ring_inl_defd_mallocator_pt const mallocator
#define mk_sl_dynamic_ring_inl_defd_mallocator_get_param mallocator
#define mk_sl_dynamic_ring_inl_defd_mallocator_assert() mk_lang_assert(mallocator)
#define mk_sl_dynamic_ring_inl_defd_mallocator_assign(x) (x)->m_mallocator = mallocator
#define mk_sl_dynamic_ring_inl_defd_mallocator_access(x) (x)->m_mallocator
#endif





#define mk_sl_dynamic_ring_inl_defd_prro_verify_invariants mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prro_verify_invariants)

#define mk_sl_dynamic_ring_inl_defd_prrw_element_construct_copy_single mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_element_construct_copy_single)
#define mk_sl_dynamic_ring_inl_defd_prrw_element_construct_move_single mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_element_construct_move_single)
#define mk_sl_dynamic_ring_inl_defd_prrw_element_assign_move_single mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_element_assign_move_single)
#define mk_sl_dynamic_ring_inl_defd_prrw_element_destroy_single mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_element_destroy_single)

#define mk_sl_dynamic_ring_inl_defd_prrw_elements_construct_copy_many mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_elements_construct_copy_many)
#define mk_sl_dynamic_ring_inl_defd_prrw_elements_construct_move_many mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_elements_construct_move_many)
#define mk_sl_dynamic_ring_inl_defd_prrw_elements_assign_move_many mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_elements_assign_move_many)
#define mk_sl_dynamic_ring_inl_defd_prrw_elements_destroy_many mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_elements_destroy_many)

#define mk_sl_dynamic_ring_inl_defd_prro_get_capacity mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prro_get_capacity)
#define mk_sl_dynamic_ring_inl_defd_prro_get_size mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prro_get_size)
#define mk_sl_dynamic_ring_inl_defd_prro_get_free_size mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prro_get_free_size)
#define mk_sl_dynamic_ring_inl_defd_prro_is_empty mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prro_is_empty)
#define mk_sl_dynamic_ring_inl_defd_prro_is_full mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prro_is_full)
#define mk_sl_dynamic_ring_inl_defd_prro_get_front mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prro_get_front)
#define mk_sl_dynamic_ring_inl_defd_prro_get_size_a mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prro_get_size_a)
#define mk_sl_dynamic_ring_inl_defd_prro_get_data_a mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prro_get_data_a)
#define mk_sl_dynamic_ring_inl_defd_prro_get_size_b mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prro_get_size_b)
#define mk_sl_dynamic_ring_inl_defd_prro_get_data_b mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prro_get_data_b)
#define mk_sl_dynamic_ring_inl_defd_prro_get_free_size_a mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prro_get_free_size_a)
#define mk_sl_dynamic_ring_inl_defd_prro_get_free_data_a mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prro_get_free_data_a)
#define mk_sl_dynamic_ring_inl_defd_prro_get_free_size_b mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prro_get_free_size_b)
#define mk_sl_dynamic_ring_inl_defd_prro_get_free_data_b mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prro_get_free_data_b)

#define mk_sl_dynamic_ring_inl_defd_prrw_get_capacity mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_get_capacity)
#define mk_sl_dynamic_ring_inl_defd_prrw_get_size mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_get_size)
#define mk_sl_dynamic_ring_inl_defd_prrw_get_free_size mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_get_free_size)
#define mk_sl_dynamic_ring_inl_defd_prrw_is_empty mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_is_empty)
#define mk_sl_dynamic_ring_inl_defd_prrw_is_full mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_is_full)
#define mk_sl_dynamic_ring_inl_defd_prrw_get_front mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_get_front)
#define mk_sl_dynamic_ring_inl_defd_prrw_get_size_a mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_get_size_a)
#define mk_sl_dynamic_ring_inl_defd_prrw_get_data_a mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_get_data_a)
#define mk_sl_dynamic_ring_inl_defd_prrw_get_size_b mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_get_size_b)
#define mk_sl_dynamic_ring_inl_defd_prrw_get_data_b mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_get_data_b)
#define mk_sl_dynamic_ring_inl_defd_prrw_get_free_size_a mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_get_free_size_a)
#define mk_sl_dynamic_ring_inl_defd_prrw_get_free_data_a mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_get_free_data_a)
#define mk_sl_dynamic_ring_inl_defd_prrw_get_free_size_b mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_get_free_size_b)
#define mk_sl_dynamic_ring_inl_defd_prrw_get_free_data_b mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_get_free_data_b)

#define mk_sl_dynamic_ring_inl_defd_prrw_construct mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_construct)
#define mk_sl_dynamic_ring_inl_defd_prrw_construct_copy mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_construct_copy)
#define mk_sl_dynamic_ring_inl_defd_prrw_construct_move mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_construct_move)
#define mk_sl_dynamic_ring_inl_defd_prrw_clear mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_clear)
#define mk_sl_dynamic_ring_inl_defd_prrw_consolidate mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_consolidate)
#define mk_sl_dynamic_ring_inl_defd_prrw_push_back_void mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_push_back_void)
#define mk_sl_dynamic_ring_inl_defd_prrw_destroy mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_destroy)
#define mk_sl_dynamic_ring_inl_defd_prrw_reserve_at_least mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_reserve_at_least)
#define mk_sl_dynamic_ring_inl_defd_prrw_reserve_additional mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_reserve_additional)
#define mk_sl_dynamic_ring_inl_defd_prrw_push_back_copy_many mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_push_back_copy_many)
#define mk_sl_dynamic_ring_inl_defd_prrw_push_back_copy_single mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_push_back_copy_single)
#define mk_sl_dynamic_ring_inl_defd_prrw_push_back_move_many mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_push_back_move_many)
#define mk_sl_dynamic_ring_inl_defd_prrw_push_back_move_single mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_push_back_move_single)
#define mk_sl_dynamic_ring_inl_defd_prrw_push_front_copy_many mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_push_front_copy_many)
#define mk_sl_dynamic_ring_inl_defd_prrw_push_front_copy_single mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_push_front_copy_single)
#define mk_sl_dynamic_ring_inl_defd_prrw_push_front_move_many mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_push_front_move_many)
#define mk_sl_dynamic_ring_inl_defd_prrw_push_front_move_single mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_push_front_move_single)
#define mk_sl_dynamic_ring_inl_defd_prrw_assign_copy mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_assign_copy)
#define mk_sl_dynamic_ring_inl_defd_prrw_assign_move mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_assign_move)
#define mk_sl_dynamic_ring_inl_defd_prrw_pop_back_many mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_pop_back_many)
#define mk_sl_dynamic_ring_inl_defd_prrw_pop_back_single mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_pop_back_single)
#define mk_sl_dynamic_ring_inl_defd_prrw_pop_front_many mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_pop_front_many)
#define mk_sl_dynamic_ring_inl_defd_prrw_pop_front_single mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _prrw_pop_front_single)





#define mk_sl_dynamic_ring_inl_defd_max_capacity_d ((mk_lang_types_usize_t)((((mk_lang_types_usize_t)(mk_lang_limits_usize_max)) / ((mk_lang_types_usize_t)(sizeof(mk_sl_dynamic_ring_inl_defd_element_t))))))
#define mk_sl_dynamic_ring_inl_defd_max_capacity_e mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _max_capacity_e)
#define mk_sl_dynamic_ring_inl_defd_max_capacity_t mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _max_capacity_t)
#define mk_sl_dynamic_ring_inl_defd_max_capacity_v mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _max_capacity_v)

#define mk_sl_dynamic_ring_inl_defd_ro_get_capacity mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _ro_get_capacity)
#define mk_sl_dynamic_ring_inl_defd_ro_get_size mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _ro_get_size)
#define mk_sl_dynamic_ring_inl_defd_ro_get_free_size mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _ro_get_free_size)
#define mk_sl_dynamic_ring_inl_defd_ro_is_empty mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _ro_is_empty)
#define mk_sl_dynamic_ring_inl_defd_ro_is_full mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _ro_is_full)
#define mk_sl_dynamic_ring_inl_defd_ro_get_front mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _ro_get_front)
#define mk_sl_dynamic_ring_inl_defd_ro_get_size_a mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _ro_get_size_a)
#define mk_sl_dynamic_ring_inl_defd_ro_get_data_a mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _ro_get_data_a)
#define mk_sl_dynamic_ring_inl_defd_ro_get_size_b mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _ro_get_size_b)
#define mk_sl_dynamic_ring_inl_defd_ro_get_data_b mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _ro_get_data_b)
#define mk_sl_dynamic_ring_inl_defd_ro_get_free_size_a mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _ro_get_free_size_a)
#define mk_sl_dynamic_ring_inl_defd_ro_get_free_data_a mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _ro_get_free_data_a)
#define mk_sl_dynamic_ring_inl_defd_ro_get_free_size_b mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _ro_get_free_size_b)
#define mk_sl_dynamic_ring_inl_defd_ro_get_free_data_b mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _ro_get_free_data_b)

#define mk_sl_dynamic_ring_inl_defd_rw_get_capacity mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_get_capacity)
#define mk_sl_dynamic_ring_inl_defd_rw_get_size mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_get_size)
#define mk_sl_dynamic_ring_inl_defd_rw_get_free_size mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_get_free_size)
#define mk_sl_dynamic_ring_inl_defd_rw_is_empty mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_is_empty)
#define mk_sl_dynamic_ring_inl_defd_rw_is_full mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_is_full)
#define mk_sl_dynamic_ring_inl_defd_rw_get_front mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_get_front)
#define mk_sl_dynamic_ring_inl_defd_rw_get_size_a mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_get_size_a)
#define mk_sl_dynamic_ring_inl_defd_rw_get_data_a mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_get_data_a)
#define mk_sl_dynamic_ring_inl_defd_rw_get_size_b mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_get_size_b)
#define mk_sl_dynamic_ring_inl_defd_rw_get_data_b mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_get_data_b)
#define mk_sl_dynamic_ring_inl_defd_rw_get_free_size_a mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_get_free_size_a)
#define mk_sl_dynamic_ring_inl_defd_rw_get_free_data_a mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_get_free_data_a)
#define mk_sl_dynamic_ring_inl_defd_rw_get_free_size_b mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_get_free_size_b)
#define mk_sl_dynamic_ring_inl_defd_rw_get_free_data_b mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_get_free_data_b)

#define mk_sl_dynamic_ring_inl_defd_rw_construct mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_construct)
#define mk_sl_dynamic_ring_inl_defd_rw_construct_copy mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_construct_copy)
#define mk_sl_dynamic_ring_inl_defd_rw_construct_move mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_construct_move)
#define mk_sl_dynamic_ring_inl_defd_rw_destroy mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_destroy)
#define mk_sl_dynamic_ring_inl_defd_rw_assign_copy mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_assign_copy)
#define mk_sl_dynamic_ring_inl_defd_rw_assign_move mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_assign_move)
#define mk_sl_dynamic_ring_inl_defd_rw_reserve_at_least mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_reserve_at_least)
#define mk_sl_dynamic_ring_inl_defd_rw_reserve_additional mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_reserve_additional)
#define mk_sl_dynamic_ring_inl_defd_rw_clear mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_clear)
#define mk_sl_dynamic_ring_inl_defd_rw_consolidate mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_consolidate)
#define mk_sl_dynamic_ring_inl_defd_rw_push_back_void mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_push_back_void)
#define mk_sl_dynamic_ring_inl_defd_rw_push_back_move_many mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_push_back_move_many)
#define mk_sl_dynamic_ring_inl_defd_rw_push_back_copy_many mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_push_back_copy_many)
#define mk_sl_dynamic_ring_inl_defd_rw_push_back_move_single mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_push_back_move_single)
#define mk_sl_dynamic_ring_inl_defd_rw_push_back_copy_single mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_push_back_copy_single)
#define mk_sl_dynamic_ring_inl_defd_rw_push_front_move_many mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_push_front_move_many)
#define mk_sl_dynamic_ring_inl_defd_rw_push_front_copy_many mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_push_front_copy_many)
#define mk_sl_dynamic_ring_inl_defd_rw_push_front_move_single mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_push_front_move_single)
#define mk_sl_dynamic_ring_inl_defd_rw_push_front_copy_single mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_push_front_copy_single)
#define mk_sl_dynamic_ring_inl_defd_rw_pop_back_many mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_pop_back_many)
#define mk_sl_dynamic_ring_inl_defd_rw_pop_back_single mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_pop_back_single)
#define mk_sl_dynamic_ring_inl_defd_rw_pop_front_many mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_pop_front_many)
#define mk_sl_dynamic_ring_inl_defd_rw_pop_front_single mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_pop_front_single)
#define mk_sl_dynamic_ring_inl_defd_rw_erase_at mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_erase_at)
#define mk_sl_dynamic_ring_inl_defd_rw_erase_element mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_erase_element)
#define mk_sl_dynamic_ring_inl_defd_rw_erase_value mk_lang_concat(mk_sl_dynamic_ring_inl_defd_name, _rw_erase_value)
