












#undef mk_sl_tree_wavl_inl_defd_name
#undef mk_sl_tree_wavl_inl_defd_element_type
#undef mk_sl_tree_wavl_inl_defd_elements_compare
#undef mk_sl_tree_wavl_inl_defd_mallocatorg_name


#undef mk_sl_tree_wavl_inl_defd_element_t
#undef mk_sl_tree_wavl_inl_defd_element_ct
#undef mk_sl_tree_wavl_inl_defd_element_pt
#undef mk_sl_tree_wavl_inl_defd_element_pct
#undef mk_sl_tree_wavl_inl_defd_element_cpt
#undef mk_sl_tree_wavl_inl_defd_element_ppt
#undef mk_sl_tree_wavl_inl_defd_element_pcpt
#undef mk_sl_tree_wavl_inl_defd_element_cpct
#undef mk_sl_tree_wavl_inl_defd_element_ppct
#undef mk_sl_tree_wavl_inl_defd_element_pcpct

#undef mk_sl_tree_wavl_inl_defd_elements_compare_fn

#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_init
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_deinit
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_allocate
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_deallocate
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_reallocate
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_allocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_deallocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_live
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_peak
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_allocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_deallocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_live
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_peak

#undef mk_sl_tree_wavl_inl_defd_mallocatorg_init
#undef mk_sl_tree_wavl_inl_defd_mallocatorg_deinit
#undef mk_sl_tree_wavl_inl_defd_mallocatorg_allocate
#undef mk_sl_tree_wavl_inl_defd_mallocatorg_deallocate
#undef mk_sl_tree_wavl_inl_defd_mallocatorg_reallocate
#undef mk_sl_tree_wavl_inl_defd_mallocatorg_statistics_get_bytes_allocated
#undef mk_sl_tree_wavl_inl_defd_mallocatorg_statistics_get_bytes_deallocated
#undef mk_sl_tree_wavl_inl_defd_mallocatorg_statistics_get_bytes_live
#undef mk_sl_tree_wavl_inl_defd_mallocatorg_statistics_get_bytes_peak
#undef mk_sl_tree_wavl_inl_defd_mallocatorg_statistics_get_blocks_allocated
#undef mk_sl_tree_wavl_inl_defd_mallocatorg_statistics_get_blocks_deallocated
#undef mk_sl_tree_wavl_inl_defd_mallocatorg_statistics_get_blocks_live
#undef mk_sl_tree_wavl_inl_defd_mallocatorg_statistics_get_blocks_peak

#undef mk_sl_tree_wavl_inl_defd_node_s
#undef mk_sl_tree_wavl_inl_defd_node_t
#undef mk_sl_tree_wavl_inl_defd_node_ct
#undef mk_sl_tree_wavl_inl_defd_node_pt
#undef mk_sl_tree_wavl_inl_defd_node_pct
#undef mk_sl_tree_wavl_inl_defd_node_cpt
#undef mk_sl_tree_wavl_inl_defd_node_ppt
#undef mk_sl_tree_wavl_inl_defd_node_pcpt
#undef mk_sl_tree_wavl_inl_defd_node_cpct
#undef mk_sl_tree_wavl_inl_defd_node_ppct
#undef mk_sl_tree_wavl_inl_defd_node_pcpct

#undef mk_sl_tree_wavl_inl_defd_s
#undef mk_sl_tree_wavl_inl_defd_t
#undef mk_sl_tree_wavl_inl_defd_ct
#undef mk_sl_tree_wavl_inl_defd_pt
#undef mk_sl_tree_wavl_inl_defd_pct
#undef mk_sl_tree_wavl_inl_defd_cpt
#undef mk_sl_tree_wavl_inl_defd_ppt
#undef mk_sl_tree_wavl_inl_defd_pcpt
#undef mk_sl_tree_wavl_inl_defd_cpct
#undef mk_sl_tree_wavl_inl_defd_ppct
#undef mk_sl_tree_wavl_inl_defd_pcpct

#undef mk_sl_tree_wavl_inl_defd_rw_construct
#undef mk_sl_tree_wavl_inl_defd_rw_destruct
#undef mk_sl_tree_wavl_inl_defd_rw_insert_node
#undef mk_sl_tree_wavl_inl_defd_rw_remove_node
#undef mk_sl_tree_wavl_inl_defd_rw_insert_element
#undef mk_sl_tree_wavl_inl_defd_ro_find
#undef mk_sl_tree_wavl_inl_defd_rw_decrement_node

#undef mk_sl_tree_wavl_inl_defd_ro_node_get_element
#undef mk_sl_tree_wavl_inl_defd_rw_node_get_element

#undef mk_sl_tree_wavl_inl_defd_visitor_callback_dummy
#undef mk_sl_tree_wavl_inl_defd_visitor_callback_t
#undef mk_sl_tree_wavl_inl_defd_visitor_context_pt
#undef mk_sl_tree_wavl_inl_defd_prro_visit
#undef mk_sl_tree_wavl_inl_defd_rule_tree_s
#undef mk_sl_tree_wavl_inl_defd_rule_tree_t
#undef mk_sl_tree_wavl_inl_defd_rule_tree_pt
#undef mk_sl_tree_wavl_inl_defd_prro_rule_visit_tree
#undef mk_sl_tree_wavl_inl_defd_prro_rule_check_tree
#undef mk_sl_tree_wavl_inl_defd_prro_rule_visit_wavl
#undef mk_sl_tree_wavl_inl_defd_prro_rule_check_wavl
#undef mk_sl_tree_wavl_inl_defd_prro_validate

#undef mk_sl_tree_wavl_inl_defd_prrw_find_smallest
#undef mk_sl_tree_wavl_inl_defd_prrw_rotate_left_single_at
#undef mk_sl_tree_wavl_inl_defd_prrw_rotate_right_single_at
#undef mk_sl_tree_wavl_inl_defd_prrw_rotate_left_double_at
#undef mk_sl_tree_wavl_inl_defd_prrw_rotate_right_double_at
#undef mk_sl_tree_wavl_inl_defd_prrw_rebalance_insert
#undef mk_sl_tree_wavl_inl_defd_prrw_swap_in
#undef mk_sl_tree_wavl_inl_defd_prrw_rebalance_remove_3child
#undef mk_sl_tree_wavl_inl_defd_prrw_rebalance_remove_2_2_leaf

#undef mk_sl_tree_wavl_inl_defd_prro_node_get_parent
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_left
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_right
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_rank
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_root
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_leaf
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_unary
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_binary
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_internal
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_external
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_rank_difference2
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_rank_difference
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_ichild
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_ijnode
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_size
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_height

#undef mk_sl_tree_wavl_inl_defd_prrw_node_get_parent
#undef mk_sl_tree_wavl_inl_defd_prrw_node_get_left
#undef mk_sl_tree_wavl_inl_defd_prrw_node_get_right
#undef mk_sl_tree_wavl_inl_defd_prrw_node_promote
#undef mk_sl_tree_wavl_inl_defd_prrw_node_demote
#undef mk_sl_tree_wavl_inl_defd_prrw_node_inc
#undef mk_sl_tree_wavl_inl_defd_prrw_node_init
#undef mk_sl_tree_wavl_inl_defd_prrw_node_alloc
#undef mk_sl_tree_wavl_inl_defd_prrw_node_dealloc
