#include "mk_lang_concat.h"


#if(!( \
	(defined mk_sl_tree_wavl_t_name) && \
	(defined mk_sl_tree_wavl_t_element_type) && \
	(defined mk_sl_tree_wavl_t_elements_compare) && \
	(defined mk_sl_tree_wavl_t_mallocatorg_name) && \
1))
#error xxxxxxxxxx
#endif


#define mk_sl_tree_wavl_inl_defd_name mk_sl_tree_wavl_t_name
#define mk_sl_tree_wavl_inl_defd_element_type mk_sl_tree_wavl_t_element_type
#define mk_sl_tree_wavl_inl_defd_elements_compare mk_sl_tree_wavl_t_elements_compare
#define mk_sl_tree_wavl_inl_defd_mallocatorg_name mk_sl_tree_wavl_t_mallocatorg_name


#define mk_sl_tree_wavl_inl_defd_element_t mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _element_t)
#define mk_sl_tree_wavl_inl_defd_element_ct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _element_ct)
#define mk_sl_tree_wavl_inl_defd_element_pt mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _element_pt)
#define mk_sl_tree_wavl_inl_defd_element_pct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _element_pct)
#define mk_sl_tree_wavl_inl_defd_element_cpt mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _element_cpt)
#define mk_sl_tree_wavl_inl_defd_element_ppt mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _element_ppt)
#define mk_sl_tree_wavl_inl_defd_element_pcpt mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _element_pcpt)
#define mk_sl_tree_wavl_inl_defd_element_cpct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _element_cpct)
#define mk_sl_tree_wavl_inl_defd_element_ppct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _element_ppct)
#define mk_sl_tree_wavl_inl_defd_element_pcpct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _element_pcpct)

#define mk_sl_tree_wavl_inl_defd_elements_compare_fn mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _elements_compare_fn)

#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_init mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocatorg_name, _init)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_deinit mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocatorg_name, _deinit)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_allocate mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocatorg_name, _allocate)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_deallocate mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocatorg_name, _deallocate)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_reallocate mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocatorg_name, _reallocate)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_allocated mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocatorg_name, _statistics_get_bytes_allocated)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_deallocated mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocatorg_name, _statistics_get_bytes_deallocated)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_live mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocatorg_name, _statistics_get_bytes_live)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_peak mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocatorg_name, _statistics_get_bytes_peak)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_allocated mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocatorg_name, _statistics_get_blocks_allocated)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_deallocated mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocatorg_name, _statistics_get_blocks_deallocated)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_live mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocatorg_name, _statistics_get_blocks_live)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_peak mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocatorg_name, _statistics_get_blocks_peak)

#define mk_sl_tree_wavl_inl_defd_mallocatorg_init mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _mallocatorg_init)
#define mk_sl_tree_wavl_inl_defd_mallocatorg_deinit mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _mallocatorg_deinit)
#define mk_sl_tree_wavl_inl_defd_mallocatorg_allocate mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _mallocatorg_allocate)
#define mk_sl_tree_wavl_inl_defd_mallocatorg_deallocate mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _mallocatorg_deallocate)
#define mk_sl_tree_wavl_inl_defd_mallocatorg_reallocate mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _mallocatorg_reallocate)
#define mk_sl_tree_wavl_inl_defd_mallocatorg_statistics_get_bytes_allocated mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _mallocatorg_statistics_get_bytes_allocated)
#define mk_sl_tree_wavl_inl_defd_mallocatorg_statistics_get_bytes_deallocated mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _mallocatorg_statistics_get_bytes_deallocated)
#define mk_sl_tree_wavl_inl_defd_mallocatorg_statistics_get_bytes_live mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _mallocatorg_statistics_get_bytes_live)
#define mk_sl_tree_wavl_inl_defd_mallocatorg_statistics_get_bytes_peak mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _mallocatorg_statistics_get_bytes_peak)
#define mk_sl_tree_wavl_inl_defd_mallocatorg_statistics_get_blocks_allocated mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _mallocatorg_statistics_get_blocks_allocated)
#define mk_sl_tree_wavl_inl_defd_mallocatorg_statistics_get_blocks_deallocated mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _mallocatorg_statistics_get_blocks_deallocated)
#define mk_sl_tree_wavl_inl_defd_mallocatorg_statistics_get_blocks_live mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _mallocatorg_statistics_get_blocks_live)
#define mk_sl_tree_wavl_inl_defd_mallocatorg_statistics_get_blocks_peak mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _mallocatorg_statistics_get_blocks_peak)

#define mk_sl_tree_wavl_inl_defd_node_s mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _node_s)
#define mk_sl_tree_wavl_inl_defd_node_t mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _node_t)
#define mk_sl_tree_wavl_inl_defd_node_ct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _node_ct)
#define mk_sl_tree_wavl_inl_defd_node_pt mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _node_pt)
#define mk_sl_tree_wavl_inl_defd_node_pct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _node_pct)
#define mk_sl_tree_wavl_inl_defd_node_cpt mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _node_cpt)
#define mk_sl_tree_wavl_inl_defd_node_ppt mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _node_ppt)
#define mk_sl_tree_wavl_inl_defd_node_pcpt mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _node_pcpt)
#define mk_sl_tree_wavl_inl_defd_node_cpct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _node_cpct)
#define mk_sl_tree_wavl_inl_defd_node_ppct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _node_ppct)
#define mk_sl_tree_wavl_inl_defd_node_pcpct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _node_pcpct)

#define mk_sl_tree_wavl_inl_defd_s mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _s)
#define mk_sl_tree_wavl_inl_defd_t mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _t)
#define mk_sl_tree_wavl_inl_defd_ct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _ct)
#define mk_sl_tree_wavl_inl_defd_pt mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _pt)
#define mk_sl_tree_wavl_inl_defd_pct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _pct)
#define mk_sl_tree_wavl_inl_defd_cpt mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _cpt)
#define mk_sl_tree_wavl_inl_defd_ppt mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _ppt)
#define mk_sl_tree_wavl_inl_defd_pcpt mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _pcpt)
#define mk_sl_tree_wavl_inl_defd_cpct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _cpct)
#define mk_sl_tree_wavl_inl_defd_ppct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _ppct)
#define mk_sl_tree_wavl_inl_defd_pcpct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _pcpct)

#define mk_sl_tree_wavl_inl_defd_rw_construct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rw_construct)
#define mk_sl_tree_wavl_inl_defd_rw_destruct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rw_destruct)
#define mk_sl_tree_wavl_inl_defd_rw_insert_node mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rw_insert_node)
#define mk_sl_tree_wavl_inl_defd_rw_remove_node mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rw_remove_node)
#define mk_sl_tree_wavl_inl_defd_rw_insert_element mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rw_insert_element)
#define mk_sl_tree_wavl_inl_defd_ro_find mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _ro_find)
#define mk_sl_tree_wavl_inl_defd_rw_decrement_node mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rw_decrement_node)

#define mk_sl_tree_wavl_inl_defd_ro_node_get_element mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _ro_node_get_element)
#define mk_sl_tree_wavl_inl_defd_rw_node_get_element mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rw_node_get_element)

#define mk_sl_tree_wavl_inl_defd_visitor_callback_dummy mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _visitor_callback_dummy)
#define mk_sl_tree_wavl_inl_defd_visitor_callback_t mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _visitor_callback_t)
#define mk_sl_tree_wavl_inl_defd_visitor_context_pt mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _visitor_context_pt)
#define mk_sl_tree_wavl_inl_defd_prro_visit mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_visit)
#define mk_sl_tree_wavl_inl_defd_rule_tree_s mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rule_tree_s)
#define mk_sl_tree_wavl_inl_defd_rule_tree_t mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rule_tree_t)
#define mk_sl_tree_wavl_inl_defd_rule_tree_pt mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rule_tree_pt)
#define mk_sl_tree_wavl_inl_defd_prro_rule_visit_tree mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_rule_visit_tree)
#define mk_sl_tree_wavl_inl_defd_prro_rule_check_tree mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_rule_check_tree)
#define mk_sl_tree_wavl_inl_defd_prro_rule_visit_wavl mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_rule_visit_wavl)
#define mk_sl_tree_wavl_inl_defd_prro_rule_check_wavl mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_rule_check_wavl)
#define mk_sl_tree_wavl_inl_defd_prro_validate mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_validate)

#define mk_sl_tree_wavl_inl_defd_prrw_find_smallest mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_find_smallest)
#define mk_sl_tree_wavl_inl_defd_prrw_rotate_left_single_at mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_rotate_left_single_at)
#define mk_sl_tree_wavl_inl_defd_prrw_rotate_right_single_at mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_rotate_right_single_at)
#define mk_sl_tree_wavl_inl_defd_prrw_rotate_left_double_at mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_rotate_left_double_at)
#define mk_sl_tree_wavl_inl_defd_prrw_rotate_right_double_at mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_rotate_right_double_at)
#define mk_sl_tree_wavl_inl_defd_prrw_rebalance_insert mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_rebalance_insert)
#define mk_sl_tree_wavl_inl_defd_prrw_swap_in mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_swap_in)
#define mk_sl_tree_wavl_inl_defd_prrw_rebalance_remove_3child mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_rebalance_remove_3child)
#define mk_sl_tree_wavl_inl_defd_prrw_rebalance_remove_2_2_leaf mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_rebalance_delete_2_2_leaf)

#define mk_sl_tree_wavl_inl_defd_prro_node_get_parent mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_get_parent)
#define mk_sl_tree_wavl_inl_defd_prro_node_get_left mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_get_left)
#define mk_sl_tree_wavl_inl_defd_prro_node_get_right mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_get_right)
#define mk_sl_tree_wavl_inl_defd_prro_node_get_rank mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_get_rank)
#define mk_sl_tree_wavl_inl_defd_prro_node_is_root mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_is_root)
#define mk_sl_tree_wavl_inl_defd_prro_node_is_leaf mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_is_leaf)
#define mk_sl_tree_wavl_inl_defd_prro_node_is_unary mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_is_unary)
#define mk_sl_tree_wavl_inl_defd_prro_node_is_binary mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_is_binary)
#define mk_sl_tree_wavl_inl_defd_prro_node_is_internal mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_is_internal)
#define mk_sl_tree_wavl_inl_defd_prro_node_is_external mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_is_external)
#define mk_sl_tree_wavl_inl_defd_prro_node_get_rank_difference2 mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_get_rank_difference2)
#define mk_sl_tree_wavl_inl_defd_prro_node_get_rank_difference mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_get_rank_difference)
#define mk_sl_tree_wavl_inl_defd_prro_node_is_ichild mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_is_ichild)
#define mk_sl_tree_wavl_inl_defd_prro_node_is_ijnode mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_is_ijnode)
#define mk_sl_tree_wavl_inl_defd_prro_node_get_size mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_get_size)
#define mk_sl_tree_wavl_inl_defd_prro_node_get_height mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_get_height)

#define mk_sl_tree_wavl_inl_defd_prrw_node_get_parent mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_get_parent)
#define mk_sl_tree_wavl_inl_defd_prrw_node_get_left mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_get_left)
#define mk_sl_tree_wavl_inl_defd_prrw_node_get_right mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_get_right)
#define mk_sl_tree_wavl_inl_defd_prrw_node_promote mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_promote)
#define mk_sl_tree_wavl_inl_defd_prrw_node_demote mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_demote)
#define mk_sl_tree_wavl_inl_defd_prrw_node_inc mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_inc)
#define mk_sl_tree_wavl_inl_defd_prrw_node_init mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_init)
#define mk_sl_tree_wavl_inl_defd_prrw_node_alloc mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_alloc)
#define mk_sl_tree_wavl_inl_defd_prrw_node_dealloc mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_dealloc)
