#ifndef mk_include_guard_mk_sl_mallocator_c
#define mk_include_guard_mk_sl_mallocator_c
#include "mk_sl_mallocator.h"

#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_platform.h"
#include "mk_lang_static_param.h"
#include "mk_lang_types.h"
#include "mk_lang_version.h"


#if mk_sl_mallocator_constexpr_have
#include "mk_sl_mallocator_arena.h"
#define mk_sl_mallocator_impl_init mk_sl_mallocator_arena_init
#define mk_sl_mallocator_impl_deinit mk_sl_mallocator_arena_deinit
#define mk_sl_mallocator_impl_allocate mk_sl_mallocator_arena_allocate
#define mk_sl_mallocator_impl_deallocate mk_sl_mallocator_arena_deallocate
#define mk_sl_mallocator_impl_reallocate mk_sl_mallocator_arena_reallocate
#define mk_sl_mallocator_impl_statistics_get_blocks_allocated mk_sl_mallocator_arena_statistics_get_blocks_allocated
#define mk_sl_mallocator_impl_statistics_get_blocks_dealocated mk_sl_mallocator_arena_statistics_get_blocks_dealocated
#define mk_sl_mallocator_impl_statistics_get_blocks_peak mk_sl_mallocator_arena_statistics_get_blocks_peak
#define mk_sl_mallocator_impl_statistics_get_blocks_live mk_sl_mallocator_arena_statistics_get_blocks_live
#define mk_sl_mallocator_impl_statistics_get_bytes_allocated mk_sl_mallocator_arena_statistics_get_bytes_allocated
#define mk_sl_mallocator_impl_statistics_get_bytes_dealocated mk_sl_mallocator_arena_statistics_get_bytes_dealocated
#define mk_sl_mallocator_impl_statistics_get_bytes_peak mk_sl_mallocator_arena_statistics_get_bytes_peak
#define mk_sl_mallocator_impl_statistics_get_bytes_live mk_sl_mallocator_arena_statistics_get_bytes_live
#define mk_sl_mallocator_impl_statistics_get_all mk_sl_mallocator_arena_statistics_get_all
#elif mk_lang_platform_is_windows_at_least_any
#include "mk_sl_mallocator_windows.h"
#define mk_sl_mallocator_impl_init mk_sl_mallocator_windows_init
#define mk_sl_mallocator_impl_deinit mk_sl_mallocator_windows_deinit
#define mk_sl_mallocator_impl_allocate mk_sl_mallocator_windows_allocate
#define mk_sl_mallocator_impl_deallocate mk_sl_mallocator_windows_deallocate
#define mk_sl_mallocator_impl_reallocate mk_sl_mallocator_windows_reallocate
#define mk_sl_mallocator_impl_statistics_get_blocks_allocated mk_sl_mallocator_windows_statistics_get_blocks_allocated
#define mk_sl_mallocator_impl_statistics_get_blocks_dealocated mk_sl_mallocator_windows_statistics_get_blocks_dealocated
#define mk_sl_mallocator_impl_statistics_get_blocks_peak mk_sl_mallocator_windows_statistics_get_blocks_peak
#define mk_sl_mallocator_impl_statistics_get_blocks_live mk_sl_mallocator_windows_statistics_get_blocks_live
#define mk_sl_mallocator_impl_statistics_get_bytes_allocated mk_sl_mallocator_windows_statistics_get_bytes_allocated
#define mk_sl_mallocator_impl_statistics_get_bytes_dealocated mk_sl_mallocator_windows_statistics_get_bytes_dealocated
#define mk_sl_mallocator_impl_statistics_get_bytes_peak mk_sl_mallocator_windows_statistics_get_bytes_peak
#define mk_sl_mallocator_impl_statistics_get_bytes_live mk_sl_mallocator_windows_statistics_get_bytes_live
#define mk_sl_mallocator_impl_statistics_get_all mk_sl_mallocator_windows_statistics_get_all
#elif mk_lang_version_has_macro_cplusplus
#include "mk_sl_mallocator_lang_cpp.hpp"
#define mk_sl_mallocator_impl_init mk_sl_mallocator_lang_cpp_init
#define mk_sl_mallocator_impl_deinit mk_sl_mallocator_lang_cpp_deinit
#define mk_sl_mallocator_impl_allocate mk_sl_mallocator_lang_cpp_allocate
#define mk_sl_mallocator_impl_deallocate mk_sl_mallocator_lang_cpp_deallocate
#define mk_sl_mallocator_impl_reallocate mk_sl_mallocator_lang_cpp_reallocate
#define mk_sl_mallocator_impl_statistics_get_blocks_allocated mk_sl_mallocator_lang_cpp_statistics_get_blocks_allocated
#define mk_sl_mallocator_impl_statistics_get_blocks_dealocated mk_sl_mallocator_lang_cpp_statistics_get_blocks_dealocated
#define mk_sl_mallocator_impl_statistics_get_blocks_peak mk_sl_mallocator_lang_cpp_statistics_get_blocks_peak
#define mk_sl_mallocator_impl_statistics_get_blocks_live mk_sl_mallocator_lang_cpp_statistics_get_blocks_live
#define mk_sl_mallocator_impl_statistics_get_bytes_allocated mk_sl_mallocator_lang_cpp_statistics_get_bytes_allocated
#define mk_sl_mallocator_impl_statistics_get_bytes_dealocated mk_sl_mallocator_lang_cpp_statistics_get_bytes_dealocated
#define mk_sl_mallocator_impl_statistics_get_bytes_peak mk_sl_mallocator_lang_cpp_statistics_get_bytes_peak
#define mk_sl_mallocator_impl_statistics_get_bytes_live mk_sl_mallocator_lang_cpp_statistics_get_bytes_live
#define mk_sl_mallocator_impl_statistics_get_all mk_sl_mallocator_lang_cpp_statistics_get_all
#else
#include "mk_sl_mallocator_lang_c.h"
#define mk_sl_mallocator_impl_init mk_sl_mallocator_lang_c_init
#define mk_sl_mallocator_impl_deinit mk_sl_mallocator_lang_c_deinit
#define mk_sl_mallocator_impl_allocate mk_sl_mallocator_lang_c_allocate
#define mk_sl_mallocator_impl_deallocate mk_sl_mallocator_lang_c_deallocate
#define mk_sl_mallocator_impl_reallocate mk_sl_mallocator_lang_c_reallocate
#define mk_sl_mallocator_impl_statistics_get_blocks_allocated mk_sl_mallocator_lang_c_statistics_get_blocks_allocated
#define mk_sl_mallocator_impl_statistics_get_blocks_dealocated mk_sl_mallocator_lang_c_statistics_get_blocks_dealocated
#define mk_sl_mallocator_impl_statistics_get_blocks_peak mk_sl_mallocator_lang_c_statistics_get_blocks_peak
#define mk_sl_mallocator_impl_statistics_get_blocks_live mk_sl_mallocator_lang_c_statistics_get_blocks_live
#define mk_sl_mallocator_impl_statistics_get_bytes_allocated mk_sl_mallocator_lang_c_statistics_get_bytes_allocated
#define mk_sl_mallocator_impl_statistics_get_bytes_dealocated mk_sl_mallocator_lang_c_statistics_get_bytes_dealocated
#define mk_sl_mallocator_impl_statistics_get_bytes_peak mk_sl_mallocator_lang_c_statistics_get_bytes_peak
#define mk_sl_mallocator_impl_statistics_get_bytes_live mk_sl_mallocator_lang_c_statistics_get_bytes_live
#define mk_sl_mallocator_impl_statistics_get_all mk_sl_mallocator_lang_c_statistics_get_all
#endif


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_init(mk_lang_types_void_t) mk_lang_noexcept
{
	return mk_sl_mallocator_impl_init();
}

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_deinit(mk_lang_types_void_t) mk_lang_noexcept
{
	return mk_sl_mallocator_impl_deinit();
}

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_allocate(mk_lang_types_usize_t const size_bytes, mk_lang_types_void_ppt const mem) mk_lang_noexcept
{
	return mk_sl_mallocator_impl_allocate(size_bytes, mem);
}

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_deallocate(mk_lang_types_void_pct const mem, mk_lang_types_usize_t const size_bytes) mk_lang_noexcept
{
	return mk_sl_mallocator_impl_deallocate(mem, size_bytes);
}

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_reallocate(mk_lang_types_void_pct const old_mem, mk_lang_types_usize_t const old_size_bytes, mk_lang_types_usize_t const new_size_bytes, mk_lang_types_void_ppt const new_mem) mk_lang_noexcept
{
	return mk_sl_mallocator_impl_reallocate(old_mem, old_size_bytes, new_size_bytes, new_mem);
}


mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_statistics_get_blocks_allocated(mk_sl_mallocator_blocks_pt const blocks_allocated) mk_lang_noexcept
{
	mk_sl_mallocator_impl_statistics_get_blocks_allocated(blocks_allocated);
}

mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_statistics_get_blocks_dealocated(mk_sl_mallocator_blocks_pt const blocks_deallocated) mk_lang_noexcept
{
	mk_sl_mallocator_impl_statistics_get_blocks_dealocated(blocks_deallocated);
}

mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_statistics_get_blocks_peak(mk_sl_mallocator_blocks_pt const blocks_peak) mk_lang_noexcept
{
	mk_sl_mallocator_impl_statistics_get_blocks_peak(blocks_peak);
}

mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_statistics_get_blocks_live(mk_sl_mallocator_blocks_pt const blocks_live) mk_lang_noexcept
{
	mk_sl_mallocator_impl_statistics_get_blocks_live(blocks_live);
}

mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_statistics_get_bytes_allocated(mk_sl_mallocator_bytes_pt const bytes_allocated) mk_lang_noexcept
{
	mk_sl_mallocator_impl_statistics_get_bytes_allocated(bytes_allocated);
}

mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_statistics_get_bytes_dealocated(mk_sl_mallocator_bytes_pt const bytes_deallocated) mk_lang_noexcept
{
	mk_sl_mallocator_impl_statistics_get_bytes_dealocated(bytes_deallocated);
}

mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_statistics_get_bytes_peak(mk_sl_mallocator_bytes_pt const bytes_peak) mk_lang_noexcept
{
	mk_sl_mallocator_impl_statistics_get_bytes_peak(bytes_peak);
}

mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_statistics_get_bytes_live(mk_sl_mallocator_bytes_pt const bytes_live) mk_lang_noexcept
{
	mk_sl_mallocator_impl_statistics_get_bytes_live(bytes_live);
}

mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_statistics_get_all(mk_lang_static_param(mk_sl_mallocator_blocks_t, blocks_all, 4), mk_lang_static_param(mk_sl_mallocator_bytes_t, bytes_all, 4)) mk_lang_noexcept
{
	mk_sl_mallocator_impl_statistics_get_all(blocks_all, bytes_all);
}


#endif
