#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_static_param.h"
#include "mk_lang_types.h"


#include "mk_sl_mallocator_lokal_inl_defd.h"


mk_lang_nodiscard mk_sl_mallocator_lokal_inl_defd_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_lokal_inl_defd_init(mk_sl_mallocator_lokal_inl_defd_pt const mallocator_lokal) mk_lang_noexcept
{
	return mk_sl_mallocator_lokal_inl_defd_base_init(mallocator_lokal);
}

mk_lang_nodiscard mk_sl_mallocator_lokal_inl_defd_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_lokal_inl_defd_deinit(mk_sl_mallocator_lokal_inl_defd_pt const mallocator_lokal) mk_lang_noexcept
{
	return mk_sl_mallocator_lokal_inl_defd_base_deinit(mallocator_lokal);
}

mk_lang_nodiscard mk_sl_mallocator_lokal_inl_defd_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_lokal_inl_defd_allocate(mk_sl_mallocator_lokal_inl_defd_pt const mallocator_lokal, mk_lang_types_usize_t const size_bytes, mk_lang_types_void_ppt const mem) mk_lang_noexcept
{
	return mk_sl_mallocator_lokal_inl_defd_base_allocate(mallocator_lokal, size_bytes, mem);
}

mk_lang_nodiscard mk_sl_mallocator_lokal_inl_defd_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_lokal_inl_defd_deallocate(mk_sl_mallocator_lokal_inl_defd_pt const mallocator_lokal, mk_lang_types_void_pct const mem, mk_lang_types_usize_t const size_bytes) mk_lang_noexcept
{
	return mk_sl_mallocator_lokal_inl_defd_base_deallocate(mallocator_lokal, mem, size_bytes);
}

mk_lang_nodiscard mk_sl_mallocator_lokal_inl_defd_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_lokal_inl_defd_reallocate(mk_sl_mallocator_lokal_inl_defd_pt const mallocator_lokal, mk_lang_types_void_pct const old_mem, mk_lang_types_usize_t const old_size_bytes, mk_lang_types_usize_t const new_size_bytes, mk_lang_types_void_ppt const new_mem) mk_lang_noexcept
{
	return mk_sl_mallocator_lokal_inl_defd_base_reallocate(mallocator_lokal, old_mem, old_size_bytes, new_size_bytes, new_mem);
}


mk_sl_mallocator_lokal_inl_defd_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_inl_defd_statistics_get_blocks_allocated(mk_sl_mallocator_lokal_inl_defd_pt const mallocator_lokal, mk_sl_mallocator_lokal_inl_defd_num_blocks_pt const blocks_allocated) mk_lang_noexcept
{
	mk_sl_mallocator_lokal_inl_defd_base_statistics_get_blocks_allocated(mallocator_lokal, blocks_allocated);
}

mk_sl_mallocator_lokal_inl_defd_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_inl_defd_statistics_get_blocks_dealocated(mk_sl_mallocator_lokal_inl_defd_pt const mallocator_lokal, mk_sl_mallocator_lokal_inl_defd_num_blocks_pt const blocks_deallocated) mk_lang_noexcept
{
	mk_sl_mallocator_lokal_inl_defd_base_statistics_get_blocks_dealocated(mallocator_lokal, blocks_deallocated);
}

mk_sl_mallocator_lokal_inl_defd_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_inl_defd_statistics_get_blocks_peak(mk_sl_mallocator_lokal_inl_defd_pt const mallocator_lokal, mk_sl_mallocator_lokal_inl_defd_num_blocks_pt const blocks_peak) mk_lang_noexcept
{
	mk_sl_mallocator_lokal_inl_defd_base_statistics_get_blocks_peak(mallocator_lokal, blocks_peak);
}

mk_sl_mallocator_lokal_inl_defd_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_inl_defd_statistics_get_blocks_live(mk_sl_mallocator_lokal_inl_defd_pt const mallocator_lokal, mk_sl_mallocator_lokal_inl_defd_num_blocks_pt const blocks_live) mk_lang_noexcept
{
	mk_sl_mallocator_lokal_inl_defd_base_statistics_get_blocks_live(mallocator_lokal, blocks_live);
}

mk_sl_mallocator_lokal_inl_defd_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_inl_defd_statistics_get_bytes_allocated(mk_sl_mallocator_lokal_inl_defd_pt const mallocator_lokal, mk_sl_mallocator_lokal_inl_defd_num_bytes_pt const bytes_allocated) mk_lang_noexcept
{
	mk_sl_mallocator_lokal_inl_defd_base_statistics_get_bytes_allocated(mallocator_lokal, bytes_allocated);
}

mk_sl_mallocator_lokal_inl_defd_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_inl_defd_statistics_get_bytes_dealocated(mk_sl_mallocator_lokal_inl_defd_pt const mallocator_lokal, mk_sl_mallocator_lokal_inl_defd_num_bytes_pt const bytes_deallocated) mk_lang_noexcept
{
	mk_sl_mallocator_lokal_inl_defd_base_statistics_get_bytes_dealocated(mallocator_lokal, bytes_deallocated);
}

mk_sl_mallocator_lokal_inl_defd_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_inl_defd_statistics_get_bytes_peak(mk_sl_mallocator_lokal_inl_defd_pt const mallocator_lokal, mk_sl_mallocator_lokal_inl_defd_num_bytes_pt const bytes_peak) mk_lang_noexcept
{
	mk_sl_mallocator_lokal_inl_defd_base_statistics_get_bytes_peak(mallocator_lokal, bytes_peak);
}

mk_sl_mallocator_lokal_inl_defd_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_inl_defd_statistics_get_bytes_live(mk_sl_mallocator_lokal_inl_defd_pt const mallocator_lokal, mk_sl_mallocator_lokal_inl_defd_num_bytes_pt const bytes_live) mk_lang_noexcept
{
	mk_sl_mallocator_lokal_inl_defd_base_statistics_get_bytes_live(mallocator_lokal, bytes_live);
}

mk_sl_mallocator_lokal_inl_defd_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_inl_defd_statistics_get_all(mk_sl_mallocator_lokal_inl_defd_pt const mallocator_lokal, mk_lang_static_param(mk_sl_mallocator_lokal_inl_defd_num_blocks_t, blocks_all, 4), mk_lang_static_param(mk_sl_mallocator_lokal_inl_defd_num_bytes_t, bytes_all, 4)) mk_lang_noexcept
{
	mk_sl_mallocator_lokal_inl_defd_base_statistics_get_all(mallocator_lokal, blocks_all, bytes_all);
}



#include "mk_sl_mallocator_lokal_inl_defu.h"
