#undef mk_sl_cui_fuzz_fromchars_t_name
#undef mk_sl_cui_fuzz_fromchars_t_a_tn
#undef mk_sl_cui_fuzz_fromchars_t_b_tn
#undef mk_sl_cui_fuzz_fromchars_t_endian
#undef mk_sl_cui_fuzz_fromchars_t_str_style
