#include "mk_lang_concat.h"


#define mk_sl_flt_parse_inl_defhd_name mk_sl_flt_name
#define mk_sl_flt_parse_inl_defhd_prefix mk_lang_concat(mk_sl_flt_parse_, mk_sl_flt_parse_inl_defhd_name)

#define mk_sl_flt_parse_inl_defhd_result_e mk_lang_concat(mk_sl_flt_parse_inl_defhd_prefix, _result_e)
#define mk_sl_flt_parse_inl_defhd_result_t mk_lang_concat(mk_sl_flt_parse_inl_defhd_prefix, _result_t)
#define mk_sl_flt_parse_inl_defhd_result_e_ok mk_lang_concat(mk_sl_flt_parse_inl_defhd_prefix, _result_e_ok)
#define mk_sl_flt_parse_inl_defhd_result_e_invalid mk_lang_concat(mk_sl_flt_parse_inl_defhd_prefix, _result_e_invalid)
#define mk_sl_flt_parse_inl_defhd_result_e_out_of_range mk_lang_concat(mk_sl_flt_parse_inl_defhd_prefix, _result_e_out_of_range)

#define mk_sl_flt_parse_inl_defhd_uchars_from_string_dec_n mk_lang_concat(mk_sl_flt_parse_inl_defhd_prefix, _uchars_from_string_dec_n)
#define mk_sl_flt_parse_inl_defhd_void_from_string_dec_n mk_lang_concat(mk_sl_flt_parse_inl_defhd_prefix, _void_from_string_dec_n)
