#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_types.h"


#include "mk_sl_tree_wavl_inl_defd.h"


typedef mk_sl_tree_wavl_inl_defd_element_type mk_sl_tree_wavl_inl_defd_element_t;
typedef mk_sl_tree_wavl_inl_defd_element_t const mk_sl_tree_wavl_inl_defd_element_ct;
typedef mk_sl_tree_wavl_inl_defd_element_t* mk_sl_tree_wavl_inl_defd_element_pt;
typedef mk_sl_tree_wavl_inl_defd_element_t const* mk_sl_tree_wavl_inl_defd_element_pct;
typedef mk_sl_tree_wavl_inl_defd_element_pt const mk_sl_tree_wavl_inl_defd_element_cpt;
typedef mk_sl_tree_wavl_inl_defd_element_pt* mk_sl_tree_wavl_inl_defd_element_ppt;
typedef mk_sl_tree_wavl_inl_defd_element_pt const* mk_sl_tree_wavl_inl_defd_element_pcpt;
typedef mk_sl_tree_wavl_inl_defd_element_pct const mk_sl_tree_wavl_inl_defd_element_cpct;
typedef mk_sl_tree_wavl_inl_defd_element_pct* mk_sl_tree_wavl_inl_defd_element_ppct;
typedef mk_sl_tree_wavl_inl_defd_element_pct const* mk_sl_tree_wavl_inl_defd_element_pcpct;


struct mk_sl_tree_wavl_inl_defd_node_s;
typedef struct mk_sl_tree_wavl_inl_defd_node_s mk_sl_tree_wavl_inl_defd_node_t;
typedef mk_sl_tree_wavl_inl_defd_node_t const mk_sl_tree_wavl_inl_defd_node_ct;
typedef mk_sl_tree_wavl_inl_defd_node_t* mk_sl_tree_wavl_inl_defd_node_pt;
typedef mk_sl_tree_wavl_inl_defd_node_t const* mk_sl_tree_wavl_inl_defd_node_pct;
typedef mk_sl_tree_wavl_inl_defd_node_pt const mk_sl_tree_wavl_inl_defd_node_cpt;
typedef mk_sl_tree_wavl_inl_defd_node_pt* mk_sl_tree_wavl_inl_defd_node_ppt;
typedef mk_sl_tree_wavl_inl_defd_node_pt const* mk_sl_tree_wavl_inl_defd_node_pcpt;
typedef mk_sl_tree_wavl_inl_defd_node_pct const mk_sl_tree_wavl_inl_defd_node_cpct;
typedef mk_sl_tree_wavl_inl_defd_node_pct* mk_sl_tree_wavl_inl_defd_node_ppct;
typedef mk_sl_tree_wavl_inl_defd_node_pct const* mk_sl_tree_wavl_inl_defd_node_pcpct;

struct mk_sl_tree_wavl_inl_defd_s
{
	mk_sl_tree_wavl_inl_defd_node_pt m_root;
	mk_lang_types_usize_t m_cnt;
};
typedef struct mk_sl_tree_wavl_inl_defd_s mk_sl_tree_wavl_inl_defd_t;
typedef mk_sl_tree_wavl_inl_defd_t const mk_sl_tree_wavl_inl_defd_ct;
typedef mk_sl_tree_wavl_inl_defd_t* mk_sl_tree_wavl_inl_defd_pt;
typedef mk_sl_tree_wavl_inl_defd_t const* mk_sl_tree_wavl_inl_defd_pct;
typedef mk_sl_tree_wavl_inl_defd_pt const mk_sl_tree_wavl_inl_defd_cpt;
typedef mk_sl_tree_wavl_inl_defd_pt* mk_sl_tree_wavl_inl_defd_ppt;
typedef mk_sl_tree_wavl_inl_defd_pt const* mk_sl_tree_wavl_inl_defd_pcpt;
typedef mk_sl_tree_wavl_inl_defd_pct const mk_sl_tree_wavl_inl_defd_cpct;
typedef mk_sl_tree_wavl_inl_defd_pct* mk_sl_tree_wavl_inl_defd_ppct;
typedef mk_sl_tree_wavl_inl_defd_pct const* mk_sl_tree_wavl_inl_defd_pcpct;


mk_lang_nodiscard mk_sl_tree_wavl_inl_defd_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_tree_wavl_inl_defd_rw_construct(mk_sl_tree_wavl_inl_defd_pt const tree_wavl) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_tree_wavl_inl_defd_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_tree_wavl_inl_defd_rw_destroy(mk_sl_tree_wavl_inl_defd_pt const tree_wavl) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_tree_wavl_inl_defd_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_tree_wavl_inl_defd_rw_insert(mk_sl_tree_wavl_inl_defd_pt const tree_wavl, mk_sl_tree_wavl_inl_defd_element_pct const element, mk_sl_tree_wavl_inl_defd_node_ppct const node) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_tree_wavl_inl_defd_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_tree_wavl_inl_defd_rw_find(mk_sl_tree_wavl_inl_defd_pt const tree_wavl, mk_sl_tree_wavl_inl_defd_element_pct const element, mk_sl_tree_wavl_inl_defd_node_ppct const node) mk_lang_noexcept;
mk_lang_nodiscard mk_sl_tree_wavl_inl_defd_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_tree_wavl_inl_defd_rw_remove(mk_sl_tree_wavl_inl_defd_pt const tree_wavl, mk_sl_tree_wavl_inl_defd_node_pct const node) mk_lang_noexcept;

mk_lang_nodiscard mk_sl_tree_wavl_inl_defd_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_tree_wavl_inl_defd_ro_node_get_element(mk_sl_tree_wavl_inl_defd_node_pct const node, mk_sl_tree_wavl_inl_defd_element_ppct const element) mk_lang_noexcept;


#include "mk_sl_tree_wavl_inl_defu.h"
