include(`mk_lang_typedef.m')dnl
#include "mk_lang_alignas.h"
#include "mk_lang_charbit.h"
#include "mk_lang_concat.h"
#include "mk_lang_flatten.h"
#include "mk_lang_forceinline.h"
#include "mk_lang_roundup.h"
#include "mk_lang_str_style.h"


#if(!( \
	(defined mk_sl_fxp_t_name) && \
	(defined mk_sl_fxp_t_base_type_name) && \
	((defined mk_sl_fxp_t_base_type_size_bits_d && (mk_sl_fxp_t_base_type_size_bits_d) >= 1 && (mk_sl_fxp_t_base_type_size_bits_d) <= 2 * 1024 * 1024) || !defined mk_sl_fxp_t_base_type_size_bits_d) && \
	(defined mk_sl_fxp_t_bits_before && (mk_sl_fxp_t_bits_before) >= 1 && (mk_sl_fxp_t_bits_before) <= 64 * 1024) && \
	(defined mk_sl_fxp_t_bits_after && (mk_sl_fxp_t_bits_after) >= 1 && (mk_sl_fxp_t_bits_after) <= 64 * 1024) && \
	((defined mk_sl_fxp_t_str_style && ((mk_sl_fxp_t_str_style) == mk_lang_str_style_table || (mk_sl_fxp_t_str_style) == mk_lang_str_style_arithmetic || (mk_sl_fxp_t_str_style) == mk_lang_str_style_arithmetic_if_possible)) || !defined mk_sl_fxp_t_str_style) && \
	((defined mk_sl_fxp_t_inline && ((mk_sl_fxp_t_inline) == 0 || (mk_sl_fxp_t_inline) == 1)) || !defined mk_sl_fxp_t_inline) && \
	((defined mk_sl_fxp_t_alignas && (mk_sl_fxp_t_alignas) >= 0 && (mk_sl_fxp_t_alignas) <= 4 * 1024) || !defined mk_sl_fxp_t_alignas) && \
1))
#error xxxxxxxxxx
#endif





#define mk_sl_fxp_inl_defd_name mk_sl_fxp_t_name

#define mk_sl_fxp_inl_defd_base_type_name mk_sl_fxp_t_base_type_name

#if defined mk_sl_fxp_t_base_type_size_bits_d
#define mk_sl_fxp_inl_defd_base_type_size_bits_d (mk_sl_fxp_t_base_type_size_bits_d)
#else
#define mk_sl_fxp_inl_defd_base_type_size_bits_d (mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _size_bits_d))
#endif

#define mk_sl_fxp_inl_defd_bits_before (mk_sl_fxp_t_bits_before)

#define mk_sl_fxp_inl_defd_bits_after (mk_sl_fxp_t_bits_after)

#if defined mk_sl_fxp_t_str_style
#define mk_sl_fxp_inl_defd_str_style (mk_sl_fxp_t_str_style)
#else
#define mk_sl_fxp_inl_defd_str_style mk_lang_str_style_arithmetic_if_possible
#endif

#if defined mk_sl_fxp_t_inline
#define mk_sl_fxp_inl_defd_inline (mk_sl_fxp_t_inline)
#else
#define mk_sl_fxp_inl_defd_inline 0
#endif

#if defined mk_sl_fxp_t_alignas
#define mk_sl_fxp_inl_defd_alignas (mk_sl_fxp_t_alignas)
#else
#define mk_sl_fxp_inl_defd_alignas 0
#endif





#if(!(mk_sl_fxp_inl_defd_bits_before + mk_sl_fxp_inl_defd_bits_after == mk_sl_fxp_inl_defd_base_type_size_bits_d))
#error xxxxxxxxxx
#endif





#if mk_sl_fxp_inl_defd_inline
#define mk_sl_fxp_inl_defd_flatten mk_lang_flatten
#define mk_sl_fxp_inl_defd_forceinline mk_lang_forceinline
#else
#define mk_sl_fxp_inl_defd_flatten
#define mk_sl_fxp_inl_defd_forceinline
#endif

#if mk_sl_fxp_inl_defd_alignas == 0
#define mk_sl_fxp_inl_defd_alignme
#else
#define mk_sl_fxp_inl_defd_alignme mk_lang_alignas(mk_sl_fxp_inl_defd_alignas)
#endif





#define mk_sl_fxp_inl_defd_base_type_name_t mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _t)
#define mk_sl_fxp_inl_defd_base mk_sl_fxp_inl_defd_base_type_name
#define mk_sl_fxp_inl_defd_base_t mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _t)
mm_per_typedef(`#define mk_sl_fxp_inl_defd_base_$1 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _$1)'`')

#define mk_sl_fxp_inl_defd_base_size_bytes_v mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _size_bytes_v)

#define mk_sl_fxp_inl_defd_base_from_base mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_base)
#define mk_sl_fxp_inl_defd_base_from_bi_bool mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_bool)
#define mk_sl_fxp_inl_defd_base_from_bi_pchar mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_pchar)
#define mk_sl_fxp_inl_defd_base_from_bi_wchar mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_wchar)
#define mk_sl_fxp_inl_defd_base_from_bi_uchar mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_uchar)
#define mk_sl_fxp_inl_defd_base_from_bi_ushort mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_ushort)
#define mk_sl_fxp_inl_defd_base_from_bi_uint mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_uint)
#define mk_sl_fxp_inl_defd_base_from_bi_ulong mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_ulong)
#define mk_sl_fxp_inl_defd_base_from_bi_ullong mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_ullong)
#define mk_sl_fxp_inl_defd_base_from_bi_ulllong mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_ulllong)
#define mk_sl_fxp_inl_defd_base_from_bi_uintptr mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_uintptr)
#define mk_sl_fxp_inl_defd_base_from_bi_uintmax mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_uintmax)
#define mk_sl_fxp_inl_defd_base_from_bi_usize mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_usize)
#define mk_sl_fxp_inl_defd_base_from_bi_schar mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_schar)
#define mk_sl_fxp_inl_defd_base_from_bi_sshort mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_sshort)
#define mk_sl_fxp_inl_defd_base_from_bi_sint mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_sint)
#define mk_sl_fxp_inl_defd_base_from_bi_slong mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_slong)
#define mk_sl_fxp_inl_defd_base_from_bi_sllong mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_sllong)
#define mk_sl_fxp_inl_defd_base_from_bi_slllong mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_slllong)
#define mk_sl_fxp_inl_defd_base_from_bi_sintptr mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_sintptr)
#define mk_sl_fxp_inl_defd_base_from_bi_sintmax mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_sintmax)
#define mk_sl_fxp_inl_defd_base_from_bi_ssize mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_bi_ssize)
#define mk_sl_fxp_inl_defd_base_to_base mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_base)
#define mk_sl_fxp_inl_defd_base_to_bi_bool mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_bool)
#define mk_sl_fxp_inl_defd_base_to_bi_pchar mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_pchar)
#define mk_sl_fxp_inl_defd_base_to_bi_wchar mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_wchar)
#define mk_sl_fxp_inl_defd_base_to_bi_uchar mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_uchar)
#define mk_sl_fxp_inl_defd_base_to_bi_ushort mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_ushort)
#define mk_sl_fxp_inl_defd_base_to_bi_uint mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_uint)
#define mk_sl_fxp_inl_defd_base_to_bi_ulong mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_ulong)
#define mk_sl_fxp_inl_defd_base_to_bi_ullong mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_ullong)
#define mk_sl_fxp_inl_defd_base_to_bi_ulllong mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_ulllong)
#define mk_sl_fxp_inl_defd_base_to_bi_uintptr mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_uintptr)
#define mk_sl_fxp_inl_defd_base_to_bi_uintmax mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_uintmax)
#define mk_sl_fxp_inl_defd_base_to_bi_usize mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_usize)
#define mk_sl_fxp_inl_defd_base_to_bi_schar mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_schar)
#define mk_sl_fxp_inl_defd_base_to_bi_sshort mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_sshort)
#define mk_sl_fxp_inl_defd_base_to_bi_sint mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_sint)
#define mk_sl_fxp_inl_defd_base_to_bi_slong mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_slong)
#define mk_sl_fxp_inl_defd_base_to_bi_sllong mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_sllong)
#define mk_sl_fxp_inl_defd_base_to_bi_slllong mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_slllong)
#define mk_sl_fxp_inl_defd_base_to_bi_sintptr mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_sintptr)
#define mk_sl_fxp_inl_defd_base_to_bi_sintmax mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_sintmax)
#define mk_sl_fxp_inl_defd_base_to_bi_ssize mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_bi_ssize)
#define mk_sl_fxp_inl_defd_base_from_buis_uchar_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_uchar_le)
#define mk_sl_fxp_inl_defd_base_from_buis_ushort_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_ushort_le)
#define mk_sl_fxp_inl_defd_base_from_buis_uint_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_uint_le)
#define mk_sl_fxp_inl_defd_base_from_buis_ulong_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_ulong_le)
#define mk_sl_fxp_inl_defd_base_from_buis_ullong_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_ullong_le)
#define mk_sl_fxp_inl_defd_base_from_buis_ulllong_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_ulllong_le)
#define mk_sl_fxp_inl_defd_base_from_buis_uintptr_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_uintptr_le)
#define mk_sl_fxp_inl_defd_base_from_buis_uintmax_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_uintmax_le)
#define mk_sl_fxp_inl_defd_base_from_buis_usize_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_usize_le)
#define mk_sl_fxp_inl_defd_base_to_buis_uchar_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_uchar_le)
#define mk_sl_fxp_inl_defd_base_to_buis_ushort_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_ushort_le)
#define mk_sl_fxp_inl_defd_base_to_buis_uint_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_uint_le)
#define mk_sl_fxp_inl_defd_base_to_buis_ulong_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_ulong_le)
#define mk_sl_fxp_inl_defd_base_to_buis_ullong_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_ullong_le)
#define mk_sl_fxp_inl_defd_base_to_buis_ulllong_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_ulllong_le)
#define mk_sl_fxp_inl_defd_base_to_buis_uintptr_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_uintptr_le)
#define mk_sl_fxp_inl_defd_base_to_buis_uintmax_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_uintmax_le)
#define mk_sl_fxp_inl_defd_base_to_buis_usize_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_usize_le)
#define mk_sl_fxp_inl_defd_base_from_buis_uchar_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_uchar_be)
#define mk_sl_fxp_inl_defd_base_from_buis_ushort_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_ushort_be)
#define mk_sl_fxp_inl_defd_base_from_buis_uint_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_uint_be)
#define mk_sl_fxp_inl_defd_base_from_buis_ulong_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_ulong_be)
#define mk_sl_fxp_inl_defd_base_from_buis_ullong_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_ullong_be)
#define mk_sl_fxp_inl_defd_base_from_buis_ulllong_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_ulllong_be)
#define mk_sl_fxp_inl_defd_base_from_buis_uintptr_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_uintptr_be)
#define mk_sl_fxp_inl_defd_base_from_buis_uintmax_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_uintmax_be)
#define mk_sl_fxp_inl_defd_base_from_buis_usize_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_buis_usize_be)
#define mk_sl_fxp_inl_defd_base_to_buis_uchar_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_uchar_be)
#define mk_sl_fxp_inl_defd_base_to_buis_ushort_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_ushort_be)
#define mk_sl_fxp_inl_defd_base_to_buis_uint_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_uint_be)
#define mk_sl_fxp_inl_defd_base_to_buis_ulong_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_ulong_be)
#define mk_sl_fxp_inl_defd_base_to_buis_ullong_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_ullong_be)
#define mk_sl_fxp_inl_defd_base_to_buis_ulllong_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_ulllong_be)
#define mk_sl_fxp_inl_defd_base_to_buis_uintptr_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_uintptr_be)
#define mk_sl_fxp_inl_defd_base_to_buis_uintmax_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_uintmax_be)
#define mk_sl_fxp_inl_defd_base_to_buis_usize_be mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_buis_usize_be)
#define mk_sl_fxp_inl_defd_base_assign mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _assign)
#define mk_sl_fxp_inl_defd_base_set_zero mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _set_zero)
#define mk_sl_fxp_inl_defd_base_set_max mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _set_max)
#define mk_sl_fxp_inl_defd_base_set_one mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _set_one)
#define mk_sl_fxp_inl_defd_base_set_two mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _set_two)
#define mk_sl_fxp_inl_defd_base_set_bit mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _set_bit)
#define mk_sl_fxp_inl_defd_base_set_mask mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _set_mask)
#define mk_sl_fxp_inl_defd_base_count_leading_zeros mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _count_leading_zeros)
#define mk_sl_fxp_inl_defd_base_count_leading_ones mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _count_leading_ones)
#define mk_sl_fxp_inl_defd_base_count_trailing_zeros mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _count_trailing_zeros)
#define mk_sl_fxp_inl_defd_base_count_trailing_ones mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _count_trailing_ones)
#define mk_sl_fxp_inl_defd_base_count_zeros mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _count_zeros)
#define mk_sl_fxp_inl_defd_base_count_ones mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _count_ones)
#define mk_sl_fxp_inl_defd_base_has_msb mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _has_msb)
#define mk_sl_fxp_inl_defd_base_has_lsb mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _has_lsb)
#define mk_sl_fxp_inl_defd_base_is_zero mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _is_zero)
#define mk_sl_fxp_inl_defd_base_is_one mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _is_one)
#define mk_sl_fxp_inl_defd_base_is_two mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _is_two)
#define mk_sl_fxp_inl_defd_base_is_max mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _is_max)
#define mk_sl_fxp_inl_defd_base_is_bit mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _is_bit)
#define mk_sl_fxp_inl_defd_base_eq mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _eq)
#define mk_sl_fxp_inl_defd_base_ne mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _ne)
#define mk_sl_fxp_inl_defd_base_lt mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _lt)
#define mk_sl_fxp_inl_defd_base_le mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _le)
#define mk_sl_fxp_inl_defd_base_gt mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _gt)
#define mk_sl_fxp_inl_defd_base_ge mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _ge)
#define mk_sl_fxp_inl_defd_base_cmp mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _cmp)
#define mk_sl_fxp_inl_defd_base_inc1 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _inc1)
#define mk_sl_fxp_inl_defd_base_dec1 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _dec1)
#define mk_sl_fxp_inl_defd_base_inc2 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _inc2)
#define mk_sl_fxp_inl_defd_base_dec2 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _dec2)
#define mk_sl_fxp_inl_defd_base_not2 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _not2)
#define mk_sl_fxp_inl_defd_base_or3 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _or3)
#define mk_sl_fxp_inl_defd_base_and3 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _and3)
#define mk_sl_fxp_inl_defd_base_xor3 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _xor3)
#define mk_sl_fxp_inl_defd_base_not1 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _not1)
#define mk_sl_fxp_inl_defd_base_or2 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _or2)
#define mk_sl_fxp_inl_defd_base_and2 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _and2)
#define mk_sl_fxp_inl_defd_base_xor2 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _xor2)
#define mk_sl_fxp_inl_defd_base_shl3 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _shl3)
#define mk_sl_fxp_inl_defd_base_shr3 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _shr3)
#define mk_sl_fxp_inl_defd_base_rotl3 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _rotl3)
#define mk_sl_fxp_inl_defd_base_rotr3 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _rotr3)
#define mk_sl_fxp_inl_defd_base_shl2 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _shl2)
#define mk_sl_fxp_inl_defd_base_shr2 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _shr2)
#define mk_sl_fxp_inl_defd_base_rotl2 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _rotl2)
#define mk_sl_fxp_inl_defd_base_rotr2 mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _rotr2)
#define mk_sl_fxp_inl_defd_base_add3_wrap_cid_cod mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _add3_wrap_cid_cod)
#define mk_sl_fxp_inl_defd_base_add3_wrap_cid_coe mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _add3_wrap_cid_coe)
#define mk_sl_fxp_inl_defd_base_add3_wrap_cie_cod mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _add3_wrap_cie_cod)
#define mk_sl_fxp_inl_defd_base_add3_wrap_cie_coe mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _add3_wrap_cie_coe)
#define mk_sl_fxp_inl_defd_base_add2_wrap_cid_cod mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _add2_wrap_cid_cod)
#define mk_sl_fxp_inl_defd_base_add2_wrap_cid_coe mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _add2_wrap_cid_coe)
#define mk_sl_fxp_inl_defd_base_add2_wrap_cie_cod mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _add2_wrap_cie_cod)
#define mk_sl_fxp_inl_defd_base_add2_wrap_cie_coe mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _add2_wrap_cie_coe)
#define mk_sl_fxp_inl_defd_base_sub3_wrap_cid_cod mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _sub3_wrap_cid_cod)
#define mk_sl_fxp_inl_defd_base_sub3_wrap_cid_coe mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _sub3_wrap_cid_coe)
#define mk_sl_fxp_inl_defd_base_sub3_wrap_cie_cod mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _sub3_wrap_cie_cod)
#define mk_sl_fxp_inl_defd_base_sub3_wrap_cie_coe mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _sub3_wrap_cie_coe)
#define mk_sl_fxp_inl_defd_base_sub2_wrap_cid_cod mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _sub2_wrap_cid_cod)
#define mk_sl_fxp_inl_defd_base_sub2_wrap_cid_coe mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _sub2_wrap_cid_coe)
#define mk_sl_fxp_inl_defd_base_sub2_wrap_cie_cod mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _sub2_wrap_cie_cod)
#define mk_sl_fxp_inl_defd_base_sub2_wrap_cie_coe mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _sub2_wrap_cie_coe)
#define mk_sl_fxp_inl_defd_base_mul3_wrap_lo mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _mul3_wrap_lo)
#define mk_sl_fxp_inl_defd_base_mul3_wrap_hi mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _mul3_wrap_hi)
#define mk_sl_fxp_inl_defd_base_mul4_wrap_wi mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _mul4_wrap_wi)
#define mk_sl_fxp_inl_defd_base_mul4_wrap_wi_smol mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _mul4_wrap_wi_smol)
#define mk_sl_fxp_inl_defd_base_mul2_wrap_lo mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _mul2_wrap_lo)
#define mk_sl_fxp_inl_defd_base_mul2_wrap_hi mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _mul2_wrap_hi)
#define mk_sl_fxp_inl_defd_base_mul2_wrap_wi mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _mul2_wrap_wi)
#define mk_sl_fxp_inl_defd_base_divmod4_wrap mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _divmod4_wrap)
#define mk_sl_fxp_inl_defd_base_div3_wrap mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _div3_wrap)
#define mk_sl_fxp_inl_defd_base_mod3_wrap mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _mod3_wrap)
#define mk_sl_fxp_inl_defd_base_div2_wrap mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _div2_wrap)
#define mk_sl_fxp_inl_defd_base_mod2_wrap mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _mod2_wrap)
#define mk_sl_fxp_inl_defd_base_divmod2_wrap mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _divmod2_wrap)
#define mk_sl_fxp_inl_defd_base_would_overflow_add_cc mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _would_overflow_add_cc)
#define mk_sl_fxp_inl_defd_base_would_overflow_add_cs mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _would_overflow_add_cs)
#define mk_sl_fxp_inl_defd_base_would_overflow_add_cp mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _would_overflow_add_cp)
#define mk_sl_fxp_inl_defd_base_would_overflow_sub_cc mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _would_overflow_sub_cc)
#define mk_sl_fxp_inl_defd_base_would_overflow_sub_cs mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _would_overflow_sub_cs)
#define mk_sl_fxp_inl_defd_base_would_overflow_sub_cp mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _would_overflow_sub_cp)
#define mk_sl_fxp_inl_defd_base_would_overflow_mul mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _would_overflow_mul)
#define mk_sl_fxp_inl_defd_base_would_overflow_div mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _would_overflow_div)
#define mk_sl_fxp_inl_defd_base_would_overflow_mod mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _would_overflow_mod)
#define mk_sl_fxp_inl_defd_base_to_str_bin_n mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_str_bin_n)
#define mk_sl_fxp_inl_defd_base_to_str_bin_w mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_str_bin_w)
#define mk_sl_fxp_inl_defd_base_to_str_oct_n mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_str_oct_n)
#define mk_sl_fxp_inl_defd_base_to_str_oct_w mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_str_oct_w)
#define mk_sl_fxp_inl_defd_base_to_str_dec_n mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_str_dec_n)
#define mk_sl_fxp_inl_defd_base_to_str_dec_w mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_str_dec_w)
#define mk_sl_fxp_inl_defd_base_to_str_hex_n mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_str_hex_n)
#define mk_sl_fxp_inl_defd_base_to_str_hex_w mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_str_hex_w)
#define mk_sl_fxp_inl_defd_base_to_str_binf_n mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_str_binf_n)
#define mk_sl_fxp_inl_defd_base_to_str_binf_w mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_str_binf_w)
#define mk_sl_fxp_inl_defd_base_to_str_hexf_n mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_str_hexf_n)
#define mk_sl_fxp_inl_defd_base_to_str_hexf_w mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_str_hexf_w)
#define mk_sl_fxp_inl_defd_base_to_str_hexf_many_n mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_str_hexf_many_n)
#define mk_sl_fxp_inl_defd_base_to_str_hexf_many_w mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _to_str_hexf_many_w)
#define mk_sl_fxp_inl_defd_base_from_str_bin_n mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_str_bin_n)
#define mk_sl_fxp_inl_defd_base_from_str_bin_w mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_str_bin_w)
#define mk_sl_fxp_inl_defd_base_from_str_oct_n mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_str_oct_n)
#define mk_sl_fxp_inl_defd_base_from_str_oct_w mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_str_oct_w)
#define mk_sl_fxp_inl_defd_base_from_str_dec_n mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_str_dec_n)
#define mk_sl_fxp_inl_defd_base_from_str_dec_w mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_str_dec_w)
#define mk_sl_fxp_inl_defd_base_from_str_hex_n mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_str_hex_n)
#define mk_sl_fxp_inl_defd_base_from_str_hex_w mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_str_hex_w)
#define mk_sl_fxp_inl_defd_base_from_str_hex_many_n mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_str_hex_many_n)
#define mk_sl_fxp_inl_defd_base_from_str_hex_many_w mk_lang_concat(mk_sl_fxp_inl_defd_base_type_name, _from_str_hex_many_w)





#define mk_sl_fxp_inl_defd_2cui mk_lang_concat(mk_sl_fxp_inl_defd_name, _zzz_2cui)
#define mk_sl_fxp_inl_defd_2cui_s mk_lang_concat(mk_sl_fxp_inl_defd_2cui, _s)
#define mk_sl_fxp_inl_defd_2cui_t mk_lang_concat(mk_sl_fxp_inl_defd_2cui, _t)
mm_per_typedef(`#define mk_sl_fxp_inl_defd_2cui_$1 mk_lang_concat(mk_sl_fxp_inl_defd_2cui, _$1)'`')
#define mk_sl_fxp_inl_defd_2cui_from_base mk_lang_concat(mk_sl_fxp_inl_defd_2cui, _from_base)
#define mk_sl_fxp_inl_defd_2cui_to_base mk_lang_concat(mk_sl_fxp_inl_defd_2cui, _to_base)
#define mk_sl_fxp_inl_defd_2cui_shl2 mk_lang_concat(mk_sl_fxp_inl_defd_2cui, _shl2)
#define mk_sl_fxp_inl_defd_2cui_shr3 mk_lang_concat(mk_sl_fxp_inl_defd_2cui, _shr3)
#define mk_sl_fxp_inl_defd_2cui_or3 mk_lang_concat(mk_sl_fxp_inl_defd_2cui, _or3)

#define mk_sl_fxp_inl_defd_ldm_name mk_lang_concat(mk_sl_fxp_inl_defd_name, _zzz_ldm)
#define mk_sl_fxp_inl_defd_ldm_divmod4 mk_lang_concat(mk_sl_fxp_inl_defd_ldm_name, _divmod4)
#define mk_sl_fxp_inl_defd_ldm_tn1s_to_tn2 mk_lang_concat(mk_sl_fxp_inl_defd_ldm_name, _tn1s_to_tn2)
#define mk_sl_fxp_inl_defd_ldm_tn1d_to_tn2 mk_lang_concat(mk_sl_fxp_inl_defd_ldm_name, _tn1d_to_tn2)
#define mk_sl_fxp_inl_defd_ldm_tn2_get_lo mk_lang_concat(mk_sl_fxp_inl_defd_ldm_name, _tn2_get_lo)
#define mk_sl_fxp_inl_defd_ldm_tn2_get_hi mk_lang_concat(mk_sl_fxp_inl_defd_ldm_name, _tn2_get_hi)





#define mk_sl_fxp_inl_defd_name_pr mk_lang_concat(mk_sl_fxp_inl_defd_name, _pr)

#define mk_sl_fxp_inl_defd_pr_adjust_after_import mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _adjust_after_import)
#define mk_sl_fxp_inl_defd_pr_adjust_before_export mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _adjust_before_export)

#define mk_sl_fxp_inl_defd_pr_from_base mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_base)
#define mk_sl_fxp_inl_defd_pr_adjust_after_import mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _adjust_after_import)
#define mk_sl_fxp_inl_defd_pr_from_bi_bool mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_bool)
#define mk_sl_fxp_inl_defd_pr_from_bi_pchar mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_pchar)
#define mk_sl_fxp_inl_defd_pr_from_bi_wchar mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_wchar)
#define mk_sl_fxp_inl_defd_pr_from_bi_uchar mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_uchar)
#define mk_sl_fxp_inl_defd_pr_from_bi_ushort mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_ushort)
#define mk_sl_fxp_inl_defd_pr_from_bi_uint mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_uint)
#define mk_sl_fxp_inl_defd_pr_from_bi_ulong mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_ulong)
#define mk_sl_fxp_inl_defd_pr_from_bi_ullong mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_ullong)
#define mk_sl_fxp_inl_defd_pr_from_bi_ulllong mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_ulllong)
#define mk_sl_fxp_inl_defd_pr_from_bi_uintptr mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_uintptr)
#define mk_sl_fxp_inl_defd_pr_from_bi_uintmax mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_uintmax)
#define mk_sl_fxp_inl_defd_pr_from_bi_usize mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_usize)
#define mk_sl_fxp_inl_defd_pr_from_bi_schar mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_schar)
#define mk_sl_fxp_inl_defd_pr_from_bi_sshort mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_sshort)
#define mk_sl_fxp_inl_defd_pr_from_bi_sint mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_sint)
#define mk_sl_fxp_inl_defd_pr_from_bi_slong mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_slong)
#define mk_sl_fxp_inl_defd_pr_from_bi_sllong mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_sllong)
#define mk_sl_fxp_inl_defd_pr_from_bi_slllong mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_slllong)
#define mk_sl_fxp_inl_defd_pr_from_bi_sintptr mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_sintptr)
#define mk_sl_fxp_inl_defd_pr_from_bi_sintmax mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_sintmax)
#define mk_sl_fxp_inl_defd_pr_from_bi_ssize mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_bi_ssize)
#define mk_sl_fxp_inl_defd_pr_from_uint8 mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_uint8)
#define mk_sl_fxp_inl_defd_pr_from_uint16 mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_uint16)
#define mk_sl_fxp_inl_defd_pr_from_uint32 mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_uint32)
#define mk_sl_fxp_inl_defd_pr_from_uint64 mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_uint64)
#define mk_sl_fxp_inl_defd_pr_from_uint128 mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_uint128)
#define mk_sl_fxp_inl_defd_pr_from_uint256 mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_uint256)
#define mk_sl_fxp_inl_defd_pr_from_uint512 mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_uint512)
#define mk_sl_fxp_inl_defd_pr_from_uint1024 mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _from_uint1024)
#define mk_sl_fxp_inl_defd_pr_to_base mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_base)
#define mk_sl_fxp_inl_defd_pr_adjust_before_export mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _adjust_before_export)
#define mk_sl_fxp_inl_defd_pr_to_bi_bool mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_bool)
#define mk_sl_fxp_inl_defd_pr_to_bi_pchar mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_pchar)
#define mk_sl_fxp_inl_defd_pr_to_bi_wchar mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_wchar)
#define mk_sl_fxp_inl_defd_pr_to_bi_uchar mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_uchar)
#define mk_sl_fxp_inl_defd_pr_to_bi_ushort mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_ushort)
#define mk_sl_fxp_inl_defd_pr_to_bi_uint mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_uint)
#define mk_sl_fxp_inl_defd_pr_to_bi_ulong mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_ulong)
#define mk_sl_fxp_inl_defd_pr_to_bi_ullong mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_ullong)
#define mk_sl_fxp_inl_defd_pr_to_bi_ulllong mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_ulllong)
#define mk_sl_fxp_inl_defd_pr_to_bi_uintptr mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_uintptr)
#define mk_sl_fxp_inl_defd_pr_to_bi_uintmax mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_uintmax)
#define mk_sl_fxp_inl_defd_pr_to_bi_usize mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_usize)
#define mk_sl_fxp_inl_defd_pr_to_bi_schar mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_schar)
#define mk_sl_fxp_inl_defd_pr_to_bi_sshort mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_sshort)
#define mk_sl_fxp_inl_defd_pr_to_bi_sint mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_sint)
#define mk_sl_fxp_inl_defd_pr_to_bi_slong mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_slong)
#define mk_sl_fxp_inl_defd_pr_to_bi_sllong mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_sllong)
#define mk_sl_fxp_inl_defd_pr_to_bi_slllong mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_slllong)
#define mk_sl_fxp_inl_defd_pr_to_bi_sintptr mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_sintptr)
#define mk_sl_fxp_inl_defd_pr_to_bi_sintmax mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_sintmax)
#define mk_sl_fxp_inl_defd_pr_to_bi_ssize mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_bi_ssize)
#define mk_sl_fxp_inl_defd_pr_set_zero mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _set_zero)
#define mk_sl_fxp_inl_defd_pr_set_one mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _set_one)
#define mk_sl_fxp_inl_defd_pr_set_two mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _set_two)
#define mk_sl_fxp_inl_defd_pr_is_zero mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _is_zero)
#define mk_sl_fxp_inl_defd_pr_is_one mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _is_one)
#define mk_sl_fxp_inl_defd_pr_is_two mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _is_two)
#define mk_sl_fxp_inl_defd_pr_eq mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _eq)
#define mk_sl_fxp_inl_defd_pr_ne mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _ne)
#define mk_sl_fxp_inl_defd_pr_lt mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _lt)
#define mk_sl_fxp_inl_defd_pr_le mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _le)
#define mk_sl_fxp_inl_defd_pr_gt mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _gt)
#define mk_sl_fxp_inl_defd_pr_ge mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _ge)
#define mk_sl_fxp_inl_defd_pr_cmp mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _cmp)
#define mk_sl_fxp_inl_defd_pr_ulp_inc1 mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _ulp_inc1)
#define mk_sl_fxp_inl_defd_pr_ulp_dec1 mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _ulp_dec1)
#define mk_sl_fxp_inl_defd_pr_ulp_inc2 mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _ulp_inc2)
#define mk_sl_fxp_inl_defd_pr_ulp_dec2 mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _ulp_dec2)
#define mk_sl_fxp_inl_defd_pr_add3_wrap_cid_cod mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _add3_wrap_cid_cod)
#define mk_sl_fxp_inl_defd_pr_add3_wrap_cid_coe mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _add3_wrap_cid_coe)
#define mk_sl_fxp_inl_defd_pr_add3_wrap_cie_cod mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _add3_wrap_cie_cod)
#define mk_sl_fxp_inl_defd_pr_add3_wrap_cie_coe mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _add3_wrap_cie_coe)
#define mk_sl_fxp_inl_defd_pr_add2_wrap_cid_cod mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _add2_wrap_cid_cod)
#define mk_sl_fxp_inl_defd_pr_add2_wrap_cid_coe mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _add2_wrap_cid_coe)
#define mk_sl_fxp_inl_defd_pr_add2_wrap_cie_cod mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _add2_wrap_cie_cod)
#define mk_sl_fxp_inl_defd_pr_add2_wrap_cie_coe mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _add2_wrap_cie_coe)
#define mk_sl_fxp_inl_defd_pr_sub3_wrap_cid_cod mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _sub3_wrap_cid_cod)
#define mk_sl_fxp_inl_defd_pr_sub3_wrap_cid_coe mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _sub3_wrap_cid_coe)
#define mk_sl_fxp_inl_defd_pr_sub3_wrap_cie_cod mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _sub3_wrap_cie_cod)
#define mk_sl_fxp_inl_defd_pr_sub3_wrap_cie_coe mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _sub3_wrap_cie_coe)
#define mk_sl_fxp_inl_defd_pr_sub2_wrap_cid_cod mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _sub2_wrap_cid_cod)
#define mk_sl_fxp_inl_defd_pr_sub2_wrap_cid_coe mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _sub2_wrap_cid_coe)
#define mk_sl_fxp_inl_defd_pr_sub2_wrap_cie_cod mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _sub2_wrap_cie_cod)
#define mk_sl_fxp_inl_defd_pr_sub2_wrap_cie_coe mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _sub2_wrap_cie_coe)
#define mk_sl_fxp_inl_defd_pr_mul3_wrap_lo mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _mul3_wrap_lo)
#define mk_sl_fxp_inl_defd_pr_mul2_wrap_lo mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _mul2_wrap_lo)
#define mk_sl_fxp_inl_defd_pr_div3_wrap mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _div3_wrap)
#define mk_sl_fxp_inl_defd_pr_div2_wrap mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _div2_wrap)
#define mk_sl_fxp_inl_defd_pr_inc1 mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _inc1)
#define mk_sl_fxp_inl_defd_pr_dec1 mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _dec1)
#define mk_sl_fxp_inl_defd_pr_inc2 mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _inc2)
#define mk_sl_fxp_inl_defd_pr_dec2 mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _dec2)
#define mk_sl_fxp_inl_defd_pr_to_string_n mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_string_n)
#define mk_sl_fxp_inl_defd_pr_to_string_w mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_string_w)
#define mk_sl_fxp_inl_defd_pr_to_string_t mk_lang_concat(mk_sl_fxp_inl_defd_name_pr, _to_string_t)





#define mk_sl_fxp_inl_defd_s mk_lang_concat(mk_sl_fxp_inl_defd_name, _s)
#define mk_sl_fxp_inl_defd_t mk_lang_concat(mk_sl_fxp_inl_defd_name, _t)
mm_per_typedef(`#define mk_sl_fxp_inl_defd_$1 mk_lang_concat(mk_sl_fxp_inl_defd_name, _$1)'`')

#define mk_sl_fxp_inl_defd_bits_before_d mk_sl_fxp_inl_defd_bits_before
#define mk_sl_fxp_inl_defd_bits_before_e mk_lang_concat(mk_sl_fxp_inl_defd_name, _bits_before_e)
#define mk_sl_fxp_inl_defd_bits_before_t mk_lang_concat(mk_sl_fxp_inl_defd_name, _bits_before_t)
#define mk_sl_fxp_inl_defd_bits_before_v mk_lang_concat(mk_sl_fxp_inl_defd_name, _bits_before_v)

#define mk_sl_fxp_inl_defd_bits_after_d mk_sl_fxp_inl_defd_bits_after
#define mk_sl_fxp_inl_defd_bits_after_e mk_lang_concat(mk_sl_fxp_inl_defd_name, _bits_after_e)
#define mk_sl_fxp_inl_defd_bits_after_t mk_lang_concat(mk_sl_fxp_inl_defd_name, _bits_after_t)
#define mk_sl_fxp_inl_defd_bits_after_v mk_lang_concat(mk_sl_fxp_inl_defd_name, _bits_after_v)

#define mk_sl_fxp_inl_defd_size_bits_d (mk_sl_fxp_inl_defd_base_type_size_bits_d)
#define mk_sl_fxp_inl_defd_size_bits_e mk_lang_concat(mk_sl_fxp_inl_defd_name, _size_bits_e)
#define mk_sl_fxp_inl_defd_size_bits_t mk_lang_concat(mk_sl_fxp_inl_defd_name, _size_bits_t)
#define mk_sl_fxp_inl_defd_size_bits_v mk_lang_concat(mk_sl_fxp_inl_defd_name, _size_bits_v)

#define mk_sl_fxp_inl_defd_size_bytes_d (mk_lang_roundup_div((mk_sl_fxp_inl_defd_base_type_size_bits_d), (mk_lang_charbit)))
#define mk_sl_fxp_inl_defd_size_bytes_e mk_lang_concat(mk_sl_fxp_inl_defd_name, _size_bytes_e)
#define mk_sl_fxp_inl_defd_size_bytes_t mk_lang_concat(mk_sl_fxp_inl_defd_name, _size_bytes_t)
#define mk_sl_fxp_inl_defd_size_bytes_v mk_lang_concat(mk_sl_fxp_inl_defd_name, _size_bytes_v)

#define mk_sl_fxp_inl_defd_from_base mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_base)
#define mk_sl_fxp_inl_defd_from_bi_bool mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_bool)
#define mk_sl_fxp_inl_defd_from_bi_pchar mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_pchar)
#define mk_sl_fxp_inl_defd_from_bi_wchar mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_wchar)
#define mk_sl_fxp_inl_defd_from_bi_uchar mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_uchar)
#define mk_sl_fxp_inl_defd_from_bi_ushort mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_ushort)
#define mk_sl_fxp_inl_defd_from_bi_uint mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_uint)
#define mk_sl_fxp_inl_defd_from_bi_ulong mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_ulong)
#define mk_sl_fxp_inl_defd_from_bi_ullong mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_ullong)
#define mk_sl_fxp_inl_defd_from_bi_ulllong mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_ulllong)
#define mk_sl_fxp_inl_defd_from_bi_uintptr mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_uintptr)
#define mk_sl_fxp_inl_defd_from_bi_uintmax mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_uintmax)
#define mk_sl_fxp_inl_defd_from_bi_usize mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_usize)
#define mk_sl_fxp_inl_defd_from_bi_schar mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_schar)
#define mk_sl_fxp_inl_defd_from_bi_sshort mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_sshort)
#define mk_sl_fxp_inl_defd_from_bi_sint mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_sint)
#define mk_sl_fxp_inl_defd_from_bi_slong mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_slong)
#define mk_sl_fxp_inl_defd_from_bi_sllong mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_sllong)
#define mk_sl_fxp_inl_defd_from_bi_slllong mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_slllong)
#define mk_sl_fxp_inl_defd_from_bi_sintptr mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_sintptr)
#define mk_sl_fxp_inl_defd_from_bi_sintmax mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_sintmax)
#define mk_sl_fxp_inl_defd_from_bi_ssize mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_bi_ssize)
#define mk_sl_fxp_inl_defd_from_uint8 mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_uint8)
#define mk_sl_fxp_inl_defd_from_uint16 mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_uint16)
#define mk_sl_fxp_inl_defd_from_uint32 mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_uint32)
#define mk_sl_fxp_inl_defd_from_uint64 mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_uint64)
#define mk_sl_fxp_inl_defd_from_uint128 mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_uint128)
#define mk_sl_fxp_inl_defd_from_uint256 mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_uint256)
#define mk_sl_fxp_inl_defd_from_uint512 mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_uint512)
#define mk_sl_fxp_inl_defd_from_uint1024 mk_lang_concat(mk_sl_fxp_inl_defd_name, _from_uint1024)
#define mk_sl_fxp_inl_defd_to_base mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_base)
#define mk_sl_fxp_inl_defd_to_bi_bool mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_bool)
#define mk_sl_fxp_inl_defd_to_bi_pchar mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_pchar)
#define mk_sl_fxp_inl_defd_to_bi_wchar mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_wchar)
#define mk_sl_fxp_inl_defd_to_bi_uchar mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_uchar)
#define mk_sl_fxp_inl_defd_to_bi_ushort mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_ushort)
#define mk_sl_fxp_inl_defd_to_bi_uint mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_uint)
#define mk_sl_fxp_inl_defd_to_bi_ulong mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_ulong)
#define mk_sl_fxp_inl_defd_to_bi_ullong mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_ullong)
#define mk_sl_fxp_inl_defd_to_bi_ulllong mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_ulllong)
#define mk_sl_fxp_inl_defd_to_bi_uintptr mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_uintptr)
#define mk_sl_fxp_inl_defd_to_bi_uintmax mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_uintmax)
#define mk_sl_fxp_inl_defd_to_bi_usize mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_usize)
#define mk_sl_fxp_inl_defd_to_bi_schar mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_schar)
#define mk_sl_fxp_inl_defd_to_bi_sshort mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_sshort)
#define mk_sl_fxp_inl_defd_to_bi_sint mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_sint)
#define mk_sl_fxp_inl_defd_to_bi_slong mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_slong)
#define mk_sl_fxp_inl_defd_to_bi_sllong mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_sllong)
#define mk_sl_fxp_inl_defd_to_bi_slllong mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_slllong)
#define mk_sl_fxp_inl_defd_to_bi_sintptr mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_sintptr)
#define mk_sl_fxp_inl_defd_to_bi_sintmax mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_sintmax)
#define mk_sl_fxp_inl_defd_to_bi_ssize mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_bi_ssize)
#define mk_sl_fxp_inl_defd_set_zero mk_lang_concat(mk_sl_fxp_inl_defd_name, _set_zero)
#define mk_sl_fxp_inl_defd_set_one mk_lang_concat(mk_sl_fxp_inl_defd_name, _set_one)
#define mk_sl_fxp_inl_defd_set_two mk_lang_concat(mk_sl_fxp_inl_defd_name, _set_two)
#define mk_sl_fxp_inl_defd_is_zero mk_lang_concat(mk_sl_fxp_inl_defd_name, _is_zero)
#define mk_sl_fxp_inl_defd_is_one mk_lang_concat(mk_sl_fxp_inl_defd_name, _is_one)
#define mk_sl_fxp_inl_defd_is_two mk_lang_concat(mk_sl_fxp_inl_defd_name, _is_two)
#define mk_sl_fxp_inl_defd_eq mk_lang_concat(mk_sl_fxp_inl_defd_name, _eq)
#define mk_sl_fxp_inl_defd_ne mk_lang_concat(mk_sl_fxp_inl_defd_name, _ne)
#define mk_sl_fxp_inl_defd_lt mk_lang_concat(mk_sl_fxp_inl_defd_name, _lt)
#define mk_sl_fxp_inl_defd_le mk_lang_concat(mk_sl_fxp_inl_defd_name, _le)
#define mk_sl_fxp_inl_defd_gt mk_lang_concat(mk_sl_fxp_inl_defd_name, _gt)
#define mk_sl_fxp_inl_defd_ge mk_lang_concat(mk_sl_fxp_inl_defd_name, _ge)
#define mk_sl_fxp_inl_defd_cmp mk_lang_concat(mk_sl_fxp_inl_defd_name, _cmp)
#define mk_sl_fxp_inl_defd_inc1 mk_lang_concat(mk_sl_fxp_inl_defd_name, _inc1)
#define mk_sl_fxp_inl_defd_dec1 mk_lang_concat(mk_sl_fxp_inl_defd_name, _dec1)
#define mk_sl_fxp_inl_defd_inc2 mk_lang_concat(mk_sl_fxp_inl_defd_name, _inc2)
#define mk_sl_fxp_inl_defd_dec2 mk_lang_concat(mk_sl_fxp_inl_defd_name, _dec2)
#define mk_sl_fxp_inl_defd_ulp_inc1 mk_lang_concat(mk_sl_fxp_inl_defd_name, _ulp_inc1)
#define mk_sl_fxp_inl_defd_ulp_dec1 mk_lang_concat(mk_sl_fxp_inl_defd_name, _ulp_dec1)
#define mk_sl_fxp_inl_defd_ulp_inc2 mk_lang_concat(mk_sl_fxp_inl_defd_name, _ulp_inc2)
#define mk_sl_fxp_inl_defd_ulp_dec2 mk_lang_concat(mk_sl_fxp_inl_defd_name, _ulp_dec2)
#define mk_sl_fxp_inl_defd_add3_wrap_cid_cod mk_lang_concat(mk_sl_fxp_inl_defd_name, _add3_wrap_cid_cod)
#define mk_sl_fxp_inl_defd_add3_wrap_cid_coe mk_lang_concat(mk_sl_fxp_inl_defd_name, _add3_wrap_cid_coe)
#define mk_sl_fxp_inl_defd_add3_wrap_cie_cod mk_lang_concat(mk_sl_fxp_inl_defd_name, _add3_wrap_cie_cod)
#define mk_sl_fxp_inl_defd_add3_wrap_cie_coe mk_lang_concat(mk_sl_fxp_inl_defd_name, _add3_wrap_cie_coe)
#define mk_sl_fxp_inl_defd_add2_wrap_cid_cod mk_lang_concat(mk_sl_fxp_inl_defd_name, _add2_wrap_cid_cod)
#define mk_sl_fxp_inl_defd_add2_wrap_cid_coe mk_lang_concat(mk_sl_fxp_inl_defd_name, _add2_wrap_cid_coe)
#define mk_sl_fxp_inl_defd_add2_wrap_cie_cod mk_lang_concat(mk_sl_fxp_inl_defd_name, _add2_wrap_cie_cod)
#define mk_sl_fxp_inl_defd_add2_wrap_cie_coe mk_lang_concat(mk_sl_fxp_inl_defd_name, _add2_wrap_cie_coe)
#define mk_sl_fxp_inl_defd_sub3_wrap_cid_cod mk_lang_concat(mk_sl_fxp_inl_defd_name, _sub3_wrap_cid_cod)
#define mk_sl_fxp_inl_defd_sub3_wrap_cid_coe mk_lang_concat(mk_sl_fxp_inl_defd_name, _sub3_wrap_cid_coe)
#define mk_sl_fxp_inl_defd_sub3_wrap_cie_cod mk_lang_concat(mk_sl_fxp_inl_defd_name, _sub3_wrap_cie_cod)
#define mk_sl_fxp_inl_defd_sub3_wrap_cie_coe mk_lang_concat(mk_sl_fxp_inl_defd_name, _sub3_wrap_cie_coe)
#define mk_sl_fxp_inl_defd_sub2_wrap_cid_cod mk_lang_concat(mk_sl_fxp_inl_defd_name, _sub2_wrap_cid_cod)
#define mk_sl_fxp_inl_defd_sub2_wrap_cid_coe mk_lang_concat(mk_sl_fxp_inl_defd_name, _sub2_wrap_cid_coe)
#define mk_sl_fxp_inl_defd_sub2_wrap_cie_cod mk_lang_concat(mk_sl_fxp_inl_defd_name, _sub2_wrap_cie_cod)
#define mk_sl_fxp_inl_defd_sub2_wrap_cie_coe mk_lang_concat(mk_sl_fxp_inl_defd_name, _sub2_wrap_cie_coe)
#define mk_sl_fxp_inl_defd_mul3_wrap_lo mk_lang_concat(mk_sl_fxp_inl_defd_name, _mul3_wrap_lo)
#define mk_sl_fxp_inl_defd_mul2_wrap_lo mk_lang_concat(mk_sl_fxp_inl_defd_name, _mul2_wrap_lo)
#define mk_sl_fxp_inl_defd_div3_wrap mk_lang_concat(mk_sl_fxp_inl_defd_name, _div3_wrap)
#define mk_sl_fxp_inl_defd_div2_wrap mk_lang_concat(mk_sl_fxp_inl_defd_name, _div2_wrap)
#define mk_sl_fxp_inl_defd_to_string_n mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_string_n)
#define mk_sl_fxp_inl_defd_to_string_w mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_string_w)
#define mk_sl_fxp_inl_defd_to_string_t mk_lang_concat(mk_sl_fxp_inl_defd_name, _to_string_t)
