#undef mk_sl_cui_convert_inl_defd_a_name
#undef mk_sl_cui_convert_inl_defd_a_base_type
#undef mk_sl_cui_convert_inl_defd_a_base_name
#undef mk_sl_cui_convert_inl_defd_a_base_bits
#undef mk_sl_cui_convert_inl_defd_a_count
#undef mk_sl_cui_convert_inl_defd_a_endian
#undef mk_sl_cui_convert_inl_defd_a_base_is_bui
#undef mk_sl_cui_convert_inl_defd_a_base_bui_tn
#undef mk_sl_cui_convert_inl_defd_a_t
#undef mk_sl_cui_convert_inl_defd_a_base_t
#undef mk_sl_cui_convert_inl_defd_a_idx

#undef mk_sl_cui_convert_inl_defd_b_name
#undef mk_sl_cui_convert_inl_defd_b_base_type
#undef mk_sl_cui_convert_inl_defd_b_base_name
#undef mk_sl_cui_convert_inl_defd_b_base_bits
#undef mk_sl_cui_convert_inl_defd_b_count
#undef mk_sl_cui_convert_inl_defd_b_endian
#undef mk_sl_cui_convert_inl_defd_b_base_is_bui
#undef mk_sl_cui_convert_inl_defd_b_base_bui_tn
#undef mk_sl_cui_convert_inl_defd_b_t
#undef mk_sl_cui_convert_inl_defd_b_base_t
#undef mk_sl_cui_convert_inl_defd_b_idx

#undef mk_sl_cui_convert_inl_defd_fn_a_to_b
