#ifndef mk_include_guard_mk_sl_dynamic_ring_h
#define mk_include_guard_mk_sl_dynamic_ring_h


#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_types.h"
#include "mk_sl_cui_uint8.h"
#include "mk_sl_dynamic_ring_copy.h"
#include "mk_sl_mallocator.h"


mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_u8_support_construct_void(mk_sl_cui_uint8_pt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_u8_support_destruct(mk_sl_cui_uint8_pt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_u8_support_construct_copy(mk_sl_cui_uint8_pt const dst, mk_sl_cui_uint8_pct const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_u8_support_construct_move(mk_sl_cui_uint8_pt const dst, mk_sl_cui_uint8_pct const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_u8_support_assign_copy(mk_sl_cui_uint8_pt const dst, mk_sl_cui_uint8_pt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_u8_support_assign_move(mk_sl_cui_uint8_pt const dst, mk_sl_cui_uint8_pt const src, mk_lang_types_usize_t const count) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_bool_t mk_sl_dynamic_ring_u8_support_eq(mk_sl_cui_uint8_pct const a, mk_sl_cui_uint8_pct const b) mk_lang_noexcept;

#define mk_sl_dynamic_ring_t_name mk_sl_dynamic_ring_u8
#define mk_sl_dynamic_ring_t_element_type mk_sl_cui_uint8_t
#define mk_sl_dynamic_ring_t_mallocatorg mk_sl_mallocator
#define mk_sl_dynamic_ring_t_copy_style mk_sl_dynamic_ring_copy_use_custom
#define mk_sl_dynamic_ring_t_element_construct_void mk_sl_dynamic_ring_u8_support_construct_void
#define mk_sl_dynamic_ring_t_element_destruct mk_sl_dynamic_ring_u8_support_destruct
#define mk_sl_dynamic_ring_t_element_construct_copy mk_sl_dynamic_ring_u8_support_construct_copy
#define mk_sl_dynamic_ring_t_element_construct_move mk_sl_dynamic_ring_u8_support_construct_move
#define mk_sl_dynamic_ring_t_element_assign_copy mk_sl_dynamic_ring_u8_support_assign_copy
#define mk_sl_dynamic_ring_t_element_assign_move mk_sl_dynamic_ring_u8_support_assign_move
#define mk_sl_dynamic_ring_t_element_eq mk_sl_dynamic_ring_u8_support_eq
#include "mk_sl_dynamic_ring_inl_fileh.h"
#include "mk_sl_dynamic_ring_inl_fileu.h"


mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_uc_support_construct_void(mk_lang_types_uchar_pt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_uc_support_destruct(mk_lang_types_uchar_pt const x) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_uc_support_construct_copy(mk_lang_types_uchar_pt const dst, mk_lang_types_uchar_pct const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_uc_support_construct_move(mk_lang_types_uchar_pt const dst, mk_lang_types_uchar_pct const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_uc_support_assign_copy(mk_lang_types_uchar_pt const dst, mk_lang_types_uchar_pt const src) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_dynamic_ring_uc_support_assign_move(mk_lang_types_uchar_pt const dst, mk_lang_types_uchar_pt const src, mk_lang_types_usize_t const count) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_bool_t mk_sl_dynamic_ring_uc_support_eq(mk_lang_types_uchar_pct const a, mk_lang_types_uchar_pct const b) mk_lang_noexcept;

#define mk_sl_dynamic_ring_t_name mk_sl_dynamic_ring_uc
#define mk_sl_dynamic_ring_t_element_type mk_lang_types_uchar_t
#define mk_sl_dynamic_ring_t_mallocatorg mk_sl_mallocator
#define mk_sl_dynamic_ring_t_copy_style mk_sl_dynamic_ring_copy_use_custom
#define mk_sl_dynamic_ring_t_element_construct_void mk_sl_dynamic_ring_uc_support_construct_void
#define mk_sl_dynamic_ring_t_element_destruct mk_sl_dynamic_ring_uc_support_destruct
#define mk_sl_dynamic_ring_t_element_construct_copy mk_sl_dynamic_ring_uc_support_construct_copy
#define mk_sl_dynamic_ring_t_element_construct_move mk_sl_dynamic_ring_uc_support_construct_move
#define mk_sl_dynamic_ring_t_element_assign_copy mk_sl_dynamic_ring_uc_support_assign_copy
#define mk_sl_dynamic_ring_t_element_assign_move mk_sl_dynamic_ring_uc_support_assign_move
#define mk_sl_dynamic_ring_t_element_eq mk_sl_dynamic_ring_uc_support_eq
#include "mk_sl_dynamic_ring_inl_fileh.h"
#include "mk_sl_dynamic_ring_inl_fileu.h"


#if mk_lang_jumbo_have
#include "mk_sl_dynamic_ring.c"
#endif
#endif
