#include "mk_lang_alignas.h"
#include "mk_lang_bui.h"
#include "mk_lang_constexpr.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_static_param.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"
#include "mk_sl_cui_uint8.h"


#include "mk_sl_mallocator_lokal_arena_inl_defd.h"


#define mk_sl_cui_t_name mk_sl_mallocator_lokal_arena_inl_defd_num_blocks_name
#define mk_sl_cui_t_base_type_name mk_lang_bui_usize
#define mk_sl_cui_t_count 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"

#define mk_sl_cui_t_name mk_sl_mallocator_lokal_arena_inl_defd_num_bytes_name
#define mk_sl_cui_t_base_type_name mk_lang_bui_usize
#define mk_sl_cui_t_count 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"


struct mk_sl_mallocator_lokal_arena_inl_defd_statistics_s
{
	mk_sl_mallocator_lokal_arena_inl_defd_num_blocks_t m_blocks_allocated;
	mk_sl_mallocator_lokal_arena_inl_defd_num_blocks_t m_blocks_deallocated;
	mk_sl_mallocator_lokal_arena_inl_defd_num_blocks_t m_blocks_peak;
	mk_sl_mallocator_lokal_arena_inl_defd_num_bytes_t m_bytes_allocated;
	mk_sl_mallocator_lokal_arena_inl_defd_num_bytes_t m_bytes_deallocated;
	mk_sl_mallocator_lokal_arena_inl_defd_num_bytes_t m_bytes_peak;
};
typedef struct mk_sl_mallocator_lokal_arena_inl_defd_statistics_s mk_sl_mallocator_lokal_arena_inl_defd_statistics_t;
mk_lang_typedef(mk_sl_mallocator_lokal_arena_inl_defd_statistics);


enum mk_sl_mallocator_lokal_arena_inl_defd_block_u { mk_sl_mallocator_lokal_arena_inl_defd_block_v = mk_sl_mallocator_lokal_arena_inl_defd_block_d }; typedef enum mk_sl_mallocator_lokal_arena_inl_defd_block_u mk_sl_mallocator_lokal_arena_inl_defd_block_t;

union mk_sl_mallocator_lokal_arena_inl_defd_mem_data_u
{
	mk_lang_alignas(mk_sl_mallocator_lokal_arena_inl_defd_block_v) mk_sl_cui_uint8_t m_u8s[mk_sl_mallocator_lokal_arena_inl_defd_algn + mk_sl_mallocator_lokal_arena_inl_defd_size];
	mk_lang_types_ulllong_t m_align;
};
typedef union mk_sl_mallocator_lokal_arena_inl_defd_mem_data_u mk_sl_mallocator_lokal_arena_inl_defd_mem_data_t;
struct mk_sl_mallocator_lokal_arena_inl_defd_mem_s
{
	mk_sl_mallocator_lokal_arena_inl_defd_mem_data_t m_data;
};
typedef struct mk_sl_mallocator_lokal_arena_inl_defd_mem_s mk_sl_mallocator_lokal_arena_inl_defd_mem_t;
mk_lang_typedef(mk_sl_mallocator_lokal_arena_inl_defd_mem);


#include "mk_lang_warning_msvc_push_c4820.h"
struct mk_sl_mallocator_lokal_arena_inl_defd_s
{
	#if mk_sl_mallocator_lokal_arena_inl_defd_statistics_want
	mk_sl_mallocator_lokal_arena_inl_defd_statistics_t m_statistics;
	#endif
	mk_sl_mallocator_lokal_arena_inl_defd_mem_t m_mem;
};
typedef struct mk_sl_mallocator_lokal_arena_inl_defd_s mk_sl_mallocator_lokal_arena_inl_defd_t;
mk_lang_typedef(mk_sl_mallocator_lokal_arena_inl_defd);
#include "mk_lang_warning_msvc_pop.h"


mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_lokal_arena_inl_defd_init(mk_sl_mallocator_lokal_arena_inl_defd_pt const arena) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_lokal_arena_inl_defd_deinit(mk_sl_mallocator_lokal_arena_inl_defd_pt const arena) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_lokal_arena_inl_defd_allocate(mk_sl_mallocator_lokal_arena_inl_defd_pt const arena, mk_lang_types_usize_t const size_bytes, mk_lang_types_void_ppt const mem) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_lokal_arena_inl_defd_deallocate(mk_sl_mallocator_lokal_arena_inl_defd_pt const arena, mk_lang_types_void_pt const mem, mk_lang_types_usize_t const size_bytes) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_constexpr mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_lokal_arena_inl_defd_reallocate(mk_sl_mallocator_lokal_arena_inl_defd_pt const arena, mk_lang_types_void_pt const old_mem, mk_lang_types_usize_t const old_size_bytes, mk_lang_types_usize_t const new_size_bytes, mk_lang_types_void_ppt const new_mem) mk_lang_noexcept;

mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_arena_inl_defd_statistics_get_blocks_allocated(mk_sl_mallocator_lokal_arena_inl_defd_pt const arena, mk_sl_mallocator_lokal_arena_inl_defd_num_blocks_pt const blocks_allocated) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_arena_inl_defd_statistics_get_blocks_dealocated(mk_sl_mallocator_lokal_arena_inl_defd_pt const arena, mk_sl_mallocator_lokal_arena_inl_defd_num_blocks_pt const blocks_deallocated) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_arena_inl_defd_statistics_get_blocks_peak(mk_sl_mallocator_lokal_arena_inl_defd_pt const arena, mk_sl_mallocator_lokal_arena_inl_defd_num_blocks_pt const blocks_peak) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_arena_inl_defd_statistics_get_blocks_live(mk_sl_mallocator_lokal_arena_inl_defd_pt const arena, mk_sl_mallocator_lokal_arena_inl_defd_num_blocks_pt const blocks_live) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_arena_inl_defd_statistics_get_bytes_allocated(mk_sl_mallocator_lokal_arena_inl_defd_pt const arena, mk_sl_mallocator_lokal_arena_inl_defd_num_bytes_pt const bytes_allocated) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_arena_inl_defd_statistics_get_bytes_dealocated(mk_sl_mallocator_lokal_arena_inl_defd_pt const arena, mk_sl_mallocator_lokal_arena_inl_defd_num_bytes_pt const bytes_deallocated) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_arena_inl_defd_statistics_get_bytes_peak(mk_sl_mallocator_lokal_arena_inl_defd_pt const arena, mk_sl_mallocator_lokal_arena_inl_defd_num_bytes_pt const bytes_peak) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_arena_inl_defd_statistics_get_bytes_live(mk_sl_mallocator_lokal_arena_inl_defd_pt const arena, mk_sl_mallocator_lokal_arena_inl_defd_num_bytes_pt const bytes_live) mk_lang_noexcept;
mk_lang_constexpr mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lokal_arena_inl_defd_statistics_get_all(mk_sl_mallocator_lokal_arena_inl_defd_pt const arena, mk_lang_static_param(mk_sl_mallocator_lokal_arena_inl_defd_num_blocks_t, blocks_all, 4), mk_lang_static_param(mk_sl_mallocator_lokal_arena_inl_defd_num_bytes_t, bytes_all, 4)) mk_lang_noexcept;


#include "mk_sl_mallocator_lokal_arena_inl_defu.h"
