include(`mk_lang_typedef.m')dnl
#include "mk_lang_assert.h"
#include "mk_lang_concat.h"


#if(!( \
	(defined mk_sl_tree_wavl_t_name) && \
	(defined mk_sl_tree_wavl_t_element_type) && \
	(defined mk_sl_tree_wavl_t_elements_compare) && \
	(defined mk_sl_tree_wavl_t_mallocatorg_name || defined mk_sl_tree_wavl_t_mallocatorl_name) && \
	((defined mk_sl_tree_wavl_t_validate_want && ((mk_sl_tree_wavl_t_validate_want) == 0 || (mk_sl_tree_wavl_t_validate_want) == 1)) || !defined mk_sl_tree_wavl_t_validate_want) && \
	(defined mk_sl_tree_wavl_t_element_copy_construct || !defined mk_sl_tree_wavl_t_element_copy_construct) && \
	(defined mk_sl_tree_wavl_t_element_move_construct || !defined mk_sl_tree_wavl_t_element_move_construct) && \
	(defined mk_sl_tree_wavl_t_element_destruct || !defined mk_sl_tree_wavl_t_element_destruct) && \
1))
#error xxxxxxxxxx
#endif


#if \
( \
	defined mk_sl_tree_wavl_t_element_copy_construct || \
	defined mk_sl_tree_wavl_t_element_move_construct || \
	defined mk_sl_tree_wavl_t_element_destruct || \
	0 \
) && \
( \
	!defined mk_sl_tree_wavl_t_element_copy_construct || \
	!defined mk_sl_tree_wavl_t_element_move_construct || \
	!defined mk_sl_tree_wavl_t_element_destruct || \
	0 \
)
#error xxxxxxxxxx
#endif

#if \
( \
	defined mk_sl_tree_wavl_t_mallocatorg_name && \
	defined mk_sl_tree_wavl_t_mallocatorl_name && \
	0 \
)
#error xxxxxxxxxx
#endif


#if defined mk_sl_tree_wavl_t_validate_want
#define mk_sl_tree_wavl_tt_validate_want mk_sl_tree_wavl_t_validate_want
#else
#if defined DEBUG || defined _DEBUG
#define mk_sl_tree_wavl_tt_validate_want 1
#else
#if defined NDEBUG || defined _NDEBUG
#define mk_sl_tree_wavl_tt_validate_want 0
#else
#define mk_sl_tree_wavl_tt_validate_want 1
#endif
#endif
#endif

#if defined mk_sl_tree_wavl_t_element_copy_construct
#define mk_sl_tree_wavl_tt_element_copy_construct mk_sl_tree_wavl_t_element_copy_construct
#else
#define mk_sl_tree_wavl_tt_element_copy_construct mk_sl_tree_wavl_inl_defd_element_copy_construct_memcopy
#endif

#if defined mk_sl_tree_wavl_t_element_move_construct
#define mk_sl_tree_wavl_tt_element_move_construct mk_sl_tree_wavl_t_element_move_construct
#else
#define mk_sl_tree_wavl_tt_element_move_construct mk_sl_tree_wavl_inl_defd_element_move_construct_memcopy
#endif

#if defined mk_sl_tree_wavl_t_element_destruct
#define mk_sl_tree_wavl_tt_element_destruct mk_sl_tree_wavl_t_element_destruct
#else
#define mk_sl_tree_wavl_tt_element_destruct mk_sl_tree_wavl_inl_defd_element_destruct_void
#endif


#define mk_sl_tree_wavl_inl_defd_name mk_sl_tree_wavl_t_name
#define mk_sl_tree_wavl_inl_defd_element_type mk_sl_tree_wavl_t_element_type
#define mk_sl_tree_wavl_inl_defd_elements_compare mk_sl_tree_wavl_t_elements_compare
#define mk_sl_tree_wavl_inl_defd_validate_want mk_sl_tree_wavl_tt_validate_want
#define mk_sl_tree_wavl_inl_defd_element_copy_construct mk_sl_tree_wavl_tt_element_copy_construct
#define mk_sl_tree_wavl_inl_defd_element_move_construct mk_sl_tree_wavl_tt_element_move_construct
#define mk_sl_tree_wavl_inl_defd_element_destruct mk_sl_tree_wavl_tt_element_destruct


#define mk_sl_tree_wavl_inl_defd_element_prefix mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _element)

#define mk_sl_tree_wavl_inl_defd_element_s mk_lang_concat(mk_sl_tree_wavl_inl_defd_element_prefix, _s)
#define mk_sl_tree_wavl_inl_defd_element_t mk_lang_concat(mk_sl_tree_wavl_inl_defd_element_prefix, _t)
mm_per_typedef(`#define mk_sl_tree_wavl_inl_defd_element_$1 mk_lang_concat(mk_sl_tree_wavl_inl_defd_element_prefix, _$1)')

#define mk_sl_tree_wavl_inl_defd_elements_compare_fn mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _elements_compare_fn)
#define mk_sl_tree_wavl_inl_defd_element_copy_construct_memcopy mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _element_copy_construct_memcopy)
#define mk_sl_tree_wavl_inl_defd_element_move_construct_memcopy mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _element_move_construct_memcopy)
#define mk_sl_tree_wavl_inl_defd_element_destruct_void mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _element_destruct_void)


#if defined mk_sl_tree_wavl_t_mallocatorg_name
#define mk_sl_tree_wavl_inl_defd_mallocator_name mk_sl_tree_wavl_t_mallocatorg_name
#define mk_sl_tree_wavl_inl_defd_mallocator_is_global 1
#define mk_sl_tree_wavl_inl_defd_mallocator_is_lokal 0
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_init mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _init)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_deinit mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _deinit)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_allocate mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _allocate)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_deallocate mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _deallocate)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_reallocate mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _reallocate)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_allocated mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_blocks_allocated)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_dealocated mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_blocks_dealocated)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_peak mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_blocks_peak)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_live mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_blocks_live)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_allocated mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_bytes_allocated)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_dealocated mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_bytes_dealocated)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_peak mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_bytes_peak)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_live mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_bytes_live)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_all mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_all)
#define mk_sl_tree_wavl_inl_defd_mallocator_member
#define mk_sl_tree_wavl_inl_defd_mallocator_param
#define mk_sl_tree_wavl_inl_defd_mallocator_assert() ((void)(0))
#define mk_sl_tree_wavl_inl_defd_mallocator_assign() ((void)(0))
#elif defined mk_sl_tree_wavl_t_mallocatorl_name
#define mk_sl_tree_wavl_inl_defd_mallocator_name mk_sl_tree_wavl_t_mallocatorl_name
#define mk_sl_tree_wavl_inl_defd_mallocator_is_global 0
#define mk_sl_tree_wavl_inl_defd_mallocator_is_lokal 1
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_t mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _t)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_pt mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _pt)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_init mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _init)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_deinit mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _deinit)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_allocate(a, b) mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _allocate)(tree->m_mallocator, a, b)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_deallocate(a, b) mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _deallocate)(tree->m_mallocator, a, b)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_reallocate mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _reallocate)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_allocated mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_blocks_allocated)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_dealocated mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_blocks_dealocated)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_peak mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_blocks_peak)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_live mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_blocks_live)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_allocated mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_bytes_allocated)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_dealocated mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_bytes_dealocated)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_peak mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_bytes_peak)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_live mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_bytes_live)
#define mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_all mk_lang_concat(mk_sl_tree_wavl_inl_defd_mallocator_name, _statistics_get_all)
#define mk_sl_tree_wavl_inl_defd_mallocator_member mk_sl_tree_wavl_inl_defd_base_mallocatorg_pt m_mallocator;
#define mk_sl_tree_wavl_inl_defd_mallocator_param , mk_sl_tree_wavl_inl_defd_base_mallocatorg_pt const mallocator
#define mk_sl_tree_wavl_inl_defd_mallocator_assert() mk_lang_assert(mallocator)
#define mk_sl_tree_wavl_inl_defd_mallocator_assign() tree->m_mallocator = mallocator
#else
#error xxxxxxxxxx
#endif


#define mk_sl_tree_wavl_inl_defd_node_prefix mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _node)
#define mk_sl_tree_wavl_inl_defd_node_s mk_lang_concat(mk_sl_tree_wavl_inl_defd_node_prefix, _s)
#define mk_sl_tree_wavl_inl_defd_node_t mk_lang_concat(mk_sl_tree_wavl_inl_defd_node_prefix, _t)
mm_per_typedef(`#define mk_sl_tree_wavl_inl_defd_node_$1 mk_lang_concat(mk_sl_tree_wavl_inl_defd_node_prefix, _$1)')

#define mk_sl_tree_wavl_inl_defd_callback_helper mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _callback_helper)
#define mk_sl_tree_wavl_inl_defd_callback_helper_s mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _callback_helper_s)
#define mk_sl_tree_wavl_inl_defd_callback_helper_t mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _callback_helper_t)
mm_per_typedef(`#define mk_sl_tree_wavl_inl_defd_callback_helper_$1 mk_lang_concat(mk_sl_tree_wavl_inl_defd_callback_helper, _$1)')

#define mk_sl_tree_wavl_inl_defd_callback_t mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _callback_t)
#define mk_sl_tree_wavl_inl_defd_s mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _s)
#define mk_sl_tree_wavl_inl_defd_t mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _t)
mm_per_typedef(`#define mk_sl_tree_wavl_inl_defd_$1 mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _$1)')

#define mk_sl_tree_wavl_inl_defd_rw_construct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rw_construct)
#define mk_sl_tree_wavl_inl_defd_rw_destruct mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rw_destruct)
#define mk_sl_tree_wavl_inl_defd_rw_insert_element_copy mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rw_insert_element_copy)
#define mk_sl_tree_wavl_inl_defd_rw_insert_element_move mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rw_insert_element_move)
#define mk_sl_tree_wavl_inl_defd_rw_insert_node mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rw_insert_node)
#define mk_sl_tree_wavl_inl_defd_ro_find_node mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _ro_find_node)
#define mk_sl_tree_wavl_inl_defd_rw_decrement_node mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rw_decrement_node)
#define mk_sl_tree_wavl_inl_defd_rw_remove_node mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rw_remove_node)
#define mk_sl_tree_wavl_inl_defd_ro_walk mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _ro_walk)

#define mk_sl_tree_wavl_inl_defd_ro_node_get_element mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _ro_node_get_element)
#define mk_sl_tree_wavl_inl_defd_rw_node_get_element mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rw_node_get_element)

#define mk_sl_tree_wavl_inl_defd_visitor_callback_dummy mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _visitor_callback_dummy)
#define mk_sl_tree_wavl_inl_defd_visitor_callback_t mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _visitor_callback_t)
#define mk_sl_tree_wavl_inl_defd_visitor_context_pt mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _visitor_context_pt)
#define mk_sl_tree_wavl_inl_defd_prro_visit mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_visit)
#define mk_sl_tree_wavl_inl_defd_rule_tree_s mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rule_tree_s)
#define mk_sl_tree_wavl_inl_defd_rule_tree_t mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rule_tree_t)
#define mk_sl_tree_wavl_inl_defd_rule_tree_pt mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _rule_tree_pt)
#define mk_sl_tree_wavl_inl_defd_prro_rule_visit_tree mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_rule_visit_tree)
#define mk_sl_tree_wavl_inl_defd_prro_rule_check_tree mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_rule_check_tree)
#define mk_sl_tree_wavl_inl_defd_prro_rule_visit_wavl mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_rule_visit_wavl)
#define mk_sl_tree_wavl_inl_defd_prro_rule_check_wavl mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_rule_check_wavl)
#define mk_sl_tree_wavl_inl_defd_prro_validate mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_validate)

#define mk_sl_tree_wavl_inl_defd_prrw_find_smallest mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_find_smallest)
#define mk_sl_tree_wavl_inl_defd_prrw_rotate_left_single_at mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_rotate_left_single_at)
#define mk_sl_tree_wavl_inl_defd_prrw_rotate_right_single_at mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_rotate_right_single_at)
#define mk_sl_tree_wavl_inl_defd_prrw_rotate_left_double_at mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_rotate_left_double_at)
#define mk_sl_tree_wavl_inl_defd_prrw_rotate_right_double_at mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_rotate_right_double_at)
#define mk_sl_tree_wavl_inl_defd_prrw_rebalance_insert mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_rebalance_insert)
#define mk_sl_tree_wavl_inl_defd_prrw_swap_in mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_swap_in)
#define mk_sl_tree_wavl_inl_defd_prrw_rebalance_remove_3child mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_rebalance_remove_3child)
#define mk_sl_tree_wavl_inl_defd_prrw_rebalance_remove_2_2_leaf mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_rebalance_delete_2_2_leaf)

#define mk_sl_tree_wavl_inl_defd_mallocatorg_allocate mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _mallocatorg_allocate)
#define mk_sl_tree_wavl_inl_defd_mallocatorg_deallocate mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _mallocatorg_deallocate)
#define mk_sl_tree_wavl_inl_defd_prro_node_get_parent mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_get_parent)
#define mk_sl_tree_wavl_inl_defd_prro_node_get_left mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_get_left)
#define mk_sl_tree_wavl_inl_defd_prro_node_get_right mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_get_right)
#define mk_sl_tree_wavl_inl_defd_prro_node_get_rank mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_get_rank)
#define mk_sl_tree_wavl_inl_defd_prro_node_is_root mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_is_root)
#define mk_sl_tree_wavl_inl_defd_prro_node_is_leaf mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_is_leaf)
#define mk_sl_tree_wavl_inl_defd_prro_node_is_unary mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_is_unary)
#define mk_sl_tree_wavl_inl_defd_prro_node_is_binary mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_is_binary)
#define mk_sl_tree_wavl_inl_defd_prro_node_is_internal mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_is_internal)
#define mk_sl_tree_wavl_inl_defd_prro_node_is_external mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_is_external)
#define mk_sl_tree_wavl_inl_defd_prro_node_get_rank_difference2 mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_get_rank_difference2)
#define mk_sl_tree_wavl_inl_defd_prro_node_get_rank_difference mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_get_rank_difference)
#define mk_sl_tree_wavl_inl_defd_prro_node_is_ichild mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_is_ichild)
#define mk_sl_tree_wavl_inl_defd_prro_node_is_ijnode mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_is_ijnode)
#define mk_sl_tree_wavl_inl_defd_prro_node_get_size mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_get_size)
#define mk_sl_tree_wavl_inl_defd_prro_node_get_height mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prro_node_get_height)

#define mk_sl_tree_wavl_inl_defd_prrw_node_get_parent mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_get_parent)
#define mk_sl_tree_wavl_inl_defd_prrw_node_get_left mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_get_left)
#define mk_sl_tree_wavl_inl_defd_prrw_node_get_right mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_get_right)
#define mk_sl_tree_wavl_inl_defd_prrw_node_promote mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_promote)
#define mk_sl_tree_wavl_inl_defd_prrw_node_demote mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_demote)
#define mk_sl_tree_wavl_inl_defd_prrw_node_inc mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_inc)
#define mk_sl_tree_wavl_inl_defd_prrw_node_init mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_init)
#define mk_sl_tree_wavl_inl_defd_prrw_node_alloc_copy mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_alloc_copy)
#define mk_sl_tree_wavl_inl_defd_prrw_node_alloc_move mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_alloc_move)
#define mk_sl_tree_wavl_inl_defd_prrw_node_dealloc mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_node_dealloc)

#define mk_sl_tree_wavl_inl_defd_prrw_dec_node mk_lang_concat(mk_sl_tree_wavl_inl_defd_name, _prrw_dec_node)
