












































#undef mk_sl_tree_wavl_tt_validate_want


#undef mk_sl_tree_wavl_tt_validate_want


#undef mk_sl_tree_wavl_tt_validate_want

#undef mk_sl_tree_wavl_tt_validate_want





#undef mk_sl_tree_wavl_tt_element_copy_construct

#undef mk_sl_tree_wavl_tt_element_copy_construct



#undef mk_sl_tree_wavl_tt_element_move_construct

#undef mk_sl_tree_wavl_tt_element_move_construct



#undef mk_sl_tree_wavl_tt_element_destruct

#undef mk_sl_tree_wavl_tt_element_destruct



#undef mk_sl_tree_wavl_inl_defd_name
#undef mk_sl_tree_wavl_inl_defd_element_type
#undef mk_sl_tree_wavl_inl_defd_elements_compare
#undef mk_sl_tree_wavl_inl_defd_validate_want
#undef mk_sl_tree_wavl_inl_defd_element_copy_construct
#undef mk_sl_tree_wavl_inl_defd_element_move_construct
#undef mk_sl_tree_wavl_inl_defd_element_destruct


#undef mk_sl_tree_wavl_inl_defd_element_prefix

#undef mk_sl_tree_wavl_inl_defd_element_s
#undef mk_sl_tree_wavl_inl_defd_element_t
#undef mk_sl_tree_wavl_inl_defd_element_ct
#undef mk_sl_tree_wavl_inl_defd_element_vt
#undef mk_sl_tree_wavl_inl_defd_element_cvt
#undef mk_sl_tree_wavl_inl_defd_element_pt
#undef mk_sl_tree_wavl_inl_defd_element_pct
#undef mk_sl_tree_wavl_inl_defd_element_pvt
#undef mk_sl_tree_wavl_inl_defd_element_pcvt
#undef mk_sl_tree_wavl_inl_defd_element_prt
#undef mk_sl_tree_wavl_inl_defd_element_prct
#undef mk_sl_tree_wavl_inl_defd_element_prvt
#undef mk_sl_tree_wavl_inl_defd_element_prcvt
#undef mk_sl_tree_wavl_inl_defd_element_lpt
#undef mk_sl_tree_wavl_inl_defd_element_lpct
#undef mk_sl_tree_wavl_inl_defd_element_lpvt
#undef mk_sl_tree_wavl_inl_defd_element_lpcvt
#undef mk_sl_tree_wavl_inl_defd_element_lprt
#undef mk_sl_tree_wavl_inl_defd_element_lprct
#undef mk_sl_tree_wavl_inl_defd_element_lprvt
#undef mk_sl_tree_wavl_inl_defd_element_lprcvt
#undef mk_sl_tree_wavl_inl_defd_element_npt
#undef mk_sl_tree_wavl_inl_defd_element_npct
#undef mk_sl_tree_wavl_inl_defd_element_npvt
#undef mk_sl_tree_wavl_inl_defd_element_npcvt
#undef mk_sl_tree_wavl_inl_defd_element_nprt
#undef mk_sl_tree_wavl_inl_defd_element_nprct
#undef mk_sl_tree_wavl_inl_defd_element_nprvt
#undef mk_sl_tree_wavl_inl_defd_element_nprcvt
#undef mk_sl_tree_wavl_inl_defd_element_cpt
#undef mk_sl_tree_wavl_inl_defd_element_vpt
#undef mk_sl_tree_wavl_inl_defd_element_cvpt
#undef mk_sl_tree_wavl_inl_defd_element_ppt
#undef mk_sl_tree_wavl_inl_defd_element_pcpt
#undef mk_sl_tree_wavl_inl_defd_element_pvpt
#undef mk_sl_tree_wavl_inl_defd_element_pcvpt
#undef mk_sl_tree_wavl_inl_defd_element_prpt
#undef mk_sl_tree_wavl_inl_defd_element_prcpt
#undef mk_sl_tree_wavl_inl_defd_element_prvpt
#undef mk_sl_tree_wavl_inl_defd_element_prcvpt
#undef mk_sl_tree_wavl_inl_defd_element_lppt
#undef mk_sl_tree_wavl_inl_defd_element_lpcpt
#undef mk_sl_tree_wavl_inl_defd_element_lpvpt
#undef mk_sl_tree_wavl_inl_defd_element_lpcvpt
#undef mk_sl_tree_wavl_inl_defd_element_lprpt
#undef mk_sl_tree_wavl_inl_defd_element_lprcpt
#undef mk_sl_tree_wavl_inl_defd_element_lprvpt
#undef mk_sl_tree_wavl_inl_defd_element_lprcvpt
#undef mk_sl_tree_wavl_inl_defd_element_nppt
#undef mk_sl_tree_wavl_inl_defd_element_npcpt
#undef mk_sl_tree_wavl_inl_defd_element_npvpt
#undef mk_sl_tree_wavl_inl_defd_element_npcvpt
#undef mk_sl_tree_wavl_inl_defd_element_nprpt
#undef mk_sl_tree_wavl_inl_defd_element_nprcpt
#undef mk_sl_tree_wavl_inl_defd_element_nprvpt
#undef mk_sl_tree_wavl_inl_defd_element_nprcvpt
#undef mk_sl_tree_wavl_inl_defd_element_cpct
#undef mk_sl_tree_wavl_inl_defd_element_vpct
#undef mk_sl_tree_wavl_inl_defd_element_cvpct
#undef mk_sl_tree_wavl_inl_defd_element_ppct
#undef mk_sl_tree_wavl_inl_defd_element_pcpct
#undef mk_sl_tree_wavl_inl_defd_element_pvpct
#undef mk_sl_tree_wavl_inl_defd_element_pcvpct
#undef mk_sl_tree_wavl_inl_defd_element_prpct
#undef mk_sl_tree_wavl_inl_defd_element_prcpct
#undef mk_sl_tree_wavl_inl_defd_element_prvpct
#undef mk_sl_tree_wavl_inl_defd_element_prcvpct
#undef mk_sl_tree_wavl_inl_defd_element_lppct
#undef mk_sl_tree_wavl_inl_defd_element_lpcpct
#undef mk_sl_tree_wavl_inl_defd_element_lpvpct
#undef mk_sl_tree_wavl_inl_defd_element_lpcvpct
#undef mk_sl_tree_wavl_inl_defd_element_lprpct
#undef mk_sl_tree_wavl_inl_defd_element_lprcpct
#undef mk_sl_tree_wavl_inl_defd_element_lprvpct
#undef mk_sl_tree_wavl_inl_defd_element_lprcvpct
#undef mk_sl_tree_wavl_inl_defd_element_nppct
#undef mk_sl_tree_wavl_inl_defd_element_npcpct
#undef mk_sl_tree_wavl_inl_defd_element_npvpct
#undef mk_sl_tree_wavl_inl_defd_element_npcvpct
#undef mk_sl_tree_wavl_inl_defd_element_nprpct
#undef mk_sl_tree_wavl_inl_defd_element_nprcpct
#undef mk_sl_tree_wavl_inl_defd_element_nprvpct
#undef mk_sl_tree_wavl_inl_defd_element_nprcvpct
#undef mk_sl_tree_wavl_inl_defd_element_cppt
#undef mk_sl_tree_wavl_inl_defd_element_vppt
#undef mk_sl_tree_wavl_inl_defd_element_cvppt
#undef mk_sl_tree_wavl_inl_defd_element_pppt
#undef mk_sl_tree_wavl_inl_defd_element_pcppt
#undef mk_sl_tree_wavl_inl_defd_element_pvppt
#undef mk_sl_tree_wavl_inl_defd_element_pcvppt
#undef mk_sl_tree_wavl_inl_defd_element_prppt
#undef mk_sl_tree_wavl_inl_defd_element_prcppt
#undef mk_sl_tree_wavl_inl_defd_element_prvppt
#undef mk_sl_tree_wavl_inl_defd_element_prcvppt
#undef mk_sl_tree_wavl_inl_defd_element_lpppt
#undef mk_sl_tree_wavl_inl_defd_element_lpcppt
#undef mk_sl_tree_wavl_inl_defd_element_lpvppt
#undef mk_sl_tree_wavl_inl_defd_element_lpcvppt
#undef mk_sl_tree_wavl_inl_defd_element_lprppt
#undef mk_sl_tree_wavl_inl_defd_element_lprcppt
#undef mk_sl_tree_wavl_inl_defd_element_lprvppt
#undef mk_sl_tree_wavl_inl_defd_element_lprcvppt
#undef mk_sl_tree_wavl_inl_defd_element_npppt
#undef mk_sl_tree_wavl_inl_defd_element_npcppt
#undef mk_sl_tree_wavl_inl_defd_element_npvppt
#undef mk_sl_tree_wavl_inl_defd_element_npcvppt
#undef mk_sl_tree_wavl_inl_defd_element_nprppt
#undef mk_sl_tree_wavl_inl_defd_element_nprcppt
#undef mk_sl_tree_wavl_inl_defd_element_nprvppt
#undef mk_sl_tree_wavl_inl_defd_element_nprcvppt

#undef mk_sl_tree_wavl_inl_defd_elements_compare_fn
#undef mk_sl_tree_wavl_inl_defd_element_copy_construct_memcopy
#undef mk_sl_tree_wavl_inl_defd_element_move_construct_memcopy
#undef mk_sl_tree_wavl_inl_defd_element_destruct_void



#undef mk_sl_tree_wavl_inl_defd_mallocator_name
#undef mk_sl_tree_wavl_inl_defd_mallocator_is_global
#undef mk_sl_tree_wavl_inl_defd_mallocator_is_lokal
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_init
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_deinit
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_allocate
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_deallocate
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_reallocate
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_allocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_dealocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_peak
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_live
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_allocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_dealocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_peak
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_live
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_all
#undef mk_sl_tree_wavl_inl_defd_mallocator_member
#undef mk_sl_tree_wavl_inl_defd_mallocator_param
#undef mk_sl_tree_wavl_inl_defd_mallocator_assert
#undef mk_sl_tree_wavl_inl_defd_mallocator_assign

#undef mk_sl_tree_wavl_inl_defd_mallocator_name
#undef mk_sl_tree_wavl_inl_defd_mallocator_is_global
#undef mk_sl_tree_wavl_inl_defd_mallocator_is_lokal
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_t
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_pt
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_init
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_deinit
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_allocate
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_deallocate
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_reallocate
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_allocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_dealocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_peak
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_live
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_allocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_dealocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_peak
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_live
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_all
#undef mk_sl_tree_wavl_inl_defd_mallocator_member
#undef mk_sl_tree_wavl_inl_defd_mallocator_param
#undef mk_sl_tree_wavl_inl_defd_mallocator_assert
#undef mk_sl_tree_wavl_inl_defd_mallocator_assign





#undef mk_sl_tree_wavl_inl_defd_node_prefix

#undef mk_sl_tree_wavl_inl_defd_node_s
#undef mk_sl_tree_wavl_inl_defd_node_t
#undef mk_sl_tree_wavl_inl_defd_node_ct
#undef mk_sl_tree_wavl_inl_defd_node_vt
#undef mk_sl_tree_wavl_inl_defd_node_cvt
#undef mk_sl_tree_wavl_inl_defd_node_pt
#undef mk_sl_tree_wavl_inl_defd_node_pct
#undef mk_sl_tree_wavl_inl_defd_node_pvt
#undef mk_sl_tree_wavl_inl_defd_node_pcvt
#undef mk_sl_tree_wavl_inl_defd_node_prt
#undef mk_sl_tree_wavl_inl_defd_node_prct
#undef mk_sl_tree_wavl_inl_defd_node_prvt
#undef mk_sl_tree_wavl_inl_defd_node_prcvt
#undef mk_sl_tree_wavl_inl_defd_node_lpt
#undef mk_sl_tree_wavl_inl_defd_node_lpct
#undef mk_sl_tree_wavl_inl_defd_node_lpvt
#undef mk_sl_tree_wavl_inl_defd_node_lpcvt
#undef mk_sl_tree_wavl_inl_defd_node_lprt
#undef mk_sl_tree_wavl_inl_defd_node_lprct
#undef mk_sl_tree_wavl_inl_defd_node_lprvt
#undef mk_sl_tree_wavl_inl_defd_node_lprcvt
#undef mk_sl_tree_wavl_inl_defd_node_npt
#undef mk_sl_tree_wavl_inl_defd_node_npct
#undef mk_sl_tree_wavl_inl_defd_node_npvt
#undef mk_sl_tree_wavl_inl_defd_node_npcvt
#undef mk_sl_tree_wavl_inl_defd_node_nprt
#undef mk_sl_tree_wavl_inl_defd_node_nprct
#undef mk_sl_tree_wavl_inl_defd_node_nprvt
#undef mk_sl_tree_wavl_inl_defd_node_nprcvt
#undef mk_sl_tree_wavl_inl_defd_node_cpt
#undef mk_sl_tree_wavl_inl_defd_node_vpt
#undef mk_sl_tree_wavl_inl_defd_node_cvpt
#undef mk_sl_tree_wavl_inl_defd_node_ppt
#undef mk_sl_tree_wavl_inl_defd_node_pcpt
#undef mk_sl_tree_wavl_inl_defd_node_pvpt
#undef mk_sl_tree_wavl_inl_defd_node_pcvpt
#undef mk_sl_tree_wavl_inl_defd_node_prpt
#undef mk_sl_tree_wavl_inl_defd_node_prcpt
#undef mk_sl_tree_wavl_inl_defd_node_prvpt
#undef mk_sl_tree_wavl_inl_defd_node_prcvpt
#undef mk_sl_tree_wavl_inl_defd_node_lppt
#undef mk_sl_tree_wavl_inl_defd_node_lpcpt
#undef mk_sl_tree_wavl_inl_defd_node_lpvpt
#undef mk_sl_tree_wavl_inl_defd_node_lpcvpt
#undef mk_sl_tree_wavl_inl_defd_node_lprpt
#undef mk_sl_tree_wavl_inl_defd_node_lprcpt
#undef mk_sl_tree_wavl_inl_defd_node_lprvpt
#undef mk_sl_tree_wavl_inl_defd_node_lprcvpt
#undef mk_sl_tree_wavl_inl_defd_node_nppt
#undef mk_sl_tree_wavl_inl_defd_node_npcpt
#undef mk_sl_tree_wavl_inl_defd_node_npvpt
#undef mk_sl_tree_wavl_inl_defd_node_npcvpt
#undef mk_sl_tree_wavl_inl_defd_node_nprpt
#undef mk_sl_tree_wavl_inl_defd_node_nprcpt
#undef mk_sl_tree_wavl_inl_defd_node_nprvpt
#undef mk_sl_tree_wavl_inl_defd_node_nprcvpt
#undef mk_sl_tree_wavl_inl_defd_node_cpct
#undef mk_sl_tree_wavl_inl_defd_node_vpct
#undef mk_sl_tree_wavl_inl_defd_node_cvpct
#undef mk_sl_tree_wavl_inl_defd_node_ppct
#undef mk_sl_tree_wavl_inl_defd_node_pcpct
#undef mk_sl_tree_wavl_inl_defd_node_pvpct
#undef mk_sl_tree_wavl_inl_defd_node_pcvpct
#undef mk_sl_tree_wavl_inl_defd_node_prpct
#undef mk_sl_tree_wavl_inl_defd_node_prcpct
#undef mk_sl_tree_wavl_inl_defd_node_prvpct
#undef mk_sl_tree_wavl_inl_defd_node_prcvpct
#undef mk_sl_tree_wavl_inl_defd_node_lppct
#undef mk_sl_tree_wavl_inl_defd_node_lpcpct
#undef mk_sl_tree_wavl_inl_defd_node_lpvpct
#undef mk_sl_tree_wavl_inl_defd_node_lpcvpct
#undef mk_sl_tree_wavl_inl_defd_node_lprpct
#undef mk_sl_tree_wavl_inl_defd_node_lprcpct
#undef mk_sl_tree_wavl_inl_defd_node_lprvpct
#undef mk_sl_tree_wavl_inl_defd_node_lprcvpct
#undef mk_sl_tree_wavl_inl_defd_node_nppct
#undef mk_sl_tree_wavl_inl_defd_node_npcpct
#undef mk_sl_tree_wavl_inl_defd_node_npvpct
#undef mk_sl_tree_wavl_inl_defd_node_npcvpct
#undef mk_sl_tree_wavl_inl_defd_node_nprpct
#undef mk_sl_tree_wavl_inl_defd_node_nprcpct
#undef mk_sl_tree_wavl_inl_defd_node_nprvpct
#undef mk_sl_tree_wavl_inl_defd_node_nprcvpct
#undef mk_sl_tree_wavl_inl_defd_node_cppt
#undef mk_sl_tree_wavl_inl_defd_node_vppt
#undef mk_sl_tree_wavl_inl_defd_node_cvppt
#undef mk_sl_tree_wavl_inl_defd_node_pppt
#undef mk_sl_tree_wavl_inl_defd_node_pcppt
#undef mk_sl_tree_wavl_inl_defd_node_pvppt
#undef mk_sl_tree_wavl_inl_defd_node_pcvppt
#undef mk_sl_tree_wavl_inl_defd_node_prppt
#undef mk_sl_tree_wavl_inl_defd_node_prcppt
#undef mk_sl_tree_wavl_inl_defd_node_prvppt
#undef mk_sl_tree_wavl_inl_defd_node_prcvppt
#undef mk_sl_tree_wavl_inl_defd_node_lpppt
#undef mk_sl_tree_wavl_inl_defd_node_lpcppt
#undef mk_sl_tree_wavl_inl_defd_node_lpvppt
#undef mk_sl_tree_wavl_inl_defd_node_lpcvppt
#undef mk_sl_tree_wavl_inl_defd_node_lprppt
#undef mk_sl_tree_wavl_inl_defd_node_lprcppt
#undef mk_sl_tree_wavl_inl_defd_node_lprvppt
#undef mk_sl_tree_wavl_inl_defd_node_lprcvppt
#undef mk_sl_tree_wavl_inl_defd_node_npppt
#undef mk_sl_tree_wavl_inl_defd_node_npcppt
#undef mk_sl_tree_wavl_inl_defd_node_npvppt
#undef mk_sl_tree_wavl_inl_defd_node_npcvppt
#undef mk_sl_tree_wavl_inl_defd_node_nprppt
#undef mk_sl_tree_wavl_inl_defd_node_nprcppt
#undef mk_sl_tree_wavl_inl_defd_node_nprvppt
#undef mk_sl_tree_wavl_inl_defd_node_nprcvppt

#undef mk_sl_tree_wavl_inl_defd_callback_t

#undef mk_sl_tree_wavl_inl_defd_s
#undef mk_sl_tree_wavl_inl_defd_t
#undef mk_sl_tree_wavl_inl_defd_ct
#undef mk_sl_tree_wavl_inl_defd_vt
#undef mk_sl_tree_wavl_inl_defd_cvt
#undef mk_sl_tree_wavl_inl_defd_pt
#undef mk_sl_tree_wavl_inl_defd_pct
#undef mk_sl_tree_wavl_inl_defd_pvt
#undef mk_sl_tree_wavl_inl_defd_pcvt
#undef mk_sl_tree_wavl_inl_defd_prt
#undef mk_sl_tree_wavl_inl_defd_prct
#undef mk_sl_tree_wavl_inl_defd_prvt
#undef mk_sl_tree_wavl_inl_defd_prcvt
#undef mk_sl_tree_wavl_inl_defd_lpt
#undef mk_sl_tree_wavl_inl_defd_lpct
#undef mk_sl_tree_wavl_inl_defd_lpvt
#undef mk_sl_tree_wavl_inl_defd_lpcvt
#undef mk_sl_tree_wavl_inl_defd_lprt
#undef mk_sl_tree_wavl_inl_defd_lprct
#undef mk_sl_tree_wavl_inl_defd_lprvt
#undef mk_sl_tree_wavl_inl_defd_lprcvt
#undef mk_sl_tree_wavl_inl_defd_npt
#undef mk_sl_tree_wavl_inl_defd_npct
#undef mk_sl_tree_wavl_inl_defd_npvt
#undef mk_sl_tree_wavl_inl_defd_npcvt
#undef mk_sl_tree_wavl_inl_defd_nprt
#undef mk_sl_tree_wavl_inl_defd_nprct
#undef mk_sl_tree_wavl_inl_defd_nprvt
#undef mk_sl_tree_wavl_inl_defd_nprcvt
#undef mk_sl_tree_wavl_inl_defd_cpt
#undef mk_sl_tree_wavl_inl_defd_vpt
#undef mk_sl_tree_wavl_inl_defd_cvpt
#undef mk_sl_tree_wavl_inl_defd_ppt
#undef mk_sl_tree_wavl_inl_defd_pcpt
#undef mk_sl_tree_wavl_inl_defd_pvpt
#undef mk_sl_tree_wavl_inl_defd_pcvpt
#undef mk_sl_tree_wavl_inl_defd_prpt
#undef mk_sl_tree_wavl_inl_defd_prcpt
#undef mk_sl_tree_wavl_inl_defd_prvpt
#undef mk_sl_tree_wavl_inl_defd_prcvpt
#undef mk_sl_tree_wavl_inl_defd_lppt
#undef mk_sl_tree_wavl_inl_defd_lpcpt
#undef mk_sl_tree_wavl_inl_defd_lpvpt
#undef mk_sl_tree_wavl_inl_defd_lpcvpt
#undef mk_sl_tree_wavl_inl_defd_lprpt
#undef mk_sl_tree_wavl_inl_defd_lprcpt
#undef mk_sl_tree_wavl_inl_defd_lprvpt
#undef mk_sl_tree_wavl_inl_defd_lprcvpt
#undef mk_sl_tree_wavl_inl_defd_nppt
#undef mk_sl_tree_wavl_inl_defd_npcpt
#undef mk_sl_tree_wavl_inl_defd_npvpt
#undef mk_sl_tree_wavl_inl_defd_npcvpt
#undef mk_sl_tree_wavl_inl_defd_nprpt
#undef mk_sl_tree_wavl_inl_defd_nprcpt
#undef mk_sl_tree_wavl_inl_defd_nprvpt
#undef mk_sl_tree_wavl_inl_defd_nprcvpt
#undef mk_sl_tree_wavl_inl_defd_cpct
#undef mk_sl_tree_wavl_inl_defd_vpct
#undef mk_sl_tree_wavl_inl_defd_cvpct
#undef mk_sl_tree_wavl_inl_defd_ppct
#undef mk_sl_tree_wavl_inl_defd_pcpct
#undef mk_sl_tree_wavl_inl_defd_pvpct
#undef mk_sl_tree_wavl_inl_defd_pcvpct
#undef mk_sl_tree_wavl_inl_defd_prpct
#undef mk_sl_tree_wavl_inl_defd_prcpct
#undef mk_sl_tree_wavl_inl_defd_prvpct
#undef mk_sl_tree_wavl_inl_defd_prcvpct
#undef mk_sl_tree_wavl_inl_defd_lppct
#undef mk_sl_tree_wavl_inl_defd_lpcpct
#undef mk_sl_tree_wavl_inl_defd_lpvpct
#undef mk_sl_tree_wavl_inl_defd_lpcvpct
#undef mk_sl_tree_wavl_inl_defd_lprpct
#undef mk_sl_tree_wavl_inl_defd_lprcpct
#undef mk_sl_tree_wavl_inl_defd_lprvpct
#undef mk_sl_tree_wavl_inl_defd_lprcvpct
#undef mk_sl_tree_wavl_inl_defd_nppct
#undef mk_sl_tree_wavl_inl_defd_npcpct
#undef mk_sl_tree_wavl_inl_defd_npvpct
#undef mk_sl_tree_wavl_inl_defd_npcvpct
#undef mk_sl_tree_wavl_inl_defd_nprpct
#undef mk_sl_tree_wavl_inl_defd_nprcpct
#undef mk_sl_tree_wavl_inl_defd_nprvpct
#undef mk_sl_tree_wavl_inl_defd_nprcvpct
#undef mk_sl_tree_wavl_inl_defd_cppt
#undef mk_sl_tree_wavl_inl_defd_vppt
#undef mk_sl_tree_wavl_inl_defd_cvppt
#undef mk_sl_tree_wavl_inl_defd_pppt
#undef mk_sl_tree_wavl_inl_defd_pcppt
#undef mk_sl_tree_wavl_inl_defd_pvppt
#undef mk_sl_tree_wavl_inl_defd_pcvppt
#undef mk_sl_tree_wavl_inl_defd_prppt
#undef mk_sl_tree_wavl_inl_defd_prcppt
#undef mk_sl_tree_wavl_inl_defd_prvppt
#undef mk_sl_tree_wavl_inl_defd_prcvppt
#undef mk_sl_tree_wavl_inl_defd_lpppt
#undef mk_sl_tree_wavl_inl_defd_lpcppt
#undef mk_sl_tree_wavl_inl_defd_lpvppt
#undef mk_sl_tree_wavl_inl_defd_lpcvppt
#undef mk_sl_tree_wavl_inl_defd_lprppt
#undef mk_sl_tree_wavl_inl_defd_lprcppt
#undef mk_sl_tree_wavl_inl_defd_lprvppt
#undef mk_sl_tree_wavl_inl_defd_lprcvppt
#undef mk_sl_tree_wavl_inl_defd_npppt
#undef mk_sl_tree_wavl_inl_defd_npcppt
#undef mk_sl_tree_wavl_inl_defd_npvppt
#undef mk_sl_tree_wavl_inl_defd_npcvppt
#undef mk_sl_tree_wavl_inl_defd_nprppt
#undef mk_sl_tree_wavl_inl_defd_nprcppt
#undef mk_sl_tree_wavl_inl_defd_nprvppt
#undef mk_sl_tree_wavl_inl_defd_nprcvppt

#undef mk_sl_tree_wavl_inl_defd_rw_construct
#undef mk_sl_tree_wavl_inl_defd_rw_destruct
#undef mk_sl_tree_wavl_inl_defd_rw_insert_element_copy
#undef mk_sl_tree_wavl_inl_defd_rw_insert_element_move
#undef mk_sl_tree_wavl_inl_defd_rw_insert_node
#undef mk_sl_tree_wavl_inl_defd_ro_find_node
#undef mk_sl_tree_wavl_inl_defd_rw_decrement_node
#undef mk_sl_tree_wavl_inl_defd_rw_remove_node
#undef mk_sl_tree_wavl_inl_defd_ro_walk

#undef mk_sl_tree_wavl_inl_defd_ro_node_get_element
#undef mk_sl_tree_wavl_inl_defd_rw_node_get_element

#undef mk_sl_tree_wavl_inl_defd_visitor_callback_dummy
#undef mk_sl_tree_wavl_inl_defd_visitor_callback_t
#undef mk_sl_tree_wavl_inl_defd_visitor_context_pt
#undef mk_sl_tree_wavl_inl_defd_prro_visit
#undef mk_sl_tree_wavl_inl_defd_rule_tree_s
#undef mk_sl_tree_wavl_inl_defd_rule_tree_t
#undef mk_sl_tree_wavl_inl_defd_rule_tree_pt
#undef mk_sl_tree_wavl_inl_defd_prro_rule_visit_tree
#undef mk_sl_tree_wavl_inl_defd_prro_rule_check_tree
#undef mk_sl_tree_wavl_inl_defd_prro_rule_visit_wavl
#undef mk_sl_tree_wavl_inl_defd_prro_rule_check_wavl
#undef mk_sl_tree_wavl_inl_defd_prro_validate

#undef mk_sl_tree_wavl_inl_defd_prrw_find_smallest
#undef mk_sl_tree_wavl_inl_defd_prrw_rotate_left_single_at
#undef mk_sl_tree_wavl_inl_defd_prrw_rotate_right_single_at
#undef mk_sl_tree_wavl_inl_defd_prrw_rotate_left_double_at
#undef mk_sl_tree_wavl_inl_defd_prrw_rotate_right_double_at
#undef mk_sl_tree_wavl_inl_defd_prrw_rebalance_insert
#undef mk_sl_tree_wavl_inl_defd_prrw_swap_in
#undef mk_sl_tree_wavl_inl_defd_prrw_rebalance_remove_3child
#undef mk_sl_tree_wavl_inl_defd_prrw_rebalance_remove_2_2_leaf

#undef mk_sl_tree_wavl_inl_defd_mallocatorg_allocate
#undef mk_sl_tree_wavl_inl_defd_mallocatorg_deallocate
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_parent
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_left
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_right
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_rank
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_root
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_leaf
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_unary
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_binary
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_internal
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_external
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_rank_difference2
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_rank_difference
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_ichild
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_ijnode
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_size
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_height

#undef mk_sl_tree_wavl_inl_defd_prrw_node_get_parent
#undef mk_sl_tree_wavl_inl_defd_prrw_node_get_left
#undef mk_sl_tree_wavl_inl_defd_prrw_node_get_right
#undef mk_sl_tree_wavl_inl_defd_prrw_node_promote
#undef mk_sl_tree_wavl_inl_defd_prrw_node_demote
#undef mk_sl_tree_wavl_inl_defd_prrw_node_inc
#undef mk_sl_tree_wavl_inl_defd_prrw_node_init
#undef mk_sl_tree_wavl_inl_defd_prrw_node_alloc_copy
#undef mk_sl_tree_wavl_inl_defd_prrw_node_alloc_move
#undef mk_sl_tree_wavl_inl_defd_prrw_node_dealloc

#undef mk_sl_tree_wavl_inl_defd_prrw_dec_node
