include(`mk_lang_typedef.m')dnl













































#undef mk_sl_tree_wavl_tt_validate_want


#undef mk_sl_tree_wavl_tt_validate_want


#undef mk_sl_tree_wavl_tt_validate_want

#undef mk_sl_tree_wavl_tt_validate_want





#undef mk_sl_tree_wavl_tt_element_copy_construct

#undef mk_sl_tree_wavl_tt_element_copy_construct



#undef mk_sl_tree_wavl_tt_element_move_construct

#undef mk_sl_tree_wavl_tt_element_move_construct



#undef mk_sl_tree_wavl_tt_element_destruct

#undef mk_sl_tree_wavl_tt_element_destruct



#undef mk_sl_tree_wavl_inl_defd_name
#undef mk_sl_tree_wavl_inl_defd_element_type
#undef mk_sl_tree_wavl_inl_defd_elements_compare
#undef mk_sl_tree_wavl_inl_defd_validate_want
#undef mk_sl_tree_wavl_inl_defd_element_copy_construct
#undef mk_sl_tree_wavl_inl_defd_element_move_construct
#undef mk_sl_tree_wavl_inl_defd_element_destruct


#undef mk_sl_tree_wavl_inl_defd_element_prefix

#undef mk_sl_tree_wavl_inl_defd_element_s
#undef mk_sl_tree_wavl_inl_defd_element_t
mm_per_typedef(`#undef mk_sl_tree_wavl_inl_defd_element_$1')

#undef mk_sl_tree_wavl_inl_defd_elements_compare_fn
#undef mk_sl_tree_wavl_inl_defd_element_copy_construct_memcopy
#undef mk_sl_tree_wavl_inl_defd_element_move_construct_memcopy
#undef mk_sl_tree_wavl_inl_defd_element_destruct_void



#undef mk_sl_tree_wavl_inl_defd_mallocator_name
#undef mk_sl_tree_wavl_inl_defd_mallocator_is_global
#undef mk_sl_tree_wavl_inl_defd_mallocator_is_lokal
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_init
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_deinit
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_allocate
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_deallocate
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_reallocate
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_allocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_dealocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_peak
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_live
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_allocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_dealocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_peak
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_live
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_all
#undef mk_sl_tree_wavl_inl_defd_mallocator_member
#undef mk_sl_tree_wavl_inl_defd_mallocator_param
#undef mk_sl_tree_wavl_inl_defd_mallocator_assert
#undef mk_sl_tree_wavl_inl_defd_mallocator_assign

#undef mk_sl_tree_wavl_inl_defd_mallocator_name
#undef mk_sl_tree_wavl_inl_defd_mallocator_is_global
#undef mk_sl_tree_wavl_inl_defd_mallocator_is_lokal
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_t
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_pt
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_init
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_deinit
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_allocate
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_deallocate
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_reallocate
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_allocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_dealocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_peak
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_blocks_live
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_allocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_dealocated
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_peak
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_bytes_live
#undef mk_sl_tree_wavl_inl_defd_base_mallocatorg_statistics_get_all
#undef mk_sl_tree_wavl_inl_defd_mallocator_member
#undef mk_sl_tree_wavl_inl_defd_mallocator_param
#undef mk_sl_tree_wavl_inl_defd_mallocator_assert
#undef mk_sl_tree_wavl_inl_defd_mallocator_assign





#undef mk_sl_tree_wavl_inl_defd_node_prefix
#undef mk_sl_tree_wavl_inl_defd_node_s
#undef mk_sl_tree_wavl_inl_defd_node_t
mm_per_typedef(`#undef mk_sl_tree_wavl_inl_defd_node_$1')

#undef mk_sl_tree_wavl_inl_defd_callback_helper
#undef mk_sl_tree_wavl_inl_defd_callback_helper_s
#undef mk_sl_tree_wavl_inl_defd_callback_helper_t
mm_per_typedef(`#undef mk_sl_tree_wavl_inl_defd_callback_helper_$1')

#undef mk_sl_tree_wavl_inl_defd_callback_t
#undef mk_sl_tree_wavl_inl_defd_s
#undef mk_sl_tree_wavl_inl_defd_t
mm_per_typedef(`#undef mk_sl_tree_wavl_inl_defd_$1')

#undef mk_sl_tree_wavl_inl_defd_rw_construct
#undef mk_sl_tree_wavl_inl_defd_rw_destruct
#undef mk_sl_tree_wavl_inl_defd_rw_insert_element_copy
#undef mk_sl_tree_wavl_inl_defd_rw_insert_element_move
#undef mk_sl_tree_wavl_inl_defd_rw_insert_node
#undef mk_sl_tree_wavl_inl_defd_ro_find_node
#undef mk_sl_tree_wavl_inl_defd_rw_decrement_node
#undef mk_sl_tree_wavl_inl_defd_rw_remove_node
#undef mk_sl_tree_wavl_inl_defd_ro_walk

#undef mk_sl_tree_wavl_inl_defd_ro_node_get_element
#undef mk_sl_tree_wavl_inl_defd_rw_node_get_element

#undef mk_sl_tree_wavl_inl_defd_visitor_callback_dummy
#undef mk_sl_tree_wavl_inl_defd_visitor_callback_t
#undef mk_sl_tree_wavl_inl_defd_visitor_context_pt
#undef mk_sl_tree_wavl_inl_defd_prro_visit
#undef mk_sl_tree_wavl_inl_defd_rule_tree_s
#undef mk_sl_tree_wavl_inl_defd_rule_tree_t
#undef mk_sl_tree_wavl_inl_defd_rule_tree_pt
#undef mk_sl_tree_wavl_inl_defd_prro_rule_visit_tree
#undef mk_sl_tree_wavl_inl_defd_prro_rule_check_tree
#undef mk_sl_tree_wavl_inl_defd_prro_rule_visit_wavl
#undef mk_sl_tree_wavl_inl_defd_prro_rule_check_wavl
#undef mk_sl_tree_wavl_inl_defd_prro_validate

#undef mk_sl_tree_wavl_inl_defd_prrw_find_smallest
#undef mk_sl_tree_wavl_inl_defd_prrw_rotate_left_single_at
#undef mk_sl_tree_wavl_inl_defd_prrw_rotate_right_single_at
#undef mk_sl_tree_wavl_inl_defd_prrw_rotate_left_double_at
#undef mk_sl_tree_wavl_inl_defd_prrw_rotate_right_double_at
#undef mk_sl_tree_wavl_inl_defd_prrw_rebalance_insert
#undef mk_sl_tree_wavl_inl_defd_prrw_swap_in
#undef mk_sl_tree_wavl_inl_defd_prrw_rebalance_remove_3child
#undef mk_sl_tree_wavl_inl_defd_prrw_rebalance_remove_2_2_leaf

#undef mk_sl_tree_wavl_inl_defd_mallocatorg_allocate
#undef mk_sl_tree_wavl_inl_defd_mallocatorg_deallocate
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_parent
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_left
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_right
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_rank
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_root
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_leaf
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_unary
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_binary
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_internal
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_external
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_rank_difference2
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_rank_difference
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_ichild
#undef mk_sl_tree_wavl_inl_defd_prro_node_is_ijnode
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_size
#undef mk_sl_tree_wavl_inl_defd_prro_node_get_height

#undef mk_sl_tree_wavl_inl_defd_prrw_node_get_parent
#undef mk_sl_tree_wavl_inl_defd_prrw_node_get_left
#undef mk_sl_tree_wavl_inl_defd_prrw_node_get_right
#undef mk_sl_tree_wavl_inl_defd_prrw_node_promote
#undef mk_sl_tree_wavl_inl_defd_prrw_node_demote
#undef mk_sl_tree_wavl_inl_defd_prrw_node_inc
#undef mk_sl_tree_wavl_inl_defd_prrw_node_init
#undef mk_sl_tree_wavl_inl_defd_prrw_node_alloc_copy
#undef mk_sl_tree_wavl_inl_defd_prrw_node_alloc_move
#undef mk_sl_tree_wavl_inl_defd_prrw_node_dealloc

#undef mk_sl_tree_wavl_inl_defd_prrw_dec_node
