












#undef mk_sl_fixed_tree_wavl_inl_defd_name
#undef mk_sl_fixed_tree_wavl_inl_defd_element_type
#undef mk_sl_fixed_tree_wavl_inl_defd_elements_compare
#undef mk_sl_fixed_tree_wavl_inl_defd_capacity


#undef mk_sl_fixed_tree_wavl_inl_defd_element_t
#undef mk_sl_fixed_tree_wavl_inl_defd_element_ct
#undef mk_sl_fixed_tree_wavl_inl_defd_element_pt
#undef mk_sl_fixed_tree_wavl_inl_defd_element_pct
#undef mk_sl_fixed_tree_wavl_inl_defd_element_cpt
#undef mk_sl_fixed_tree_wavl_inl_defd_element_ppt
#undef mk_sl_fixed_tree_wavl_inl_defd_element_pcpt
#undef mk_sl_fixed_tree_wavl_inl_defd_element_cpct
#undef mk_sl_fixed_tree_wavl_inl_defd_element_ppct
#undef mk_sl_fixed_tree_wavl_inl_defd_element_pcpct

#undef mk_sl_fixed_tree_wavl_inl_defd_elements_compare_fn

#undef mk_sl_fixed_tree_wavl_inl_defd_node_s
#undef mk_sl_fixed_tree_wavl_inl_defd_node_t
#undef mk_sl_fixed_tree_wavl_inl_defd_node_ct
#undef mk_sl_fixed_tree_wavl_inl_defd_node_pt
#undef mk_sl_fixed_tree_wavl_inl_defd_node_pct
#undef mk_sl_fixed_tree_wavl_inl_defd_node_cpt
#undef mk_sl_fixed_tree_wavl_inl_defd_node_ppt
#undef mk_sl_fixed_tree_wavl_inl_defd_node_pcpt
#undef mk_sl_fixed_tree_wavl_inl_defd_node_cpct
#undef mk_sl_fixed_tree_wavl_inl_defd_node_ppct
#undef mk_sl_fixed_tree_wavl_inl_defd_node_pcpct

#undef mk_sl_fixed_tree_wavl_inl_defd_fv_name
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_s
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_t
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_ct
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_pt
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_pct
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_cpt
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_ppt
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_pcpt
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_cpct
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_ppct
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_pcpct
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_st_capacity
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_ro_capacity
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_ro_size
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_ro_free
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_ro_is_empty
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_ro_is_full
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_ro_at
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_ro_data
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_ro_front
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_ro_back
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_capacity
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_size
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_free
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_is_empty
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_is_full
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_at
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_data
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_front
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_back
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_construct
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_shrink
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_resize
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_push_back_many
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_push_back_one
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_push_back_void
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_pop_back_one
#undef mk_sl_fixed_tree_wavl_inl_defd_fv_rw_pop_back_many

#undef mk_sl_fixed_tree_wavl_inl_defd_s
#undef mk_sl_fixed_tree_wavl_inl_defd_t
#undef mk_sl_fixed_tree_wavl_inl_defd_ct
#undef mk_sl_fixed_tree_wavl_inl_defd_pt
#undef mk_sl_fixed_tree_wavl_inl_defd_pct
#undef mk_sl_fixed_tree_wavl_inl_defd_cpt
#undef mk_sl_fixed_tree_wavl_inl_defd_ppt
#undef mk_sl_fixed_tree_wavl_inl_defd_pcpt
#undef mk_sl_fixed_tree_wavl_inl_defd_cpct
#undef mk_sl_fixed_tree_wavl_inl_defd_ppct
#undef mk_sl_fixed_tree_wavl_inl_defd_pcpct

#undef mk_sl_fixed_tree_wavl_inl_defd_rw_construct
#undef mk_sl_fixed_tree_wavl_inl_defd_rw_destroy
#undef mk_sl_fixed_tree_wavl_inl_defd_rw_insert_element
#undef mk_sl_fixed_tree_wavl_inl_defd_rw_insert_node
#undef mk_sl_fixed_tree_wavl_inl_defd_rw_find
#undef mk_sl_fixed_tree_wavl_inl_defd_rw_decrement_node
#undef mk_sl_fixed_tree_wavl_inl_defd_rw_remove_node

#undef mk_sl_fixed_tree_wavl_inl_defd_ro_node_get_element
#undef mk_sl_fixed_tree_wavl_inl_defd_rw_node_get_element

#undef mk_sl_fixed_tree_wavl_inl_defd_prro_node_is_root
#undef mk_sl_fixed_tree_wavl_inl_defd_prro_node_is_binary
#undef mk_sl_fixed_tree_wavl_inl_defd_prro_node_is_unary
#undef mk_sl_fixed_tree_wavl_inl_defd_prro_node_is_leaf
#undef mk_sl_fixed_tree_wavl_inl_defd_prro_node_is_internal
#undef mk_sl_fixed_tree_wavl_inl_defd_prro_node_is_external
#undef mk_sl_fixed_tree_wavl_inl_defd_prro_node_get_next
#undef mk_sl_fixed_tree_wavl_inl_defd_prro_node_has_cycle
#undef mk_sl_fixed_tree_wavl_inl_defd_prro_node_is_cmp
#undef mk_sl_fixed_tree_wavl_inl_defd_prro_node_is_valid
#undef mk_sl_fixed_tree_wavl_inl_defd_prro_node_get_rank_bit
#undef mk_sl_fixed_tree_wavl_inl_defd_prro_node_get_sibling
#undef mk_sl_fixed_tree_wavl_inl_defd_prro_node_is_leaf
#undef mk_sl_fixed_tree_wavl_inl_defd_prro_node_is_2child
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_node_set_rank_bit
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_node_get_sibling
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_node_find_minimum
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_node_promote_single
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_node_promote_double
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_node_demote_single
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_node_demote_double
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_node_inc
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_node_dec

#undef mk_sl_fixed_tree_wavl_inl_defd_prro_validate_impl3
#undef mk_sl_fixed_tree_wavl_inl_defd_prro_validate_impl2
#undef mk_sl_fixed_tree_wavl_inl_defd_prro_validate_impl
#undef mk_sl_fixed_tree_wavl_inl_defd_prro_validate
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_alloc
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_destroy_single
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_destroy_iterative
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_rotate_left_single
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_rotate_right_single
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_rotate_left_double
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_rotate_right_double
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_rebalance_insert
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_swap_in
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_rebalance_delete_3child
#undef mk_sl_fixed_tree_wavl_inl_defd_prrw_rebalance_delete_22leaf
