#define mk_sl_cui_fuzz_inl_defd_fn mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _fn)

#define mk_sl_cui_fuzz_inl_defd_to_bi_ulllong mk_lang_concat(mk_lang_concat(mk_sl_cui_, mk_sl_cui_inl_defd_name), _to_bi_ulllong)
#define mk_sl_cui_fuzz_inl_defd_from_bi_ulllong mk_lang_concat(mk_lang_concat(mk_sl_cui_, mk_sl_cui_inl_defd_name), _from_bi_ulllong)

#define mk_sl_cui_fuzz_inl_defd_eq_restrict mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _eq_restrict)
#define mk_sl_cui_fuzz_inl_defd_ne_restrict mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _ne_restrict)
#define mk_sl_cui_fuzz_inl_defd_lt_restrict mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _lt_restrict)
#define mk_sl_cui_fuzz_inl_defd_le_restrict mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _le_restrict)
#define mk_sl_cui_fuzz_inl_defd_gt_restrict mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _gt_restrict)
#define mk_sl_cui_fuzz_inl_defd_ge_restrict mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _ge_restrict)
#define mk_sl_cui_fuzz_inl_defd_inc2_restrict mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _inc2_restrict)
#define mk_sl_cui_fuzz_inl_defd_dec2_restrict mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _dec2_restrict)

#define mk_sl_cui_fuzz_inl_defd_eq_alias mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _eq_alias)
#define mk_sl_cui_fuzz_inl_defd_ne_alias mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _ne_alias)
#define mk_sl_cui_fuzz_inl_defd_lt_alias mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _lt_alias)
#define mk_sl_cui_fuzz_inl_defd_le_alias mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _le_alias)
#define mk_sl_cui_fuzz_inl_defd_gt_alias mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _gt_alias)
#define mk_sl_cui_fuzz_inl_defd_ge_alias mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _ge_alias)
#define mk_sl_cui_fuzz_inl_defd_inc2_alias mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _inc2_alias)
#define mk_sl_cui_fuzz_inl_defd_dec2_alias mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _dec2_alias)

#define mk_sl_cui_fuzz_inl_defd_set_zero mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _set_zero)
#define mk_sl_cui_fuzz_inl_defd_set_max mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _set_max)
#define mk_sl_cui_fuzz_inl_defd_set_one mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _set_one)
#define mk_sl_cui_fuzz_inl_defd_set_bit mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _set_bit)
#define mk_sl_cui_fuzz_inl_defd_set_mask mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _set_mask)
#define mk_sl_cui_fuzz_inl_defd_is_zero mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _is_zero)
#define mk_sl_cui_fuzz_inl_defd_is_max mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _is_max)
#define mk_sl_cui_fuzz_inl_defd_eq mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _eq)
#define mk_sl_cui_fuzz_inl_defd_ne mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _ne)
#define mk_sl_cui_fuzz_inl_defd_lt mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _lt)
#define mk_sl_cui_fuzz_inl_defd_le mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _le)
#define mk_sl_cui_fuzz_inl_defd_gt mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _gt)
#define mk_sl_cui_fuzz_inl_defd_ge mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _ge)
#define mk_sl_cui_fuzz_inl_defd_inc2 mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _inc2)
#define mk_sl_cui_fuzz_inl_defd_dec2 mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _dec2)
#define mk_sl_cui_fuzz_inl_defd_inc1 mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _inc1)
#define mk_sl_cui_fuzz_inl_defd_dec1 mk_lang_concat(mk_lang_concat(mk_sl_cui_fuzz_, mk_sl_cui_inl_defd_name), _dec1)
