include(`mk_lang_typedef.m')dnl



































































#undef mk_sl_dynamic_ring_inl_defd_name
#undef mk_sl_dynamic_ring_inl_defd_element_type


#undef mk_sl_dynamic_ring_inl_defd_mallocator
#undef mk_sl_dynamic_ring_inl_defd_mallocator_is_global
#undef mk_sl_dynamic_ring_inl_defd_mallocator_is_lokal

#undef mk_sl_dynamic_ring_inl_defd_mallocator
#undef mk_sl_dynamic_ring_inl_defd_mallocator_is_global
#undef mk_sl_dynamic_ring_inl_defd_mallocator_is_lokal





#undef mk_sl_dynamic_ring_inl_defd_copy_style


#undef mk_sl_dynamic_ring_inl_defd_copy_style


#undef mk_sl_dynamic_ring_inl_defd_copy_style

#undef mk_sl_dynamic_ring_inl_defd_copy_style





#undef mk_sl_dynamic_ring_inl_defd_element_construct_destruct_has
#undef mk_sl_dynamic_ring_inl_defd_element_construct_void
#undef mk_sl_dynamic_ring_inl_defd_element_destruct

#undef mk_sl_dynamic_ring_inl_defd_element_construct_destruct_has



#undef mk_sl_dynamic_ring_inl_defd_element_copy_has
#undef mk_sl_dynamic_ring_inl_defd_element_copy_construct
#undef mk_sl_dynamic_ring_inl_defd_element_copy_assign

#undef mk_sl_dynamic_ring_inl_defd_element_copy_has



#undef mk_sl_dynamic_ring_inl_defd_element_move_has
#undef mk_sl_dynamic_ring_inl_defd_element_move_construct
#undef mk_sl_dynamic_ring_inl_defd_element_move_assign

#undef mk_sl_dynamic_ring_inl_defd_element_move_has



#undef mk_sl_dynamic_ring_inl_defd_element_eq_has
#undef mk_sl_dynamic_ring_inl_defd_element_eq

#undef mk_sl_dynamic_ring_inl_defd_element_eq_has



#undef mk_sl_dynamic_ring_inl_defd_element_prefix
#undef mk_sl_dynamic_ring_inl_defd_element_s
#undef mk_sl_dynamic_ring_inl_defd_element_t
mm_per_typedef(`#undef mk_sl_dynamic_ring_inl_defd_element_$1')`'dnl

#undef mk_sl_dynamic_ring_inl_defd_mallocator_pt

#undef mk_sl_dynamic_ring_inl_defd_mallocator_init
#undef mk_sl_dynamic_ring_inl_defd_mallocator_deinit
#undef mk_sl_dynamic_ring_inl_defd_mallocator_allocate
#undef mk_sl_dynamic_ring_inl_defd_mallocator_deallocate
#undef mk_sl_dynamic_ring_inl_defd_mallocator_reallocate
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_blocks_allocated
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_blocks_dealocated
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_blocks_peak
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_blocks_live
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_bytes_allocated
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_bytes_dealocated
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_bytes_peak
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_bytes_live
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_all

#undef mk_sl_dynamic_ring_inl_defd_mallocator_init
#undef mk_sl_dynamic_ring_inl_defd_mallocator_deinit
#undef mk_sl_dynamic_ring_inl_defd_mallocator_allocate
#undef mk_sl_dynamic_ring_inl_defd_mallocator_deallocate
#undef mk_sl_dynamic_ring_inl_defd_mallocator_reallocate
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_blocks_allocated
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_blocks_dealocated
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_blocks_peak
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_blocks_live
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_bytes_allocated
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_bytes_dealocated
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_bytes_peak
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_bytes_live
#undef mk_sl_dynamic_ring_inl_defd_mallocator_statistics_get_all


#undef mk_sl_dynamic_ring_inl_defd_s
#undef mk_sl_dynamic_ring_inl_defd_t
mm_per_typedef(`#undef mk_sl_dynamic_ring_inl_defd_$1')`'dnl


#undef mk_sl_dynamic_ring_inl_defd_mallocator_member
#undef mk_sl_dynamic_ring_inl_defd_mallocator_param

#undef mk_sl_dynamic_ring_inl_defd_mallocator_assert
#undef mk_sl_dynamic_ring_inl_defd_mallocator_assign
#undef mk_sl_dynamic_ring_inl_defd_mallocator_access

#undef mk_sl_dynamic_ring_inl_defd_mallocator_member
#undef mk_sl_dynamic_ring_inl_defd_mallocator_param
#undef mk_sl_dynamic_ring_inl_defd_mallocator_get_param
#undef mk_sl_dynamic_ring_inl_defd_mallocator_assert
#undef mk_sl_dynamic_ring_inl_defd_mallocator_assign
#undef mk_sl_dynamic_ring_inl_defd_mallocator_access






#undef mk_sl_dynamic_ring_inl_defd_prro_verify_invariants

#undef mk_sl_dynamic_ring_inl_defd_prrw_element_construct_copy_single
#undef mk_sl_dynamic_ring_inl_defd_prrw_element_construct_move_single
#undef mk_sl_dynamic_ring_inl_defd_prrw_element_destroy_single

#undef mk_sl_dynamic_ring_inl_defd_prrw_elements_construct_copy_many
#undef mk_sl_dynamic_ring_inl_defd_prrw_elements_construct_move_many
#undef mk_sl_dynamic_ring_inl_defd_prrw_elements_assign_move_many
#undef mk_sl_dynamic_ring_inl_defd_prrw_elements_destroy_many

#undef mk_sl_dynamic_ring_inl_defd_prro_get_capacity
#undef mk_sl_dynamic_ring_inl_defd_prro_get_size
#undef mk_sl_dynamic_ring_inl_defd_prro_get_sise
#undef mk_sl_dynamic_ring_inl_defd_prro_get_free_size
#undef mk_sl_dynamic_ring_inl_defd_prro_is_empty
#undef mk_sl_dynamic_ring_inl_defd_prro_is_full
#undef mk_sl_dynamic_ring_inl_defd_prro_get_front
#undef mk_sl_dynamic_ring_inl_defd_prro_get_size_a
#undef mk_sl_dynamic_ring_inl_defd_prro_get_sise_a
#undef mk_sl_dynamic_ring_inl_defd_prro_get_data_a
#undef mk_sl_dynamic_ring_inl_defd_prro_get_size_b
#undef mk_sl_dynamic_ring_inl_defd_prro_get_sise_b
#undef mk_sl_dynamic_ring_inl_defd_prro_get_data_b
#undef mk_sl_dynamic_ring_inl_defd_prro_get_free_size_a
#undef mk_sl_dynamic_ring_inl_defd_prro_get_free_data_a
#undef mk_sl_dynamic_ring_inl_defd_prro_get_free_size_b
#undef mk_sl_dynamic_ring_inl_defd_prro_get_free_data_b

#undef mk_sl_dynamic_ring_inl_defd_prrw_get_capacity
#undef mk_sl_dynamic_ring_inl_defd_prrw_get_size
#undef mk_sl_dynamic_ring_inl_defd_prrw_get_sise
#undef mk_sl_dynamic_ring_inl_defd_prrw_get_free_size
#undef mk_sl_dynamic_ring_inl_defd_prrw_is_empty
#undef mk_sl_dynamic_ring_inl_defd_prrw_is_full
#undef mk_sl_dynamic_ring_inl_defd_prrw_get_front
#undef mk_sl_dynamic_ring_inl_defd_prrw_get_size_a
#undef mk_sl_dynamic_ring_inl_defd_prrw_get_sise_a
#undef mk_sl_dynamic_ring_inl_defd_prrw_get_data_a
#undef mk_sl_dynamic_ring_inl_defd_prrw_get_size_b
#undef mk_sl_dynamic_ring_inl_defd_prrw_get_sise_b
#undef mk_sl_dynamic_ring_inl_defd_prrw_get_data_b
#undef mk_sl_dynamic_ring_inl_defd_prrw_get_free_size_a
#undef mk_sl_dynamic_ring_inl_defd_prrw_get_free_data_a
#undef mk_sl_dynamic_ring_inl_defd_prrw_get_free_size_b
#undef mk_sl_dynamic_ring_inl_defd_prrw_get_free_data_b

#undef mk_sl_dynamic_ring_inl_defd_prrw_construct
#undef mk_sl_dynamic_ring_inl_defd_prrw_construct_copy
#undef mk_sl_dynamic_ring_inl_defd_prrw_construct_move
#undef mk_sl_dynamic_ring_inl_defd_prrw_clear
#undef mk_sl_dynamic_ring_inl_defd_prrw_consolidate
#undef mk_sl_dynamic_ring_inl_defd_prrw_push_back_void
#undef mk_sl_dynamic_ring_inl_defd_prrw_destroy
#undef mk_sl_dynamic_ring_inl_defd_prrw_reserve_at_least
#undef mk_sl_dynamic_ring_inl_defd_prrw_reserve_additional
#undef mk_sl_dynamic_ring_inl_defd_prrw_push_back_copy_many
#undef mk_sl_dynamic_ring_inl_defd_prrw_push_back_copy_single
#undef mk_sl_dynamic_ring_inl_defd_prrw_push_back_move_many
#undef mk_sl_dynamic_ring_inl_defd_prrw_push_back_move_single
#undef mk_sl_dynamic_ring_inl_defd_prrw_push_front_copy_many
#undef mk_sl_dynamic_ring_inl_defd_prrw_push_front_copy_single
#undef mk_sl_dynamic_ring_inl_defd_prrw_push_front_move_many
#undef mk_sl_dynamic_ring_inl_defd_prrw_push_front_move_single
#undef mk_sl_dynamic_ring_inl_defd_prrw_assign_copy
#undef mk_sl_dynamic_ring_inl_defd_prrw_assign_move
#undef mk_sl_dynamic_ring_inl_defd_prrw_pop_back_many
#undef mk_sl_dynamic_ring_inl_defd_prrw_pop_back_single
#undef mk_sl_dynamic_ring_inl_defd_prrw_pop_front_many
#undef mk_sl_dynamic_ring_inl_defd_prrw_pop_front_single





#undef mk_sl_dynamic_ring_inl_defd_max_capacity_d
#undef mk_sl_dynamic_ring_inl_defd_max_capacity_e
#undef mk_sl_dynamic_ring_inl_defd_max_capacity_t
#undef mk_sl_dynamic_ring_inl_defd_max_capacity_v

#undef mk_sl_dynamic_ring_inl_defd_ro_get_capacity
#undef mk_sl_dynamic_ring_inl_defd_ro_get_size
#undef mk_sl_dynamic_ring_inl_defd_ro_get_sise
#undef mk_sl_dynamic_ring_inl_defd_ro_get_free_size
#undef mk_sl_dynamic_ring_inl_defd_ro_is_empty
#undef mk_sl_dynamic_ring_inl_defd_ro_is_full
#undef mk_sl_dynamic_ring_inl_defd_ro_get_front
#undef mk_sl_dynamic_ring_inl_defd_ro_get_size_a
#undef mk_sl_dynamic_ring_inl_defd_ro_get_sise_a
#undef mk_sl_dynamic_ring_inl_defd_ro_get_data_a
#undef mk_sl_dynamic_ring_inl_defd_ro_get_size_b
#undef mk_sl_dynamic_ring_inl_defd_ro_get_sise_b
#undef mk_sl_dynamic_ring_inl_defd_ro_get_data_b
#undef mk_sl_dynamic_ring_inl_defd_ro_get_free_size_a
#undef mk_sl_dynamic_ring_inl_defd_ro_get_free_data_a
#undef mk_sl_dynamic_ring_inl_defd_ro_get_free_size_b
#undef mk_sl_dynamic_ring_inl_defd_ro_get_free_data_b

#undef mk_sl_dynamic_ring_inl_defd_rw_get_capacity
#undef mk_sl_dynamic_ring_inl_defd_rw_get_size
#undef mk_sl_dynamic_ring_inl_defd_rw_get_sise
#undef mk_sl_dynamic_ring_inl_defd_rw_get_free_size
#undef mk_sl_dynamic_ring_inl_defd_rw_is_empty
#undef mk_sl_dynamic_ring_inl_defd_rw_is_full
#undef mk_sl_dynamic_ring_inl_defd_rw_get_front
#undef mk_sl_dynamic_ring_inl_defd_rw_get_size_a
#undef mk_sl_dynamic_ring_inl_defd_rw_get_sise_a
#undef mk_sl_dynamic_ring_inl_defd_rw_get_data_a
#undef mk_sl_dynamic_ring_inl_defd_rw_get_size_b
#undef mk_sl_dynamic_ring_inl_defd_rw_get_sise_b
#undef mk_sl_dynamic_ring_inl_defd_rw_get_data_b
#undef mk_sl_dynamic_ring_inl_defd_rw_get_free_size_a
#undef mk_sl_dynamic_ring_inl_defd_rw_get_free_data_a
#undef mk_sl_dynamic_ring_inl_defd_rw_get_free_size_b
#undef mk_sl_dynamic_ring_inl_defd_rw_get_free_data_b

#undef mk_sl_dynamic_ring_inl_defd_rw_construct
#undef mk_sl_dynamic_ring_inl_defd_rw_construct_copy
#undef mk_sl_dynamic_ring_inl_defd_rw_construct_move
#undef mk_sl_dynamic_ring_inl_defd_rw_destroy
#undef mk_sl_dynamic_ring_inl_defd_rw_assign_copy
#undef mk_sl_dynamic_ring_inl_defd_rw_assign_move
#undef mk_sl_dynamic_ring_inl_defd_rw_reserve_at_least
#undef mk_sl_dynamic_ring_inl_defd_rw_reserve_additional
#undef mk_sl_dynamic_ring_inl_defd_rw_clear
#undef mk_sl_dynamic_ring_inl_defd_rw_consolidate
#undef mk_sl_dynamic_ring_inl_defd_rw_push_back_void
#undef mk_sl_dynamic_ring_inl_defd_rw_push_back_move_many
#undef mk_sl_dynamic_ring_inl_defd_rw_push_back_copy_many
#undef mk_sl_dynamic_ring_inl_defd_rw_push_back_move_single
#undef mk_sl_dynamic_ring_inl_defd_rw_push_back_copy_single
#undef mk_sl_dynamic_ring_inl_defd_rw_push_front_move_many
#undef mk_sl_dynamic_ring_inl_defd_rw_push_front_copy_many
#undef mk_sl_dynamic_ring_inl_defd_rw_push_front_move_single
#undef mk_sl_dynamic_ring_inl_defd_rw_push_front_copy_single
#undef mk_sl_dynamic_ring_inl_defd_rw_pop_back_many
#undef mk_sl_dynamic_ring_inl_defd_rw_pop_back_single
#undef mk_sl_dynamic_ring_inl_defd_rw_pop_front_many
#undef mk_sl_dynamic_ring_inl_defd_rw_pop_front_single
#undef mk_sl_dynamic_ring_inl_defd_rw_erase_at
#undef mk_sl_dynamic_ring_inl_defd_rw_erase_element
#undef mk_sl_dynamic_ring_inl_defd_rw_erase_value
