#undef mk_sl_speed_counter_inl_defd_name
#undef mk_sl_speed_counter_inl_defd_item_prefix
#undef mk_sl_speed_counter_inl_defd_time_prefix
#undef mk_sl_speed_counter_inl_defd_time_denominator
#undef mk_sl_speed_counter_inl_defd_time_granule_size
#undef mk_sl_speed_counter_inl_defd_time_granule_count

#undef mk_sl_speed_counter_inl_defd_prefix

#undef mk_sl_speed_counter_inl_defd_s
#undef mk_sl_speed_counter_inl_defd_t
#undef mk_sl_speed_counter_inl_defd_ct
#undef mk_sl_speed_counter_inl_defd_pt
#undef mk_sl_speed_counter_inl_defd_pct

#undef mk_sl_speed_counter_inl_defd_construct
#undef mk_sl_speed_counter_inl_defd_count
#undef mk_sl_speed_counter_inl_defd_get_time_quantized
#undef mk_sl_speed_counter_inl_defd_get_speed

#undef mk_sl_speed_counter_inl_defd_item_t
#undef mk_sl_speed_counter_inl_defd_item_ct
#undef mk_sl_speed_counter_inl_defd_item_pt
#undef mk_sl_speed_counter_inl_defd_item_pct
#undef mk_sl_speed_counter_inl_defd_item_memmove
#undef mk_sl_speed_counter_inl_defd_item_set_zero
#undef mk_sl_speed_counter_inl_defd_item_to_bi_uint
#undef mk_sl_speed_counter_inl_defd_item_from_bi_uint
#undef mk_sl_speed_counter_inl_defd_item_is_max
#undef mk_sl_speed_counter_inl_defd_item_shr3
#undef mk_sl_speed_counter_inl_defd_item_inc1
#undef mk_sl_speed_counter_inl_defd_item_would_overflow_add_cc
#undef mk_sl_speed_counter_inl_defd_item_add2_wrap_cid_cod
#undef mk_sl_speed_counter_inl_defd_item_add3_wrap_cid_cod
#undef mk_sl_speed_counter_inl_defd_item_mul3_wrap_lo

#undef mk_sl_speed_counter_inl_defd_time_t
#undef mk_sl_speed_counter_inl_defd_time_ct
#undef mk_sl_speed_counter_inl_defd_time_pt
#undef mk_sl_speed_counter_inl_defd_time_pct
#undef mk_sl_speed_counter_inl_defd_time_set_zero
#undef mk_sl_speed_counter_inl_defd_time_to_bi_ulllong
#undef mk_sl_speed_counter_inl_defd_time_from_bi_ulllong
#undef mk_sl_speed_counter_inl_defd_time_sub3_wrap_cid_cod
#undef mk_sl_speed_counter_inl_defd_time_div3_wrap
