#undef mk_sl_vector_inl_defd_vector_s
#undef mk_sl_vector_inl_defd_vector_t
#undef mk_sl_vector_inl_defd_vector_ct
#undef mk_sl_vector_inl_defd_vector_pt
#undef mk_sl_vector_inl_defd_vector_pct

#undef mk_sl_vector_inl_defd_vector_ro_destroy
#undef mk_sl_vector_inl_defd_vector_ro_is_empty
#undef mk_sl_vector_inl_defd_vector_ro_get_count
#undef mk_sl_vector_inl_defd_vector_ro_get_capacity
#undef mk_sl_vector_inl_defd_vector_ro_get_data
#undef mk_sl_vector_inl_defd_vector_ro_get_data_at

#undef mk_sl_vector_inl_defd_vector_rw_construct
#undef mk_sl_vector_inl_defd_vector_rw_destroy
#undef mk_sl_vector_inl_defd_vector_rw_is_empty
#undef mk_sl_vector_inl_defd_vector_rw_get_count
#undef mk_sl_vector_inl_defd_vector_rw_get_capacity
#undef mk_sl_vector_inl_defd_vector_rw_get_data
#undef mk_sl_vector_inl_defd_vector_rw_get_data_at
#undef mk_sl_vector_inl_defd_vector_rw_reserve
#undef mk_sl_vector_inl_defd_vector_rw_clear


#undef mk_sl_vector_inl_defd_elem_t
#undef mk_sl_vector_inl_defd_elem_ct
#undef mk_sl_vector_inl_defd_elem_pt
#undef mk_sl_vector_inl_defd_elem_pct


#undef mk_sl_vector_inl_defd_buffer_t

#undef mk_sl_vector_inl_defd_buffer_ro_get_size
#undef mk_sl_vector_inl_defd_buffer_ro_get_data
#undef mk_sl_vector_inl_defd_buffer_ro_get_data_at
#undef mk_sl_vector_inl_defd_buffer_ro_destroy
#undef mk_sl_vector_inl_defd_buffer_ro_get_size

#undef mk_sl_vector_inl_defd_buffer_rw_construct
#undef mk_sl_vector_inl_defd_buffer_rw_destroy
#undef mk_sl_vector_inl_defd_buffer_rw_get_size
#undef mk_sl_vector_inl_defd_buffer_rw_get_data_at
#undef mk_sl_vector_inl_defd_buffer_rw_resize
#undef mk_sl_vector_inl_defd_buffer_rw_push_back_from_capacity_one
#undef mk_sl_vector_inl_defd_buffer_rw_pop_back_one
