#ifndef mk_include_guard_mk_sl_mallocator_lang_c89_h
#define mk_include_guard_mk_sl_mallocator_lang_c89_h


#include "mk_lang_bui.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_static_param.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"


#define mk_sl_cui_t_name mk_sl_mallocator_lang_c89_blocks
#define mk_sl_cui_t_base_type_name mk_lang_bui_usize
#define mk_sl_cui_t_count 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"
#define mk_sl_mallocator_lang_c89_blocks_size_bits_d mk_lang_bui_usize_size_bits_d

#define mk_sl_cui_t_name mk_sl_mallocator_lang_c89_bytes
#define mk_sl_cui_t_base_type_name mk_lang_bui_usize
#define mk_sl_cui_t_count 1
#include "mk_sl_cui_inl_fileh.h"
#include "mk_sl_cui_inl_fileu.h"
#define mk_sl_mallocator_lang_c89_bytes_size_bits_d mk_lang_bui_usize_size_bits_d


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_lang_c89_init(mk_lang_types_void_t) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_lang_c89_deinit(mk_lang_types_void_t) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_lang_c89_allocate(mk_lang_types_usize_t const size_bytes, mk_lang_types_void_ppt const mem) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_lang_c89_deallocate(mk_lang_types_void_pt const mem, mk_lang_types_usize_t const size_bytes) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_mallocator_lang_c89_reallocate(mk_lang_types_void_pt const old_mem, mk_lang_types_usize_t const old_size_bytes, mk_lang_types_usize_t const new_size_bytes, mk_lang_types_void_ppt const new_mem) mk_lang_noexcept;

mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lang_c89_statistics_get_blocks_allocated(mk_sl_mallocator_lang_c89_blocks_pt const blocks_allocated) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lang_c89_statistics_get_blocks_dealocated(mk_sl_mallocator_lang_c89_blocks_pt const blocks_deallocated) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lang_c89_statistics_get_blocks_peak(mk_sl_mallocator_lang_c89_blocks_pt const blocks_peak) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lang_c89_statistics_get_blocks_live(mk_sl_mallocator_lang_c89_blocks_pt const blocks_live) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lang_c89_statistics_get_bytes_allocated(mk_sl_mallocator_lang_c89_bytes_pt const bytes_allocated) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lang_c89_statistics_get_bytes_dealocated(mk_sl_mallocator_lang_c89_bytes_pt const bytes_deallocated) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lang_c89_statistics_get_bytes_peak(mk_sl_mallocator_lang_c89_bytes_pt const bytes_peak) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lang_c89_statistics_get_bytes_live(mk_sl_mallocator_lang_c89_bytes_pt const bytes_live) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_sl_mallocator_lang_c89_statistics_get_all(mk_lang_static_param(mk_sl_mallocator_lang_c89_blocks_t, blocks_all, 4), mk_lang_static_param(mk_sl_mallocator_lang_c89_bytes_t, bytes_all, 4)) mk_lang_noexcept;


#if mk_lang_jumbo_have
#include "mk_sl_mallocator_lang_c89.c"
#endif
#endif
