#include "mk_lang_concat.h"
#include "mk_lang_limits.h"
#include "mk_lang_types.h"
#include "mk_sl_fixed_vector_copy.h"


#if(!( \
	(defined mk_sl_fixed_vector_t_name) && \
	(defined mk_sl_fixed_vector_t_element_type) && \
	(defined mk_sl_fixed_vector_t_capacity && (mk_sl_fixed_vector_t_capacity) >= 1 && (mk_sl_fixed_vector_t_capacity) <= 1 * 1024 * 1024 * 1024) && \
	((defined mk_sl_fixed_vector_t_copy_style && ((mk_sl_fixed_vector_t_copy_style) == mk_sl_fixed_vector_copy_use_bitblt || (mk_sl_fixed_vector_t_copy_style) == mk_sl_fixed_vector_copy_use_custom)) || !defined mk_sl_fixed_vector_t_copy_style) && \
	(defined mk_sl_fixed_vector_t_element_construct_void || !defined mk_sl_fixed_vector_t_element_construct_void) && \
	(defined mk_sl_fixed_vector_t_element_destroy || !defined mk_sl_fixed_vector_t_element_destroy) && \
	(defined mk_sl_fixed_vector_t_element_construct_copy || !defined mk_sl_fixed_vector_t_element_construct_copy) && \
	(defined mk_sl_fixed_vector_t_element_construct_move || !defined mk_sl_fixed_vector_t_element_construct_move) && \
	(defined mk_sl_fixed_vector_t_element_assign_copy || !defined mk_sl_fixed_vector_t_element_assign_copy) && \
	(defined mk_sl_fixed_vector_t_element_assign_move || !defined mk_sl_fixed_vector_t_element_assign_move) && \
	(defined mk_sl_fixed_vector_t_element_eq || !defined mk_sl_fixed_vector_t_element_eq) && \
1))
#error xxxxxxxxxx
#endif


#if( \
	defined mk_sl_fixed_vector_t_element_construct_void || \
	defined mk_sl_fixed_vector_t_element_destroy || \
0)
#if(!( \
	defined mk_sl_fixed_vector_t_element_construct_void && \
	defined mk_sl_fixed_vector_t_element_destroy && \
1))
#error xxxxxxxxxx
#endif
#endif

#if( \
	defined mk_sl_fixed_vector_t_element_construct_copy || \
	defined mk_sl_fixed_vector_t_element_assign_copy || \
0)
#if(!( \
	defined mk_sl_fixed_vector_t_element_construct_copy && \
	defined mk_sl_fixed_vector_t_element_assign_copy && \
1))
#error xxxxxxxxxx
#endif
#endif

#if( \
	defined mk_sl_fixed_vector_t_element_construct_move || \
	defined mk_sl_fixed_vector_t_element_assign_move || \
0)
#if(!( \
	defined mk_sl_fixed_vector_t_element_construct_move && \
	defined mk_sl_fixed_vector_t_element_assign_move && \
1))
#error xxxxxxxxxx
#endif
#endif


#define mk_sl_fixed_vector_inl_defd_name mk_sl_fixed_vector_t_name
#define mk_sl_fixed_vector_inl_defd_element_type mk_sl_fixed_vector_t_element_type
#define mk_sl_fixed_vector_inl_defd_capacity (mk_sl_fixed_vector_t_capacity)

#if defined mk_sl_fixed_vector_t_copy_style
#define mk_sl_fixed_vector_inl_defd_copy_style (mk_sl_fixed_vector_t_copy_style)
#else
#if defined mk_sl_fixed_vector_t_element_construct_copy && defined mk_sl_fixed_vector_t_element_assign_copy
#define mk_sl_fixed_vector_inl_defd_copy_style mk_sl_fixed_vector_copy_use_custom
#else
#if defined mk_sl_fixed_vector_t_element_construct_move && defined mk_sl_fixed_vector_t_element_assign_move
#define mk_sl_fixed_vector_inl_defd_copy_style mk_sl_fixed_vector_copy_use_custom
#else
#define mk_sl_fixed_vector_inl_defd_copy_style mk_sl_fixed_vector_copy_use_bitblt
#endif
#endif
#endif

#if defined mk_sl_fixed_vector_t_element_construct_void && defined mk_sl_fixed_vector_t_element_destroy
#define mk_sl_fixed_vector_inl_defd_element_construct_destroy_has 1
#define mk_sl_fixed_vector_inl_defd_element_construct_void mk_sl_fixed_vector_t_element_construct_void
#define mk_sl_fixed_vector_inl_defd_element_destroy mk_sl_fixed_vector_t_element_destroy
#else
#define mk_sl_fixed_vector_inl_defd_element_construct_destroy_has 0
#endif

#if defined mk_sl_fixed_vector_t_element_construct_copy && defined mk_sl_fixed_vector_t_element_assign_copy
#define mk_sl_fixed_vector_inl_defd_element_copy_has 1
#define mk_sl_fixed_vector_inl_defd_element_construct_copy(a, b) mk_sl_fixed_vector_t_element_construct_copy((a), (b))
#define mk_sl_fixed_vector_inl_defd_element_assign_copy(a, b) mk_sl_fixed_vector_t_element_assign_copy((a), (b))
#else
#define mk_sl_fixed_vector_inl_defd_element_copy_has 0
#endif

#if defined mk_sl_fixed_vector_t_element_construct_move && defined mk_sl_fixed_vector_t_element_assign_move
#define mk_sl_fixed_vector_inl_defd_element_move_has 1
#define mk_sl_fixed_vector_inl_defd_element_construct_move(a, b) mk_sl_fixed_vector_t_element_construct_move((a), (b))
#define mk_sl_fixed_vector_inl_defd_element_assign_move(a, b) mk_sl_fixed_vector_t_element_assign_move((a), (b))
#else
#define mk_sl_fixed_vector_inl_defd_element_move_has 0
#endif

#if defined mk_sl_fixed_vector_t_element_eq
#define mk_sl_fixed_vector_inl_defd_element_eq_has 1
#define mk_sl_fixed_vector_inl_defd_element_eq_fn mk_sl_fixed_vector_t_element_eq
#else
#define mk_sl_fixed_vector_inl_defd_element_eq_has 0
#endif





#define mk_sl_fixed_vector_inl_defd_element_prefix mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _element)

#define mk_sl_fixed_vector_inl_defd_element_s mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _s)
#define mk_sl_fixed_vector_inl_defd_element_t mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _t)
#define mk_sl_fixed_vector_inl_defd_element_ct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _ct)
#define mk_sl_fixed_vector_inl_defd_element_vt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _vt)
#define mk_sl_fixed_vector_inl_defd_element_cvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _cvt)
#define mk_sl_fixed_vector_inl_defd_element_pt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _pt)
#define mk_sl_fixed_vector_inl_defd_element_pct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _pct)
#define mk_sl_fixed_vector_inl_defd_element_pvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _pvt)
#define mk_sl_fixed_vector_inl_defd_element_pcvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _pcvt)
#define mk_sl_fixed_vector_inl_defd_element_prt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _prt)
#define mk_sl_fixed_vector_inl_defd_element_prct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _prct)
#define mk_sl_fixed_vector_inl_defd_element_prvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _prvt)
#define mk_sl_fixed_vector_inl_defd_element_prcvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _prcvt)
#define mk_sl_fixed_vector_inl_defd_element_lpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lpt)
#define mk_sl_fixed_vector_inl_defd_element_lpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lpct)
#define mk_sl_fixed_vector_inl_defd_element_lpvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lpvt)
#define mk_sl_fixed_vector_inl_defd_element_lpcvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lpcvt)
#define mk_sl_fixed_vector_inl_defd_element_lprt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lprt)
#define mk_sl_fixed_vector_inl_defd_element_lprct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lprct)
#define mk_sl_fixed_vector_inl_defd_element_lprvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lprvt)
#define mk_sl_fixed_vector_inl_defd_element_lprcvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lprcvt)
#define mk_sl_fixed_vector_inl_defd_element_npt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _npt)
#define mk_sl_fixed_vector_inl_defd_element_npct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _npct)
#define mk_sl_fixed_vector_inl_defd_element_npvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _npvt)
#define mk_sl_fixed_vector_inl_defd_element_npcvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _npcvt)
#define mk_sl_fixed_vector_inl_defd_element_nprt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nprt)
#define mk_sl_fixed_vector_inl_defd_element_nprct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nprct)
#define mk_sl_fixed_vector_inl_defd_element_nprvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nprvt)
#define mk_sl_fixed_vector_inl_defd_element_nprcvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nprcvt)
#define mk_sl_fixed_vector_inl_defd_element_cpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _cpt)
#define mk_sl_fixed_vector_inl_defd_element_vpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _vpt)
#define mk_sl_fixed_vector_inl_defd_element_cvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _cvpt)
#define mk_sl_fixed_vector_inl_defd_element_ppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _ppt)
#define mk_sl_fixed_vector_inl_defd_element_pcpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _pcpt)
#define mk_sl_fixed_vector_inl_defd_element_pvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _pvpt)
#define mk_sl_fixed_vector_inl_defd_element_pcvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _pcvpt)
#define mk_sl_fixed_vector_inl_defd_element_prpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _prpt)
#define mk_sl_fixed_vector_inl_defd_element_prcpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _prcpt)
#define mk_sl_fixed_vector_inl_defd_element_prvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _prvpt)
#define mk_sl_fixed_vector_inl_defd_element_prcvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _prcvpt)
#define mk_sl_fixed_vector_inl_defd_element_lppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lppt)
#define mk_sl_fixed_vector_inl_defd_element_lpcpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lpcpt)
#define mk_sl_fixed_vector_inl_defd_element_lpvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lpvpt)
#define mk_sl_fixed_vector_inl_defd_element_lpcvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lpcvpt)
#define mk_sl_fixed_vector_inl_defd_element_lprpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lprpt)
#define mk_sl_fixed_vector_inl_defd_element_lprcpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lprcpt)
#define mk_sl_fixed_vector_inl_defd_element_lprvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lprvpt)
#define mk_sl_fixed_vector_inl_defd_element_lprcvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lprcvpt)
#define mk_sl_fixed_vector_inl_defd_element_nppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nppt)
#define mk_sl_fixed_vector_inl_defd_element_npcpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _npcpt)
#define mk_sl_fixed_vector_inl_defd_element_npvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _npvpt)
#define mk_sl_fixed_vector_inl_defd_element_npcvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _npcvpt)
#define mk_sl_fixed_vector_inl_defd_element_nprpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nprpt)
#define mk_sl_fixed_vector_inl_defd_element_nprcpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nprcpt)
#define mk_sl_fixed_vector_inl_defd_element_nprvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nprvpt)
#define mk_sl_fixed_vector_inl_defd_element_nprcvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nprcvpt)
#define mk_sl_fixed_vector_inl_defd_element_cpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _cpct)
#define mk_sl_fixed_vector_inl_defd_element_vpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _vpct)
#define mk_sl_fixed_vector_inl_defd_element_cvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _cvpct)
#define mk_sl_fixed_vector_inl_defd_element_ppct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _ppct)
#define mk_sl_fixed_vector_inl_defd_element_pcpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _pcpct)
#define mk_sl_fixed_vector_inl_defd_element_pvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _pvpct)
#define mk_sl_fixed_vector_inl_defd_element_pcvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _pcvpct)
#define mk_sl_fixed_vector_inl_defd_element_prpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _prpct)
#define mk_sl_fixed_vector_inl_defd_element_prcpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _prcpct)
#define mk_sl_fixed_vector_inl_defd_element_prvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _prvpct)
#define mk_sl_fixed_vector_inl_defd_element_prcvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _prcvpct)
#define mk_sl_fixed_vector_inl_defd_element_lppct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lppct)
#define mk_sl_fixed_vector_inl_defd_element_lpcpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lpcpct)
#define mk_sl_fixed_vector_inl_defd_element_lpvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lpvpct)
#define mk_sl_fixed_vector_inl_defd_element_lpcvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lpcvpct)
#define mk_sl_fixed_vector_inl_defd_element_lprpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lprpct)
#define mk_sl_fixed_vector_inl_defd_element_lprcpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lprcpct)
#define mk_sl_fixed_vector_inl_defd_element_lprvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lprvpct)
#define mk_sl_fixed_vector_inl_defd_element_lprcvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lprcvpct)
#define mk_sl_fixed_vector_inl_defd_element_nppct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nppct)
#define mk_sl_fixed_vector_inl_defd_element_npcpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _npcpct)
#define mk_sl_fixed_vector_inl_defd_element_npvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _npvpct)
#define mk_sl_fixed_vector_inl_defd_element_npcvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _npcvpct)
#define mk_sl_fixed_vector_inl_defd_element_nprpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nprpct)
#define mk_sl_fixed_vector_inl_defd_element_nprcpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nprcpct)
#define mk_sl_fixed_vector_inl_defd_element_nprvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nprvpct)
#define mk_sl_fixed_vector_inl_defd_element_nprcvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nprcvpct)
#define mk_sl_fixed_vector_inl_defd_element_cppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _cppt)
#define mk_sl_fixed_vector_inl_defd_element_vppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _vppt)
#define mk_sl_fixed_vector_inl_defd_element_cvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _cvppt)
#define mk_sl_fixed_vector_inl_defd_element_pppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _pppt)
#define mk_sl_fixed_vector_inl_defd_element_pcppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _pcppt)
#define mk_sl_fixed_vector_inl_defd_element_pvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _pvppt)
#define mk_sl_fixed_vector_inl_defd_element_pcvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _pcvppt)
#define mk_sl_fixed_vector_inl_defd_element_prppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _prppt)
#define mk_sl_fixed_vector_inl_defd_element_prcppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _prcppt)
#define mk_sl_fixed_vector_inl_defd_element_prvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _prvppt)
#define mk_sl_fixed_vector_inl_defd_element_prcvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _prcvppt)
#define mk_sl_fixed_vector_inl_defd_element_lpppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lpppt)
#define mk_sl_fixed_vector_inl_defd_element_lpcppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lpcppt)
#define mk_sl_fixed_vector_inl_defd_element_lpvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lpvppt)
#define mk_sl_fixed_vector_inl_defd_element_lpcvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lpcvppt)
#define mk_sl_fixed_vector_inl_defd_element_lprppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lprppt)
#define mk_sl_fixed_vector_inl_defd_element_lprcppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lprcppt)
#define mk_sl_fixed_vector_inl_defd_element_lprvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lprvppt)
#define mk_sl_fixed_vector_inl_defd_element_lprcvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _lprcvppt)
#define mk_sl_fixed_vector_inl_defd_element_npppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _npppt)
#define mk_sl_fixed_vector_inl_defd_element_npcppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _npcppt)
#define mk_sl_fixed_vector_inl_defd_element_npvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _npvppt)
#define mk_sl_fixed_vector_inl_defd_element_npcvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _npcvppt)
#define mk_sl_fixed_vector_inl_defd_element_nprppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nprppt)
#define mk_sl_fixed_vector_inl_defd_element_nprcppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nprcppt)
#define mk_sl_fixed_vector_inl_defd_element_nprvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nprvppt)
#define mk_sl_fixed_vector_inl_defd_element_nprcvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_element_prefix, _nprcvppt)

#define mk_sl_fixed_vector_inl_defd_s mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _s)
#define mk_sl_fixed_vector_inl_defd_t mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _t)
#define mk_sl_fixed_vector_inl_defd_ct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ct)
#define mk_sl_fixed_vector_inl_defd_vt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _vt)
#define mk_sl_fixed_vector_inl_defd_cvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _cvt)
#define mk_sl_fixed_vector_inl_defd_pt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _pt)
#define mk_sl_fixed_vector_inl_defd_pct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _pct)
#define mk_sl_fixed_vector_inl_defd_pvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _pvt)
#define mk_sl_fixed_vector_inl_defd_pcvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _pcvt)
#define mk_sl_fixed_vector_inl_defd_prt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prt)
#define mk_sl_fixed_vector_inl_defd_prct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prct)
#define mk_sl_fixed_vector_inl_defd_prvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prvt)
#define mk_sl_fixed_vector_inl_defd_prcvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prcvt)
#define mk_sl_fixed_vector_inl_defd_lpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lpt)
#define mk_sl_fixed_vector_inl_defd_lpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lpct)
#define mk_sl_fixed_vector_inl_defd_lpvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lpvt)
#define mk_sl_fixed_vector_inl_defd_lpcvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lpcvt)
#define mk_sl_fixed_vector_inl_defd_lprt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lprt)
#define mk_sl_fixed_vector_inl_defd_lprct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lprct)
#define mk_sl_fixed_vector_inl_defd_lprvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lprvt)
#define mk_sl_fixed_vector_inl_defd_lprcvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lprcvt)
#define mk_sl_fixed_vector_inl_defd_npt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _npt)
#define mk_sl_fixed_vector_inl_defd_npct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _npct)
#define mk_sl_fixed_vector_inl_defd_npvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _npvt)
#define mk_sl_fixed_vector_inl_defd_npcvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _npcvt)
#define mk_sl_fixed_vector_inl_defd_nprt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nprt)
#define mk_sl_fixed_vector_inl_defd_nprct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nprct)
#define mk_sl_fixed_vector_inl_defd_nprvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nprvt)
#define mk_sl_fixed_vector_inl_defd_nprcvt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nprcvt)
#define mk_sl_fixed_vector_inl_defd_cpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _cpt)
#define mk_sl_fixed_vector_inl_defd_vpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _vpt)
#define mk_sl_fixed_vector_inl_defd_cvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _cvpt)
#define mk_sl_fixed_vector_inl_defd_ppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ppt)
#define mk_sl_fixed_vector_inl_defd_pcpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _pcpt)
#define mk_sl_fixed_vector_inl_defd_pvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _pvpt)
#define mk_sl_fixed_vector_inl_defd_pcvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _pcvpt)
#define mk_sl_fixed_vector_inl_defd_prpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prpt)
#define mk_sl_fixed_vector_inl_defd_prcpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prcpt)
#define mk_sl_fixed_vector_inl_defd_prvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prvpt)
#define mk_sl_fixed_vector_inl_defd_prcvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prcvpt)
#define mk_sl_fixed_vector_inl_defd_lppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lppt)
#define mk_sl_fixed_vector_inl_defd_lpcpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lpcpt)
#define mk_sl_fixed_vector_inl_defd_lpvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lpvpt)
#define mk_sl_fixed_vector_inl_defd_lpcvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lpcvpt)
#define mk_sl_fixed_vector_inl_defd_lprpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lprpt)
#define mk_sl_fixed_vector_inl_defd_lprcpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lprcpt)
#define mk_sl_fixed_vector_inl_defd_lprvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lprvpt)
#define mk_sl_fixed_vector_inl_defd_lprcvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lprcvpt)
#define mk_sl_fixed_vector_inl_defd_nppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nppt)
#define mk_sl_fixed_vector_inl_defd_npcpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _npcpt)
#define mk_sl_fixed_vector_inl_defd_npvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _npvpt)
#define mk_sl_fixed_vector_inl_defd_npcvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _npcvpt)
#define mk_sl_fixed_vector_inl_defd_nprpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nprpt)
#define mk_sl_fixed_vector_inl_defd_nprcpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nprcpt)
#define mk_sl_fixed_vector_inl_defd_nprvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nprvpt)
#define mk_sl_fixed_vector_inl_defd_nprcvpt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nprcvpt)
#define mk_sl_fixed_vector_inl_defd_cpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _cpct)
#define mk_sl_fixed_vector_inl_defd_vpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _vpct)
#define mk_sl_fixed_vector_inl_defd_cvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _cvpct)
#define mk_sl_fixed_vector_inl_defd_ppct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ppct)
#define mk_sl_fixed_vector_inl_defd_pcpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _pcpct)
#define mk_sl_fixed_vector_inl_defd_pvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _pvpct)
#define mk_sl_fixed_vector_inl_defd_pcvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _pcvpct)
#define mk_sl_fixed_vector_inl_defd_prpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prpct)
#define mk_sl_fixed_vector_inl_defd_prcpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prcpct)
#define mk_sl_fixed_vector_inl_defd_prvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prvpct)
#define mk_sl_fixed_vector_inl_defd_prcvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prcvpct)
#define mk_sl_fixed_vector_inl_defd_lppct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lppct)
#define mk_sl_fixed_vector_inl_defd_lpcpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lpcpct)
#define mk_sl_fixed_vector_inl_defd_lpvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lpvpct)
#define mk_sl_fixed_vector_inl_defd_lpcvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lpcvpct)
#define mk_sl_fixed_vector_inl_defd_lprpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lprpct)
#define mk_sl_fixed_vector_inl_defd_lprcpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lprcpct)
#define mk_sl_fixed_vector_inl_defd_lprvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lprvpct)
#define mk_sl_fixed_vector_inl_defd_lprcvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lprcvpct)
#define mk_sl_fixed_vector_inl_defd_nppct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nppct)
#define mk_sl_fixed_vector_inl_defd_npcpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _npcpct)
#define mk_sl_fixed_vector_inl_defd_npvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _npvpct)
#define mk_sl_fixed_vector_inl_defd_npcvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _npcvpct)
#define mk_sl_fixed_vector_inl_defd_nprpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nprpct)
#define mk_sl_fixed_vector_inl_defd_nprcpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nprcpct)
#define mk_sl_fixed_vector_inl_defd_nprvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nprvpct)
#define mk_sl_fixed_vector_inl_defd_nprcvpct mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nprcvpct)
#define mk_sl_fixed_vector_inl_defd_cppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _cppt)
#define mk_sl_fixed_vector_inl_defd_vppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _vppt)
#define mk_sl_fixed_vector_inl_defd_cvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _cvppt)
#define mk_sl_fixed_vector_inl_defd_pppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _pppt)
#define mk_sl_fixed_vector_inl_defd_pcppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _pcppt)
#define mk_sl_fixed_vector_inl_defd_pvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _pvppt)
#define mk_sl_fixed_vector_inl_defd_pcvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _pcvppt)
#define mk_sl_fixed_vector_inl_defd_prppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prppt)
#define mk_sl_fixed_vector_inl_defd_prcppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prcppt)
#define mk_sl_fixed_vector_inl_defd_prvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prvppt)
#define mk_sl_fixed_vector_inl_defd_prcvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prcvppt)
#define mk_sl_fixed_vector_inl_defd_lpppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lpppt)
#define mk_sl_fixed_vector_inl_defd_lpcppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lpcppt)
#define mk_sl_fixed_vector_inl_defd_lpvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lpvppt)
#define mk_sl_fixed_vector_inl_defd_lpcvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lpcvppt)
#define mk_sl_fixed_vector_inl_defd_lprppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lprppt)
#define mk_sl_fixed_vector_inl_defd_lprcppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lprcppt)
#define mk_sl_fixed_vector_inl_defd_lprvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lprvppt)
#define mk_sl_fixed_vector_inl_defd_lprcvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _lprcvppt)
#define mk_sl_fixed_vector_inl_defd_npppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _npppt)
#define mk_sl_fixed_vector_inl_defd_npcppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _npcppt)
#define mk_sl_fixed_vector_inl_defd_npvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _npvppt)
#define mk_sl_fixed_vector_inl_defd_npcvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _npcvppt)
#define mk_sl_fixed_vector_inl_defd_nprppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nprppt)
#define mk_sl_fixed_vector_inl_defd_nprcppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nprcppt)
#define mk_sl_fixed_vector_inl_defd_nprvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nprvppt)
#define mk_sl_fixed_vector_inl_defd_nprcvppt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _nprcvppt)





#define mk_sl_fixed_vector_inl_defd_prrw_element_bitblt mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_element_assign_bitblt)
#define mk_sl_fixed_vector_inl_defd_prrw_element_construct_void mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_element_construct_void)
#define mk_sl_fixed_vector_inl_defd_prrw_element_destroy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_element_destroy)
#define mk_sl_fixed_vector_inl_defd_prrw_element_construct_copy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_element_construct_copy)
#define mk_sl_fixed_vector_inl_defd_prrw_element_construct_move mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_element_construct_move)
#define mk_sl_fixed_vector_inl_defd_prrw_element_assign_copy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_element_assign_copy)
#define mk_sl_fixed_vector_inl_defd_prrw_element_assign_move mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_element_assign_move)
#define mk_sl_fixed_vector_inl_defd_prrw_element_eq mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_element_eq)

#define mk_sl_fixed_vector_inl_defd_prro_verify_invariants mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_verify_invariants)

#define mk_sl_fixed_vector_inl_defd_prst_max_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prst_max_capacity)
#define mk_sl_fixed_vector_inl_defd_prro_max_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_max_capacity)
#define mk_sl_fixed_vector_inl_defd_prro_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_capacity)
#define mk_sl_fixed_vector_inl_defd_prro_size mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_size)
#define mk_sl_fixed_vector_inl_defd_prro_sise mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_sise)
#define mk_sl_fixed_vector_inl_defd_prro_free mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_free)
#define mk_sl_fixed_vector_inl_defd_prro_is_empty mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_is_empty)
#define mk_sl_fixed_vector_inl_defd_prro_is_full mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_is_full)
#define mk_sl_fixed_vector_inl_defd_prro_data mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_data)
#define mk_sl_fixed_vector_inl_defd_prro_at mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_at)
#define mk_sl_fixed_vector_inl_defd_prro_front mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_front)
#define mk_sl_fixed_vector_inl_defd_prro_back mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_back)
#define mk_sl_fixed_vector_inl_defd_prro_eq mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_eq)
#define mk_sl_fixed_vector_inl_defd_prro_ne mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prro_ne)

#define mk_sl_fixed_vector_inl_defd_prrw_max_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_max_capacity)
#define mk_sl_fixed_vector_inl_defd_prrw_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_capacity)
#define mk_sl_fixed_vector_inl_defd_prrw_size mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_size)
#define mk_sl_fixed_vector_inl_defd_prrw_sise mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_sise)
#define mk_sl_fixed_vector_inl_defd_prrw_free mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_free)
#define mk_sl_fixed_vector_inl_defd_prrw_is_empty mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_is_empty)
#define mk_sl_fixed_vector_inl_defd_prrw_is_full mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_is_full)
#define mk_sl_fixed_vector_inl_defd_prrw_data mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_data)
#define mk_sl_fixed_vector_inl_defd_prrw_at mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_at)
#define mk_sl_fixed_vector_inl_defd_prrw_front mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_front)
#define mk_sl_fixed_vector_inl_defd_prrw_back mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_back)
#define mk_sl_fixed_vector_inl_defd_prrw_eq mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_eq)
#define mk_sl_fixed_vector_inl_defd_prrw_ne mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_ne)

#define mk_sl_fixed_vector_inl_defd_prrw_elements_construct_void_from_to mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_construct_void_from_to)
#define mk_sl_fixed_vector_inl_defd_prrw_elements_destroy_from_to mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_destroy_from_to)
#define mk_sl_fixed_vector_inl_defd_prrw_elements_construct_void_last mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_construct_void_last)
#define mk_sl_fixed_vector_inl_defd_prrw_elements_destroy_last mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_destroy_last)
#define mk_sl_fixed_vector_inl_defd_prrw_elements_destroy_all mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_destroy_all)
#define mk_sl_fixed_vector_inl_defd_prrw_elements_construct_copy_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_construct_copy_many)
#define mk_sl_fixed_vector_inl_defd_prrw_elements_construct_move_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_construct_move_many)
#define mk_sl_fixed_vector_inl_defd_prrw_elements_assign_copy_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_assign_copy_many)
#define mk_sl_fixed_vector_inl_defd_prrw_elements_assign_move_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_elements_assign_move_many)

#define mk_sl_fixed_vector_inl_defd_prrw_construct_void mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_construct_void)
#define mk_sl_fixed_vector_inl_defd_prrw_destroy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_destroy)
#define mk_sl_fixed_vector_inl_defd_prrw_construct_copy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_construct_copy)
#define mk_sl_fixed_vector_inl_defd_prrw_construct_move mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_construct_move)
#define mk_sl_fixed_vector_inl_defd_prrw_assign_copy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_assign_copy)
#define mk_sl_fixed_vector_inl_defd_prrw_assign_move mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_assign_move)
#define mk_sl_fixed_vector_inl_defd_prrw_reserve_at_least mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_reserve_at_least)
#define mk_sl_fixed_vector_inl_defd_prrw_reserve_additional mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_reserve_additional)
#define mk_sl_fixed_vector_inl_defd_prrw_shrink_by mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_shrink_by)
#define mk_sl_fixed_vector_inl_defd_prrw_resize_to mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_resize_to)
#define mk_sl_fixed_vector_inl_defd_prrw_grow_by mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_grow_by)
#define mk_sl_fixed_vector_inl_defd_prrw_clear mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_clear)
#define mk_sl_fixed_vector_inl_defd_prrw_push_back_copy_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_push_back_copy_many)
#define mk_sl_fixed_vector_inl_defd_prrw_push_back_move_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_push_back_move_many)
#define mk_sl_fixed_vector_inl_defd_prrw_push_back_copy_single mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_push_back_copy_single)
#define mk_sl_fixed_vector_inl_defd_prrw_push_back_move_single mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_push_back_move_single)
#define mk_sl_fixed_vector_inl_defd_prrw_pop_back_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_pop_back_many)
#define mk_sl_fixed_vector_inl_defd_prrw_pop_back_single mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_pop_back_single)
#define mk_sl_fixed_vector_inl_defd_prrw_erase_at mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_erase_at)
#define mk_sl_fixed_vector_inl_defd_prrw_erase_element mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _prrw_erase_element)





#define mk_sl_fixed_vector_inl_defd_capacity_e mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _capacity_e)
#define mk_sl_fixed_vector_inl_defd_capacity_t mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _capacity_t)
#define mk_sl_fixed_vector_inl_defd_capacity_v mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _capacity_v)
#define mk_sl_fixed_vector_inl_defd_capacity_d mk_sl_fixed_vector_inl_defd_capacity

#define mk_sl_fixed_vector_inl_defd_st_max_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _st_max_capacity)

#define mk_sl_fixed_vector_inl_defd_ro_max_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_max_capacity)
#define mk_sl_fixed_vector_inl_defd_ro_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_capacity)
#define mk_sl_fixed_vector_inl_defd_ro_size mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_size)
#define mk_sl_fixed_vector_inl_defd_ro_sise mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_sise)
#define mk_sl_fixed_vector_inl_defd_ro_free mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_free)
#define mk_sl_fixed_vector_inl_defd_ro_is_empty mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_is_empty)
#define mk_sl_fixed_vector_inl_defd_ro_is_full mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_is_full)
#define mk_sl_fixed_vector_inl_defd_ro_at mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_at)
#define mk_sl_fixed_vector_inl_defd_ro_data mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_data)
#define mk_sl_fixed_vector_inl_defd_ro_front mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_front)
#define mk_sl_fixed_vector_inl_defd_ro_back mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_back)
#define mk_sl_fixed_vector_inl_defd_ro_eq mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_eq)
#define mk_sl_fixed_vector_inl_defd_ro_ne mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _ro_ne)

#define mk_sl_fixed_vector_inl_defd_rw_max_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_max_capacity)
#define mk_sl_fixed_vector_inl_defd_rw_capacity mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_capacity)
#define mk_sl_fixed_vector_inl_defd_rw_size mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_size)
#define mk_sl_fixed_vector_inl_defd_rw_sise mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_sise)
#define mk_sl_fixed_vector_inl_defd_rw_free mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_free)
#define mk_sl_fixed_vector_inl_defd_rw_is_empty mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_is_empty)
#define mk_sl_fixed_vector_inl_defd_rw_is_full mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_is_full)
#define mk_sl_fixed_vector_inl_defd_rw_at mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_at)
#define mk_sl_fixed_vector_inl_defd_rw_data mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_data)
#define mk_sl_fixed_vector_inl_defd_rw_front mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_front)
#define mk_sl_fixed_vector_inl_defd_rw_back mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_back)
#define mk_sl_fixed_vector_inl_defd_rw_eq mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_eq)
#define mk_sl_fixed_vector_inl_defd_rw_ne mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_ne)

#define mk_sl_fixed_vector_inl_defd_rw_construct_void mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_construct_void)
#define mk_sl_fixed_vector_inl_defd_rw_destroy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_destroy)
#define mk_sl_fixed_vector_inl_defd_rw_construct_copy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_construct_copy)
#define mk_sl_fixed_vector_inl_defd_rw_construct_move mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_construct_move)
#define mk_sl_fixed_vector_inl_defd_rw_assign_copy mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_assign_copy)
#define mk_sl_fixed_vector_inl_defd_rw_assign_move mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_assign_move)
#define mk_sl_fixed_vector_inl_defd_rw_reserve_at_least mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_reserve_at_least)
#define mk_sl_fixed_vector_inl_defd_rw_reserve_additional mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_reserve_additional)
#define mk_sl_fixed_vector_inl_defd_rw_shrink_by mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_shrink_by)
#define mk_sl_fixed_vector_inl_defd_rw_resize_to mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_resize_to)
#define mk_sl_fixed_vector_inl_defd_rw_grow_by mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_grow_by)
#define mk_sl_fixed_vector_inl_defd_rw_clear mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_clear)
#define mk_sl_fixed_vector_inl_defd_rw_push_back_copy_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_push_back_copy_many)
#define mk_sl_fixed_vector_inl_defd_rw_push_back_move_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_push_back_move_many)
#define mk_sl_fixed_vector_inl_defd_rw_push_back_copy_single mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_push_back_copy_single)
#define mk_sl_fixed_vector_inl_defd_rw_push_back_move_single mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_push_back_move_single)
#define mk_sl_fixed_vector_inl_defd_rw_pop_back_many mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_pop_back_many)
#define mk_sl_fixed_vector_inl_defd_rw_pop_back_single mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_pop_back_single)
#define mk_sl_fixed_vector_inl_defd_rw_erase_at mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_erase_at)
#define mk_sl_fixed_vector_inl_defd_rw_erase_element mk_lang_concat(mk_sl_fixed_vector_inl_defd_name, _rw_erase_element)
