#include "mk_lang_concat.h"


#if(!( \
	(defined mk_sl_sort_merge_t_name) && \
	(defined mk_sl_sort_merge_t_data_type) && \
	(defined mk_sl_sort_merge_t_is_sorted) && \
	(defined mk_sl_sort_merge_t_proxy_type || !defined mk_sl_sort_merge_t_proxy_type) && \
	1))
#error xxxxxxxxxx
#endif


#define mk_sl_sort_merge_inl_defd_name mk_sl_sort_merge_t_name
#define mk_sl_sort_merge_inl_defd_data_type mk_sl_sort_merge_t_data_type
#define mk_sl_sort_merge_inl_defd_is_sorted mk_sl_sort_merge_t_is_sorted

#if defined mk_sl_sort_merge_t_proxy_type
#define mk_sl_sort_merge_inl_defd_has_proxy 1
#define mk_sl_sort_merge_inl_defd_proxy_type mk_sl_sort_merge_t_proxy_type
#else
#define mk_sl_sort_merge_inl_defd_has_proxy 0
#define mk_sl_sort_merge_inl_defd_proxy_type mk_lang_types_sint_t
#endif


#define mk_sl_sort_merge_inl_defd_data_t mk_lang_concat(mk_sl_sort_merge_t_name, _data_t)
#define mk_sl_sort_merge_inl_defd_data_ct mk_lang_concat(mk_sl_sort_merge_t_name, _data_ct)
#define mk_sl_sort_merge_inl_defd_data_pt mk_lang_concat(mk_sl_sort_merge_t_name, _data_pt)
#define mk_sl_sort_merge_inl_defd_data_pct mk_lang_concat(mk_sl_sort_merge_t_name, _data_pct)
#define mk_sl_sort_merge_inl_defd_data_prt mk_lang_concat(mk_sl_sort_merge_t_name, _data_prt)
#define mk_sl_sort_merge_inl_defd_data_prct mk_lang_concat(mk_sl_sort_merge_t_name, _data_prct)

#define mk_sl_sort_merge_inl_defd_proxy_t mk_lang_concat(mk_sl_sort_merge_t_name, _proxy_t)
#define mk_sl_sort_merge_inl_defd_proxy_ct mk_lang_concat(mk_sl_sort_merge_t_name, _proxy_ct)
#define mk_sl_sort_merge_inl_defd_proxy_pt mk_lang_concat(mk_sl_sort_merge_t_name, _proxy_pt)
#define mk_sl_sort_merge_inl_defd_proxy_pct mk_lang_concat(mk_sl_sort_merge_t_name, _proxy_pct)
#define mk_sl_sort_merge_inl_defd_proxy_prt mk_lang_concat(mk_sl_sort_merge_t_name, _proxy_prt)
#define mk_sl_sort_merge_inl_defd_proxy_prct mk_lang_concat(mk_sl_sort_merge_t_name, _proxy_prct)

#define mk_sl_sort_merge_inl_defd_overlap_data_name mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _zzz_overlap_data)
#define mk_sl_sort_merge_inl_defd_overlap_data_fn mk_lang_concat(mk_sl_sort_merge_inl_defd_overlap_data_name, _fn)
#define mk_sl_sort_merge_inl_defd_overlap_proxy_name mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _zzz_overlap_proxy)
#define mk_sl_sort_merge_inl_defd_overlap_proxy_fn mk_lang_concat(mk_sl_sort_merge_inl_defd_overlap_proxy_name, _fn)
#define mk_sl_sort_merge_inl_defd_swap_datat_name mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _zzz_swap_datat)
#define mk_sl_sort_merge_inl_defd_swap_datat_fn mk_lang_concat(mk_sl_sort_merge_inl_defd_swap_datat_name, _fn)
#define mk_sl_sort_merge_inl_defd_swap_datap_name mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _zzz_swap_datap)
#define mk_sl_sort_merge_inl_defd_swap_datap_fn mk_lang_concat(mk_sl_sort_merge_inl_defd_swap_datap_name, _fn)
#define mk_sl_sort_merge_inl_defd_swap_proxyt_name mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _zzz_swap_proxyt)
#define mk_sl_sort_merge_inl_defd_swap_proxyt_fn mk_lang_concat(mk_sl_sort_merge_inl_defd_swap_proxyt_name, _fn)
#define mk_sl_sort_merge_inl_defd_swap_proxyp_name mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _zzz_swap_proxyp)
#define mk_sl_sort_merge_inl_defd_swap_proxyp_fn mk_lang_concat(mk_sl_sort_merge_inl_defd_swap_proxyp_name, _fn)
#define mk_sl_sort_merge_inl_defd_memcpy_datat_name mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _zzz_memcpy_datat)
#define mk_sl_sort_merge_inl_defd_memcpy_datat_fn mk_lang_concat(mk_sl_sort_merge_inl_defd_memcpy_datat_name, _fn)
#define mk_sl_sort_merge_inl_defd_memcpy_proxyt_name mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _zzz_memcpy_proxyt)
#define mk_sl_sort_merge_inl_defd_memcpy_proxyt_fn mk_lang_concat(mk_sl_sort_merge_inl_defd_memcpy_proxyt_name, _fn)
#define mk_sl_sort_merge_inl_defd_bui_usize_name mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _zzz_bui_usize)
#define mk_sl_sort_merge_inl_defd_bui_usize_count_leading_zeros mk_lang_concat(mk_sl_sort_merge_inl_defd_bui_usize_name, _count_leading_zeros)

#define mk_sl_sort_merge_inl_defd_pr_plain_swap mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _pr_plain_swap)
#define mk_sl_sort_merge_inl_defd_pr_plain_is_sorted mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _pr_plain_is_sorted)
#define mk_sl_sort_merge_inl_defd_pr_plain_merge mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _pr_plain_merge)
#define mk_sl_sort_merge_inl_defd_pr_plain_inplace mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _pr_plain_inplace)
#define mk_sl_sort_merge_inl_defd_pr_plain_copy mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _pr_plain_copy)
#define mk_sl_sort_merge_inl_defd_pr_plain_first mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _pr_plain_first)
#define mk_sl_sort_merge_inl_defd_pr_plain_many mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _pr_plain_many)

#define mk_sl_sort_merge_inl_defd_pr_proxy_swap mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _pr_proxy_swap)
#define mk_sl_sort_merge_inl_defd_pr_proxy_is_sorted mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _pr_proxy_is_sorted)
#define mk_sl_sort_merge_inl_defd_pr_proxy_merge mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _pr_proxy_merge)
#define mk_sl_sort_merge_inl_defd_pr_proxy_inplace mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _pr_proxy_inplace)
#define mk_sl_sort_merge_inl_defd_pr_proxy_copy mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _pr_proxy_copy)
#define mk_sl_sort_merge_inl_defd_pr_proxy_first mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _pr_proxy_first)
#define mk_sl_sort_merge_inl_defd_pr_proxy_many mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _pr_proxy_many)


#define mk_sl_sort_merge_inl_defd_fn_plain mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _fn_plain)
#define mk_sl_sort_merge_inl_defd_fn_proxy mk_lang_concat(mk_sl_sort_merge_inl_defd_name, _fn_proxy)
