#ifndef mk_include_guard_mk_sl_io_async_writer_file_windows
#define mk_include_guard_mk_sl_io_async_writer_file_windows


#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_types.h"
#include "mk_sl_uint64.h"
#include "mk_sl_uint8.h"
#include "mk_win_base.h"
#include "mk_win_kernel_files.h"


struct mk_sl_io_transaction_windows_s;
typedef struct mk_sl_io_transaction_windows_s mk_sl_io_transaction_windows_t;
typedef mk_sl_io_transaction_windows_t const mk_sl_io_transaction_windows_ct;
typedef mk_sl_io_transaction_windows_t* mk_sl_io_transaction_windows_pt;
typedef mk_sl_io_transaction_windows_t const* mk_sl_io_transaction_windows_pct;


struct mk_sl_io_async_writer_file_windows_s
{
	mk_win_base_handle_t m_file;
};
typedef struct mk_sl_io_async_writer_file_windows_s mk_sl_io_async_writer_file_windows_t;
typedef mk_sl_io_async_writer_file_windows_t const mk_sl_io_async_writer_file_windows_ct;
typedef mk_sl_io_async_writer_file_windows_t* mk_sl_io_async_writer_file_windows_pt;
typedef mk_sl_io_async_writer_file_windows_t const* mk_sl_io_async_writer_file_windows_pct;

struct mk_sl_io_async_writer_file_iorp_windows_s
{
	mk_win_base_void_lpt m_buf;
	mk_win_base_dword_t m_len;
	mk_win_base_dword_t m_transfered;
	mk_lang_types_bool_t m_finished;
	mk_win_kernel_files_overlapped_t m_overlapped;
};
typedef struct mk_sl_io_async_writer_file_iorp_windows_s mk_sl_io_async_writer_file_iorp_windows_t;
typedef mk_sl_io_async_writer_file_iorp_windows_t const mk_sl_io_async_writer_file_iorp_windows_ct;
typedef mk_sl_io_async_writer_file_iorp_windows_t* mk_sl_io_async_writer_file_iorp_windows_pt;
typedef mk_sl_io_async_writer_file_iorp_windows_t const* mk_sl_io_async_writer_file_iorp_windows_pct;


mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_io_async_writer_file_windows_open_n(mk_sl_io_async_writer_file_windows_pt const writer, mk_lang_types_pchar_pct const name) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_io_async_writer_file_windows_open_w(mk_sl_io_async_writer_file_windows_pt const writer, mk_lang_types_wchar_pct const name) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_io_async_writer_file_windows_open_tx_n(mk_sl_io_async_writer_file_windows_pt const writer, mk_lang_types_pchar_pct const name, mk_sl_io_transaction_windows_pt const tx) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_io_async_writer_file_windows_open_tx_w(mk_sl_io_async_writer_file_windows_pt const writer, mk_lang_types_wchar_pct const name, mk_sl_io_transaction_windows_pt const tx) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_io_async_writer_file_windows_request_write(mk_sl_io_async_writer_file_windows_pt const writer, mk_sl_io_async_writer_file_iorp_windows_pt const iorp) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_io_async_writer_file_windows_close(mk_sl_io_async_writer_file_windows_pt const writer) mk_lang_noexcept;

mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_io_async_writer_file_iorp_windows_construct_void(mk_sl_io_async_writer_file_iorp_windows_pt const iorp) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_io_async_writer_file_iorp_windows_construct_args(mk_sl_io_async_writer_file_iorp_windows_pt const iorp, mk_sl_cui_uint8_pt const buf, mk_lang_types_usize_t const len, mk_sl_cui_uint64_pct const pos) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_io_async_writer_file_iorp_windows_reconstruct(mk_sl_io_async_writer_file_iorp_windows_pt const iorp, mk_sl_cui_uint8_pt const buf, mk_lang_types_usize_t const len, mk_sl_cui_uint64_pct const pos) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_io_async_writer_file_iorp_windows_buf(mk_sl_io_async_writer_file_iorp_windows_pt const iorp, mk_sl_cui_uint8_pt* const buf) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_io_async_writer_file_iorp_windows_len(mk_sl_io_async_writer_file_iorp_windows_pt const iorp, mk_lang_types_usize_pt const len) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_io_async_writer_file_iorp_windows_pos(mk_sl_io_async_writer_file_iorp_windows_pt const iorp, mk_sl_cui_uint64_pt const pos) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_lang_types_sint_t mk_sl_io_async_writer_file_iorp_windows_destroy(mk_sl_io_async_writer_file_iorp_windows_pt const iorp) mk_lang_noexcept;


#if mk_lang_jumbo_want == 1
#include "mk_sl_io_async_writer_file_windows.c"
#endif
#endif
