#include "mk_lang_concat.h"


#define mk_win_sl_file_istream_buffered_inl_defd_count (mk_win_sl_file_istream_buffered_t_count)
#define mk_win_sl_file_istream_buffered_inl_defd_size (mk_win_sl_file_istream_buffered_t_size)
#define mk_win_sl_file_istream_buffered_inl_defd_bytes (mk_win_sl_file_istream_buffered_inl_defd_count * mk_win_sl_file_istream_buffered_inl_defd_size)

#define mk_win_sl_file_istream_buffered_inl_defd_prefix mk_lang_concat(mk_win_sl_file_istream_buffered_, mk_win_sl_file_istream_buffered_t_name)

#define mk_win_sl_file_istream_buffered_inl_defd_s mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _s)
#define mk_win_sl_file_istream_buffered_inl_defd_t mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _t)
#define mk_win_sl_file_istream_buffered_inl_defd_ct mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _ct)
#define mk_win_sl_file_istream_buffered_inl_defd_pt mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _pt)
#define mk_win_sl_file_istream_buffered_inl_defd_pct mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _pct)
#define mk_win_sl_file_istream_buffered_inl_defd_lpt mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _lpt)
#define mk_win_sl_file_istream_buffered_inl_defd_lpct mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _lpct)
#define mk_win_sl_file_istream_buffered_inl_defd_npt mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _npt)
#define mk_win_sl_file_istream_buffered_inl_defd_npct mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _npct)

#define mk_win_sl_file_istream_buffered_inl_defd_state_s mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _state_s)
#define mk_win_sl_file_istream_buffered_inl_defd_state_t mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _state_t)
#define mk_win_sl_file_istream_buffered_inl_defd_state_ct mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _state_ct)
#define mk_win_sl_file_istream_buffered_inl_defd_state_pt mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _state_pt)
#define mk_win_sl_file_istream_buffered_inl_defd_state_pct mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _state_pct)
#define mk_win_sl_file_istream_buffered_inl_defd_state_lpt mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _state_lpt)
#define mk_win_sl_file_istream_buffered_inl_defd_state_lpct mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _state_lpct)
#define mk_win_sl_file_istream_buffered_inl_defd_state_npt mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _state_npt)
#define mk_win_sl_file_istream_buffered_inl_defd_state_npct mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _state_npct)

#define mk_win_sl_file_istream_buffered_inl_defd_rw_init_last mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _rw_init_last)
#define mk_win_sl_file_istream_buffered_inl_defd_rw_submit_read mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _rw_submit_read)
#define mk_win_sl_file_istream_buffered_inl_defd_rw_wait_read mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _wait_read)

#define mk_win_sl_file_istream_buffered_inl_defd_rw_construct_from_file_handle mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _rw_construct_from_file_handle)
#define mk_win_sl_file_istream_buffered_inl_defd_rw_construct_from_file_name mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _rw_construct_from_file_name)
#define mk_win_sl_file_istream_buffered_inl_defd_rw_destroy mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _rw_destroy)
#define mk_win_sl_file_istream_buffered_inl_defd_rw_read mk_lang_concat(mk_win_sl_file_istream_buffered_inl_defd_prefix, _rw_read)
