#ifndef mk_include_guard_mk_win_kernel_communication
#define mk_include_guard_mk_win_kernel_communication


#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_restrict.h"
#include "mk_win_base.h"
#include "mk_win_kernel_files.h"


#define mk_win_kernel_communication_device_id_beep                ((mk_win_base_dword_t)(0x00000001ul))
#define mk_win_kernel_communication_device_id_cd_rom              ((mk_win_base_dword_t)(0x00000002ul))
#define mk_win_kernel_communication_device_id_cd_rom_file_system  ((mk_win_base_dword_t)(0x00000003ul))
#define mk_win_kernel_communication_device_id_controller          ((mk_win_base_dword_t)(0x00000004ul))
#define mk_win_kernel_communication_device_id_datalink            ((mk_win_base_dword_t)(0x00000005ul))
#define mk_win_kernel_communication_device_id_dfs                 ((mk_win_base_dword_t)(0x00000006ul))
#define mk_win_kernel_communication_device_id_disk                ((mk_win_base_dword_t)(0x00000007ul))
#define mk_win_kernel_communication_device_id_disk_file_system    ((mk_win_base_dword_t)(0x00000008ul))
#define mk_win_kernel_communication_device_id_file_system         ((mk_win_base_dword_t)(0x00000009ul))
#define mk_win_kernel_communication_device_id_inport_port         ((mk_win_base_dword_t)(0x0000000aul))
#define mk_win_kernel_communication_device_id_keyboard            ((mk_win_base_dword_t)(0x0000000bul))
#define mk_win_kernel_communication_device_id_mailslot            ((mk_win_base_dword_t)(0x0000000cul))
#define mk_win_kernel_communication_device_id_midi_in             ((mk_win_base_dword_t)(0x0000000dul))
#define mk_win_kernel_communication_device_id_midi_out            ((mk_win_base_dword_t)(0x0000000eul))
#define mk_win_kernel_communication_device_id_mouse               ((mk_win_base_dword_t)(0x0000000ful))
#define mk_win_kernel_communication_device_id_multi_unc_provider  ((mk_win_base_dword_t)(0x00000010ul))
#define mk_win_kernel_communication_device_id_named_pipe          ((mk_win_base_dword_t)(0x00000011ul))
#define mk_win_kernel_communication_device_id_network             ((mk_win_base_dword_t)(0x00000012ul))
#define mk_win_kernel_communication_device_id_network_browser     ((mk_win_base_dword_t)(0x00000013ul))
#define mk_win_kernel_communication_device_id_network_file_system ((mk_win_base_dword_t)(0x00000014ul))
#define mk_win_kernel_communication_device_id_null                ((mk_win_base_dword_t)(0x00000015ul))
#define mk_win_kernel_communication_device_id_parallel_port       ((mk_win_base_dword_t)(0x00000016ul))
#define mk_win_kernel_communication_device_id_physical_netcard    ((mk_win_base_dword_t)(0x00000017ul))
#define mk_win_kernel_communication_device_id_printer             ((mk_win_base_dword_t)(0x00000018ul))
#define mk_win_kernel_communication_device_id_scanner             ((mk_win_base_dword_t)(0x00000019ul))
#define mk_win_kernel_communication_device_id_serial_mouse_port   ((mk_win_base_dword_t)(0x0000001aul))
#define mk_win_kernel_communication_device_id_serial_port         ((mk_win_base_dword_t)(0x0000001bul))
#define mk_win_kernel_communication_device_id_screen              ((mk_win_base_dword_t)(0x0000001cul))
#define mk_win_kernel_communication_device_id_sound               ((mk_win_base_dword_t)(0x0000001dul))
#define mk_win_kernel_communication_device_id_streams             ((mk_win_base_dword_t)(0x0000001eul))
#define mk_win_kernel_communication_device_id_tape                ((mk_win_base_dword_t)(0x0000001ful))
#define mk_win_kernel_communication_device_id_tape_file_system    ((mk_win_base_dword_t)(0x00000020ul))
#define mk_win_kernel_communication_device_id_transport           ((mk_win_base_dword_t)(0x00000021ul))
#define mk_win_kernel_communication_device_id_unknown             ((mk_win_base_dword_t)(0x00000022ul))
#define mk_win_kernel_communication_device_id_video               ((mk_win_base_dword_t)(0x00000023ul))
#define mk_win_kernel_communication_device_id_virtual_disk        ((mk_win_base_dword_t)(0x00000024ul))
#define mk_win_kernel_communication_device_id_wave_in             ((mk_win_base_dword_t)(0x00000025ul))
#define mk_win_kernel_communication_device_id_wave_out            ((mk_win_base_dword_t)(0x00000026ul))
#define mk_win_kernel_communication_device_id_8042_port           ((mk_win_base_dword_t)(0x00000027ul))
#define mk_win_kernel_communication_device_id_network_redirector  ((mk_win_base_dword_t)(0x00000028ul))
#define mk_win_kernel_communication_device_id_battery             ((mk_win_base_dword_t)(0x00000029ul))
#define mk_win_kernel_communication_device_id_bus_extender        ((mk_win_base_dword_t)(0x0000002aul))
#define mk_win_kernel_communication_device_id_modem               ((mk_win_base_dword_t)(0x0000002bul))
#define mk_win_kernel_communication_device_id_vdm                 ((mk_win_base_dword_t)(0x0000002cul))
#define mk_win_kernel_communication_device_id_mass_storage        ((mk_win_base_dword_t)(0x0000002dul))
#define mk_win_kernel_communication_device_id_smb                 ((mk_win_base_dword_t)(0x0000002eul))
#define mk_win_kernel_communication_device_id_ks                  ((mk_win_base_dword_t)(0x0000002ful))
#define mk_win_kernel_communication_device_id_changer             ((mk_win_base_dword_t)(0x00000030ul))
#define mk_win_kernel_communication_device_id_smartcard           ((mk_win_base_dword_t)(0x00000031ul))
#define mk_win_kernel_communication_device_id_acpi                ((mk_win_base_dword_t)(0x00000032ul))
#define mk_win_kernel_communication_device_id_dvd                 ((mk_win_base_dword_t)(0x00000033ul))
#define mk_win_kernel_communication_device_id_fullscreen_video    ((mk_win_base_dword_t)(0x00000034ul))
#define mk_win_kernel_communication_device_id_dfs_file_system     ((mk_win_base_dword_t)(0x00000035ul))
#define mk_win_kernel_communication_device_id_dfs_volume          ((mk_win_base_dword_t)(0x00000036ul))
#define mk_win_kernel_communication_device_id_serenum             ((mk_win_base_dword_t)(0x00000037ul))
#define mk_win_kernel_communication_device_id_termsrv             ((mk_win_base_dword_t)(0x00000038ul))
#define mk_win_kernel_communication_device_id_ksec                ((mk_win_base_dword_t)(0x00000039ul))
#define mk_win_kernel_communication_device_id_fips                ((mk_win_base_dword_t)(0x0000003Aul))
#define mk_win_kernel_communication_device_id_infiniband          ((mk_win_base_dword_t)(0x0000003Bul))
#define mk_win_kernel_communication_device_id_vmbus               ((mk_win_base_dword_t)(0x0000003Eul))
#define mk_win_kernel_communication_device_id_crypt_provider      ((mk_win_base_dword_t)(0x0000003Ful))
#define mk_win_kernel_communication_device_id_wpd                 ((mk_win_base_dword_t)(0x00000040ul))
#define mk_win_kernel_communication_device_id_bluetooth           ((mk_win_base_dword_t)(0x00000041ul))
#define mk_win_kernel_communication_device_id_mt_composite        ((mk_win_base_dword_t)(0x00000042ul))
#define mk_win_kernel_communication_device_id_mt_transport        ((mk_win_base_dword_t)(0x00000043ul))
#define mk_win_kernel_communication_device_id_biometric           ((mk_win_base_dword_t)(0x00000044ul))
#define mk_win_kernel_communication_device_id_pmi                 ((mk_win_base_dword_t)(0x00000045ul))
#define mk_win_kernel_communication_device_id_ehstor              ((mk_win_base_dword_t)(0x00000046ul))
#define mk_win_kernel_communication_device_id_devapi              ((mk_win_base_dword_t)(0x00000047ul))
#define mk_win_kernel_communication_device_id_gpio                ((mk_win_base_dword_t)(0x00000048ul))
#define mk_win_kernel_communication_device_id_usbex               ((mk_win_base_dword_t)(0x00000049ul))
#define mk_win_kernel_communication_device_id_console             ((mk_win_base_dword_t)(0x00000050ul))
#define mk_win_kernel_communication_device_id_nfp                 ((mk_win_base_dword_t)(0x00000051ul))
#define mk_win_kernel_communication_device_id_sysenv              ((mk_win_base_dword_t)(0x00000052ul))
#define mk_win_kernel_communication_device_id_virtual_block       ((mk_win_base_dword_t)(0x00000053ul))
#define mk_win_kernel_communication_device_id_point_of_service    ((mk_win_base_dword_t)(0x00000054ul))
#define mk_win_kernel_communication_device_id_storage_replication ((mk_win_base_dword_t)(0x00000055ul))
#define mk_win_kernel_communication_device_id_trust_env           ((mk_win_base_dword_t)(0x00000056ul))
#define mk_win_kernel_communication_device_id_ucm                 ((mk_win_base_dword_t)(0x00000057ul))
#define mk_win_kernel_communication_device_id_ucmtcpci            ((mk_win_base_dword_t)(0x00000058ul))
#define mk_win_kernel_communication_device_id_persistent_memory   ((mk_win_base_dword_t)(0x00000059ul))
#define mk_win_kernel_communication_device_id_nvdimm              ((mk_win_base_dword_t)(0x0000005aul))
#define mk_win_kernel_communication_device_id_holographic         ((mk_win_base_dword_t)(0x0000005bul))
#define mk_win_kernel_communication_device_id_sdfxhci             ((mk_win_base_dword_t)(0x0000005cul))
#define mk_win_kernel_communication_device_id_ucmucsi             ((mk_win_base_dword_t)(0x0000005dul))
#define mk_win_kernel_communication_device_id_prm                 ((mk_win_base_dword_t)(0x0000005eul))
#define mk_win_kernel_communication_device_id_event_collector     ((mk_win_base_dword_t)(0x0000005ful))
#define mk_win_kernel_communication_device_id_usb4                ((mk_win_base_dword_t)(0x00000060ul))
#define mk_win_kernel_communication_device_id_soundwire           ((mk_win_base_dword_t)(0x00000061ul))

#define mk_win_kernel_communication_method_id_buffered   0
#define mk_win_kernel_communication_method_id_in_direct  1
#define mk_win_kernel_communication_method_id_out_direct 2
#define mk_win_kernel_communication_method_id_neither    3

#define mk_win_kernel_communication_access_id_any     0x0000
#define mk_win_kernel_communication_access_id_special 0x0000
#define mk_win_kernel_communication_access_id_read    0x0001
#define mk_win_kernel_communication_access_id_write   0x0002

#define mk_win_kernel_communication_code_make(device_id, access_id, function_id, method_id) \
( \
	((mk_win_base_dword_t)(((mk_win_base_dword_t)(((mk_win_base_dword_t)(device_id  )) & ((mk_win_base_dword_t)((1u << 16) - 1)))) << 16)) | \
	((mk_win_base_dword_t)(((mk_win_base_dword_t)(((mk_win_base_dword_t)(access_id  )) & ((mk_win_base_dword_t)((1u <<  2) - 1)))) << 14)) | \
	((mk_win_base_dword_t)(((mk_win_base_dword_t)(((mk_win_base_dword_t)(function_id)) & ((mk_win_base_dword_t)((1u << 12) - 1)))) <<  2)) | \
	((mk_win_base_dword_t)(((mk_win_base_dword_t)(((mk_win_base_dword_t)(method_id  )) & ((mk_win_base_dword_t)((1u <<  2) - 1)))) <<  0)) | \
	0 \
)

#define mk_win_kernel_communication_control_code_id_fs_request_oplock_level_1                           mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,   0, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_request_oplock_level_2                           mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,   1, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_request_batch_oplock                             mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,   2, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_oplock_break_acknowledge                         mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,   3, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_opbatch_ack_close_pending                        mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,   4, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_oplock_break_notify                              mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,   5, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_lock_volume                                      mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,   6, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_unlock_volume                                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,   7, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_dismount_volume                                  mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,   8, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_is_volume_mounted                                mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  10, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_is_pathname_valid                                mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  11, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_mark_volume_dirty                                mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  12, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_retrieval_pointers                         mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  14, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_get_compression                                  mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  15, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_compression                                  mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read | mk_win_kernel_communication_access_id_write,  16, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_bootloader_accessed                          mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  19, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_oplock_break_ack_no_2                            mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  20, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_invalidate_volumes                               mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  21, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_fat_bpb                                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  22, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_request_filter_oplock                            mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  23, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_filesystem_get_statistics                        mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  24, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_get_ntfs_volume_data                             mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  25, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_get_ntfs_file_record                             mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  26, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_get_volume_bitmap                                mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  27, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_get_retrieval_pointers                           mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  28, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_move_file                                        mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           ,  29, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_is_volume_dirty                                  mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  30, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_allow_extended_dasd_io                           mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system,  mk_win_kernel_communication_access_id_any                                              ,  32, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_find_files_by_sid                                mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  35, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_set_object_id                                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           ,  38, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_get_object_id                                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  39, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_delete_object_id                                 mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           ,  40, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_reparse_point                                mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           ,  41, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_get_reparse_point                                mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  42, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_delete_reparse_point                             mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           ,  43, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_enum_usn_data                                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  44, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_security_id_check                                mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read                                              ,  45, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_read_usn_journal                                 mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  46, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_set_object_id_extended                           mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           ,  47, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_create_or_get_object_id                          mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  48, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_sparse                                       mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           ,  49, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_zero_data                                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             ,  50, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_allocated_ranges                           mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read                                              ,  51, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_enable_upgrade                                   mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             ,  52, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_encryption                                   mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  53, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_encryption_fsctl_io                              mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  54, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_write_raw_encrypted                              mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           ,  55, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_read_raw_encrypted                               mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           ,  56, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_create_usn_journal                               mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  57, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_read_file_usn_data                               mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  58, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_write_usn_close_record                           mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  59, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_extend_volume                                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  60, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_usn_journal                                mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  61, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_delete_usn_journal                               mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  62, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_mark_handle                                      mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  63, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_sis_copyfile                                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  64, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_sis_link_files                                   mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read | mk_win_kernel_communication_access_id_write,  65, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_recall_file                                      mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  69, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_read_from_plex                                   mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read                                              ,  71, mk_win_kernel_communication_method_id_out_direct)
#define mk_win_kernel_communication_control_code_id_fs_file_prefetch                                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           ,  72, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_make_media_compatible                            mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             ,  76, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_defect_management                            mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             ,  77, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_sparing_info                               mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  78, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_on_disk_volume_info                        mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               ,  79, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_volume_compression_state                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           ,  80, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_modify_rm                                   mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             ,  81, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_query_rm_information                        mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read                                              ,  82, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_rollforward_redo                            mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             ,  84, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_rollforward_undo                            mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             ,  85, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_start_rm                                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             ,  86, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_shutdown_rm                                 mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             ,  87, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_read_backup_information                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read                                              ,  88, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_write_backup_information                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             ,  89, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_create_secondary_rm                         mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             ,  90, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_get_metadata_info                           mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read                                              ,  91, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_get_transacted_version                      mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read                                              ,  92, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_savepoint_information                       mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             ,  94, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_create_miniversion                          mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             ,  95, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_transaction_active                          mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read                                              ,  99, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_zero_on_deallocation                         mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           , 101, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_repair                                       mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 102, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_get_repair                                       mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 103, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_wait_for_repair                                  mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 104, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_initiate_repair                                  mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 106, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_csc_internal                                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 107, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_shrink_volume                                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           , 108, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_short_name_behavior                          mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 109, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_dfsr_set_ghost_handle_state                      mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 110, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_list_transaction_locked_files               mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read                                              , 120, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_list_transactions                           mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read                                              , 121, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_pagefile_encryption                        mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 122, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_reset_volume_allocation_hints                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 123, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_dependent_volume                           mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 124, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_sd_global_change                                 mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 125, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_read_backup_information2                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 126, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_lookup_stream_from_cluster                       mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 127, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_txfs_write_backup_information2                   mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 128, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_file_type_notification                           mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 129, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_file_level_trim                                  mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             , 130, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_get_boot_area_info                               mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 140, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_get_retrieval_pointer_base                       mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 141, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_persistent_volume_state                      mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 142, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_persistent_volume_state                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 143, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_request_oplock                                   mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 144, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_csv_tunnel_request                               mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 145, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_is_csv_file                                      mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 146, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_file_system_recognition                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 147, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_csv_get_volume_path_name                         mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 148, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_csv_get_volume_name_for_volume_mount_point       mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 149, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_csv_get_volume_path_names_for_volume_name        mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 150, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_is_file_on_csv_volume                            mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 151, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_corruption_handling                              mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 152, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_offload_read                                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read                                              , 153, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_offload_write                                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             , 154, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_csv_internal                                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 155, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_purge_failure_mode                           mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 156, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_file_layout                                mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 157, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_is_volume_owned_bycsvfs                          mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 158, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_get_integrity_information                        mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 159, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_integrity_information                        mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read | mk_win_kernel_communication_access_id_write, 160, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_file_regions                               mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 161, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_rkf_internal                                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 171, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_scrub_data                                       mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 172, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_repair_copies                                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read | mk_win_kernel_communication_access_id_write, 173, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_disable_local_buffering                          mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 174, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_csv_mgmt_lock                                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 175, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_csv_query_down_level_file_system_characteristics mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 176, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_advance_file_id                                  mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 177, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_csv_sync_tunnel_request                          mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 178, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_csv_query_veto_file_direct_io                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 179, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_write_usn_reason                                 mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 180, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_csv_control                                      mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 181, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_get_refs_volume_data                             mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 182, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_csv_h_breaking_sync_tunnel_request               mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 185, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_storage_classes                            mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 187, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_region_info                                mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 188, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_usn_track_modified_ranges                        mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 189, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_shared_virtual_disk_support                mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 192, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_svhdx_sync_tunnel_request                        mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 193, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_svhdx_set_initiator_information                  mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 194, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_external_backing                             mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           , 195, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_get_external_backing                             mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 196, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_delete_external_backing                          mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           , 197, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_enum_external_backing                            mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 198, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_enum_overlay                                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 199, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_add_overlay                                      mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             , 204, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_remove_overlay                                   mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             , 205, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_update_overlay                                   mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             , 206, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_shuffle_file                                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read | mk_win_kernel_communication_access_id_write, 208, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_duplicate_extents_to_file                        mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             , 209, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_sparse_overallocate                              mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           , 211, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_storage_qos_control                              mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 212, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_initiate_file_metadata_optimization              mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           , 215, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_file_metadata_optimization                 mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           , 216, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_svhdx_async_tunnel_request                       mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 217, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_get_wof_version                                  mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 218, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_hcs_sync_tunnel_request                          mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 219, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_hcs_async_tunnel_request                         mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 220, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_extent_read_cache_info                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 221, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_query_refs_volume_counter_info                   mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 222, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_clean_volume_metadata                            mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 223, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_integrity_information_ex                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 224, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_suspend_overlay                                  mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 225, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_virtual_storage_query_property                   mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 226, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_filesystem_get_statistics_ex                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 227, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_volume_container_state                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 228, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_layer_root                                   mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 229, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_direct_access_extents                      mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 230, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_notify_storage_space_allocation                  mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 231, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_ssdi_storage_request                             mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 232, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_direct_image_original_base                 mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 233, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_read_unprivileged_usn_journal                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 234, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_ghost_file_extents                               mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             , 235, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_ghosted_file_extents                       mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 236, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_unmap_space                                      mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 237, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_hcs_sync_no_write_tunnel_request                 mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 238, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_start_virtualization_instance                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 240, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_get_filter_file_identifier                       mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 241, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_streams_query_parameters                         mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 241, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_streams_associate_id                             mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 242, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_streams_query_id                                 mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 243, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_get_retrieval_pointers_and_refcount              mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system,  mk_win_kernel_communication_access_id_any                                              , 244, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_query_volume_numa_info                           mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 245, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_refs_deallocate_ranges                           mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 246, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_refs_smr_volume_info                       mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 247, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_refs_smr_volume_gc_parameters                mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 248, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_refs_file_strictly_sequential                mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 249, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_duplicate_extents_to_file_ex                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_write                                             , 250, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_bad_ranges                                 mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 251, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_dax_alloc_alignment_hint                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 252, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_delete_corrupted_refs_container                  mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 253, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_scrub_undiscoverable_id                          mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 254, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_notify_data_change                               mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 255, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_start_virtualization_instance_ex                 mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 256, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_encryption_key_control                           mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 257, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_virtual_storage_set_behavior                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 258, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_reparse_point_ex                             mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_special                                           , 259, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_rearrange_file                                   mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_read | mk_win_kernel_communication_access_id_write, 264, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_virtual_storage_passthrough                      mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 265, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_get_retrieval_pointer_count                      mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system,  mk_win_kernel_communication_access_id_any                                              , 266, mk_win_kernel_communication_method_id_neither   )
#define mk_win_kernel_communication_control_code_id_fs_enable_per_io_flags                              mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 267, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_async_duplicate_extents_status             mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 268, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_smb_share_flush_and_purge                        mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 271, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_refs_stream_snapshot_management                  mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 272, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_manage_bypass_io                                 mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 274, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_refs_deallocate_ranges_ex                        mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 275, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_set_cached_runs_state                            mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 276, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_refs_set_volume_compression_info                 mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 277, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_refs_query_volume_compression_info               mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 278, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_duplicate_cluster                                mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 279, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_create_lcn_weak_reference                        mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 280, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_clear_lcn_weak_reference                         mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 281, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_query_lcn_weak_reference                         mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 282, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_clear_all_lcn_weak_references                    mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 283, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_refs_set_volume_dedup_info                       mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 284, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_refs_query_volume_dedup_info                     mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 285, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_lmr_query_info                                   mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 286, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_refs_checkpoint_volume                           mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 287, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_refs_query_volume_total_shared_lcns              mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 288, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_upgrade_volume                                   mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 289, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_refs_set_volume_io_metrics_info                  mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 290, mk_win_kernel_communication_method_id_buffered  )
#define mk_win_kernel_communication_control_code_id_fs_refs_query_volume_io_metrics_info                mk_win_kernel_communication_code_make(mk_win_kernel_communication_device_id_file_system, mk_win_kernel_communication_access_id_any                                               , 291, mk_win_kernel_communication_method_id_buffered  )


struct mk_win_kernel_communication_buf_fs_starting_vcn_s
{
	mk_win_base_large_integer_t m_starting_vcn;
};
typedef struct mk_win_kernel_communication_buf_fs_starting_vcn_s mk_win_kernel_communication_buf_fs_starting_vcn_t;
typedef mk_win_kernel_communication_buf_fs_starting_vcn_t const mk_win_kernel_communication_buf_fs_starting_vcn_ct;
typedef mk_win_kernel_communication_buf_fs_starting_vcn_t* mk_win_kernel_communication_buf_fs_starting_vcn_pt;
typedef mk_win_kernel_communication_buf_fs_starting_vcn_t const* mk_win_kernel_communication_buf_fs_starting_vcn_pct;
typedef mk_win_kernel_communication_buf_fs_starting_vcn_t mk_win_base_far* mk_win_kernel_communication_buf_fs_starting_vcn_lpt;
typedef mk_win_kernel_communication_buf_fs_starting_vcn_t mk_win_base_far const* mk_win_kernel_communication_buf_fs_starting_vcn_lpct;
typedef mk_win_kernel_communication_buf_fs_starting_vcn_t mk_win_base_near* mk_win_kernel_communication_buf_fs_starting_vcn_npt;
typedef mk_win_kernel_communication_buf_fs_starting_vcn_t mk_win_base_near const* mk_win_kernel_communication_buf_fs_starting_vcn_npct;
typedef mk_win_kernel_communication_buf_fs_starting_vcn_t* mk_lang_restrict mk_win_kernel_communication_buf_fs_starting_vcn_prt;
typedef mk_win_kernel_communication_buf_fs_starting_vcn_t const* mk_lang_restrict mk_win_kernel_communication_buf_fs_starting_vcn_prct;
typedef mk_win_kernel_communication_buf_fs_starting_vcn_t mk_win_base_far* mk_lang_restrict mk_win_kernel_communication_buf_fs_starting_vcn_lprt;
typedef mk_win_kernel_communication_buf_fs_starting_vcn_t mk_win_base_far const* mk_lang_restrict mk_win_kernel_communication_buf_fs_starting_vcn_lprct;
typedef mk_win_kernel_communication_buf_fs_starting_vcn_t mk_win_base_near* mk_lang_restrict mk_win_kernel_communication_buf_fs_starting_vcn_nprt;
typedef mk_win_kernel_communication_buf_fs_starting_vcn_t mk_win_base_near const* mk_lang_restrict mk_win_kernel_communication_buf_fs_starting_vcn_nprct;

struct mk_win_kernel_communication_buf_fs_starting_lcn_s
{
	mk_win_base_large_integer_t m_starting_lcn;
};
typedef struct mk_win_kernel_communication_buf_fs_starting_lcn_s mk_win_kernel_communication_buf_fs_starting_lcn_t;
typedef mk_win_kernel_communication_buf_fs_starting_lcn_t const mk_win_kernel_communication_buf_fs_starting_lcn_ct;
typedef mk_win_kernel_communication_buf_fs_starting_lcn_t* mk_win_kernel_communication_buf_fs_starting_lcn_pt;
typedef mk_win_kernel_communication_buf_fs_starting_lcn_t const* mk_win_kernel_communication_buf_fs_starting_lcn_pct;
typedef mk_win_kernel_communication_buf_fs_starting_lcn_t mk_win_base_far* mk_win_kernel_communication_buf_fs_starting_lcn_lpt;
typedef mk_win_kernel_communication_buf_fs_starting_lcn_t mk_win_base_far const* mk_win_kernel_communication_buf_fs_starting_lcn_lpct;
typedef mk_win_kernel_communication_buf_fs_starting_lcn_t mk_win_base_near* mk_win_kernel_communication_buf_fs_starting_lcn_npt;
typedef mk_win_kernel_communication_buf_fs_starting_lcn_t mk_win_base_near const* mk_win_kernel_communication_buf_fs_starting_lcn_npct;
typedef mk_win_kernel_communication_buf_fs_starting_lcn_t* mk_lang_restrict mk_win_kernel_communication_buf_fs_starting_lcn_prt;
typedef mk_win_kernel_communication_buf_fs_starting_lcn_t const* mk_lang_restrict mk_win_kernel_communication_buf_fs_starting_lcn_prct;
typedef mk_win_kernel_communication_buf_fs_starting_lcn_t mk_win_base_far* mk_lang_restrict mk_win_kernel_communication_buf_fs_starting_lcn_lprt;
typedef mk_win_kernel_communication_buf_fs_starting_lcn_t mk_win_base_far const* mk_lang_restrict mk_win_kernel_communication_buf_fs_starting_lcn_lprct;
typedef mk_win_kernel_communication_buf_fs_starting_lcn_t mk_win_base_near* mk_lang_restrict mk_win_kernel_communication_buf_fs_starting_lcn_nprt;
typedef mk_win_kernel_communication_buf_fs_starting_lcn_t mk_win_base_near const* mk_lang_restrict mk_win_kernel_communication_buf_fs_starting_lcn_nprct;

struct mk_win_kernel_communication_buf_fs_retrieval_pointers_extent_s
{
	mk_win_base_large_integer_t m_next_vcn;
	mk_win_base_large_integer_t m_lcn;
};
typedef struct mk_win_kernel_communication_buf_fs_retrieval_pointers_extent_s mk_win_kernel_communication_buf_fs_retrieval_pointers_extent_t;

struct mk_win_kernel_communication_buf_fs_retrieval_pointers_s
{
	mk_win_base_dword_t m_extents_count;
	mk_win_base_large_integer_t m_starting_vcn;
	mk_win_kernel_communication_buf_fs_retrieval_pointers_extent_t m_extents[mk_win_base_anysize_array];
};
typedef struct mk_win_kernel_communication_buf_fs_retrieval_pointers_s mk_win_kernel_communication_buf_fs_retrieval_pointers_t;
typedef mk_win_kernel_communication_buf_fs_retrieval_pointers_t const mk_win_kernel_communication_buf_fs_retrieval_pointers_ct;
typedef mk_win_kernel_communication_buf_fs_retrieval_pointers_t* mk_win_kernel_communication_buf_fs_retrieval_pointers_pt;
typedef mk_win_kernel_communication_buf_fs_retrieval_pointers_t const* mk_win_kernel_communication_buf_fs_retrieval_pointers_pct;
typedef mk_win_kernel_communication_buf_fs_retrieval_pointers_t mk_win_base_far* mk_win_kernel_communication_buf_fs_retrieval_pointers_lpt;
typedef mk_win_kernel_communication_buf_fs_retrieval_pointers_t mk_win_base_far const* mk_win_kernel_communication_buf_fs_retrieval_pointers_lpct;
typedef mk_win_kernel_communication_buf_fs_retrieval_pointers_t mk_win_base_near* mk_win_kernel_communication_buf_fs_retrieval_pointers_npt;
typedef mk_win_kernel_communication_buf_fs_retrieval_pointers_t mk_win_base_near const* mk_win_kernel_communication_buf_fs_retrieval_pointers_npct;
typedef mk_win_kernel_communication_buf_fs_retrieval_pointers_t* mk_lang_restrict mk_win_kernel_communication_buf_fs_retrieval_pointers_prt;
typedef mk_win_kernel_communication_buf_fs_retrieval_pointers_t const* mk_lang_restrict mk_win_kernel_communication_buf_fs_retrieval_pointers_prct;
typedef mk_win_kernel_communication_buf_fs_retrieval_pointers_t mk_win_base_far* mk_lang_restrict mk_win_kernel_communication_buf_fs_retrieval_pointers_lprt;
typedef mk_win_kernel_communication_buf_fs_retrieval_pointers_t mk_win_base_far const* mk_lang_restrict mk_win_kernel_communication_buf_fs_retrieval_pointers_lprct;
typedef mk_win_kernel_communication_buf_fs_retrieval_pointers_t mk_win_base_near* mk_lang_restrict mk_win_kernel_communication_buf_fs_retrieval_pointers_nprt;
typedef mk_win_kernel_communication_buf_fs_retrieval_pointers_t mk_win_base_near const* mk_lang_restrict mk_win_kernel_communication_buf_fs_retrieval_pointers_nprct;

struct mk_win_kernel_communication_buf_fs_volume_bitmap_s
{
	mk_win_base_large_integer_t m_starting_lcn;
	mk_win_base_large_integer_t m_bitmap_len;
	mk_win_base_uchar_t m_buffer[mk_win_base_anysize_array];
};
typedef struct mk_win_kernel_communication_buf_fs_volume_bitmap_s mk_win_kernel_communication_buf_fs_volume_bitmap_t;
typedef mk_win_kernel_communication_buf_fs_volume_bitmap_t const mk_win_kernel_communication_buf_fs_volume_bitmap_ct;
typedef mk_win_kernel_communication_buf_fs_volume_bitmap_t* mk_win_kernel_communication_buf_fs_volume_bitmap_pt;
typedef mk_win_kernel_communication_buf_fs_volume_bitmap_t const* mk_win_kernel_communication_buf_fs_volume_bitmap_pct;
typedef mk_win_kernel_communication_buf_fs_volume_bitmap_t mk_win_base_far* mk_win_kernel_communication_buf_fs_volume_bitmap_lpt;
typedef mk_win_kernel_communication_buf_fs_volume_bitmap_t mk_win_base_far const* mk_win_kernel_communication_buf_fs_volume_bitmap_lpct;
typedef mk_win_kernel_communication_buf_fs_volume_bitmap_t mk_win_base_near* mk_win_kernel_communication_buf_fs_volume_bitmap_npt;
typedef mk_win_kernel_communication_buf_fs_volume_bitmap_t mk_win_base_near const* mk_win_kernel_communication_buf_fs_volume_bitmap_npct;
typedef mk_win_kernel_communication_buf_fs_volume_bitmap_t* mk_lang_restrict mk_win_kernel_communication_buf_fs_volume_bitmap_prt;
typedef mk_win_kernel_communication_buf_fs_volume_bitmap_t const* mk_lang_restrict mk_win_kernel_communication_buf_fs_volume_bitmap_prct;
typedef mk_win_kernel_communication_buf_fs_volume_bitmap_t mk_win_base_far* mk_lang_restrict mk_win_kernel_communication_buf_fs_volume_bitmap_lprt;
typedef mk_win_kernel_communication_buf_fs_volume_bitmap_t mk_win_base_far const* mk_lang_restrict mk_win_kernel_communication_buf_fs_volume_bitmap_lprct;
typedef mk_win_kernel_communication_buf_fs_volume_bitmap_t mk_win_base_near* mk_lang_restrict mk_win_kernel_communication_buf_fs_volume_bitmap_nprt;
typedef mk_win_kernel_communication_buf_fs_volume_bitmap_t mk_win_base_near const* mk_lang_restrict mk_win_kernel_communication_buf_fs_volume_bitmap_nprct;

struct mk_win_kernel_communication_buf_fs_move_file_s
{
	mk_win_base_handle_t m_file;
	mk_win_base_large_integer_t m_vcn;
	mk_win_base_large_integer_t m_lcn;
	mk_win_base_dword_t m_clusters;
};
typedef struct mk_win_kernel_communication_buf_fs_move_file_s mk_win_kernel_communication_buf_fs_move_file_t;
typedef mk_win_kernel_communication_buf_fs_move_file_t const mk_win_kernel_communication_buf_fs_move_file_ct;
typedef mk_win_kernel_communication_buf_fs_move_file_t* mk_win_kernel_communication_buf_fs_move_file_pt;
typedef mk_win_kernel_communication_buf_fs_move_file_t const* mk_win_kernel_communication_buf_fs_move_file_pct;
typedef mk_win_kernel_communication_buf_fs_move_file_t mk_win_base_far* mk_win_kernel_communication_buf_fs_move_file_lpt;
typedef mk_win_kernel_communication_buf_fs_move_file_t mk_win_base_far const* mk_win_kernel_communication_buf_fs_move_file_lpct;
typedef mk_win_kernel_communication_buf_fs_move_file_t mk_win_base_near* mk_win_kernel_communication_buf_fs_move_file_npt;
typedef mk_win_kernel_communication_buf_fs_move_file_t mk_win_base_near const* mk_win_kernel_communication_buf_fs_move_file_npct;
typedef mk_win_kernel_communication_buf_fs_move_file_t* mk_lang_restrict mk_win_kernel_communication_buf_fs_move_file_prt;
typedef mk_win_kernel_communication_buf_fs_move_file_t const* mk_lang_restrict mk_win_kernel_communication_buf_fs_move_file_prct;
typedef mk_win_kernel_communication_buf_fs_move_file_t mk_win_base_far* mk_lang_restrict mk_win_kernel_communication_buf_fs_move_file_lprt;
typedef mk_win_kernel_communication_buf_fs_move_file_t mk_win_base_far const* mk_lang_restrict mk_win_kernel_communication_buf_fs_move_file_lprct;
typedef mk_win_kernel_communication_buf_fs_move_file_t mk_win_base_near* mk_lang_restrict mk_win_kernel_communication_buf_fs_move_file_nprt;
typedef mk_win_kernel_communication_buf_fs_move_file_t mk_win_base_near const* mk_lang_restrict mk_win_kernel_communication_buf_fs_move_file_nprct;


mk_lang_nodiscard mk_lang_jumbo mk_win_base_bool_t mk_win_kernel_communication_device_io_control(mk_win_base_handle_t const device, mk_win_base_dword_t const control_code, mk_win_base_void_lpct const inbuf, mk_win_base_dword_t const inlen, mk_win_base_void_lpt const outbuf, mk_win_base_dword_t const outlen, mk_win_base_dword_lpt const written, mk_win_kernel_files_overlapped_lpt const overlapped) mk_lang_noexcept;


#if mk_lang_jumbo_want == 1
#include "mk_win_kernel_communication.c"
#endif
#endif
