#include "mk_lang_exception.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_types.h"
#include "mk_win_base.h"
#include "mk_win_tstring.h"


#include "mk_win_sl_file_ostream_buffered_inl_defd.h"


struct mk_win_sl_file_ostream_buffered_inl_defd_s
{
	mk_win_base_void_lpt m_state;
};
typedef struct mk_win_sl_file_ostream_buffered_inl_defd_s mk_win_sl_file_ostream_buffered_inl_defd_t;
typedef mk_win_sl_file_ostream_buffered_inl_defd_t const mk_win_sl_file_ostream_buffered_inl_defd_ct;
typedef mk_win_sl_file_ostream_buffered_inl_defd_t* mk_win_sl_file_ostream_buffered_inl_defd_pt;
typedef mk_win_sl_file_ostream_buffered_inl_defd_t const* mk_win_sl_file_ostream_buffered_inl_defd_pct;
typedef mk_win_sl_file_ostream_buffered_inl_defd_t mk_win_base_far* mk_win_sl_file_ostream_buffered_inl_defd_lpt;
typedef mk_win_sl_file_ostream_buffered_inl_defd_t mk_win_base_far const* mk_win_sl_file_ostream_buffered_inl_defd_lpct;
typedef mk_win_sl_file_ostream_buffered_inl_defd_t mk_win_base_near* mk_win_sl_file_ostream_buffered_inl_defd_npt;
typedef mk_win_sl_file_ostream_buffered_inl_defd_t mk_win_base_near const* mk_win_sl_file_ostream_buffered_inl_defd_npct;


mk_lang_jumbo void mk_win_sl_file_ostream_buffered_inl_defd_rw_reconstruct_from_file_handle(mk_win_sl_file_ostream_buffered_inl_defd_pt const ostream, mk_win_base_handle_t const file_handle, mk_lang_types_bool_t const own) mk_lang_noexcept;
mk_lang_jumbo void mk_win_sl_file_ostream_buffered_inl_defd_rw_reconstruct_from_file_name(mk_win_sl_file_ostream_buffered_inl_defd_pt const ostream, mk_lang_exception_pt const ex, mk_win_tstring_tchar_pct const file_name) mk_lang_noexcept;
mk_lang_jumbo void mk_win_sl_file_ostream_buffered_inl_defd_rw_construct_from_file_handle(mk_win_sl_file_ostream_buffered_inl_defd_pt const ostream, mk_lang_exception_pt const ex, mk_win_base_handle_t const file_handle, mk_lang_types_bool_t const own) mk_lang_noexcept;
mk_lang_jumbo void mk_win_sl_file_ostream_buffered_inl_defd_rw_construct_from_file_name(mk_win_sl_file_ostream_buffered_inl_defd_pt const ostream, mk_lang_exception_pt const ex, mk_win_tstring_tchar_pct const file_name) mk_lang_noexcept;
mk_lang_jumbo void mk_win_sl_file_ostream_buffered_inl_defd_rw_submit_write(mk_win_sl_file_ostream_buffered_inl_defd_pt const ostream, mk_lang_exception_pt const ex) mk_lang_noexcept;
mk_lang_jumbo void mk_win_sl_file_ostream_buffered_inl_defd_rw_close(mk_win_sl_file_ostream_buffered_inl_defd_pt const ostream, mk_lang_exception_pt const ex) mk_lang_noexcept;
mk_lang_jumbo void mk_win_sl_file_ostream_buffered_inl_defd_rw_destroy(mk_win_sl_file_ostream_buffered_inl_defd_pt const ostream) mk_lang_noexcept;
mk_lang_jumbo void mk_win_sl_file_ostream_buffered_inl_defd_rw_write(mk_win_sl_file_ostream_buffered_inl_defd_pt const ostream, mk_lang_exception_pt const ex, mk_lang_types_void_pt const source, mk_lang_types_usize_t const bytes_to_write, mk_lang_types_usize_pt const bytes_written) mk_lang_noexcept;


#include "mk_win_sl_file_ostream_buffered_inl_defu.h"
