#ifndef mk_include_guard_mk_win_dll_kernel_synchronization_waitable_timer_h
#define mk_include_guard_mk_win_dll_kernel_synchronization_waitable_timer_h


#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_typedef.h"
#include "mk_win_base.h"


struct mk_win_dll_kernel_synchronization_waitable_timer_detailed_reason_s
{
	mk_win_base_module_t m_localized_reason_module;
	mk_win_base_ulong_t m_localized_reason_id;
	mk_win_base_ulong_t m_reason_string_count;
	mk_win_base_wchar_lplpt m_reason_strings;
};
typedef struct mk_win_dll_kernel_synchronization_waitable_timer_detailed_reason_s mk_win_dll_kernel_synchronization_waitable_timer_detailed_reason_t;
struct mk_win_dll_kernel_synchronization_waitable_timer_simple_reason_s
{
	mk_win_base_wchar_lpt m_simple_reason_string;
};
typedef struct mk_win_dll_kernel_synchronization_waitable_timer_simple_reason_s mk_win_dll_kernel_synchronization_waitable_timer_simple_reason_t;
union mk_win_dll_kernel_synchronization_waitable_timer_all_reason_data_u
{
	mk_win_dll_kernel_synchronization_waitable_timer_simple_reason_t m_simple;
	mk_win_dll_kernel_synchronization_waitable_timer_detailed_reason_t m_detailed;
};
typedef union mk_win_dll_kernel_synchronization_waitable_timer_all_reason_data_u mk_win_dll_kernel_synchronization_waitable_timer_all_reason_data_t;
struct mk_win_dll_kernel_synchronization_waitable_timer_all_reason_s
{
	mk_win_dll_kernel_synchronization_waitable_timer_all_reason_data_t m_data;
};
typedef struct mk_win_dll_kernel_synchronization_waitable_timer_all_reason_s mk_win_dll_kernel_synchronization_waitable_timer_all_reason_t;
struct mk_win_dll_kernel_synchronization_waitable_timer_reason_context_s
{
  mk_win_base_ulong_t m_version;
  mk_win_base_dword_t m_flags;
	mk_win_dll_kernel_synchronization_waitable_timer_all_reason_t m_reason;
};
typedef struct mk_win_dll_kernel_synchronization_waitable_timer_reason_context_s mk_win_dll_kernel_synchronization_waitable_timer_reason_context_t;
mk_lang_typedef(mk_win_dll_kernel_synchronization_waitable_timer_reason_context);


mk_win_base_typedef_func(mk_win_base_void_t, mk_win_base_stdcall, mk_win_dll_kernel_synchronization_waitable_timer_completion_routine_t, (mk_win_base_void_lpt const completion_arg, mk_win_base_dword_t const timer_lo, mk_win_base_dword_t const timer_hi));


mk_lang_nodiscard mk_lang_jumbo mk_win_base_bool_t mk_win_dll_kernel_synchronization_waitable_timer_cancel_waitable_timer(mk_win_base_handle_t const timer) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_handle_t mk_win_dll_kernel_synchronization_waitable_timer_create_waitable_timer_w(mk_win_base_void_lpt const security_attributes, mk_win_base_bool_t const manual_reset, mk_win_base_wchar_lpct const name) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_handle_t mk_win_dll_kernel_synchronization_waitable_timer_create_waitable_timer_ex_w(mk_win_base_void_lpt const security_attributes, mk_win_base_wchar_lpct const name, mk_win_base_dword_t const flags, mk_win_base_dword_t const desired_access) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_handle_t mk_win_dll_kernel_synchronization_waitable_timer_open_waitable_timer_w(mk_win_base_dword_t const desired_access, mk_win_base_bool_t const inherit, mk_win_base_wchar_lpct const name) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_bool_t mk_win_dll_kernel_synchronization_waitable_timer_set_waitable_timer(mk_win_base_handle_t const timer, mk_win_base_large_integer_lpct const due_time, mk_win_base_slong_t const period, mk_win_dll_kernel_synchronization_waitable_timer_completion_routine_t const completion_routine, mk_win_base_void_lpt const completion_arg, mk_win_base_bool_t const resume) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_bool_t mk_win_dll_kernel_synchronization_waitable_timer_set_waitable_timer_ex(mk_win_base_handle_t const timer, mk_win_base_large_integer_lpct const due_time, mk_win_base_slong_t const period, mk_win_dll_kernel_synchronization_waitable_timer_completion_routine_t const completion_routine, mk_win_base_void_lpt const completion_arg, mk_win_dll_kernel_synchronization_waitable_timer_reason_context_lpt const wake_context, mk_win_base_ulong_t const tolerable_delay) mk_lang_noexcept;


#if mk_lang_jumbo_have
#include "mk_win_dll_kernel_synchronization_waitable_timer.c"
#endif
#endif
