#ifndef mk_include_guard_mk_win_dll_kernel_synchronization_event_h
#define mk_include_guard_mk_win_dll_kernel_synchronization_event_h


#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_win_base.h"


mk_lang_nodiscard mk_lang_jumbo mk_win_base_handle_t mk_win_dll_kernel_synchronization_event_create_event_a(mk_win_base_void_lpt const security_attributes, mk_win_base_bool_t const manual_reset, mk_win_base_bool_t const initial_state, mk_win_base_pchar_lpct const name) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_handle_t mk_win_dll_kernel_synchronization_event_create_event_w(mk_win_base_void_lpt const security_attributes, mk_win_base_bool_t const manual_reset, mk_win_base_bool_t const initial_state, mk_win_base_wchar_lpct const name) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_handle_t mk_win_dll_kernel_synchronization_event_create_event_ex_a(mk_win_base_void_lpt const security_attributes, mk_win_base_pchar_lpct const name, mk_win_base_dword_t const flags, mk_win_base_dword_t const desired_access) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_handle_t mk_win_dll_kernel_synchronization_event_create_event_ex_w(mk_win_base_void_lpt const security_attributes, mk_win_base_wchar_lpct const name, mk_win_base_dword_t const flags, mk_win_base_dword_t const desired_access) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_handle_t mk_win_dll_kernel_synchronization_event_open_event_a(mk_win_base_dword_t const desired_access, mk_win_base_bool_t const inherit, mk_win_base_pchar_lpct const name) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_handle_t mk_win_dll_kernel_synchronization_event_open_event_w(mk_win_base_dword_t const desired_access, mk_win_base_bool_t const inherit, mk_win_base_wchar_lpct const name) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_bool_t mk_win_dll_kernel_synchronization_event_pulse_event(mk_win_base_handle_t const event) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_bool_t mk_win_dll_kernel_synchronization_event_reset_event(mk_win_base_handle_t const event) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_bool_t mk_win_dll_kernel_synchronization_event_set_event(mk_win_base_handle_t const event) mk_lang_noexcept;


#if mk_lang_jumbo_have
#include "mk_win_dll_kernel_synchronization_event.c"
#endif
#endif
