#ifndef mk_include_guard_mk_win_dll_kernel_synchronization_critical_section_h
#define mk_include_guard_mk_win_dll_kernel_synchronization_critical_section_h


#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_typedef.h"
#include "mk_lang_types.h"
#include "mk_win_base.h"


mk_lang_forward(mk_win_dll_kernel_synchronization_critical_section_list_entry);
struct mk_win_dll_kernel_synchronization_critical_section_list_entry_s
{
	mk_win_dll_kernel_synchronization_critical_section_list_entry_pt m_next;
	mk_win_dll_kernel_synchronization_critical_section_list_entry_pt m_prev;
};
typedef struct mk_win_dll_kernel_synchronization_critical_section_list_entry_s mk_win_dll_kernel_synchronization_critical_section_list_entry_t;
mk_lang_typedef(mk_win_dll_kernel_synchronization_critical_section_list_entry);

#include "mk_lang_warning_msvc_push_c4820.h"
mk_lang_forward(mk_win_dll_kernel_synchronization_critical_section);
struct mk_win_dll_kernel_synchronization_critical_section_debug_s
{
	mk_win_base_word_t m_type;
	mk_win_base_word_t m_creator_back_trace_index;
	mk_win_dll_kernel_synchronization_critical_section_pt m_critical_section;
	mk_win_dll_kernel_synchronization_critical_section_list_entry_t m_process_locks_list;
	mk_win_base_dword_t m_entry_count;
	mk_win_base_dword_t m_contention_count;
	mk_win_base_dword_t m_flags;
	mk_win_base_word_t m_creator_back_trace_index_high;
	mk_win_base_word_t m_identifier;
};
typedef struct mk_win_dll_kernel_synchronization_critical_section_debug_s mk_win_dll_kernel_synchronization_critical_section_debug_t;
mk_lang_typedef(mk_win_dll_kernel_synchronization_critical_section_debug);
#include "mk_lang_warning_msvc_pop.h"

struct mk_win_dll_kernel_synchronization_critical_section_s
{
	mk_win_dll_kernel_synchronization_critical_section_debug_pt m_debug_info;
	mk_win_base_slong_t m_lock_count;
	mk_win_base_slong_t m_recursion_count;
	mk_win_base_handle_t m_owning_thread;
	mk_win_base_handle_t m_lock_semaphore;
	mk_win_base_uintptr_t m_spin_count;
};
typedef struct mk_win_dll_kernel_synchronization_critical_section_s mk_win_dll_kernel_synchronization_critical_section_t;
mk_lang_typedef(mk_win_dll_kernel_synchronization_critical_section);


mk_lang_jumbo mk_lang_types_void_t mk_win_dll_kernel_synchronization_critical_section_initialize_critical_section(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_bool_t mk_win_dll_kernel_synchronization_critical_section_initialize_critical_section_and_spin_count(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section, mk_win_base_dword_t const spin_count) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_bool_t mk_win_dll_kernel_synchronization_critical_section_initialize_critical_section_ex(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section, mk_win_base_dword_t const spin_count, mk_win_base_dword_t const flags) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_win_dll_kernel_synchronization_critical_section_delete_critical_section(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_dword_t mk_win_dll_kernel_synchronization_critical_section_set_critical_section_spin_count(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section, mk_win_base_dword_t const spin_count) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_win_dll_kernel_synchronization_critical_section_enter_critical_section(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section) mk_lang_noexcept;
mk_lang_jumbo mk_lang_types_void_t mk_win_dll_kernel_synchronization_critical_section_leave_critical_section(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section) mk_lang_noexcept;
mk_lang_nodiscard mk_lang_jumbo mk_win_base_bool_t mk_win_dll_kernel_synchronization_critical_section_try_enter_critical_section(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section) mk_lang_noexcept;


#if mk_lang_jumbo_have
#include "mk_win_dll_kernel_synchronization_critical_section.c"
#endif
#endif
