#ifndef mk_include_guard_mk_win_dll_kernel_synchronization_critical_section_c
#define mk_include_guard_mk_win_dll_kernel_synchronization_critical_section_c
#include "mk_win_dll_kernel_synchronization_critical_section.h"

#include "mk_lang_extern.h"
#include "mk_lang_jumbo.h"
#include "mk_lang_nodiscard.h"
#include "mk_lang_noexcept.h"
#include "mk_lang_types.h"
#include "mk_win_base.h"


mk_lang_extern_force_c mk_win_base_dll_import mk_lang_types_void_t mk_win_base_stdcall InitializeCriticalSection(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section) mk_lang_noexcept;
mk_lang_extern_force_c mk_lang_nodiscard mk_win_base_dll_import mk_win_base_bool_t mk_win_base_stdcall InitializeCriticalSectionAndSpinCount(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section, mk_win_base_dword_t const spin_count) mk_lang_noexcept;
mk_lang_extern_force_c mk_lang_nodiscard mk_win_base_dll_import mk_win_base_bool_t mk_win_base_stdcall InitializeCriticalSectionEx(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section, mk_win_base_dword_t const spin_count, mk_win_base_dword_t const flags) mk_lang_noexcept;
mk_lang_extern_force_c mk_win_base_dll_import mk_lang_types_void_t mk_win_base_stdcall DeleteCriticalSection(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section) mk_lang_noexcept;
mk_lang_extern_force_c mk_lang_nodiscard mk_win_base_dll_import mk_win_base_dword_t mk_win_base_stdcall SetCriticalSectionSpinCount(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section, mk_win_base_dword_t const spin_count) mk_lang_noexcept;
mk_lang_extern_force_c mk_win_base_dll_import mk_lang_types_void_t mk_win_base_stdcall EnterCriticalSection(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section) mk_lang_noexcept;
mk_lang_extern_force_c mk_win_base_dll_import mk_lang_types_void_t mk_win_base_stdcall LeaveCriticalSection(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section) mk_lang_noexcept;
mk_lang_extern_force_c mk_lang_nodiscard mk_win_base_dll_import mk_win_base_bool_t mk_win_base_stdcall TryEnterCriticalSection(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section) mk_lang_noexcept;


mk_lang_jumbo mk_lang_types_void_t mk_win_dll_kernel_synchronization_critical_section_initialize_critical_section(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section) mk_lang_noexcept
{
	InitializeCriticalSection(critical_section);
}

mk_lang_nodiscard mk_lang_jumbo mk_win_base_bool_t mk_win_dll_kernel_synchronization_critical_section_initialize_critical_section_and_spin_count(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section, mk_win_base_dword_t const spin_count) mk_lang_noexcept
{
	mk_win_base_bool_t ret;

	ret = InitializeCriticalSectionAndSpinCount(critical_section, spin_count);
	return ret;
}

mk_lang_nodiscard mk_lang_jumbo mk_win_base_bool_t mk_win_dll_kernel_synchronization_critical_section_initialize_critical_section_ex(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section, mk_win_base_dword_t const spin_count, mk_win_base_dword_t const flags) mk_lang_noexcept
{
	mk_win_base_bool_t ret;

	ret = InitializeCriticalSectionEx(critical_section, spin_count, flags);
	return ret;
}

mk_lang_jumbo mk_lang_types_void_t mk_win_dll_kernel_synchronization_critical_section_delete_critical_section(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section) mk_lang_noexcept
{
	DeleteCriticalSection(critical_section);
}

mk_lang_nodiscard mk_lang_jumbo mk_win_base_dword_t mk_win_dll_kernel_synchronization_critical_section_set_critical_section_spin_count(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section, mk_win_base_dword_t const spin_count) mk_lang_noexcept
{
	mk_win_base_dword_t ret;

	ret = SetCriticalSectionSpinCount(critical_section, spin_count);
	return ret;
}

mk_lang_jumbo mk_lang_types_void_t mk_win_dll_kernel_synchronization_critical_section_enter_critical_section(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section) mk_lang_noexcept
{
	EnterCriticalSection(critical_section);
}

mk_lang_jumbo mk_lang_types_void_t mk_win_dll_kernel_synchronization_critical_section_leave_critical_section(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section) mk_lang_noexcept
{
	LeaveCriticalSection(critical_section);
}

mk_lang_nodiscard mk_lang_jumbo mk_win_base_bool_t mk_win_dll_kernel_synchronization_critical_section_try_enter_critical_section(mk_win_dll_kernel_synchronization_critical_section_lpt const critical_section) mk_lang_noexcept
{
	mk_win_base_bool_t ret;

	ret = TryEnterCriticalSection(critical_section);
	return ret;
}


#endif
