#undef mk_win_sl_file_istream_buffered_inl_defd_count
#undef mk_win_sl_file_istream_buffered_inl_defd_size
#undef mk_win_sl_file_istream_buffered_inl_defd_bytes

#undef mk_win_sl_file_istream_buffered_inl_defd_prefix

#undef mk_win_sl_file_istream_buffered_inl_defd_s
#undef mk_win_sl_file_istream_buffered_inl_defd_t
#undef mk_win_sl_file_istream_buffered_inl_defd_ct
#undef mk_win_sl_file_istream_buffered_inl_defd_pt
#undef mk_win_sl_file_istream_buffered_inl_defd_pct
#undef mk_win_sl_file_istream_buffered_inl_defd_lpt
#undef mk_win_sl_file_istream_buffered_inl_defd_lpct
#undef mk_win_sl_file_istream_buffered_inl_defd_npt
#undef mk_win_sl_file_istream_buffered_inl_defd_npct

#undef mk_win_sl_file_istream_buffered_inl_defd_state_s
#undef mk_win_sl_file_istream_buffered_inl_defd_state_t
#undef mk_win_sl_file_istream_buffered_inl_defd_state_ct
#undef mk_win_sl_file_istream_buffered_inl_defd_state_pt
#undef mk_win_sl_file_istream_buffered_inl_defd_state_pct
#undef mk_win_sl_file_istream_buffered_inl_defd_state_lpt
#undef mk_win_sl_file_istream_buffered_inl_defd_state_lpct
#undef mk_win_sl_file_istream_buffered_inl_defd_state_npt
#undef mk_win_sl_file_istream_buffered_inl_defd_state_npct

#undef mk_win_sl_file_istream_buffered_inl_defd_rw_init_last
#undef mk_win_sl_file_istream_buffered_inl_defd_rw_submit_read
#undef mk_win_sl_file_istream_buffered_inl_defd_rw_wait_read

#undef mk_win_sl_file_istream_buffered_inl_defd_rw_construct_from_file_handle
#undef mk_win_sl_file_istream_buffered_inl_defd_rw_construct_from_file_name
#undef mk_win_sl_file_istream_buffered_inl_defd_rw_destroy
#undef mk_win_sl_file_istream_buffered_inl_defd_rw_read
