#undef mk_win_sl_file_ostream_buffered_inl_defd_count
#undef mk_win_sl_file_ostream_buffered_inl_defd_size
#undef mk_win_sl_file_ostream_buffered_inl_defd_bytes

#undef mk_win_sl_file_ostream_buffered_inl_defd_prefix

#undef mk_win_sl_file_ostream_buffered_inl_defd_s
#undef mk_win_sl_file_ostream_buffered_inl_defd_t
#undef mk_win_sl_file_ostream_buffered_inl_defd_ct
#undef mk_win_sl_file_ostream_buffered_inl_defd_pt
#undef mk_win_sl_file_ostream_buffered_inl_defd_pct
#undef mk_win_sl_file_ostream_buffered_inl_defd_lpt
#undef mk_win_sl_file_ostream_buffered_inl_defd_lpct
#undef mk_win_sl_file_ostream_buffered_inl_defd_npt
#undef mk_win_sl_file_ostream_buffered_inl_defd_npct

#undef mk_win_sl_file_ostream_buffered_inl_defd_overlapped2_s
#undef mk_win_sl_file_ostream_buffered_inl_defd_overlapped2_t
#undef mk_win_sl_file_ostream_buffered_inl_defd_overlapped2_ct
#undef mk_win_sl_file_ostream_buffered_inl_defd_overlapped2_pt
#undef mk_win_sl_file_ostream_buffered_inl_defd_overlapped2_pct
#undef mk_win_sl_file_ostream_buffered_inl_defd_overlapped2_lpt
#undef mk_win_sl_file_ostream_buffered_inl_defd_overlapped2_lpct
#undef mk_win_sl_file_ostream_buffered_inl_defd_overlapped2_npt
#undef mk_win_sl_file_ostream_buffered_inl_defd_overlapped2_npct

#undef mk_win_sl_file_ostream_buffered_inl_defd_state_s
#undef mk_win_sl_file_ostream_buffered_inl_defd_state_t
#undef mk_win_sl_file_ostream_buffered_inl_defd_state_ct
#undef mk_win_sl_file_ostream_buffered_inl_defd_state_pt
#undef mk_win_sl_file_ostream_buffered_inl_defd_state_pct
#undef mk_win_sl_file_ostream_buffered_inl_defd_state_lpt
#undef mk_win_sl_file_ostream_buffered_inl_defd_state_lpct
#undef mk_win_sl_file_ostream_buffered_inl_defd_state_npt
#undef mk_win_sl_file_ostream_buffered_inl_defd_state_npct

#undef mk_win_sl_file_ostream_buffered_inl_defd_private_rw_construct
#undef mk_win_sl_file_ostream_buffered_inl_defd_private_rw_open_file_name
#undef mk_win_sl_file_ostream_buffered_inl_defd_private_rw_submit_write_curr_and_advance
#undef mk_win_sl_file_ostream_buffered_inl_defd_private_rw_wait_idx
#undef mk_win_sl_file_ostream_buffered_inl_defd_private_rw_wait_write_curr_and_prepare_curr_based_on_prev

#undef mk_win_sl_file_ostream_buffered_inl_defd_rw_construct_from_file_handle
#undef mk_win_sl_file_ostream_buffered_inl_defd_rw_construct_from_file_name
#undef mk_win_sl_file_ostream_buffered_inl_defd_rw_close
#undef mk_win_sl_file_ostream_buffered_inl_defd_rw_destroy
#undef mk_win_sl_file_ostream_buffered_inl_defd_rw_write
