<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<mk_is_32bit Condition="'$(Platform)'=='ARM'">true</mk_is_32bit>
		<mk_is_32bit Condition="'$(Platform)'=='ARM64'">false</mk_is_32bit>
		<mk_is_32bit Condition="'$(Platform)'=='ARM64EC'">false</mk_is_32bit>
		<mk_is_32bit Condition="'$(Platform)'=='Win32'">true</mk_is_32bit>
		<mk_is_32bit Condition="'$(Platform)'=='x64'">false</mk_is_32bit>
		<mk_is_64bit Condition="'$(Platform)'=='ARM'">false</mk_is_64bit>
		<mk_is_64bit Condition="'$(Platform)'=='ARM64'">true</mk_is_64bit>
		<mk_is_64bit Condition="'$(Platform)'=='ARM64EC'">true</mk_is_64bit>
		<mk_is_64bit Condition="'$(Platform)'=='Win32'">false</mk_is_64bit>
		<mk_is_64bit Condition="'$(Platform)'=='x64'">true</mk_is_64bit>
		<mk_is_arm Condition="'$(Platform)'=='ARM'">true</mk_is_arm>
		<mk_is_arm Condition="'$(Platform)'=='ARM64'">true</mk_is_arm>
		<mk_is_arm Condition="'$(Platform)'=='ARM64EC'">true</mk_is_arm>
		<mk_is_arm Condition="'$(Platform)'=='Win32'">false</mk_is_arm>
		<mk_is_arm Condition="'$(Platform)'=='x64'">false</mk_is_arm>
		<mk_is_clang Condition="'$(Configuration)'=='DebugMSVC'">false</mk_is_clang>
		<mk_is_clang Condition="'$(Configuration)'=='DebugClang'">true</mk_is_clang>
		<mk_is_clang Condition="'$(Configuration)'=='ReleaseMSVC'">false</mk_is_clang>
		<mk_is_clang Condition="'$(Configuration)'=='ReleaseClang'">true</mk_is_clang>
		<mk_is_debug Condition="'$(Configuration)'=='DebugMSVC'">true</mk_is_debug>
		<mk_is_debug Condition="'$(Configuration)'=='DebugClang'">true</mk_is_debug>
		<mk_is_debug Condition="'$(Configuration)'=='ReleaseMSVC'">false</mk_is_debug>
		<mk_is_debug Condition="'$(Configuration)'=='ReleaseClang'">false</mk_is_debug>
		<mk_is_intel Condition="'$(Platform)'=='ARM'">false</mk_is_intel>
		<mk_is_intel Condition="'$(Platform)'=='ARM64'">false</mk_is_intel>
		<mk_is_intel Condition="'$(Platform)'=='ARM64EC'">false</mk_is_intel>
		<mk_is_intel Condition="'$(Platform)'=='Win32'">true</mk_is_intel>
		<mk_is_intel Condition="'$(Platform)'=='x64'">true</mk_is_intel>
		<mk_is_msvc Condition="'$(Configuration)'=='DebugMSVC'">true</mk_is_msvc>
		<mk_is_msvc Condition="'$(Configuration)'=='DebugClang'">false</mk_is_msvc>
		<mk_is_msvc Condition="'$(Configuration)'=='ReleaseMSVC'">true</mk_is_msvc>
		<mk_is_msvc Condition="'$(Configuration)'=='ReleaseClang'">false</mk_is_msvc>
		<mk_is_release Condition="'$(Configuration)'=='DebugMSVC'">false</mk_is_release>
		<mk_is_release Condition="'$(Configuration)'=='DebugClang'">false</mk_is_release>
		<mk_is_release Condition="'$(Configuration)'=='ReleaseMSVC'">true</mk_is_release>
		<mk_is_release Condition="'$(Configuration)'=='ReleaseClang'">true</mk_is_release>
	</PropertyGroup>
	<PropertyGroup>
		<mk_project>$(RootNamespace)</mk_project>
		<mk_is_entry_point Condition="'$(mk_project)' != 'mk_clib_slib' And '$(mk_project)' != 'mk_clib_test' And '$(mk_project)' != 'mk_clib_fuzz' And '$(mk_is_release)' == 'true' And '$(mk_is_intel)' == 'true'">true</mk_is_entry_point>
		<mk_is_entry_point Condition="!('$(mk_project)' != 'mk_clib_slib' And '$(mk_project)' != 'mk_clib_test' And '$(mk_project)' != 'mk_clib_fuzz' And '$(mk_is_release)' == 'true' And '$(mk_is_intel)' == 'true')">false</mk_is_entry_point>
	</PropertyGroup>
	<PropertyGroup>
		<!--<ExtensionsToDeleteOnClean>*.cdf;*.cache;*.obj;*.obj.enc;*.ilk;*.ipdb;*.iobj;*.resources;*.tlb;*.tli;*.tlh;*.tmp;*.rsp;*.pgc;*.pgd;*.meta;*.tlog;*.manifest;*.res;*.pch;*.exp;*.idb;*.rep;*.xdc;*.pdb;*_manifest.rc;*.bsc;*.sbr;*.xml;*.metagen;*.bi</ExtensionsToDeleteOnClean>-->
		<!--<TargetExt>.exe</TargetExt>-->
		<CopyCppRuntimeToOutputDir>false</CopyCppRuntimeToOutputDir>
		<CopyLocalDebugSymbols>false</CopyLocalDebugSymbols>
		<CopyLocalDeploymentContent>false</CopyLocalDeploymentContent>
		<CopyLocalProjectReference>false</CopyLocalProjectReference>
		<EnableManagedIncrementalBuild>false</EnableManagedIncrementalBuild>
		<IntDir>$(SolutionDir)build\int\$(RootNamespace)\$(Platform)\$(Configuration)\</IntDir>
		<ManagedAssembly>false</ManagedAssembly>
		<OutDir>$(SolutionDir)build\out\$(Platform)\$(Configuration)\</OutDir>
		<TargetName>$(RootNamespace)</TargetName>
		<UseStructuredOutput>true</UseStructuredOutput>
	</PropertyGroup>
</Project>
