<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ImportGroup Label="ExtensionSettings">
		<Import Project="$(VCTargetsPath)\BuildCustomizations\masm.props"/>
	</ImportGroup>
	<ImportGroup Label="Shared"/>
	<ImportGroup Label="PropertySheets">
		<Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform"/>
	</ImportGroup>
	<PropertyGroup Label="UserMacros"/>
	<ItemDefinitionGroup>
		<ClCompile>
			<AdditionalIncludeDirectories></AdditionalIncludeDirectories>
			<AdditionalUsingDirectories></AdditionalUsingDirectories>
			<AdditionalBMIDirectories></AdditionalBMIDirectories>
			<AdditionalModuleDependencies></AdditionalModuleDependencies>
			<AdditionalHeaderUnitDependencies></AdditionalHeaderUnitDependencies>
			<ScanSourceForModuleDependencies>false</ScanSourceForModuleDependencies>
			<TranslateIncludes>false</TranslateIncludes>
			<DebugInformationFormat Condition="'$(mk_is_debug)'=='true'">ProgramDatabase</DebugInformationFormat>
			<DebugInformationFormat Condition="'$(mk_is_release)'=='true'">None</DebugInformationFormat>
			<SupportJustMyCode Condition="'$(mk_is_debug)'=='true'">true</SupportJustMyCode>
			<SupportJustMyCode Condition="'$(mk_is_release)'=='true'">false</SupportJustMyCode>
			<UseDynamicDebugging Condition="'$(mk_is_debug)'=='true'">false</UseDynamicDebugging>
			<UseDynamicDebugging Condition="'$(mk_is_debug)'=='true'">false</UseDynamicDebugging>
			<UseDynamicDebugging Condition="'$(mk_is_release)'=='true'">false</UseDynamicDebugging>
			<CompileAsManaged>false</CompileAsManaged>
			<CompileAsWinRT>false</CompileAsWinRT>
			<SuppressStartupBanner>true</SuppressStartupBanner>
			<WarningLevel>EnableAllWarnings</WarningLevel>
			<TreatWarningAsError>true</TreatWarningAsError>
			<WarningVersion></WarningVersion>
			<DiagnosticsFormat>Column</DiagnosticsFormat>
			<SDLCheck Condition="'$(mk_is_debug)'=='true'">true</SDLCheck>
			<SDLCheck Condition="'$(mk_is_release)'=='true'">false</SDLCheck>
			<MultiProcessorCompilation>true</MultiProcessorCompilation>
		</ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup>
		<ClCompile>
			<Optimization Condition="'$(mk_is_debug)'=='true'">Disabled</Optimization>
			<InlineFunctionExpansion Condition="'$(mk_is_debug)'=='true'">Disabled</InlineFunctionExpansion>
			<IntrinsicFunctions Condition="'$(mk_is_debug)'=='true'">false</IntrinsicFunctions>
			<FavorSizeOrSpeed Condition="'$(mk_is_debug)'=='true'">Neither</FavorSizeOrSpeed>
			<OmitFramePointers Condition="'$(mk_is_debug)'=='true'">false</OmitFramePointers>
			<EnableFiberSafeOptimizations Condition="'$(mk_is_debug)'=='true'">false</EnableFiberSafeOptimizations>
			<WholeProgramOptimization Condition="'$(mk_is_debug)'=='true'">false</WholeProgramOptimization>
			<Optimization Condition="'$(mk_is_release)'=='true'">MaxSpeed</Optimization>
			<InlineFunctionExpansion Condition="'$(mk_is_release)'=='true'">AnySuitable</InlineFunctionExpansion>
			<IntrinsicFunctions Condition="'$(mk_is_release)'=='true'">true</IntrinsicFunctions>
			<FavorSizeOrSpeed Condition="'$(mk_is_release)'=='true'">Speed</FavorSizeOrSpeed>
			<OmitFramePointers Condition="'$(mk_is_release)'=='true'">true</OmitFramePointers>
			<EnableFiberSafeOptimizations Condition="'$(mk_is_release)'=='true'">true</EnableFiberSafeOptimizations>
			<WholeProgramOptimization Condition="'$(mk_is_release)'=='true'">true</WholeProgramOptimization>
		</ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup>
		<ClCompile>
			<PreprocessorDefinitions Condition="'$(mk_is_asan)'!='true'">mk_lang_asan_has=0;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions Condition="'$(mk_is_asan)'=='true'">mk_lang_asan_has=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions Condition="'$(mk_is_debug)'=='true' Or '$(mk_project)'=='mk_clib_fuzz' Or '$(mk_project)'=='mk_clib_test'">mk_lang_assert_crash_want=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions Condition="'$(mk_is_debug)'=='true' Or '$(mk_project)'=='mk_clib_fuzz' Or '$(mk_project)'=='mk_clib_test'">mk_lang_assert_want=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions Condition="'$(mk_is_debug)'=='true' Or '$(mk_project)'=='mk_clib_fuzz' Or '$(mk_project)'=='mk_clib_test'">mk_lang_crash_detail_want=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions Condition="'$(mk_is_debug)'=='true' Or '$(mk_project)'=='mk_clib_fuzz' Or '$(mk_project)'=='mk_clib_test'">mk_lang_test_detail_want=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions Condition="'$(mk_is_debug)'=='true'">_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions Condition="'$(mk_is_debug)'=='true'">DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions Condition="'$(mk_is_entry_point)'=='true'">mk_lang_entry_point_want=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions Condition="'$(mk_is_fuzzer)'!='true'">mk_lang_fuzzer_has=0;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions Condition="'$(mk_is_fuzzer)'=='true'">mk_lang_fuzzer_has=1;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions Condition="'$(mk_is_release)'=='true'">_NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions Condition="'$(mk_is_release)'=='true'">NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions>_ALLOW_RTCc_IN_STL;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions>_UNICODE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions>UNICODE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<UndefinePreprocessorDefinitions>%(UndefinePreprocessorDefinitions)</UndefinePreprocessorDefinitions>
			<UndefineAllPreprocessorDefinitions>false</UndefineAllPreprocessorDefinitions>
			<IgnoreStandardIncludePath>false</IgnoreStandardIncludePath>
			<PreprocessToFile>false</PreprocessToFile>
			<PreprocessSuppressLineNumbers>false</PreprocessSuppressLineNumbers>
			<PreprocessKeepComments>false</PreprocessKeepComments>
			<UseStandardPreprocessor>true</UseStandardPreprocessor>
		</ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup>
		<ClCompile>
			<StringPooling Condition="'$(mk_is_debug)'=='true'">false</StringPooling>
			<StringPooling Condition="'$(mk_is_release)'=='true'">true</StringPooling>
			<MinimalRebuild>false</MinimalRebuild>
			<ExceptionHandling Condition="'$(mk_is_debug)'=='true'">Sync</ExceptionHandling>
			<ExceptionHandling Condition="'$(mk_is_release)'=='true'">false</ExceptionHandling>
			<SmallerTypeCheck>false</SmallerTypeCheck><!-- buggy? -->
			<BasicRuntimeChecks Condition="'$(mk_is_debug)'=='true'">EnableFastChecks</BasicRuntimeChecks>
			<BasicRuntimeChecks Condition="'$(mk_is_release)'=='true'">Default</BasicRuntimeChecks>
			<RuntimeLibrary Condition="'$(mk_is_debug)'=='true'">MultiThreadedDebugDLL</RuntimeLibrary>
			<RuntimeLibrary Condition="'$(mk_is_release)'=='true'">MultiThreaded</RuntimeLibrary>
			<StructMemberAlignment>Default</StructMemberAlignment>
			<BufferSecurityCheck Condition="'$(mk_is_debug)'=='true'">true</BufferSecurityCheck>
			<BufferSecurityCheck Condition="'$(mk_is_release)'=='true'">false</BufferSecurityCheck>
			<ControlFlowGuard Condition="'$(mk_is_debug)'=='true'">Guard</ControlFlowGuard>
			<ControlFlowGuard Condition="'$(mk_is_release)'=='true'">false</ControlFlowGuard>
			<FunctionLevelLinking Condition="'$(mk_is_debug)'=='true'">false</FunctionLevelLinking>
			<FunctionLevelLinking Condition="'$(mk_is_release)'=='true'">true</FunctionLevelLinking>
			<EnableParallelCodeGeneration>false</EnableParallelCodeGeneration>
			<EnableEnhancedInstructionSet>NotSet</EnableEnhancedInstructionSet>
			<EnableVectorLength>NotSet</EnableVectorLength>
			<FloatingPointModel>Precise</FloatingPointModel>
			<FloatingPointExceptions>false</FloatingPointExceptions>
			<CreateHotpatchableImage>false</CreateHotpatchableImage>
			<IntelJCCErratum Condition="'$(mk_is_debug)'=='true'">true</IntelJCCErratum>
			<IntelJCCErratum Condition="'$(mk_is_release)'=='true'">false</IntelJCCErratum>
			<GuardEHContMetadata Condition="'$(mk_is_intel)'=='true' And '$(mk_is_64bit)'=='true'">true</GuardEHContMetadata>
			<GuardEHContMetadata Condition="'$(mk_is_release)'=='true'">false</GuardEHContMetadata>
			<!--<GuardSignedReturns>false</GuardSignedReturns>-->
		</ClCompile>
	</ItemDefinitionGroup>
	<PropertyGroup Label="Configuration">
		<SpectreMitigation>false</SpectreMitigation>
	</PropertyGroup>
	<ItemDefinitionGroup>
		<ClCompile>
			<DisableLanguageExtensions>false</DisableLanguageExtensions>
			<TreatWChar_tAsBuiltInType>true</TreatWChar_tAsBuiltInType>
			<ForceConformanceInForLoopScope>true</ForceConformanceInForLoopScope>
			<RemoveUnreferencedCodeData>true</RemoveUnreferencedCodeData>
			<EnforceTypeConversionRules>true</EnforceTypeConversionRules>
			<RuntimeTypeInfo Condition="'$(mk_is_debug)'=='true'">true</RuntimeTypeInfo>
			<RuntimeTypeInfo Condition="'$(mk_is_release)'=='true'">false</RuntimeTypeInfo>
			<OpenMPSupport>false</OpenMPSupport>
			<LanguageStandard>stdcpp20</LanguageStandard>
			<LanguageStandard_C>stdc17</LanguageStandard_C>
			<ConformanceMode>true</ConformanceMode>
			<EnableModules>false</EnableModules>
			<BuildStlModules>false</BuildStlModules>
		</ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup>
		<ClCompile>
			<PrecompiledHeader>NotUsing</PrecompiledHeader>
			<PrecompiledHeaderFile>stdafx.h</PrecompiledHeaderFile>
			<PrecompiledHeaderOutputFile>$(IntDir)$(TargetName).pch</PrecompiledHeaderOutputFile>
		</ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup>
		<ClCompile>
			<ExpandAttributedSource>false</ExpandAttributedSource>
			<AssemblerOutput>NoListing</AssemblerOutput>
			<UseUnicodeForAssemblerListing></UseUnicodeForAssemblerListing>
			<AssemblerListingLocation>$(IntDir)</AssemblerListingLocation>
			<ModuleOutputFile>$(IntDir)</ModuleOutputFile>
			<ModuleDependenciesFile>$(IntDir)</ModuleDependenciesFile>
			<ObjectFileName>$(IntDir)</ObjectFileName>
			<ProgramDataBaseFileName>$(IntDir)vc$(PlatformToolsetVersion).pdb</ProgramDataBaseFileName>
			<GenerateXMLDocumentationFiles>false</GenerateXMLDocumentationFiles>
			<XMLDocumentationFileName>$(IntDir)</XMLDocumentationFileName>
			<GenerateSourceDependencies>false</GenerateSourceDependencies>
			<SourceDependenciesFile>$(IntDir)</SourceDependenciesFile>
		</ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup>
		<ClCompile>
			<BrowseInformation>false</BrowseInformation>
			<BrowseInformationFile>$(IntDir)</BrowseInformationFile>
		</ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup>
		<ClCompile>
			<TreatAngleIncludeAsExternal>true</TreatAngleIncludeAsExternal>
			<ExternalWarningLevel>TurnOffAllWarnings</ExternalWarningLevel>
			<ExternalTemplatesDiagnostics>false</ExternalTemplatesDiagnostics>
			<DisableAnalyzeExternal>true</DisableAnalyzeExternal>
			<AnalyzeExternalRuleset>AllRules.ruleset</AnalyzeExternalRuleset>
		</ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup>
		<ClCompile>
			<CallingConvention>Cdecl</CallingConvention>
			<CompileAs Condition="'$(mk_project)'=='mk_clib_slib'">Default</CompileAs>
			<CompileAs Condition="'$(mk_project)'!='mk_clib_slib'">CompileAsCpp</CompileAs>
			<DisableSpecificWarnings>4464;%(DisableSpecificWarnings)</DisableSpecificWarnings><!-- warning C4464: relative include path contains '..' -->
			<DisableSpecificWarnings>4514;%(DisableSpecificWarnings)</DisableSpecificWarnings><!-- warning C4514: 'xxx': unreferenced inline function has been removed -->
			<DisableSpecificWarnings>4557;%(DisableSpecificWarnings)</DisableSpecificWarnings><!-- warning C4557: '__assume' contains effect '=' -->
			<DisableSpecificWarnings>4577;%(DisableSpecificWarnings)</DisableSpecificWarnings><!-- warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc -->
			<DisableSpecificWarnings>4710;%(DisableSpecificWarnings)</DisableSpecificWarnings><!-- warning C4710: 'xxx': function not inlined -->
			<DisableSpecificWarnings>4711;%(DisableSpecificWarnings)</DisableSpecificWarnings><!-- warning C4711: function 'xxx' selected for automatic inline expansion -->
			<DisableSpecificWarnings>5045;%(DisableSpecificWarnings)</DisableSpecificWarnings><!-- warning C5045: Compiler will insert Spectre mitigation for memory load if /Qspectre switch specified -->
			<DisableSpecificWarnings>5072;%(DisableSpecificWarnings)</DisableSpecificWarnings><!-- warning C5072: ASAN enabled without debug information emission. Enable debug info for better ASAN error reporting -->
			<DisableSpecificWarnings>5287;%(DisableSpecificWarnings)</DisableSpecificWarnings><!-- warning C5287: operands are different enum types 'xxx' and 'xxx'; use an explicit cast to silence this warning -->
			<DisableSpecificWarnings Condition="'$(mk_is_release)'=='true'">4127;%(DisableSpecificWarnings)</DisableSpecificWarnings><!-- warning C4127: conditional expression is constant -->
			<ForcedIncludeFiles></ForcedIncludeFiles>
			<ForcedUsingFiles></ForcedUsingFiles>
			<ShowIncludes>false</ShowIncludes>
			<UseFullPaths>true</UseFullPaths>
			<OmitDefaultLibName>false</OmitDefaultLibName>
			<ErrorReporting>None</ErrorReporting>
			<TreatSpecificWarningsAsErrors></TreatSpecificWarningsAsErrors>
		</ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup>
		<ClCompile>
			<AdditionalOptions Condition="'$(mk_is_entry_point)'=='true'">/Gs2097152 %(AdditionalOptions)</AdditionalOptions>
			<AdditionalOptions Condition="'$(mk_is_msvc)'=='true'">/constexpr:steps1000000000 %(AdditionalOptions)</AdditionalOptions>
			<AdditionalOptions>/bigobj %(AdditionalOptions)</AdditionalOptions>
		</ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup>
		<Link>
			<OutputFile>$(OutDir)$(TargetName)$(TargetExt)</OutputFile>
			<ShowProgress>NotSet</ShowProgress>
			<Version></Version>
			<IncrementalLinkDatabaseFile>$(IntDir)$(TargetName).ilk</IncrementalLinkDatabaseFile>
			<SuppressStartupBanner>true</SuppressStartupBanner>
			<RegisterOutput>false</RegisterOutput>
			<PerUserRedirection>false</PerUserRedirection>
			<AdditionalLibraryDirectories>$(OutDir)</AdditionalLibraryDirectories>
			<LinkStatus></LinkStatus>
			<PreventDllBinding>true</PreventDllBinding>
			<TreatLinkerWarningAsErrors>true</TreatLinkerWarningAsErrors>
			<ForceFileOutput></ForceFileOutput>
			<CreateHotPatchableImage></CreateHotPatchableImage>
			<SpecifySectionAttributes>%(SpecifySectionAttributes)</SpecifySectionAttributes>
		</Link>
	</ItemDefinitionGroup>
	<PropertyGroup>
		<LinkIncremental>false</LinkIncremental>
		<IgnoreImportLibrary>false</IgnoreImportLibrary>
	</PropertyGroup>
	<ItemDefinitionGroup>
		<ProjectReference>
			<LinkLibraryDependencies>true</LinkLibraryDependencies>
			<UseLibraryDependencyInputs>false</UseLibraryDependencyInputs>
		</ProjectReference>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup>
		<Link>
			<AdditionalDependencies Condition="'$(RootNamespace)'!='mk_clib_slib' And '$(mk_is_debug)'=='true'">mk_clib_slib.lib;%(AdditionalDependencies)</AdditionalDependencies>
			<IgnoreAllDefaultLibraries Condition="'$(mk_is_entry_point)'=='false'">false</IgnoreAllDefaultLibraries>
			<IgnoreAllDefaultLibraries Condition="'$(mk_is_entry_point)'=='true'">true</IgnoreAllDefaultLibraries>
			<IgnoreSpecificDefaultLibraries>%(IgnoreSpecificDefaultLibraries)</IgnoreSpecificDefaultLibraries>
			<ModuleDefinitionFile></ModuleDefinitionFile>
			<AddModuleNamesToAssembly>%(AddModuleNamesToAssembly)</AddModuleNamesToAssembly>
			<EmbedManagedResourceFile>%(EmbedManagedResourceFile)</EmbedManagedResourceFile>
			<ForceSymbolReferences>%(ForceSymbolReferences)</ForceSymbolReferences>
			<DelayLoadDLLs>%(DelayLoadDLLs)</DelayLoadDLLs>
			<AssemblyLinkResource>%(AssemblyLinkResource)</AssemblyLinkResource>
		</Link>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup>
		<Link>
			<ManifestFile>$(IntDir)$(TargetName)$(TargetExt).intermediate.manifest</ManifestFile>
			<AdditionalManifestDependencies>%(AdditionalManifestDependencies)</AdditionalManifestDependencies>
			<AllowIsolation>true</AllowIsolation>
			<EnableUAC>true</EnableUAC>
			<UACExecutionLevel>AsInvoker</UACExecutionLevel>
			<UACUIAccess>false</UACUIAccess>
		</Link>
	</ItemDefinitionGroup>
	<PropertyGroup>
		<GenerateManifest>true</GenerateManifest>
	</PropertyGroup>
	<ItemDefinitionGroup>
		<Link>
			<GenerateDebugInformation Condition="'$(mk_is_debug)'=='true'">DebugFastLink</GenerateDebugInformation>
			<GenerateDebugInformation Condition="'$(mk_is_release)'=='true'">false</GenerateDebugInformation>
			<ProgramDatabaseFile>$(OutDir)$(TargetName).pdb</ProgramDatabaseFile>
			<StripPrivateSymbols></StripPrivateSymbols>
			<GenerateMapFile>false</GenerateMapFile>
			<MapFileName></MapFileName>
			<MapExports>false</MapExports>
			<AssemblyDebug>true</AssemblyDebug>
			<UseDynamicDebugging>false</UseDynamicDebugging>
		</Link>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup>
		<Link>
			<SubSystem>Console</SubSystem>
			<MinimumRequiredVersion></MinimumRequiredVersion>
			<HeapReserveSize></HeapReserveSize>
			<HeapCommitSize></HeapCommitSize>
			<StackReserveSize Condition="'$(mk_is_release)'=='true'">1048576</StackReserveSize>
			<StackCommitSize Condition="'$(mk_is_release)'=='true'">1048576</StackCommitSize>
			<LargeAddressAware>true</LargeAddressAware>
			<TerminalServerAware>true</TerminalServerAware>
			<SwapRunFromCD>true</SwapRunFromCD>
			<SwapRunFromNET>true</SwapRunFromNET>
			<Driver></Driver>
		</Link>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup>
		<Link>
			<OptimizeReferences Condition="'$(mk_is_debug)'=='true'">true</OptimizeReferences>
			<OptimizeReferences Condition="'$(mk_is_release)'=='true'">true</OptimizeReferences>
			<EnableCOMDATFolding Condition="'$(mk_is_debug)'=='true'">true</EnableCOMDATFolding>
			<EnableCOMDATFolding Condition="'$(mk_is_release)'=='true'">true</EnableCOMDATFolding>
			<FunctionOrder></FunctionOrder>
			<ProfileGuidedDatabase>$(OutDir)$(TargetName).pgd</ProfileGuidedDatabase>
			<LinkTimeCodeGeneration Condition="'$(mk_is_debug)'=='true'">Default</LinkTimeCodeGeneration>
			<LinkTimeCodeGeneration Condition="'$(mk_is_release)'=='true'">UseLinkTimeCodeGeneration</LinkTimeCodeGeneration>
			<LinkTimeCodeGenerationObjectFile>$(IntDir)$(TargetName).iobj</LinkTimeCodeGenerationObjectFile>
		</Link>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup>
		<Link>
			<MidlCommandFile></MidlCommandFile>
			<IgnoreEmbeddedIDL>false</IgnoreEmbeddedIDL>
			<MergedIDLBaseFileName></MergedIDLBaseFileName>
			<TypeLibraryFile></TypeLibraryFile>
			<TypeLibraryResourceID>1</TypeLibraryResourceID>
		</Link>
	</ItemDefinitionGroup>



	<ItemDefinitionGroup>
		<Link>
			<EntryPointSymbol Condition="'$(mk_is_entry_point)'=='true'">mk_lang_entry_point</EntryPointSymbol>
			<ImageHasSafeExceptionHandlers Condition="'$(Configuration)|$(Platform)'=='ReleaseMSVC|Win32'">false</ImageHasSafeExceptionHandlers>
			<AdditionalOptions>/ignore:4006 %(AdditionalOptions)</AdditionalOptions><!-- warning LNK4006: xxx already defined in xxx.obj; second definition ignored -->
			<AdditionalOptions>/ignore:4302 %(AdditionalOptions)</AdditionalOptions><!-- warning LNK4302: please add '/DEBUG' to the link command line for better ASAN error reporting -->
		</Link>
	</ItemDefinitionGroup>
</Project>
