bash build_run_lnx_c.sh double_analyzer 89
bash build_run_lnx_c.sh float_analyzer 89
bash build_run_lnx_c.sh mkcc 89
bash build_run_lnx_c.sh mkcf 89
bash build_run_lnx_c.sh mkcfct 89
bash build_run_lnx_c.sh mkcflt 89
bash build_run_lnx_c.sh mkch 89
bash build_run_lnx_c.sh mkci 89
bash build_run_lnx_c.sh mkct 89
bash build_run_lnx_c.sh mkvc 89
bash build_run_lnx_c.sh quad_analyzer 89

bash build_run_lnx_c.sh double_analyzer 99
bash build_run_lnx_c.sh float_analyzer 99
bash build_run_lnx_c.sh mkcc 99
bash build_run_lnx_c.sh mkcf 99
bash build_run_lnx_c.sh mkcfct 99
bash build_run_lnx_c.sh mkcflt 99
bash build_run_lnx_c.sh mkch 99
bash build_run_lnx_c.sh mkci 99
bash build_run_lnx_c.sh mkct 99
bash build_run_lnx_c.sh mkvc 99
bash build_run_lnx_c.sh quad_analyzer 99

bash build_run_lnx_c.sh double_analyzer 11
bash build_run_lnx_c.sh float_analyzer 11
bash build_run_lnx_c.sh mkcc 11
bash build_run_lnx_c.sh mkcf 11
bash build_run_lnx_c.sh mkcfct 11
bash build_run_lnx_c.sh mkcflt 11
bash build_run_lnx_c.sh mkch 11
bash build_run_lnx_c.sh mkci 11
bash build_run_lnx_c.sh mkct 11
bash build_run_lnx_c.sh mkvc 11
bash build_run_lnx_c.sh quad_analyzer 11

bash build_run_lnx_c.sh double_analyzer 18
bash build_run_lnx_c.sh float_analyzer 18
bash build_run_lnx_c.sh mkcc 18
bash build_run_lnx_c.sh mkcf 18
bash build_run_lnx_c.sh mkcfct 18
bash build_run_lnx_c.sh mkcflt 18
bash build_run_lnx_c.sh mkch 18
bash build_run_lnx_c.sh mkci 18
bash build_run_lnx_c.sh mkct 18
bash build_run_lnx_c.sh mkvc 18
bash build_run_lnx_c.sh quad_analyzer 18

bash build_run_lnx_cpp.sh double_analyzer 98
bash build_run_lnx_cpp.sh float_analyzer 98
bash build_run_lnx_cpp.sh mkcc 98
bash build_run_lnx_cpp.sh mkcf 98
bash build_run_lnx_cpp.sh mkcfct 98
bash build_run_lnx_cpp.sh mkcflt 98
bash build_run_lnx_cpp.sh mkch 98
bash build_run_lnx_cpp.sh mkci 98
bash build_run_lnx_cpp.sh mkct 98
bash build_run_lnx_cpp.sh mkvc 98
bash build_run_lnx_cpp.sh quad_analyzer 98

bash build_run_lnx_cpp.sh double_analyzer 11
bash build_run_lnx_cpp.sh float_analyzer 11
bash build_run_lnx_cpp.sh mkcc 11
bash build_run_lnx_cpp.sh mkcf 11
bash build_run_lnx_cpp.sh mkcfct 11
bash build_run_lnx_cpp.sh mkcflt 11
bash build_run_lnx_cpp.sh mkch 11
bash build_run_lnx_cpp.sh mkci 11
bash build_run_lnx_cpp.sh mkct 11
bash build_run_lnx_cpp.sh mkvc 11
bash build_run_lnx_cpp.sh quad_analyzer 11

bash build_run_lnx_cpp.sh double_analyzer 14
bash build_run_lnx_cpp.sh float_analyzer 14
bash build_run_lnx_cpp.sh mkcc 14
bash build_run_lnx_cpp.sh mkcf 14
bash build_run_lnx_cpp.sh mkcfct 14
bash build_run_lnx_cpp.sh mkcflt 14
bash build_run_lnx_cpp.sh mkch 14
bash build_run_lnx_cpp.sh mkci 14
bash build_run_lnx_cpp.sh mkct 14
bash build_run_lnx_cpp.sh mkvc 14
bash build_run_lnx_cpp.sh quad_analyzer 14

bash build_run_lnx_cpp.sh double_analyzer 17
bash build_run_lnx_cpp.sh float_analyzer 17
bash build_run_lnx_cpp.sh mkcc 17
bash build_run_lnx_cpp.sh mkcf 17
bash build_run_lnx_cpp.sh mkcfct 17
bash build_run_lnx_cpp.sh mkcflt 17
bash build_run_lnx_cpp.sh mkch 17
bash build_run_lnx_cpp.sh mkci 17
bash build_run_lnx_cpp.sh mkct 17
bash build_run_lnx_cpp.sh mkvc 17
bash build_run_lnx_cpp.sh quad_analyzer 17

bash build_run_lnx_cpp.sh double_analyzer 20
bash build_run_lnx_cpp.sh float_analyzer 20
bash build_run_lnx_cpp.sh mkcc 20
bash build_run_lnx_cpp.sh mkcf 20
bash build_run_lnx_cpp.sh mkcfct 20
bash build_run_lnx_cpp.sh mkcflt 20
bash build_run_lnx_cpp.sh mkch 20
bash build_run_lnx_cpp.sh mkci 20
bash build_run_lnx_cpp.sh mkct 20
bash build_run_lnx_cpp.sh mkvc 20
bash build_run_lnx_cpp.sh quad_analyzer 20

bash build_run_lnx_cpp.sh double_analyzer 23
bash build_run_lnx_cpp.sh float_analyzer 23
bash build_run_lnx_cpp.sh mkcc 23
bash build_run_lnx_cpp.sh mkcf 23
bash build_run_lnx_cpp.sh mkcfct 23
bash build_run_lnx_cpp.sh mkcflt 23
bash build_run_lnx_cpp.sh mkch 23
bash build_run_lnx_cpp.sh mkci 23
bash build_run_lnx_cpp.sh mkct 23
bash build_run_lnx_cpp.sh mkvc 23
bash build_run_lnx_cpp.sh quad_analyzer 23

