"on": "push"
"jobs":
  "build_run_win":
    "strategy":
      "matrix":
        "proj": ["mk_clib_hasher", "mk_clib_hosts", "mk_clib_info", "mk_clib_test"]
        "conf": ["DebugMSVC", "ReleaseMSVC"]
        "plat": ["x86", "x64"]
    "runs-on": "windows-latest"
    "steps":
      - "uses": "actions/checkout@main"
      - "run": "cmd.exe /c .github\\workflows\\build_run_win.bat ${{matrix.conf}} ${{matrix.plat}} ${{matrix.proj}}"
      - "uses": "actions/upload-artifact@main"
        "with":
          "name": "${{matrix.proj}}-${{matrix.conf}}-${{matrix.plat}}.exe"
          "path": "${{matrix.proj}}-${{matrix.conf}}-${{matrix.plat}}.exe"
      - "uses": "actions/upload-artifact@main"
        "with":
          "name": "${{matrix.proj}}-${{matrix.conf}}-${{matrix.plat}}.pdb"
          "path": "${{matrix.proj}}-${{matrix.conf}}-${{matrix.plat}}.pdb"
      - "uses": "actions/upload-artifact@main"
        "with":
          "name": "${{matrix.proj}}-${{matrix.conf}}-${{matrix.plat}}.txt"
          "path": "${{matrix.proj}}-${{matrix.conf}}-${{matrix.plat}}.txt"
  "build_wasm":
    "strategy":
      "matrix":
        "proj": ["mk_clib_float_analyzer_b128", "mk_clib_float_analyzer_b16", "mk_clib_float_analyzer_b32", "mk_clib_float_analyzer_b64", "mk_clib_hasher", "mk_clib_info"]
    "runs-on": "ubuntu-latest"
    "defaults":
      "run":
        "working-directory": "./mk_clib/projects/emscripten"
    "steps":
      - "uses": mymindstorm/setup-emsdk@v14
      - "uses": "actions/checkout@main"
      - "run": "bash ./../gcc/build_m4.bash"
      - "run": "bash ./${{matrix.proj}}.bash"
      - "uses": "actions/upload-artifact@main"
        "with":
          "name": "${{matrix.proj}}.wasm"
          "path": "./mk_clib/projects/emscripten/${{matrix.proj}}.wasm"
  "mk_clib":
    "runs-on": "ubuntu-latest"
    "needs": ["build_run_win", "build_wasm"]
    "steps":
      - "uses": "actions/download-artifact@main"
        "with":
          "merge-multiple": "true"
      - "uses": "actions/upload-artifact@main"
        "with":
          "name": "mk_clib"
          "path": "/home/runner/work/mk_clib/mk_clib/*"
