"on": "push"
"jobs":
  "build_wasm":
    "strategy":
      "matrix":
        "proj": ["mkch", "mkcc", "float_analyzer", "float_analyzer", "double_analyzer", "quad_analyzer"]
    "runs-on": "ubuntu-24.04"
    "defaults":
      "run":
        "working-directory": "./mk_clib/projects/emscripten"
    "steps":
      - "uses": mymindstorm/setup-emsdk@v13
      - "uses": "actions/checkout@main"
      - "run": "bash ./../gcc/build_m4.sh"
      - "run": "bash ./${{matrix.proj}}.sh"
      - "uses": "actions/upload-artifact@main"
        "with":
          "name": "${{matrix.proj}}.wasm"
          "path": "./mk_clib/projects/emscripten/${{matrix.proj}}.wasm"
  "mk_clib":
    "runs-on": "ubuntu-24.04"
    "needs": ["build_wasm"]
    "steps":
      - "uses": "actions/download-artifact@main"
        "with":
          "merge-multiple": "true"
      - "uses": "actions/upload-artifact@main"
        "with":
          "name": "mk_clib"
          "path": "/home/runner/work/mk_clib/mk_clib/*"
