"on": "push"
"jobs":
  "build_run_win_c":
    "strategy":
      "matrix":
        "proj": ["mkch", "mkci"]
    "runs-on": "windows-latest"
    "steps":
      - "uses": "actions/checkout@main"
      - "run": "dir"
      - "run": "devenv.com /?"
